### ISSUE TITLE
Invocation Groups not well-defined by the Vulkan specification.

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#1]
SPIR-V 1.00 R3 defines the concept of an `invocation group`. However, it only fully defines it for a compute operation (where it is defined as "a particular compute workgroup"). For other shader types, it is defined as a "graphical operation" which is further defined as:

>  implementation dependent, but at least as large as a single triangle
or patch, and at most as large as a single rendering command, as defined by the client API.

So the client API is supposed to fill in the details. But Vulkan never does. Or at least, not explicitly. I've read through Chapter 8, and the concept never comes up. Vulkan in fact never mentions the term "invocation group" at all (at least, as far as I can tell from doing a text search).

This is important because it's not clear what dynamically uniform means in some cases. Some examples:

* Is a value from a `flat` interpolated fragment shader input "dynamically uniform"? Well, if "invocation group" for fragment shaders is defined as the primitive, then it is dynamically uniform. If "invocation group" for fragment shaders is defined as the whole rendering command, then it is not.

* Is `InstanceIndex` dynamically uniform for Vertex Shaders? It could be, if "invocation group" were defined as the sequence of primitives within an instance, but it would not be if "invocation group for VS's were the whole rendering command.

* Are `patch` inputs to TES shaders dynamically uniform? If "invocation group" means all of the invocations that cover a patch, then it is. If it is defined as the whole rendering command, then it isn't.

* Are the input arrays to TCS shaders dynamically uniform? Again, if "invocation group" means all of the invocations that cover a patch, then it is. If it is defined as the whole rendering command, then it isn't.

Each shader stage definition in Chapter 8 should have an explicit paragraph stating how it defines "invocation group".

**Comment by oddhack** [comment]
We'll take this into the Vulkan working group for discussion and update this issue when we have a resolution.

**Comment by jeffbolznv** [comment]
We discussed this in the group, and we will provide a definition of an invocation group for graphics shaders but it will need to be the most conservative definition - one group per draw. Hardware often packs invocations from multiple primitives into a single hardware invocation group, and per-draw is the only safe boundary.

**Comment by NicolBolas** [comment]
I want to make sure I understand this resolution correctly.

If I use `InstanceIndex`, or a value derived from it, to select a sampler from an array of `SampledImage`s (directly or indirectly), and the draw call renders more than one instance, that is undefined behavior. Even in the fragment shader. Nor can I use it to select from an array of `Block`s or `BufferBlock`s.

This would seem to limit the usage of per-instance data substantially. You can use them in array textures and to access arrays of data fields in specific buffers. But you cannot use them to select which buffer/image you're accessing.

The above assumes that the Vulkan implementation supports dynamic indexing for blocks/images, of course.

**Comment by jeffbolznv** [comment]
That's correct. I know in the past, at least one IHV has said they pack invocations from multiple instances into a single invocation group.

FWIW, when we did https://www.opengl.org/registry/specs/ARB/shader_draw_parameters.txt we explicitly made gl_DrawIDARB dynamically uniform. So multidraws are a more flexible way to draw many objects and also support indexing across draws. Or at least they will, if/when that is added to Vulkan.

**Comment by NicolBolas** [comment]
I mentioned above that `InstanceIndex` was not dynamically uniform if you render multiple instances in the same draw call. But it _would be_ dynamically uniform if you submit only one instance in that draw call, yes?

Given that, what happens if you submit multiple "draws" via `vkCmdDraw[Indexed]Indirect`, each using one instance but each with different starting instances? Does the definition of "per draw" mean "per call to `vkCmdDraw*`" or is it "per draw within a `vkCmdDraw*` command"?

Also, excellent point about shader_draw_parameters. Though really, since Vulkan fixed OpenGL's issues with `gl_InstanceID`, the only thing we're missing is `gl_DrawIDARB`. And since Vulkan doesn't have a `vkCmdMultiDraw`, it would only make sense with indirect rendering.

Of course, you could always add multi-drawing functionality...

**Comment by jeffbolznv** [comment]
> Does the definition of "per draw" mean "per call to vkCmdDraw*" or is it "per draw within a vkCmdDraw* command"?

It means per draw within a multidraw. I've got this special case in the pending (private) merge request.

> But it would be dynamically uniform if you submit only one instance in that draw call, yes?

Yes, and more generally it is a "value" that is dynamically uniform or not a storage type or something like that. So for example, a value in a (vertex-rate) vertex attribute can be dynamically uniform if it happens to be the same value for all vertices in the draw. It doesn't have to come from a certain type of input like a uniform buffer.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.6 spec update.
