### ISSUE TITLE
vkGetInstanceProcAddr behavior missing

### ISSUE THREAD

**Issue by abergmeier** [KhronosGroup/Vulkan-Docs#1003]
I think this is missing the definition for:
- _instance_ + `vkEnumerateInstanceVersion` -> ?
- _instance_ + `vkEnumerateInstanceExtensionProperties` -> ?
- _instance_ + `vkEnumerateInstanceLayerProperties` -> ?
- _instance_ + `vkCreateInstance` -> ?

**Comment by krOoze** [comment]
> instance | * (any pName not covered above) | NULL
> -- | -- | --

**Comment by abergmeier** [comment]
To me as a non-native speaker it is at best ambiguous whether these 4 values are included in `(any pName not covered above)`.

**Comment by krOoze** [comment]
OK, what about PR #1004 ([html](http://vulkan.hys.cz/pr1004/vkspec.html#initialization-functionpointers))

**Comment by abergmeier** [comment]
That clears it up!
Thanks
