### ISSUE TITLE
Inconsistent description of VK_ACCESS_MEMORY_*_BIT wrt host

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1007]
In description of access mask it says:

> `VK_ACCESS_MEMORY_READ_BIT` specifies read access via non-specific entities. These entities include the Vulkan device **and host**, but **may** also include entities external to the Vulkan device or otherwise not part of the core Vulkan pipeline.

But in specific parts describing visibility it says you need `VK_ACCESS_HOST_*_BIT` explicitly. E.g. most importantly:

> If the destination access mask includes `VK_ACCESS_HOST_READ_BIT` or `VK_ACCESS_HOST_WRITE_BIT`, then the dependency includes a memory domain operation from device domain to host domain.

**Comment by Tobski** [comment]
The "MEMORY_READ" and "MEMORY_WRITE" bits are supposed to be a catch-all for "every other applicable access bit"; but it's not written like that, which I guess has led to this inconsistency. I will attempt to fix this.
