### ISSUE TITLE
vk.xml is invalid

### ISSUE THREAD

**Issue by ThuCommix** [KhronosGroup/Vulkan-Docs#1008]
Since the latest changes on the vk.xml its no longer valid.

The value of attribute "contact" associated with an element type "extension" must not contain the '<' character.

Commit: 355950cc0dd4ff94424fedfc1719a2c138c80eb3

**Comment by oddhack** [comment]
It will get fixed in the next spec update over the weekend.

**Comment by oddhack** [comment]
This was fixed in the 1.1.117 spec update (I neglected to add a ChangeLog comment but it's a trivial fix).
