### ISSUE TITLE
VK_EXT_buffer_device_address revision history not updated

### ISSUE THREAD

**Issue by WoodRain** [KhronosGroup/Vulkan-Docs#1009]
Hi @jeffbolznv From [git blame info of VK_EXT_buffer_device_address](https://github.com/KhronosGroup/Vulkan-Docs/blame/master/appendices/VK_EXT_buffer_device_address.txt), the struct name is changed, but the revision number and revision history is not changed accordingly.
By the way, why not changing VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BUFFER_ADDRESS_FEATURES_EXT to VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BUFFER_DEVICE_ADDRESS_FEATURES_EXT in the initial version. It seems more suitable together with VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_INFO_EXT.

**Comment by jeffbolznv** [comment]
We've done several of these structure renames recently for consistency, but they're backward compatible and we haven't changed the version numbers for any of them.

> By the way, why not changing VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BUFFER_ADDRESS_FEATURES_EXT to VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BUFFER_DEVICE_ADDRESS_FEATURES_EXT in the initial version.

I don't understand the question. We did this rename, what's missing?

**Comment by oddhack** [comment]
If I'm following the question, the answer is that we just didn't catch the inconsistency before the extension shipped.

**Comment by WoodRain** [comment]
Well, I mean the naming changes may be recorded in the spec to avoid some sort of confusion. And people had a look at the earlier editions of those names can still find those in the new spec :)

**Comment by oddhack** [comment]
@WoodRain want to propose a PR suggesting what you would like to see here? Probably something in the Issues section of the appendix would be most appropriate.

**Comment by WoodRain** [comment]
Got it. A PR is issued as #1024 .
