### ISSUE TITLE
Editorial issues (section 23-C)

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#101]
Some other smallish things.

Section numbers based on https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html version 1.0.4.

#### 23.5

> Multiple viewports are available and are numbered zero up to the value of VkPhysicalDeviceLimits::maxViewports.

Should be "...maxViewports minus one, inclusive."

#### 24

VkPipelineRasterizationStateCreateInfo says:

> If the non-solid fill modes feature is not enabled, the value of fillMode must be VK_POLYGON_MODE_FILL

Should be polygonMode, not fillMode.

#### 24.3

> minSampleShading must be in the range [0,1].

I think this ought to be in the "Valid Usage" section of VkPipelineMultisampleStateCreateInfo, because that's where that kind of constraint is nearly always specified, instead of just in the prose much later on.

#### 24.5.1

In the "Non strict lines" diagram, it says "Ab, Yb, Zb". I think it should be "Xb, Yb, Zb".

#### 24.6.1

>     typedef enum VkCullModeFlagBits {
>         VK_CULL_MODE_NONE = 0,
>         VK_CULL_MODE_FRONT_BIT = 0x00000001,
>         VK_CULL_MODE_BACK_BIT = 0x00000002,
>         VK_CULL_MODE_FRONT_AND_BACK = 0x3,
>     } VkCullModeFlagBits;

That should be 0x00000003 for consistency with all the other hex enum values.

Same with

>         VK_STENCIL_FRONT_AND_BACK = 0x3,

#### 29.1

https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#VkLayerProperties

VkLayerProperties says:

> * layerName is a null-terminated string specifying the name of the layer. Use this name in the ppEnabledLayerNames array in the VkInstanceCreateInfo given to vkCreateInstance to enable this layer in the instance.

This can equally be used in ppEnabledLayerNames in VkDeviceCreateInfo given to vkCreateDevice, so it should probably mention that too.

#### 29.1

https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#VkLayerProperties

VkLayerProperties says:

> * layerName is a null-terminated string specifying the name of the layer. [...]
> * description is a null-terminated string providing additional details that can be used by the application to identify the layer.

These should state that they're UTF-8 encoded strings. (The other functions that consume layer names are explicit about UTF-8, and descriptions should be UTF-8 for consistency and sanity.)

#### 29.2

https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#extended-functionality-extensions

vkEnumerateInstanceExtensionProperties says:

> * If pLayerName is not NULL, it must be the name of a layer available on the system

vkEnumerateDeviceExtensionProperties says:

> * If pLayerName is not NULL, it must be the name of a layer available on the system

I think these should say "must be the name of a (instance|device) layer available on the system" - passing the wrong type of layer sounds like it ought to be an error.

Also, instead of the vague phrase "available on the system", maybe it would be clearer to say "returned by vkEnumerate(Instance|Device)LayerProperties" (unless you're meant to be able to use some external knowledge about layer names without enumerating them?)

#### 29.2

https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#extended-functionality-extensions

vkEnumerateInstanceExtensionProperties, vkEnumerateDeviceExtensionProperties say:

> Any (instance|device) extensions provided by the Vulkan implementation or by implicitly enabled layers, but not by explicitly enabled layers, are returned when pLayerName parameter is NULL.

What are the "explicitly enabled layers" here? We can call vkEnumerate* before vkCreateInstance/vkCreateDevice, so there won't have been any opportunity to have explicitly enabled any.

If there *were* some explicitly enabled layers, it'd be unclear whether a layer that was both implicitly and explicitly enabled should be included or not.

I think saying "..., but not by any other layers available on the system" would be better.

#### 30.2

https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#features-limits

features.txt says:

>     1::
>         For all bitmasks of type elink:VkSampleCountFlags above, the bits which
>         can: be set include:
>     +
>     include::../enums/VkSampleCountFlagBits.txt[]
>     +
>     The sample count limits defined above represent the minimum

which the HTML version renders with a visible "+" character before "The sample count limits".

#### 30.2.1

https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#features-limits-required

> sparseAddressSpaceSize ___ 0 ___ 2 GB ____ min

"2 GB" isn't really an integer, so this lacks dimensional consistency. It's also ambiguous whether "GB" means 2*10^9 or 2^31 bytes. It'd be better to just write "2^31" here.

#### 30.3.3

https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#id-1.32.5.5.4 defines the symbols "•" and "∘".

Those two symbols look extremely similar to me - they're both tiny circles, one with a few extra white pixels in the middle. They should be changed to much more distinctive symbols. (They're okay in the PDF, it's just the HTML that's hard to see.)

#### 30.3.3

https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#id-1.32.5.5.4 says the "∘" symbol means "This feature must be supported on at least some of the named formats, with more information below".

https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#features-formats-mandatory-features-bcn and the other compressed-format tables use that symbol, but don't give any more information below. They give the information above the tables instead (directly adjacent to other information which is below the previous table).

#### C.3

> For example, a layer written by the owner of www.3dxcl.com would use the prefix VK_LAYER_com_3dxcl_www_.

Referencing an apparently unregistered domain seems dangerous - some spammer is sure to buy it and get millions of hits from curious spec readers.

> Layer authors that prefer not to register an author prefix can instead use a fully-qualified domain name (FQDN) in reverse-order as an author prefix, using all lower-case characters, [...] FQDNs must be encoded in UTF-8.

The UTF-8 encoding implies that these can be non-ASCII. In that case, what does "lower-case" mean? (Unicode makes it a non-trivial question.)

I guess you'd want something equivalent to the lowercasing in https://tools.ietf.org/html/rfc5895 so that you'd end up with an equivalent domain name, but I'm not familiar with the precise details.

Or I guess you could be sensible and say "it totally doesn't matter, nobody's really going to use an uppercase Cherokee name like VK_com_ᎤᎵᎮᎵᏍᏗ_ and force us to worry about whether that's valid given that lowercase Cherokee syllabic characters were added in Unicode 8.0 (with abnormal case folding rules) but RFC5895 only uses Unicode 5.2, so stop wasting everyone's time".

(Of course even "3dxcl" is not "all lower-case characters", because "3" has no case...)

#### C.4

> Where ExtensionAuthorPrefix is equal to that of the prefixes defined above for extension names with the exception that a leading _ (underscore) is added for non-Khronos extensions.
> [...]
> A Google extension could expose the following command:
>
>     void vkDoSomethingGOOGLE(void);

That example is a non-Khronos extension but doesn't have the leading underscore.

> Extensions may add new [...] tokens, and types [...]. These names shall conform to the following template:
>
>     vk<CommandName><ExtensionAuthorPrefix>
>
> [...]
>
>     enum VkSomeValuesGRPHX {
>         VK_SOME_VALUE_0_GRPHX = 0,
>         VK_SOME_VALUE_1_GRPHX = 1,
>         VK_SOME_VALUE_2_GRPHX = 2,
>     };

Those tokens and types don't follow that template.

**Comment by oddhack** [comment]
I'm taking the issues I didn't propose fixes for in #105 inside the Vulkan WG for further discussion.

**Comment by oddhack** [comment]
Partly fixed in the 1.0.5 spec update. Issues still being worked internally:

- [ ] 24.5.1 "Ab, Yb, Zb" -> "Xb, Yb, Zb"
- [ ] 29.2 "explicitly enabled layers" clarification
- [ ] 30.3.3 Confusingly similar tiny circle symbols in format tables
- [ ] 30.3.3 Missing information about some formats
- [ ] C.3 Clarify lower-case UTF-8 in FQDN layer names

**Comment by oddhack** [comment]
Should be fixed in the 1.0.6 spec update. Please open a new issue if we missed anything.
