### ISSUE TITLE
Multisample storage images?

### ISSUE THREAD

**Issue by procedural** [KhronosGroup/Vulkan-Docs#1015]
DXC states there is "no such thing" as `RWTexture2DMS*` (multisample storage images in D3D lingo): 

[indexing-operator_Mod.hlsl](https://github.com/microsoft/DirectXShaderCompiler/blob/83c1bf8/tools/clang/test/CodeGenHLSL/batch/misc/indexing-operator_Mod.hlsl)
[indexing-operator_noerr.hlsl](https://github.com/microsoft/DirectXShaderCompiler/blob/83c1bf8/tools/clang/test/HLSL/rewriter/indexing-operator_noerr.hlsl)
[indexing-operator.hlsl](https://github.com/microsoft/DirectXShaderCompiler/blob/83c1bf8/tools/clang/test/HLSL/indexing-operator.hlsl)

```
// No such thing as these:
// RWTexture2DMS g_rw_t2dms;
// RWTexture2DMSArray g_rw_t2dmsa;
```

Are multisample storage images supported in SPIR-V and not in DXC? Validation layers currently don't report an error when both `VK_IMAGE_USAGE_STORAGE_BIT` and a sample flag other than `VK_SAMPLE_COUNT_1_BIT` are specified for an image, is this valid?

**Comment by critsec** [comment]
Multisample storage images are an optional feature in Vulkan; support is indicated/enabled with  VkPhysicalDeviceFeatures::shaderStorageImageMultisample. When enabled, SPIR-V shader modules can declare the StorageImageMultisample capability, can declare OpTypeImage with Sampled=2 (storage image) and MS=1 (multisample), and can pass a Sample operand to OpImageRead and OpImageWrite to read/write a specific sample.

In GLSL this is available by declaring a image2DMS object and passing an extra int coordinate to imageLoad()/imageStore() to access a specific sample.

**Comment by procedural** [comment]
@critsec Interesting, thanks for the details! So it looks like DXC doesn't support it because D3D12 doesn't support it, or something like that.

Either way, Vulkan is fine here, so closing.
