### ISSUE TITLE
Missing structextends for VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Docs#1018]
The recently introduced ```VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR``` is missing struct extension information:

```xml
    <type category="struct" name="VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR">
        <member values="VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PIPELINE_EXECUTABLE_PROPERTIES_FEATURES_KHR"><type>VkStructureType</type> <name>sType</name></member>
        <member><type>void</type>*              <name>pNext</name></member>
        <member><type>VkBool32</type>           <name>pipelineExecutableInfo</name></member>
    </type>
```

To my knowledge it's missing a ```structextends="VkPhysicalDeviceFeatures2,VkDeviceCreateInfo"```.

Nothing major, but I'm currently working on some tooling to extract extension related information and structures from the xml spec and I'm using the data from ```structextends``` to decide if I need to fetch that type.

**Comment by oddhack** [comment]
This should be fixed in the 1.1.121 spec update.
