### ISSUE TITLE
Inconsistent if Ray Tracing allowed inside renderpass scope

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1021]
@ewerness
`vkCmdTraceRaysNV` and `vkCmdBuildAccelerationStructureNV` say:

> Render Pass Scope: Both

Ray tracing extension defines `VK_PIPELINE_BIND_POINT_RAY_TRACING_NV`.

But render pass creation VU says:

> `pipelineBindPoint` **must** be `VK_PIPELINE_BIND_POINT_GRAPHICS`

So is it allowed inside render pass or not?

On the other hand `vkCmdTraceRaysNV` is missing VUs restricting the `pipelineBindPoint` of the subpass it is recorded in.

If it is allowed, it is not clear if `vkCmdProcessCommandsNVX`, conditional rendering, and fragment density is also allowed in a ray tracing subpass.

**Comment by dgkoch** [comment]
Ray tracing commands are supposed to be outside renderpass scope. 
Will clarify this in the next update.

**Comment by oddhack** [comment]
This should be fixed in the 1.1.121 spec update.
