### ISSUE TITLE
vkCmdBindPipeline missing pipelineBindPoint restriction if inside render pass

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1022]
`vkCmdBindPipeline`'s `pipelineBindPoint` should match `VkSubpassDescription::pipelineBindPoint`?

**Comment by Tobski** [comment]
Hey @krOoze we usually have fairly loose requirements on state setting commands - if we added this restriction it would be a breaking change and it'd be inconsistent with other behaviours. However it is _somewhat_ nonsensical - possibly an option would be to raise it as a potential warning for the validation layers to pick up on?

**Comment by Tobski** [comment]
In an effort to get through stuff that's assigned to me I'm going to close this issue as it's resolved from a spec standpoint AFAICT, but feel free to re-open or raise a new issue if you have further questions.

**Comment by krOoze** [comment]
> However it is somewhat nonsensical - possibly an option would be to raise it as a potential warning for the validation layers to pick up on?

Probably.

Specifically. in secondary command buffer with `VK_COMMAND_BUFFER_USAGE_RENDER_PASS_CONTINUE_BIT` the `vkCmdBindPipeline` to a wrong bind point would be a noop, right?
