### ISSUE TITLE
VK_EXT_validation_flags and VK_EXT_validation_features issues

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1025]
1) I don't see significant difference between `VkValidationFeatureDisableEXT` and `VkValidationFlagsEXT` to warrant existence of both extensions.
2) Apparently flag Bits are added over time there, but VU requires valid values. Would it make sense instead that Bits outside range are ignored?
3) The extensions are tied to Validation Layers, and only to subset of their config. It is reasonable to want to configure (all) layers, and all settings. Would something more generic make more sense? E.g.:
```
struct VkLayerConfig{
    const char* layer;
    uint32_t settingCount;
    const char*const* settings;
    const char*const* values;
};
```

**Comment by mark-lunarg** [comment]
`VK_EXT_validation_flags` is to be deprecated.  The current method for configuring layer-specific information is through the `vk_layer_settings.txt` file, which can be used for settings which do not need to be formalized in the specification.  For the Khronos Validation Layer, it seem valuable to formalize those controls using the `VK_EXT_validation `features extension.

**Comment by krOoze** [comment]
4. Which setting has priority? The `vk_layer_settings.txt` or the programatic one? If feature is not in `pDisabledValidationFeatures`, does it mean "enabled", or "default"? Spec says "This feature is enabled by default." But it might not be accounting for the file settings...
5. Does `VK_VALIDATION_FEATURE_DISABLE_SHADERS_EXT` imply disabled "GPU assisted" validation?

**Comment by mark-lunarg** [comment]
Features in DisabledValidationFeatures are 'On' if no setting changes them, and vice-versa with the EnabledValidationFeatures.  Obviously, some combinations of enables/disables would not make sense. 

GPU-Assisted validation will be moved out of core_validation in the near future, and would then be unaffected by the shader-validation disable.  There is a bunch of work on the `VkConfig `utility to make this more clear and useful, and hopefully during that effort we can better define issues of priority.

There is now a Vulkan spec issue/merge request pending which will deprecate `VK_EXT_validation_flags`, thanks again for bringing this up.

**Comment by mikew-lunarg** [comment]
@krOoze please close this issue if complete.

**Comment by krOoze** [comment]
What about nr. 2?
Would it make sense for flags to be ignored? Otherwise app has to check extension version, which is annoying. Or are the flag bits expected to be fixed from now on?

**Comment by mark-lunarg** [comment]
@krOoze, not sure I'm interpreting this correctly, but the intent is that flags will not change, though new bits may be added.  So hopefully there won't be any unknown flags (assuming a current set of validation is being used).
