### ISSUE TITLE
Valid usage condition of pAllocateInfo->allocationSize, vkAllocateMemory

### ISSUE THREAD

**Issue by motangish** [KhronosGroup/Vulkan-Docs#1032]
One of the valid usage conditions of vkAllocateMemory is defined as
> pAllocateInfo->allocationSize must be less than or equal to VkPhysicalDeviceMemoryProperties::memoryHeaps[pAllocateInfo->memoryTypeIndex].size as returned by vkGetPhysicalDeviceMemoryProperties for the VkPhysicalDevice that device was created from.

But
> memoryTypeIndex is an index identifying a memory type from the memoryTypes array of the VkPhysicalDeviceMemoryProperties structure

> heapIndex describes which memory heap this memory type corresponds to, and must be less than memoryHeapCount from the VkPhysicalDeviceMemoryProperties structure.

Therefore
`pAllocateInfo->allocationSize` must be less than or equal to `VkPhysicalDeviceMemoryProperties::memoryHeaps[VkPhysicalDeviceMemoryProperties::memoryTypes[pAllocateInfo->memoryTypeIndex].heapIndex].size`

**Comment by oddhack** [comment]
Agreed - we'll correct this in an upcoming spec update.

**Comment by oddhack** [comment]
This should be fixed in the 1.1.128 spec update.
