### ISSUE TITLE
Vulkan prohibits 2D (array) view of 3D images bound to descriptors even with VK_IMAGE_VIEW_TYPE_2D_ARRAY

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-Docs#1033]
`VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT` allows 2D and 2D array views for 3D images. However, validation language for `VkDescriptorImageInfo` says that:

> imageView must not be 2D or 2D array image view created from a 3D image

Is this an error? Was this meant to say "unless `VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT`"?

---

This is unlike GL where `glBindImageTexture` could be used to bind a layer of a 3D texture to an `image2D` in the shader.

**Comment by null77** [comment]
Thanks for filing Shabi. ANGLE could consider emulating this functionality. It would potentially involve patching the shaders we feed to glslang at draw-call time when we detect this incompatibility. But if it's fairly trivial for drivers to support the functionality an extension or something like that would help.

**Comment by null77** [comment]
@courtney-g @tobine fyi

**Comment by ShabbyX** [comment]
Note that on Nvidia at least, it looks like ignoring the validation error allows tests to use individual layers of the 3d texture as image2D anyway. This further strengthens the assumption that this OpenGL functionality is very likely already ubiquitously available.

**Comment by jeffbolznv** [comment]
The working group discussed this today, and there is some hardware where making this work would require either reallocating images under the hood, or switching shaders based on bound resources (or something like that). So we would rather that work be done by the emulation layer.
