### ISSUE TITLE
How to use semaphore to sync queue ownership transfer?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1036]
For queue ownership transfer it is written:

>`dstStageMask` is ignored [for release barrier]

> The release operation happens-after the availability operation.

> `srcStageMask` is ignored [for acquire barrier]

> The acquire operation happens-before the visibility operation.

> An application **must** ensure that these operations [release op and acquire op] occur in the correct order by defining an execution dependency between them, e.g. using a semaphore.

Given this, it is non-obvious how would I be able to ensure it with a semaphore. What `pWaitDstStageMask` would I have to use?

`srcStageMask` is ignored, so it cannot be chained. Besides acquire operation does not say what it happens-after, so it is fundamentally unclear how it would be possible to order it after something else in any way.

**Comment by Tobski** [comment]
This is a weird and good point. A full semaphore will definitely do the right thing here (i.e. `pWaitDstStageMask[*] = VK_PIPELINE_STAGE_ALL_COMMANDS_BIT`), but I don't believe that's intended to be necessary. The "is ignored" part is rather gross.

The original intent was that it's not supposed to be guaranteeing where (or if) any possible operation occurs, but that's kind of just confused things... it would be much neater to have language like the layout transition language which just states that it _does_ happen, and the rules for that.

I think I'll have to take a look at this language in greater detail when I get a spare minute, but agree this needs improvement.

**Comment by Tobski** [comment]
Ok this actually seems like a fairly straightforward fix - it's supposed to be the **Access** masks that are ignored, not the stage masks. Whoops.

**Comment by krOoze** [comment]
It is still unclear how to order release op and acquire op. The spec does not say what the release op happens-before, and the acquire op happens-after. So they are unorderable. But the spec still requires the app to order them.

**Comment by Tobski** [comment]
Right, there should be something saying that the release and acquire op happen within the relevant stages as per other sync operations. I'll clarify this.

> PS: May I assume now srcStageMask and dstStageMask behave exactly the same as for regular barrier? E.g. if the release barrier was merged with some normal barriers, it would still behave as expected?

Yep.

**Comment by devshgraphicsprogramming** [comment]
This is basically the same problem as in  my issue #2319 

The spec should have a clear discussion of this use case and what to set the stage masks to + how to signal/await the semaphores in one of those extra-information sections.

**Comment by krOoze** [comment]
The issue here I believe was the spec mistakenly said the stages are ignored instead of the access flags. And that the specification didn't say where the release and acquire op happen.

Both seem to have been addressed. Now the access flags are ignored. The stages are **not** ignored and work as usual. The release and acquire ops happen with relations to these stage flags specified in the barrier.
