### ISSUE TITLE
Why not make this information into a database?

### ISSUE THREAD

**Issue by gchihiha** [KhronosGroup/Vulkan-Docs#1037]
Why not make this information into a database? Or is there actually a database, but it is not public?

**Comment by oddhack** [comment]
Which information?

**Comment by gchihiha** [comment]
vk.xml

**Comment by oddhack** [comment]
It's already in a structured machine-readable format with a defined schema. You can search XML with tools supporting XPath, if searching is what you need. I'm unclear what value putting the same information into a different database schema would have?

**Comment by gchihiha** [comment]
fine
