### ISSUE TITLE
 vkCreateSwapchainKHR fails randomly with NVidia if CS_OWNDC is not specified

### ISSUE THREAD

**Issue by cos-public** [KhronosGroup/Vulkan-Docs#1039]
Not sure if it's a specification or a driver implementation bug, but vkCreateSwapchainKHR fails with with VK_ERROR_INITIALIZATION_FAILED on a newly created window.
The test consisted of a simple loop where I created a window, initalized a swapchain and then immediately destroyed a window (all resources are nicely RAII managed).
It fails with about 30% chance if windowClass = CS_PARENTDC (on a 2nd-10th iteration of a loop) and 5% chance (on a 15th-30th iteration of a loop) if windowClass = 0, and doesn't fail at all if windowClass = CS_OWNDC.
It fails with the following hardware configuration: Intel 620 primary GPU (running a Desktop Manager) and nVidia GTX 1050 secondary GPU (Microsoft Surface Book 2). Vulkan device is GTX 1050. OS: Windows 10 Pro 17763. Driver versions tested: 436.30, 431.86.

It never fails with either class=CS_PARENTDC or class=0 on a desktop PC with a single GTX 1080Ti GPU, driver version 436.02.

In-depth debugging suggests that it fails somewhere near the GetPixelFormat() / wglGetPixelFormat() win api call.

May be related with #511

**Comment by pdaniell-nv** [comment]
@cos-public Do you have a simple repro we can run to reproduce the issue locally? Thanks.

**Comment by jjulianoatnv** [comment]
Thank you for the issue report.

My guess is that you are correct about it being related to #511. Khronos has yet to adequately document requirements on the win32 platform that are discussed in that issue. Your new issue 1039 is a good reminder to Khronos to write such documentation.

If this is due to something else then we probably do need a repro app to characterize what's actually going on.

**Comment by cos-public** [comment]
Please find the minimal repro app here https://github.com/cos-public/vulkan_wnd_test

**Comment by krOoze** [comment]
^ FWIW works for me on a desktop NVIDIA 436.48.

**Comment by pdaniell-nv** [comment]
Works for me too on a Razer Blade RTX 2070. I see:
classStyle = CS_OWNDC test passed
classStyle = 0 test passed
classStyle = CS_PARENTDC test passed

I tried several times.

**Comment by cos-public** [comment]
I've tried many different configurations with a single GPU. And all work fine. The problem is just with my Microsoft Surface Book 2 configuration with two GPUs, when Vulkan is running on a secondary GTX 1050 GPU. Possibly it can be reproduced on a similar dual GPU configuration where NVidia is not running the Desktop Manager. May be the driver have to do some magic to transfer rendered surface back to the primary GPU for display output and CS_OWNDC class is needed in such case.

**Comment by cos-public** [comment]
I was able to reproduce this issue on a different machine: thinkpad X1 carbon with eGPU Akitio Node Thunderbolt 3 fitted with GTX 1080Ti.
Primary GPU: embedded Intel 620
Vulkan GPU: GTX 1080Ti; driver versions: 24.21.13.9924 (Windows stock driver), 436.48 (recent game-ready driver)

You could probably reproduce the issue, if you configure your Windows to use embedded Intel GPU, plug monitor to it and run the repro app on NVidia GPU (it would probably run on NVidia by default)

**Comment by pdaniell-nv** [comment]
I tried again on my Razer Blade RTX 2070, which has Intel UHD Graphics 630 and an RTX 2070 (TU106). I tried the following configurations:
1) Laptop monitor only
2) Laptop+HDMI monitors (Laptop master and HDMI master)
3) Laptop+Thunderbolt monitors (Laptop master and Thunderbolt master)

I wasn't able to get a repro. Can you attach your vulkaninfo to this issue?

**Comment by pdaniell-nv** [comment]
@cos-public are you still affected by this issue? If so, and considering this sounds like a vendor issue, perhaps report the bug here: https://devtalk.nvidia.com/.
