### ISSUE TITLE
DebugReportFn msgCode is alway zero.

### ISSUE THREAD

**Issue by rjklindsay** [KhronosGroup/Vulkan-Docs#1041]
Although validation layers are useful at times, they are also often wrong, and false positive error messages can quickly become a hindrance to Vulkan app development.

Rather than disable validation completely, I would like to disable individual error messages, when they are known to be incorrect. Obviously, I would use the debug report callback feature to do this.  Back when I worked at LunarG, the debug report callback returned a unique code for each error message type, in the msgCode field, so it was easy to identify and discard false positives.  

However, in newer versions of the validation layers, the msgCode always returns 0.
So, this code can no longer be used.  Was this feature removed intentionally, and if so, why?

So it seems, the only other way to identify a specific error message, is to do a string compare on the error message string.   Terrible terrible terrible!!!

Please fix the msgCode feature.

**Comment by mark-lunarg** [comment]
Please refer to [Vulkan-ValidationLayers issue #1160](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/1160) for the answer to this issue.

**Comment by rjklindsay** [comment]
Ok... string-compare it is. (Sigh)
