### ISSUE TITLE
type needs to be valid under what macro definition?

### ISSUE THREAD

**Issue by gchihiha** [KhronosGroup/Vulkan-Docs#1042]
Relying on the information in vk.xml, how can we know that a type needs to be valid under what macro definition?
vk.xml or reg.py or others file 
Would you like to tell me some useful information?

**Comment by krOoze** [comment]
I am not sure what you are asking, so you might want to restate your question.

`vk.xml` and the [schema](https://www.khronos.org/registry/vulkan/specs/1.1/registry.html) are the base documents. The *.py scripts are only xml consumers.

**Comment by oddhack** [comment]
Could you give a specific example related to your question? I am also unsure what you're asking. There is almost no interaction between C macros and the Vulkan types, aside from the macros which help define handle types.

**Comment by gchihiha** [comment]
for example:
enum VkFullScreenExclusiveEXT
in vk.xml:
![image](https://user-images.githubusercontent.com/25894997/66216338-e08a9580-e6f7-11e9-9bbf-c34218e63542.png)
in vulkan_win32.h
![image](https://user-images.githubusercontent.com/25894997/66216492-25163100-e6f8-11e9-97b5-9f5dad866a62.png)

How can I know that a type needs to be predefined VK_USE_PLATFORM_WIN32_KHR ??


PS:
use reg.py like this
`import reg
from lxml import etree
vk_xml_file_path = "./vk.xml"`
you know.

**Comment by gchihiha** [comment]
I want to do something better than vulkan-bind.
So I need to use vk.xml and reg.py to extract some useful information.

**Comment by krOoze** [comment]
Ah.

You know it like this:
`<extension name="VK_KHR_win32_surface" number="10" type="instance" requires="VK_KHR_surface" platform="win32" author="KHR" contact="Jesse Hall @critsec,Ian Elliott @ianelliottus" supported="vulkan">`.

Notice `platform="win32"`. Which is defined as `<platform name="win32" protect="VK_USE_PLATFORM_WIN32_KHR" comment="Microsoft Win32 API (also refers to Win64 apps)"/>`.

**Comment by gchihiha** [comment]
fine

**Comment by gchihiha** [comment]
fine
just like this? I will be the authoritative answer.
thank you and oddhack

**Comment by gchihiha** [comment]
fine
I will think of it as an authoritative answer.
thank you and oddhack

**Comment by oddhack** [comment]
You should also be aware that the partioning of the Vulkan core APIs and platform-specific APIs into different header files is driven by logic defined in genvk.py, not by data in the XML file. Specific extensions are defined to go into specific platform headers, which have the platform protections, and everything else into vulkan_core.h.
