### ISSUE TITLE
You can't change limits willy-nilly like that!

### ISSUE THREAD

**Issue by procedural** [KhronosGroup/Vulkan-Docs#1044]
Some people (like me) can rely on them!

For example:
> * Increase the maximum nonCoherentAtomSize value in the Required Limits section from 128 to 256 (internal issue 435).

Some people could rely on this, a potential program that relied on the max value of 128 can now be broken by a GPU with a value of 256 just because the spec guarantees were changed.

I hope all limit changes are logged and will continue to be logged in ChangeLog.txt.

If no one at Khronos cares about this, I will populate this issues with all the limit changes I can find.

**Comment by krOoze** [comment]
All changes to the spec are to some degree compatibility breaking. That cannot be avoided.

You assume your "potential program" is not already broken. What if the driver cannot honor the limit no matter what the spec says?

**Comment by procedural** [comment]
> All changes to the spec are to some degree compatibility breaking. That cannot be avoided.
> 
> You assume your "potential program" is not already broken. What if the driver cannot honor the limit no matter what the spec says?

Isn't it Khronos' job to answer this exact question.

**Comment by krOoze** [comment]
I guess. More communication is better. I mean, they having a private repo is half the problem; most of the fixes do not really require such secrecy IMO.

Then again, incompatible changes are not allowed. Therefore in the absence of any explanation, one must assume it is a bugfix like any other done in the spec.

**Comment by jeffbolznv** [comment]
We only change limits after very careful consideration, when it's unavoidable. Some implementations couldn't support a 128B nonCoherentAtomSize.

Closing this, since there's no action to take.

**Comment by krOoze** [comment]
@oddhack In 1.1.124 `maxPerStageDescriptorUpdateAfterBindInputAttachments` and `maxDescriptorSetUpdateAfterBindInputAttachments` are lowered (from likely nonsense value).
But it is not mentioned in the changelog.
