### ISSUE TITLE
In vkspec.html, is it possible to have a switch button to turn off  "Table of Contents"

### ISSUE THREAD

**Issue by locke-lunarg** [KhronosGroup/Vulkan-Docs#1053]
In vkspec.html, is it possible to have a switch button to turn off `Table of Contents`? It looks like it shows the content in full screen.

I know when I zoom in it, `Table of Contents` will be moved to the top, but I don't want to make the font size too large. Or if I could move `Table of Contents` to the top without increasing font size. It's also good.

**Comment by krOoze** [comment]
Well, it is _theoretically_ possible.

> I know when I zoom in it, Table of Contents will be moved to the top

Oh I didn't know it does that. I suspect that is another cause of the full spec loading so long...

**Comment by krOoze** [comment]
PS: Do you mean temporarily switched of or permanently. The second would be much easier; just build the spec with no ToS (or always on top) in the first place.

**Comment by oddhack** [comment]
If you figure out a good way you are welcome to propose a PR, but we aren't going to spend time on this unless there's widespread demand for it. Completely turning off the ToC during HTML generation is easy.

Most people are probably using the chunked HTML document these days.

**Comment by locke-lunarg** [comment]
OK. I close the issue. I will propose a PR when I'm done something.
