### ISSUE TITLE
Are enums tags guarenteed to exist when a type names one?

### ISSUE THREAD

**Issue by zyrolasting** [KhronosGroup/Vulkan-Docs#1060]
I assumed that if `<type category="enum" name="X">`exists, then `<enums name="X">` exists.

It seems `VkQueryPoolCreateFlagBits` is a current counterexample on `master`: https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/master/xml/vk.xml

Is this just how you all reserve names for future use?

**Comment by krOoze** [comment]
Nope. There's is no `VkInstanceCreateFlagBits` neither.
If there are no bits, assume either no `<enums>` or an empty one.

**Comment by zyrolasting** [comment]
Thanks much. Awesome response time!
