### ISSUE TITLE
GL_INTEL_shader_integer_functions2 referenced in spec not released

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1065]
@ianromanick The `GL_INTEL_shader_integer_functions2` extension referenced in the `VK_INTEL_shader_integer_functions2` seems not available anywhere.

**Comment by oddhack** [comment]
@ianromanick isn't a member of the Vulkan Team on github so I can't assigned this to them and I'm guessing @-mentioning them may not notify, though unsure about that. But this is an issue for Intel and you may have more success directing it to them through some other means - all we can do with vendor EXTs is publish the specs they give us.

**Comment by krOoze** [comment]
Well, it is the only contact the spec gives... Mentions should be global, unless user is blocked, I think.

I personally don't particularly care, except I stumbled upon it with the #1066. It is weird a GLSL dependency would not be published after half a year from extension release.

Hm, I found the extension specification on his personal [fork of GLSL registry](https://github.com/ianromanick/GLSL/tree/INTEL_shader_integer_functions2). I will try to comment on the commit, and see what happens...

**Comment by ianromanick** [comment]
This extension kind of got put on the back burner, and I forgot about it.  I _thought_ I had submitted PRs for the GLSL extension spec and the glslang changes.  I'll see if I can figure out what I was doing.

**Comment by ianromanick** [comment]
I just submitted an MR for the OpenGL extension in the Khronos internal gitlab.  Hopefully that will make it out to the public registry relatively soon.

**Comment by oddhack** [comment]
@ianromanick we're not mirroring the internal repo to github - to publish an extension propose a PR here. If it needs some internal soak & discussion time that's fine, this is just a heads-up so you don't expect it to appear here without additional intervention.

**Comment by oddhack** [comment]
This has been in the registry as https://www.khronos.org/registry/OpenGL/extensions/INTEL/INTEL_shader_integer_functions2.txt for a while, though this issue was left open.
