### ISSUE TITLE
Allow depth to color copies and vice versa on Nvidia devices

### ISSUE THREAD

**Issue by ReinUsesLisp** [KhronosGroup/Vulkan-Docs#1069]
We are porting work from console where the proprietary API allows copies and image views between depth and color. I am aware devices are free to use whatever layout they want for depth images, hence why I'm requesting for an Nvidia extension in particular (since their color and depth/stencil layouts match).

Both the Vulkan [specification](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#formats-compatibility) and [GL_ARB_copy_image](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_copy_image.txt) disallow these copies:
> Uncompressed color formats are compatible with each other if they occupy the same number of bits per texel block. [...] Each depth/stencil format is only compatible with itself

That being said, Nvidia allows these copies on OpenGL (and in their proprietary API). The following code on Nvidia's OpenGL driver prints out `Success` without aborting:
```cpp
constexpr GLsizei size = 8;
GLuint depth_tex;
glCreateTextures(GL_TEXTURE_2D, 1, &depth_tex);
glTextureStorage2D(depth_tex, 1, GL_DEPTH_COMPONENT32F, size, size);

std::vector<float> depth_data(size * size, 0.5f);
glTextureSubImage2D(depth_tex, 0, 0, 0, size, size, GL_DEPTH_COMPONENT, GL_FLOAT, std::data(depth_data));

GLuint color_tex;
glCreateTextures(GL_TEXTURE_2D, 1, &color_tex);
glTextureStorage2D(color_tex, 1, GL_R32F, size, size);

glCopyImageSubData(depth_tex, GL_TEXTURE_2D, 0, 0, 0, 0, color_tex, GL_TEXTURE_2D, 0, 0, 0, 0, size, size, 1);
if (glGetError() != GL_NO_ERROR) {
    std::abort();
}

// Data will now be in the color image view
std::array<float, size * size> color_data;
glGetTextureSubImage(color_tex, 0, 0, 0, 0, size, size, 1, GL_RED, GL_FLOAT, sizeof(color_data), std::data(color_data));
for (const float color : color_data) {
    if (color != 0.5f) {
        std::abort();
    }
}
std::puts("Success");
```

What are the alternatives for depth/stecil<->color copies or image views without having these available on Vulkan?
- For depth->color, to use a graphics queue renderpass that samples the depth texture; for color->depth, to use a graphics queue renderpass that samples the color texture and writes to `FragDepth` on the fragment shader.
- Linearize the image (regardless of the source/destination format) to a temporary buffer with `vkCmdCopyImageToBuffer` and reupload it to the destination image with `vkCmdCopyBufferToImage`.
- Using `imageStore` in a compute pass is disallowed because depth stencil images can't be used as storage images due to their undefined layout.

These alternatives are slow and lossy compared to the raw copy `vkCmdCopyImage` would do.

**Comment by krOoze** [comment]
- Take the depth value in fragment shader directly and save it color using image store? Or as a color attachment if allowed (should be better).

**Comment by ReinUsesLisp** [comment]
That could be done on compute, since sampling depth/stencil images and storing to color is legal. It still has the same drawbacks of the other approaches and it doesn't allow color to depth copies/views.

**Comment by ReinUsesLisp** [comment]
Closing so I can formulate it better when I have to revisit this.

**Comment by pdaniell-nv** [comment]
Just adding a note that https://github.com/KhronosGroup/Vulkan-Docs/issues/2079 is a similar request.
