### ISSUE TITLE
VK_EXT_debug_report: Reports during vkDestroyInstance

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#107]
If I do:

```
VkDebugReportCallbackCreateInfoEXT debugReportInfo = {...};
VkInstanceCreateInfo instanceCreateInfo = {...};
instanceCreateInfo.pNext = &debugReportInfo;

vkCreateInstance(&instanceCreateInfo, ...);
vkCreateDebugReportCallbackEXT(instance, &debugReportInfo, ...);
...
vkCreateDevice(...);
...
vkDestroyInstance(instance, ...);
````

then I get reports like:

```
...
[ERROR] Swapchain: vkDestroyInstance() called before all of its associated VkDevices were destroyed.
[WARN] DebugReport: Debug Report callbacks not removed before DestroyInstance
[WARN] DebugReport: Debug Report callbacks not removed before DestroyInstance
...
```

The message about the leaked VkDevice is helpful, but clearly I need to destroy the debug report callbacks too:

```
...
vkCreateDevice(...);
...
vkDestroyDebugReportCallbackEXT(...);
vkDestroyInstance(instance, ...);
````

Now I'm cleaning up the debug report callbacks, so it won't complain about that, which is okay. But that means I don't have any callbacks registered when vkDestroyInstance is called, so I never see the report of the leaked VkDevice.

Is there any valid way to get report callbacks for errors that are detected during vkDestroyInstance?

If not, would it be possible to make that possible? There's already the pNext trick for getting reports from the start of vkCreateInstance, so it'd be nice to have some trick to get reports until the end of vkDestroyInstance too.

A few bad ideas of how to do it:

* Maybe specify that vkDestroyInstance will implicitly destroy any debug report callbacks that it owns, so that it's not considered an object lifetime violation, and get the layer implementations to stop warning in that situation.

* Maybe do the above, but only for debug report callbacks created with a VK_DEBUG_REPORT_IMPLICITLY_DESTROYABLE_BIT flag.

* Maybe add a VK_DEBUG_REPORT_KEEP_UNTIL_DESTROY_BIT flag to the VkDebugReportCallbackCreateInfoEXT set in instanceCreateInfo.pNext, so that the implementation will use those callbacks during vkCreateInstance and make a copy of them so it can use them during vkDestroyInstance too.

**Comment by courtney-g** [comment]
We count extend the lifetime of the VkDebugReportCallbackCreateInfoEXT callback used at CreateInstance time. Could use that callback for issues detected at CreateInstance and DestroyInstance. Somewhat funky because it requires the loader to remember it which isn't a very Vulkan thing to do.

**Comment by philiptaylor** [comment]
VkAllocationCallbacks provides a precedent for that - a vkCreate function can save a copy of the allocations callbacks to use later, up until the corresponding vkDestroy. That sounds quite similar to this case.

**Comment by courtney-g** [comment]
This feature is now documented in the latest VK_EXT_debug_report.
Devices that implement version 3 of VK_EXT_debug_report should support this feature.

**Comment by philiptaylor** [comment]
Hmm, where specifically is it documented? I can't seem to find it anywhere!

https://github.com/KhronosGroup/Vulkan-Docs/commits/1.0-VK_EXT_debug_report/doc/specs/vulkan/appendices/debug_report.txt doesn't list any relevant-looking changes, and https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml still says VK_EXT_DEBUG_REPORT_SPEC_VERSION is 2.

**Comment by courtney-g** [comment]
Somehow missed the commit for that change on the Github 1.0-VK_EXT_debug_report branch.
I've added it so should see it here: https://github.com/KhronosGroup/Vulkan-Docs/commits/1.0-VK_EXT_debug_report

**Comment by philiptaylor** [comment]
Okay, thanks!

**Comment by oddhack** [comment]
@courtney-g please close this if possible - the change to vk.xml has gone into the 1.0.17 spec update. I'm not sure where you stand on keeping the external EXT branch synced up with the internal one, if that's been done then we should be good to go.
