### ISSUE TITLE
Why can `vkFreeDescriptorSets` fail when every other resource releasing functions can't?

### ISSUE THREAD

**Issue by nyronium** [KhronosGroup/Vulkan-Docs#1070]
Any function that releases a resource, (such as `vkDestroy*` and `vkFree*`) cannot fail.
With the sole exception of [`vkFreeDescriptorSets`](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/vkFreeDescriptorSets.html).

**vkFreeDescriptorSets** can fail with both `VK_ERROR_OUT_OF_HOST_MEMORY` and `VK_ERROR_OUT_OF_DEVICE_MEMORY`.

The specification does not provide reasoning for this, and it complicates error handling in language bindings which such as `Vulkan-Hpp` (See [PR#338 in Vulkan-Hpp](https://github.com/KhronosGroup/Vulkan-Hpp/pull/338)).

It would be great to know more about the reasoning behind this decision.

**Comment by oddhack** [comment]
We already have an internal discussion going on about this. It appears this was probably an oversight, and if we can establish that all implementations only return successfully, we'll probably add a restriction to the allowed return value and a Note explaining the discrepancy. We are unlikely to actually change the API to remove the return value, however.

**Comment by nyronium** [comment]
That is good to hear. Please tell us when you have come to a conclusion internally.

**Comment by krOoze** [comment]
Seems fixed in 1.1.128

**Comment by oddhack** [comment]
Yes, thanks. Lost track of the internal / external issue association.
