### ISSUE TITLE
VK_KHR_external_memory_win32: 

### ISSUE THREAD

**Issue by LucaGanio** [KhronosGroup/Vulkan-Docs#1074]
@cubanismo 
where can I find an example on how to use this extension? is there any kind of documentation about it?

**Comment by oddhack** [comment]
@LucaGanio have you checked in the https://github.com/KhronosGroup/Vulkan-Samples repository? That's new and the repository is just getting up to speed, so I don't know if it would help you, but it's the best place to look within Khronos-owned resources.

**Comment by LucaGanio** [comment]
Still haven't checked in that repository. I am gonna give it a try. Thanks

**Comment by djdeath** [comment]
The CTS has some tests using this extension : https://github.com/KhronosGroup/VK-GL-CTS/blob/master/external/vulkancts/modules/vulkan/synchronization/vktSynchronizationCrossInstanceSharingTests.cpp

**Comment by sasmaster** [comment]
Download NVIDIA video SDK. There is an example where Vulkan buffer is mapped to CUDA resource using that extension.

**Comment by oddhack** [comment]
There have been a couple of suggestions for sample code here, so closing this.
