### ISSUE TITLE
VK_PIPELINE_CREATE_DISPATCH_BASE should have _BIT

### ISSUE THREAD

**Issue by Kangz** [KhronosGroup/Vulkan-Docs#1075]
The `VK_PIPELINE_CREATE_DISPATCH_BASE` bit of `VkPipelineCreateFlagBits` doesn't follow the naming convention of other bits where they end in `_BIT`.

Should it be renamed to `VK_PIPELINE_CREATE_DISPATCH_BASE_BIT` instead?

**Comment by oddhack** [comment]
Thanks, we're taking a look at it. Will probably add an alias following the naming convention.

**Comment by oddhack** [comment]
This should be fixed in the 1.1.128 spec update.
