### ISSUE TITLE
VK_KHR_imageless_framebuffer missing type declarations

### ISSUE THREAD

**Issue by liam-middlebrook** [KhronosGroup/Vulkan-Docs#1076]
The `<extension>` block for `VK_KHR_imageless_framebuffer` is missing the `<type>` block for `VkFramebufferAttachmentImageInfoKHR`. This should be added in order to resolve issues with some external parsers of the `vk.xml` specification (such as [WineVulkan](https://source.winehq.org/git/wine.git/tree/HEAD:/dlls/winevulkan)).

**Comment by oddhack** [comment]
What is the WineVulkan doing that this makes a difference to them? Every tool processing the XML needs to follow type dependencies to determine what types are needed. There's no harm in being more explicit about it in this case, but it's a nuisance requirement I'm not eager to generally impose on people adding to the XML.

**Comment by Guy1524** [comment]
I submitted a patch to wine that should fix this issue: https://source.winehq.org/patches/data/172490

**Comment by oddhack** [comment]
@liam-middlebrook do you still want this PR applied?

Also, if I'm reading the winehq patch correctly, it may still need to transitively require the dependencies of the members in some circumstances (probably not this one).

**Comment by oddhack** [comment]
Closing. I think between the fix in #1077 having already been applied (AFAICT) and the winehq patch, there's nothing left to do here.
