### ISSUE TITLE
vkCmdBuildAccelerationStructureNV: dst and src "can" be identical

### ISSUE THREAD

**Issue by alek314** [KhronosGroup/Vulkan-Docs#1079]
Suppose one store a skin-animated mesh in a BLAS, and one need to update this BLAS every frame. A friend from Nvidia told me, "dst" and "src" parameter in vkCmdBuildAccelerationStructureNV "can" be identical, as long as vertex count and index count of the mesh did not changed. 
I think this is a common scenario, and the above approach is very convenient.
But this behavior is found in the spec. Is this feature official?

Thank you

**Comment by dgkoch** [comment]
Yes, this is an official feature.  
Will try to add spec language for this.

**Comment by dgkoch** [comment]
This should be addressed in the 1.2.135 spec update.  This got tangled in with the KHR_ray_tracing  spec (see #1205), so was held up until that was released. 
Please re-open if you don't find it adequately addressed.
