### ISSUE TITLE
Clarify lifetime of push constants

### ISSUE THREAD

**Issue by martty** [KhronosGroup/Vulkan-Docs#1081]
The spec contains very descriptive wording for the lifetime of push descriptors: 

> When a command buffer begins recording, all push descriptors are undefined. Push descriptors can be updated incrementally and cause shaders to use the updated descriptors for subsequent rendering commands (either compute or graphics, according to the pipelineBindPoint) until the descriptor is overwritten, or else until the set is disturbed as described in Pipeline Layout Compatibility. When the set is disturbed or push descriptors with a different descriptor set layout are set, all push descriptors are undefined.

But such wording is missing for push constants (except for the initial undefined value). I suspect this above wording can be directly copied, with push descriptors replaced with push constants.

**Comment by sfricke-samsung** [comment]
@martty a little overdue, but this issue is being actively looked into now internally with the Working Group. We agree that there is some serious ambiguity here and will be taking action to better define how all Vulkan implementations can handle the lifetime of a push constant. Thanks again for raising this issue.

**Comment by martty** [comment]
Thank you for adding the wording for this issue in the latest spec update!

However I have some difficulty with parsing this part:
```
When a bound pipeline command is issued, the bound pipeline’s layout must be compatible with the layouts used to set the values of all push constants in the pipeline layout’s push constant ranges, as described in Pipeline Layout Compatibility.
```
It seems like this clause is missing an "or" part - what happens if this is not the case? I suppose the intent is to say that then the values read in the shader are undefined, but the actual memory backing the values remains undisturbed (as said by the subsequent sentence).

**Comment by sfricke-samsung** [comment]
So there is already a VU (`VUID-vkCmdDraw-None-02698`) that will blow up in your if you don't have a compatible layout at draw time. So if you go

```
vkBeginCommandBuffer()
vkCmdBindPipeline(pipeline_A)
vkCmdPushConstants(layout_A)
vkCmdBindPipeline(pipeline_B) // different range - non compatible
vkCmdBindPipeline(pipeline_A)
vkCmdDraw()
vkEndCommandBuffer()
```

You are fine, as long at draw/dispatch/etc time the last pipeline and push constant match up and all the various `vkCmdBindPipeline` and `vkCmdPushConstants` in between that are different shouldn't affect anything

This has been a fun, slow work in progress, so please let me know if you still have something that doesn't fully make sense or I may have missed

**Comment by martty** [comment]
I was confused by the term "bound pipeline command" and interpreted it as "pipeline bind command", but now I am thinking it means "any command that uses a bound pipeline" and that way it makes more sense.

Thanks for the clarification!

**Comment by sfricke-samsung** [comment]
ok, so if you view the html/pdf version of the text, the `bound pipeline command` has a link to 
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#pipeline-bindpoint-commands

which basically was the way for us to "graphics pipelines are used by `draws`, compute pipelines are used by `dispatch`, ray tracing, etc..."

So we have defined what "bound pipeline command" means and your "any command that uses the bound pipeline" is just a much nicer, less spec-style way, or saying it :)

**Comment by martty** [comment]
Yes, that makes sense. Thanks for the effort and explanation! Can be closed from my end.

**Comment by sfricke-samsung** [comment]
thanks for poking this issue, trust me, you are/were not the only one out there who wanted better clarification on this!
