### ISSUE TITLE
Is extension dependency satisfied by promotion?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1085]
Is extension dependency satisfied by promotion?

For example `VK_KHR_device_group` device extension have dependency on `VK_KHR_device_group_creation` instance extension. Let's assume the physical device is version 1.0 but the instance is version 1.1. Both of those extensions are promoted, but on 1.0 device I must enable the `VK_KHR_device_group`. Does  `VK_KHR_device_group_creation` still have to be enabled on instance, or does simply 1.1 core version suffice to satisfy the dependency?

**Comment by oddhack** [comment]
As a general matter the answer is yes, but there may be circumstances that differ; for example, an extension that has a required feature is promoted to a future Vulkan core, but the feature is made optional in core. Probably the best we can do is making the general statement + caveat in the fundamentals section, then document any such exceptions in extension and version appendices. This is likely to take a while to sort out internally, so we're tracking it there and there won't be much activity here until that's sorted out.

**Comment by oddhack** [comment]
This should be addressed in the 1.2.131 spec update.
