### ISSUE TITLE
Clarify vkGetQueryPoolResults with VK_QUERY_RESULT_WITH_AVAILABILITY_BIT

### ISSUE THREAD

**Issue by kuhar** [KhronosGroup/Vulkan-Docs#1086]
When using `vkGetQueryPoolResults` with the `VK_QUERY_RESULT_WITH_AVAILABILITY_BIT` flag set, it is unclear where the availability result will be actually written.

The current [spec](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/vkGetQueryPoolResults.html) says:
> * dataSize is the size in bytes of the buffer pointed to by pData.
> * pData is a pointer to a user-allocated buffer where the results will be written

> However, availability state is still written to pData for those queries if VK_QUERY_RESULT_WITH_AVAILABILITY_BIT is set.

> If VK_QUERY_RESULT_WITH_AVAILABILITY_BIT is set, the final integer value written for each query is non-zero if the query’s status was available or zero if the status was unavailable. When VK_QUERY_RESULT_WITH_AVAILABILITY_BIT is used, implementations must guarantee that if they return a non-zero availability value then the numerical results must be valid, assuming the results are not reset by a subsequent command.

While the flag [is described](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkQueryResultFlagBits.html) as follows:
> VK_QUERY_RESULT_WITH_AVAILABILITY_BIT specifies that the availability status accompanies the results.

Suppose there are 2 queries that need `stride * numQueries` of storage. Based on the wording above, it is unclear to me:
1. How big the `pData` buffer has to be? Are there 2 separate availability integers for each query, or just one? What is `VK_QUERY_RESULT_64_BIT` is set? It seems like that the wording suggests that `pData` needs to be either `stride * numQueries * 2` or `stride * (numQueries + 1)` bytes big.
2. Where exactly are the availability integer(s) stored exactly. Does the final integer mean the last cell of `pData`, i.e., `pData[numQueries]`?

Rephrasing these questions a bit, is the data layout of the result buffer `pData`:
* `[result0, availability0, result1, availability1]` where each array cell size is `stride`,
* `[result0, result1, availability]` where each array cell size is `stride`,
* or something else?

**Comment by dneto0** [comment]
I agree this is unclear to me.

The conformance tests follow the rule in your first bullet point:

> * `[result0, availability0, result1, availability1]` where each array cell size is `stride`,

And to be perfectly explicit, stride is 4 bytes if the queried values are 32-bit, and 8 bytes if the queried values are 64bit (the VK_QUERY_RESULT_64_BIT is set).

See the conformance code:

*  Where the query pool data is read and stored into a vector of ints:
https://github.com/KhronosGroup/VK-GL-CTS/blob/9e805a03dd0931838b3d8cb837417839733056b1/external/vulkancts/modules/vulkan/query_pool/vktQueryPoolStatisticsTests.cpp#L167
   * This shows that the number of words to be read is twice the number of queries times the number of words in each query value.

* Where the vector is interpreted:  https://github.com/KhronosGroup/VK-GL-CTS/blob/9e805a03dd0931838b3d8cb837417839733056b1/external/vulkancts/modules/vulkan/query_pool/vktQueryPoolStatisticsTests.cpp#L542
   * Shows that the first value in the pair is the actually the queried value, and the second value is the 0 or non-zero to indicate availability.

**Comment by janharaldfredriksen-arm** [comment]
Isn't this answered by the section right before vkGetQueryPoolResults that starts with:
>An application can retrieve results either by requesting they be written into application-provided memory, or by requesting they be copied into a VkBuffer. In either case, the layout in memory is defined as follows:

(The description that follows matches what the CTS does.)

**Comment by kuhar** [comment]
Thanks @janharaldfredriksen-arm, I didn't see that at all using https://www.khronos.org/registry/vulkan/specs

> * The first query’s result is written starting at the first byte requested by the command, and each subsequent query’s result begins stride bytes later.
> * Each query’s result is a tightly packed array of unsigned integers, either 32- or 64-bits as requested by the command, storing the numerical results and, if requested, the availability status.
> * If VK_QUERY_RESULT_WITH_AVAILABILITY_BIT is used, the final element of each query’s result is an integer indicating whether the query’s result is available, with any non-zero value indicating that it is available.
> * If more than one query is retrieved and stride is not at least as large as the size of the array of integers corresponding to a single query, the values written to memory are undefined.

Does this mean that with 2 queries and 64-bit results the layout should be:
`[[result0,availability0], [[result0,availability0]]` with array stride 16 bytes?

**Comment by janharaldfredriksen-arm** [comment]
Yes, that's my understanding.

**Comment by oddhack** [comment]
@kuhar we agreed to write up a Note in the spec documenting option #1, which we're tracking internally. If you don't have additional questions about this and are satisfied with that resolution, this could be closed now - your call.

**Comment by kuhar** [comment]
Sounds good to me, thanks for the help.
The behavior I observed on my ICD matches the understanding we arrived to here.
