### ISSUE TITLE
Deriving current spec version from vk.xml

### ISSUE THREAD

**Issue by zyrolasting** [KhronosGroup/Vulkan-Docs#1087]
If I append the value of `VK_HEADER_VERSION` to the max `number` attribute value out of all `<feature>` elements, can I treat that as the latest ratified version of the specification? Should I leave `VK_HEADER_VERSION` out?

**Comment by oddhack** [comment]
Yes, although the way tha the header version / patch version number makes it into the spec is through an equivalent macro in the toplevel spec Makefile that gets updated at the same time.

Whether you need to do anything with the version depends on what the use case is. Bumping the patch version / header version indicates bugfixes to the spec, not new functionality.
