### ISSUE TITLE
Split VU by preprocessor

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1094]
There's VU split by preprocessor at https://github.com/KhronosGroup/Vulkan-Docs/commit/d4b6925d02d0c917403fb8743c0289dd67b027f1#diff-f7ced97bab319d7b65f3bded6b78fc63R784 in 1.1.128

IIRC that does not work ATM.

**Comment by oddhack** [comment]
Thanks. We will take care of it.

**Comment by oddhack** [comment]
Should be fixed in the 1.1.130 spec update.
