### ISSUE TITLE
19.1.13 Typo: vkCmdDrawIndexed and vkCmdDrawIndexed

### ISSUE THREAD

**Issue by ireyon** [KhronosGroup/Vulkan-Docs#11]
Section 19.1.13:
> * Indexed drawing commands (vkCmdDrawIndexed and
    vkCmdDrawIndexed) read index values from an index buffer

One of them was probably meant to be vkCmdDrawIndexed**Indirect**.

**Comment by oddhack** [comment]
We've already fixed this internally; it will roll out when we're able to update Github (probably next Thursday, we're going to try to set a weekly syncup frequency).
