### ISSUE TITLE
make allchecks crash python scripts

### ISSUE THREAD

**Issue by salamanderrake** [KhronosGroup/Vulkan-Docs#110]
Running make allchecks causes a crash with the python scripts.

```
make allchecks
Include files not found in the spec source are in ../../../out/core/checks/notInSpec.txt
Generating link checks for spec (specErrs.txt) and man pages (manErrs.txt)
Traceback (most recent call last):
  File "checkLinks.py", line 310, in <module>
    checkLinks(file, follow)
  File "checkLinks.py", line 243, in checkLinks
    checkLinks(newpath, follow, included=True)
  File "checkLinks.py", line 272, in checkLinks
    if (curStruct and value in structs[curStruct]):
TypeError: argument of type 'NoneType' is not iterable
Makefile:277: recipe for target 'checklinks' failed
make: *** [checklinks] Error 1

```

Ubuntu 16.04( I know its not supported yet)
nVidia Driver Version: 255.00.28
Python3 Version: 3.5.1+( also not supported?)
Vulkan-Docs Branch: 1.0-wsi_extensions
Vulkan-Docs Comment Revision: 39c51879998d85b635e5387803ab41c19c92a91b

**Comment by oddhack** [comment]
Could you check this again and close it if the problem's gone away? I think I noticed this myself at one point, but it's not occurring in the 1.0.10 spec tree. Possibly a script fix someone else put in the internal tree dealt with it and I didn't notice.

**Comment by oddhack** [comment]
Closing - if you're still having problems, feel free to reopen.
