### ISSUE TITLE
Safer automation for LaTeX compilation

### ISSUE THREAD

**Issue by elfring** [KhronosGroup/Vulkan-Docs#111]
The program "pdflatex" is called several times in [the make file for the Vulkan specification](https://github.com/KhronosGroup/Vulkan-Docs/blob/d204ac2f6991f75fab2ebc22136fd179d692f84f/src/spec/Makefile#L106 "Documentation targets").
I would prefer that LaTeX input files will be processed by [a higher-level software build system](https://ctan.org/topic/compilation "Doc­u­ment com­pi­la­tion pro­cess for LaTeX").

**Comment by oddhack** [comment]
We are not planning to change the build system at present.
