### ISSUE TITLE
Can Render passes exist across multiple command buffers?

### ISSUE THREAD

**Issue by phire** [KhronosGroup/Vulkan-Docs#112]
I'm like 80% sure that render passes must start and finish within the same command buffer, but the Vulkan specification doesn't appear to explicitly state this either way.

At the very least, I was expecting `vkCmdNextSubpass` and `vkCmdEndRenderPass` to state that they required the commandBuffer parameter to require that a `vkCmdBeginRenderPass` command had previously been recorded in it.

It's possible that render passes can persist over multiple primary command buffers, and my current reading of the specification allows that, but such an interpenetration feels weird as there is no inheritance of state across primary command buffers.

**Comment by janharaldfredriksen-arm** [comment]
You are correct in saying that render passes must begin and end within the same command buffer.

I think this is covered by:
>vkEndCommandBuffer must not be called inside a render pass instance

That is:
- vkCmdBeginRenderPass begins a _render pass instance_
- vkCmdNextSubpass moves to the next subpass in the render pass instance
- vkCmdEndRenderPass ends the render pass instance

Between the calls to vkCmdBeginRenderPass and vkCmdEndRenderPass, the command buffer is "inside a render pass instance", and you're not allowed to end the command buffer while it is in this state.

**Comment by phire** [comment]
Ah yes, it does say that "**vkEndCommandBuffer** must not be called inside a render pass instance"

**Comment by oddhack** [comment]
@janharaldfredriksen-arm's comment seems to address this, so closing.
