### ISSUE TITLE
vkGetAccelerationStructureMemoryRequirementsNV uses VkMemoryRequirements2KHR

### ISSUE THREAD

**Issue by ville-h** [KhronosGroup/Vulkan-Docs#1122]
In vk.xml the vkGetAccelerationStructureMemoryRequirementsNV command uses VkMemoryRequirements2KHR rather than VkMemoryRequirements2 as the type of the 3rd parameter. Is the intention for vk.xml to use the non-alias names where possible? Would be nicer if it was so.

**Comment by dgkoch** [comment]
> Is the intention for vk.xml to use the non-alias names where possible?

I think is actually more of a question for @oddhack.  I'm not sure that we typically go through and rewrite all references to something that is aliased with the non-aliased version. 
Is it causing problems?

**Comment by oddhack** [comment]
> I think is actually more of a question for @oddhack. I'm not sure that we typically go through and rewrite all references to something that is aliased with the non-aliased version.

I'm not sure it's been consistently followed but it's a good idea to use the most-correct name, which is usually the one that's aliased, not the old name that becomes the alias.

**Comment by oddhack** [comment]
Also, there are actually a bunch of cases where using the alias name would cause problems - includes of API prototypes / validity, refpage names come to mind. I think just the slink:/flink: type usage would pass the 'allchecks' markup validator target but anything beyond that is a concern.

**Comment by ville-h** [comment]
> Is it causing problems?

It's not a problem per se, or something that can't be worked around, it's just something I ran into when processing the vk.xml file and trying to figure out what entity might be referred to at various places. Doing a second lookup through the aliases works out fine for my purposes at least.

**Comment by dgkoch** [comment]
I believe this should be addressed in the 1.2.135 spec update.
