### ISSUE TITLE
VkPhysicalDeviceBufferDeviceAddressFeaturesEXT included twice in 1.1.129

### ISSUE THREAD

**Issue by allanmac** [KhronosGroup/Vulkan-Docs#1123]
Chapter 35. Features, pages 1377-8.

**Comment by krOoze** [comment]
I don't see it.
There is one KHR and one EXT struct.

**Comment by oddhack** [comment]
Agreed - I think you're misreading this. Normally we would just typedef the EXT to the KHR structure on promotion, but IIRC there were sufficient differences between EXT and KHR that this wasn't possible.

Closing as invalid.

**Comment by allanmac** [comment]
Sorry, my mistake!  The KHR and EXT happen to be side-by-side in the PDF and they look identical if you skim too fast.  Ooops.
