### ISSUE TITLE
Point sprite clipping doesn't follow OpenGL ES rules

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#113]
I'm honestly not sure if this constitutes a bug or just criticism, so feel free to close as wontfix as needed.

The OpenGL ES 2.0 specification defines clipping with regard to point sprites as follows:

> If the primitive under consideration is a point, then clipping discards it if it lies outside the near or far clip plane; otherwise it is passed unchanged

This language persists through ES 3.2. In short, it means that points are not clipped to the sides of the volume, so even if the center of a point sprite is off to the side, the visible part will still be rasterized.

Vulkan does not. It says:

> If the primitive under consideration is a point, then clipping passes it unchanged if it lies within the clip volume; otherwise, it is discarded.

This requires that point sprites who's centers are off the side of the viewport to be clipped. This would mean that a point sprite would disappear while some of it is still genuinely visible.

This is a pretty serious change from OpenGL ES's rules. Granted, to be fair, this is in line with desktop OpenGL's rules. But it is very different from the rules of any version of [Direct3D](https://msdn.microsoft.com/en-us/library/windows/desktop/bb147281%28v=vs.85%29.aspx). Metal seems to be [somewhat split on it](http://stackoverflow.com/questions/35731051/does-metal-clip-points-to-the-center). So it seems clear that a lot of hardware can handle OpenGL ES's rules.

I don't suppose there's any chance of that getting fixed in a 1.1 release?

**Comment by NicolBolas** [comment]
Maybe this could be an optional feature added to 1.1. By default, it could use the 1.0 wording, but 1.1 implementations can expose proper point sprite clipping as an always-on feature.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.40 spec update, in the sense that vagueification language was added. We are considering a future feature or query to expose just what sort of behavior an implementation does.

**Comment by critsec** [comment]
I was doing some archeology and noticed that we never pointed out here that the VK_KHR_maintenance2 extension added a way for implementations to declare what their point clipping behavior is. VK_POINT_CLIPPING_BEHAVIOR_ALL_CLIP_PLANES_KHR is the OpenGL popping behavior, and VK_POINT_CLIPPING_BEHAVIOR_USER_CLIP_PLANES_ONLY_KHR is the OpenGL ES pop-free behavior.

**Comment by NicolBolas** [comment]
@critsec "added"? KHR_maintenance2 hasn't been released yet, has it?

But I do look forward to seeing that query made available. Granted, I'd *rather* we force implementations into the ES behavior, but at least knowing up-front makes it possible to know how to use point sprites. I would hope that if an implementation has a choice, that we encourage them to pursue the ES behavior rather than the desktop GL behavior.

**Comment by critsec** [comment]
Ahem. I've deleted my comment.
