### ISSUE TITLE
VkPerformanceCounterScopeKHR enumeration value name prefix

### ISSUE THREAD

**Issue by ville-h** [KhronosGroup/Vulkan-Docs#1130]
[VkPerformanceCounterScopeKHR](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkPerformanceCounterScopeKHR.html) seems to use "VK_QUERY_SCOPE_" as enumeration value prefix rather than "VK_PERFORMANCE_COUNTER_SCOPE_". Is this intentional or a naming bug?

**Comment by djdeath** [comment]
Indeed it seems like an naming mistake, probably leftover from the previous iteration of the spec.

Let me submit a change.

**Comment by oddhack** [comment]
This should be fixed in the 1.2.131 spec update.
