### ISSUE TITLE
Unclear meaning of independent capabilities

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1132]
Spec says:

> Capabilities that correspond to image creation parameters are not
independent of each other: combinations of parameters that are not supported
as reported by `vkGetPhysicalDeviceImageFormatProperties` are not
supported by the surface on that physical device, even if the capabilities
taken individually are supported as part of some other parameter
combinations.

I am unable to parse this, and what it is trying to convey. I think it conflates two or three concepts making it illegible.

**Comment by polarina** [comment]
I believe that in a nutshell, your compositor (X11/Wayland/Win32) may support some image capabilities (format + extents + image count, etc.) that your device does not, and your device may support capabilities your compositor does not.

It is saying that even if `VkSurfaceCapabilitiesKHR` indicates that something is supported by the compositor, the device may not and you should do cross-checks before deciding on what to use.

**Comment by krOoze** [comment]
"Believe" is not good enough for a specification.

Hopefully it is covered by VUs, and so the quote just addresses Implementations...

**Comment by polarina** [comment]
@krOoze I would say that they are dependent. For example, one implementation may support `VK_FORMAT_B8G8R8A8_UNORM` at 8192x8192 resolution and `VK_FORMAT_A2B10G10R10_UNORM_PACK32` at only 4096x4096. This would be indicated by `vkGetPhysicalDeviceImageFormatProperties` for these formats.

It may be that `VkSurfaceCapabilitiesKHR` reports 8000x8000 for `minImageExtent` and `VkSurfaceFormatKHR` reports `VK_FORMAT_A2B10G10R10_UNORM_PACK32` as a supported format, and yet you may not use these two combinations together.

**Comment by krOoze** [comment]
Well, that still sounds like "independent" in my dictionary. As in each of those limits standing on its own, and all three needing to be satisfied separately.

I made #1135 with my interpretation of your interpretation.

**Comment by polarina** [comment]
@krOoze looks good to me. Your change aligns with my understanding of the original paragraph.
