### ISSUE TITLE
Weird wait semaphores policy at vkQueuePresentKHR

### ISSUE THREAD

**Issue by daemyung** [KhronosGroup/Vulkan-Docs#1139]
I raise up a validation issue(https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/1423#) and they recommends raise up an issue at here.

Spec says

**All elements of the pWaitSemaphores member of pPresentInfo must be semaphores that are signaled, or have semaphore signal operations previously submitted for execution.**(https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/vkQueuePresentKHR.html)

The last condition **have semaphore signal operations previously submitted for execution** is wired. Because even I'm using a semaphore to synchronize, I must submit command buffers with semaphores which are signaled at first and next I can call vkQueuePresentKHR because of the last condition.

What I say that I need to write my code like below...

```
VkSubmitInfo submit_info {};

submit_info.signalSemaphoreCount = 1;
submit_info.pSignalSemaphores = &render_semaphore;

vkQueueSubmit(queue_, 1, &submit_info, VK_NULL_HANDLE);

VkPresentInfoKHR present_info {};

present_info.waitSemaphoreCount = 1;
present_info.pWaitSemaphores = &render_semaphore;

vkQueuePresentKHR(queue_, &present_info);
```

However

**A semaphore can be signaled after execution of a queue operation is completed, and a queue operation can wait for a semaphore to become signaled before it begins execution."**(https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkSemaphore.html)

I means that API call order doesn't matter and synchronization is done by a semaphore.

So I can write my code like below
```
// Present will be executed when a wait semaphore is signaled.
// This semaphore will be signaled a command buffer is processed.
VkPresentInfoKHR present_info {};

present_info.waitSemaphoreCount = 1;
present_info.pWaitSemaphores = &render_semaphore;

vkQueuePresentKHR(queue_, &present_info);

VkSubmitInfo submit_info {};

submit_info.signalSemaphoreCount = 1;
submit_info.pSignalSemaphores = &render_semaphore;

vkQueueSubmit(queue_, 1, &submit_info, VK_NULL_HANDLE);
```

So the last condition needs to change

**have semaphore will be signaled ~~signal operations previously submitted~~ for execution.**

Or if API call order is important, we need to describe more detail information about this.

**Comment by krOoze** [comment]
wired -> weird?

> A semaphore **can** be signaled after execution of a queue operation is completed, and a queue operation **can** wait for a semaphore to become signaled before it begins execution.

is bit misleading. "can" has special meaning.
What it means is:

> You can submit a batch with a seamaphore to signal. That semaphore will be signaled after that batch completes execution. And you can also submit another batch with a semaphore to wait on. That batch will wait for the semaphore to become signaled before it starts executing.

Binary semaphores do not support wait-before-signal.

**Comment by daemyung** [comment]
Got it... could I know the detail reason about this limitation?

**Comment by daemyung** [comment]
I will close this issue... but I hope somebody answer why Vulkan has Queue Forward Progress limitation...

**Comment by tigerssj** [comment]
@daemyung Did you fix this issue?

**Comment by tigerssj** [comment]
![image](https://user-images.githubusercontent.com/3362783/223682498-e78f2599-5d28-4695-95ef-1f2634601c00.png)

**Comment by solidpixel** [comment]
Your issue seems completely unrelated to this one.

**Comment by daemyung** [comment]
@tigerssj This is not an issue as far as I remember. I remember it's documentation issue.
