### ISSUE TITLE
DeviceCreateInfo valid usage

### ISSUE THREAD

**Issue by graphitemaster** [KhronosGroup/Vulkan-Docs#114]
## Issue
The wording in `DeviceCreateInfo` regarding `pEnabledFeatures` states **pEnabledFeatures must be a pointer to a valid VkPhysicalDeviceFeatures structure.** However `GetPhysicalDeviceFeatures` tells us that **To disable all features which are not required, set pEnabledFeatures to NULL.**

## Suggested Fix
Change the wording in `DeviceCreateInfo` to **pEnabledFeatures must be a pointer to a valid VkPhysicalDeviceFeatures structure or NULL to disable all features which are not required.**

**Comment by TobiasHector** [comment]
This is a duplicate of #104.

**Comment by krOoze** [comment]
^ #104 fixed in 1.0.6 update. Close?
