### ISSUE TITLE
Descriptor update clarification

### ISSUE THREAD

**Issue by szdarkhack** [KhronosGroup/Vulkan-Docs#115]
There is no mention in the spec of what happens when a descriptor is used both as a write destination and a copy source/destination in the same `vkUpdateDescriptorSets` call. It should be clarified whether it is completely undefined behavior or if there are some implicit ordering/visibility guarantees between the update operations.

Leaving it unspecified makes it impossible for users to use (because it my be undefined behavior), but more importantly it makes it impossible for validation layers to catch (because it may not be), so I think it should be explicitly stated in the spec.

**Comment by janharaldfredriksen-arm** [comment]
Yes, we should clarify.
I think the same issue applies when a descriptor is referenced, as source or destination, by multiple entries of the pDescriptorCopies and pDescriptorWrites arrays.

(This is somewhat related to #32, which clarifies the case where the copy source and copy destination in VkCopyDescriptorSet is the same.)

**Comment by oddhack** [comment]
This should be dealt with in the 1.0.8 spec update.
