### ISSUE TITLE
Not clear if Signal Operation Order covers unsignal operations too

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1150]
It is unclear is if Signal Operation Order also covers unsignal operations. One would assume so, since it references `vkQueuePresentKHR`, which only has a wait. But it is not otherwisely clear from the wording.

EDIT: I removed the original Issue, which became clear enough to me when reading the VU and synch scopes few more times. But just to be safe, I assume this is valid:
```
VkQueue q;
VkSemaphore s;
vkQueuePresentKHR(q, s);
vkQueueSubmit(q, signalSemaphores=s); // valid to reuse s because of Signal Operation Order
```

**Comment by jekstrand** [comment]
The example you posted is valid because everything happens on the same queue.  We're discussing internally what changes to the spec, if any, are required to make that more clear.

**Comment by krOoze** [comment]
@jekstrand Right, so I figured. What short-circuited my brain is the synchronization scopes of `vkQueueSubmit` are the thing that makes it satisfy its own VUs. Feels bit chicken-eggish. Though I guess that is how all the semaphores (and their relations) that are referenced in the `vkQueueSubmit` work.

**Comment by jekstrand** [comment]
Thinking about this a bit more....

It's not really semaphore signalling order that guarantees anything.  Rather, it's the ordering of signal operations with respect to wait operations.  If the a batch X waits on a semaphore S and signals S then the signal of S happens-after the execution of the batch which happens-after the wait on S so the signal happens-after the wait.  The "Semaphore Waiting" section says, of semaphore wait operations:

> Such semaphore wait operations set the semaphores created with a `VkSemaphoreType` of `VK_SEMAPHORE_TYPE_BINARY` to the unsignaled state.

I believe the understanding here should be that the wait+reset operation is roughly atomic in the sense that, by the time the wait has completed and work blocking on the wait is executing, the reset has occurred.  Therefore, the fact that the second signal happens-after the wait is enough to ensure that it's unsignaled in time.

**Comment by krOoze** [comment]
@jekstrand Well, that seems strained explanation to me; not sure I quite understood it. `vkQueuePresent` is in any rate a different batch from subsequent `vkQueueSubmit` , and it does not have any semaphores to signal.

What I am relying on for this is (Semaphore Signaling):

> The first synchronization scope includes [...] Semaphore signal operations that are defined by `vkQueueSubmit` or `vkQueueBindSparse` additionally include in the first synchronization scope any semaphore and fence signal operations that occur earlier in _signal operation order_.

> The signal operation order for queue operations is determined as follows:
> The initial order is determined by the order in which `vkQueuePresentKHR`, `vkQueueSubmit` [...]

> The second synchronization scope includes only the semaphore signal operation.

`vkQueuePresent` wait is before in signal order in my pseudocode. `vkQueueSubmit` signals its semaphores only after all semaphores before in signal order are resolved (i.e. the wait op in `vkQueuePresent` should be finished). Ergo I know `s` is unsignaled and not pending at the time the signal op is executed.

> the wait+reset operation is roughly atomic

I hope that was not in question. The spec calls it in sumary fashion "the semaphore wait operation" (previously "unsignal operation" IIRC). I assumed switching the semaphore state is part of execution of that operation, and have not really considered it confusing.

**Comment by jekstrand** [comment]
Sorry, I missed that we were dealing with `vkQueuePresent`.  That one is, indeed, trickier.  We don't have a lot of guarantees about when the semaphore wait operation in a `vkQueuePresent` occurs.

**Comment by krOoze** [comment]
Right, that's in #152. Though I think I have enough intuition now. If I weren't lazy I could finish #785.

**Comment by jekstrand** [comment]
We talked about this a bit on the call today.  The best advice we can offer at the moment is to keep your window system semaphores separate and have a semaphore per WSI image which you use for `vkQueuePresentKHR`.  Once you've gotten that image back from `vkAcquireNextImageKHR` *and* you've waited on the fence from `vkAcquireNextImageKHR`, it should be safe to re-use the semaphore.  Prior to that, it's hard to say for sure.  Some implementations may be fine and others may have issues.

The primary difficulty here is that, even though `vkQueuePresentKHR` looks like a queue operation, it's actually handing stuff off to an external process to execute in some other process' queue.  This makes it all very annoying to spec.  @cubanismo has a plan for an extension which will hopefully make this stuff more well-defined but it's still in-progress.  Unfortunately, what I suggested above is probably the best you can do with the current spec.

**Comment by krOoze** [comment]
So you are saying the original example is not valid after all?

**Comment by jekstrand** [comment]
> So you are saying the original example is not valid after all?

Correct.  On some implementations (including Intel and RADV linux; not sure about others) it does work because we have to do the semaphore wait on the queue itself before handing off to the window system due to limitations with the X server and DRI3 protocol.  On others, it may not be so generous.  It's certainly not guaranteed to work by the spec.

**Comment by krOoze** [comment]
> It's certainly not guaranteed to work by the spec.

I could be easily mislead that it is. I quote the relevant parts above.
Then I do not understand why ` vkQueuePresentKHR` is listed in the Signal Operation Order.

**Comment by jekstrand** [comment]
>  Then I do not understand why vkQueuePresentKHR is listed in the Signal Operation Order.

That was my mistake.  After our teleconference discussion today, I realized that I probably should not have put it in there.

> PS: Also point of the semaphore from vkAcquireNextImage is I do not have to wait on the host. If I have to use fence wait anyway before I can reuse present semaphore that's weird. Also in that case, why is not fence to vkAcquireNextImage mandatory by VU?

Yes, it's all very weird and terrible and we're sorry.  Sadly, that's the state we're in :frowning:

**Comment by krOoze** [comment]
I see. Then I have a bunch of people to unmislead...

**Comment by krOoze** [comment]
PS: I assume then the same as in #1059 applies? `vkDeviceWaitIdle()` would not work for `vkQueuePresent`?

**Comment by cubanismo** [comment]
Need to confirm with the rest of the group, but my understanding is vkDeviceWaitIdle() does make it safe to delete the semaphores passed to a prior vkQueuePresentKHR() function.  Unlike vkAcquireNextImageKHR(), vkQueuePresentKHR() is a queue operation, at least in part, and the parts that aren't are supposed to be the implementation's responsibility to track as far as object lifetimes.

That seems like it covers the more egregious hypothetical side effects brought up in the last comment too.

**Comment by cubanismo** [comment]
Note my explanation above may require disconnecting "safe to delete" from "safe to re-use", which I think are nicely packaged together in the semaphore behavior definitions at the moment.  That's just not how WSI works in practice though, and that tends to get ignored whenever anyone tries to neatly reorganize the definitions of synchronization behavior in the spec.  I think there's probably more discussion necessary here.

**Comment by krOoze** [comment]
`vkQueuePresentKHR` was removed from _Signal operation order_ in 1.2.132. So I suppose this can be closed.
