### ISSUE TITLE
Inline Ray Tracing and Compute Shaders

### ISSUE THREAD

**Issue by helixd-2k18** [KhronosGroup/Vulkan-Docs#1155]
DirectX 12.1 (Windows 10 20H1) already added Inline Ray Tracing for other shaders stages... 
I want discuss and propose to add Ray Tracing in Vulkan API Compute Shaders...

**Comment by krOoze** [comment]
Any chance to get intersection ops and other constituent parts of the raytracing black-box into normal shaders?

**Comment by TomOlson** [comment]
Thanks for this input - developer requests and feedback are important in helping us prioritize what we work on.  As you probably know (see e.g. [this comment on #686]( https://github.com/KhronosGroup/Vulkan-Docs/issues/686#issuecomment-538482022)), there’s a Vulkan TSG working actively on ray tracing extensions for Vulkan, and the functionality of inline ray tracing is within the scope of what they’re looking at. While I can’t commit to a timeline or specific details, they are fairly far along in the process. If there is more you can tell us about your use cases or your experience with this functionality in DX, we’d be interested in hearing about it.

**Comment by dgkoch** [comment]
Hi @helixd-2k18 we believe this should be address with the Ray Query functionality in the provisional Vulkan ray tracing extensions that we released today. See #1205 and provide feedback via #1206

**Comment by pdaniell-nv** [comment]
For those wanting to play with [Ray Queries](https://www.khronos.org/blog/ray-tracing-in-vulkan#raytracing3b), support can be found in NVIDIA's latest beta driver here:  
https://developer.nvidia.com/vulkan-driver
