### ISSUE TITLE
The wiki full barrier lists all access flags instead only ACCESS_MEMORY_*

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1156]
@Tobski Is there a reason the [full barrier in wiki](https://github.com/KhronosGroup/Vulkan-Docs/wiki/Synchronization-Examples#full-pipeline-barrier) lists all access flags instead of simply `VK_ACCESS_MEMORY_*_BIT`?

Also the wiki should probably be transfered to the new materials repo.

**Comment by Tobski** [comment]
At the time I wrote that it was because there was still some confusion about what the MEMORY* bits meant, and it’s probable there are still implementations out there which don’t implement those properly.

As for moving it, the plan is to move it to the Vulkan guide repo at some point.

**Comment by Tobski** [comment]
Assuming from your :+1: that you're happy with my response, so closing - feel free to reopen if there's something you feel still needs addressing.

**Comment by krOoze** [comment]
Sounds sensible explanation. Could be directly in the wiki though.

TBH I would prefer if we could pretend non-conformant drivers do not exist though.
