### ISSUE TITLE
Error compiling on linux

### ISSUE THREAD

**Issue by cwabbott0** [KhronosGroup/Vulkan-Docs#116]
When compiling on Linux, I get an error like:

/home/cwabbott/code/vulkan-demos/shadowmapping/shadowmapping.cpp: In function ‘void handle_event(const xcb_generic_event_t*)’:
/home/cwabbott/code/vulkan-demos/shadowmapping/shadowmapping.cpp:1177:18: error: ‘class VulkanExample’ has no member named ‘handle_event’

the function is unused, so if I delete it everything compiles, but it seems like something's missing since there's also WIN32 event handling code that's a little different.

**Comment by ratchetfreak** [comment]
probably a missing missing ifdef. But that should probably be reported on the proper github, this one is for the docs and the vulkan.h header. Your code comes from the samples repo.

**Comment by cwabbott0** [comment]
sorry, wrong repo :(
