### ISSUE TITLE
Typo in synchronization example

### ISSUE THREAD

**Issue by alek314** [KhronosGroup/Vulkan-Docs#1166]
In the “Transfer dependency, upload data from cpu to image” section, after the transfer is finished, in the second branch (transfer and graphics are different queue), one can find the following code:
> VkImageMemoryBarrier postCopyMemoryBarrier = {
        ...
        .srcAccessMask = 0,                           
        .dstAccessMask = VK_ACCESS_SHADER_READ_BIT,
        .oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
        .newLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
        .srcQueueFamilyIndex = transferQueueFamilyIndex,
        .dstQueueFamilyIndex = graphicsQueueFamilyIndex,
        .image = image,
        .subresourceRange = ... }; 

The sample code has transfer the layout from dst-optimal to read-only-optimal in the transfer queue already(using postCopyMemoryBarrier, which has the same name with the above barrier), why do we need to do a layout transfer again in the graphics queue again
? Is that a typo? Thank you.

**Comment by krOoze** [comment]
Queue Family Ownership Transfer chapter of the specification:

> If the transfer is via an image memory barrier, and an image layout transition is desired, then the values of `oldLayout` and `newLayout` in the release memory barrier **must** be equal to values of `oldLayout` and `newLayout` in the acquire memory barrier. Although the image layout transition is submitted twice, it will only be executed once.

**Comment by procedural** [comment]
Fun fact: the spec never mentions the existence of "release memory barrier" and "acquire memory barrier" until that one sentence.

**Comment by krOoze** [comment]
@procedural Fun fix: #1171

**Comment by procedural** [comment]
@krOoze thanks :)

**Comment by krOoze** [comment]
@Tobski In the wiki `VkImageMemoryBarrier postCopyMemoryBarrier` is declared twice, so it would probably not compile if copy-pasted out. Could you fix that?
Otherwise I do not see any typo here, and this could be closed.

**Comment by Tobski** [comment]
Done. I think that takes care of everything on this issue...?
