### ISSUE TITLE
vkAcquireNextImage is overburdened.

### ISSUE THREAD

**Issue by ratchetfreak** [KhronosGroup/Vulkan-Docs#117]
`vkAcquireNextImage` blocks if no image is ready and a timeout is set. However you can pass a fence that gets signaled when the image does become ready.

This seems to result from a change in the semantics according to the version history. It was originally meant to block until the image was ready (concerning [issue 7](https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#_issues_2) in the spec). However [Revision 56, (2015-09-18)](https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#_version_history_3) added the fence argument which makes the blocking behavior redundant.

As it stands now it's unclear exactly what happens if an image is not ready (but will be soon) and you call `vkAcquireNextImage` with various timeout values and whether or not you provide a semaphore and/or fence.

Similarly it is unclear when an image is actually owned by the application for a given return value.

I propose to remove the timeout parameter and turn the operation into one that never blocks. 

If no semaphore and no fence is provided it will only return `VK_SUCCESS` if an image is ready and its index is passed back through `pImageIndex`. The image can be used immediately. If no image is ready then it will return `VK_NOT_READY` and no image is reserved.

if any of the two is provided then it will not block and return `VK_SUCCESS` if the swapchain can reserve an image, the reserved image's index is passed back through `pImageIndex`. The image cannot be used until after the semaphore or fence is signaled. If no image can be reserved then it will return `VK_NOT_READY` and no image is reserved.

`VK_ERROR_SURFACE_LOST_KHR` and `VK_ERROR_OUT_OF_DATE_KHR` both will not reserve an image. `VK_SUBOPTIMAL_KHR` will reserve an image with the same semantics as if it had returned `VK_SUCCESS`.

This simplifies behavior on both sides.

**Comment by jjulianoatnv** [comment]
Thank you for this insightful feedback.

You raise good points. Some of this was already under discussion within Khronos. Some of it goes beyond what we were already discussing. I've broadened our discussion to include those additional details.

**Comment by ratchetfreak** [comment]
There is a related issue, when using mailbox and with 3 or more images there is no way to meter your renders to the framerate. Because there will always be an image ready for the application to use.

So there is no way to to know when vblank happened.

**Comment by jjulianoatnv** [comment]
Noted. Thank you again for valuable feedback.

The points you raise are still on the agenda within Khronos. Things moved slowly the last couple weeks due to the conferences and other agenda topics.

**Comment by ianelliottus** [comment]
Hi @ratchetfreak ,

I apologize that I've been so busy that I've ignoried this issue.  I finally read it (as opposed to the internal-to-Khronos discussion), and think I can help.  The original author of that timeout is on a leave right now, but I was part of all of these conversations.  I'll see if I can shed some light on this.


> vkAcquireNextImage blocks if no image is ready and a timeout is set. However you can pass a fence that gets signaled when the image does become ready.
> 
> This seems to result from a change in the semantics according to the version history. It was originally meant to block until the image was ready (concerning issue 7 in the spec). However Revision 56, (2015-09-18) added the fence argument which makes the blocking behavior redundant.

Actually, the timeout and semaphore/fence have nothing to do with each other.  The fence and the semaphore must be used to know when the image is actually owned by the app (i.e. can be transitioned and rendered to).  The timeout controls how long the vkAcquireNextImageKHR command will wait for an image to become available (even though it may not be owned by the app at the time the command returns).

Assuming no OUT_OF_DATE or SUBOPTIMAL occurs, if timeout is 0, either an image will be available (i.e. VK_SUCCESS), or it won't (i.e. an error).  If timeout is infinite, the command waits until an image is available.  If the timeout is somewhere between 0 and infinite, a VK_TIMEOUT error will occur if the command waits for the timeout and no image is available.  In either non-0 case, if an image becomes available, the command returns with VK_SUCCESS.  Once an image is available, the app must still wait for the semaphore and/or fence before the image is owned by the app.

> I propose to remove the timeout parameter and turn the operation into one that never blocks.

First, we are past the time where incompatible changes like this can be made.  Second, I hope that my clarification (above) helps in terms of how vkAcquireNextImage is meant to work.  If not, please ask some additional questions.  I promise to try to respond more promptly!

Best regards,
Ian

**Comment by ratchetfreak** [comment]
I see, the command waits until it can guarantee an image and if it didn't time out uses the fence and semaphore to signal when the image is ready to be rendered to.

You also seem to imply that you *need* a fence or a semaphore. Even though the spec doesn't say anything about that, currently you can pass NULL for both.

That's something that needs clarifying in the spec. 

---

I know it's not possible to include such a breaking change in a patch version. That proposal was something for 1.1.

**Comment by jjulianoatnv** [comment]
After your suggestion in the first comment of this issue I have been in favor of modifying the behavior of vkAcquireNextImageKHR when both the fence and semaphore are NULL. However, as has been pointed out, it is past the time where incompatible changes like this can be made in 1.0.

Quoting myself from internal discussion:
> The poster suggests that if vkAcquireNextImageKHR is called with NULL semaphore and fence, then the semantics of vkAcquireNextImageKHR in that case should be modified to block (with timeout) until the semaphore/fence would have been signaled. That way an app can immediately begin using the returned image.
> The poster has a good point. It does not seem useful for vkAcquireNextImageKHR to return an image when both semaphore and fence are VK_NULL_HANDLE. I don't see a way that the application can safely use the image in this case.
> On the other hand, I do not want to encourage, and maybe even want to disallow, apps to call vkAcquireNextImageKHR in such a way that causes the ICD to block on a sync object

For 1.0 it would be good if a validation layer warns when semaphore and timeout are both VK_NULL_HANDLE. I looked at the swapchain validation layer and, by code inspection, I think it does not check for this condition. I did not check any other validation layers.

**Comment by ratchetfreak** [comment]
But if you can't safely use the image if both semaphore and fence are null then it should be disallowed or we should at least discourage the application from doing so. The spec should at least mention that providing null for both is not useful. 

Though technically if you vkDeviceWaitIdle you would be able to use the image. At least I think so, vkDeviceWaitIdle is defined in function of the queues and vkAcquireNextImageKHR doesn't use a queue. Either way doing so is not recommendable.

**Comment by ianelliottus** [comment]
> You also seem to imply that you need a fence or a semaphore. Even though the spec doesn't say anything about that, currently you can pass NULL for both.

Hmm.  I was going off of recollection (I'm one of the authors of this:-).  However, changes occurred over time (e.g. the fence parameter was added), and so I looked more carefully.  The following language (further down) may help ...

    When the application calls vkQueuePresentKHR, it releases ownership of the images referenced by imageIndices
    to the presentation engine. The presented images must not be used again until the application regains control of them
    using vkAcquireNextImageKHR (and waiting until the returned semaphore is signaled or fence is completed).

The original intention and language of the spec was that an application use the semaphore, so that the application be able to immediately start queueing the transition and rendering with the returned image.  As pointed out in other comments, an app could do something else in order to safely wait before using the returned image.  However, that's not an optimal way to use the API.  So, I may have overstated things because I see that as the only wise use of the API.

Later, the fence parameter was added, at the request of an ISV, in order to help with metering the application's rendering (using FIFO mode).  There should be example code that shows how to do this.  The fence can also be used as a replacement for the semaphore, but this wasn't the intention.  A fence is used for the CPU (i.e. app code) to sync with, while the semaphore is for the GPU to sync with.  Thus, if an app uses the semaphore, it can be as pipelined as possible.

Note: that there's a WSI appendix, where this are issues and example code, that can give further guidance.  The WSI part of the spec was originally written as some stand-alone documents.  These were reorganized to become part of the Vulkan spec.  You will find some useful info there, including issue 10 that asks " Does the vkAcquireNextImageKHR command return a semaphore to the application via an output parameter, or accept a semaphore to signal from the application as an object handle parameter?"

There are other subtleties that we discussed when this was being defined.  We should probably discuss these sometime in the spec, or an app-writer's guide.

> That's something that needs clarifying in the spec.

I agree.  I'll try to work with the rest of the WSI group to add some clarifications.

> I know it's not possible to include such a breaking change in a patch version. That proposal was something for 1.1. 

I think you have good intentions, and perhaps we could (if desired) add a new function that behaved in the way you want.  However, breaking backwards compatibility would require bumping to 2.0, and would change the ABI versioning number of the Windows/Linux loader shared libaries.  Besides, I hope that you are convinced that an app really wants to use a semaphore, to be as pipelined as possible.

Thanks for your thoughtful comments and questions!

**Comment by ianelliottus** [comment]
> For 1.0 it would be good if a validation layer warns when semaphore and timeout are both VK_NULL_HANDLE. I looked at the swapchain validation layer and, by code inspection, I think it does not check for this condition. I did not check any other validation layers.

I agree.  I think that the swapchain layer is the correct place to check this.  I'll double-check whether the param_checker should do this first, but plan on adding this check today.

**Comment by ianelliottus** [comment]
> I agree. I think that the swapchain layer is the correct place to check this. I'll double-check whether the param_checker should do this first, but plan on adding this check today.

I created pull request 167 to add this to the swapchain validation layer.  If you'd like to review it, please see https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/167

I think the change is fairly straight-forward, and so I plan to push this change after today's WSI meeting (around 16:30 UTC) unless I hear objections.  Even after I push it, I can always change it:-).

**Comment by ianelliottus** [comment]
I pushed the fix in pull request 167, changing it from a warning to an error, after a good discussion in the WSI meeting today.

We agreed that the spec should be changed to state that the app must set at least one of semaphore and fence.  It wasn't clear to me if @jjulianoatnv was going to include that as part of an MR that he was going to do for a related, internal-to-Khronos issue.  Either way, Jeff and I will work to make sure we improve the spec.  Thanks again @ratchetfreak !

**Comment by ratchetfreak** [comment]
No problem.

The behavior of vkAcquireNextImageKHR when passing 0 for timeout now matches my proposal (when a semaphore or fence are passed).

**Comment by oddhack** [comment]
Partly dealt with in the 1.0.8 spec update, still working on some aspects.

**Comment by ratchetfreak** [comment]
A few things for the next iteration at least:

Valid Usage is missing some return values, namely timeout and suboptimal.

**Comment by ianelliottus** [comment]
If I'm looking at the same box you are, it looks like VK_TIMEOUT was left out (good catch).  VK_SUBOPTIMAL_KHR is there (it's a success code).  Do you also see that?

Also, I'm moving the validity for vkAcquireNextImageKHR up to where it should be--right after the parameters.

**Comment by ratchetfreak** [comment]
Must have looked over that one. Even though I triple checked that...

I'll note that having such a long explanation (where most functions have 1 or 2 paragraphs outside the parameter descriptions) is a symptom of a function being too complicated or trying to do too much.

I'm still convinced that the timeout/blocking behavior doesn't belong in vkAcquireNextImage and that a proper/explicit "vsync happened" event (like a fence that gets signaled when a present completes) is missing and can replace the blocking behavior. Especially if you add some semantics where guarantees can be made about availability of the next image.

**Comment by jjulianoatnv** [comment]
Fundamentally there are three timelines.

- CPU timeline: commands get queued here
- GPU timeline: queues execute here
- Presentation Engine (PE) timeline: outside of Vulkan

Section 6.6 of the core Vulkan spec explains how semaphores can be used to create dependency chains on the GPU timeline, and how fences can be used to synchronize the GPU and CPU timelines.

The PE timeline is separate from Vulkan. AcquireNextImage and QueuePresent provide a mechanism to synchronize the CPU and GPU timelines with the PE timeline.

- AcquireNextImage's semaphore can be used in a dependency chain to express a dependency on acquiring an image from the PE.

- AcquireNextImage's fence can be used to synchronize CPU operations with acquiring an image from the PE.

- A wait semaphore passed into QueuePresent makes the PE wait on a Vulkan dependency chain.

The timeout parameter to AcquireNextImage serves none of these functions.

AcquireNextImage interfaces with the PE in the following ways:
- Gets from the PE the index of an acquired image
- Arranges for the PE to signal a Vulkan semaphore and/or a Vulkan fence when it is safe for the Vulkan application to operate on the image.

AcquireNextImage is supposed to return the image index as soon as it has accomplished these things. The timeout parameter to AcquireNextImage bounds how long AcquireNextImage can wait to acquire an image from the PE.  

If fence and semaphore are not already signaled by the end of AcquireNextImage then it is the PE that asynchronously signals the semaphore and fence.  Stated another way, the semaphore passed into AcquireNextImage can extend a Vulkan dependency chain such that the dependency chain waits for the PE to signal semaphore. It is not AcquireNextImage's responsibility to block until the PE has signaled.

E.g., on some platforms it may be illegal for the app to attempt to queue a wait operation for the VkSemaphore prior to the PE having queued a signal operation for the platform's underlying sync primitive.  On such a platform AcquireNextImage would wait (with timeout) until the PE has queued a semaphore signal operation. But AcquireNextImage would not wait for the semaphore to transition to the signaled state--the app does that through its execution dependency chain.  The PE might not be able to queue the signal operation until e.g. the next vblank event.

Today I signed up to create an MR that describes the interaction between the Vulkan core concept of dependency chains and the semaphore and fence objects used with AcquireNextImage and QueuePresent. The WSI extension language predates the dependency chain language from section 6.6 "Implicit Ordering Guarantees". I want to restate the WSI synchronization requirements in terms of those core concepts.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.9 spec update.
