### ISSUE TITLE
Documentation for VK_EXT_provoking_vertex ?

### ISSUE THREAD

**Issue by Degerz** [KhronosGroup/Vulkan-Docs#1173]
I realize that this extension is not in the Vulkan headers but is it possible that we can get public information ? It is already being put to use for software rendering like ANGLE's SwiftShader backend and I believe all desktop IHVs can support both the first and last vertex as the provoking vertex. Also do IHVs have any plans to potentially support this functionality in Vulkan ? 

For API comparison purposes, in D3D, Metal, and Vulkan the first vertex is always the provoking vertex while in OpenGL both the first vertex or the last vertex can be the provoking vertex.

**Comment by critsec** [comment]
The ANGLE and Swiftshader code is a prototype meant to inform and validate an actual extension spec. That should be coming soon, but we're following our normal practice of not releasing the spec or headers until we've validated that spec, tests, and multiple implementations all agree; we're mostly there but do have one open issue with the spec.
