### ISSUE TITLE
Semantics of "Events" are ambiguous

### ISSUE THREAD

**Issue by magcius** [KhronosGroup/Vulkan-Docs#1178]
> 6.5. Events
> Events are a synchronization primitive that can be used to insert a fine-grained dependency between commands submitted to the same queue, or between the host and a queue. Events must not be used to insert a dependency between commands submitted to different queues. Events have two states - signaled and unsignaled. An application can signal an event, or unsignal it, on either the host or the device. **A device can wait for an event to become signaled** before executing further operations. No command exists to wait for an event to become signaled on the host, but the current state of an event can be queried.

Ambiguous wording highlighted in bold. A casual reading would imply what the API can and can't do. But a more careful reading suggests devices are allowed to ignore events entirely.

Is a device allowed to NOT wait for the event before executing further operations?

**Comment by krOoze** [comment]
"**can**" always addresses the application, as specified in the 1.1.1. Normative Terminology chapter.

Still the sentence could be improved to be more english...

**Comment by magcius** [comment]
The proposed wording doesn't seem to answer my question. Either that, or I need more practice reading spec-ese. Is the former or the latter interpretation correct?

**Comment by krOoze** [comment]
AIS above, "**can**" in this specification always addresses the application. It is something you can do using the Vulkan API. It is just an introductory (practically non-normative) paragraph saying there exists a `vkCmdWaitEvents` command. And you **can** call that command to make the device wait for event signal.

> Is a device allowed to NOT wait for the event before executing further operations?

that would be "device **may** wait for an event to become signaled".
