### ISSUE TITLE
Vector alignment in Standard Buffer Layout issue

### ISSUE THREAD

**Issue by kennyalive** [KhronosGroup/Vulkan-Docs#1183]
Spec version 1.2.132. Section 14.5.4. Offset and Stride Assignment, Standard Buffer Layout section.
It defines struct member alignment according to the **first matching rule**.  The first two rules are:

> 1. If the scalarBlockLayout feature is enabled on the device then every member must be aligned according to its scalar alignment.
> 2. All vectors must be aligned according to their scalar alignment.

Consider struct member of vector type. If scalarBlockLayout is disabled then rule 2 is the first matching rule and it says that alignment of float3 is 4, so it can intersect 16 bytes boundary. This is incorrect if scalarBlockLayout is not enabled. 

It looks like *rule 2* is based on vulkan 1.1's VK_KHR_relaxed_block functionality but that extension only states that we can have { float; float3} without padding but still doesn't allow 16 bytes crossing.

**Comment by kennyalive** [comment]
Not an issue. Few lines after that the spec says "*Unless the scalarBlockLayout feature is enabled on the device: Vectors must not improperly straddle, as defined above.*". 

**But!** :)
It's still  confusing when at first you read a statement that is not correct in general and later in text additional restriction is provided that makes the previous statement valid.

**Comment by kennyalive** [comment]
I've decide to re-open for visibility, it's very easy to be confused by the rule 2, nothing suggests there's more to it and you need to read to the end of the section.

**Comment by oddhack** [comment]
Do you have an idea on how to improve this language? We think it's pretty easy to confuse this section in other ways by shifting around the "Unless" comment but we're if you have a specific suggestion to evaluate, by all means please propose a PR.

**Comment by kennyalive** [comment]
Here's the idea. The rule 1 in the list of the *first matching rules* specifies alignment rule for every struct member when scalarBlockLayout  is enabled. If rule 1 was not selected as the first matching rule it means all subsequent rules can assume that scalarBlockLayout is not enabled, and **there is no way for rule 2 to be applied in the context when scalarBlockLayout is enabled**, so I think we can say for rule 2 that **vectors must be aligned according to their scalar alignment and must not improperly straddle**. With this change rule 1 + rule 2 will handle all vector types (we can't reach 3 or 4 for vector type) and that means we can remove *Vectors must not improperly...* item from the *Unless* section.
