### ISSUE TITLE
Unspecified WSI coordinate system origin?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1191]
I cannot find in the specification how is a `VkImage` interpreted by the presentation engine. I.e. in what corner of the surface\window\display would a texel (0,0) show up.

Is this trully unspecified and implementation dependent (in which case I think there should be a Note)? Or is this an omission?

**Comment by stonesthrow** [comment]
WSI WG discussed this today. There are many places in vulkan we do specify the upper left. However the Presentation Engine is platform specific and defines it's origin, typically upper-left. We decided a note to clarify this would be good - it is according to the native window system.
@krOoze , would you like to propose a note in the spec? (PR)

**Comment by krOoze** [comment]
>  would you like to propose a note in the spec? (PR)

I guess. For the purposes of writing a Note, may I assume all the current WSI platforms are upper-left by default?

I am also thinking if it would make sense to just fix that to upper-left, and instead handle any quaint platform with having appropriate `VkSurfaceCapabilitiesKHR::currentTransform`.

**Comment by stonesthrow** [comment]
The note should say that origin is window system specific, but typically this is the upper-left. thanks.

**Comment by krOoze** [comment]
IDK, "typically" is non-information. How should one know which platform is "typical" and which is not?

What about the suggestion? It seems `VkSurfaceCapabilitiesKHR::currentTransform` can already express upside-down image. Wouldn't it then make more sense to simply make Vulkan always upper-left?
