### ISSUE TITLE
Layout transitions vs execution dependency chain: convoluted specification?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1193]
I think there is a spec hole in the dependency chain definition.

The dependency chain is basically defined as:
If there are two dependencies chained, then it is as if there is a single dependency that has src scope of the first dependency and dst scope of the second dependency.

That poses the problem if those dependencies define a layout transition, which is defined to happen before src scope and dst scope of the dependency. That means the layout transition of the first dependency could happen at the same time the layout transition of the second dependency.

Of course, there's this gem:

> Layout transitions that are performed via image memory barriers execute in their entirety in submission order, relative to other image layout transitions submitted to the same queue, including those performed by render passes. In effect there is an implicit execution dependency from each such layout transition to all layout transitions previously submitted to the same queue.

Then again, there might not be two layout transitions. The situation can be a semaphore wait and a barrier with layout transition, e.g.:

```
VkCommandBuffer cb;
vkCmdPipelineBarrier(cb, srcStage = CS, srcAccess = 0, dstStage = DS, dstAccess = DA, newLayout=NL);

pWaitDstStageMask = CS;
vkQueueSubmit(pWaitDstStageMask, cb);
```

Now there seems to be a subset, which is anything in the batch before the `vkCmdPipelineBarrier` limited to stage CS. So an execution dependency chain is formed.

That chain seems to guarantee the semaphore signal happens-before the dst scope of the barrier. But I do not see a dependency between the signal and the layout transition.

Now, layout transition is specified to happen-after the availability operation:

>When a layout transition is specified in a memory dependency, it happens-after the availability operations in the memory dependency, and happens-before the visibility operations. Image layout transitions **may** perform read and write accesses on all memory bound to the image subresource range, so applications **must** ensure that all memory writes have been made available before a layout transition is executed.
>
> Automatic layout transitions away from `initialLayout` happens-after the availability operations for all dependencies with a srcSubpass equal to VK_SUBPASS_EXTERNAL

Which kinds sorta probably can be made true if we invoke the _memory dependency_ specification of the _execution dependency chain_:

> - Memory dependency **m** guarantees that:
>   - Memory writes in **a'** are made available.

Though it is not immediatelly obvious the above layout transition definitions mean **this** availability operation.

<hr>

I find the part where _memory dependency_ is described only in the terms of the _execution dependency chain_ bit convoluted. I think the dependency could be defined in isolation in terms of a single dependency, if execution dependency chain is also tweaked:

Also I think it would make things much simpler if _execution dependency chain_ descriptions simply said that "source scope **and** operations invoked by the first dependency (such as layout transitions) happen-before destination scope **and** operations invoked by the second dependency.

Would such formalism mean the same thing as the original?

**Comment by Tobski** [comment]
> That poses the problem if those dependencies define a layout transition, which is defined to happen before src scope and dst scope of the dependency. That means the layout transition of the first dependency could happen at the same time the layout transition of the second dependency.

Possibly key point here - image layout transitions happen _after_ the source scope, not before it.

If you see something in the spec suggesting otherwise please point me at it so I can blew it to smithereens...

I can't tell how much of your issue is affected by that clarification but I think it's not insignificant, so I'll let you respond before I tackle the rest.

**Comment by krOoze** [comment]
> Possibly key point here - image layout transitions happen after the source scope, not before it.

of what? "the dependency". That is suggestive. I could read it like "the src scope of specifically the `VkSubpassDependency`.

Which is the problem. If source scope of the `VkSubpassDependency` is `VK_STAGE_NOTHING` and `VK_ACCESS_NOTHING`, then the layout transition has unlimited range in which it can happen.

Then if such `VkSubpassDependency` is chained to e.g. a Semaphore wait, then execution dependency is not established between the semaphore signal op and the layout transition. Because the execution chain is defined **only** in the terms of src scope of the Semaphore wait and dst scope of the `VkSubpassDependency`. It does not consider any ops the `VkSubpassDependency might generate (the layout transition).

Even if I interpret the spec "better", I think it would still be much clearer formalism if this was covered directly by _execution dependency chain_ definition. I.e. that the execution dep. chain would include any opt the sync primitives might generate too (like the layout transition). Otherwise it necessitates some spec hacks like the _implicit layout transition order_, and perhaps the _signal order_ too.

**Comment by Tobski** [comment]
> of what? "the dependency". That is suggestive. I could read it like "the src scope of specifically the VkSubpassDependency.

I'm not sure I follow - when did we start talking about subpass dependencies? I meant very specifically that if you have a single pipeline barrier that defines a layout transition, the order of operations is:

1. prior operations in src scope
2. availability operations
3. layout transition
4. visibility operations
5. subsequent operations in dst scope  

From this sentence in the layout transitions section:

> When a layout transition is specified in a memory dependency, it happens-after the availability operations in the memory dependency, and happens-before the visibility operations

And earlier in the spec it states that av/vis operations happen between src and dst scope too, completing the ordering.

The same rough thing applies to subpass dependencies but that chapter is garbage so I'm not going to attempt to quote it 😛 

>  then the layout transition has unlimited range in which it can happen.

Yes, that's exactly the case, ish. Firstly there's no "NONE" stage - it's TOP or BOTTOM. Semaphore signals include _everything prior_ in their scope, and semaphore waits include everything afterwards within the specified destination scope - noting that this scope will always include execution of BOTTOM due to pipeline stage logical ordering.

>  Because the execution chain is defined only in the terms of src scope of the Semaphore wait and dst scope of the VkSubpassDependency

I assume you mean destination scope for the wait, source scope for the VkSubpassDependency?

> I think none

Well it looks like there were some more missing pieces there, so let's try again 😬 

I can buy that something is unclear in the spec, I'm just not sure specifically what that is yet.

**Comment by krOoze** [comment]
> when did we start talking about subpass dependencies?

It doesn't matter here. Barriers and SBs are virtually the same thing, except perhaps SBs are more frequently used.

My point was the spec can be interpreted in a way that the availability operation of one of the dependencies in a dependency chain can happen whenever wrt to the other dependency, therefore potentionally forming a memory hazard.

> if you have a **single** pipeline barrier that defines a layout transition, the order of operations is:

That was not in question. The fun starts when there are two (and more) interacting dependencies.

>  Firstly there's no "NONE" stage - it's TOP or BOTTOM.

Yea, obviously. I am just making things clear. I don't like `TOP` and `BOTTOM`. What I mean is `srcStage=VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT`. Which is the same thing as hypothetical `VK_PIPELINE_STAGE_NO_COMMANDS_BIT`.

> Semaphore signals include everything prior in their scope, and semaphore waits include everything afterwards within the specified destination scope

Sure, but that is colloquial intuition. You might have surprisingly hard time supporting this from spec. Also might have hard time defining what "everything" means.

Specifically in the semaphore wait. There is a `pWaitDstStage`, so you cannot just say "everything". If by "everything" you mean action commands, then that is clear. But sync commands are (unfortunately for simplicity) special. They are not covered by synchronization scopes. Instead they have their own language specifying how they interact: the dependency chains, and the signal op order.

>>Because the execution chain is defined only in the terms of src scope of the Semaphore wait and dst scope of the VkSubpassDependency
>
>I assume you mean destination scope for the wait, source scope for the VkSubpassDependency?

Nope. That is exactly the problem. If it would defined as you say, then it would be nice and clear.

But the execution dependency chain **is** defined in the terms of src scope (sic) of the Semaphore wait and dst scope (sic) of the `VkSubpassDependency` (resp. Barrier). If a chain is formed, it means stuff in the src scope of the first dependency happens-before the stuff in dst scope of the second dependency. But layout transition happens before dst scope of the second dependency, therefore **execution** dependency chain in of itself does not help to cover it. Should probably quote the language:

> An execution dependency chain is a sequence of execution dependencies that form a happens-before relation between the first dependency’s **A'** and the final dependency’s **B'**. [**A'** and **B'** being practically what I said above]

Now If I squint my eyes really hard, I could hallucinate it still works out as intended after reading "memory dependency of an execution dependency chain". But at best that is ambiguous. And as the title says, it seems unnecessarily convoluted and I think I can imagine simpler formalism.

**Comment by Tobski** [comment]
Can you write down an rough example of code you think exhibits a memory hazard? Because I still don't see it from your description, and it feels like there's a disconnect here between what each of us is saying...

**Comment by krOoze** [comment]
Scenario 1:

```
VkImage i;
vkCmdPipelineBarrier(
    .dstStage=COLOR_STAGE,
    .dstAccess = 0,
    .newLayout = LAYOUT_WHATEVER,
    .image = i
);
vkCmdPipelineBarrier(
    .srcStage=COLOR_STAGE,
    .srcAccess = 0,
    .oldLayout = LAYOUT_WHATEVER,
    .newLayout = COOL_LAYOUT,
    .image = i
);
```

The spec does not make clear the two layout transitions do not clash except the:

> Layout transitions that are performed via image memory barriers execute in their entirety in submission order, relative to other image layout transitions submitted to the same queue, including those performed by render passes.

Which honestly feel like a spec hack. But I can even get around that hack by replacing one of the barriers by something else:

Scenario 2:
```
// Presentation engine reads image
VkSemaphore s;
VkImage i;
vkAcquireNextImage( s, i );

VkCommandBuffer cb;
vkCmdPipelineBarrier(
    cb,
    .srcStage=COLOR_STAGE,
    .srcAccess = 0,
    .oldLayout = LAYOUT_WHATEVER,
    .newLayout = COOL_LAYOUT,
    .image = i
);
vkCmdCoolCommand(cb);

vkQueueSubmit( cb, .pWaitDstStages=COLOR_STAGE );
```

It is not unabiguously clear from spec that the presentation reads happen-before the layout transition starts. From spec it is only clear that the presentation reads happen-before the cool command.

**Comment by krOoze** [comment]
I think #1348 technically handles most of it.

That the specification is convoluted on the point I thiks still stands. Which creates mild ambiguities here and there. I think there might be a better and simpler way to specify sync, but I don't have any idea for atomic and small limited change that could improve this. So I think unless anyone feels like rewriting the sync system spec (again), then this is not actionable.
