### ISSUE TITLE
Move extensions to their own (separate) page

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Docs#1195]
Would it be possible to move the extensions to a separate page? With the current structure of the specs, getting to the extension inside the specs e.g. from the links via the [Vulkan Registry](https://www.khronos.org/registry/vulkan/) takes ages as it needs to load the whole HTML spec. Even on a capable desktop PC this takes extremely long (20~30 Seconds, and sometimes won't even jump to the extension's anchor), on mobile it's almost impossible to get there. 

Having the extensions separated so you can quickly access the extension spec from e.g. the Vulkan registry would be very much appreciated, and is something that's also often coming up at public discussions.

**Comment by SaschaWillems** [comment]
It seems there's already something similar. If you manually change the link in the extension registry to have vkspec replaced with chap44 you get there a lot faster: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap44.html#VK_EXT_acquire_xlib_display

So maybe another option would be to just change the links in the Vulkan Registry?

**Comment by oddhack** [comment]
This is an ongoing discussion inside the working group, and I expect we will do something like thispretty soon. My personal preference is to split out the per-extension sections as refpages like the API refpages but we haven't settled on an answer yet.

**Comment by krOoze** [comment]
> Would it be possible to move the extensions to a separate page?

That's solving the symptom, not the problem. Could we just merge #704 and #708?
After that it takes about 8 seconds, of which over half seems to be the search box script, which will cost the same no matter how much paginated the spec is.

Anyway, try it here: http://vulkan.hys.cz/i1195/chap44.html#VK_EXT_acquire_xlib_display

> If you manually change the link in the extension registry to have vkspec replaced with chap44 you get there faster

That possibly makes sense though. Only problem is to make the chap44 constant somehow. That's problem of the `chunked`, that there can't be permalinks into it. Or it needs to manually change when new chapters are added.

**Comment by oddhack** [comment]
This has been addressed in the 1.2.136 spec update. The content of each extension appendix is now included in the corresponding per-extension refpage (for example: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_external_memory_win32.html), and the registry extension index links to those refpages instead of the full spec. There are still some issues with links to extension APIs that were promoted landing in the wrong place, which we'll address pretty soon, but it should be a significant improvement for quick reference purposes.
