### ISSUE TITLE
Inconsistency in Appendix A, wrt `KHR_buffer_device_address`

### ISSUE THREAD

**Issue by Hugobros3** [KhronosGroup/Vulkan-Docs#1199]
Being very interested in pushing Vulkan for compute, I recently started digging into `KHR_buffer_device_address` (now core in 1.2, thanks for that!) and the associated `SPV_KHR_physical_storage_buffer` spir-v extension. 

In particular, that extension introduces the `PhysicalStorageBuffer64` addressing model, to allow for a limited use of pointers in spir-v meant for execution in vulkan compute shaders. The spec mostly accounts for that, but I found that in Appendix A, section "Validation Rules within a Module", the following is said:

> The `Logical` addressing model *must* be selected.

Which would outright prevent using the newly added addressing model and render it useless.
This seems like an oversight, and a simple fix. Hopefully that's it and I'm not missing anything.

**Comment by jeffbolznv** [comment]
Agreed, I'll fix this.

**Comment by oddhack** [comment]
This should be fixed in the 1.2.135 spec update.
