### ISSUE TITLE
vulkan.h : VkPipelineCacheHeaderVersion enumeration 

### ISSUE THREAD

**Issue by AlessandroBorges** [KhronosGroup/Vulkan-Docs#12]
Hi !
at Vulkan.h header file we have the following enumeration:
///////////////////////////////////////////////////////
typedef enum VkPipelineCacheHeaderVersion {
    VK_PIPELINE_CACHE_HEADER_VERSION_ONE = 1,
    VK_PIPELINE_CACHE_HEADER_VERSION_BEGIN_RANGE =     VK_PIPELINE_CACHE_HEADER_VERSION_ONE,
    VK_PIPELINE_CACHE_HEADER_VERSION_END_RANGE = VK_PIPELINE_CACHE_HEADER_VERSION_ONE,
 **VK_PIPELINE_CACHE_HEADER_VERSION_RANGE_SIZE = (VK_PIPELINE_CACHE_HEADER_VERSION_ONE - VK_PIPELINE_CACHE_HEADER_VERSION_ONE + 1),** 
    VK_PIPELINE_CACHE_HEADER_VERSION_MAX_ENUM = 0x7FFFFFFF
} VkPipelineCacheHeaderVersion;
 ////////////////////////////////////////////////

Note that 
VK_PIPELINE_CACHE_HEADER_VERSION_RANGE_SIZE 
should be defined as 

(VK_PIPELINE_CACHE_HEADER_VERSION_BEGIN_RANGE  - VK_PIPELINE_CACHE_HEADER_VERSION_END_RANGE + 1)

instead of 
(VK_PIPELINE_CACHE_HEADER_VERSION_ONE - VK_PIPELINE_CACHE_HEADER_VERSION_ONE + 1)

Sounds silly, but once fixed, future versions would have only to update VK_PIPELINE_CACHE_HEADER_VERSION_END_RANGE value.

**Comment by AlessandroBorges** [comment]
This also happens with all other enumerations featuring *_BEGIN_RANGE / *_END_RANGE / *_RANGE_SIZE values..

**Comment by adamsmigielski** [comment]
Hi.

The header file is generated from xml file. The script and xml file are available in this repository.

I think that yours and current solution are equal.

**Comment by oddhack** [comment]
Adam is correct. The purpose of the BEGIN/END tokens is to give the valid range of core enumerant values of that type, which may be helpful with switch/conditionals on enum values in driver code. They are automatically updated from the XML whenever the header is regenerated, so there's no need to make it easier for the nonexistent editors of the header :-)
