### ISSUE TITLE
Editorial: term "subresource" never formally defined.

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#120]
The closest to a formal definition "subresource" gets is a parenthetical in this sentence:

> The layout of a subresource (mipLevel/arrayLayer) of an image

It's a very odd place for defining an important term like subresource. I would think that a more formal definition for it could be included at the top of Chapter 11, after the definition of "resource".

**Comment by oddhack** [comment]
Agreed. The glossary was constructed after the spec had been written so we've surely left other things out as well that are deserving of glossary entries, and more formal definitions in the body.

**Comment by oddhack** [comment]
Should have been fixed in the 1.0.10 spec update.
