### ISSUE TITLE
VK_STRUCTURE_TYPE_QUERY_POOL_PERFORMANCE_QUERY_CREATE_INFO_INTEL missing

### ISSUE THREAD

**Issue by archimedus** [KhronosGroup/Vulkan-Docs#1207]
I have tried to update in CTS  `vulkan_core.h` and `vulkan_beta.h` and VS complains:

```
Error	C2065	'VK_STRUCTURE_TYPE_QUERY_POOL_PERFORMANCE_QUERY_CREATE_INFO_INTEL': undeclared identifier
vkutilnoshader
\vk-gl-cts\external\vulkancts\framework\vulkan\vkGetStructureTypeImpl.inl	1581	
```

I suppose this is because of:

```
typedef VkQueryPoolPerformanceQueryCreateInfoINTEL VkQueryPoolCreateInfoINTEL;
```

gen_framework.py generates following:

```
template<> VkStructureType getStructureType<VkQueryPoolPerformanceQueryCreateInfoINTEL> (void)
{
   return VK_STRUCTURE_TYPE_QUERY_POOL_PERFORMANCE_QUERY_CREATE_INFO_INTEL;
}
```

and enum `VK_STRUCTURE_TYPE_QUERY_POOL_PERFORMANCE_QUERY_CREATE_INFO_INTEL` does not exist.

I suppose `VK_STRUCTURE_TYPE_QUERY_POOL_PERFORMANCE_QUERY_CREATE_INFO_INTEL = VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO_INTEL` should be added?

**Comment by oddhack** [comment]
This should be fixed in the 1.2.136 spec update.
