### ISSUE TITLE
Editorial issues in 1.0.5

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#121]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#pipelines-cache says:

> This field is interpreted as an VkPipelineCacheHeaderVersion value

Should be "a".

---

vkMapMemory, vkCmdFillBuffer say:

> size must be greater than 0

VkBufferMemoryBarrier says:

> The value of size must be greater than 0

VkBufferViewCreateInfo, VkDescriptorBufferInfo says:

> The value of range must be greater than 0 

These should all say "If (size|range) is not equal to VK_WHOLE_SIZE, (size|range) must be greater than 0", because there isn't a well-defined ordering between VK_WHOLE_SIZE and 0.

(Apart from that, 1.0.5 mostly looks good to me - thanks for resolving lots of the issues!)

**Comment by oddhack** [comment]
Thanks. We'll take care of these shortly.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.6 spec update.
