### ISSUE TITLE
Typo VkMemoryAllocateInfo docs

### ISSUE THREAD

**Issue by Jasper-Bekkers** [KhronosGroup/Vulkan-Docs#1211]
> If the parameters define an import operation and the external handle type is VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_BIT, VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_KMT_BIT, or VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_RESOURCE_BIT, allocationSize must match the size reported in the memory requirements of the image or buffer member of the **VkDedicatedAllocationMemoryAllocateInfoNV** structure included in the pNext chain.

I guess this happened when standardizing the dedicated allocation docs.

**Comment by oddhack** [comment]
Asked @cubanismo to look at this. Note this is not an alias of a promoted structure, so it may call for a new, parallel VU statement for the comparable KHR structure.

**Comment by Jasper-Bekkers** [comment]
Closing due to lack of traction.

**Comment by krOoze** [comment]
I think this whole VU was removed in 1.2.148 update.
