### ISSUE TITLE
Make target to generate include/vulkan/vulkan_core.h

### ISSUE THREAD

**Issue by expipiplus1** [KhronosGroup/Vulkan-Docs#1226]
It would be nice to have a target like the following:

```make
include/vulkan/vulkan_core.h: $(VKXML) $(GENVK)
	$(QUIET)$(PYTHON) $(GENVK) $(GENVKOPTS) -o include/vulkan vulkan_core.h
```

This would be handy in places where generating the documentation is not possible for instance.

**Comment by krOoze** [comment]
```
cd xml
make
```

**Comment by oddhack** [comment]
Agreed to both of @krOoze's comments. In addition the top-level README.adoc has a section on generating headers.

**Comment by expipiplus1** [comment]
> ```
> cd xml
> make
> ```
> 
> PS: You might also be better served simply by the [Vulkan-Headers](https://github.com/KhronosGroup/Vulkan-Headers/), which simply has the headers.

Ah thanks, I somehow completely missed the section in the readme, but it is very clear. 

I'm making use of the generated documentation, so will probably stick with `Vulkan-Docs`, but thanks for the pointer!
