### ISSUE TITLE
Wrong vkCmdBindTransformFeedbackBuffersEXT::bindingCount VU

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1227]
This autogenerated VU for `vkCmdBindTransformFeedbackBuffersEXT` seems wrong:

> If `pSizes` is not `NULL`, `bindingCount` **must** be greater than `0`

Should probably be just:

> `bindingCount` **must** be greater than `0`

**Comment by pdaniell-nv** [comment]
Sure, this sounds correct and would match `vkCmdBindVertexBuffers`. I'll make the change...

**Comment by krOoze** [comment]
Oh, it is an Implicit VU. It's some tricky script problem...

**Comment by pdaniell-nv** [comment]
Fix is here: https://gitlab.khronos.org/vulkan/vulkan/merge_requests/3736

**Comment by oddhack** [comment]
This should be fixed in the 1.2.140 spec update.
