### ISSUE TITLE
vk.xml since v1.2.135: VkAccelerationStructureInstanceKHR definition :number after <\name> tags?

### ISSUE THREAD

**Issue by ParticlePeter** [KhronosGroup/Vulkan-Docs#1229]
`VkAccelerationStructureInstanceKHR` is the only struct defined in vk.xml having `:8` and `:24` after some if its member definition <\name> tags. Are those typos, or which purpose do they have?

```
        <type category="struct" name="VkAccelerationStructureInstanceKHR">
            <member><type>VkTransformMatrixKHR</type>                                    <name>transform</name></member>
            <member><type>uint32_t</type>                                                <name>instanceCustomIndex</name>:24</member>
            <member><type>uint32_t</type>                                                <name>mask</name>:8</member>
            <member><type>uint32_t</type>                                                <name>instanceShaderBindingTableRecordOffset</name>:24</member>
            <member optional="true"><type>VkGeometryInstanceFlagsKHR</type>              <name>flags</name>:8</member>
            <member><type>uint64_t</type>                                                <name>accelerationStructureReference</name></member>
        </type>

**Comment by krOoze** [comment]
They are C\C++ bit fields.
It means `instanceCustomIndex` takes 24 bits of the `uint32_t` and the `mask` takes the remaining 8 bits.

Not sure why they felt it is necessary to use this.

**Comment by ParticlePeter** [comment]
Ok, thanks, unfortunately this is inconvenient for my target language :-(

**Comment by oddhack** [comment]
Vulkan is explicitly a C API, and that's how the RT folks chose to expose this. While it's great when people create bindings to other languages, it's up to those bindings to do whatever transformation is required to and from their representation.

I am closing this because the original question has been answered.

**Comment by expipiplus1** [comment]
> Not sure why they felt it is necessary to use this feature. It might come back to bite them if more options are ever added to `VkGeometryInstanceFlagBitsKHR`.

I guess it was done this way to make `VkAccelerationStructureInstanceKHR` come out to a nice 64 bytes.

**Comment by krOoze** [comment]
You mean "nice" 512 bytes?

**Comment by krOoze** [comment]
Probably it is expected the GPU\driver will use this layout directly. Still, a bitmask of 8 bits, while 4 are already reserved. Asking for problems if it is heavily extended.

**Comment by expipiplus1** [comment]
@krOoze worth raising in #1206 perhaps

**Comment by krOoze** [comment]
alright
