### ISSUE TITLE
Rule stating when an object may be destroyed is too permissive?

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/Vulkan-Docs#123]
2.2.1 "Object Model" says:

> The application must not destroy any other type of Vulkan object until any uses of that object by the device (such as via command buffer execution) have completed.

Should't that be "... until **all** uses of that object..."?

**Comment by oddhack** [comment]
Personally I agree, and will try to get that accepted for the next public update.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.7 spec update.
