### ISSUE TITLE
Removed interface blocks where both OpVariable and block members are decorated with Location

### ISSUE THREAD

**Issue by programmerjake** [KhronosGroup/Vulkan-Docs#1233]
The fix for #1203 removed the possibility of having a interface block where both the `OpVariable` and some or all of the interface block members are decorated with `Location`. Was this intentional?

New text:
https://github.com/KhronosGroup/Vulkan-Docs/blob/019f62b11de9358d3383ead2e1a8c5bc2fda23ad/chapters/interfaces.txt#L226-L231

Old text:
https://github.com/KhronosGroup/Vulkan-Docs/blob/1298bf8b56a8f004c202d2ec5bba568b12b75df4/chapters/interfaces.txt#L233-L241

**Comment by johnkslang** [comment]
Yes, this was intentional.  Does it cause an issue for a front end?

**Comment by programmerjake** [comment]
Not that I'm aware of, just double checking that I can throw out the code I have for handling the removed logic.
