### ISSUE TITLE
Allocating multiple descriptor sets with the same descriptor layout

### ISSUE THREAD

**Issue by cos-public** [KhronosGroup/Vulkan-Docs#1236]
From what I understand so far in Vulkan, it's typical to allocate identical descriptor sets per frame in flight. Currently, to allocate multiple descriptor sets of the same layout you have to duplicate the layout in `VkDescriptorSetAllocateInfo::pSetLayouts` or use a loop. I would expect a well-thought API like Vulkan to suggest the proper usage by function definitions, so I'm concerned if I'm missing something?

If my logic is correct, I would like to kindly ask you to consider extending `VkDescriptorSetAllocateInfo` (through `pNext`?) structure to allow specifing the number of descriptor sets of the same layout to allocate.

**Comment by krOoze** [comment]
Hmmm

```
VkResult vkAllocateDescriptorSets2(
    VkDevice device,
    uint32_t allocateInfoCount,
    const VkDescriptorSetAllocateInfo2* pAllocateInfos,
    VkDescriptorSet* pDescriptorSets);

struct VkDescriptorSetAllocateInfo2{
    VkStructureType sType;
    const void* pNext;
    uint32_t descriptorSetCount;
    VkDescriptorPool descriptorPool;
    VkDescriptorSetLayout layout;
}

But I think Vulkan, if you would have large set of DescriptorSets, wants to coerce you into using `VK_EXT_descriptor_indexing` extension instead.
```

**Comment by cos-public** [comment]
Does `vkAllocateDescriptorSets2` already exist or it's a prototype of how it may look like?

> But I think Vulkan, if you would have large set of DescriptorSets, wants to coerce you into using `VK_EXT_descriptor_indexing` extension instead.

Thank you. That's good to know.

**Comment by krOoze** [comment]
> Does vkAllocateDescriptorSets2 already exist or it's a prototype of how it may look like?

Sorry, I am not Khronos. I was just thinking aloud.

**Comment by jekstrand** [comment]
The API is designed in that way to allow you to allocate multiple descriptor sets with a single call regardless of whether they have the same layout or not.  While it is expected that you will use the same descriptor set layout many times, you're not expected to only use a single descriptor set layout in your app.  With that in mind, the API is optimized towards allowing you to do an arbitrary number of descriptor set allocations, regardless of whether or not they use the same layout, in a single function call.  Unfortunately, this means that if you want to allocate multiple descriptor sets with the same layout you need an array and a loop.  However, that's likely lower overhead than multiple calls to `vkAllocateDescriptorSets`.

Could we fix this?  Yes, we could add an extension which provides an alternate mechanism for allocating descriptor sets which optimizes for this case.  However, adding an extension just for that likely isn't worth the effort.

**Comment by eligt** [comment]
I think it's really unfortunate that this was the conclusion for this issue. "optimizes for this case" makes it sound like this is a rare edge case, but all Vulkan literature I've read recommends the creation of fewer layouts to improve compatibility between pipelines and reduce rebinds. 

So I'd think the case of having 1 layout and 1000 sets of that layout to be a lot more common than having 100 sets of 100 different layouts. Right now you're forced to allocate and iterate through 8KB of memory for the first case, just to circumvent an API limitation.
