### ISSUE TITLE
VkValidationFeaturesEXT::pNext missing VUID

### ISSUE THREAD

**Issue by tambry** [KhronosGroup/Vulkan-Docs#1239]
`VkValidationFeaturesEXT::pNext` lacks a VUID. I think an appropriate VUID would be:

> pNext must be NULL

**Comment by krOoze** [comment]
Extension structs typically do not have `pNext` VU. Those are at the base struct.

**Comment by tambry** [comment]
Ah, my bad. Shouldn't be coding so late in the evenings...
