### ISSUE TITLE
For sake of ABI compatibility, don't use enums in functions or structs

### ISSUE THREAD

**Issue by rhymoid** [KhronosGroup/Vulkan-Docs#124]
As pointed out by @Rukachan in #122, there are some structs that have enum-valued fields. For example, [VkImageViewCreateInfo](Vulkan-Docs/doc/specs/vulkan/structs/VkImageViewCreateInfo.txt) has a field with type [VkImageViewType](Vulkan-Docs/doc/specs/vulkan/enums/VkImageViewType.txt). This is asking for trouble:

* C99 states (in section 6.7.1.1 paragraph 4) that the choice of the compatible integer type for enums is implementation-defined, with the only restriction that it can represent all values.
* The SysV ABIs mention enums and nail them down to signed integers of 32-bits size and alignment. Only some of them have the following footnote:

  > C++ and some implementations of C permit enums larger than an int. The underlying
type is bumped to an unsigned int, long int or unsigned long int, in that order.

  I'd think that it boils down to "pick the smallest of `signed int`, `unsigned int`, `signed long`, `unsigned long`, depending on the values", and have to presume that the ABIs that don't have this footnote don't allow this. However, I'm not sure whether implementors agree on this, because the wording is ambiguous at best.
* The Microsoft ABIs don't seem to mention enums at all. This should mean that implementations only have to adhere to the language constraints, which effectively means "pick whatever you like".

My guess is that you really don't want enum-typed struct fields and function arguments in a specification that *relies* on ABI compatibility.

**Comment by oddhack** [comment]
We're probably going to add padding values in the enumerations to ensure they all take 32 bits - although we're not yet convinced the theoretical scenario of some enums taking only 16 bits is a real one, so people aren't especially worried about it - and we will be careful not to put any value requiring more than 32 bits into any enumeration (at least until a hypothetical Vulkan 2.0 that would break API compatibility). Problem avoided.

We're not willing to lose the degree of typesafety provided by the enums, or to change the API, either.

**Comment by philiptaylor** [comment]
> we're not yet convinced the theoretical scenario of some enums taking only 16 bits is a real one

A not-*entirely*-theoretical example: I believe the VideoCore VPU compiler represented enums as the smallest integer type that could contain their values, so the best solution was to add a "FORCE_32_BIT = 0x7fffffff" value to any enums used in structs shared between the VPU and host processors. Portability was an issue for the OpenGL driver, which proxied commands from the host to VPU. But VC4 can't do Vulkan so this is still mostly theoretical, it's not a real architecture that actually needs this now.
