### ISSUE TITLE
where is the 'maker vulkan api doc'

### ISSUE THREAD

**Issue by Azaretdodo** [KhronosGroup/Vulkan-Docs#1240]
Hello,

I have install Vulkan Docs… Vulkan Hpp… Vulkan Tools… Vulkan Headers… vulkan basic sample and Vulkan web registry but I don't know where in chapter from Vulkan Docs I will find how to build vulkan api ?

Thank you in advance to explain to myself where is the doc for build vulkan api,

Regards.

Azaretdodo.

**Comment by oddhack** [comment]
It's not completely clear what you're asking, but it sounds like you should be installing both the Vulkan SDK, and the appropriate Vulkan driver provided by the GPU manufacturer for whatever device you're using. Together the SDK and the hardware driver provide a Vulkan API implementation, which it sounds like you're after. See khronos.org/vulkan for links that should help out with this.

**Comment by Azaretdodo** [comment]
Hello,


Your sdk tarball don't work,

How to check if vulkan is installed?

I can't install by apt I am on fedora the program installer is dnf,

Thank you in advance to help myself check if vulkan is installed,

Regards.


Azaretdodo.

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by oddhack** [comment]
@KarenGhavam-lunarG could you or someone else at LunarG direct @Azaretdodo towards help on installing the SDK and drivers for Fedora? I'm out of my depth at this point, and Vulkan-Docs is really only for specification issues.

**Comment by KarenGhavam-lunarG** [comment]
@oddhack Tell him to submit his issue on vulkan.lunarg.com and close this one.

**Comment by Azaretdodo** [comment]
I should explain the error happening to your link?

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by KarenGhavam-lunarG** [comment]
Issues with installation or usage of the SDK should be submitted to vulkan.lunarg.com (the SDK download site).

**Comment by oddhack** [comment]
Closing per @KarenGhavam-lunarG's advice.
