### ISSUE TITLE
Vulkan 1.2 crashes with ray queries on 1060

### ISSUE THREAD

**Issue by Brejlounek** [KhronosGroup/Vulkan-Docs#1241]
Hi, I attempted to run new GL_EXT_ray_query sample code ( https://nvpro-samples.github.io/vk_raytracing_tutorial_KHR/vkrt_tuto_rayquery.md.htm#rayquery
 ) on my Pascal 1060. The ray query sample crashes on pipeline creation when using the new ray query functions in GLSL but runs fine without them. Is it possible the ray queries arent supported on my pascal hardware even tho VkPhysicalDeviceRayTracingFeaturesKHR says it is? The GLSL code in question is this:

> // Initializes a ray query object but does not start traversal
> rayQueryEXT rayQuery;
> rayQueryInitializeEXT(rayQuery, topLevelAS, gl_RayFlagsTerminateOnFirstHitEXT, 0xFF, origin, tMin,
> direction, tMax);
> 
> // Start traversal: return false if traversal is complete
> while(rayQueryProceedEXT(rayQuery))
> {
> }
> 
> // Returns type of committed (true) intersection
> if(rayQueryGetIntersectionTypeEXT(rayQuery, true) != gl_RayQueryCommittedIntersectionNoneEXT)
> {
> // Got an intersection == Shadow
> outColor *= 0.1;
> }

Thanks for your help.

**Comment by pdaniell-nv** [comment]
It was a mistake for the driver to advertise rayQuery on GPUs which don't have RT Cores. That will be fixed in a future driver. For now assume that rayQuery is VK_FALSE on Pascal and only VK_TRUE for GeForce RTX products. Sorry for the inconvenience.
