### ISSUE TITLE
a typo "can be can be"

### ISSUE THREAD

**Issue by wind0204** [KhronosGroup/Vulkan-Docs#1247]
in the first sentence, it says "A render pass transform **can be can be** enabled for render pass instances."
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#vertexpostproc-renderpass-transform

Best regards

**Comment by jackohound** [comment]
Thanks.  We'll fix this typo.

**Comment by oddhack** [comment]
Fixed internally - will go out in the next public spec update.
