### ISSUE TITLE
Vulkan program keeps crashing with error

### ISSUE THREAD

**Issue by TheShermanTanker** [KhronosGroup/Vulkan-Docs#1248]
I've written a test program with all required Vulkan headers included and the vulkan-1.lib library properly linked and all, yet whenever I try to run it, it always crashes with this error:

<img width="960" alt="2020-04-17" src="https://user-images.githubusercontent.com/32636402/79565895-2df2b100-80e4-11ea-88fa-96e1095c02ba.png">

(VulkanTest.exe is my compiled test program)

It's definitely not because my drivers don't support Vulkan; vkcube.exe and vkcubepp.exe both run normally on my computer. Does anyone know what is causing this?

This is the code for VulkanTest.exe, if it's important. Although I highly doubt that's the cause of the issue, but I've realised it only crashes if vkCreateInstance is called

```
/*
 ============================================================================
 Name        : VulkanTest.c
 Author      : TheShermanTanker
 Version     :
 Copyright   : None
 Description : Hello World in C, Ansi-style
 ============================================================================
 */

#include <stdio.h>
#include <stdlib.h>

#include "vulkan/vulkan.h"

int main(void) {
	puts("Hello World"); /* prints Hello World */

	VkResult status;
	VkInstance instance;
	VkApplicationInfo applicationInfo = {VK_STRUCTURE_TYPE_APPLICATION_INFO, NULL, "Vulkan Test", 1.2, "Native Vulkan Engine", 0.7, 121350};
	VkInstanceCreateInfo instanceInfo = {VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO, NULL, 0, &applicationInfo, 0, NULL, 0, NULL};
	status = vkCreateInstance(&instanceInfo, NULL, &instance);

	return EXIT_SUCCESS;
}
```

**Comment by krOoze** [comment]
This is a Vulkan specification repo. It is not a community self-help nor driver support forum.

Anyway, app version and engine version are uints. `1.2` and `0.7` are doubles, so should not compile (without warning anyway).

Not sure what `121350` is. Does not seem like a valid Vulkan version. Use `VK_API_VERSION_1_*` macros.
