### ISSUE TITLE
Feedback loop self-dependency requirements

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#125]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#renderpass-creation says:

> Second, if the input attachment reads components that are written by the color or depth/stencil attachment, then there is a feedback loop and a pipeline barrier must be used between when the attachment is written and when it is subsequently read by later fragments. This pipeline barrier must follow the rules of a self-dependency as described in Subpass Self-dependency, where the barrier's flags include:
> - dstStageMask = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,
> - dstAccessMask = VK_ACCESS_INPUT_ATTACHMENT_READ_BIT, and
> - srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT (for color attachments) or srcAccessMask = VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT (for depth/stencil attachments).
> - srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT (for color attachments) or srcStageMask = VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT | VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT (for depth/stencil attachments).
> - dependencyFlags = VK_DEPENDENCY_BY_REGION_BIT. 

I assume the "flags include ... dstStageMask = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT" really means "dstStageMask & VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT != 0", i.e. other flag bits are permitted too, not that it must strictly equal FRAGMENT_SHADER.

In any case, that means:
- The last pipeline stage in srcStageMask is COLOR_ATTACHMENT_OUTPUT (assuming color attachments) or possibly later.
- The first pipeline stage in dstStageMask is FRAGMENT_SHADER or possibly earlier.

https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#synchronization-pipeline-barriers-subpass-self-dependencies says:

> Self-dependencies must not have any earlier pipeline stages depend on any later pipeline stages. More precisely, this means that whatever is the last pipeline stage in srcStageMask must be no later than whatever is the first pipeline stage in dstStageMask (the latest source stage can be equal to the earliest destination stage).

COLOR_ATTACHMENT_OUTPUT is later than FRAGMENT_SHADER. I think that means it's impossible to follow these rules.

**Comment by jeffbolznv** [comment]
Yikes, good catch. The second rule was really meant to prevent having e.g. a fragment->vertex dependency. We'll need to find some alternative way to phrase this rule.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.47 spec update.
