### ISSUE TITLE
Nothing stops anyone from specifying all the available queue families in Vk*CreateInfo::pQueueFamilyIndices

### ISSUE THREAD

**Issue by ghost** [KhronosGroup/Vulkan-Docs#1251]
Anyone can specify all the available queue family indices of a device in `VkBufferCreateInfo::pQueueFamilyIndices` and `VkImageCreateInfo::pQueueFamilyIndices` and there seems to be no limit which queue family indices you can and can not specify.

**Comment by polarina** [comment]
Valid Usage for `VkBufferCreateInfo`:

> If `sharingMode` is `VK_SHARING_MODE_CONCURRENT`, each element of `pQueueFamilyIndices` **must** be unique and **must** be less than `pQueueFamilyPropertyCount` returned by `vkGetPhysicalDeviceQueueFamilyProperties` for the `physicalDevice` that was used to create `device`

Valid usage for `VkImageCreateInfo` is similar.

What in the specification indicates that one may not specify any or all queue families?

**Comment by procedural** [comment]
> Valid Usage for VkBufferCreateInfo:
> 
> > If sharingMode is VK_SHARING_MODE_CONCURRENT, each element of pQueueFamilyIndices **must** be unique and **must** be less than pQueueFamilyPropertyCount returned by vkGetPhysicalDeviceQueueFamilyProperties for the physicalDevice that was used to create device

Read the first comment carefully before replying with a spec quote that doesn't have anything to do with the issue. I'm not talking about the uniqueness of `pQueueFamilyIndices` or the count of `pQueueFamilyPropertyCount`.

**Comment by TomOlson** [comment]
Please note our [Code of Conduct](https://github.com/KhronosGroup/Vulkan-Docs/blob/master/CODE_OF_CONDUCT.md) - keep the discussion friendly and civil.

To answer the implied question - yes and no: 
> Anyone can specify all the available queue family indices of a device in VkBufferCreateInfo::pQueueFamilyIndices and VkImageCreateInfo::pQueueFamilyIndices...

Yes. That is valid usage, and is expected to work.
> ... and there seems to be no limit which queue family indices you can and can not specify.

No - as stated in the VU quoted by @polarina, it is invalid to specify queue family indices that are outside the range supported by the device.

**Comment by procedural** [comment]
@TomOlson read the first comment again, I'm not talking about queue family indices ranges nor did I asked anyone to link code of conducts for no reason.

> Yes. That is valid usage, and is expected to work.

So specifying a `VK_QUEUE_SPARSE_BINDING_BIT`-only queue in vkCreateSwapchainKHR::pQueueFamilyIndices is a valid usage?

**Comment by polarina** [comment]
> So specifying a VK_QUEUE_SPARSE_BINDING_BIT-only queue in vkCreateSwapchainKHR::pQueueFamilyIndices is a valid usage?

Yes, that queue may support presentation.

**Comment by oddhack** [comment]
Closing this - OP has closed their account and the question was addressed, as well.
