### ISSUE TITLE
on gtx 1660, why ray tracing is ok for Quake2RTX, but not support VK_NV_ray_tracing?

### ISSUE THREAD

**Issue by SuperCarrot2012** [KhronosGroup/Vulkan-Docs#1253]
I have a card gtx 1660 of gigabyte. The version of nvidia driver is 445.87, and version of vulkan sdk is 1.1.126.
When i call interface vkEnumerateDeviceExtensionProperties, i cannot find the extend "VK_NV_ray_tracing". Also, when i call vkCreateDevice, it will returen error "extend not present(-7)"
However, i download the game Quake2RTX, and enable RTX function, everything is ok.
So, i want to ask how to solve the problem?

**Comment by pdaniell-nv** [comment]
Is your application 32-bit or 64-bit? Ray tracing is only available with 64-bit applications.

**Comment by SuperCarrot2012** [comment]
> Is your application 32-bit or 64-bit? Ray tracing is only available with 64-bit applications.

Yes, you are right, it is ok after i create 64-bits app. Thanks very much !
