### ISSUE TITLE
getting a new VkDriverId for a mesa software driver

### ISSUE THREAD

**Issue by airlied** [KhronosGroup/Vulkan-Docs#1256]
I'd like to please get

VK_DRIVER_ID_MESA_LLVMPIPE

assigned a value.

**Comment by oddhack** [comment]
Fairly obvious question, but this is a formal request on behalf of the Mesa project, right?

**Comment by airlied** [comment]
Yes as part of the X.org/ SPI adopters

**Comment by oddhack** [comment]
OK. I will assign one for the next spec update (probably going out Sunday).

**Comment by airlied** [comment]
@oddhack hey I didn't see this land but actually I wanted to also ask for a vendor ID since I realised I we don't have one for MESA software.

Please also assign VK_VENDOR_ID_MESA

**Comment by oddhack** [comment]
We'll be assigning VK_DRIVER_ID_MESA_LLVMPIPE = 13 and VK_VENDOR_ID_MESA = 0x10005. I'll try to do a minor spec update this weekend including this change as I overlooked doing it in the 1.2.140 update - apologies for that.

**Comment by oddhack** [comment]
The 1.2.141 spec update contains these enums.
