### ISSUE TITLE
Implicit flush on vkUnmapMemory

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#126]
In issue #27, @szdarkhack said:

> I think there should also be some explicit mention of whether vkUnmapMemory performs an implicit flush or not, there is nothing in the specification clarifying it (I've looked throughout the entire 10.2.1 section as well as the description of the VkMemoryPropertyFlagBits flags in section 10.2, and text-searching "unmap" doesn't bring up any other hits).
> 
> On the other hand, [this](https://www.khronos.org/registry/vulkan/specs/1.0/apispec.html#VkMemoryPropertyFlagBits) (obviously outdated, but look at the description for VK_MEMORY_PROPERTY_HOST_NON_COHERENT_BIT) seems to imply that unmapping does flush non coherent memory.
> 
> I think a clarification should be added in the description of vkUnmapMemory.

I agree with that comment, and I don't think it got fixed in 1.0.5, and it'd probably be confusing to reopen that issue, so I'm reposting it here.

**Comment by ratchetfreak** [comment]
There is also the related issue about whether a vkMapMemory has an implicit invalidate.

**Comment by krOoze** [comment]
The spec should not always say all the things some command does **not** do.
It would be a long list.

Not sure if there were any relevant changes over the time, but the text seems clear to me (that it does not do any implicit operations).

**Comment by oddhack** [comment]
This should be fixed in the 1.0.35 spec update.
