### ISSUE TITLE
Extensions should not have pre-release revision numbers

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1263]
All the released extensions should just start at `1`. Apps cannot do anything with pre-release extension, and it should not be their responsibility to filter such extension out should a pre-release revision number be reported.

Besides, revision numbers are only allowed for compatible changes. I assume a not-yet-released extension would just do whatever changes it needs.

Also keeping version history in the spec that goes past the release date is bit pointless for most readers, and a waste of space.

**Comment by Tobski** [comment]
Thanks @krOoze - we're unlikely to change existing extensions to conform to this, but think it probably makes sense to do this. We'll consider this internally and see if we can find a way to make this work with the way we handle versions prior to release.

**Comment by krOoze** [comment]
PS: Extension revisions typically start at `1`, but `0` is representible in `uint32_t`. I think it should also be noted in the spec if `0` revision has some special meaning or not.

**Comment by oddhack** [comment]
We put a CI test in our internal repo to ensure that SPEC_VERSION == 1 at the time an extension is merged to master branch, and guidance to that effect in the spec, in the 1.2.146 update.
