### ISSUE TITLE
There is no valid usage statment regarding the length of pDiscardRectangles in VkPipelineDiscardRectangleStateCreateInfoEXT

### ISSUE THREAD

**Issue by expipiplus1** [KhronosGroup/Vulkan-Docs#1267]
The names suggest that it should point to `discardRectangleCount` elements. 

I assume that `optional=true` is present on the pointer because of

>If the VK_DYNAMIC_STATE_DISCARD_RECTANGLE_EXT dynamic state is enabled for a pipeline, the pDiscardRectangles member is ignored.

And the noautovalidity is there because this isn't represented in the state.

I would expect to see some valid use statement along the lines of

"if discardRectangleCount is not 0 and VK_DYNAMIC_STATE_DISCARD_RECTANGLE_EXT dynamic state is not enabled then pDiscardedRectangles must point to an array of discardRectangleCount values"

**Comment by krOoze** [comment]
Yea, I have this in #1185. Needs some rebasin'

**Comment by expipiplus1** [comment]
Great, thanks!
