### ISSUE TITLE
Flushes and host writes in non-coherent memory

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#127]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#memory-device-hostaccess says:

> In order to enable applications to work with non-coherent memory allocations, two entry points are provided. To flush host write caches, an application must use vkFlushMappedMemoryRanges, while vkInvalidateMappedMemoryRanges allows invalidating host input caches so that device writes become visible to the host. vkFlushMappedMemoryRanges must be called after the host writes to non-coherent memory have completed and before command buffers that will read or write any of those memory locations are submitted to a queue. Similarly, vkInvalidateMappedMemoryRanges must be called after command buffers that execute and flush (via memory barriers) the device writes have completed, and before the host will read or write any of those locations.

What precisely are "those memory locations"?

E.g. in the following situation:
- A non-coherent buffer is filled with 0x00
- The host calls vkInvalidateMappedMemoryRanges on the whole buffer
- The host reads from the buffer (so it gets into the CPU cache)
- The device writes (int32_t)0x01 to offset 0 in the buffer
- The host writes (int32_t)0x02 to offset 4 in the buffer
- (Time passes, stuff gets evicted from the CPU cache)
- The device reads from offset 0 in the buffer

The device is reading/writing memory locations 0,1,2,3 (in bytes), and the host is writing memory locations 4,5,6,7. They are clearly not accessing the same memory locations, so no flushing or invalidating is needed.

In practice this seems broken: the host CPU cache might write back a whole cache line (which is full of 0x00 plus a single 0x02), and overwrite the 0x01 that the device had previously written, so the device will unexpectedly read back 0x00.

This probably needs to be specified in terms of nonCoherentAtomSize, i.e. if the host/device accesses overlap with nonCoherentAtomSize granularity then the flushes/invalidates are required.

---

But even with that change, I think the behaviour is unclear in the following case:
- A non-coherent buffer is filled with 0x00
- The host calls vkInvalidateMappedMemoryRanges on the whole buffer
- The host reads from the buffer (so it gets into the CPU cache)
- The device writes (int32_t)0x01 to offset 0 in the buffer
- The host writes (int32_t)0x02 to offset nonCoherentAtomSize in the buffer
- The host calls vkFlushMappedMemoryRanges with offset 0, size 2*nonCoherentAtomSize
- The device reads from offset 0 in the buffer

The device write and host write do not overlap, even with nonCoherentAtomSize granularity, so I believe this is perfectly valid.

What is the effect of the vkFlushMappedMemoryRanges? Is it allowed to overwrite the data that the device wrote to offset 0, because that's included in the flush range? or is it only allowed to flush cache lines that are dirty on the CPU?

If it's the former, I think there needs to be an extra requirement that if the device writes to a memory location, and the host later flushes a range including that memory location, then the host must invalidate a range including that memory location after the write and before the flush, to ensure consistent behaviour. If it's the latter, I think the concept of "dirty cache lines" would need to be defined or at least referenced.

**Comment by krOoze** [comment]
That quote was deleted in 1.0.12. And some other changes were made over time.
Is this issue still valid?

There seem to be specified that the Application is responsible for synchronizing the ranges expanded to the `nonCoherentAtomSize`.
It is part of the `VkMappedMemoryRange` command VU (used by both flush and invalidate) that it must be a multiple of `nonCoherentAtomSize`.

It also says the memory must be invalidated before host write.

**Comment by philiptaylor** [comment]
I think this is still a valid issue.

The spec currently says:

> `vkFlushMappedMemoryRanges` must be used to guarantee that host writes to non-coherent memory are visible to the device. It must be called after the host writes to non-coherent memory have completed and before command buffers that will read or write any of those memory locations are submitted to a queue.

and

> `vkInvalidateMappedMemoryRanges` must be used to guarantee that device writes to non-coherent memory are visible to the host. It must be called after command buffers that execute and flush (via memory barriers) the device writes have completed, and before the host will read or write any of those locations. If a range of non-coherent memory is written by the host and then invalidated without first being flushed, its contents are undefined.

i.e. it's still talking about "those memory locations". If the host writes to offset 0 and the device writes to offset 4, those aren't the same memory locations, so it doesn't say I need to flush/invalidate on the host. But I expect it really should say I need to (otherwise the host might randomly decide to write back its dirty cache line at any time, which could conflict with the device's write).


The spec also says:

> vkMapMemory does not check whether the device memory is currently in use before returning the host-accessible pointer. The application must guarantee that any previously submitted command that writes to this range has completed before the host reads from or writes to that range, and that any previously submitted command that reads from that range has completed before the host writes to that region (see here for details on fulfilling such a guarantee)

where "see here" links to `vkWaitForFences`, which talks about how to "guarantee that the results of memory accesses will be visible to the host, or that the memory is available" and says "`vkInvalidateMappedMemoryRanges` must be called after the fence is signaled in order to ensure the writes are visible to the host" - but I don't care about those guarantees in this example because the host and device aren't accessing the same locations and don't need to see each other's writes, so this still doesn't answer the questions.

(Also, that part of the spec seems incomplete since it only talks about previously submitted commands - it doesn't talk about host writes vs device reads/writes in subsequently submitted commands. That's hidden in the "Host Write Ordering Guarantees" section instead, though that section is similarly vague about when flushes are required.)

(Also all of this stuff uses totally vague terms like "previously" and "before" and "completed", which can have many different meanings when synchronisation is involved - execution dependencies, memory dependencies, host memory-access order (i.e. C++11 happens-before or equivalents in other languages (if they even bother to define a memory model)), host<->device interaction, etc. So it's all very ambiguous and hard to read. It needs to be integrated into some precise coherent clearly-defined synchronisation model that fully covers both device and host, which probably doesn't exist yet.)

**Comment by TobiasHector** [comment]
I *think* most of this is now fixed, or is soon to be fixed - the one thing that is still definitely not answered is whether the entire mapped memory range might be flushed, or just the dirty cache lines. Will try to get an answer from the working group.

**Comment by oddhack** [comment]
This should be fixed (in master branch) for the 1.1.70 spec release.
