### ISSUE TITLE
vkSetPrivateDataEXT missing externsync

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1270]
`vkSetPrivateDataEXT` seems to be missing `externsync`.
Not sure if the whole `privateDataSlot` should be `externsync` or just the (`privateDataSlot`, `objectHandle`) pair.

**Comment by mattruschnv** [comment]
I think the object(Handle) is what needs to be externsync. I don't think the slot is in danger of modification here.

**Comment by krOoze** [comment]
@mattruschnv That sorta makes sense to me. Although on the other hand I don't see a reason why `vkSetPrivateDataEXT` couldn't be called next to e.g. `vkBeginCommandBuffer`. It needs to be protected only against another `vkSetPrivateDataEXT`, or `vkGetPrivateDataEXT`, or `vkDestroySlot`. Possibly needs some subtle touch.

**Comment by jeffbolznv** [comment]
I think we want neither to be externsync.

We went through a lot of internal design discussions to get the overhead of this extension to be very low, and the intent is that (when you use privateDataSlotRequestCount) Sets and Gets are just atomic store/load of an array in the object. Having externsync on objectHandle would kill the performance of this, particularly for layers where they don't know which objects other threads are using (and would have to lock conservatively).

And given this intended implementation, the fallback to storing something in the privateDataSlot parameter is rare and we don't want to require apps to externally synchronize that either.

**Comment by krOoze** [comment]
> array in the object

Hm, doesn't that mean `vkCreatePrivateDataSlotEXT` needs to be externsync-ish too? It could invalidate the array on resize, if it is indeed implemented this way. And I don't quite like the idea of internal sync being prevalent in Vulkan.

> are just atomic store/load of an array in the object.

If access through the `vk*PrivateDataEXT` is regulated it would obviate the need for atomics. Wouldn't that be better? Considering this does not have the more useful parts, like atomic addition (i.e. CAS), this has no reason to be atomic. Would probably also obviate the need for the feature bool, as practically every platform could support it.

What about this. The spec could say exactly that:

> The private data payload **may** not be stored atomically.  `vkGetPrivateDataEXT` returns **undefined result** if a `vkSetPrivateDataEXT` is executing in parallel on the same slot and object.

BTW: Why is the extension not at least physical-device-level extension?

**Comment by mattruschnv** [comment]
> Hm, doesn't that mean `vkCreatePrivateDataSlotEXT` needs to be externsync-ish too? It could invalidate the array on resize, if it is indeed implemented this way. And I don't quite like the idea of internal sync being prevalent in Vulkan.

It doesn't resize if you utilize privateDataSlotRequestCount. The data slot is effectively an index in that case.

> BTW: Why is the extension not at least physical-device-level extension?

It started out as an instance level extension. There was a decision made at some point that extensions should be instance or device, but not both. This would necessitate 2 extensions (and there could still be an instance level version of this), but the focus of the usefulness is at the device level.

**Comment by jeffbolznv** [comment]
> Hm, doesn't that mean vkCreatePrivateDataSlotEXT needs to be externsync-ish too? It could invalidate the array on resize, if it is indeed implemented this way.

The intent is that the array size is determined at device creation time, the array is allocated at object creation time, and never grows. If more private data slots are created than there are slots in the array, then those extra private data slots have a slower, internally synchronized implementation.

> If access through the vk*PrivateDataEXT is regulated it would obviate the need for atomics. 

Atomic loads and stores of 32/64 bit types are more or less free, at least on x86_64. This avoids undefined behavior if two threads access the same slot without synchronization.

**Comment by DadSchoorse** [comment]
> BTW: Why is the extension not at least physical-device-level extension?

Just as a side note, as a layer developer I'm extremely happy that it's not an instance extension since that would make it totally unusable for layers as a result of https://github.com/KhronosGroup/Vulkan-Loader/issues/51 .

**Comment by krOoze** [comment]
Physical-device extension counts as a device extension in Vulkan 1.1 (or `VK_KHR_get_physical_device_properties2`).

**Comment by jeffbolznv** [comment]
We discussed this in today's meeting and agreed that the intended design was for these to not be externsync, for the reasons I previously described. Closing.
