### ISSUE TITLE
VkMemoryRequirements.memoryTypeBits returned by vkGetAccelerationStructureMemoryRequirementsKHR should be 0xFFFFFFFF

### ISSUE THREAD

**Issue by Karlovsky120** [KhronosGroup/Vulkan-Docs#1272]
The current Vulkan specification on vkGetAccelerationStructureMemoryRequirementsKHR says the following:

> Scratch space is allocated as a VkBuffer, so for VK_ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_TYPE_BUILD_SCRATCH_KHR and VK_ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_TYPE_UPDATE_SCRATCH_KHR the pMemoryRequirements->alignment and pMemoryRequirements->memoryTypeBits values returned by this call must be filled with zero, and should be ignored by the application.

In general, memoryTypeBits is an 32bit integer with n-th bit set to 1 if memory at index n of the VkPhysicalDeviceMemoryProperties.memoryTypes can be used as memory for the object for which memory query has been made.

The fact that this value is ignored in this case implies that any memory available can be used. 
If this is not correct, this part of specification should clarify what memory types are applicable here.
If this is correct (which I assume it is), it would be far better for the value to be set to 0xFFFFFFFF instead of 0.

Given the definition of memoryTypeBits, setting it to 0 implies that no memory present on the device can be used, while 0xFFFFFFFF implies that any memory on the device can be used.
Since memoryTypes is an array of 32, but the device might have fewer types of memory available, this value could also be set to that instead of 0xFFFFFFFF, if it were better for any reason.

Other than that, I'm guessing that most of functions that try to find the appropriate memory based on the info from memory properties look something like this:

```
uint32_t MemoryAllocator::findMemoryType(uint32_t memoryTypeBits , vk::MemoryPropertyFlags propertyFlags) {
    for (uint32_t i = 0; i < m_memoryProperties.memoryTypeCount; ++i) {
        if ((memoryTypeBits & (1 << i)) && (m_memoryProperties.memoryTypes[i].propertyFlags & propertyFlags)) {
            return i;
        }
    }

    throw std::runtime_error("No suitable memory type found!");
}
```

Having memoryTypeBits set to 0 will break this code (no memory will ever be selected), while setting it to 0xFFFFFFFF will have no effect.

If you consider that setting VkMemoryRequirements.alignment to 0 means that any alignment is valid, the suggestion above would also remove this as an exception or special case. The values given could be treated as values of any other VkMemoryRequirements and resulting code would be correct.

**Comment by dgkoch** [comment]
A query for build or update scratch memory requirement is *only* a query for the size of the scratch buffer.  Any values returned for alignment or memory type would be bogus and would need to be "intersected" with the proper memory requirements (obtained via vkGetBufferMemoryRequirements) for the scratch VkBuffer. The acceleration structure memory requirements query has no way of knowing what the buffer requirements might be, because it doesn't have the buffer properties.
