### ISSUE TITLE
Are nil UUIDs valid device UUIDs?

### ISSUE THREAD

**Issue by haasn** [KhronosGroup/Vulkan-Docs#1273]
I naively made the assumption that valid device UUIDs could never be all zeros, but upon being contested, I failed to find any wording in the spec that actually implies or guarantees it.

Could you please clarify whether or not such nil UUIDs are legal device UUIDs?

**Comment by krOoze** [comment]
I mean, Universally Unique ID should be universally unique.

**Comment by haasn** [comment]
That is true, but the spec specifically points out that UUIDs are only meant to be valid or sensible within the contexts of the currently running system. It even mentions the possibility of the same device/driver/whatever generating the same UUIDs on different systems.

My own driver (RADV) generates a device UUID that looks like `00000000-0800-0000-0000-000000000000` (which, side note, is *awful* in my terminal's font since it barely distinguishes 0 from 8 visually...), hardly a "universally unique" number.

**Comment by krOoze** [comment]
Not quite cryptographically healthy-looking, but should work given Pauli exclusion principle.

Still, little bit problematic. Say, someone releases an USB-connected GPU and gives it UUID the USB port id, which also happens to be `0`.

Not sure how you would clarify this. If you ban all zeroes, they will just use all ones, or `12345...`, or something.

**Comment by haasn** [comment]
To clarify, the reason I'm interested is that I was wondering whether I could treat "all zeroes" as "no UUID known", i.e. the same way that 0 handles are often interpreted as "no such resource" even in schemes that could technically allow `0` to be a valid handle.

**Comment by krOoze** [comment]
No, only the LUID is optional.

**Comment by oddhack** [comment]
Khronos does not want to say that specific UUID values are or are not valid.

Related, we have no way of enforcing that UUIDs are *actually* unique across vendors which may coexist in a machine. So it's fair to say that calling it "universally unique" is too strong, and we plan to add some clarifying language to VkPhysicalDeviceIDProperties about that. Using (vendorID, UUID) should be unique, since the vendor ID is something we manage.

Closing this as the original question has been addressed.

**Comment by oddhack** [comment]
FYI we added some language to the 1.2.146 spec update which advises vendors to select UUIDs that are actually likely to be as unique as they need to be in a running system, and in particular to avoid all-zero-bits.
