### ISSUE TITLE
Question about image layout

### ISSUE THREAD

**Issue by konstantinegorov** [KhronosGroup/Vulkan-Docs#1274]
Hi.
There are note in the specification:

> After initialization, applications need not use any layout other than the general layout, though this may produce suboptimal performance on some implementations.

Did I understand correctly that it is good practice to use one of the general layouts everywhere.

**Comment by krOoze** [comment]
I think the quote speaks for itself that it is not good practice.

Additionally you cannot use general layout for presentation.

**Comment by Tobski** [comment]
@krOoze's answer is accurate; using the GENERAL layout can cause significant performance reductions on some implementations, so should be avoided in production applications.
