### ISSUE TITLE
Fix clang-tidy warnings for [hicpp-signed-bitwise]

### ISSUE THREAD

**Issue by MuAlphaOmegaEpsilon** [KhronosGroup/Vulkan-Docs#1278]
Running clang-tidy on some basic Vulkan code emits warnings related to the usage of VK_MAKE_VERSION, VK_API_VERSION_1_X and VK_VERSION_MAJOR/MINOR, due to the usage of bitwise shift operations performed on signed integers:
```
warning: use of a signed integer operand with a binary bitwise operator [hicpp-signed-bitwise]
```

**Comment by oddhack** [comment]
Closed by #1279, I believe.
