### ISSUE TITLE
What happens when the swapchain underflows?

### ISSUE THREAD

**Issue by haasn** [KhronosGroup/Vulkan-Docs#1281]
I couldn't find a note for this anywhere. Would it be possible to add a quick clarification in the spec of what happens when a `VkSwapchainKHR` has no image in its queue during a vertical blanking period?

I assume the answer will simply be "it's implementation-defined", perhaps with platform-specific addendums like "the frontbuffer contents will remain valid until XYZ damage event is fired". But even just clarifying that this is implementation defined would be helpful, as right now it seems to be more or less undefined behavior.

The context is that I'm not actually sure what mechanism guarantees that it's valid to assume the previous frame will remain on-screen when the program stops presenting to the swapchain, which is something that's widely being done by e.g. multimedia players and other applications that only redraw when something changes. I assume the relevant platform-specific specs (e.g. wayland/X11) end up effectively defining this behavior in practice, but it's not entirely clear whether the vulkan WSI code needs to be making any guarantees about the frontbuffer contents, or whether it would be a valid implementation to e.g. show a black screen for "missed" vsyncs.

**Comment by krOoze** [comment]
Obviously swapchain cannot give you an image that does not exist.

When you acquire certain amount of images, you are no longer allowed to use infinite timeout (`UINT64_MAX`):

> An image will eventually be acquired if the number of images that the application has currently acquired (but not yet presented) is less than or equal to the difference between the number of images in `swapchain` and the value of `VkSurfaceCapabilitiesKHR::minImageCount`. If the number of currently acquired images is greater than this, `vkAcquireNextImageKHR` **should** not be called; if it is, `timeout` **must** not be `UINT64_MAX`.

So, the specification recommends you to not "underflow" swapchain. If you do, either it will give you one of its images it has for its internal use (`minImageCount - 1`), or it will timeout eventually.  If it has no images at all, it should timeout.

> The context is that I'm not actually sure what mechanism guarantees that it's valid to assume the previous frame will remain on-screen when the program stops presenting to the swapchain

The present mode definitions are worded such that they "update the current image". That strongly implies the original image is used in perpetuity unless new one is in the queue.

**Comment by haasn** [comment]
I feel like you misunderstood my usage of the term "underflow". I meant underflow not in the sense of no longer being able to acquire, but in the sense of the FIFO's queue completely "draining". (i.e. if I'm rendering too slowly, not too quickly - it's the opposite question)

> That strongly implies the original image is used in perpetuity unless new one is in the queue.

In practice this is not entirely the case, because various OS events can cause the frontbuffer contents to become undefined on vsync if the swapchain is empty. For an example, simply switching to a different workspace and back will leave the frontbuffer mangled, unless users use other (external) mechanisms to detect window damage and re-submit to the same swapchain.

While looking into the question of "to what extent is this defined behaviour?", I noticed that e.g. GLX actually provides explicit mechanisms for detecting clobber events, which somewhat raises the question of whether vulkan swapchains should be capable of doing the same?

**Comment by critsec** [comment]
I'm not sure it's spelled out anywhere in the spec, but I believe the implicit intent -- and this is certainly true on all platforms I'm aware of -- is that the PE continues to display the last presented image indefinitely until a newer one is presented. There is not an expectation that apps present a new image for each vblank period; even games that are aiming for 30fps could have a problem with that.

Many of the rules around `vkAcquireNextImageKHR` ordering and blocking/async behavior are there because the PE need continuous access to the most recently presented image, so it can't (in general) say when it will no longer need that access until a newer frame has been put in the present queue.

**Comment by haasn** [comment]
Makes sense. I guess this issue can be closed, since there's not really a bug. I'm just surprised by this implied behaviour not actually being documented.
