### ISSUE TITLE
vertex shader can't get all input data 

### ISSUE THREAD

**Issue by ArtiAdler** [KhronosGroup/Vulkan-Docs#1282]
**I have my Vertex data defined like this:**
struct Vertex{
    glm::vec4 pos;
    glm::vec2 texcoord;
    glm::vec2 texcoordex;
    float alpha;
    float idx;
};
### **vertex shader input**
layout (location = 0) in vec4 pos;
layout (location = 1) in vec2 attr;
layout (location = 2) in vec2 attrex;
layout (location = 3) in float alph;
layout (location = 4) in float id;

**some  code snippets** 

  VkVertexInputBindingDescription vertex_input_bindings{
      .binding = 0,
      .stride = sizeof(Vertex),
      .inputRate = VK_VERTEX_INPUT_RATE_VERTEX,
  };
  VkVertexInputAttributeDescription vertex_input_attributes[5]{
          {
                  .binding = 0,
                  .location = 0,
                  .format = VK_FORMAT_R32G32B32A32_SFLOAT,
                  .offset = offsetof(Vertex, pos),
          },
          {
                  .binding = 0,
                  .location = 1,
                  .format = VK_FORMAT_R32G32_SFLOAT,
                  .offset = offsetof(Vertex, texcoord),
          },
          {
                  .binding = 0,
                  .location = 2,
                  .format = VK_FORMAT_R32G32_SFLOAT,
                  .offset = offsetof(Vertex, texcoordex),
          },
          {
                  .binding = 0,
                  .location = 3,
                  .format = VK_FORMAT_R32_SFLOAT,
                  .offset = offsetof(Vertex, alpha),
          },
          {
                  .binding = 0,
                  .location = 4,
                  .format = VK_FORMAT_R32_SFLOAT,
                  .offset = offsetof(Vertex, idx),
          }};

VkPipelineVertexInputStateCreateInfo vertexInputInfo{
      .sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO,
      .pNext = nullptr,
      .vertexBindingDescriptionCount = 1,
      .pVertexBindingDescriptions = &vertex_input_bindings,
      .vertexAttributeDescriptionCount = 5,
      .pVertexAttributeDescriptions = vertex_input_attributes,
  };

VkDeviceSize offset = 0;
vkCmdBindVertexBuffers(render.cmdBuffer_[bufferIndex], 0, 1, &buffers.vertexBuf_, &offset);

How can I solve the problem? Thanks for any help.

**Comment by krOoze** [comment]
This is the ticket system for the specification, not a debug help site. Please keep the Issues on topic.
