### ISSUE TITLE
VK_EXT_conservative_rasterization Interactions and External Dependencies

### ISSUE THREAD

**Issue by MulattoKid** [KhronosGroup/Vulkan-Docs#1288]
When looking at [VK_EXT_post_depth_coverage](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_post_depth_coverage.html), there's a list of external dependencies and interactions for said extension. This is not the case when looking at [VK_EXT_conservative_rasterization](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_conservative_rasterization.html).

In order to make use of the _fullyCoveredFragmentShaderInputVariable_ property (if supported by the implementation), I believe the following is required:

- [SPV_EXT_fragment_fully_covered](http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/EXT/SPV_EXT_fragment_fully_covered.html)
- [GL_NV_conservative_raster_underestimation](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_conservative_raster_underestimation.txt) to write GLSL code using `gl_FragFullyCoveredNV` which is translated to SPIR-V's `FullyCoveredEXT`.

And in order to make use of the _conservativeRasterizationPostDepthCoverage_ property (if supported by the implementation), I believe the following is required:

- [VK_EXT_post_depth_coverage](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_post_depth_coverage.html) to allow the `PostDepthCoverage OpExecutionMode` to be used, by using the GLSL built-in variable `gl_SampleMaskIn`.

**Comment by pdaniell-nv** [comment]
Thanks for your issue. We'll fix the spec.

**Comment by MulattoKid** [comment]
I just had a look here https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_conservative_rasterization.html and the docs seems to have been updated. I think this can be closed.

**Comment by oddhack** [comment]
OK. You should be able to close your own issues, too.

**Comment by MulattoKid** [comment]
Just wanted to get a verification :)
