### ISSUE TITLE
Editorial (1.0.5) Section 9.2 Graphics Pipelines

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-Docs#129]
pRasterState is a pointer to an instance of the VkPipelineRasterizationStateCreateInfo structure.

should be:

pRasterizationState is a pointer to an instance of the VkPipelineRasterizationStateCreateInfo structure.

**Comment by oddhack** [comment]
Thanks! I'll fix these in the next public update.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.7 spec update.
