### ISSUE TITLE
Shouldn't CreateImageInof validity for cube compatible be arrayLayers a multiple of 6?

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/Vulkan-Docs#1290]
The spec. (1.2.142) in the validity rules for `VkCreateImageInfo` says

```
If imageType is VK_IMAGE_TYPE_2D and flags contains VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT, extent.width and extent.height must be equal and arrayLayers must be greater than or equal to 6
```

According to this it would be valid for arrayLayers to have a value of 7. Really? Doesn't it have to be a multiple of 6?

**Comment by jeffbolznv** [comment]
Cube views have to be equal to 6 and CubeArray views have to be a multiple of 6, but the image need not be a multiple of 6.

**Comment by MarkCallow** [comment]
I see. Thank you.
