### ISSUE TITLE
Can we allow SHADER_READ_ONLY_OPTIMAL for read-only depth/stencil?

### ISSUE THREAD

**Issue by kvark** [KhronosGroup/Vulkan-Docs#1291]
We have a problem exposing read-only depth (RODS) in WebGPU, described https://github.com/gpuweb/gpuweb/pull/859. Ideally, we'd like the same descriptor sets (`GPUBindGroup`) to be used in both RODS and non-rods passes. However, this would require us to have all sampled images in `VK_IMAGE_LAYOUT_GENERAL` layout, which is inefficient.

It would be great if we could have all sampled images in `VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL` and specify this layout for the d/s attachment of RODS render passes. Vulkan validation currently requires such attachments to be in either `VK_IMAGE_LAYOUT_GENERAL` or one of the depth-stencil-specific layouts, so `VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL` is not allowed. Is this limitation present in the actual driver/hardware?

**Comment by Tobski** [comment]
Hi @kvark, thanks for the input - we can see how this would be a little awkward, and we'll take this into consideration for the future. For now though, I suspect the most pragmatic solution is to simply switch between SHADER_READ_ONLY and DEPTH_STENCIL_READ_ONLY based on the format of the image, rather than using GENERAL.

**Comment by kvark** [comment]
Thanks for responding @Tobski ! 
> simply switch between SHADER_READ_ONLY and DEPTH_STENCIL_READ_ONLY based on the format of the image, rather than using GENERAL.

That's an interesting idea! Would `DEPTH_STENCIL_READ_ONLY` be less efficient for regular image sampling than `SHADER_READ_ONLY`?

What I was going to suggest WebGPU next is just lifting up the distinction about RO/RW to the view creation, so that a view knows if it's read-only or not. This would let us pick the proper layout in all cases, see https://github.com/gpuweb/gpuweb/pull/860

**Comment by Tobski** [comment]
> That's an interesting idea! Would DEPTH_STENCIL_READ_ONLY be less efficient for regular image sampling than SHADER_READ_ONLY?

That's really a question for other vendors, but to my knowledge (and I have asked about this in the past) nobody is expecting reduced efficiency from this particular usage.

**Comment by kvark** [comment]
Alright, we can close this then. Our implementation has switched to use `DEPTH_STENCIL_READ_ONLY` for depth textures even if they are just sampled.

**Comment by oddhack** [comment]
Closing per @kvark above
