### ISSUE TITLE
Unclear interaction between VIEWPORT and VIEWPORT_WITH_COUNT dynamic state

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1296]
The interaction between `VK_DYNAMIC_STATE_VIEWPORT` and `VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT_EXT` seem unclear. Same thing with `SCISSOR`.

It does not seem to be outright forbidden to enable both dynamic states in the pipeline. Then again it is not clear what should happen when both dynamic states **are** enabled, and how their respective `vkCmdSet*` interact with each other.

Additionally the NV viewport dynamic extensions potentially need an update, as they seem to depend on `VK_DYNAMIC_STATE_VIEWPORT`, but not the new one. E.g. `VUID-VkPipelineViewportStateCreateInfo-viewportWScalingEnable-01726` would prevent usage of these extensions with the new dynamic state.

Also `VUID-VkPipelineViewportStateCreateInfo-viewportCount-arraylength` contradicts `VUID-VkGraphicsPipelineCreateInfo-pDynamicStates-03379`.

**Comment by oddhack** [comment]
This should be fixed in the 1.2.149 spec update.

**Comment by krOoze** [comment]
As I commented in the commit log, the solution seems to be generally allow extension viewport counts to be greater than the non-extension count.

 - that is relaxing restrictions, so probably should bump revision number of the extensions
 - has the problem that `multipleViewport` restriction does not have the transitional property, and is now missing in the extensions
 - has the problem that `maxViewports` restriction does not have the transitional property, and is now missing in the extensions
 - for consistency it feels the extension viewport counts should also be forced to `0` if the Viewport count is dynamic and the extension state is also dynamic.
