### ISSUE TITLE
Typo: Constants Documentation for VkMemoryPropertyFlags

### ISSUE THREAD

**Issue by SE2Dev** [KhronosGroup/Vulkan-Docs#13]
It appears that the documentation page for `VkMemoryPropertyFlags` incorrectly documents the following enumerations for `VkMemoryPropertyFlagBits`:

- `VK_MEMORY_PROPERTY_DEVICE_ONLY ` is incorrectly used in place of `VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT`
- `VK_MEMORY_PROPERTY_HOST_NON_COHERENT_BIT ` is incorrectly used in place of `VK_MEMORY_PROPERTY_HOST_COHERENT_BIT`
- `VK_MEMORY_PROPERTY_HOST_UNCACHED_BIT ` is incorrectly used in place of `VK_MEMORY_PROPERTY_HOST_CACHED_BIT`

The documentation summaries for `VK_MEMORY_PROPERTY_HOST_NON_COHERENT_BIT` and `VK_MEMORY_PROPERTY_HOST_UNCACHED_BIT` appear to reflect these names as well.

---------
VkMemoryPropertyFlagBits is defined as the following in `/src/vulkan/vulkan.h`:

``` c
typedef enum VkMemoryPropertyFlagBits {
    VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT = 0x00000001,
    VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT = 0x00000002,
    VK_MEMORY_PROPERTY_HOST_COHERENT_BIT = 0x00000004,
    VK_MEMORY_PROPERTY_HOST_CACHED_BIT = 0x00000008,
    VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT = 0x00000010,
} VkMemoryPropertyFlagBits;
```

These flags are documented in the **Constants** section of `\doc\specs\vulkan\man\VkMemoryPropertyFlags.txt` and appear as follows:
```
ename:VK_MEMORY_PROPERTY_DEVICE_ONLY::
    Unless any other flag is used to enable other uses this constant
    identifies memory that's only accessible by the device.

ename:VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT::
    Identifies a memory pool that can be mapped into host memory address
    space and thus is accessible by the host.

ename:VK_MEMORY_PROPERTY_HOST_NON_COHERENT_BIT::
    Identifies a memory pool where accesses beteen the host and the
    coherency domain are not conherent. Memory with this property needs
    explicit use of flink:vkFlushMappedMemoryRanges after host writes to
    this type of memory, and use of flink:vkInvalidateMappedMemoryRanges
    before host reads from that memory.

ename:VK_MEMORY_PROPERTY_HOST_UNCACHED_BIT::
    Identifies memory that is not cached by the host.

ename:VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT::
    Identifies memory where an object's backing may be provided lazily
    (when needed) by the implementation.
```

**Comment by oddhack** [comment]
Thanks! We will be fixing these in a near-future updated from the internal repos, once approved by the working group. They are good catches dating back to one of our internal naming discussions that was reflected in the spec, but not the ref pages.
