### ISSUE TITLE
Layer and extension names should not be optional for vkCreateDevice in all cases

### ISSUE THREAD

**Issue by polarina** [KhronosGroup/Vulkan-Docs#130]
Section 4.2.1, Device Creation, has this to say about valid usages:

> If enabledLayerCount is not 0, and ppEnabledLayerNames is not NULL, ppEnabledLayerNames must be a pointer to an array of enabledLayerCount null-terminated strings

and

> If enabledExtensionCount is not 0, and ppEnabledExtensionNames is not NULL, ppEnabledExtensionNames must be a pointer to an array of enabledExtensionCount null-terminated strings

These conditions imply that passing a positive `enabledLayerCount` or `enabledExtensionCount` with a corresponding `NULL` for `ppEnabledLayerNames` and `ppEnabledExtensionNames`, respectively, is valid.

**Comment by courtney-g** [comment]
This affects the header generation scripts, will discuss in Khronos work group and provide resolution here.

**Comment by philiptaylor** [comment]
The equivalent fields in VkInstanceCreateInfo look more sensibly defined to me, it seems the difference is probably just an optional="true" in the XML.

**Comment by courtney-g** [comment]
Most likely. Want to check if there are any other similar fields that need help as well.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.7 spec update.
