### ISSUE TITLE
`vkGetPhysicalDeviceFeatures2` Needs Better Documentation

### ISSUE THREAD

**Issue by nicebyte** [KhronosGroup/Vulkan-Docs#1309]
Here is what the current version has to say:

> Each structure in pFeatures and its pNext chain contains members corresponding to fine-grained features. vkGetPhysicalDeviceFeatures2 writes each member to a boolean value indicating whether that feature is supported.

Now, this may be obvious in retrospect, but the implication is that the user is supposed to _provide_ a `pNext` chain with structures corresponding to the device features that they are interested in. 

My initial understanding was that I would be given a long `pNext` chain that I would then have to walk myself to find the information relevant to me. This led to much confusion.

The actual intended usage of the API is much more convenient, but it's not very obvious from reading the page (at least to me). I think there should be a better wording. Perhaps something along the lines of: 

> Each element in the provided `pNext` chain will be initialized with the fine-grained features corresponding to its structure type.

**Comment by sfricke-samsung** [comment]
Thanks for feedback

- There is a chapter in the Vulkan Guide about [pNext](https://github.com/KhronosGroup/Vulkan-Guide/blob/master/chapters/pnext_and_stype.md)
- There is a section on [Using vkGetPhysicalDeviceFeatures2 ](https://github.com/KhronosGroup/Vulkan-Guide/blob/master/chapters/enabling_features.md#how-to-enable-the-features) in the Vulkan Guide as well

I am not dismissing that it might be better to add the extra language/sentence you proposed, but it is easier to "approve" of the addition if you create a PR with what you think should be added for clarity

**Comment by nicebyte** [comment]
Fair enough - I will try to flesh out a better wording and send a PR.

**Comment by oddhack** [comment]
Passing in pNext chains to make queries extensible isn't intended to be something unique to this one Get command, so I suggest genericizing whatever language you're proposing, dropping it somewhere in the Fundamentals chapter (perhaps as a 3rd-level subsection under the 'Object Model' section - the current discussion of pNext chains is entirely inside the Errors / Valid Usage section and not all of it really belongs there), and linking to it from the Get command appendix.

**Comment by oddhack** [comment]
@nicebyte is this still something you might propose a PR for? If not, please close this.
