### ISSUE TITLE
VkSubpassDescription missing layout VUs?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1316]
`VkSubpassDescription` might be missing image layout VUs.

E.g. `pColorAttachments` should have `VkAttachmentReference::layout` restricted to either `VK_IMAGE_LAYOUT_GENERAL`, `VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL`, or `VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR`?

**Comment by sfricke-samsung** [comment]
I am currently looking into these set of VUs within the Validation Layers, will take control of this, thanks for pointing it out!

**Comment by oddhack** [comment]
This should be addressed in the 1.2.152 spec update.
