### ISSUE TITLE
Constraints on groups returned by vkEnumeratePhysicalDeviceGroups

### ISSUE THREAD

**Issue by janekb04** [KhronosGroup/Vulkan-Docs#1318]
I have a few questions regarding `vkEnumeratePhysicalDeviceGroups` that I could not find answers to in the spec:

1.  Can a single physical device appear in multiple groups?
2.  Is it guaranteed that any PD (any PD returned by `vkEnumeratePhysicalDevices`) is in (at least) one group (that would allow to use only `vkEnumeratePhysicalDeviceGroups` and not have to call `vkEnumeratePhysicalDevices` at all; for systems with one PD this would present a single group with a size of one)?

If the answers are in the spec and I missed them I would appreciate a pointer to their location. Thanks!

**Comment by janekb04** [comment]
Question 3 (may be a little off topic):

What kind of performance penalty can be expected from using a logical device created from multiple physical devices instead of creating a single logical device per physical device and distributing the workload between them manually?

I suspect its more then negligible, as it seems with Vulkan that the more explicit, the better, though I could be wrong as driver developers know Vulkan better than me and have access to more sophisticated means of optimization (though this is the same kind of argument that encourages the usage of OpenGL over Vulkan).

**Comment by krOoze** [comment]
ad Q 1 and 2 ([Devices](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#devsandqueues-devices) chapter):

> Every physical device **must** be in exactly one device group.

ad Q 3: AFAIK the device groups have special relationship. Something you cannot just do by using the single physical device interface. So it is not exactly comparable. Notably, without the groups the Crossfire\SLI bridge would go unused. Or the direct GPU-to-GPU PCIe transfers would not work. You would have to transfer memory using the regular `vkMapMemory` command, which might not be as great.

**Comment by janekb04** [comment]
Ok, now I understand. Thanks for such a quick reply!
