### ISSUE TITLE
VK_STRUCTURE_TYPE_DRM_FORMAT_MODIFIER_PROPERTIES_EXT never used

### ISSUE THREAD

**Issue by asuessenbach** [KhronosGroup/Vulkan-Docs#1325]
In vk.xml, the extension "VK_EXT_image_drm_format_modifier" specifies "VK_STRUCTURE_TYPE_DRM_FORMAT_MODIFIER_PROPERTIES_EXT" as an extension of "VkStructureType" with offset 1.

But that value is never used anywhere, there's no structure specified to use that value for its sType.

Should that value be removed?

**Comment by dgkoch** [comment]
cc @chadversary as extension contact/owner

**Comment by oddhack** [comment]
Already reported internally, issue 2275. Closing the public tracker.

**Comment by expipiplus1** [comment]
Looks like this is fixed now in 1.2.157: https://github.com/KhronosGroup/Vulkan-Docs/compare/cee0f4b12acde766e64d0d038b03458c74bb67f1...fa50015cb517fc3105ffdab1fc055e322a682265#diff-92d0e5376f9e604e03fac86fbb661950

In cases like this, would it be possible to link to this issue too in the changelog to help people avoid hunting for github issues?

**Comment by oddhack** [comment]
> In cases like this, would it be possible to link to this issue too in the changelog to help people avoid hunting for github issues?

We generally do, but lost the association between the internal and external issues at some point. Sorry about that.

**Comment by expipiplus1** [comment]
Cool, no worries, thanks
