### ISSUE TITLE
Subgroup properties on 1.0

### ISSUE THREAD

**Issue by martty** [KhronosGroup/Vulkan-Docs#1326]
There are 2 subgroup extensions that require 1.0 (VK_EXT_shader_subgroup_ballot and VK_EXT_shader_subgroup_vote). 
These have smaller functionality than what was then subsequently standardized into 1.1, including the ability to query granular subgroup support and subgroup size. This information is subsequently not available (to my understanding) to programs targeting 1.0 + the aforementioned extensions. As far as I can tell the extensions themselves don't specify the values that can be queried on 1.1, which leaves me unsure if those extensions can be safely used.

Is there a way to work around this?

**Comment by oddhack** [comment]
Unfortunately, there isn't. You'll need to use 1.1 for that.
