### ISSUE TITLE
descriptor index for acceleration structure in vk_khr_ray_tracing

### ISSUE THREAD

**Issue by yunpengzhu** [KhronosGroup/Vulkan-Docs#1327]
Acceleration structure is a new descriptor type.
There's no feature control to show descriptor index for acceleration structure.
Does it mean that  neither uniform nor non uniform indexing is allowed for acceleration structure?

**Comment by Tobski** [comment]
Thanks for your feedback! We're aware of the lack of feature bit and plan to fix it, but this is allowed, please see the end of this section:

> https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#interfaces-resources-descset

It lists acceleration structures as dynamically indexed without a capability.
