### ISSUE TITLE
corner case in vk_khr_ray_tracing

### ISSUE THREAD

**Issue by yunpengzhu** [KhronosGroup/Vulkan-Docs#1328]
These cases are meanless in the applications. Are they explicitly not allowed to set  in the spec?
Bottom AS Geometrycount =0
Bottom AS geometry object has primitive count = 0
Top AS instancecount=0
Top AS all the instances are inactive
Bottom AS all primitives are inactive

**Comment by Tobski** [comment]
Thanks for your feedback! Whilst these cases are somewhat useless, they are intended to be completely valid as it's expected these will come up occasionally during the normal operation of a ray tracing application, so they are definitely allowed. As you've pointed this out, we'll make sure these get tested as part of the final CTS tests, and I've raised [this issue](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2081) with the validation layers to fire out a warning if these cases are encountered. Hopefully that addresses your questions!
