### ISSUE TITLE
Submission order vs execution order and play back.

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#133]
Chapter 2.1.1 defines the ordering of work submitted to the queue:

> Command buffers submitted to a single queue are played back in the order they were submitted, and commands within each buffer are played back in the order they were recorded.

This would appear to contradict Chapter 5's statement about ordering:

> Unless otherwise specified, and without explicit synchronization, the various commands submitted to a queue via command buffers may execute in arbitrary order relative to each other, and/or concurrently.

I think the confusion here is due to the ambiguous term "played back" in Chapter 2.1.1. The idea, as I understand it, is that Chapter 2 is trying to define submission ordering, which is the order of command buffers and commands within buffers for a queue. Chapter 5 is defining the _execution_ ordering, which is largely unordered except where otherwise stated. The term "played back" makes this ambiguous, since it sounds like execution rather than simple ordering.

**Comment by oddhack** [comment]
My first thought is to do away with "played back" and instead do something like "submitted to a queue" / "submitted for execution from a queue" or perhaps "added to a queue" / "command submitted for execution". We'll take a look at it.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.40 spec update.
