### ISSUE TITLE
VK_NULL_HANDLE has a type mismatch with non-dispatchable handles in C++ on many architectures

### ISSUE THREAD

**Issue by sylistine** [KhronosGroup/Vulkan-Docs#1332]
Vulkan.h defines `VK_DEFINE_NON_DISPATCHABLE_HANDLE` as a pointer type on many architectures, which means `VK_NULL_HANDLE` cannot be assigned to these handles in strictly typed situations (templates, etc).

I believe `VK_NULL_HANDLE` should be defined as `nullptr` for C++ in this situation, if only to more explicitly match the pragma'd redefinition of `VK_DEFINE_NON_DISPATCHABLE_HANDLE`.

The area of Vulkan.h in question:
```
#define VK_NULL_HANDLE 0

#define VK_DEFINE_HANDLE(object) typedef struct object##_T* object;

#if !defined(VK_DEFINE_NON_DISPATCHABLE_HANDLE)
#if defined(__LP64__) || defined(_WIN64) || (defined(__x86_64__) && !defined(__ILP32__) ) || defined(_M_X64) || defined(__ia64) || defined (_M_IA64) || defined(__aarch64__) || defined(__powerpc64__)
    #define VK_DEFINE_NON_DISPATCHABLE_HANDLE(object) typedef struct object##_T *object;
#else
    #define VK_DEFINE_NON_DISPATCHABLE_HANDLE(object) typedef uint64_t object;
#endif
#endif
```

A C++ sample that seems like it should but does not work on certain architectures (i.e.: x86-64):
```
auto oldHandle = std::exchange(m_nonDispatchableHandle, VK_NULL_HANDLE);
```

I propose the following:
```
#ifdef __cplusplus
    #define VK_NULL_HANDLE nullptr
#else
    #define VK_NULL_HANDLE 0
#endif
````

**Comment by oddhack** [comment]
@asuessenbach @mtavenrath would it causes any issues for Vulkan-Hpp's consumption of the XML if we changed the definition of VK_NULL_HANDLE along these lines? Also, do you have any insights on exactly how such a change should be structured to deal with @sylistine's issue while not affecting existing Vulkan C++ code using the C headers? We discussed briefly this morning and feel the change proposed above may need codesmithing, but we need some more C++ experts to provide input before deciding whether to proceed or not with this.

**Comment by krOoze** [comment]
Indeed some codesmithing needed. `nullptr` is "only" C++11. And notably VS was bad at updating `__cplusplus`, so might need some extra preprocessor.

Might also want to over-ride the definition, if custom non-dispatchable handle types are used.

```
#ifndef VK_NULL_HANDLE
#if ...   //is pointer-like
#if defined(__cplusplus) && (__cplusplus >= 201103L || MSC_VER >= ?)
#define VK_NULL_HANDLE nullptr
#else // __cplusplus && (__cplusplus >= 201103L || MSC_VER >= ?)
#define VK_NULL_HANDLE NULL
#endif // __cplusplus && (__cplusplus >= 201103L || MSC_VER >= ?)
#else //is pointer-like
#define VK_NULL_HANDLE ((uint64_t)0)
#endif //is pointer-like
#endif //VK_NULL_HANDLE

**Comment by asuessenbach** [comment]
I would expect problems in vk.xml, to make `VK_NULL_HANDLE` "more type-safe": while `VK_DEFINE_HANDLE` is always a pointer type, `VK_DEFINE_NON_DISPATCHABLE_HANDLE` is a pointer type only under certain circumstances. But `VK_NULL_HANDLE` should probably work with both handle types.
I can't see how that could be resolved without modifying the definitions of those two handle types.

**Comment by krOoze** [comment]
> But `VK_NULL_HANDLE` should probably work with both handle types.

That would be nice, but not how it is specified. Per spec, `VK_NULL_HANDLE` is for NDHs, and `NULL` is for DHs. Thouhg some use it wrong, and therefore their code might break at compile-time when messing with this.

**Comment by asuessenbach** [comment]
> Per spec, VK_NULL_HANDLE is for NDHs, and NULL is for DHs.

That's kind of right. But VK_NULL_HANDLE is used all over the spec as the null value for NDHs as well.

**Comment by krOoze** [comment]
Not "kinda".

> The reserved values `VK_NULL_HANDLE` and `NULL` **can** be used in place of valid non-dispatchable handles and dispatchable handles, **respectively**

**Comment by krOoze** [comment]
I have found only one wrong usage of `VK_NULL_HANDLE` in the spec (#1347). Though the debug extensions do type punning and use `uint64_t` for all handles, and do reference `VK_NULL_HANDLE`.

**Comment by asuessenbach** [comment]
Some places, where VK_NULL_HANDLE is used for NDHs:

- https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkDestroyCommandPool-commandPool-parameter
- https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkCommandBufferBeginInfo-flags-00055
- https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkQueueSubmit-fence-00063
- https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkDestroySemaphore-semaphore-parameter
... and probably many more.

**Comment by krOoze** [comment]
@asuessenbach `VK_NULL_HANDLE` is used for NDHs. That is correct.

**Comment by asuessenbach** [comment]
Oops, you're right (of course). Please sorry for my confusion!

**Comment by asuessenbach** [comment]
But, to come back to the questions:

> would it causes any issues for Vulkan-Hpp's consumption of the XML if we changed the definition of VK_NULL_HANDLE along these lines?

Some minor changes in the generator would be needed.
Besides that, the 'is pointer-like' check should probably be the exact same condition as is used with the definition of VK_DEFINE_NON_DISPATCHABLE_HANDLE.

**Comment by luckyxxl** [comment]
Isn't this resolved by now? `vulkan_core.h` defines `VK_NULL_HANDLE` as `nullptr` if it's deemed to be supported.

**Comment by oddhack** [comment]
@sylistine there were pretty significant changes in the definition of VK_NULL_HANDLE a few months ago, though we did not notice the relationship to this issue at the time. Could you check against the current headers and close this issue if they've resolved it?

**Comment by oddhack** [comment]
Closing per previous comment. @sylistine if you think there are still problems in this area, please reopen and comment.
