### ISSUE TITLE
Official Rust bindings generator

### ISSUE THREAD

**Issue by ethindp** [KhronosGroup/Vulkan-Docs#1334]
I'm not sure if I'm filing this in the right place -- apologies if I'm not. I'd like to contribute to this project though, and would like to add a Rust bindings generator. I've been looking at the code for the generator base classes as well as the code for the C bindings generator. Adding one for Rust doesn't seem too complex, however I'm not really sure how to alter the generator to extend it for other languages. Like the C bindings, I'm not looking to generate "idiomatic" Rust bindings -- those can be wrapped. I know that there are already vulkan generators out there like vk_generator and vkgen, but neither of those appear to work anymore with the latest specifications. What would I need to do to modify the generator (either through subclassing or through modification of scripts/generator.py) to add another language to the list of generated bindings?

**Comment by krOoze** [comment]
You would fork the cgenerator.py. Make your own Options and Generator class, as the `cgenerator` does. Then you would add instance of your Options class to `genvk.py` related to some rust file(s) you want to generate. Then you would add to `xml/Makefile` to invoke the stuff.

**Comment by oddhack** [comment]
While we're happy to see new language bindings created, we probably don't want to host them in this repository - that creates a long-term maintenance burden none of us would be in a position to satisfy. Suggest you fork the Vulkan-Docs repository and host your own project for this (though really all you need i scripts/ and xml/ directories). Since new extensions / APIs are added by modifying vk.xml in this repo, you would want to keep it synced up pretty often.

**Comment by oddhack** [comment]
I'll leave this assigned to me in case of specific questions, but there's not a lot to say until you get into coding the bindings.

**Comment by ethindp** [comment]
I've actually found this to be completely unnecessary; there are two crates -- [ash](https://crates.io/crates/ash) and [erupt](https://crates.io/crates/erupt) that have low-level bindings to Vulkan. Though it would be nice if there was an official generator for Rust so that the Vulkan SDK comes with rust bindings people can just copy into their projects, this already exists on an unofficial basis as a Rust crate. Modifying the C generator (as of 7c18dc68) to conform to Rust presents some problems though:

1. There is no such thing as "inclusion guards" for rust -- the compiler takes care of multiple module inclusion by spitting out an appropriate error.
2. Feature interface protection via `#ifndef`...`#endif` could be changed to `#[feature(...)]`. However, we'd most likely need to contain that in an entirely separate module per feature, unless we want `#[feature(...)]` duplicated a few thousand times depending on feature (I'm not precisely sure what this corresponds to in actual code). We'd need the same for prototypes -- either a separate module or just a tun of `#[feature(...)]`s.
3. The `apicall`, `apientryp`, and `apientry` options don't need to exist; rust just allows you to use `extern "C"` or `extern "system"`. I'm not really sure what would be appropriate for this. The erupt crate uses `extern "system"` (as illustrated on the page for the `PFN_vkGetInstanceProcAddr` function pointer type [here](https://docs.rs/erupt/0.11.0+148/erupt/vk1_0/type.PFN_vkGetInstanceProcAddr.html)). As noted in the [External Blocks](https://doc.rust-lang.org/reference/items/external-blocks.html) section of the Rust reference, there are 10 ABI strings, three of which are cross-platform (`Rust`, `C`, and `system`) and 7 that are platform-specific (`cdecl`, `stdcall`, `win64`, `sysv64`, `aapcs`, `fastcall`, and `vectorcall`). Thoughts? I know that in the C headers, this is a conditional based on platform, but Rust makes this a bit simpler.
4. What are `BEGIN_RANGE` and `END_RANGE`? We may not need these in Rust at all.
5. Finally, the alias macros (or macros in general) that are function-based will be difficult to port. Rusts macro system is a lot more complex than that of C's macro system. Take for example the `VK_MAKE_VERSION` macro in C:
    ```C
    #define VK_MAKE_VERSION(major, minor, patch) \
        (((major) << 22) | ((minor) << 12) | (patch))
    ```
    In Rust, this might translate to:
    ```rust
    macro_rules! make_version {
        ($major:expr, $minor:expr, $patch:expr) => ((major << 22) | (minor << 12) | patch)
    }
    ```

Thoughts on these particular problems? Most of them have solutions but I'd appreciate input -- I really would like to see this in the Vulkan repositories someday!

**Comment by krOoze** [comment]
A crate feels like a more Rusty solution, as that is also the way dependencies are defined.

ad 1. Sounds like a non-problem if Rust does not need include guards.
ad 2. IIRC that is already done even in C. There is per-platform header + beta.
ad 3. Consult `vk_platform.h`. It is not liable to change for existing platforms, and could be hardcoded (and only checked if the XML changed).
ad 4. Those are extra-specification, and removed in 1.2.140
ad 5. Most macros are basically global `constexpr` functions or constants.

**Comment by oddhack** [comment]
However Rust implements calls into C code, it still needs to comply with the convention expected *in* the C code - which is just as true for C language apps, and thus the platform-specific definitions of these macros in vk_platform.h. Maybe you could just fold that into your bindings generator; although vk_platform.h is subject to modification on new platforms, the rate of change is extremely low. So if you would be chasing a moving target, it's very slow moving.

Probably the best thing to do for the macros is special-case them in the generator rather than try to translate arbitrary C preprocessor text on the fly. The macros are also slow to change.

**Comment by Lokathor** [comment]
As was said earlier: the [ash](https://docs.rs/ash) crate is already the "ecosystem standard" for Rust calling Vulkan. There's no need for a new crate, and also no need for such a thing to be hosted in any KhronosGroup repository.

That said, people are of course free to make additional generators. In fact I spent a few hours yesterday on a generator of my own. It's just that there's not any big need ecosystem need for such a thing to be made. You can still do it for fun, or to learn, or whatever personal reason.

**Comment by oddhack** [comment]
Closing this. @MarijnS95 who owns ash-rs is active inside Khronos now and we are helping out with some of their requests.
