### ISSUE TITLE
Is protectedMemory without protected queues useful?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1335]
Spec says:

> If the protected memory physical device feature is supported, then at least one queue family of at least one physical device exposed by the implementation **must** support this bit.

Why not simply:

>  If the protected memory physical device feature is supported, then the physical device  **must** support this bit.

Seems that protected memory cannot be accessed on Host. And I would think without protected queue it cannot be accessed on Device. So the corner-case of a device with protected memory features, but no protected queue does not make sense to me. It would allow only allocating the memory, and do nothing with it.

Is this some intentional future-proofing, or is it a spec bug?

**Comment by sfricke-samsung** [comment]
> So the corner-case of a device with protected memory features, but no protected queue does not make sense to me

I don't see where this corner case is being pulled from. The `protectedMemory` feature is true, then at least one queue family will support `VK_QUEUE_PROTECTED_BIT`

Protected memory is a single feature boolean for everything, there is not feature bit just for allocating or queue submission

**Comment by krOoze** [comment]
I quoted the spec. It says if protected feature is supported on one physical device, then some (potentially other) physical device has to have protected queue family. That implies there might be a physical device that has protected feature support, but no protected queue family.

There is not feature bit just for queue submission, but there is queue family enumaration, and it might return no protected queue families.
Now that you mention it, sanity requirements are missing for Memory Type enumeration too.

**Comment by oddhack** [comment]
This should be fixed in the 1.2.151 spec update.
