### ISSUE TITLE
Inconsistent if oldLayout\newLayout must match current layout

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1337]
Spec: 

> The old layout **must** either be `VK_IMAGE_LAYOUT_UNDEFINED`, or match the current layout of the image subresource range.

Also spec:

> - If `srcQueueFamilyIndex` and `dstQueueFamilyIndex` define a _queue family ownership transfer_ or `oldLayout` and `newLayout` define a _image layout transition_, `oldLayout` **must** be `VK_IMAGE_LAYOUT_UNDEFINED` or the current layout of the image subresources affected by the barrier
>- If `srcQueueFamilyIndex` and `dstQueueFamilyIndex` define a queue family ownership transfer or `oldLayout` and `newLayout` define a _image layout transition_, `newLayout` **must** not be `VK_IMAGE_LAYOUT_UNDEFINED` or `VK_IMAGE_LAYOUT_PREINITIALIZED`

It seems unclear if e.g. `oldLayout = VK_IMAGE_LAYOUT_UNDEFINED, newLayout = VK_IMAGE_LAYOUT_UNDEFINED`. is valid. I think maybe 1.2.142 update accidentally relaxed the VUs.

Additionally I think the spec does not specify when "`oldLayout` and `newLayout` define a _image layout transition_". At least the VU link seems unhelpful to determine that. It only says:

> Image subresources **can** be transitioned from one layout to another as part of a memory dependency (e.g. by using an image memory barrier).

I assume it is when `oldLayout != newLayout`.

**Comment by jekstrand** [comment]
> It seems unclear if e.g. `oldLayout = VK_IMAGE_LAYOUT_UNDEFINED`, `newLayout = VK_IMAGE_LAYOUT_UNDEFINED` is valid.

You gave a spec quote for the VU which explicitly disallows any case in which `newLayout = VK_IMAGE_LAYOUT_UNDEFINED` is disallowed.  How is this unclear?

> I think maybe 1.2.142 update accidentally relaxed the VUs.

What VUs do you think 1.2.142 relaxed?

**Comment by krOoze** [comment]
> You gave a spec quote for the VU which explicitly disallows any case in which `newLayout = VK_IMAGE_LAYOUT_UNDEFINED` is disallowed. How is this unclear?

It is contitioned "if `oldLayout` and `newLayout` define a _image layout transition_". One could argue `oldLayout == newLayout`, does **not** "define a _image layout transition_", and therefore `oldLayout = VK_IMAGE_LAYOUT_UNDEFINED, newLayout = VK_IMAGE_LAYOUT_UNDEFINED` would be valid.

> What VUs do you think 1.2.142 relaxed?

The quoted ones. The removed versions were:

> * [[VUID-VkImageMemoryBarrier-oldLayout-01197]]
    pname:oldLayout must: be ename:VK_IMAGE_LAYOUT_UNDEFINED or the current
    layout of the image subresources affected by the barrier
>  * [[VUID-VkImageMemoryBarrier-newLayout-01198]]
    pname:newLayout must: not be ename:VK_IMAGE_LAYOUT_UNDEFINED or
    ename:VK_IMAGE_LAYOUT_PREINITIALIZED

which are unconditional on neither `srcQueueFamilyIndex` and `dstQueueFamilyIndex`, nor on whether they "define a _image layout transition_".

**Comment by jekstrand** [comment]
> It is contitioned "if oldLayout and newLayout define a image layout transition". One could argue oldLayout == newLayout does not "define a image layout transition", and therefore oldLayout = VK_IMAGE_LAYOUT_UNDEFINED, newLayout = VK_IMAGE_LAYOUT_UNDEFINED would be a valid usage.

Ah, thanks for clarifying and good catch!  Looking at the internal git history, this appears to be part of some general spec clean-up work.  I don't think the removal of those VUs was intentional.  I can raise an internal issue to get them re-instated or, if you'd like, you can feel free to make a public MR to add those VUs back in to the new common section.

**Comment by krOoze** [comment]
The VUs I quoted seem to replace them, plus-minus issues in this Issue.
I do not immediately understand why the conditionals were added to the VU sentences, so I would prefer **not** to make a PR, as my proposed changes might be lossy of the intent of the author of 142.

**Comment by jekstrand** [comment]
Ok, I'll raise an internal issue and we'll get this sorted out.

**Comment by Tobski** [comment]
Sorry I'm responsible for this - didn't spot the issue til now though. So the key part here is "If ... oldLayout and newLayout define a image layout transition". Right now, they _always_ define an image layout transition (which is stated in the definition of that term, if not in the VU). There's an upcoming extension that changes that, I just pushed this particular change out before the extension lands. Not sure whether it makes sense to change this in the interim since it'll make more sense in the near future.

**Comment by Tobski** [comment]
Sorry for leaving this issue so long - the extension I hinted at above was VK_KHR_synchronization2, which has now been released. I can't see a way to more cleanly have both the core and extended spec work beyond what is already there, noting that it already links to the relevant section. So I'm tentatively closing this, but feel free to reopen if there are any suggestions.
