### ISSUE TITLE
Subpass feedback loop unspecified

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1338]
Spec:

> If a subpass uses the same attachment as both an input attachment and either a color attachment or a depth/stencil attachment, writes via the color or depth/stencil attachment are not automatically made visible to reads via the input attachment, causing a _feedback loop_, except in any of the following conditions:

It is unspecified what a "feedback loop" is. Seems like it should just say it is a memory hazard that leads to undefined results?

The whole thing could perhaps be a Note, as order of operations is already specified elsewhere?

**Comment by TomOlson** [comment]
Agreed, that language isn't great. I think it does kind of tell you what a feedback loop is, but it doesn't tell you why you should care. We're hashing out some better language.

**Comment by oddhack** [comment]
Changes were made to address this in the 1.2.159 spec update.
