### ISSUE TITLE
YCBCR planes memory allocation strategy is unclear

### ISSUE THREAD

**Issue by sasmaster** [KhronosGroup/Vulkan-Docs#1343]
Hi. I am working on a project where I decode mp4 into YUV420p (semi planar NV12) and copy into Vulkan image that uses multi-planar layout with format  VK_FORMAT_G8_B8R8_2PLANE_420_UNORM

I use Nvidia hardware decoder to decode, CUDA to map Vulkan's memory to CUDevice. Currently I am able to use such a setup,but ONLY with some video sizes. For example, 1280x720 size works, but 640x360 doesn't copy the frame data correctly.
First thing I noted Vulkan does when allocating memory for such an image - it pads the plane memory with decent amount of extra bytes. For example, for Y plane for frame size of 1280x720 the default size should be 921,600  bytes,but Vulkan returns 983,040,which is 61,440 more bytes. Now, in order to copy decoded YUV frame from NVIDIA decoded surface I must know offset in number of horizontal lines from start of Y plane to the start of UV plane,otherwise copying the whole frame data will write data related to UV plane into Y plane ( due to those extra bytes padding). What I figured out to be working for 1280x720 size was to divide Y plane size by pitch.Here for example the pitch is the width = 1280,so  983,040 / 1280  = 768. So providing cuMemCpy2D::dstY = 768 does the trick. 
But in case of video with frame resolution 640x360 the following happens:
Vulkan allocates 262144 bytes for Y plane .The pitch is 640. It is not divisible:  262144 x 640= 409.6  :/ 
I am not sure what value an offset of the UV plane should be in such a case as I was assuming that Vulkan requires memory size to be multiple of  64 byte ,as in the example with resolution 1280x720. But now I see this is not the case. And this second video is not copied correctly into Vulkan image.
I can't find anything in the docs which would shed some light regarding memory allocation strategy for these images. For example I don't understand why in case of 1280x720 Y plane height got extra 48 lines. Also in case of 640x360 ,I totally don't understand how to figure out offset in pitch lines for  Y plane with 262144  bytes size. How do I tell CUDA from where I start copying UV plane in such a case? Maybe this is also vendor's bug ,but even if this is, I think better documentation should be provided for this part of the API.

**Comment by TomOlson** [comment]
@sasmaster one of the NVIDIA folks will get in touch with you - after they figure out what's going on, we'll see what we can do to clarify the spec.

**Comment by pdaniell-nv** [comment]
This issue has been discussed in detail in an external thread and the conclusion is that this is an implementation specific detail and doesn't require an Vulkan specification change or clarification.

**Comment by shiuang** [comment]
@sasmaster and for others who may need this:
use vkGetImageSubresourceLayout to query size and offset (and rowPitch), e.g.
`
    VkImageSubresource imageSubres = {};
    VkSubresourceLayout subresLayout0, subresLayout1;
    imageSubres.aspectMask = VK_IMAGE_ASPECT_PLANE_0_BIT;
    vkGetImageSubresourceLayout(device, image, &imageSubres, &subresLayout0);
    imageSubres.aspectMask = VK_IMAGE_ASPECT_PLANE_1_BIT;
    vkGetImageSubresourceLayout(device, image, &imageSubres, &subresLayout1);

    ...

    ptrYPlane[subresLayout0.offset + yY * subresLayout0.rowPitch + xY] = yValue;
    prtUVPlane[subresLayout1.offset + yUV * subresLayout1.rowPitch + xUV] = uvValue;
`
