### ISSUE TITLE
Purpose of implicit layout transition dependency?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1348]
Follow-up from #302.

Similar language is still there in the spec, and it is not exactly clear what it is good for.

> Layout transitions that are performed via image memory barriers execute in their entirety in _submission order_, relative to other image layout transitions submitted to the same queue, including those performed by _render passes_. In effect there is an implicit execution dependency from each such layout transition to all layout transitions previously submitted to the same queue.

Layout transitions have otherwisely defined when they happen, so this language does not make sense. Is this some spec hack that makes something else work (e.g. I touched on this in #1193)?

Additionally, this language allows code such as this:

```
vkCmdPipelineBarrier( oldLayout = BLAH, newLayout = FOO, srcStage = TOP, dstStage = BOTTOM );
vkCmdPipelineBarrier( oldLayout = FOO, newLayout = COOL, srcStage = TOP, dstStage = BOTTOM );
```

Since there is implicit dependency based on submission order, then this is perfectly valid. Is this intentional?

In the other thread it was suggested this is because of Layout Transitions are defined in the terms of memory dependency (availability, visibility), which might cause problems in some cases. But it seems this language does not help that, as it says there is "only" execution dependency.

**Comment by Tobski** [comment]
So my recollection is that the original use case was to simplify resource tracking. As you can record your command buffers across multiple threads, you need to somehow determine the way that image layouts change in a way that remains parallelizable. One of the earliest ways people were doing this was by always transitioning from/to a "known" layout at the beginning/end of a command buffer, after all other accesses were complete. This meant there needed to be some way to guarantee that the transitions at the end of a command buffer would happen before transitions at the start of the next submitted command buffer. Since we don't have stage/access masks for layout transitions (or synchronization commands in general), we ended up with this guarantee.

There are much better ways to manage this that are in use in many applications I'm aware of, making this guarantee somewhat unnecessary, but we're not going to remove it at this point.

**Comment by krOoze** [comment]
Hm, does that mean the above snippet is valid then?

>  Since we don't have stage/access masks for layout transitions (or synchronization commands in general), we ended up with this guarantee.

We sorta do have sync commands. We know the layout transition is done before `dstStageMask`.

We do not need any access masks, because spec also says this:

> Available memory is automatically made visible to a layout transition, and writes performed by a layout transition are automatically made available.

Besides the quote in the op says "implicit **execution** dependency", so formalistically speaking it does not even cover memory dependency.

**Comment by Tobski** [comment]
> Hm, does that mean the above snippet is valid then?

Shockingly, yes.

> The problem to me here seems the language above not just plugs the spec hole, but allows user to do way more.

100% agreed, but it's in the spec, and AFAIK relied upon by some developers. Not sure what we can do about that now.

> We sorta do have sync commands. We know the layout transition is done before dstStageMask. That tells me all I need to know. It will work well with Semaphores and Fences.

I meant specifically that there's no "VK_PIPELINE_STAGE_SYNC_COMMAND". If you don't have this ordering guarantee, then you need the dstStageMask in the earlier command buffer to match the srcStageMask in the later command buffer, which however you slice it will lead to a pipeline bubble (stall) on the GPU. With this ordering guarantee that's not strictly necessary (although potentially still happens).

I mean at the end of the day, I don't think this was a particularly well thought through feature, but it's there and we have to live with it. Anyone relying on it should probably not be, so maybe there's an argument for firing a warning in the best practices layer?

**Comment by krOoze** [comment]
Yea, perhaps performance warning because overlapping layout transitions probably trigger some unknown sync barrier.

Though there is also the matter of drivers having to track this no matter what. Which is against the fundamental tenets of Vulkan. And I am not even sure if CTS covers this properly to be reliable.
Maybe worth asking around with the drivers. It would potentially be pretty simple extension, only adding a feature flag that would remove this paragraph (and disable any tracking the driver has to do to satisfy this).

As for pipeline stage, I think it is generally a problem with dependency chaining. I think it would be nice if there were added few pseudo-stages just for chaining. It is a common question why `pWaitDstStageMasks` should be `X_STAGE`, when there is Subpass with `srcStageMask = dstStageMask = X_STAGE` (which on top of the desired dependency chain also still collateraly blocks anything executing an `X_STAGE`). It would be nice to have a stage that says "I want to chain these two specific sync primitives together, but block nothing else if possible". I guess `VkEvents` were meant to do that, but they are bit of a failed concept IMO (and it would not work with the `pWaitDstStageMasks` anyway).

**Comment by krOoze** [comment]
> > Hm, does that mean the above snippet is valid then?
>
> Shockingly, yes.

Given that I think I am gonna go ahead close this.
