### ISSUE TITLE
Non-dispatchable handle uniqueness with VK_EXT_private_data unclear

### ISSUE THREAD

**Issue by DadSchoorse** [KhronosGroup/Vulkan-Docs#1349]
Non-dispatchable object handles are not guaranteed to be unique by the spec:
> Non-dispatchable handle types are a 64-bit integer type whose meaning is implementation-dependent, and may encode object information directly in the handle rather than acting as a reference to an underlying object. Objects of a non-dispatchable type may not have unique handle values within a type or across types.

Here is unclear how `VK_EXT_private_data` would behave in a case where two handles with the same type, from the same device are the identical. Are those handles the same, so is there only one private `uint64_t` per data slot for both of them? Alternatively, does activating `VK_EXT_private_data` guarantee unique handles within a type and device?

**Comment by jeffbolznv** [comment]
> Alternatively, does activating VK_EXT_private_data guarantee unique handles within a type and device?

We had discussed this during the extension's development and it was supposed to be this, but I'm not seeing the spec language for it. @tobski or @mattruschnv do you recall what happened to it?

**Comment by Tobski** [comment]
Doesn't look like we ever updated that section after discussing it - I'll raise an internal MR to fix this and guarantee uniqueness when the extension is enabled.

**Comment by oddhack** [comment]
This should be addressed in the 1.2.159 spec update.
