### ISSUE TITLE
"lifetime of the Vulkan command"

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#135]
Reported in #33 but not fixed in 1.0.6:

https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#memory-host says:

> VK_SYSTEM_ALLOCATION_SCOPE_COMMAND - The allocation is scoped to the lifetime of the Vulkan command.

I don't think the "lifetime" of a command is a defined or meaningful concept, since they're not created or allocated. This should probably say "duration of the Vulkan command" instead (which is also the phrase used a few paragraphs later).

**Comment by oddhack** [comment]
This should be dealt with in the 1.0.8 spec update.
