### ISSUE TITLE
Notice of upcoming default branch renaming to 'main' by August 30, 2020

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Docs#1351]
The Khronos Vulkan Working Group has decided to rename the default branch for the Vulkan-Docs repository from 'master' to 'main'. This is expected to occur over the weekend of August 29-30, 2020, assuming no unanticipated issues come up. This issue exists to help notify downstream consumers of Vulkan-Docs that starting with the first specification update after August 30, 2020, they should pull from 'main' branch to get the current repository contents; and to notify people proposing Pull Requests against the repository that their PRs should target 'main' branch.

If you are in one of these groups and see a significant technical or process issue with this timeline, please comment here as soon as possible, and we will attempt to accommodate your concern. The timing could possibly be pushed later than August 30 depending on the feedback received.

We expect that 'master' branch will continue to exist after August 30 but will not be further updated. 

Over the weekend of August 29-30, we expect to:

* Branch 'master' to 'main' and make 'main' the new repository default branch.
* Retarget existing PRs to 'main'. This should not require any action on the part of owners of open PRs.

Shortly after this date, the next spec update will occur in 'main'.

While we are open to technical and process concerns, the branch renaming decision has been made and we do not anticipate revisiting it.

**Comment by etisdew** [comment]
Would it be possible to request that this change be referenced in the master/readme to avoid probable confusion?

**Comment by oddhack** [comment]
> Would it be possible to request that this change be referenced in the master/readme to avoid probable confusion?

Yes, we'll do that. There is some consideration being given to intentionally breaking the build in master in the final commit, as an unambiguous forcing function to migrate, but there are both pros and cons to doing that and we haven't decided.

**Comment by expipiplus1** [comment]
> There is some consideration being given to intentionally breaking the build in master in the final commit

At the least building with `master` could spit a warning notifying the user that an obsolete branch is being built.

**Comment by oddhack** [comment]
> At the least building with `master` could spit a warning notifying the user that an obsolete branch is being built.

That sounds useful. I suspect, but don't know, that the majority of downstream consumers are after just the XML and perhaps scripts. It's less obvious what to do about that since we have no visibility into how people are consuming it - I know some parse the XML directly.

**Comment by expipiplus1** [comment]
> I know some parse the XML directly.

Oh, that's me :)

What are the downsides of just breaking `master? I'm sure anyone pulling master hoping to get the latest changes would rather have things break loudly than silently fall behind.

Kudos for making this change too.

**Comment by oddhack** [comment]
> What are the downsides of just breaking `master?

We don't know what the downsides would be because we can only ask the downstreams whose existence we are aware of. Hopefully you are correct that everyone would prefer brokenness to silent stagnation, but we want to do this in the way that minimizes impact on downstreams. There's also a question of how to break it - we could simple delete the branch or empty it out, but consider what happens to someone who is auto-merging content from master into their repository - that seems unfriendly.

There is apparently a way of configuring repository metadata to, in effect, alias two branches, but we're not brave enough to want to play with that in a production repository.

**Comment by krOoze** [comment]
I just want to say that I hope you know what you are doing with this and the politically motivated changes in previous patches. Frivolous politically-motivated changes are unprofessional and put in doubt the trustworthiness, values, and independence of the Khronos Group.

It is appropriation of English language that belongs to all of us (not just rich bored white men that push this change), and is one of our most sacred possesions. It is threatening to opponents of oppresive regimes, the regimes that do use this tactic of messing with our language. And it is disrespectful to past and future authors that used\\will continue to use the proper, perfectly innocent, and conventional words, from now on painting them as racists or worse and making them open to bullying, lynching, and workplace or employment discrimination.

<hr>

I understand the lure to be silently complicit to this, or even post-hoc deceive ourselves that we are doing some good here. Unfortunatelly that is no longer possible if one bothers to look what this is actually about. Allow me to lay it out for you:

The destruction of words like "master" (especially wrt git) can be tracked to a [IETF draft](https://tools.ietf.org/html/draft-knodel-terminology-02). The authors are:
- Mallory Knodel, white lady, CTO of Center for Democracy & Technology, BA of physics and math and MA of science education
- Niels ten Oever, white man, researcher of media and politology, MA in philosophy.

The CDT seems to be the organization behind the push. It is some political organization, its [finances](https://cdt.org/financials/) can be tracked to any of your favorite ecorp. It has [predominantly white staff](https://cdt.org/staff/). The board of the organization consists of seven white men, two white women, one black woman, one black man. Those are the people and corporations we let decide for ourselves.

Secondly, we need to apply the Golden Rule to see how silly and dangerous the usual proxy faux-beneficial reasons are. Say, we have long history of feudalism in Europe. Imagine the Chinese deciding for us and in our name that words like "king" and "subject" should be destroyed in all their uses. I, for one, say it would make me angry, powerless, robbed, and it would feel like everyone secretly looks at me like I am idiot for hating those words for no reason (even if it is not a change that I wanted and it was done in my name without my consent).

Finally, this might be a last good chance to say "no". I even volunteer to revert the changes thus far, and write you a guidline against politics in contributions if you wish, as to make it effortless for you.
It will be harder to say "no" once you go on this path. By accepting this change you disenfranchise rational people, and tell them to just stay silent and hop on the clown bandwagon. And you are accepting the whims of large political organizations and their mind-slaves. I guess, that's classic \#2020 :/

Do not kid yourselves; the encroachment of totalitarian politics into software development will continue. [Newspeak Dictionaries](https://source.android.com/setup/contribute/respectful-code) are being enthusiastically produced by the oligarchy. And next wave of words to destroy is already being planned. These include "robot", "native\\foreign", anything including "man", you need to refer to "user" as "they", "abort"\\"kill"\\"destroy"\\"terminate", "argument", "turn on"\\"turn off", etc...

<hr>

I do not hold much hope, but it has been bothering me and making me depressed to see this malignant nonsense even here.
I guess... Everybody knows the fight was fixed. The poor stay poor, the rich get rich. Everybody knows the deal is rotten; ol' black Joe's still pickin' cotton.  :musical_note:
But at least we have shiny new fake words like "denylist". That is, at least untill we find out that "denial" is negative and discriminatory.

**Comment by MichaelMitchellM** [comment]
@krOoze Lmao dude, imagine caring this much about a single word substitution. Language and its use evolves, get over it.

**Comment by krOoze** [comment]
- This is not about a single word. It is about five, one of which is frivolous breaking change. And it is about any planned in the future.
- This is not evolution. "lol" or "woot" is evolution. The language did not change one bit from yesterday. This is manufactured. Besides conventions do not change this way. This is not language evolution. It is [political renaming](https://en.wikipedia.org/wiki/List_of_politically_motivated_renamings).
- If you claim to be for **real** inclusivenes, you cannot be lmaoing, duding, and getting over people. That only shows you are intellectualy dishonest.

**Comment by Wunkolo** [comment]
@krOoze really went and linked this github issue on /r/vulkan to try and militarize people against a literal `Ctrl+h` only to find out that most people don't mind it or don't care and don't give into your "sjw conspiracy" and downvoted it to hell.

Someone is changing a github branch name.
Get over it, or "boycott/fork vulkan because they are an sjw graphics API that renamed a branch" like the rest of the people that agree with you.

**Comment by cdefgah** [comment]
Just wondering, will MasterCard reconsider its trademark according to the same reasons?

**Comment by enkore** [comment]
"master" as the default branch name in git was always a poor choice (because it doesn't make much sense) and I'll take any excuse I can get to replace it with something more meaningful in as many projects as possible.

**Comment by bakugo** [comment]
@Wunkolo There's a certain kind of irony in saying "get over it" while also being so triggered by a branch name that you feel the need to change it.

**Comment by Vaporeon** [comment]
I am sick of being told to "get over it" and "who cares". Honestly I would not care either if not for the reason behind this change. There is an obvious push to brand the words "Master" and "Slave" as racist. Neither of these words are inherently linked to a persons race. People of all races have been enslaved throughout history, and slavery is not solely related to the history of the United States cotton industry. The word "Master" on its own also has many meanings outside slavery that are also much nicer, such as having "mastered" a skill.

I reject the notion that the fact language evolves over time is justification for the sudden redefinition of commonly used words.
Sudden redefinition like this is potentially dangerous (as in this case) because older works and writings will now be taken out of context and read under the new definition. I sure as hell was not thinking of human race differences when initializing git repositories, yet people of the future could be left wondering why they contain the now hateful word "master".

**Comment by etisdew** [comment]
2020: 
US Policy ...Actual legally sactioned slavery via the prison system perpetuating a for profit industry of arrest, representation, and sentence.Github repo: ..That git branch is putting off some racist vibes.
main is a fairly standard name, why not reach out to git and seek an update in their next major versions? Its not really the best example of a master/slave relationship in the first place. Typically branches will represent clones, and perhaps atypically sub packages to a solution.

This message will self-destruct.

**Comment by Wunkolo** [comment]
[Khronos' repositories on github inherit the github ecosystem and github is changing defaults from `master` to `main` in October so they may be following suite to make PRs and such easier with all newly created repos moving forward in anticipation of `main` repos outnumbering `master` repos on github as time goes on](https://github.com/github/renaming). [Git introduced the option to change the default branch name to accommodate people that rename their default branch and provide other accessibility to reduce any technical strain in having a renamed default branch](https://github.blog/2020-07-27-highlights-from-git-2-28/#introducing-init-defaultbranch) stating:

> `main` is the most popular replacement for `master` that we’re seeing across GitHub. We like it because it’s short, it keeps your muscle memory intact, and it translates well across most languages.

So far there has been _zero_ or _little_ technical strain stated here or on the Reddit threads and just strain that "please keep it `master` so the SJWs don't win"-people are experiencing for whatever reason. [I'm not seeing any technical strain in the process of porting existing repos](https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx), and new repos moving forward in October likely won't see any strain either.

A git branch name is being changed. You are losing nothing but are putting in the most energy being offended by it and pretending like you're losing everything.

> While we are open to _technical_ and _process_ concerns, **the branch renaming decision _has been made_** and **_we do not anticipate revisiting it._**

Again, deal with it. It's happening.

**Comment by krOoze** [comment]
If we are to be honest and self-consistent about it, we need to destroy all words as remotely related to slavery as "master" is: robot\bot, service, worker, labor, private property, subject, bondage\binding, dependent\dependency, branding, inferior\superior, supervisor\boss\driver, ...

Or cathegorically say "no".

**Comment by bakugo** [comment]
>You are losing nothing but are putting in the most energy being offended by it


I legitimately cannot handle this level of irony. It should be illegal to be this hypocritical.

**Comment by oddhack** [comment]
This issue will now be locked. The decision has been made, the useful feedback has been incorporated, and we are proceeding. In future comments on Khronos repositories, everyone is reminded to refer to the Khronos code of conduct at https://www.khronos.org/events/code-of-conduct for acceptable behavior.

**Comment by oddhack** [comment]
This change has been completed as described in the issue. The default branch is now 'main' and open PRs have been retargeted to that branch. Per @etisdew the README in the old 'master' branch has been changed to describe the current state of that branch. We might still do something to disable the build from 'master', but we're still unsure if that would be more help or more harm.
