### ISSUE TITLE
Required feature for vkCmdDrawIndexedIndirectCount and vkCmdDrawIndexedIndirect wrong

### ISSUE THREAD

**Issue by wickedmic** [KhronosGroup/Vulkan-Docs#1352]
When looking at the documentation of the [drawIndirectCount ](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#features-drawIndirectCount)feature it says:

> drawIndirectCount indicates whether the implementation supports the vkCmdDrawIndirectCount and vkCmdDrawIndexedIndirectCount functions. If this feature is not enabled, these functions must not be used.

But the documentation of [vkCmdDrawIndexedIndirectCount ](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdDrawIndexedIndirectCount.html)does not mention this requirement. Instead, when you look at the documentation of [vkCmdDrawIndexedIndirect ](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdDrawIndexedIndirect.html#VUID-vkCmdDrawIndexedIndirect-None-02837)it says:

> If drawIndirectCount is not enabled this function must not be used

Which seems not to be correct, since the feature description does not mention this function to be affected.

**Comment by sfricke-samsung** [comment]
This was fixed in 1.2.152 by putting in the common validity pages, thanks again @wickedmic for pointing this out
