### ISSUE TITLE
Add a way to identify the DRM node of a physical device 

### ISSUE THREAD

**Issue by emersion** [KhronosGroup/Vulkan-Docs#1354]
One of the few missing specs to write a Vulkan Wayland compositor is a way to map Vulkan physical devices and DRM nodes. The best that can be done right now is using PCI IDs ([example](https://github.com/nyorain/kms-vulkan/blob/e66655b05ebc6281c1ebffec12681240caf305be/vulkan.c#L255)). However some GPUs aren't PCI (e.g. platform devices).

It would be nice to be able to get a reliable way to do the mapping. See https://gitlab.freedesktop.org/wayland/wayland-protocols/issues/10 for a list of ways to refer to DRM devices.

**Comment by cubanismo** [comment]
Agreed, this would be useful, and frankly I think we just hadn't got around to it yet.  Would you mind writing up a patch to add the necessary structures?

We discussed a bit at Khronos and it sounds like we're in agreement that exposing a minor number for both the primary and render node would be a good solution.  We also noted the API may need to accommodate Vulkan devices which do not have one or both types of DRM device nodes, as there may be, for example, SW rendering engines exposed as Vulkan devices, and devices without display subsystems that do not wish to expose control or primary nodes.

**Comment by emersion** [comment]
Submitted a draft: https://github.com/KhronosGroup/Vulkan-Docs/pull/1356
