### ISSUE TITLE
VkMemoryPropertyFlags value 0 not explained in the documentation

### ISSUE THREAD

**Issue by Karlovsky120** [KhronosGroup/Vulkan-Docs#1355]
I've looked at the page for `VkPhysicalDeviceMemoryProperties`, `VkMemoryType` and `VkMemoryPropertyFlagBits`.

The page for `VkPhysicalDeviceMemoryProperties` claims that value of 0 for `VkMemoryPropertyFlagBits` is a valid value, but does not explain what this value actually means.

Value of 0 for these flags is not mentioned on any of the other two pages as well.

This should be explained, especially since (at the very least some) Nvidia Turing GPUs running on latest beta drivers at the time of writing (451.98) are exposing their first memory type in the array with flags being set to 0.

**Comment by krOoze** [comment]
Value of `0` means none of the flags bits. The memory type has none of the capabilities defined by any of the flag bits.
There is really nothing to explain. It is consistent with how flags generally work.

**Comment by Karlovsky120** [comment]
But what kind of memory is it then? What is it's purpose? Is it a part of the device or a part of the host? How do I use such memory type when I rely on host visible and device local flags when allocating any memory?

**Comment by krOoze** [comment]
You know what kind of memory the `VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT` is? `0` is the same memory type, minus the `VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT` flag. It does exactly the same things, minus being "most efficient for device access".

**Comment by Karlovsky120** [comment]
I still have trouble understanding how this works then. Allocating a buffer, I was told by the requirements I need either memory 0 or memory 1 (`memoryTypeBits` being set to 3). I want to write to this buffer from the CPU, so I need to make sure that the memory is host visible, which I tried doing by checking for appropriate flag, which failed since the flags are 0.

How do I ensure that I'm using memory that I can write to from the CPU? Do I really need to check which heap it is from and then look for the other memory types in the heap and see if any of them are host visible? Would that logic even hold?

Heaps also have flags, but they only advertise device local bit there, which may or may not be host visible, so I have no guarantees there.

Sure, that buffer will do buffery things, but how do I know if I can access it from the host?

**Comment by krOoze** [comment]
Unless the buffer is created with `VK_BUFFER_CREATE_SPARSE_BINDING_BIT`, then host-visible memory type is guaranteed.
You either made a mistake, or the driver is non-conformant.

**Comment by Karlovsky120** [comment]
So, if I were to create a buffer without that flag, the host visible type will be guaranteed if the flag is 0, but will the depend on flags if the flag isn't 0?

**Comment by krOoze** [comment]
If it is without `VK_BUFFER_CREATE_SPARSE_BINDING_BIT`, then you will get a host-visible memory typo offered in the memory requirements.

It is [below `VkMemoryRequirements`](http://vulkan.hys.cz/1.2-extensions/vkspec.html#VkMemoryRequirements):

> If `buffer` is a `VkBuffer` not created with the `VK_BUFFER_CREATE_SPARSE_BINDING_BIT` bit set, or if `image` is _linear image_, then the `memoryTypeBits` member always contains at least one bit set corresponding to a `VkMemoryType` with a `propertyFlags` that has both the `VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT` bit and the `VK_MEMORY_PROPERTY_HOST_COHERENT_BIT` bit set. In other words, mappable coherent memory **can** always be attached to these objects.

BTW, I would assume the same for `PROTECTED` buffer. At the minimum you cannot bind non-protected memory to protected buffer, so the driver would have no reason to advertise non-protected memory despite the above quote.

**Comment by Karlovsky120** [comment]
Oh now it makes sense, it must be then that the nvidia beta driver is not conforming to the spec. Only two memory types offered to me when allocating the most basic of buffers are:
memory 0 with flags 0
memory 1 with flags VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT

Since memory 0 is from heap 1 which seems to be system memory, it should have host visible and coherent bits set, at the very least. Feel free to close the issue then, I'll go and file a bug with nvidia.

Since I j

**Comment by Karlovsky120** [comment]
Okay, an update.
As I was writing the example to file a bug report, I realized I was requesting memory properties for a wrong object, once I rectified that, memory type bits were set to 31, so all 5 memory types were available, one of them being host visible and coherent.

I had a feeling this was too big to be a bug.
Specification is fine and the driver is conforming to spec.

**Comment by krOoze** [comment]
Yes, driver bug seems unlikely as this would immediatelly break every but the most basic apps.

**Comment by jeffbolznv** [comment]
It is something you can use as a fallback if you run out of device-local memory and don't need host access to the memory.

**Comment by krOoze** [comment]
If you really understand what the lack of flags mean, then you understand the usage.

You can map a memory only if the memory is `VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT`. `0` means lack of all flag bits, including the lack of `VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT`.

`VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT` is specified as "most efficient for device access". `0` is also lack of that bit.

`0` type memory can do everything a `VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT` type can do, except being "most efficient for device access".

**Comment by Karlovsky120** [comment]
Ah, the last sentence cleared it up for me, thank you, I understand now.
