### ISSUE TITLE
multiple overlapping per-stream transform feedback queries

### ISSUE THREAD

**Issue by brianpaul** [KhronosGroup/Vulkan-Docs#1357]
The spec for VkCmdBeginQueryIndexedEXT() under "Valid Usage" says "queryPool must have been created with a queryType that differs from that of any queries that are active within commandBuffer".

That seems to indicate that one cannot have two or more simultaneous VK_QUERY_TYPE_TRANSFORM_FEEDBACK_STREAM_EXT queries, one per vertex stream.  The Vulkan validation layer seems to disallow this as well.

This is allowed with OpenGL. See Issue #4 of the GL_ARB_transform_feedback3 spec at 
https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_transform_feedback3.txt

The utility of transform feedback queries seems limited if one can't set up simultaneous per-stream queries.

Was this an oversight in the spec?

**Comment by pdaniell-nv** [comment]
Yes, I think this was an oversight in the Vulkan spec. You should be able to have more than one active VK_QUERY_TYPE_TRANSFORM_FEEDBACK_STREAM_EXT as long as they all use different streams.

**Comment by pdaniell-nv** [comment]
Internal fix for this is here: https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/4126

**Comment by oddhack** [comment]
This should be fixed in the 1.2.173 spec update.
