### ISSUE TITLE
Incorrect link in VkRenderPassCreateInfo2

### ISSUE THREAD

**Issue by MulattoKid** [KhronosGroup/Vulkan-Docs#1358]
In its explanation, the `pDependencies` member of the VkRenderPassCreateInfo2 is linked to VkSubpassDependency instead of VkSubpassDependency2.

https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkRenderPassCreateInfo2.html

**Comment by sfricke-samsung** [comment]
Can make quick patch, thanks for pointing this out!

**Comment by oddhack** [comment]
This should be fixed in the 1.2.153 spec update.
