### ISSUE TITLE
Description of VK_COMMAND_POOL_RESET_RELEASE_RESOURCES_BIT seems to be inaccurate

### ISSUE THREAD

**Issue by Karlovsky120** [KhronosGroup/Vulkan-Docs#1359]
The vulkan spec [here](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkCommandPoolResetFlagBits.html) says:

`VK_COMMAND_POOL_RESET_RELEASE_RESOURCES_BIT specifies that resetting a command pool recycles all of the resources from the command pool back to the system.`

This implies that by resetting a command pool with this flag releases all of command buffers allocated from that pool along with any memory they used (at least that's what I consider to be "all of the resources from the command pool"). I'm guessing that attempting to do this while any buffers from the command pool are still in use would be invalid and would produce a validation error.

However, resetting a command pool with this flag without previously freeing the command buffers allocated from that pool introduces a memory leak to the program.

What is the purpose of this flag? Is this the intended behavior?

**Comment by jeffbolznv** [comment]
The spec for vkResetCommandPool says:

```
Resetting a command pool recycles all of the resources from all of the
command buffers allocated from the command pool back to the command pool.
All command buffers that have been allocated from the command pool are put
in the <<commandbuffers-lifecycle, initial state>>.
```

So the command buffers stay around, but the memory they had taken from the pool are recycled back to the pool (and back to the system if this flag is set).

If you're seeing a memory leak on some implementation, that would probably be a driver bug.

**Comment by Karlovsky120** [comment]
If I'm resetting a pool, allocating a buffer from it, recording to it, using it and then doing it all again, 1500 times a second, I suspect all those buffers and their handles will take up more and more space since I'm not freeing them, right? If so, it's probably not a driver bug.

I'll create a PR to clarify the flag a bit, using the info you provided.

**Comment by jeffbolznv** [comment]
If you keep allocating new command buffers, then yes that'll take more space. But you can reuse the command buffers that were already allocated. So if you're allocating new ones but not reusing or freeing the old ones, then it's really the app that is leaking.

**Comment by Karlovsky120** [comment]
Yeah, I figured that, I just wanted to clarify that I was the problem, not the driver. I'll rewrite the program so that the old buffers are just reused instead of freed and reallocated.

**Comment by tuket** [comment]
Can you please let me know if I'm understanding this correctly?

- Call vkResetCommandPool without any flags: the command buffers can still be used they are in the "initial" state.
- Call vkResetCommandPool with VK_COMMAND_POOL_RESET_RELEASE_RESOURCES_BIT: the command buffers can't be used anymore. I don't see this mentioned in the docs, but I guess they are put in the "invalid" state?
