### ISSUE TITLE
Cases where pfnAllocation may be called for command scope

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#136]
Reported in #33 but not fixed in 1.0.6:

https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#memory-host says:

> pfnAllocation or pfnReallocation may be called in the following situations:

That looks like it's trying to be an exhaustive list, but it doesn't list any cases where host memory scoped to the lifetime/duration of a Vulkan command may be allocated.

It should probably say "Host memory scoped to the duration of a command may be allocated from any API command".

**Comment by oddhack** [comment]
Should be fixed in the 1.0.9 spec update.
