### ISSUE TITLE
Clarify linear sampling misbehavior

### ISSUE THREAD

**Issue by kvark** [KhronosGroup/Vulkan-Docs#1362]
We are working on WebGPU on top of Vulkan, and we are trying to figure out what happens if a linearly sampled image doesn't happen to have the format with `SAMPLED_IMAGE_FILTER_LINEAR` feature bit.

The validation rule simply states that this would be invalid, and hence implies the undefined behavior.
> VUID-vkCmdDraw-None-02690
If a VkImageView is sampled with VK_FILTER_LINEAR as a result of this command, then the image view’s format features must contain VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT 

The problem is that Vulkan has pretty low guarantees on which formats are linearly sample-able. For example, `R32_SFLOAT` isn't guaranteed to have it! I don't believe any other graphics API would really have undefined behavior on linear sampling of `R32_SFLOAT`. The hardware will probably still do something meaningful, won't it?

Would it be possible to fix the specification in a way that turns this UB into some sort of an undefined result instead? I'm thinking about a similar wording that you have for linear depth sampling:
> If this bit is not present, linear filtering with depth compare disabled is unsupported and linear filtering with depth compare enabled is supported, but may compute the filtered value in an implementation-dependent manner which differs from the normal rules of linear filtering.

Btw, isn't this excerpt from the spec contradicting the valid usage rule? The VU says you can't linearly sample, but the text says you can, but you may get some implementation-dependent behavior...

**Comment by oddhack** [comment]
We closed the corresponding internal issue with your agreement, on grounds that DX also couldn't be relied upon for WebGPU, so also closing this.
