### ISSUE TITLE
VkPerformanceCounterDescriptionFlagBitsKHR value names are missing the _BIT part

### ISSUE THREAD

**Issue by jacereda** [KhronosGroup/Vulkan-Docs#1367]
I guess the correct names would be `VK_PERFORMANCE_COUNTER_DESCRIPTION_PERFORMANCE_IMPACTING_BIT_KHR` and `VK_PERFORMANCE_COUNTER_DESCRIPTION_CONCURRENTLY_IMPACTED_BIT_KHR`

**Comment by sfricke-samsung** [comment]
Will raise up internally, thanks for spotting

**Comment by oddhack** [comment]
This should be addressed in the 1.2.159 spec update.
