### ISSUE TITLE
VkSurfaceCounterFlagBitsEXT value name is missing the _BIT part

### ISSUE THREAD

**Issue by jacereda** [KhronosGroup/Vulkan-Docs#1368]
Correct name should probably be `VK_SURFACE_COUNTER_VBLANK_BIT_EXT`

**Comment by sfricke-samsung** [comment]
@jacereda sorry for the delay, but I agree, will raise up internally to fix with an alias

**Comment by oddhack** [comment]
This should be addressed in the 1.2.159 spec update.
