### ISSUE TITLE
Maximum mipLevels for 1D/2D images

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#137]
Reported in #33 but not fixed in 1.0.6:

https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#resources-images says:

> mipLevels must be less than or equal to ⌊log2(max(extent.width,extent.height,extent.depth))⌋+1

That means I can make an image with imageType = VK_IMAGE_TYPE_2D, extent = { 256, 256, 2^31 }, and mipLevels = 32, which seems silly.

I think either it should require extent.depth = 1 for 2D/1D and extent.height = 1 for 1D; or it should ignore the unused dimensions for the limit of mipLevels.

**Comment by oddhack** [comment]
This should be dealt with in the 1.0.8 spec update.
