### ISSUE TITLE
Memory type requirements for depth-stencil images

### ISSUE THREAD

**Issue by konstantinegorov** [KhronosGroup/Vulkan-Docs#1370]
The specification states:

> For images created with a depth/stencil format, the memoryTypeBits member is identical for all VkImage objects created with the same combination of values for the format member, the tiling member, the VK_IMAGE_CREATE_SPARSE_BINDING_BIT bit of the flags member, the VK_IMAGE_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT bit of the flags member, handleTypes member of VkExternalMemoryImageCreateInfo, and the VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT of the usage member in the VkImageCreateInfo structure passed to vkCreateImage.

"same combination of values for the format member": what does it mean?

**Comment by sfricke-samsung** [comment]
@konstantinegorov sorry for the delay on this, but the `format member` is referring to "member" (or "field") in the struct of `VkImageCreateInfo::format`

This paragraph is explaining if you keep the various members of  `VkImageCreateInfo` the same you will get the same `memoryTypeBits` when you call `vkGetImageMemoryRequirements` later

**Comment by konstantinegorov** [comment]
Thanks.

**Comment by sfricke-samsung** [comment]
Closing unless you have further questions
