### ISSUE TITLE
pSetLayouts must keep order

### ISSUE THREAD

**Issue by lance-loong** [KhronosGroup/Vulkan-Docs#1372]
In the development and use, I encountered a trap of multiple sets. When creating "pipelinelayout," vkpipelinelayoutcreateinfo:: psetlayouts "must keep the order with" set "in" shader ", and I can't skip the empty" set ". I read many documents and can't find the answer, which once made me confused. Should I declare this in the document?

```
layout (set = 0, binding = 0, std140) uniform Bt1 { int a; } bt1;
layout (set = 2, binding = 0, std140) uniform Bt1 { int a; } bt2;
layout (set = 4, binding = 0, std140) uniform Bt1 { int a; } bt3;

VkDescriptorSetLayoutBinding aryLayoutBinding[3];
....

VkDescriptorSetLayout aryDescriptorSetLayoutVk[3];
for( uint8_t i = 0; i < 3; ++i )
{
	VkDescriptorSetLayoutCreateInfo sLayoutSamplerInfo = {};
	sLayoutSamplerInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
	sLayoutSamplerInfo.bindingCount = 1;
	sLayoutSamplerInfo.pBindings = &( aryLayoutBinding[i] );
	VK_CHECK( vkCreateDescriptorSetLayout( DeviceVk, &sLayoutSamplerInfo, s_AllocCall, &( aryDescriptorSetLayoutVk[i )) );
}

VkPipelineLayoutCreateInfo sPipelineLayoutInfo = {};
sPipelineLayoutInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
sPipelineLayoutInfo.setLayoutCount = 3;
sPipelineLayoutInfo.pSetLayouts = aryDescriptorSetLayoutVk;
sPipelineLayoutInfo.pushConstantRangeCount = 0;
sPipelineLayoutInfo.pPushConstantRanges = nullptr;
vkCreatePipelineLayout( m_LogicalDevice, &sPipelineLayoutInfo, nullptr, &PipelineLayoutVk );
```

This leads to the error "shader uses descriptor slot 4.1 (expected '...') but not declared in pipeline layout",It will be very difficult to locate specific problems.

**Comment by sfricke-samsung** [comment]
If you think about that fact you case the implementation compiler essentially view the sets as an array which is will grab index `[0,2, 4]` for this particular shader, it makes sense that the pipeline layout expects the sets, even if not being used

I guess 

1. Why is the shader not just using set `[0, 1, 2]` to start with
2. You will need add "some" `VkDescriptorSetLayout` to the pipeline layout creation, if your shader uses set `[0, 2, 4]` it implies another shader is using the `1` and `3` index and so your pipeline layout should have those sets prepared

**Comment by lance-loong** [comment]
I'm making a multi platform API. I set different set numbers for different shaders, which will not be sequential numbers

**Comment by jeffbolznv** [comment]
In this case, the pipeline layout should be created with 5 descriptor set layouts, and the layouts for sets 1 and 3 can be empty (no bindings).

**Comment by lance-loong** [comment]
you are right,thank you answer.
