### ISSUE TITLE
Possibly missing type tags in the require of "VK_EXT_device_memory_report" extension?

### ISSUE THREAD

**Issue by Friz64** [KhronosGroup/Vulkan-Docs#1374]
I am specifically talking about these three types

- `VkDeviceMemoryReportFlagsEXT`
- `VkDeviceMemoryReportEventTypeEXT`
- `PFN_vkDeviceMemoryReportCallbackEXT`

It looks like they were added by the extension but not included as a `type` of the extension here?
![image](https://user-images.githubusercontent.com/20155479/95107363-1c58a080-073a-11eb-8a82-136c281cb2b4.png)

The extension is defined on line `13625` as of cee0f4b12acde766e64d0d038b03458c74bb67f1.

Sorry if i am missing something.

**Comment by r-potter** [comment]
Thanks. That does appear to be an oversight. I'll file an internal MR and ping the extension author.

**Comment by oddhack** [comment]
This should be fixed in the 1.2.157 spec update.
