### ISSUE TITLE
Depth/Stencil input attachment question

### ISSUE THREAD

**Issue by konstantinegorov** [KhronosGroup/Vulkan-Docs#1375]
How to use both depth input attachment and stencil input attachment simultaneously in same subpass?

**Comment by sfricke-samsung** [comment]
@konstantinegorov So this is possible to do in Vulkan, but this also lacks information about if you a single attachment with depth/stencil format or two attachments with a depth-only and stencil-only format. With that, you should be able to pass in all the attachments you want in `VkSubpassDescription::pInputAttachments` as you can have more than 1. 
Also, there is a `VK_KHR_separate_depth_stencil_layouts` extension, which might be what you are looking for, not sure.

With that, discussed in the Working Group meeting today, and this is not a Vulkan Spec issue, but rather a programming question so we will have to close this. Please look for external resources such as StackOverflow, [Khronos Forumn](https://community.khronos.org/c/vulkan/24), [Khronos Slack](https://www.khronos.org/news/permalink/khronos-developer-slack-5bfc62eb261764.20435008), etc.
