### ISSUE TITLE
OpImageSampleImplicitLod/OpImageSampleDrefImplicitLod with MS

### ISSUE THREAD

**Issue by Retrofractal** [KhronosGroup/Vulkan-Docs#1377]
Is it intended that the SPIR-V instructions `OpImageSampleImplicitLod` and `OpImageSampleDrefImplicitLod` support an `MS` operand of 1? I note that all remaining sampling instructions appear to prevent multisampling with restrictions in the instruction description (`OpImageSampleProjImplicitLod`, `OpImageSampleProjExplicitLod`, `OpImageSampleProjDrefImplicitLod`, `OpImageSampleProjDrefExplicitLod`) and/or the optional image operands (`OpImageSampleExplicitLod`, `OpImageSampleDrefExplicitLod`, `OpImageSampleProjExplicitLod`, `OpImageSampleProjDrefExplicitLod`).

OpenGL:
> No standard sampling instructions are allowed on the multisample texture targets, and no filtering is performed by the fetch.

DirectX also indicates that sampling instructions are not supported with multisample resources (https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#7.17%20Texture%20Load)

**Comment by gnl21** [comment]
No, it is not intended. A clarification was recently made to the SPIR-V spec and it should be included in the next published version.

**Comment by Retrofractal** [comment]
Great, thank you.

**Comment by gnl21** [comment]
This spec update is public now. For example, `OpImageSampleImplicitLod` now says:
> Sampled Image must be an object whose type is OpTypeSampledImage. The MS operand of the underlying OpTypeImage must be 0.

I think this issue is resolved now, but please reopen if you think something more is needed.
