### ISSUE TITLE
Description of VkAttachmentReference2 contradicts the Valid Usage of aspectMask

### ISSUE THREAD

**Issue by luckyxxl** [KhronosGroup/Vulkan-Docs#1378]
Please see https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VkAttachmentReference2

The descriptive text below `typedef struct VkAttachmentReference2` states that `aspectMask is ignored when this structure is used to describe anything other than an input attachment reference`.

The `Valid Usage` section contains mostly statements that restrict valid values for `layout` based on bits set in `aspectMask`, but without a restriction that this applies to input attachment references only.

The validation layers of Vulkan SDK 1.2.154 report an error if `aspectMask` is not valid according to the `Valid Usage` section for an attachment reference that is not a input attachment reference.

I'm not sure how tight the `Valid Usage` sections are supposed to be defined, so I'm not sure whether this is an error in the spec or in the validation layer.

**Comment by luckyxxl** [comment]
On second though the third option is that neither is erroneous, but then I think that the line `aspectMask is ignored when this structure is used to describe anything other than an input attachment reference` could just be removed to prevent further confusion, no?

**Comment by sfricke-samsung** [comment]
So agree this isn't fully correct. The validation layers are following the VUs as they are written and so if there is a change it should be made in the spec and then trickle down to the Validation Layers when updated.

I think the intended result would be to update all the VUs from

> If attachment is not VK_ATTACHMENT_UNUSED, and aspectMask ...

to something like

> If attachment is not VK_ATTACHMENT_UNUSED, is an input attachment, and aspectMask ...

I will purpose that fix internally. Thank @luckyxxl for pointing this out and reporting it!

**Comment by luckyxxl** [comment]
OK, no worries, thank you for the explination & clarification and your work on the fix!

**Comment by sfricke-samsung** [comment]
Validation Layers have been fixed to only account for input attachment!
