### ISSUE TITLE
usage1/usage2 containing/comprising/etc each other

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#138]
In the 1.0.6 commit for https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#resources-association :

>          to fname:vkCreateBuffer. Further, if code:usage1 and code:usage2 of type
>     -    elink:VkBufferUsageFlags are such that code:usage2 contains a subset of
>     -    the bits set in code:usage1 and they have the same value of pname:flags,
>     +    elink:VkBufferUsageFlags are such that code:usage2 comprises a subset of
>     +    the bits set in code:usage1 and they have the same pname:flags, then the

I think this change made it far worse. Most dictionaries seem to define "comprise" as both "to include" and "to constitute the whole of", which mean quite different things, and I don't think there's any standard mathematical meaning of "comprise", so this is very confusing language.

Just say "if usage1 is a subset of usage2" (or maybe "if the bits set in usage1 are a subset of the bits set in usage2" to match the phrasing later in the sentence), or vice versa (I'm still not sure which way round it's meant to be).

There's also a similar sentence in https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#_additional_image_capabilities :

> The limitations on an image format that are reported by vkGetPhysicalDeviceImageFormatProperties have the following property: if usage1 and usage2 of type VkImageUsageFlags and flags1 and flags2 of type VkImageCreateFlags are such that usage1 contains a subset of the bits set in usage2 and flags1 contains a subset of the bits set in flags2, then the limitations for usage1 and flags1 must be no more strict than the limitations for usage2 and flags2, for all values of format, type, and tiling.

This should use the same phrasing as the above.

**Comment by oddhack** [comment]
Fair enough. I like the "if the bits set / are a subset of the bits set" terminology and will propose that.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.7 spec update.
