### ISSUE TITLE
rayQueryEXT in compute shaders

### ISSUE THREAD

**Issue by mkdotcom** [KhronosGroup/Vulkan-Docs#1380]
Hello
Using rayQueryEXT (and rayQueryInitializeEXT, rayQueryProceedEXT,...)  doesn't seems to work in compute shaders. 
I have a simple rayquery code in a fragment shader, it works perfectly.
If i use the same code in a compute shader, there is no error at compilation and no error at runtime, but rays never hit anything.
Is it supposed to work? Is there something special about compute shaders?
Thanks a lot for your help

**Comment by dgkoch** [comment]
yes rayQuery is supposed to work in compute shaders, nothing special there.

Seems likely to be a driver or tool-chain issue (not a spec issue), but in the interests of pointing you in the right direction, can you share what your tool-chain is (glslang? DXC?) and drivers. Have you tried looking at the generated SPIR-V to make sure it seems sane and comparable between the fragment and compute versions?
For NVIDIA driver issues, it would be best to follow up at vulkan-support@nvidia.com with repro details.

**Comment by mkdotcom** [comment]
Glslang, latest spirv, all sdks and drivers (beta) up-to-date.
I will try to compare the spir-v.
Thanks!

**Comment by dgkoch** [comment]
@mkdotcom did you have any progress?  

I don't think this is a spec issue, so would like to close this, but am happy to follow up with you elsewhere if needed.

**Comment by mkdotcom** [comment]
I tried today to compare the spirv and just noticed that it's actually working now...
I guess I had someting not well handled somewhere that got fixed, though I don't know how... 
Thanks for your help.
