### ISSUE TITLE
VK_NV_device_generated_commands - alignment of each token input unspecified?

### ISSUE THREAD

**Issue by flisgd** [KhronosGroup/Vulkan-Docs#1382]
https://github.com/KhronosGroup/Vulkan-Docs/blob/c54f67d95ba74b5d5d4e26fb68927666ecbeec2f/chapters/VK_NV_device_generated_commands/indirectcommands.txt#L111

But how to check the alignment for token input?

**Comment by pixeljetstream** [comment]
Natural alignment of the token structs. Most of them will be 4-byte aligned, those with 64-bit addresses, will be 8-byte aligned.

If the buffer is provided with an offset, that offset must be aligned to VkPhysicalDeviceDeviceGeneratedCommandsPropertiesNV
::minIndirectCommandsBufferOffsetAlignment

**Comment by oddhack** [comment]
@flisgd if @pixeljetstream answered your question, could you close this? Thanks.

**Comment by flisgd** [comment]
Thank you!
