### ISSUE TITLE
Fragment shader interlock doesn't guarantee visibility.

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#1383]
While the "Fragment Shader Interlock" section of the specification specifies ordering, it says nothing about the visibility of writes from other critical sections. There's no statement that a primitive ordered operation will see writes that were executed from critical sections from previous fragments in primitive order.

The overview section for the SPIR-V feature states:

> Algorithms using this extension can access per-pixel data structures in critical sections without other invocations accessing the same per-pixel data. Additionally, the ordering guarantees are useful for cases where the API ordering of fragments is meaningful. For example, applications may be able to execute programmable blending operations in the fragment shader, where the destination buffer is read via image loads and the final value is written via image stores.

Doing what the last sentence states requires visibility guarantees in addition to ordering. But neither the SPIR-V extension nor the Vulkan one appears to guarantee visibility.

**Comment by jeffbolznv** [comment]
The memory model appendix describes the ordering guarantees that are provided by the Begin/End instructions, but it's still necessary to use another mechanism (e.g. "coherent") to get the availability/visibility operations. Between those two, you get the full "availability+synchronizes-with+visibility" chain.

**Comment by jeffbolznv** [comment]
I'm planning to add a note to the spec to make this more clear.

**Comment by oddhack** [comment]
This should be addressed in the 1.2.159 spec update.
