### ISSUE TITLE
Add extension with support for QNX platform

### ISSUE THREAD

**Issue by llmike** [KhronosGroup/Vulkan-Docs#1387]
Hi,

I would like to add support for QNX and QNX's Screen composition manager. My primary source of information will be existing Wayland extensions (WSI surface extension as initial step) for this, since concepts of all composition managers are close to each other.

Currently we are not a Khronos member, so we'll go on non-members path.

The first question is what extension suffix we have to pick for surface extension? As far as I understood it should be under QNX domain, so extension name will be something like this: VK_QNX_screen_surface. Is it right? Could it be, for example,, VK_KHR_qnx_screen_surface? I know it must be ratified by Khronos to be KHR.

I have read Vulkan® Documentation and Extensions: Procedures and Conventions, it's pretty clear regarding all required steps.

Thanks.

**Comment by sfricke-samsung** [comment]
As a good source of information, this seems similar to the newly added  `VK_EXT_directfb_surface` which came out of a public GitHub request as well.

https://github.com/KhronosGroup/Vulkan-Docs/pull/1292
https://github.com/KhronosGroup/Vulkan-Docs/pull/1293
https://github.com/KhronosGroup/Vulkan-Docs/pull/1294

As far as the actual functionality, could you clarify what Vulkan implementation this is for? There may be some additional questions raised by the working group once they all had a chance to take a look at this in the next meeting

**Comment by oddhack** [comment]
@llmike if it's QNX the company creating the extension - not clear from your profile - then using that is appropriate. It's unlikely that Khronos would ratify an extension created by a non-member as a KHR extension - there's no mechanism for that and it creates a  large IP risk.

Let us know if you need assistance. The first order of business is a PR reserving an extension number, which should be done as soon as you're committed to creating the extension.

**Comment by llmike** [comment]
@oddhack I'm working for QNX/BlackBerry and I will do this using corporate account, not this one. I'm trying to define all required steps for now and prepare some internal documents first. As for KHR extension - no problems, I expected something like that.

@sfricke-samsung Thanks! Yes, this was an excellent example for me what and how to do this.

**Comment by oddhack** [comment]
Assign back to llmike to propose extension & update title

**Comment by sfricke-samsung** [comment]
@llmike did https://github.com/KhronosGroup/Vulkan-Docs/pull/1449 close this?

**Comment by mgorchak-blackberry** [comment]
Absolutely. We can close this.
