### ISSUE TITLE
Input attachment index SPIR-V example

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#139]
Reported in #33 but not fixed in 1.0.6:

https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#descriptorsets-inputattachment says:

> layout (input_attachment_index=i, set=m, binding=n) uniform subpass myInputAttachment;

The corresponding SPIR-V example doesn't use "i" anywhere. I guess it should have a "OpDecorate %7 InputAttachmentIndex i" to decorate the OpTypeImage.

**Comment by oddhack** [comment]
This should be dealt with in the 1.0.8 spec update.
