### ISSUE TITLE
Missing VU for imageless framebuffer <=> VkImageViewUsageCreateInfo interaction

### ISSUE THREAD

**Issue by martty** [KhronosGroup/Vulkan-Docs#1391]
Since the usage of a VkImageView can be further restricted via VkImageViewUsageCreateInfo, I think a VUID should be added after VUID-VkRenderPassBeginInfo-framebuffer-03210 or so, that calls out VkImageViews with VkImageViewUsageCreateInfos.

For "vanilla" framebuffers, the wording is more loose, so I think it covers this case.

**Comment by sfricke-samsung** [comment]
So thanks for catching this and we agreed and are resolving this issue.

So if you do use `VkImageViewUsageCreateInfo` then when you create your renderpass, the `usage` should match the subset imageView's `usage` instead of the `imageView->image.usage`

**Comment by oddhack** [comment]
This should be fixed in the 1.2.165 spec update.
