### ISSUE TITLE
VkPhysicalDeviceFragmentShadingRateKHR sType member

### ISSUE THREAD

**Issue by Tobski** [KhronosGroup/Vulkan-Docs#1394]
Is there a reason for `VkPhysicalDeviceFragmentShadingRateKHR` to have an `sType` member? That structure type is only used in a get function, but with it having an `sType` member needing initialization (to silence validation), it makes up from some odd code.

Take this for example:

```cpp
std::vector<VkPhysicalDeviceFragmentShadingRateKHR> fragment_shading_rates{};
uint32_t fragment_shading_rate_count = 0;
vkGetPhysicalDeviceFragmentShadingRatesKHR(device, &fragment_shading_rate_count, nullptr);
if (fragment_shading_rate_count > 0)
{
	fragment_shading_rates.resize(fragment_shading_rate_count);
	vkGetPhysicalDeviceFragmentShadingRatesKHR(device, &fragment_shading_rate_count, fragment_shading_rates.data());
}
```

This will trigger validation layer message for all entries in the `fragment_shading_rates` vector. So to silence these and adhere to the valid usage, one would have to set the `sType`  for each entry in that vector. This looks a bit odd and counter-intuitive.

_Originally posted by @SaschaWillems in https://github.com/KhronosGroup/Vulkan-Docs/issues/1384#issuecomment-722513273_

**Comment by Tobski** [comment]
So looking at the rest of the API, I think this might well be the first time we've returned an array of structures with sType parameters, which is somewhat surprising. For consistency with other structs, I added an sType and pNext combo to VkPhysicalDeviceFragmentShadingRateKHR, but it certainly does make code slightly awkward. I'm not sure there's much to do about this as a simple updaet, because we're shipping - but maybe there's some way we can make this less painful...

**Comment by r-potter** [comment]
It's come up in at least two other cases that I know of for in-flight extension proposals. It's especially awkward when you want to actually use the pNext chain. In that case you end up:

1. Querying the element count
2. Dynamically allocating an array of the `header` struct
3. Dynamically allocating one or more arrays of extension structs
4. Iterating over those arrays manually wiring up both the sType and chaining the pNext pointers from one array to the next 

It's not exactly elegant, and it would be nice if we could devise a good API pattern for this. Unfortunately I didn't come up with a solution that I liked when I hit this.

**Comment by jeffbolznv** [comment]
This wasn't the first time it came up, we have the same for at least vkGetPipelineExecutablePropertiesKHR/vkGetPipelineExecutableStatisticsKHR, vkGetPhysicalDeviceToolPropertiesEXT, and vkGetPhysicalDeviceCooperativeMatrixPropertiesNV.

I don't see any problem with this, and suggest we close the issue.

**Comment by oddhack** [comment]
We could set noautovalidity on sType. That won't stop people asking why sType is present but will affect validation layers, I hope.

**Comment by r-potter** [comment]
Discussed in the WG and decided not to make a change here. Unfortunately, even if we made sType optional, pNext would still need wiring up/zero initializing.

For this specific example @oddhack's suggestion *would* work fine from C++11 onwards thanks to how resize() is defined, but the general case/C99 would not.
