### ISSUE TITLE
Float/int aliasing in code sample for section 9.7

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#14]
Another few trivial things. Section numbers are based on https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html

#### 7.1

> During a renderpass instance, input/color attachments [...]

Should be "render pass".

#### 7.4

> The subpasses indices for a render pass begin at zero when vkCmdBeginRenderPass is recorded, and increments each time vkCmdNextSubpass is recorded.

Inconsistent pluralisation ("indices begin ... and increments").

"subpasses indices" sounds really awkward too, I think "subpass indices" would be better English.

#### 8.9

> With few exceptions, fragment shaders do not have access to any data associated with other fragments and is considered to execute in isolation of fragment shader invocations associated with other fragments.

Inconsistent pluralisation ("fragment shaders do not ... and is considered ...").

#### 9.1

> VK_SHADER_STAGE_ALL_GRAPHICS = 0x1F,

All other enum values are defined with 8 digits, so this should be 0x0000001F.

#### 9.2

> * The value of stageCount must be greater than 0 
> * [...]
> * stageCount must be greater than or equal to 1

Redundant requirements.

#### 9.6

> The contents and size of the pipeline cache objects is managed by the implementation.

Should be "are", not "is".

> The details of the merge operation are implementation dependent, but implementations are recommended: to merge the contents of the specified pipelines and prune duplicate entries.

I guess the "recommended:" is meant to be an RFC 2119 term, but it's not formatted properly in the HTML and its colon is visible.

> This field is a VkPipelineCacheHeaderVersion value.

VkPipelineCacheHeaderVersion is not defined anywhere in the document.

#### 9.7

> VkSpecializationMapEntry entries[2];
> const VkSpecializationMapEntry entries[] =

Duplicate definition.

> ((float*)data)[1] = 42.0f;

I think that's undefined behaviour in C. It'd be more correct to do "float f = 42.0f; memcpy(&data[1], &f, sizeof(float))", or easier to just define a "struct { int a; float b; } data" instead of an incorrectly-typed array.

(I think having code samples in the spec is generally a good thing, to help clarify the prose, but it ought to be valid code in case people are tempted to copy-and-paste it into their applications.)

**Comment by oddhack** [comment]
Are you sure about ((float *)data)[1] = 42.0f being undefined? I ran a test case through gcc -std=c99 -Wall -Wpedantic and it didn't complain.

**Comment by oddhack** [comment]
Otherwise, good calls as usual. Working to resolve internally.

**Comment by philiptaylor** [comment]
GCC isn't highly accurate at detecting undefined behaviour, and I think its warnings are dependent on optimisation, though in this case it can emit warnings with the right flags:

    $ cat test.c
    int main() {
      int data[2];
      data[0] = 42;
      ((float*)data)[1] = -42.0f;
      return data[1];
    }
    $ gcc test.c -std=c99 -Wstrict-aliasing=2 -fstrict-aliasing
    test.c: In function 'main':
    test.c:4:3: warning: dereferencing type-punned pointer will break strict aliasing rules [-Wstrict-aliasing]

I think the relevant bit of [C99 (PDF)](http://www.open-std.org/jtc1/sc22/WG14/www/docs/n1256.pdf) is:

> The effective type of an object for an access to its stored value is the declared type of the object, if any.
>
> ...
>
> An object shall have its stored value accessed only by an lvalue expression that has one of the following types:
> * a type compatible with the effective type of the object,
> * ...

So the effective type of data[1] is int (from its declaration), and you're accessing it as float, which is not a compatible (essentially equal) type, so that's not permitted (and it doesn't fall under any of the other permitted cases either).

**Comment by oddhack** [comment]
Done in spec update 1.0.5. Except for the float/int aliasing thing, which I'm narrowing this bug to.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.7 spec update.

**Comment by philiptaylor** [comment]
Was it intentional that the fixed example code is only valid in C++, not C99? (I had the impression the spec was trying to use C99 everywhere.)
