### ISSUE TITLE
Undefined "imageInfo" in VkWriteDescriptorSet description

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#140]
Reported in #33 but not fixed in 1.0.6:

https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#descriptorsets-updates says:

> imageInfo is of type VkDescriptorImageInfo and is defined as:

What is "imageInfo"? That name isn't referenced anywhere else. Maybe should say "Each entry of pImageInfo is of type ...".

**Comment by oddhack** [comment]
This should be dealt with in the 1.0.8 spec update.
