### ISSUE TITLE
Event synchronization

### ISSUE THREAD

**Issue by konstantinegorov** [KhronosGroup/Vulkan-Docs#1403]
> Applications should be careful to avoid race conditions when using events. There is no direct ordering guarantee between a vkCmdResetEvent command and a vkCmdWaitEvents command submitted after it. Another execution dependency (e.g. a pipeline barrier or semaphore with VK_PIPELINE_STAGE_ALL_COMMANDS_BIT) is needed to prevent such a race condition.

Can the sequence `vkCmdWaitEvents/vkCmdResetEvent` cause a race condition, if `dstStageMask `in the wait operation is same as `stageMask` in reset operation? Can the a dependeny chain be formed by `vkCmdSetEvent/vkCmdWaitEvents/vkCmdResetEvent` operations?

Will the following code be safe?

```
vkCmdWaitEvents(..., dstStageMask = COMPUTE_SHADER, ...)
vkCmdResetEvent(..., stageMask = COMPUTE_SHADER)
```

There is one more question. Can the sequence `vkCmdSetEvent/vkCmdWaitEvents/vkCmdResetEvent` for immediate barriers give less performance than `vkCmdPipelineBarrier`, or should it be about the same? In other words, should I expect performance regression if I replace all `vkCmdPipelineBarrier` calls with corresponding VkEvent operations?

**Comment by jzulauf-lunarg** [comment]
Set/Wait/Reset can certainly be safe in the way you describe.  Between the Reset and next use of Set, some additional synchronization (such as a pipeline barrier with VK_PIPELINE_STAGE_ALL_COMMANDS_BIT) will be needed to avoid race conditions between the Reset and Set.

I'm working with @jeffbolznv  and @Tobski on a small clarification here.

**Comment by jzulauf-lunarg** [comment]
The mentioned clarification in the spec doc has been committed.
