### ISSUE TITLE
Device buffer address with offset?

### ISSUE THREAD

**Issue by helixd-2k18** [KhronosGroup/Vulkan-Docs#1404]
Almost a year ago, the `VK_KHR_buffer_device_address` extension was released, and today the final version of ray tracing for the Vulkan API was released, where any offset was removed from the structures, and the buffer address remained in their place. I propose to return these offsets, but in an extremely unusual way. Namely, embed it in the buffer address. Since the structure `VkBufferDeviceAddressInfo` has`pNext`, I suggest adding the structure `VkBufferDeviceAddressOffset[KHR|EXT]`.
```cpp
typedef struct VkBufferDeviceAddressOffset {
    VkStructureType    sType;
    const void*        pNext;
    VkDeviceSize       offset;
} VkBufferDeviceAddressInfo;
```
Not `vkGetBufferDeviceAddress2KHR`, not `VkBufferDeviceAddressInfo2KHR`.

**Comment by dgkoch** [comment]
For what purpose?

The reason for removal of offset is that you can just add the offset to the base device address and pass that offset address in.

**Comment by dgkoch** [comment]
Closing as we don't believe this would add any additional functionality, and would just give two ways of doing the same thing.
