### ISSUE TITLE
26.8. Render Pass Transform, last paragraph seems to be missing words.

### ISSUE THREAD

**Issue by npuschke** [KhronosGroup/Vulkan-Docs#1406]
The last paragraph of section 26.8. Render Pass Transform seems to be missing words and is not very clear.
> The net result of the above, is that applications can act **as if the rendering to a framebuffer oriented with the VkSurfaceCapabilitiesKHR::currentTransform**, as if the presentation engine **will performing** the transformation of the swapchain image after rendering and prior to presentation to the user.

• The first "as if" clause seems incomplete
• will _be?_ performing

**Comment by jackohound** [comment]
Thanks for the feedback.  To be grammatically correct and clearer we should modify the sentence as follows:

> The net result of the above, is that applications can act as if rendering to a framebuffer oriented with the VkSurfaceCapabilitiesKHR::currentTransform.  In other words, applications can act as if the presentation engine will be performing the transformation of the swapchain image after rendering and prior to presentation to the user.

Hopefully this will clarify the intent.   While we are fixing the typos, we will consider adding more developer-focused documentation in the [VK_QCOM_render_pass_transform appendix](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_QCOM_render_pass_transform) if this remains unclear.  

In the mean time, this Qualcomm Developer Guide may provide more complete documentation on how to use the extension:
https://developer.qualcomm.com/downloads/developer-guide-vkqcomrenderpasstransform-extension-rev-b

**Comment by oddhack** [comment]
This should be fixed in the 1.2.169 spec update.
