### ISSUE TITLE
Ambiguous interface location assignment

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#141]
Reported in #45 but not fixed in 1.0.6:

https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#interfaces-iointerfaces-locations says:

> If it is a Block with a Location decoration, then its first member is assigned to the location specified for the Block, any member with its own Location decoration is assigned that location, and each remaining member is assigned the location after the immediately preceding member in declaration order.

If the block has a Location decoration, and first member also has its own Location decoration (which might differ from the block's Location), which rule applies?

**Comment by dgkoch** [comment]
I would propose it's silly to do that :-)
But I'd expect the explicitly assigned one would rule.

**Comment by philiptaylor** [comment]
I wouldn't disagree with that assessment, but I think the behaviour still needs to be specified (or specified as invalid) because, to the best of my knowledge, the spec never states that application developers must not be silly :-)

**Comment by dgkoch** [comment]
Proposing the following language: 

If the structure type is a code:Block but without a code:Location, then
each of its members must: have a code:Location decoration. If it is a
code:Block with a code:Location decoration, then its members are
assigned consecutive locations in declaration order, starting from the
first member which is initially assigned the location specified for the
code:Block. Any member with its own code:Location decoration is assigned
that location. Each remaining member is assigned the location after the
immediately preceding member in declaration order.

Does this clarify it adequately?

**Comment by philiptaylor** [comment]
Hmm, I think that just makes it more ambiguous. The second sentence could be read as "starting from the first of the members that are initially assigned the location specified for the Block", or as "starting from the first member, and that member is initially assigned ...". I assume it means the latter, but in that case, it still doesn't resolve the question of what happens when the first member has its own Location decoration - the "is initially assigned the location specified for the Block" and "assigned [its own Location decoration's] location" requirements both apply and there's no clear precedence between them.

I think it might be better like:

> If the structure type is a Block without a Location decoration, then each of its members must have a Location decoration. If it is a Block with a Location decoration, then each of its members may have a Location decoration. Any member with its own Location decoration is assigned that location. If the first member does not have its own Location decoration, it is assigned the location specified for the block. Each remaining member is assigned the consecutive location after the immediately preceding member in declaration order.

or something a bit like that, so that it's clearer about separately specifying each possible case.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.9 spec update.

**Comment by philiptaylor** [comment]
Looks like the applied change was what @dgkoch quoted above, so my previous response still applies.

I think I disagree with myself about my "no clear precedence" comment though - one of the requirements says "initially" so it seems reasonable to interpret that one as applying first and then being overridden by the other requirement. If people think the current text is clear enough then I'm happy to leave it.
