### ISSUE TITLE
VkAccelerationStructureGeometryTrianglesDataKHR.maxVertex needing to be greater than 0

### ISSUE THREAD

**Issue by llatta** [KhronosGroup/Vulkan-Docs#1413]
From the spec for the maxVertex field in VkAccelerationStructureGeometryTrianglesDataKHR:
"maxVertex is the highest index of a vertex that will be addressed by a build command using this structure."
it sounds like the field should be set to basically "numVertices - 1", as eg a mesh with 50 vertices will use the highest index 49. Is that correct?

If so, the validation VUID-VkAccelerationStructureGeometryTrianglesDataKHR-maxVertex-03655 "maxVertex must be greater than 0" doesn't quite make sense, as it basically disallows meshes with 1 vertex (eg a degenerate triangle with 3 indices pointing to vertex 0), while it allows similarly degenerate triangle meshes with 2 vertices as the minimum. I ran into such a mesh and validation failed.

Can you clarify either the definition or the validation of the maxVertex field?

Thanks!

**Comment by dgkoch** [comment]
Hi @llatta - you are right, the VU should be >= 0, but since maxVertex is uint32_t, we can just delete the VU.

**Comment by dgkoch** [comment]
Fixed in 1.2.166
