### ISSUE TITLE
What happened to the length attribute on VkDescriptorSetAllocateInfo->pSetLayouts

### ISSUE THREAD

**Issue by expipiplus1** [KhronosGroup/Vulkan-Docs#1414]
This seems to have been removed for 1.2.164, was this intentional? The similar length attribute for `VkPipelineLayoutCreateInfo->pSetLayouts` is still present. I had a quick grep through the diff since 1.2.163 and couldn't see any relevant change explaining this, it's not mentioned in the changelog either.

At the moment the spec says (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkDescriptorSetAllocateInfo.html):

> pSetLayouts is a pointer to an array of descriptor set layouts, with each member specifying how the corresponding descriptor set is allocated.

And also

> pSetLayouts must be a valid pointer to a valid VkDescriptorSetLayout handle

**Comment by oddhack** [comment]
@sfricke-samsung can you take this?

**Comment by sfricke-samsung** [comment]
The issue was there was 2 VUs for `descriptorSetCount` to not be zero.... we did (IMO) decide to NOT remove the XML and just keep the 2nd VU, but some miscommunication on my end occurred and I feel we accidentally removed it from the 1.2.164 XML and it should be restored

**Comment by expipiplus1** [comment]
No worries, Thanks for the speedy resolution!
