### ISSUE TITLE
vkCmdBindVertexBuffers2EXT inconsistency

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-Docs#1415]
The docs for vkCmdBindVertexBuffers2EXT state:

VUID-vkCmdBindVertexBuffers2EXT-pStrides-03363
If pStrides is not NULL each element of pStrides must be greater than or equal to the maximum extent of of all vertex input attributes fetched from the corresponding binding, where the extent is calculated as the VkVertexInputAttributeDescription::offset plus VkVertexInputAttributeDescription::format size

This allows `pStrides` to be NULL, at which point drivers infer a value for the associated binding. This does not, however, permit an array containing both nonzero values and zero values, which seems broken to me, as this is an actual use case (e.g., running Unigine Heaven under zink).

I think this instead should read:

If pStrides is not NULL each element of pStrides must be **either zero or** greater than or equal to the maximum extent of of all vertex input attributes fetched from the corresponding binding, where the extent is calculated as the VkVertexInputAttributeDescription::offset plus VkVertexInputAttributeDescription::format size

**Comment by zmike** [comment]
Disregard, Monday is hitting hard this week :/

**Comment by zmike** [comment]
But actually, I'm still interested in this even if the base assertion I made regarding passing NULL for `pStrides` is inaccurate (NULL is not valid when using VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE_EXT). If there's a vertex buffer with different-sized attributes, how is one supposed to accurately generate a stride to pass?

The spec seems to imply that I should be calculating the max `VkVertexInputAttributeDescription::offset + VkVertexInputAttributeDescription::format size` from all the attributes on the buffer, but this doesn't seem to actually work in any driver I've tested. I'd instead expect that passing 0 here would let drivers infer the stride for the attributes on the specified buffer based on their format size? Maybe I'm missing something.

**Comment by pdaniell-nv** [comment]
A single binding point can only have one stride, and it must be non-zero. If you want to consume attributes from the same vertex buffer using different strides, just create additional binding points for each unique stride and bind the same vertex buffers to them.

**Comment by zmike** [comment]
Huh, that's sort of counter to my expectations. Would be great if the documentation could point this out.

**Comment by pdaniell-nv** [comment]
Which part is not what you expected?

**Comment by zmike** [comment]
While it might seem obvious to some, the spec for vkCmdBindVertexBuffers2EXT doesn't ever explicitly state that a single binding point can't have differing strides for the contained elements. Also:
* [section 22.1](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#fxvertex-attrib) on vertex attributes only says *Applications can store multiple vertex input attributes interleaved in a single buffer, and use a single vertex input binding to access those attributes.* There is no mention of stride here.
* The description of `VkVertexInputBindingDescription` makes no mention of this, stating only *stride is the distance in bytes between two consecutive elements within the buffer.* and *stride must be less than or equal to VkPhysicalDeviceLimits::maxVertexInputBindingStride*

For context, I'm using this in a translation from OpenGL, and the stride that I have available for a given binding in this case is 0. When passed to underlying Vulkan drivers (tested on both RADV and ANV), this seems to work as expected with the driver inferring the stride as necessary. This has, I supposed, furthered my confusion here, but I was also unable to find any reference to your point here in the remainder of the spec, so it seems like this is an area which needs clarification.

**Comment by pdaniell-nv** [comment]
I think you're confusing VkVertexInputBindingDescription.stride with how much data a single attribute consumes. They are two separate things. You can have multiple VkVertexInputAttributeDescription definitions share the same binding, and VkVertexInputAttributeDescription.offset specifies where within each binding data element the attribute data is pulled. The amount of data pulled for a single attribute is defined by its format. So VkVertexInputBindingDescription.stride needs to be as big as the largest VkVertexInputAttributeDescription.offset + sizeof(format) to ensure that attribute data isn't being fetched from the next binding data element. Since VkVertexInputBindingDescription and VkVertexInputAttributeDescription are specified separately, which is especially true when using vkCmdBindVertexBuffers2EXT, it would be unreasonable for a stride=0 to infer the stride from the vertex attributes. This is why the Vulkan spec says nothing about stride=0 doing something special.

**Comment by zmike** [comment]
Hm this seems like it makes sense. Based on your description though, I'm a bit confused as to how this has been working until now.

Maybe it's overkill, but it might be worthwhile to add a note about the difference between `VkVertexInputBindingDescription.stride` and the size of an attribute into the docs to avoid this sort of confusion in the future?

**Comment by pdaniell-nv** [comment]
The formula's near the bottom of the https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#_vertex_attribute_divisor_in_instanced_rendering section make it really clear what stride means and how it affects where the attribute data is pulled from.

**Comment by TomOlson** [comment]
@zmike I'll close this for now - please reopen or raise a new ticket if this is still unclear.

**Comment by zmike** [comment]
Ah, sorry, I'd meant to close this a while ago and got sidetracked. Thanks again for the help!
