### ISSUE TITLE
Question About Shader Binding Overlaps

### ISSUE THREAD

**Issue by mossseank** [KhronosGroup/Vulkan-Docs#1420]
I've been planning out a design for a bind-less (or bind-once) descriptor/shader system for my Vulkan renderer. Part of this has been looking into the rules regarding descriptor types and how they can be accessed in shaders - specifically the binding of different shader types (of the same underlying descriptor type) to the same set and binding index within a shader.

An example of what I am talking about (what I am unsure will work, or is even allowed per spec):

```
layout(binding = 0) uniform sampler SAMPLER_TABLE[512];
layout(binding = 1) uniform sampler1D SAMPLER_1D_TABLE[512];
layout(binding = 1) uniform sampler2D SAMPLER_2D_TABLE[512];
/// ...
layout(binding = 2) uniform texture1D TEXTURE_1D_TABLE[512];
layout(binding = 2) uniform texture2D TEXTURE_2D_TABLE[512];
```

Note that the different shader types are all bound to the same binding index, but they do all use the same descriptor type for Vulkan (e.g. `VK_DESCRIPTOR_TYPE_SAMPLER` is at binding 0, `VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER` is at binding 1, ect...).

The plan at runtime would be to pass the resource index in a UBO or as a push constant, and access the resource using that index. Each underlying descriptor type would share a binding array in a single global descriptor set (e.g. all images, regardless of dimensionality, would go into the large array at binding *N*).  This seems to be a pretty common pattern in some oft-cited [presentations](https://gpuopen.com/wp-content/uploads/2016/03/VulkanFastPaths.pdf) and [blogs](http://kylehalladay.com/blog/tutorial/vulkan/2018/01/28/Textue-Arrays-Vulkan.html) that discuss bind-less/bind-once systems.

If this sort of aliasing/overlapping is not supported, then the alternative would be to use something along the lines of:

```
layout(binding = 0) uniform sampler SAMPLER_TABLE[512];
layout(binding = 1) uniform sampler1D SAMPLER_1D_TABLE[512];
layout(binding = 2) uniform sampler2D SAMPLER_2D_TABLE[512];
/// ...
layout(binding = <N>) uniform texture1D TEXTURE_1D_TABLE[512];
layout(binding = <N+1>) uniform texture2D TEXTURE_2D_TABLE[512];
```

There is a specific note in the [Binding Assignment section of the spec](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap16.html#interfaces-resources-setandbinding) that addresses this situation, namely:

> If multiple shader variables are declared with the same set and binding values, and with the same underlying descriptor type, they can all be statically used within the same shader. However, accesses are not automatically synchronized, and Aliased decorations should be used to avoid data hazards (see section 2.18.2 Aliasing in the SPIR-V specification).

This seems to imply that what I am asking about is possible, but I am still unsure about the provided example for a few reasons:

1. The resources are bound as large arrays that act as tables, that are indexed dynamically at runtime. 
2. What affect the different SPIR-V types have on this rule (e.g. `sampler2D` and `sampler3D` indexing the same descriptor table) 

Additionally, I'm not sure how this would be affected if the renderer could somehow guarantee that the wrong type is never accessed (e.g. indexing into the `sampler3D` table for a resource that is only backed by a 2D image).

**Comment by jeffbolznv** [comment]
This is valid. But as you suggest, the renderer has to guarantee that it won't do an access where the shader variable dimension and image view dimension don't match.

**Comment by jeffbolznv** [comment]
Closing. Please reopen if there are any concerns.
