### ISSUE TITLE
custom border color swizzle ambiguity

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-Docs#1421]
When using VK_EXT_custom_border_color to create a custom border color, there's some ambiguity regarding whether the color specified should be swizzled using the VkImageView's swizzle prior to creating the sampler or whether the color will "automatically" be swizzled.

I've [filed a bug against ANV](https://gitlab.freedesktop.org/mesa/mesa/-/issues/4020) since their implementation's behavior is consistent with automatic swizzling.

RADV developers have been similarly notified, and this driver assumes pre-swizzling.

Clarification would be appreciated.

**Comment by jekstrand** [comment]
At the top of the _Texel Input Operations_ section, there is a list of operations and the order in which they occur.  It's very explicit that texel replacement (which includes application of border color) happens before texture swizzle.  I think you're looking at a RADV bug.  There is a special case in the spec for `OPAQUE_BLACK` which says that swizzling it may not work correctly, but we didn't put any such special cases in VK_EXT_custom_border_color.

**Comment by rg3igalia** [comment]
@oddhack this issue can be closed. VK_EXT_border_color_swizzle was shipped to fix these cases.
