### ISSUE TITLE
Peer memory synchronization

### ISSUE THREAD

**Issue by pascal-gw** [KhronosGroup/Vulkan-Docs#1426]
Hi,

I'm having issue to properly synchronize peer memory between physical devices of a device group. And I can't figure it out from the specs and the docs online (eg. https://www.khronos.org/assets/uploads/developers/library/2017-gdc/GDC_Vulkan-on-Desktop_Feb17.pdf). How is it supposed to be done correctly? :)

Let's say that I have an image A with its memory bound to 2 GPUs, a shader is writing to this image A on GPU 0 (using the appropriate device mask), and now I'd like to transfer the result to GPU 1.
What I've been doing so far is to create 2 additional images B0 and B1 sharing the memory allocation of image A (with Bi memory only being bound to physical device i), all 3 images have the alias bit set. To do the copy I'm doing something like:

```
vkSetDeviceMask(GPU0 & GPU1);
imageMemoryBarrier with VK_ACCESS_TRANSFER_READ_BIT | VK_ACCESS_TRANSFER_WRITE_BIT, VK_IMAGE_LAYOUT_GENERAL, VK_PIPELINE_STAGE_TRANSFER

vkSetDeviceMask(GPU0);
vkCmdCopyImage(srcImage = B0, srcImageLayout = VK_IMAGE_LAYOUT_GENERAL, dstImage = B1, dstImageLayout = VK_IMAGE_LAYOUT_GENERAL);

vkSetDeviceMask(GPU0 & GPU1);
imageMemoryBarrier with VK_ACCESS_TRANSFER_READ_BIT | VK_ACCESS_TRANSFER_WRITE_BIT, VK_IMAGE_LAYOUT_GENERAL, VK_PIPELINE_STAGE_TRANSFER
```

It kind of works :D but there are artifacts from time to time, indicating that I have no idea what I'm really doing.

Do I even need those 2 extra aliased images just for the transfer? It doesn't seem possible to do this transfer only with A.
Also I tried not using `VK_IMAGE_LAYOUT_GENERAL`, eg. `VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL` & `VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL` but the validation layer is complaining a lot.

How is `VK_DEPENDENCY_DEVICE_GROUP_BIT` supposed to be used? If I use it for my memory barriers I end up with the GPUs no longer working at the same time.

Cheers.

**Comment by jeffbolznv** [comment]
It sounds like there's missing synchronization to make GPU1 wait for the copy done by GPU0 to finish. Adding VK_DEPENDENCY_DEVICE_GROUP_BIT should do it - that flag essentially makes each GPU wait on the other. But if the work is unbalanced then it can cause the other GPU to sit idle. The other option is to use semaphores to do this synchronization - have GPU0 signal a semaphore after the copy and GPU1 wait on it before it starts using the result.

Hope this helps.

**Comment by pascal-gw** [comment]
Thanks. I could get rid of the artifacts.
