### ISSUE TITLE
[Specification] Ray Intersection Candidate Determination

### ISSUE THREAD

**Issue by Retrofractal** [KhronosGroup/Vulkan-Docs#1427]
I'm not sure whether this section is still a work-in-progress so apologies if this is already clear, but I'm not sure the rotation matrix defined in section 36.1 really provides the intended implementation freedom. Specifically, the unit vector `a` looks like it needs to be perpendicular to both `k` and `d` for this to work (it's the axis of rotation). The intersection candidate definition essentially assumes the z-axis has been rotated onto the ray direction, which means the bottom row of that matrix (I'm assuming the column vector and matrix are exchanged here, otherwise those column vectors probably should be row vectors) ought to be parallel to the direction vector.
The above also seems to assume that `d` is a unit vector, both in the definition of the rotation angle (that involves an undefined term `u` [should this be `k`?']) and the intersection candidate z interval (where neither `tmin` nor `tmax` have been scaled).

**Comment by Tobski** [comment]
Ping @fluppeteer since he was the last person to suggest edits to this section IIRC.

@Retrofractal I know we made changes to this section fairly late when we realised there could be an issue, so it's possible we missed something. I can't quite visualise the issue here, but we will look at figuring it out...

**Comment by Retrofractal** [comment]
Thanks - I should think, given the relaxations on accuracy and watertightness requirements, it would be sufficient to revert the description to a rotation onto the ray. The implementation can decide whether to perform this operation to determine an intersection candidate, or some other equivalent calculation.

**Comment by fluppeteer** [comment]
We did make a late change - I think I observed that having a fixed unit vector wasn't common practice compared with picking something based on the major axis of the ray direction.

I need to think this through again, but I think what we meant might have been:

> s and c are the sine and cosine of the angle &alpha; between k and **a**.

...and remove the description of k.

Is that plausible?

**Comment by Retrofractal** [comment]
The rotation angle should be between `k` and `d` with `k.d/|d|` instead of `u.d` and `a` should be perpendicular to both, as it was previously, otherwise the ray won't point in the correct direction. As far as an actual implementation is concerned, it should produce equivalent results (up to implementation-specific accuracy and watertight behaviour) so there's no need to worry about what's common practice.
Additionally, since `t` measures lengths in units of `|d|`, we want something like `tmin <= z_r / |d| <= tmax` for the intersection candidate criteria.

**Comment by oddhack** [comment]
This should be fixed in the 1.2.169 spec update.
