### ISSUE TITLE
Cross reference pipelines-dynamic-state from functions that set dynamic state

### ISSUE THREAD

**Issue by aclysma** [KhronosGroup/Vulkan-Docs#1428]
It wasn't clear to me from reading https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdSetViewport.html if the lifetime of the state was tied to a bound pipeline, render pass, or commands buffer.

Some kind people linked https://renderdoc.org/vkspec_chunked/chap11.html#pipelines-dynamic-state for me which explained it. Would it make sense to add something like "This call affects <<pipelines-dynamic-state, Dynamic State>>." somewhere on that page (and other calls that affect dynamic state)? Or, link it from the first occurrence of "dynamic state" on the page? (I think this would be helpful on all calls that affect dynamic state.)

**Comment by oddhack** [comment]
This should be fixed in the 1.2.194 spec update (n.b. in addition to adding the requested links, I did quite a bit of editing to make the various dynamic state-setting commands use consistent and complete language).
