### ISSUE TITLE
Is it valid to pass a wrong extension or layer name?

### ISSUE THREAD

**Issue by tomaka** [KhronosGroup/Vulkan-Docs#143]
Section 2.5 of the specs explains that there are two kinds of errors:

- Valid API usage is not checked and is left to the application or the validation layers.
- Runtime errors, which are returned with return codes.

However there's an ambiguity in the situation where you pass a wrong layer name or extension name to `vkCreateInstance` or `vkCreateDevice`.

On one hand the specs say, for example for `vkCreateInstance`:
> Any given element of ppEnabledLayerNames must be the name of a layer present on the system, exactly matching a string returned in the VkLayerProperties structure by vkEnumerateInstanceLayerProperties
> Any given element of ppEnabledExtensionNames must be the name of an extension present on the system, exactly matching a string returned in the VkExtensionProperties structure by vkEnumerateInstanceExtensionProperties
> If an extension listed in ppEnabledExtensionNames is provided as part of a layer, then both the layer and extension must be enabled to enable that extension

On the other hand `vkCreateInstance` and `vkCreateDevice` can also return the `VK_ERROR_LAYER_NOT_PRESENT` and `VK_ERROR_EXTENSION_NOT_PRESENT` return codes.

Which raises the question: is it mandatory for implementations to return an error when a layer or extension name is wrong, or is it the job of the application to enumerate layers and extensions and only pass correct names?

**Comment by courtney-g** [comment]
We added the run-time VK_ERROR_LAYER_NOT_PRESENT and VK_ERROR_EXTENSION_NOT_PRESENT because it's possible for changes in the system to change the layers / extensions available, i.e. unpredictable events that can only happen at run-time and so we provide that runtime error.

So, yes, it is mandatory for systems to return that error. Right now, that is done/implemented in the desktop and Android loaders.

**Comment by tomaka** [comment]
Shouldn't these sets of rules be removed then?

> Any given element of ppEnabledLayerNames must be the name of a layer present on the system, exactly matching a string returned in the VkLayerProperties structure by vkEnumerateInstanceLayerProperties
> Any given element of ppEnabledExtensionNames must be the name of an extension present on the system, exactly matching a string returned in the VkExtensionProperties structure by vkEnumerateInstanceExtensionProperties
> If an extension listed in ppEnabledExtensionNames is provided as part of a layer, then both the layer and extension must be enabled to enable that extension

**Comment by courtney-g** [comment]
I don't think so. The app should do that, but due to changes outside it's control, a layer / extension it thought was there may not be anymore.
