### ISSUE TITLE
read-after-read dependency

### ISSUE THREAD

**Issue by konstantinegorov** [KhronosGroup/Vulkan-Docs#1430]
Suppose there is a buffer that is already visible to the compute shader for uniform reading, and I want to also read it as a uniform buffer, but in the vertex shader. Does a just execution dependency between compute and vertex shaders guarantee (VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT -> VK_PIPELINE_STAGE_VERTEX_SHADER_BIT) that memory that is already visible to the compute shader will be visible to the vertex shader for uniform reading?

**Comment by Tobski** [comment]
You never need any dependency between reads, but you do need to explicitly request visibility in each shader you are going to access it in - you can't assume that all shader stages share a cache, for instance.

The most efficient thing to do is that wherever you make the value visible to the compute shader you should also make it visible to the vertex shader at the same time.

**Comment by konstantinegorov** [comment]
Thanks for the answer
