### ISSUE TITLE
VK_DEFINE_NON_DISPATCHABLE_HANDLE issues on 32-bit platforms

### ISSUE THREAD

**Issue by baryluk** [KhronosGroup/Vulkan-Docs#1431]
On 64-bit platforms the handles becomes pointer. As I understand this is for type safety in C.

On 32-bit platforms the handles become uint64, which removes the type safety.

I understand the generic convenience and help it adds to finding bugs and coding mistakes.

But it also causes issues when writing generic code for both 32-bit and 64-bit platforms.

For example in Mesa zink OpenGL on Vulkan driver, there is code like this:

```c
...
   struct hash_entry *he = _mesa_hash_table_search_pre_hashed(&fb->objects, hash, rp);
   if (he) {
#if defined(__LP64__) || defined(_WIN64) || (defined(__x86_64__) && !defined(__ILP32__) ) || defined(_M_X64) || defined(__ia64) || defined (_M_IA64) || defined(__aarch64__) || defined(__powerpc64__)
      ret = (VkFramebuffer)he->data;
#else
      ret = *((VkFramebuffer *)he->data);
#endif
      goto out;
   }
...


#if defined(__LP64__) || defined(_WIN64) || (defined(__x86_64__) && !defined(__ILP32__) ) || defined(_M_X64) || defined(__ia64) || defined (_M_IA64) || defined(__aarch64__) || defined(__powerpc64__)
   _mesa_hash_table_insert_pre_hashed(&fb->objects, hash, rp, ret);
#else
   {
      VkFramebuffer *ret_p = ralloc(NULL, VkFramebuffer);
      *ret_p = ret;
      _mesa_hash_table_insert_pre_hashed(&fb->objects, hash, rp, ret_p);
   }
#endif
out:

...

   hash_table_foreach(&fb->objects, he) {
#if defined(__LP64__) || defined(_WIN64) || (defined(__x86_64__) && !defined(__ILP32__) ) || defined(_M_X64) || defined(__ia64) || defined (_M_IA64) || defined(__aarch64__) || defined(__powerpc64__)
      vkDestroyFramebuffer(screen->dev, (VkFramebuffer)he->data, NULL);
#else
      VkFramebuffer *r = (VkFramebuffer *)(he->data);
      vkDestroyFramebuffer(screen->dev, *r, NULL);
      ralloc_free(r);
#endif
   }


...

   if (vkAllocateDescriptorSets(screen->dev, &dsai, sets) != VK_SUCCESS) {
#if defined(__LP64__) || defined(_WIN64) || (defined(__x86_64__) && !defined(__ILP32__) ) || defined(_M_X64) || defined(__ia64) || defined (_M_IA64) || defined(__aarch64__) || defined(__powerpc64__)
      debug_printf("ZINK: %p failed to allocate descriptor set :/\n", dsl);
#else
      debug_printf("ZINK: %" PRIu64 " failed to allocate descriptor set :/\n", dsl);
#endif

      return false;
   }

```

`_mesa_hash_table_insert_pre_hashed` accepts as a last parameter a `void*`. It doesn't take ownership of this pointer.

So for the case of 64-bit, we just put it there, and use on lookup, and pass around.

However, on 32-bit platforms this hash table now still only accepts `void*`, but that is 32-bit, so not enough to hold VkFramebuffer, which is still 64-bit.

Thus this special casing with dynamic allocation is required.

You could say, the special casing is not required, and just doing a second branch would work.

While that is true, that would introduce unnecessary overheads on 64-bit platforms.

Even if the `_mesa_hash_table_insert_pre_hashed` and family is extended to support 64-bit values unconditionally, it would still require special handling by macros, to detect between `void*` and `uint64_t` for type safety. And would not solve the issue of `printf` (very handy in debugging).

The problem, because it is not possible to detect the object or type size from the C macro, we need to repeat the entire define condition, which is ugly and fragile.

It would be nice, if the VK_DEFINE_NON_DISPATCHABLE_HANDLE would be rewritten to allow easier detection of which mode of operations is in effect:

```c
#if !defined(VK_DEFINE_NON_DISPATCHABLE_HANDLE)
#if defined(__LP64__) || defined(_WIN64) || (defined(__x86_64__) && !defined(__ILP32__) ) || defined(_M_X64) || defined(__ia64) || defined (_M_IA64) || defined(__aarch64__) || defined(__powerpc64__)
        #define VK_DEFINE_NON_DISPATCHABLE_HANDLE_IS_PTR 1
        #define VK_DEFINE_NON_DISPATCHABLE_HANDLE(object) typedef struct object##_T *object;
#else
        #define VK_DEFINE_NON_DISPATCHABLE_HANDLE_IS_UINT64 1
        #define VK_DEFINE_NON_DISPATCHABLE_HANDLE(object) typedef uint64_t object;
#endif
#endif
```

Then the code above will reduce considerably in size and become less fragile. This can't be solved just by adding this macros in the client code, because it will become out of sync with Vulkan headers eventually (i.e. what about RISC-V, or Alpha, or other new architecture, etc).

**Comment by jekstrand** [comment]
Do you really need all that complexity?  Going off your first example, why can't you just do this?
```c++
   struct hash_entry *he = _mesa_hash_table_search_pre_hashed(&fb->objects, hash, rp);
   if (he) {
      if (sizeof(void *) == sizeof(VkFramebuffer)) {
         ret = (VkFramebuffer)he->data;
      } else {
         ret = *((VkFramebuffer *)he->data);
      }
   }
```
and the compiler should constant-fold that if statement away so you only end up with one of the two in the biary.

Or, even better yet, why not make a variant of the hash table which has `uint64_t` values.  We (mesa) already have one which takes `uint64_t` keys so it wouldn't be hard to do the same thing for `void *` keys and `uint64_t` values.

I really don't think this is Vulkan's problem to solve.  Non-dispatchable handles are always 64-bit.  If that ever changes on some other platform then then we (the Vulkan working group) got something very wrong.

**Comment by baryluk** [comment]
@jekstrand Or, even better yet, why not make a variant of the hash table which has uint64_t values.

Yes, that is the best option of course.

**Comment by baryluk** [comment]
> Do you really need all that complexity? Going off your first example, why can't you just do this?
> 
> ```c++
>    struct hash_entry *he = _mesa_hash_table_search_pre_hashed(&fb->objects, hash, rp);
>    if (he) {
>       if (sizeof(void *) == sizeof(VkFramebuffer)) {
>          ret = (VkFramebuffer)he->data;
>       } else {
>          ret = *((VkFramebuffer *)he->data);
>       }
>    }
> ```
> 
> and the compiler should constant-fold that if statement away so you only end up with one of the two in the biary.

As I said before this would not work without a macro. The issue with the above code, is that when compiling on 32-bit system, the compiler will still emit a warning or error in a dead code:

```
 ../../src/gallium/drivers/zink/zink_descriptors.c:354:17: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  354 |          return (VkDescriptorSetLayout)he->data;
```

Similarly, in opposite way, i.e. on 32-bit system:

```
../../src/gallium/drivers/zink/zink_descriptors.c:375:81: error: passing argument 4 of ‘_mesa_hash_table_insert_pre_hashed’ makes pointer from integer without a cast [-Werror=int-conversion]
  375 |       _mesa_hash_table_insert_pre_hashed(&ctx->desc_set_layouts[type], hash, k, dsl);
      |                                                                                 ^~~
      |                                                                                 |
      |                                                                                 VkDescriptorSetLayout {aka long long unsigned int}
```

The problem, is that here `dsl` is `uint64_t`, but the last argument is `void*` which is 32-bit. So double bad.

AFAIK this can only be solved by having a macro just like I presented initially.

**Comment by dgkoch** [comment]
VK_USE_64_BIT_PTR_DEFINES was added in 1.2.174
