### ISSUE TITLE
vkGetPipelineExecutableStatisticsKHR for ray-tracing pipeline

### ISSUE THREAD

**Issue by pascal-gw** [KhronosGroup/Vulkan-Docs#1433]
`VUID-vkGetPipelineExecutableStatisticsKHR-pipeline-03274` only specifies compute and graphics pipeline. Shouldn't it be allowed for the new khr ray-tracing pipeline as well?

**Comment by sfricke-samsung** [comment]
`VUID-vkGetPipelineExecutableInternalRepresentationsKHR-pipeline-03278` also has this issue (and I guess `VK_AMD_pipeline_compiler_control` as well) scanning the spec

**Comment by sfricke-samsung** [comment]
Also seems the validation layers have these VUs covered, but have not added a check for `VK_STRUCTURE_TYPE_RAY_TRACING_PIPELINE_CREATE_INFO_KHR`

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/1186f95a2f7bdc8240349e4aa48594594b9d0871/layers/core_validation_types.h#L1034

**Comment by oddhack** [comment]
This should be fixed in the 1.2.171 spec update.
