### ISSUE TITLE
Potentially missing levelCount validation for 3D textures viewed as 2D array

### ISSUE THREAD

**Issue by Kangz** [KhronosGroup/Vulkan-Docs#1438]
Shouldn't the `vkCreateImageView` validation require that if a 2D / 2D array view is created on a 3D texture with `VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT ` then `levelCount` should be one?

The reason is the following: imagine that we have a 3D texture of size 2x2x2 and 2 mip levels that's `VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT`. If we create a 2D array view on it for the whole subresource range, we're going to have a 2D array view with miplevels 0 size 2x2x2 and miplevel 1 sized 1x1x1, which breaks assumptions about 2D array view. What happens then when in the shader I sample from the second layer of the texture but LOD computations select mip level 1?

**Comment by Kangz** [comment]
Correction, it is listed in `Table 8. Image and image view parameter compatibility requirements` but not in the VUs.

**Comment by krOoze** [comment]
[VUID-VkImageViewCreateInfo-subResourceRange-01021](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkImageViewCreateInfo-subResourceRange-01021):

> `subresourceRange` and `viewType` **must** be compatible with the image, as described in the _compatibility table_

**Comment by Kangz** [comment]
Thanks, that makes sense.
