### ISSUE TITLE
Missing types/commands in vk.xml for extension VK_QNX_screen_surface

### ISSUE THREAD

**Issue by cmarcelo** [KhronosGroup/Vulkan-Docs#1440]
These types and commands below are missing their respective entries in `<types>` and `<commands>` sections.

    <type name="VkScreenSurfaceCreateFlagsQNX"/>
    <type name="VkScreenSurfaceCreateInfoQNX"/>
    <command name="vkCreateScreenSurfaceQNX"/>
    <command name="vkGetPhysicalDeviceScreenPresentationSupportQNX"/>

Found when Vulkan-ValidationLayers complained about the missing entries.

CC: @oddhack @mgorchak-blackberry

**Comment by mgorchak-blackberry** [comment]
Hi,

I almost ready to submit all missing parts. Will try to do this ASAP, perhaps this week.

Thanks!

**Comment by dgkoch** [comment]
I believe this has been addressed by #1449. closing.
