### ISSUE TITLE
Is `minImportedHostPointerAlignment` intended to be a power of two?

### ISSUE THREAD

**Issue by haasn** [KhronosGroup/Vulkan-Docs#1442]
Most other alignment fields are specified as being powers of two, with the exception of `minImportedHostPointerAlignment`. Is this an oversight or intentional?

**Comment by sfricke-samsung** [comment]
So discussed internally and we believe this is an oversight. We are going to purpose a spec fix internally to add the power of two restrictions as well as a CTS test for it as well

**Comment by oddhack** [comment]
This should be fixed in the 1.2.179 spec update.
