### ISSUE TITLE
Sparse image granularity inconsistency for compressed formats

### ISSUE THREAD

**Issue by skeysl** [KhronosGroup/Vulkan-Docs#1444]
There are two definitions of _imageGranularity_ in the standard. First for _VkSparseImageFormatProperties_ structure and second for _VkSparseImageMemoryRequirements_ structure:

[https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#_sparse_image_format_properties_api](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#_sparse_image_format_properties_api)

> imageGranularity is the width, height, and depth of the sparse image block in texels or compressed texel blocks.

[https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#_sparse_image_memory_requirements](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#_sparse_image_memory_requirements)

> formatProperties.imageGranularity describes the dimensions of a single bindable sparse image block in texel units. ....

Second definition does not mention compressed texel blocks. Does it mean that value of this property is expressed only in texels and not in compressed texel blocks? Is the value result of multiplication noted in section Standard Sparse Image Block Shapes?

[https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#sparsememory-standard-shapes](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#sparsememory-standard-shapes)

>For block-compressed formats, the dimensions of a sparse image block in terms of texels can be calculated by multiplying the sparse image block dimensions by the compressed texel block dimensions

Please, could you clarify?

**Comment by oddhack** [comment]
This should be fixed in the 1.2.184 spec update. The second bit of language you quoted should not have described the nested struct members, just the formatProperties member.
