### ISSUE TITLE
Clarification on meta-stage access

### ISSUE THREAD

**Issue by martty** [KhronosGroup/Vulkan-Docs#1446]
The spec says 
```
VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT is equivalent to VK_PIPELINE_STAGE_ALL_COMMANDS_BIT with VkAccessFlags set to 0 when specified in the second synchronization scope, but specifies no stages in the first scope.
VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT is equivalent to VK_PIPELINE_STAGE_ALL_COMMANDS_BIT with VkAccessFlags set to 0 when specified in the first synchronization scope, but specifies no stages in the second scope.
```
What does `VkAccessFlags set to 0` mean in practice? I can imagine that this means that the relevant flags are either
 - considered to be zero, the actual value is ignored
 - must be zero, it is incorrect to pass any other value
 - suggested to be set to zero (perhaps a best-practices issue?)

But I think this could be clarified in the text, unless I missed it.

**Comment by krOoze** [comment]
I think it means this: https://stackoverflow.com/questions/65764113/vk-pipeline-stage-top-of-pipe-bit-vkaccessflags-set-to-0/65776635#65776635

**Comment by Tobski** [comment]
I'm not sure if @krOoze's response satisfied you here @martty, but just to answer your specific question, the spec basically ignores whatever you put in the access masks for the noted stages if you use TOP/BOTTOM (so basically your first comment). It's also saying that it is equivalent to using the ALL_COMMANDS or 0 with an empty access mask.

There's also an open item for the best practices layer to catch use of non-empty access masks with TOP/BOTTOM: https://github.com/KhronosGroup/Vulkan-ValidationLayers/projects/1#card-48657691

If you're satisfied that your questions have been answered, please close the issue. Thanks!

**Comment by martty** [comment]
Thank you for the answers, I am satisfied (I suppose synchronization2 was also an answer in its way)!
