### ISSUE TITLE
Missing SPIR-V extension SPV_EXT_shader_atomic_float_add from vk.xml

### ISSUE THREAD

**Issue by ilkkasaa** [KhronosGroup/Vulkan-Docs#1447]
I think the extension `SPV_EXT_shader_atomic_float_add` / `VK_EXT_shader_atomic_float` should be listed in vk.xml in the list "SPIR-V Extensions allowed in Vulkan and what is required to use it".

The validation layers use the list to check if a SPIR-V code requires any extensions not supported by Vulkan. At the moment the layers give an error if the extension `SPV_EXT_shader_atomic_float_add` is used.

**Comment by sfricke-samsung** [comment]
Created internal MR 4376 to add. Sorry this got missed in the recent Spec XML addition to auto generate the Validation Layers. Thanks for raising this!

**Comment by oddhack** [comment]
This should be fixed in the 1.2.171 spec update.
