### ISSUE TITLE
vkCmdResetEvent and subsequent vkCmdSetEvent

### ISSUE THREAD

**Issue by konstantinegorov** [KhronosGroup/Vulkan-Docs#1452]
> Applications should be careful to avoid race conditions when using events. There is no direct ordering guarantee between a vkCmdResetEvent command and vkCmdSetEvent or vkCmdWaitEvents commands submitted after it. Similarly, there is no ordering guarantee between sequential vkCmdSetEvent commands, leading to a race condition on the event status. Waiting on an event in these cases without additional synchronization can result in a data race. Another execution dependency (e.g. a pipeline barrier or semaphore with VK_PIPELINE_STAGE_ALL_COMMANDS_BIT) is needed to prevent such race conditions.

Could the following cause a race condition?

```
let STAGE_MASK_FOR_RESET = ...
let STAGE_MASK_FOR_SET = STAGE_MASK_FOR_RESET | ... (superset of the STAGE_MASK_FOR_RESET or same)

vkCmdResetEvent(event, STAGE_MASK_FOR_RESET)
vkCmdSetEvent(event, STAGE_MASK_FOR_SET)

**Comment by krOoze** [comment]
Well yea. You just quoted that "there is no direct ordering guarantee between a `vkCmdResetEvent` command and `vkCmdSetEvent`".

Only thing that has ordering guarantee is the event signal by `vkCmdSetEvent` and `vkCmdWaitEvents` submitted after it.

**Comment by jzulauf-lunarg** [comment]
STAGE_MASK_FOR_RESET  is what vkCmdResetEvent will wait for before un-signaling the event.

STAGE_MASK_FOR_SET  is what vkCmdSetEvent will wait for before signaling the event.

However if they are waiting on the same stages (including VK_PIPELINE_STAGE_ALL_COMMANDS_BIT), the order in which they attempt the un-signal and signal operations is undefined and the following means that potentially the SetEvent will be effectively noop'd if performed *first*.

> If event is already in the signaled state when vkCmdSetEvent is executed on the device, then vkCmdSetEvent has no effect, no event signal operation occurs, and no dependency is generated.

So the spec's injunction

> Another execution dependency (e.g. a pipeline barrier or semaphore with VK_PIPELINE_STAGE_ALL_COMMANDS_BIT) is needed to prevent such race conditions.

is the requirement for correct operation.

**Comment by jzulauf-lunarg** [comment]
@krOoze  -- in discussion with @Tobski, ResetEvent can correctly synchronize with WaitEvents using a stageMask including the *dst*StageMask of WaitEvents -- but the VK_PIPELINE_STAGE_ALL_COMMANDS_BIT synchronization between Reset and Set can't be avoided.

**Comment by krOoze** [comment]
@jzulauf-lunarg I believe that is what I said. There is no implicit ordering guarantee. Only way to make it work is with explicit sync. Besides, why would you sync reset with wait; that would be a deadlock.

**Comment by jzulauf-lunarg** [comment]
@krOoze -- I don't believe *any* CmdSetEvent mask can guard w.r.t. CmdResetEvent  ...  in an implementation, there's going to be an atomic clear (reset) and and atomic test and set(set) that are going to happen at some point *after* the commands pass TOP_OF_PIPE (though they happen at *no* stage), and you don't know the order. If they happen clear then test-and-set then the signal op will happen, test-and-set (fails) and then clear, the set will be no-op'd.  There needs to be an additional synchronization operation between the two.

The CmdWaitEvents(dstStageMask); CmdResetEvent(stageMask) doesn't deadlock, but safely resets if stageMask & dstStageMask.

**Comment by krOoze** [comment]
@jzulauf-lunarg I am just reading the spec. If a pipeline barrier can cover it, then `vkCmdSetEvent` can cover it; a source stage should be a source stage no matter which command. If that is not so, then it needs some serious spec clarification, if not outright correction.

> The CmdWaitEvents(dstStageMask); CmdResetEvent(stageMask) doesn't deadlock, but safely resets if stageMask & dstStageMask.

Waiting on a unsignalled primitive is a deadlock. I mean there can be some niche, like resetting the event (and syncing it with wait), and then instead signal it from host. But that is kinda obscure case, and IIRC it was marked unspecified at some point too.

**Comment by Tobski** [comment]
@krOoze is correct, waiting for ALL_COMMANDS_BIT on a set event would wait for _any_ reset event, as ALL_COMMANDS_BIT waits for _everything_. I do wonder if we're testing this slightly wacky corner case however...

**Comment by jzulauf-lunarg** [comment]
@krOoze  -- I'm assuming there is a Set *prior* to the Wait.  I'm just noting that Reset can safely follow Wait when dstStageMask & stageMask != 0 (unless I misunderstood @Tobski .

@Tobski -- I'm not even sure how one would *reliably* test that corner case.

**Comment by oddhack** [comment]
@jzulauf-lunarg is there more to be done here? The original request wasn't for a spec clarification and I think? has been answered in the long discussion above, so perhaps this can be closed?

**Comment by jzulauf-lunarg** [comment]
Clarification in discussion above consistent with spec. No spec changes required.
