### ISSUE TITLE
VK_EXT_image_drm_format_modifier: Ambiguity between vkBindImageMemory memoryOffset and VkSubresourceLayout.offset

### ISSUE THREAD

**Issue by haasn** [KhronosGroup/Vulkan-Docs#1453]
When importing external memory using DRM format modifiers, the offsets for each plane are moved to `VkImageDrmFormatModifierExplicitCreateInfoEXT.pPlaneLayouts`. However, this seems to create some amount of ambiguity between this set of plane offsets and the image offset provided in `vkBindImageMemory` (the `VkDeviceSize memoryOffset` parameter).

It seems like some drivers deal with this in practice by assuming the `vkBindImageMemory` offset is used as a *base* to which the plane offsets are relative to, but it would be helpful if the spec could clarify that this is intended behaviour. As of now it seems to be ambiguous/unspecified behaviour.

I personally think it would make most sense to require that the `vkBindImageMemory` offset is 0 when using DRM modifiers / plane offsets, to prevent any confusion.

**Comment by haasn** [comment]
Hmm, answering my own question I think this is not actually ambiguous. The spec says,

> `offset` is the byte offset from the start of the image or the plane where the image subresource begins.

So given that the `vkBindImageMemory` offset represents the start of the image, naturally the `pPlaneLayouts` offsets would be relative to this.

**Comment by oddhack** [comment]
@haasn closing since it sounds like the apparent ambiguity has been resolved.
