### ISSUE TITLE
Barrier VU references layout instead of usage

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1458]
>VUID-VkImageMemoryBarrier-srcQueueFamilyIndex-03938
If srcQueueFamilyIndex and dstQueueFamilyIndex define a queue family ownership transfer or oldLayout and newLayout define an image layout transition, and oldLayout or newLayout is VK_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL_KHR, image must have been created with VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT or VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL

last word should be `USAGE` bit instead.

**Comment by oddhack** [comment]
This should be fixed in the 1.2.171 spec update.
