### ISSUE TITLE
because because typo

### ISSUE THREAD

**Issue by trianglecube36** [KhronosGroup/Vulkan-Docs#146]
In section 18.3,
"For example, VK_FORMAT_R8G8B8A8_UNORM is compatible with VK_FORMAT_R32_UINT
because because both texels are 4 bytes in size. Depth/stencil formats must match exactly."
should be
For example, "VK_FORMAT_R8G8B8A8_UNORM is compatible with VK_FORMAT_R32_UINT
because both texels are 4 bytes in size. Depth/stencil formats must match exactly.".

**Comment by oddhack** [comment]
Thanks! I'll fix these in the next public update.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.7 spec update.
