### ISSUE TITLE
Clarification request on tessellation PatchVertices documentation

### ISSUE THREAD

**Issue by Venemo** [KhronosGroup/Vulkan-Docs#1461]
I'm reading the [spec about built-in variables](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap16.html#interfaces-builtin-variables) and specifically about `PatchVertices`.  
As far as I understand this is the equivalent of [gl_PatchVerticesIn in OpenGL](https://www.khronos.org/opengl/wiki/Built-in_Variable_(GLSL)#Tessellation_evaluation_shader_inputs).

## Is `PatchVertices` different or the same between TCS and TES?

The spec says:

> Decorating a variable with the `PatchVertices` built-in decoration will make that variable contain the number of vertices in the input patch being processed by the shader.

Can you please clarify what exactly *the number of vertices in the input patch being processed by the shader* means specifically for TCS and TES? Does it work like `gl_PatchVerticesIn` which in TES, is output patch size of the TCS?

I took a look at the CTS tests `dEQP-VK.tessellation.*` and I'm afraid there isn't a single one which uses `PatchVertices` in TES.

## How can a shader read patches of differing sizes?

I'd also appreciate some clarification about this:

> A single tessellation control or tessellation evaluation shader can read patches of differing sizes, so the value of the PatchVertices variable may differ between patches.

Does this mean that the same pipeline can contain patches of differing sizes? How is that possible? This would contradict what [the TCS spec says](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap10.html#shaders-tessellation-control). I think every input patch in the pipeline has the same size (according to the input patch size is set in `VkPipelineTessellationStateCreateInfo`), and also every output patch in the pipeline has the same size (set by the `OpExecutionMode OutputVertices` in either TCS or TES).

**Comment by gnl21** [comment]
> Is PatchVertices different or the same between TCS and TES?

My understanding is that yes, the `PatchVertices` variable is the equivalent of the GLSL builtin `gl_PatchVerticesIn`. I think "input patch" is referring to the input of that shader, rather than the whole pipeline, so in the TES the size of the input patch is the same as that output by the TCS. I agree that the spec text could be a bit clearer about that.

> I took a look at the CTS tests dEQP-VK.tessellation.* and I'm afraid there isn't a single one which uses PatchVertices in TES.

I'll create a CTS issue to look into whether there is any coverage of this and to create some if there is not.

> How can a shader read patches of differing sizes?

I think this has come from the GLSL definition and is a bit misleading in this context. I think that the idea is that a SPIR-V module containing this variable could be used in different pipelines, which might then have different patch sizes. The same SPIR-V code would see different patch sizes, but never from the same pipeline.

**Comment by Venemo** [comment]
Hello @gnl21 Thanks for the quick reply.

> I'll create a CTS issue to look into whether there is any coverage of this and to create some if there is not.

Sorry, this was my mistake. I now believe the reason why I didn't see it is because I was looking at the IR, rather than the input SPIR-V code of the shaders. It turns out that `PatchVertices` is constant-folded and optimized out before it reaches our compiler backend, and that's why I didn't see it.

> My understanding is that yes, the PatchVertices variable is the equivalent of the GLSL builtin gl_PatchVerticesIn. I think "input patch" is referring to the input of that shader, rather than the whole pipeline, so in the TES the size of the input patch is the same as that output by the TCS. I agree that the spec text could be a bit clearer about that.

Thanks.

> I think that the idea is that a SPIR-V module containing this variable could be used in different pipelines, which might then have different patch sizes.

Also, thanks.

Is it possible to change the text of `PatchVertices` to make it a little clearer? If such changes are welcome, I can submit a pull request with a suggested edit.

**Comment by gnl21** [comment]
> Is it possible to change the text of PatchVertices to make it a little clearer? If such changes are welcome, I can submit a pull request with a suggested edit.

Yes, I think making the text clearer is a good idea. Changes are certainly welcome, so if you're able to propose something then that would be great. Thanks.

**Comment by oddhack** [comment]
Closing this based on #1475 having been merged. If that's not correct then please reopen with a comment about what remains to be done.
