### ISSUE TITLE
Synchronization Example wrong/confusing

### ISSUE THREAD

**Issue by googlaboga** [KhronosGroup/Vulkan-Docs#1466]
The "First draw samples a texture in the fragment shader. Second draw writes to that texture as a color attachment." example in the new VK_KHR_synchronization2 section looks wrong? Or if it is not it could use some more explanation.
It specifies these stage masks:
```
  .srcStageMask = VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT_KHR,
  .dstStageMask = VK_PIPELINE_STAGE_2_VERTEX_SHADER_BIT_KHR,
```
Why is there a vertex shader stage? And why is it the dst stage?

The legacy synchronization example specifies these instead:
```
    VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,         // srcStageMask
    VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT, // dstStageMask
```

**Comment by Tobski** [comment]
Thanks for spotting this! I think this was just a copy+paste error, I've now made this example consistent with the sync1 example.
