### ISSUE TITLE
read-only storage images and image layout

### ISSUE THREAD

**Issue by konstantinegorov** [KhronosGroup/Vulkan-Docs#1471]
Why is it forbidden to use VK_IMAGE_LAYOUT_SHADER_READ_ONLY for read-only storage images (storage images with "readonly"  qualifier in glsl)? Is this a hardware limitation?

**Comment by sfricke-samsung** [comment]
If you really want a read only image, why not just use a `VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE` or get it into a `VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER`

Also as an edge case, if you have vert and frag shader that both use the storage image and the vert is `readonly` but the fragment is not and writes to it, how would you set the image layout to read only for only one stage.

**Comment by oddhack** [comment]
@konstantinegorov can this be closed based on @sfricke-samsung's response above?

**Comment by oddhack** [comment]
Closing. Please reopen with comment if there are points not addressed by @sfricke-samsung comment above.
