### ISSUE TITLE
Truly Bindless

### ISSUE THREAD

**Issue by Eichenherz** [KhronosGroup/Vulkan-Docs#1474]
Recently I discovered this extension : https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NVX_image_view_handle.html which allows for "OpenGL bindless" not just descriptor indexing.
But unfortunately it isn't available on my Pascal gtx 1050 mobile. And being nvidia only I'm sure AMD devs wouldn't mind at all having this functionality.  While it is an NV eXperimental it would be nice to have a VK_EXT some time soon.
Cheers !

**Comment by helixd-2k18** [comment]
Old no more actual discussions… 
https://community.khronos.org/t/bindless-textures/103941
https://community.khronos.org/t/vulkan-and-bindless/6758/13

**Comment by Tobski** [comment]
Thanks for raising this issue - as this is covered by #871, I'm going to close this as a duplicate, but it is probably worth reposting some of these comments onto that issue. We'll also post a small status update on that issue.
