### ISSUE TITLE
Queue transfer operation for VK_SHARING_MODE_CONCURRENT?

### ISSUE THREAD

**Issue by llatta** [KhronosGroup/Vulkan-Docs#1479]
In section [7.7.2 of the Vulkan spec](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#synchronization-buffer-memory-barriers) it says:

> If buffer was created with VK_SHARING_MODE_CONCURRENT, and srcQueueFamilyIndex is not equal to dstQueueFamilyIndex, this memory barrier defines a queue family transfer operation.

From other parts of the spec (eg [Queue Family Ownership Transfer](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#synchronization-queue-transfers)) I understood that queue family ownership is only something VK_SHARING_MODE_EXCLUSIVE needs, and not VK_SHARING_MODE_CONCURRENT.

Is this a typo in the spec, or why does this section explicitly highlight concurrent sharing mode vs exclusive?

Thanks!

**Comment by krOoze** [comment]
Yes, copy-paste error. Image barrier section says the same but `VK_SHARING_MODE_EXCLUSIVE`.

**Comment by HansKristian-Work** [comment]
It's also possible to transfer CONCURRENT <-> EXTERNAL, so the wording shouldn't refer to a queue family sharing mode at all I think. I'll look into fixing this.

**Comment by oddhack** [comment]
This should be fixed in the 1.2.175 spec update.
