### ISSUE TITLE
Primitive clipping of a sufficiently big polygon

### ISSUE THREAD

**Issue by kvark** [KhronosGroup/Vulkan-Docs#1480]
> If the primitive is a polygon, it passes unchanged if every one of its edges lie entirely inside the clip volume, and it is discarded if every one of its edges lie entirely outside the clip volume. If the edges of the polygon intersect the boundary of the clip volume, the intersecting edges are reconnected by new edges that lie along the boundary of the clip volume - in some cases requiring the introduction of new vertices into a polygon.

So it is saying, if I'm reading correctly, that a primitive with all the edges outside of my view frustum will be totally discarded? That doesn't sound right, since a big enough primitive would just cover the whole screen without having any of the edges intersecting the clip volume.

**Comment by oddhack** [comment]
This should be fixed in the 1.2.175 spec update.
