### ISSUE TITLE
Clipping produces value t based on the "original vertices"

### ISSUE THREAD

**Issue by kvark** [KhronosGroup/Vulkan-Docs#1481]
> This clipping produces a value, 0 ≤ t ≤ 1, for each clipped vertex. If the coordinates of a clipped vertex are P and the original vertices’ coordinates are P1 and P2, then t is given by:

It reads a little bit out of context. It doesn't explain what "original vertices" are.

**Comment by oddhack** [comment]
I have an old editorial note that this sentence says 't is given by', but the next equation actually gives P in terms of P1, P2, t, not t in terms of P1, P2, clip volume.

**Comment by oddhack** [comment]
This should be fixed in the 1.2.175 spec update.
