### ISSUE TITLE
Null miss shader support clarification

### ISSUE THREAD

**Issue by kennyalive** [KhronosGroup/Vulkan-Docs#1487]
It's not clear for me if specification allows to specify somehow null miss shader, i.e. to specify no-op when conditions to run miss shader are met. Is it supported in vulkan and if yes, which part of spec does explain this?

There is indirect hint that this might a real feature in the form of ```VK_PIPELINE_CREATE_RAY_TRACING_NO_NULL_MISS_SHADERS_BIT_KHR``` flag  which mentions null miss shader but I can't find corresponding confirmation in the specification and also did not succeed to enable this in practice by  providing ```VkStridedDeviceAddressRegionKHR``` object filled with zeros for miss SBT (tested on nvidia drivers).

**Comment by dgkoch** [comment]
Hi @kennyalive - I agree it's very non-obvious how this might work if it's permitted. Will have to discuss internally. 

> I also did not succeed to enable this in practice by providing VkStridedDeviceAddressRegionKHR object filled with zeros for miss SBT (tested on nvidia drivers).

What behaviour did you get in this case?

**Comment by kennyalive** [comment]
Device lost during vkQueueSubmit. No complains from validation layers.

**Comment by kennyalive** [comment]
It gets better but still wrong...

Initially I tested with game drivers 460.79 and had crash there in the situation described above.

I just updated to the latest 465.89 and indeed it does not crash when I provide zeroed SBT entry for miss.
But it still does not work correctly: the problem that even with zeroed miss SBT it still executes miss shader... My explanation to this is that driver looks for miss shader in the VkPipeline object and just picks up the first miss shader there, i.e. it ignores miss SBT.

I made a video to show this behavior: 
https://www.youtube.com/watch?v=cMoe0Qzkld4

If someone wants to play with demo itself, here's the project:
https://github.com/kennyalive/vulkan-raytracing

Works only on Windows. It can be built with Visual Studio 2017 (or 2019 after project conversion), all dependencies are included except VulkanSDK which should be installed locally. I still use 1.2.162.1 due to some bugs in validation layers in the latest 1.2.170.

The miss SBT entry is set up in raytrace_scene.cpp, line 48
The miss shader is in rt_mesh.rmiss.glsl file. For demo purposes I changed color to red to indicate region affected by miss shader.

**Comment by kennyalive** [comment]
Okay, I’ll try that tomorrow.

**Comment by kennyalive** [comment]
I tested approach with filling SBT buffer, it's the same behavior as with zeroing VkStridedDeviceAddressRegionKHR{} - driver still managed to find miss shader based on bound pipeline.

Here's the video:
https://youtu.be/skCqPAvH0mU

**Comment by kennyalive** [comment]
One more observation: 
If VkRayTracingPipelineCreateInfoKHR::pStages contain more than 1 miss shader, then behavior is correct - filling miss SBT buffer with zeros disables miss shader execution. But if VkRayTracingPipelineCreateInfoKHR::pStages contains exactly single miss shader then that miss shader will be used to handle miss events ignoring the content of the miss SBT buffer. 

That's mostly nvidia specific details, apologies for this, the following updates will be sent directy to nvidia vulkan support.

**Comment by kennyalive** [comment]
The issues is resolved, vulkan-support@nvidia.com helped to understand the issue. It was bug in my code - uninitialized payload variable when miss shader is disabled. 
@dgkoch, as you suggested, filling miss SBT buffer with zeros disables miss shader.
Still additional clarification in the specification are welcomed :)

**Comment by oddhack** [comment]
This should be fixed in the 1.2.180 spec update.
