### ISSUE TITLE
Impossible to render to 3D image slices

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/Vulkan-Docs#149]
Currently there is now way to render to 3D image slices.

OpenGL 4.5 and OpenGLES 3.1 are capable of this (e.g. glFramebufferTextureLayer), but as i understand the current specification, there is no valid way to render directly into slices of a 3D image.

**Comment by pdaniell-nv** [comment]
Today the Vulkan working group released new extension VK_KHR_maintenance1 (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_maintenance1) which adds support for rendering to a 3D slice. Conformant implementations will follow shortly. The latest Vulkan conformance 1.0.2.0 has test coverage for the new extension.
