### ISSUE TITLE
VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER with single-aspect zs images

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-Docs#1490]
According to the spec:
> The image subresources for VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR, a combined image sampler must be in the VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL, VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL, VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, or VK_IMAGE_LAYOUT_GENERAL layout in order to access its data in a shader.

Usually I try to use `VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL` for my zs images, but if I have a depth-only format like `VK_FORMAT_D16_UNORM`, this is illegal since there is no stencil aspect. It's also illegal to use `VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL` since this isn't in the above list.

This leaves only `VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL`, which isn't viable as a read-only renderpass attachment, forcing me to change layouts.

It seems to me like either `VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL` should be usable for single-aspected zs formats (which would make things much easier on the application side) or combined samplers should allow single-aspect read-only layouts.

**Comment by pdaniell-nv** [comment]
I think it was an oversight that VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL and VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL are not in this list. Also it should be valid to use VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL for both depth-only or stencil-only formats.

**Comment by pdaniell-nv** [comment]
A fix for the oversight is here: https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/4522. I believe VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL is already valid to use with depth-only or stencil-only formats.

**Comment by oddhack** [comment]
It appears a fix for this was commited to the spec repository about 7 months ago, but we neglected to close this tracking issue. Sorry!
