### ISSUE TITLE
Comments in XML

### ISSUE THREAD

**Issue by ParticlePeter** [KhronosGroup/Vulkan-Docs#1491]
While parsing vk.xml I noticed that some inconsistencies in the comment system:
1. Some of the comments in the XML seem to aimed for the XML spec only, e.g.:
`<comment>Types generated from corresponding enums tags below</comment`,
while others are quite useful and could end up in the vulkan headers, e.g.:
`<comment>Dimensions of a rectangle that has not changed, in pixels of a presentation images</comment>`.

2. Some are implemented as child nodes (see 1.) and others as node attributes:
`<enums name="API Constants" comment="Vulkan hardcoded constants - ...">`

3. For the latter case of 2. they seem to be always strings (as opposed to text), but then few of them are already prefixed with "// ", e,g,:  `comment="// Union of all the possible return types a counter result could return">`

4. Assuming that the string comments are meant to end up in generated code, some of the helpful comments for code (second of 1.) are not strings. 

Looking into vulkan_core.h, I find almost none of them, why is that?
Is there a system behind all these different comment occurrences?
Is there a way to define a more uniform usage?

E.g.:
1. XML tag <xml_comment> for comments meant for only the vk.xml
2. Comments as either attributes or child nodes, not both.
3. Comments as either strings or text, not both
4. Comments are not to be prefixed with "// "

**Comment by oddhack** [comment]
There isn't a system behind them, they were just put in where various people thought they were relevant. Probably some of those people didn't realize at the time that the comment fields aren't propagated to the headers.

At present we don't have any intent to put them into the headers; if we started down that path they would need to be systematized and that's a great deal of work. If there were a lot of demonstrated demand from developers we would consider it, but only then.

**Comment by ParticlePeter** [comment]
That's too bad, as said above, I think they are useful, in particular as spec memory support. But I also don't know how many people use the headers to look stuff up, instead of going directly to the spec (I do).
Would you maybe consider to add it in one of your future surveys?

**Comment by oddhack** [comment]
We're asking the Vulkan developer relations folks to take a look at the demand for this. I don't know how long it might take for them to give some guidance, but it won't be in the immediate future.

**Comment by oddhack** [comment]
Closing this on the basis that we never got feedback from the devrel folks about this, which suggests the interest is very limited.
