### ISSUE TITLE
Storage image format should not be part of the shader

### ISSUE THREAD

**Issue by DadSchoorse** [KhronosGroup/Vulkan-Docs#1492]
Without `storageImageWriteWithoutFormat` and `storageImageReadWithoutFormat` the format of a storage image must be specified in shader e.g. :
```glsl
layout(set=0, binding=1, rgba8) uniform image2D storageImage;
```
The exact format is pretty much irrelevant for the shader itself, in this case the `rgba8` could be replaced by any other floating point format (e.g. `rgba16`, `rgba16f`, `rgba32f`, ...). 

The other problem with storage image formats in shaders is that there are no spirv formats for most vulkan formats. For example it's not possible to have a `VK_FORMAT_R4G4B4A4_UNORM_PACK16` storage image. `storageImageWriteWithoutFormat` and `storageImageReadWithoutFormat` provide a dirty workaround for that, but at the expense of information for optimization.

The requirement of specifying the format in spirv should be removed. Instead the application could provide the exact vulkan format for each image in `VkComputePipelineCreateInfo`/`VkGraphicsPipelineCreateInfo`. That provides the same information to the driver and avoids having to create separate spirv blobs for pipelines which only differ in storage image formats. At the same time usable storage image formats are no longer blocked by the limited amount of spirv formats.

**Comment by HansKristian-Work** [comment]
This came up in the call yesterday. There wasn't much enthusiasm for adding yet another way to specify formats. Some things to consider are:

- Explicit format in shader is somewhat of a legacy compromise and it's something we expect to become less relevant over time. Reintroducing another orthogonal way now to specify formats seems counter productive.
- Generally, application authors can avoid using esoteric formats for storage images. The main case where this comes up at all is BGRA8 swapchains where there is less flexibility w.r.t. format selection.
- WriteWithoutFormat tends to be well supported, with ReadWithoutFormat being not universal. However, for reading scenarios it's usually possible to use normal textures. imageLoad() is only strictly required for coherent sampling inside a dispatch.
- If alternatives are not possible, descriptor aliasing, MUTABLE_FORMAT and specialization constants can be used to handle any format.

A workaround could look something like:
```
layout(set = 0, binding = 0, r32ui) uniform uimage2D Image32;
layout(set = 0, binding = 0, r16ui) uniform uimage2D Image16;
layout(constant_id = 0) const uint FMT = 0;

if (FMT == TYPE_MY_ESTOERIC_32_FMT) { Pack to something r32ui and load/store }
else if (FMT == TYPE_MY_ESOTERIC_16_FMT) { Pack to something r16ui and load/store }
```

**Comment by DadSchoorse** [comment]
Thanks for the answer! My main use case (low bits per channel formats for scanout in my pet compute only compositor) is definitely covered by the last part, and I guess in the future everything will hopefully support Read/WriteWithoutFormat.
