### ISSUE TITLE
Minimum ComputeWorkGroupSize (clarification needed)

### ISSUE THREAD

**Issue by daniel-schuermann** [KhronosGroup/Vulkan-Docs#1493]
I wanted to ask whether we could clarify if the minimum workgroup size should be `{ 0, 0, 0 }` or `{ 1, 1, 1 }`.
As far as I can see, the spec only demands respecting maxComputeWorkGroupSize.

What would be the expected behavior from the driver? (silent drop/warning/error)
As far as I'm aware of, no application is affected, but our driver crashes in this case, so I'd like to resolve that properly.

Thanks,
Daniel

(for reference: https://gitlab.freedesktop.org/mesa/mesa/-/issues/4591)

**Comment by sfricke-samsung** [comment]
So looking at the spir-v shader from the MESA issue, That is not valid SPIR-V (if you use `spirv-val --target-env vulkan1.2`)

> VUID-StandaloneSpirv-LocalSize-04683
For each compute shader entry point, either a LocalSize execution mode or an object decorated with the WorkgroupSize decoration must be specified

But assuming you have `OpExecutionMode %main LocalSize 0 0 0` to make it "legal"  still a good question (as I can't find language in Vulkan or SPIR-V spec saying anything for or against it... also nothing I can find in CTS or validation coverage)

**Comment by sfricke-samsung** [comment]
We agreed in the working group today that a static `LocalSize 0 0 0` should be invalid (making a `1,1,1` min). Going to first see if this should just be a SPIR-V validation, if not, will make it a Vulkan VU

**Comment by daniel-schuermann** [comment]
Thanks, that would also be my preferred solution.

**Comment by sfricke-samsung** [comment]
Sorry never got back to this, but a while ago we did actually add this to the SPIR-V 1.5.5 spec

> #651: Add a validation rule that the workgroup size cannot have a dimension with the value zero statically.
>
> If the workgroup size is statically specified (using the LocalSize, LocalSizeId execution modes, or the WorkgroupSize BuiltIn), the product of all workgroup size dimensions must not be zero.
