### ISSUE TITLE
Avoid usages of "type" for name

### ISSUE THREAD

**Issue by buzmeg** [KhronosGroup/Vulkan-Docs#1494]
The word "type" is a restricted keyword in many languages, but unfortunately is part of some Vulkan structs.  This makes bindings on alternate languages have to come up with problematic workarounds.

see:
VkDescriptorPoolSize
VkPhysicalDeviceImageFormatInfo2
VkPhysicalDeviceSparseImageFormatInfo2

And it has a tendency to be in experimental extensions:
VkObjectTableEntryNVX
VkObjectTablePipelineEntryNVX
VkObjectTableDescriptorSetEntryNVX
VkObjectTableVertexBufferEntryNVX

It would be nice to provide "new" structs/functions that are precisely equivalent to the old ones in order to avoid this issue, but, at the very least, please avoid creating new entities with the keyword "type" in them (it is particularly unfortunate that VkPhysicalDeviceImageFormatInfo2 and VkPhysicalDeviceSparseImageFormatInfo2 fell into this).

Thanks.

**Comment by nanokatze** [comment]
Many languages' FFI mechanisms deal with this issue on regular basis. Some examples:
Rust: https://github.com/WizardOfArc/rust-bindgen/blob/4a3eec8c4f996b78a1f7ae4ff8fee06bebd963b6/src/ir/context.rs#L851
Go:
>  Within the Go file, C's struct field names that are keywords in Go can be accessed by prefixing them with an underscore: if x points at a C struct with a field named "type", x._type accesses the field. C struct fields that cannot be expressed in Go, such as bit fields or misaligned data, are omitted in the Go struct, replaced by appropriate padding to reach the next field or the end of the struct. 

What exactly would "avoid creating new entries with the keyword "type" in them" solve? You already have to deal with reserved keyword use in the types you mention. Moreover, why would `type` alone get special treatment? What about `module`, which is a member of VkPipelineShaderStageCreateInfo but also happens to be a keyword in at least Pascal and TypeScript? Or `range`, which is what members of VkBufferViewCreateInfo and VkDescriptorBufferInfo are called, but is a reserved keyword in Go?

**Comment by buzmeg** [comment]
Just because the FFI's deal with this (with varying levels of awfulness) does not mean this is ideal.

> What about module, which is a member of VkPipelineShaderStageCreateInfo but also happens to be a keyword in at least Pascal and TypeScript? Or range, which is what members of VkBufferViewCreateInfo and VkDescriptorBufferInfo are called, but is a reserved keyword in Go?

Agreed.  Those should probably get similar treatment.  And, I believe "module" is a keyword in C++ even though it hasn't been used.

Why call it a pName in VkPipelineShaderStageCreateInfo when in C everybody would simple think "name" as all strings are always effectively pointers/arrays?  The fact that there are so few of these collisions shows that the people who originally put the Vulkan API together went out of their way to avoid some collisions with this kind of thing by choosing to name things appropriately (sType or pNext, for instance.)

Since Vulkan is the origination upstream, a little consideration for the downstream helps everybody.

**Comment by oddhack** [comment]
There are, roughly, 150 member / parameter names in the API at present that might collide with some language's keywords (excluding camelCase). There are lots of languages with lots of reserved words. While we might be willing to entertain a small exclusion list backed by explanations of what languages are affected, this isn't something we can retroactively fix nor that we can guarantee will never happen in the future with languages evolving all the time.  I'll run it by the working group to see if there's appetite for a small exclusion list, but we're really going to want concrete evidence of problems affecting a lot of developers.

Keyword list attached.
[names.txt](https://github.com/KhronosGroup/Vulkan-Docs/files/6334893/names.txt)

**Comment by buzmeg** [comment]
Thanks.  I realize that this one can't be cleaned up.

However, simply making sure that future member/parameter names are camelCase or StudlyCaps solves 99% of the problem, no?

I'm struggling to come up with a "reserved word" that has a mixed case.

**Comment by oddhack** [comment]
It would solve it(*) for all the parameter names that aren't a single word, but not all of them are.

(*) Assuming there isn't going to be some language with case-insensitive keywords.

**Comment by oddhack** [comment]
@buzmeg if you've got a specific keyword list to look at, we'll consider it, but otherwise please close this. We're not going to constrain ourselves to the extent of not using any possible keyword in any language.

**Comment by buzmeg** [comment]
I'm fine with closing this out.  I've said my piece, and Vulkan folks can help the downstream or not as they choose.

However, I am going to flag this:

> Assuming there isn't going to be some language with case-insensitive keywords

Sorry, case insensitivity is a relic of ASCII-only and is dead and buried with Unicode support.  There is no unique mapping between upper and lower case in Unicode and sometimes there are even multiple ways to form the same lower-case glyph (which generally read as non-equivalent in code).
