### ISSUE TITLE
Canonicalize "const" to right hand side CDATA

### ISSUE THREAD

**Issue by buzmeg** [KhronosGroup/Vulkan-Docs#1495]
While there has been some discussion about moving pointers to an attribute (see #930), it would be helpful for parsing for starters to at least cause "const" and "*" to always be on the right hand side CDATA entry:

ie The XML currently has:

'''const void * pNext;'''  (which is actually slightly confusing)
'''\<member\>const \<type\>void\</type\>*            \<name\>pNext\</name\>\</member\>'''
but
'''void const * pNext;'''
'''\<member\>\<type\>void\</type\>const *             \<name\>pNext\</name\>\</member\>'''
works fine in C.

Or, take something like:
'''const uint8_t * const foo;'''
'''\<member\>const \<type\>uint8_t\</type\>* const            \<name\>foo\</name\>\</member\>'''
while it is perfectly equivalent C to write:
'''uint8_t const * const foo;'''
'''\<member\>\<type\>uint8_t\</type\>const * const            \<name\>foo\</name\>\</member\>'''

This means that you only have to look at a single CDATA to determine all the const and pointerness of the entity instead of having to grab the CDATA of something like "const struct", hold it through the parsing until you hit the name, then the pointer CDATA, and then reassemble everything in the correct order.

The advantage here is that the XML gets easier to parse while the C stays completely semantically equivalent.

Thanks.

**Comment by oddhack** [comment]
Stripping tags from the member/parameter declarations is exactly how our own generator scripts function, so we haven't thought of this as a big obstacle for downstream generators.

**Comment by buzmeg** [comment]
Um, exactly?

The fact that people (like me) continue to write their own parsers instead of being able to easily slightly modify the repository scripts demonstrates that the parser and xml is far too intricately interwoven with the notion that it is always generating C header files.

As for downstream, you could release the Vulkan description as a base-64 blob, and those of us downstream would somehow make it work--so you can't particularly draw conclusions from the fact that we *can* make it work.

**Comment by Lokathor** [comment]
Yeah, I know that it's an API using the C ABI and all, but having the XML not assume that C is the only language in the world is a good long term plan.

There's more and more up and coming languages that aren't C, and making the XML easy to parse and conceptually clear without directly referring to C stuff lets each group convert the concepts to their own language in the way that fits them best.

**Comment by buzmeg** [comment]
A good thought experiment is "Can I suck in the XML with {xml2dict, xml2json, xml2yaml, etc.} and then spit it out into a language wrapper with a "templating engine" (or similar tool) without having to write too much parsing code?"

If that can be done, then the description has a "cohesive model" that it mostly comports with.

The fact that "validitygenerator.py", for example, takes 1500 lines *in addition to* the 1200 of "generator.py" suggests ... otherwise.

**Comment by oddhack** [comment]
I'm sorry this isn't working for you. We discussed it and are not willing to create that amount of churn for so little benefit.

We have never had a goal to create a language-independent description of the Vulkan API in vk.xml. That's explicit in the introduction of the registry schema document:

> The cost is that people writing output generators for other languages will have to include enough logic to parse the C declarations and extract the relevant information.

Sometimes this causes friction with folks like yourself. If the XML is helpful to people doing other language bindings, that's great, and if someone wants to write a schema converter that generates a more neutral description for other people to consume, also great. I think someone actually did this a few years ago, but it didn't seem to get enough buy-in to turn into an ongoing project, unless I missed something.
