### ISSUE TITLE
Typo(s) with VkSemaphoreSubmitInfoKHR::stageMask

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1498]
`VkSemaphoreSubmitInfoKHR::stageMask` seem to be referred to as `stage` at at least two places.

**Comment by sfricke-samsung** [comment]
Could you please list the 2 spots you are seeing it being referred to as `stage`?

**Comment by krOoze** [comment]
The point was kinda not to tell to be sure whoever fixes it actually does the work and fulltext searches for it to catch all the occurences. Nvm, I will PR it then...
