### ISSUE TITLE
[enhancement] Errors chapter should be split

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1499]
The Errors chapter should be split into valid usage, and return codes. I always look for error codes and then have to scroll over bunch of structure type definitions. Plus the chapter name is not really descriptive.

**Comment by oddhack** [comment]
Point taken, though not clear what to do with the introductory paragraph in that case. I'm thinking renaming the section something more encompassing of both validation and success/failure signalling, and renaming "Return Codes" -> "Return Codes and Error Codes" would be simpler.

**Comment by krOoze** [comment]
I think it is too smart to think of both as errors. Yea, technically one are sorta logical errors, and the other are runtime errors. But a reader going to the chapter is usualy not interested in both topics. If someone looks for return codes, he is unlikely to be also interested in validation. My goal here is they both appear as separate chapter in the table of contents for easier navigation.

So I would think split into "3.7 Valid Usage", and "3.8 `VkResult` Return Codes".

As for introductory paragraph, it seems everything there belongs to Valid Usage, and does not talk about anything related to `VkResult`, so Return Codes could be just split with no additional work than the chapter rename.

`VkStructureType` is generally bit annoying being there inline. I would be tempted to take it an put it into an Appendix (perhaps with other meta stuff like `VkObjectType`). Or possibly at the end of 3.10. Common Object Types.

BTW, there's "Provided by VK_VERSION_1_0, VK_VERSION_1_0" on `VkStructureType`. Some kind of script glitch...
