### ISSUE TITLE
StdVideoH264ProfileIdc has no definition in XML file

### ISSUE THREAD

**Issue by buzmeg** [KhronosGroup/Vulkan-Docs#1505]
StdVideoH264ProfileIdc (and associated) has no definition in the XML file.

Please convert to a handle or provide a definition.

Thanks.

**Comment by oddhack** [comment]
By "and associated" do you mean everything in the vk_video/ static headers, or just the enumerated types?

**Comment by buzmeg** [comment]
Well, the H265 versions, at minimum, likely have the same issue, no?

I suspect there are only a couple of base definitions that need to be fixed (maybe only two?) and everything else just ripples forward properly.

My use case is using the XML to parse for an FFI to a different language.  As I'm not currently using these APIs, I simply commented out anything having to do with the H264/H265 interfaces.

Consequently, I haven't done a detailed analysis.  Sorry.

**Comment by MaikKlein** [comment]
We ran into the same issue. A lot of types are not defined in the xml. From a quick glance, all of those types are annotated with `<type requires="vk_video/vulkan_video_codec_*.h"`

Is that an intended change? I know it is only a provisional extension but that forces us to parse c headers.

**Comment by oddhack** [comment]
> Is that an intended change? I know it is only a provisional extension but that forces us to parse c headers.

I'm checking with the subgroup that developed the extensions.

**Comment by zlatinski** [comment]
These are all external header files targeting the h.254/5 standard. We do not have plans to generate XML files for these standard tokens. The std files must be explicitly included with the rest of the platform-specific files.

**Comment by buzmeg** [comment]
Why are these included *by value* (directly in the struct) rather than *by reference* (behind a handle/ptr)?

Does this mean a change in the H264/H265 system can cause my Vulkan structs to change size?

Isn't this a huge break with the "standard" ways of interacting with the Vulkan API.

This feels like it needs more time in the working group.

**Comment by oddhack** [comment]
I believe all the Std*Idc types that are included by value are enumerants, while the other Std* structures are all passed by pointer. Either way language bindings do need access to define the Std* APIs themselves, of course. The Video TSG is aware of the issue and will be discussing it this week. It is a provisional extension and can easily change.

**Comment by oddhack** [comment]
Still being discussed. It is likely but not certain we will create an auxiliary video.xml from which the video headers will be constructed. That they are "sideband" is probably not going to change, however.

**Comment by buzmeg** [comment]
That doesn't fix the fundamental problem.

The fundamental problem is that Vulkan is binding to a particular video implementation instead of it being a generic interface that any video provider can implement.

At the very least, did anybody go get some feedback on the video extensions from the *gaming* development community?  You know, the bunch that with lots of video assets but *won't actually run H.264 video*?  Perhaps they might like to be able to use their video codecs (some of which are proprietary) with a Vulkan video extension?

Vulkan went through this back at the beginning with the explicit renderpasses/subpasses abstraction in order to unify desktop/mobile (how to help tiling renderers without penalizing desktop performance).  Vulkan folks are smart enough to go cough up an abstraction that suits the mobile video guys (who want to access their hardware encoder/decoders), the gaming video guys (who want storage compaction with fast decompression), and the desktop video guys (who might want to build a new encoder/decoder through the compute pipeline).

**Comment by Jasper-Bekkers** [comment]
@oddhack Checked the discussion - video.xml seems like a good solution for our usecase, esp with all the other constraints involved thanks :-)

**Comment by Jasper-Bekkers** [comment]
> The fundamental problem is that Vulkan is binding to a particular video implementation instead of it being a generic interface that any video provider can implement.

That's not actually true: https://www.khronos.org/blog/an-introduction-to-vulkan-video

**Comment by buzmeg** [comment]
Okay, I took a much stronger look at the deep dive on the video stuff.

I see where this is coming from, but I still think the implementation level is going to lead to collisions.  I would feel a lot better about the abstraction level if there was an example of say ... using the extensions to decode some older much simpler format (like MP2?) via the compute resources on the graphics card.

However, at this point, I'm bikeshedding, and I should shut up.  I don't have a dog in this fight after the video stuff got moved to a separate XML file.

Thanks.  And you can close the issue from my point of view.
