### ISSUE TITLE
Special Use breaks Contact rendering in extension manual page

### ISSUE THREAD

**Issue by DadSchoorse** [KhronosGroup/Vulkan-Docs#1518]
1: visit https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_transform_feedback.html (or the page of any other extension with special usages)
2:  notice the broken `== Contact`
![grafik](https://user-images.githubusercontent.com/49841484/116593399-56c99b00-a921-11eb-964e-e272a658b324.png)

**Comment by oddhack** [comment]
Thanks. There will be a fix for this in the next public spec update, in a week or two.
