### ISSUE TITLE
Problem with Vulkan spec PDF version 1.2.178

### ISSUE THREAD

**Issue by IAmNotHanni** [KhronosGroup/Vulkan-Docs#1530]
Hi

if I search for "Vulkan spec PDF", I find this link: https://www.khronos.org/registry/vulkan/specs/1.2/pdf/vkspec.pdf
There seems to be something wrong with that PDF. It is full of unresolved anchors, for example

> pNext is NULL or a pointer to a structure extending this structure. :anchor-prefix: extension-

> [[{anchor-prefix}limits-subgroup-size]] subgroupSize is the default number of invocations in
each subgroup. subgroupSize is at least 1 if any of the physical device’s queues support
VK_QUEUE_GRAPHICS_BIT or VK_QUEUE_COMPUTE_BIT. subgroupSize is a power-of-two.

I'm sure that's not correct.
Sry I didn't know where else to drop this.

best regards
Johannes

**Comment by krOoze** [comment]
It's in the HTML too...

**Comment by oddhack** [comment]
> Hi
> 
> if I search for "Vulkan spec PDF", I find this link: https://www.khronos.org/registry/vulkan/specs/1.2/pdf/vkspec.pdf
> There seems to be something wrong with that PDF. It is full of unresolved anchors, for example
> 
> > pNext is NULL or a pointer to a structure extending this structure. :anchor-prefix: extension-
> 
> > [[{anchor-prefix}limits-subgroup-size]] subgroupSize is the default number of invocations in
> > each subgroup. subgroupSize is at least 1 if any of the physical device’s queues support
> > VK_QUEUE_GRAPHICS_BIT or VK_QUEUE_COMPUTE_BIT. subgroupSize is a power-of-two.
> 
> I'm sure that's not correct.
> Sry I didn't know where else to drop this.
> 
> best regards
> Johannes

Thanks, Johannes. I did some overzealout whitespace removal in the last spec update resulting in asciidoctor markup making its way through to the text. Will be fixed in the next spec update.

**Comment by oddhack** [comment]
This should be fixed in the 1.2.179 spec update.
