### ISSUE TITLE
VK video enum variant names do not share a common prefix with the type

### ISSUE THREAD

**Issue by MarijnS95** [KhronosGroup/Vulkan-Docs#1531]
`VK_VIDEO_DECODE_H264_PROGRESSIVE_PICTURES_ONLY_EXT` should be called `VK_VIDEO_DECODE_H264_FIELD_LAYOUT_PROGRESSIVE_PICTURES_ONLY_EXT` (notice missing `_FIELD_LAYOUT` in the current name) just like the rest of the enum variants, so that it has a common prefix with `VkVideoDecodeH264FieldLayoutFlagBitsEXT`.

Likewise, `VK_VIDEO_ENCODE_H264_CAPABILITY_*` variants should use plural `CAPABILITIES_` in the name so that it has a common prefix with its enum type name `VkVideoEncodeH264CapabilitiesFlagBitsEXT` again.

**Comment by oddhack** [comment]
We'll ask the Video subgroup to take a look at this.

**Comment by MarijnS95** [comment]
It appears both issues were fixed in `.187`:

```markdown
  * Fix a few enumerant and member names in the provisional video extensions
    to comply with the spec style guidelinse (internal issue 2710).
```

**Comment by MarijnS95** [comment]
@oddhack Just letting you know so that you can set up this internal association after the fact. I won't judge whether the external or internal issue was first :wink:
