### ISSUE TITLE
Video extensions contains images that are disguised PNG

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1537]
Video extensions spec contains images that are PNGs disguised as SVG. For one it is conceivable they are larger than pure optimized SVG images would have been, increasing the spec size unnecesserily. Secondly, it does not seem to work well in PDF, and the parts that are supposed to be transparent are rendered as black.

**Comment by oddhack** [comment]
We're aware of that. The Video people think the artifacts are acceptable and don't want to make new SVGs at present. Unfortunately the asciidoctor-pdf toolchain does not support some common SVG tags like \<mask>, so really nothing to be done about this unless someone else volunteers to re-do the artwork.

**Comment by oddhack** [comment]
For this spec update, I removed the \<mask> tags in order to suppress the numerous warnings from the PDF build. @fluppeteer has expressed some willingness to update the SVGs to replace the mask tags with supported constructs.

**Comment by krOoze** [comment]
Right. Cosider remaking in pure SVG. If every extension added 1 MB of images in base64 PNG, then the spec would have like 200 MB. I don't think this is something where "the authors found it acceptable" is applicable (of course they did, because it means less work for them). They should just follow the styleguide as everyone else, and use actual svg as it prescribes...

**Comment by oddhack** [comment]
Should be fixed in the 1.2.186 spec update.
