### ISSUE TITLE
Use mathit in latexmath for multi-character symbols

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#154]
Compare:

![maths-pdf](https://cloud.githubusercontent.com/assets/131713/14060254/8bfacb0e-f356-11e5-976c-64e4149bac73.png)

The top half is what the spec currently produces. The bottom part is what you get after adding `\mathit{...}` around all the multi-character symbols.

See in particular the "undefined" and "Op". The top version is quite ugly, the bottom version looks much better.

The problem is that LaTeX interprets `$abc$` as the product of variables _a_, _b_, and _c_, so it increases the letter spacing compared to normal text. It's especially noticeable on _f_ which gets even larger spacing (which I vaguely remember hearing is so that `$fx$` looks like the function _f_ applied to _x_, though I can't find any references for that now). `\mathit` tells it to format the text more like a single word instead.

The image above is from the PDF version, but the same issue is visible in the HTML version, e.g. as rendered by Chrome:

![maths-chrome](https://cloud.githubusercontent.com/assets/131713/14060259/9e2f70f4-f356-11e5-8f81-4e4c65e1edbc.png)

The spec should be fixed to use `\mathit` where appropriate in all its `latexmath` blocks. Or at least it should be added to the style guide to encourage the correct usage in future updates, and don't bother fixing all of the current spec until someone with enough time on their hands provides a patch.

(I may have spent too many years reading and writing LaTeX, so this kind of thing offends me greatly. And don't get me started on sentence-spacing in e.g. `Blah blah OpenGL. Blah blah` vs `Blah blah OpenGL\@. Blah blah`...)

**Comment by oddhack** [comment]
I'll take it under advisement as a background task, but don't expect a lot of fixes in the near term.

**Comment by oddhack** [comment]
We have largely, though not entirely moved away from MathJax / latexmath in the 1.0.29 spec update, mostly to increase XHTML loading speed. So the layout issues are different and there are some new font problems related to that, which I'm working on as another background task.

**Comment by oddhack** [comment]
Closing this. There are some known issues in KaTeX layout which are still affecting prettyfication of equations but are outside our control, and most of the \mathit issues have been addressed separately. There are doubtless lingering ones but we'd rather see a new issue opened specifically identifying them than keep this open indefinitely.
