### ISSUE TITLE
Should `vk_video/` headers be moved to `vulkan/video/`?

### ISSUE THREAD

**Issue by MarijnS95** [KhronosGroup/Vulkan-Docs#1541]
https://github.com/KhronosGroup/Vulkan-Docs/pull/1538#issuecomment-850016405:

All the other headers sit under the `vulkan` header too, it's odd to have the Video headers live outside that while still sharing a `vk_` prefix.

**Comment by zlatinski** [comment]
The video standard's header files are intentially placed outside the Vulkan's headers NS. There are at least two reasons for that:
1. IP separation. For example: MPEG vs. Khronos;
2. There should't be any code dependency of the standard video headers on Vulkan;

**Comment by MarijnS95** [comment]
Note that the video headers currently implicitly depend on `vk_platform.h` to pull in `<stdint.h>` or the `VK_NO_STDINT_H` fallbacks.
It's a bit strange to use a `vk_` prefix for that next to the `vulkan/` folder, would it make sense to move it in a separate directory inside `vulkan/`, indicating these headers are definitely specific to Vulkan (otherwise, why carry a `vk_` prefix?) but not under the same IP?

**Comment by zlatinski** [comment]
> otherwise, why carry a vk_ prefix?

These codec std header files are created by the Vulkan Video TSG and, currently, maintained by the same group. However, those header files are not covered by the same Khronos IP licensing (protection).

**Comment by krOoze** [comment]
I mean, the headers do have Khronos copyright, and Apache licence. There's nothing to protect,.

**Comment by neiltrevett** [comment]
Yes - agree with @krOoze above, The headers are outside the IP framework - which applies only to specifications.
