### ISSUE TITLE
[Specification] Request for clarification on timeline semaphore values

### ISSUE THREAD

**Issue by DethRaid** [KhronosGroup/Vulkan-Docs#1545]
I submit my command lists with a couple signal semaphores - some are timeline semaphores, some are not

If I put all the timeline semaphores at the beginning of the `pSignalSemaphores` array in my `VkSubmitInfo`, and the non-timeline semaphores at the end, do I need to supply values for every single semaphore in my `VkTimelineSemaphoreSubmitInfo`? Or do I only need to supply values for the timeline semaphores?

The spec implies the former, but it's not very clear to me

**Comment by sfricke-samsung** [comment]
So if you have a case where you have

```cpp
VkSemaphore binary_a;
VkSemaphore binary_b;
VkSemaphore timeline_a;
VkSemaphore timeline_b;

VkTimelineSemaphoreSubmitInfo timelineInfo;
timelineInfo.signalSemaphoreValueCount = 4; // VU forces to match signalSemaphoreCount
timelineInfo.pSignalSemaphoreValues = [6, 7, 8, 9];

VkSubmitInfo submitInfo;
submitInfo.pNext = &timelineInfo;
submitInfo.signalSemaphoreCount = 4;
submitInfo.pSignalSemaphores = [binary_a, timeline_a, binary_b, timeline_b];
```

The spec says

> If the semaphore in VkSubmitInfo::pWaitSemaphores or **VkSubmitInfo::pSignalSemaphores** corresponding to an entry in pWaitSemaphoreValues or **pSignalSemaphoreValues** respectively was **not created** with a VkSemaphoreType of **VK_SEMAPHORE_TYPE_TIMELINE**, the implementation **must ignore the value** in the pWaitSemaphoreValues or **pSignalSemaphoreValues** entry.

Which would basically give you

```cpp
timelineInfo.pSignalSemaphoreValues = [ignored, 7, ignored, 9];
```

> The spec implies the former, but it's not very clear to me

(granted finding the exact sentence in the spec is never easy) I hope the quote text is clear and you also think explicitly states the former

**Comment by DethRaid** [comment]
My case is more like
```cpp
VkSemaphore binary_a;
VkSemaphore binary_b;
VkSemaphore timeline_a;
VkSemaphore timeline_b;

VkTimelineSemaphoreSubmitInfo timelineInfo;
timelineInfo.signalSemaphoreValueCount = 4; // VU forces to match signalSemaphoreCount
timelineInfo.pSignalSemaphoreValues = [6, 7, 8, 9];

VkSubmitInfo submitInfo;
submitInfo.pNext = &timelineInfo;
submitInfo.signalSemaphoreCount = 4;
submitInfo.pSignalSemaphores = [timeline_a, timeline_b, binary_a, binary_b];
```
Which gives me
```cpp
timelineInfo.pSignalSemaphoreValues = [6, 7, ignored, ignored];
```

**Comment by sfricke-samsung** [comment]
So 

```
timelineInfo.pSignalSemaphoreValues = [6, 7, ignored, ignored];
```

is correct idea, the main thing is the `uint64_t` array you hand off to `pSignalSemaphoreValues` is of size `signalSemaphoreValueCount` 

Even though the values are ignored, a driver/layer still might loop each item so "something" valid needs to be there in memory

**Comment by llandwerlin-intel** [comment]
@sfricke-samsung is correct. I can provide the Intel/Mesa example : 

- For signal binary semaphore, we will ignore the value completely : https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/intel/vulkan/anv_queue.c#L1084
- Same for wait binary semaphores : https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/intel/vulkan/anv_queue.c#L994

**Comment by sfricke-samsung** [comment]
Going to close issue for now, if there is a suggestion on how to make the spec language more clear, happy to reopen and discuss
