### ISSUE TITLE
Clarify how VK_WHOLE_SIZE works with dynamic offset

### ISSUE THREAD

**Issue by sfricke-samsung** [KhronosGroup/Vulkan-Docs#1546]
From https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2846

The phrase `effective range` in the spec in currently not clear and ambiguous

Need to make more clear that how the end point of a buffer's range is baked into the descriptor on some GPUs

**Comment by oddhack** [comment]
@sfricke-samsung did this get an internal tracker? I can't find one.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.211 spec update.
