### ISSUE TITLE
Is it allowed to wait and signal the same semaphore?

### ISSUE THREAD

**Issue by tomaka** [KhronosGroup/Vulkan-Docs#155]
When you call `vkQueueSubmit`, is it allowed to pass a `VkSubmitInfo` that has the same semaphore object in both `pWaitSemaphores` and `pSignalSemaphores`?

The specs only say this, which doesn't answer the question:

> Any given element of pSignalSemaphores must currently be unsignalled 
> Any given element of VkSemaphore in pWaitSemaphores must refer to a prior signal of that VkSemaphore that won’t be consumed by any other wait on that semaphore 
> The application must ensure that command buffer submissions will be able to complete without any subsequent operations by the application on any queue. After any call to vkQueueSubmit, for every queued wait on a semaphore there must be a prior signal of that semaphore that won’t be consumed by a different wait on the semaphore.

Whether it's allowed or forbidden, I think that in both cases it would be a good idea to mention it explicitly.

**Comment by tomaka** [comment]
Related question: what does `currently` mean here?

> Any given element of pSignalSemaphores must currently be unsignalled 

Does it mean "when the queue reaches that command buffer" (which would be the logical thing), or "when you call vkQueueSubmit" (which is the literal interpretation of this sentence)?

**Comment by oddhack** [comment]
This should be addressed in the 1.0.18 spec update. A lot of related changes were made in the queue and synchronization sections as well.
