### ISSUE TITLE
[enhancement] In case of C++, put [[nodiscard]] on VkResult?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1550]
Gonna be kinda annoying with the compiler warnings, but then again runtime errors should always be checked.

**Comment by r-potter** [comment]
Discussed in the WG today, and opted not to make this change.

Whilst checking `VkResult` return values is clearly best practice, enforcing this via the compiler carries a high risk of breaking existing downstream application builds. If we made this change then any build/CI setup that treats warnings as errors would begin failing as the result of a minor header update.

If we were designing the API from scratch today, and there wasn't an existing body of code that needs to continue to build, then we might have reached a different decision.

**Comment by krOoze** [comment]
Then again if it fails to build, it possibly prevented some undefined behavior on runtime.

Anyway, what about making it an opt-in feature?

**Comment by r-potter** [comment]
We discussed that as well and opted against it. It adds a future set of permutations that have to be tested, and introduces a difference in behaviour between C99/older C++ compilers and those which support C++17.

**Comment by oddhack** [comment]
Closing per @r_potter's comments.
