### ISSUE TITLE
Direct3D VkExternalMemoryHandleTypeFlagBits documentation is misleading

### ISSUE THREAD

**Issue by DadSchoorse** [KhronosGroup/Vulkan-Docs#1551]
While working on resource sharing in Wine, I got confused if it's possible to export D3D handles from Vulkan.
The documentation for `VkExternalMemoryHandleTypeFlagBits` for the D3D handles implies that such handles can only be created by the respective D3D api. For example:

> VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_BIT specifies an NT handle returned by IDXGIResource1::CreateSharedHandle referring to a Direct3D 10 or 11 texture resource.

But the documentation around `VkExportMemoryWin32HandleInfoKHR` seems to imply that such handles can also be exported from Vulkan:

> For handles of the following types:
>    VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT
>   VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_BIT
>The implementation must ensure the access rights allow read and write access to the memory.

**Comment by stonesthrow** [comment]
Scheduled for triage discussion 6/23

**Comment by stonesthrow** [comment]
Action: Remove handle from second list.
