### ISSUE TITLE
Can render pass use image as attachment and non-attachment?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1559]
Can render pass use (color) image as (written) attachment and (read-only)non-attachment?

My initial impression was that it cannot. But then I started weasling around it, and this seems valid:

- use image only in `VK_IMAGE_LAYOUT_GENERAL` (so it is valid for both color attachment and sampler descriptors)
- put store op to `VK_ATTACHMENT_STORE_OP_STORE`
- put appropriate `VkSubpassDependency` between two subpasses, with `src = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT + VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT` and `dst = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT + VK_ACCESS_SHADER_READ_BIT`. Probably needs `dependencyFlags = 0` to be sane.
- in the first subpass write the image as color attachment, and in the second subpass sample it as non-attachment.

Now, normally I would need a layout change, and `VkAttachmentReference` would break stuff. But by `VK_IMAGE_LAYOUT_GENERAL` I workaround around that.

I need store op to be finished in the first subpass, because:

> Other than the exceptions listed below, applications **must** ensure that all accesses to memory that backs image subresources used as attachments in a given renderpass instance either happen-before the load operations for those attachments, or **happen-after the store operations for those attachments**.

That seems the way it works naturally:

> The store operation for each sample in an attachment happens-after any recorded command which accesses the sample in the last subpass where the attachment is used.

Now I need the second subpass to actually have dependency on that store op. `src = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT + VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT` is appropriate there, and checking the spec it should work:

> [...] the first set of commands includes all commands submitted as part of the subpass instance identified by srcSubpass and any load, **store** or multisample resolve operations on attachments used in srcSubpass.

Is this usage intentionally valid?

**Comment by Tobski** [comment]
I've raised an internal issue for this, because it does seem potentially weird, and if it's intentional we might need some new CTS tests.

**Comment by Tobski** [comment]
FWIW though from an initial assessment I agree that it doesn't seem to be invalid, but the render pass chapter is long and messy, so maybe there's something lurking in there we both missed...

**Comment by oddhack** [comment]
This should be fixed in the 1.3.205 spec update.
