### ISSUE TITLE
Input attachments: using the same index.

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#156]
Section 13.1.11 describes how a FS can consume an input attachment as a descriptor image binding. Section 14.1 describes how a FS can consume an input attachment as an input variable (thus always fetching the sample that corresponds with the current fragment's sample).

However, I do not believe the specification ever says what happens if you use the same input attachment index for *both* uses. I imagine that this should be some kind of validation failure. Alternatively, it could be allowed via aliasing, since you can't write to an input attachment.

**Comment by janharaldfredriksen-arm** [comment]
There shouldn't be two types of uses here.

The input attachments need to be included in the descriptor set so that implementations that cannot merge the subpasses can replace the input attachment reads with regular texture reads. The input attachment also needs to be specified in the renderpass/framebuffer.

That is:
>Each element of the array corresponds to an input attachment unit number in the shader, i.e. if the shader declares an input variable layout(input_attachment_index=X, set=Y, binding=Z) then it uses the attachment provided in pInputAttachments[X]. Input attachments must also be bound to the pipeline with a descriptor set, with the input attachment descriptor written in the location (set=Y, binding=Z).

It seems like there's something we should clarify here, but I'm not entirely sure what. Could you provide some more details on what makes you think there are two distinct uses?

**Comment by NicolBolas** [comment]
> It seems like there's something we should clarify here, but I'm not entirely sure what. Could you provide some more details on what makes you think there are two distinct uses?

Because I was reading Vulkan version 1.0.5; the bug was relative to that version. In that version, Chapter 14.1 described input attachments as `Input`-decorated variables, rather than those with descriptor sets. Since 13.1.11 described an alternate input attachment scheme (through descriptor sets), it appeared as though input attachments could be connected to in two separate ways.

But in any case, this is irrelevant. the most recent version of Vulkan corrected this, changing 14.1 to refer to descriptor set bindings, rather than input variables.

**Comment by NicolBolas** [comment]
Oh, and they didn't fix it completely:

> **Fragment Input Attachment Interface**
> A fragment shader entry point’s variables with `Input` storage class and a decoration of
`InputAttachmentIndex`, which receive values from input attachments.

**Comment by oddhack** [comment]
Could you clarify what you would like done against the 1.0.7 spec? Is it just the glossary entry to be fixed?

**Comment by NicolBolas** [comment]
As far as I can tell, it's just that glossary entry at this point. Everything else says that input attachments worth through descriptor set bindings.

**Comment by NicolBolas** [comment]
@oddhack 

There have been 3 point releases of Vulkan since 1.0.7. And they all still have that very incorrect glossary entry that states that `InputAttachmentIndex` gets applied to `Input` variables.

**Comment by NicolBolas** [comment]
1.0.11: The glossary entry is *still wrong*.

**Comment by oddhack** [comment]
Understood. We have finite bandwidth to deal with public issues and are going as fast as we can, so it will get fixed when it does. Sorry for the delay.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.15 spec update.
