### ISSUE TITLE
Unclear definition for VkSubpassDescription::pDepthStencilAttachment

### ISSUE THREAD

**Issue by moongoal** [KhronosGroup/Vulkan-Docs#1561]
The [Vulkan 1.2.181 specification](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap8.html#VkSubpassDescription) states:

> pDepthStencilAttachment is a pointer to **an array of VkAttachmentReference structures** specifying the depth/stencil attachment for this subpass and its layout.

and then [also](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap8.html#VUID-VkSubpassDescription-pDepthStencilAttachment-parameter) states:

> If pDepthStencilAttachment is not NULL, pDepthStencilAttachment must be a valid pointer to **a valid VkAttachmentReference structure**

It's then unclear whether the pointer is to an array of multiple attachment reference structures or to a single attachment reference.

**Comment by sfricke-samsung** [comment]
To clarify, it should **not** be an array, and it is right in `VkSubpassDescription2`

> pDepthStencilAttachment is a pointer to a VkAttachmentReference2 structure specifying the depth/stencil attachment for this subpass and its layout.

So will remove "an array of"

**Comment by oddhack** [comment]
This should be fixed in the 1.2.183 spec update.
