### ISSUE TITLE
Task list for VK_EXT_multi_draw release

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-Docs#1563]
This extension is used to serialize sequential draw commands into a single function call, reducing the overhead of recording the draws.

The task list for the VK_EXT_multi_draw release is:

 - [x] Vulkan Specification:  https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_multi_draw.html
 - [x ] Conformance tests released: 
 - [x ] SDK released: 
     - [x ] Validation layer: 

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by krOoze** [comment]
Why is `instanceCount` not part of `VkMultiDrawInfoEXT`?
