### ISSUE TITLE
vkGetSubpassShadingMaxWorkgroupSizeHUAWEI doesn't take a dispatchable handle as first parameter

### ISSUE THREAD

**Issue by DadSchoorse** [KhronosGroup/Vulkan-Docs#1564]
All Vulkan functions which are not global take either a `VkInstance`, `VkPhysicalDevice`, `VkDevice` , `VkQueue` or `VkCommandBuffer` as its first parameter. `vkGetSubpassShadingMaxWorkgroupSizeHUAWEI` doesn't, it takes a `VkRenderPass`.

This is fundamentally broken, you need a dispatchable handle for the vulkan loader to do its thing, and we need it in Wine as well for our dispatch tables.

**Comment by expipiplus1** [comment]
FWIW, the Haskell bindings will require a workaround for this too.

**Comment by DadSchoorse** [comment]
It's not possible to work around it in any way, the loader will break if you ever call the function returned by `vkGetInstanceProcAddr(instance, "vkGetSubpassShadingMaxWorkgroupSizeHUAWEI")`.

**Comment by lenny-lunarg** [comment]
+1. The desktop loader is designed entirely assuming that every function will start with a dispatchable handle. Without that, we have no way of calling into the correct layer or ICD efficiently. We can add new dispatchable handles if needed, but we can't make something that was previously non-dispatchable (like `VkRenderPass`) into a dispatchable handle (without breaking backwards compatibility). We need something like as `VkDevice` as the first argument.

**Comment by KarenGhavam-lunarG** [comment]
The next Vulkan SDK will be released without this issue being resolved. If an application attempts to use this extension, it will be broken. Since this is a vendor extension and not an EXT or KHR, this was deemed acceptable.

**Comment by WyvernWang** [comment]
I think I can change the API to vkGetPhysicalDeviceSubpassShadingMaxWorkgroupSizeHUAWEI with a VkPhysicalDevice dispatch handle. May I do that? and is it enough to resolve this?

**Comment by DadSchoorse** [comment]
In my opinion it would make more sense to take a VkDevice, since you already use a VkRenderPass created for one specific device.

**Comment by WyvernWang** [comment]
In the first time, I did consider the VKDevice. However, I also consider the condition a device could be created from a device group. But maybe I shall not go that far for now.

**Comment by WyvernWang** [comment]
Ok, I kindly figure out this puzzle and I think use VkDevice is ok since we may return the minimum value of all maximum workgroup size for all physical devices used to create this device.

**Comment by WyvernWang** [comment]
I created a merge request for this
https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/4666

**Comment by oddhack** [comment]
This should be fixed in the 1.2.184 spec update.
