### ISSUE TITLE
VK_EXT_swapchain_colorspace promoted?

### ISSUE THREAD

**Issue by Carandiru0** [KhronosGroup/Vulkan-Docs#1566]
Well - I get no such validation error for using the enums returned from vkGetPhysicalDeviceSurfaceFormats2KHR , when I have not explicitly enabled the instance extension VK_EXT_swapchain_colorspace. vkGetPhysicalDeviceSurfaceFormats2KHR seems to return all supported formats that can be used in swapchain creation.

Vulkan SDK 1.2.154.1

Was this extension internally promoted to no longer be an extension ? Is it built-in now so to speak that explicitly enabling the extension is no longer required to use these colorspace enumerations?

Currently on the "Vulkan Hardware Capability Database" this extension has **vendor gpu support** of **7.7%** vs no support at 92.3%

What is going on here? Is this extension deprecated?

I'm not sure if enabling this extension is required for HDR/WideGamut Colorspaces. These formats are important for implementations supporting true hdr monitors.

**Comment by krOoze** [comment]
Validation layers do not have complete coverage, nor are bug-free. If something is not reported, then it is probably not yet or improperly checked. That being said, your SDK version is also way old.

If it were promoted, then specification would note it in the [extension appendix](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_EXT_swapchain_colorspace). See extensions in the List of Deprecated Extensions section for an example.

The 7.7 % are old buggy drivers that accidentally expose it as a device extension. You have to look at the [instance extension list](https://vulkan.gpuinfo.org/listinstanceextensions.php), which currently does not have a coverage percentage on the website. Nevertheless AMD, NV, and lots of stuff seem supported.

**Comment by Carandiru0** [comment]
thank you for clearing that up. I guess it's just a validation error that is missing.
Still works without enabling the instance extension nevertheless. I can select the expanded color spaces returned by vkGetPhysicalDeviceSurfaceFormats2KHR and use them as a swapchain format.
Isn't it supposed to be required to enable the extension on the instance first?
Or is this not neccessary? Thanks again.

**Comment by krOoze** [comment]
Yea, you need to enable extension to use it.

Well, undefined behavior is undefined. If it would always visibly break when you do a bad thing, then that would be a defined behavior.

I think currently enums are not checked against extensions at all.

**Comment by oddhack** [comment]
@stonesthrow this is a new SI issue (or maybe a validation layer issue).

**Comment by stonesthrow** [comment]
If not resolved, we'll triage and give action plan next week.

**Comment by stonesthrow** [comment]
Thank you krOoze for the response.
@Carandiru0, the question seems resolved. Can we close this?

**Comment by Carandiru0** [comment]
Sounds good. Thank you for clarifying I still need to enable it.
