### ISSUE TITLE
VK_EXT_calibrated_timestamps missing physical-device-level dependencies?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1568]
`VK_EXT_calibrated_timestamps` is a device extension that adds `vkGetPhysicalDeviceCalibrateableTimeDomainsEXT`. But it does not have any dependencies, and formally only `VK_KHR_get_physical_device_properties2` or in turn Vulkan 1.1 adds the physical-device-level capability.

It should either have "Requires `VK_KHR_get_physical_device_properties2`", or the `vkGetPhysicalDeviceCalibrateableTimeDomainsEXT` should have `<require feature="something">`.

**Comment by Tobski** [comment]
Thanks, this just looks like an oversight, I'll raise an internal MR to fix this.

**Comment by krOoze** [comment]
It's potentionally a class of issues, and other extensions might have the same problem...

**Comment by oddhack** [comment]
This should be fixed in the 1.2.185 spec update.
