### ISSUE TITLE
14.4 Fragment Input Attachment Interface not allowed?

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#157]
Section 14.4 outlines the means to declare that an `Input`-decorated variable to a FS will be filled in by an input attachment. This would be an alternate means to access input attachments, instead of declaring `UniformConstant` variables of a `SubpassData` type, and then fetching a value from them.

However, while exploring #156, I discovered that... SPIR-V 1.00 doesn't actually allow `Input`-qualified variables to have the `InputAttachmentIndex` qualifier on them. Nor does [the VK-GLSL extension](https://www.khronos.org/registry/vulkan/specs/misc/GL_KHR_vulkan_glsl.txt) allow the use of `input_attachment_index`

This makes it seem like section 14.4 was kind of a mistake. That perhaps it was from an older design, but was never fully expunged. Either that, or it was a newer designed intended to replace the descriptor based one, but was never fully realized.

Either way, something's gotta change. Either remove the functionality that neither VK-GLSL nor SPIR-V can specify, or allow them to specify it so that we can actually use it.

**Comment by philiptaylor** [comment]
> Section 14.4 outlines the means to declare that an Input-decorated variable to a FS will be filled in by an input attachment.

It looks like that section was changed in 1.0.7 to refer to UniformConstant-decorated variables instead, with a reference to https://github.com/KhronosGroup/glslang/issues/169

**Comment by NicolBolas** [comment]
Is there not some kind of update when they release a new version of the specification?

**Comment by NicolBolas** [comment]
Also, they didn't quite fix it fully in 1.0.7. Namely, the glossary section:

> A fragment shader entry point’s variables with `Input` storage class and a decoration of
`InputAttachmentIndex`, which receive values from input attachments.

**Comment by oddhack** [comment]
I'm not sure exactly how we *can* announce it; there's no mailing list for the purpose. I think Khronos has a Twitter account so that would be a possibility, or on the front page of Khronos.org - I ping the webmaster when I put up a new version, but I'm not sure that always turns into a news item.

**Comment by oddhack** [comment]
The glossary entry has been updated at this point. If that resolves the issue for you then please close it.

**Comment by NicolBolas** [comment]
Thanks; that does resolve the problem.
