### ISSUE TITLE
Why are layout transitions and pipeline barriers part of the same api?

### ISSUE THREAD

**Issue by fctorial** [KhronosGroup/Vulkan-Docs#1570]
Image layout change operation appears to be completely orthogonal to the topic of synchronization. They why are image layout transitions a part of the pipeline barrier api in vulkan?

Let's say I want to add screenshot capability to a game. This is the sequence of steps the application has to follow when the user presses the screenshot button:

1. Finish the current rendering operation.
2. Change swapchain image layout to `TRANSFER_DST_OPTIMAL`.
3. Perform a `cmdCopyImage`
4. Change swapchain image layout to `PRESENT_SRC_OPTIMAL`.
5. Queue the image for presentation

The API documentation seems to suggest that a transition layout operation is likely to perform a copy of the image. If that is the case, then the above sequence of operations will likely perform three copies. Wouldn't it be simpler if the the layout transition operation was a part of `cmdCopyImage` api instead of pipeline barrier api (with the option of source and destination images being same, if all you want to do is a layout transition)? What are the motivations for the api being the way it is now?

**Comment by nanokatze** [comment]
No, because whatever performs the copy doesn't necessarily understand the image in the layout you're transitioning away from.

**Comment by Tobski** [comment]
Hi @fctorial, image layout transitions are not actually copies per say - they're usually done "in place", where some meta data is translated into raw pixel values. In this particular case in step 2 you'd usually want to be transitioning from UNDEFINED, which will actually do very little.

Even if the transitions were part of copy image, it likely wouldn't save any work from being done - if dedicated transfer hardware is used, then it may only understand the transfer layout and wouldn't be able to perform transitions "in-line". If such a layout isn't required, then the transitions will most likely be no-ops.

**Comment by cubanismo** [comment]
> In this particular case in step 2 you'd usually want to be transitioning from UNDEFINED, which will actually do very little anyway.

Agreed with your response in general @Tobski, but this part doesn't sound right. Wouldn't that mean the screenshot and also the vkQueuePresentKHR() operation in step 5 would contain undefined data? The app is copying data *out* of the swapchain image here, not *in.*

**Comment by Tobski** [comment]
@cubanismo whoops you're right, missed the use case there!

**Comment by ShabbyX** [comment]
> Image layout change operation appears to be completely orthogonal to the topic of synchronization.

Conceptually yes, but they do go hand in hand. When you transition an image from layout A to B, you need to synchronize the layout transition both before and after (with the operations that have come before it and the operations that will come after it). If they were not tied to the same API, you would have had to do something like this:

1. Finish the current rendering operation.
2. Issue a pipeline barrier
3. Change swapchain image layout to TRANSFER_DST_OPTIMAL. (with some new API that doesn't do synchronization)
4. Issue another pipeline barrier
5. Perform a cmdCopyImage
6. Issue a pipeline barrier
7. Change swapchain image layout to PRESENT_SRC_OPTIMAL.
8. Issue another pipeline barrier
9. Queue the image for presentation

That's just more verbose.

**Comment by Tobski** [comment]
Hopefully the responses from myself and @ShabbyX explain the reasoning here. Given the lack of recent responses we're closing this issue - but if there's any further questions or further comments, please feel free to reopen.
