### ISSUE TITLE
Paths to sibling headers in vulkan_core.h

### ISSUE THREAD

**Issue by TheMostDiligent** [KhronosGroup/Vulkan-Docs#1573]
This [recent change](https://github.com/KhronosGroup/Vulkan-Headers/commit/a8964617af6b104d0341874e9b4776d82f80f9af#diff-e222ae95c2b0d5082b94d6086fb1c24da18ee31384c1a39840df3b9152023ee6R23) made all headers included from `vulkan_core.h` relative to the parent directory. This is a bit strange as all headers are located in the same folder as `vulkan_core.h`. This also caused some minor build breakages in our project.

**Comment by oddhack** [comment]
See #1538 for the motivation for this change. At this point we are inclined to wait and see if it affects many other people.

**Comment by TheMostDiligent** [comment]
@oddhack Public headers should be self-contained and not require an application to add any include search paths. All includes should be referenced relative to the location of the current header.

Before the change we did not add any search paths at all and the following worked fine, but now produces an error:

```cpp
#include "ThirdParty/Vulkan-Headers/include/vulkan/vulkan.h"
```

Please reconsider your change as it is really a strange way of organizing headers.

**Comment by oddhack** [comment]
We talked about this today and are generally feeling that accepting #1538 was premature and the change should be reverted, possibly with a downstream change to just move the vk_video directory under vulkan/. I will propose a PR to that effect and we'll have until next week to discuss. Unfortunately at this point, whatever we do will affect someone; affecting people using the provisional video extensions is less problematic the alternative.

**Comment by TheMostDiligent** [comment]
Why can't you use relative paths to reference vk_video headers too, e.g.
```cpp
#include "../vk_video/vulkan_video_codec_h264std.h"
```

**Comment by MarijnS95** [comment]
> We talked about this today and are generally feeling that accepting #1538 was premature and the change should be reverted, possibly with a downstream change to just move the vk_video directory under vulkan/. I will propose a PR to that effect and we'll have until next week to discuss. Unfortunately at this point, whatever we do will affect someone; affecting people using the provisional video extensions is less problematic the alternative.

Noticing just now that one of my contributions is in dispute (thanks for keeping me in the loop...). That change in `vulkan_core.h` is a nasty side effect and, quite frankly, plain wrong.

This change was _not_ made to accommodate `vk_video/`, _at all_. It has nothing to do with it besides providing a nice example. Instead, the common factor in all `<type category="include">` elements is that their paths are relative to an `include/` folder, with `vk_platform.h` being the only exception.

**Comment by oddhack** [comment]
Didn't actually close this after my previous comment.
