### ISSUE TITLE
Broken link in VK_KHR_spirv_1_4

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/Vulkan-Docs#1574]
In the `1.0-wsi_extensions` and `1.0-extensions` builds of the Vulkan spec, the link to `VkPhysicalDeviceSubgroupProperties` in the Issues section of the `VK_KHR_spirv_1_4` extension points to nowhere.

**Comment by oddhack** [comment]
Will be corrected in the next spec update by conditionalizing the reference, which requires Vulkan 1.1.

**Comment by oddhack** [comment]
This should be fixed in the 1.2.185 spec update.
