### ISSUE TITLE
Definition of "stride" in VkVertexInputBindingDescription not clear

### ISSUE THREAD

**Issue by moongoal** [KhronosGroup/Vulkan-Docs#1575]
In the definition of *VkVertexInputBindingDescription* the [Vulkan spec 1.2.184](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap22.html#VkVertexInputBindingDescription) states:

> stride is the distance in bytes between two consecutive elements within the buffer.

I think this is not clear since the *distance* between two consecutive elements can be defined as the size of the gap between the two, while the *stride* should always be defined as the size of one element plus the size of the gap - from the start of the first element, to the start of the second.

I suggest rephrasing as:

> stride is the distance in bytes between **the beginning of one element and that of the element immediately following** ~~two consecutive elements~~ within the buffer.

which I believe should be less open to interpretation.

**Comment by fluppeteer** [comment]
I agree the wording could be a little less ambiguous, and it's a case that should be clear. It was noted that "distance in bytes" is a bit odd too. Perhaps "difference in byte address between the beginning of one element and that of any element immediately following within the buffer", by symmetry with ptrdiff_t?

**Comment by moongoal** [comment]
Out of curiosity, why is "distance in bytes" odd? If we think of system memory as a large byte array, then the difference between any two pointers will always yield a scalar that is effectively a "distance", although not necessarily computed in bytes - which is the reason why "in bytes" is also often specified when it's the case. It seems at least mathematically correct and is certainly very common speech.

**Comment by sfricke-samsung** [comment]
So in `VkDescriptorUpdateTemplateEntry`, `vkGetQueryPoolResults`, and a few other functions we just say

> stride is the stride in bytes between...

So to be consistent with the rest of the spec, I would purpose rewording `VkVertexInputBindingDescription::stride` as just

> stride is the byte stride between consecutive elements within the buffer.

-----

(Noting for myself any word change will need to be made to `VkVertexInputBindingDescription2EXT` and `vkCmdBindVertexBuffers2EXT` as well)

**Comment by fluppeteer** [comment]
> Out of curiosity, why is "distance in bytes" odd? If we think of system memory as a large byte array, then the difference between any two pointers will always yield a scalar that is effectively a "distance", although not necessarily computed in bytes - which is the reason why "in bytes" is also often specified when it's the case. It seems at least mathematically correct and is certainly very common speech.

Oops, sorry, missed this. I just tend to think "difference" because I've had ptrdiff_t drummed into me. I agree there's nothing logically wrong with "distance", although I tend to think of that in terms of spatial dimensions. I'm sensitised because of trying to differentiate memory and coordinates in the KDFS. :-)

**Comment by oddhack** [comment]
Should be fixed in the 1.2.186 spec update.
