### ISSUE TITLE
VK_EXT_multi_draw DrawIndex interaction

### ISSUE THREAD

**Issue by akeley98NV** [KhronosGroup/Vulkan-Docs#1576]
In the documentation for vkCmdDrawMultiEXT, it's stated that

> This command is equivalent to calling vkCmdDraw drawCount times

If this were the case, then the value of gl_DrawIndex would be uniformly 0, rather than counting up with each draw, as I'd expect. Is this a spec bug, or an intentional incompatibility with OpenGL behavior?

@zmike

**Comment by zmike** [comment]
spec bug

**Comment by zmike** [comment]
See also the `DrawIndex` documentation in spirv interfaces.

**Comment by oddhack** [comment]
@akeley98NV this should have been addressed in the most recent spec update. Please reopen if there's still something needing attention.
