### ISSUE TITLE
"trace ray instruction" not defined

### ISSUE THREAD

**Issue by dylanede** [KhronosGroup/Vulkan-Docs#1578]
In section 38.1 _"Shader Call Instructions"_, the term "trace ray instruction" is used multiple times without being defined. It might be that this phrase is meant to refer to `OpTraceRayKHR` and `OpTraceRayMotionNV` instructions only, in which case the section leaves ambiguity about how the other non-trace-ray instructions, are allowed to be used. In particular, the details of recursion limits are only specified in relation to "trace ray instructions", with no mention of other recursion limits on other shader call instructions that can recurse, for example `OpExecuteCallableKHR`. One question that arises is, if I have a pipeline that purely recursively calls `OpExecuteCallableKHR` without tracing any rays, what should the `maxRayRecursionDepth` parameter on the pipeline be set to?

It would seem to me that the specification would make more sense if occurrences of "trace ray instruction" are meant to read "shader call instruction". This however does then imply that `maxRayRecursionDepth` is a bit of a misnomer.

**Edit:** Actually, just replacing "trace ray instruction" with "shader call instruction" would not make sense, since then it would imply that maximum recursion depth would be affected by calls to `OpReportIntersectionKHR` calling any-hit shaders, which I don't think is currently the case (i.e. for a pipeline with intersection and any hit shaders, it would make the shader call recursion depth potentially double the number of rays recursively traced).

**Edit 2:** Looking at the DXR documentation for comparison, it seems that instead the solution is to give a definition of "trace ray instruction" to mean just `OpTraceRayKHR` and `OpTraceRayMotionNV`, and to explicitly state that there is no limit on recursion of other shader call instructions other than the stack size.

**Comment by dgkoch** [comment]
Proposed change does the following: 

Defines the term "pipeline trace ray instruction" in the glossary:

> 
> **Pipeline Trace Ray Instruction**
> A ray tracing instruction which traces a ray into an acceleration structure when using ray tracing pipelines. One of OpTraceNV, OpTraceRayMotionNV, OpTraceMotionNV, OpTraceRayKHR .

Changes the indicated use in 38.1 to be:

> _Pipeline trace ray instructions_ can be used recursively; invoked shaders can themselves execute pipeline trace ray instructions, to a maximum depth defined by the maxRecursionDepth or maxRayRecursionDepth limit.

And added the following per your suggestion: 

> There is no explicit recursion limit for other shader call instructions which may recurse (e.g. OpExecuteCallableKHR) but there is an upper bound determined by the stack size.

**Comment by dylanede** [comment]
That looks perfect. Thanks!

**Comment by oddhack** [comment]
This should be fixed in the 1.2.187 spec update.
