### ISSUE TITLE
vk*WaitIdle should say it is equivalent to vkQueueSubmit

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1579]
`vkQueueWaitIdle` and `vkDeviceWaitIdle` should explicitly say they are same as `vkQueueSubmit`, because some other language depends on it. Notably the fence signal op, which says:

> Fence signal operations that are defined by `vkQueueSubmit` additionally include in the first synchronization scope all commands that occur earlier in _submission order_.

The current wording is:

> `vkQueueWaitIdle` is equivalent to submitting a fence to a queue and waiting with an infinite timeout for that fence to signal.

With that it is not 110 % clear if it counts as "Fence signal operations that are defined by `vkQueueSubmit`" for the purposes of the above.

**Comment by stonesthrow** [comment]
@oddhack, we think this a Vulkan issue and not SI. Its vkQueueSubmit and not vkQueuePresent. So question for Vulkan WG.

**Comment by oddhack** [comment]
Should be fixed in the 1.2.186 spec update.
