### ISSUE TITLE
VkCommandBufferBeginInfo::pipelineStatistics referenced which does not exist

### ISSUE THREAD

**Issue by Saulzar** [KhronosGroup/Vulkan-Docs#158]
> If commandBuffer has a VK_QUERY_TYPE_PIPELINE_STATISTICS query active, then each element of pCommandBuffers must have been recorded with VkCommandBufferBeginInfo::pipelineStatistics having all bits set that are set in the VkQueryPool the query uses.

VkCommandBufferBeginInfo::pipelineStatistics does not exist.

Should this be VkCommandBufferBeginInfo->pInheritanceInfo->pipelineStatistics ?

**Comment by Saulzar** [comment]
The story around pipeline statistics queries is very unclear . For example in the documentation for VkQueryPoolCreateInfo states:

> pipelineStatistics is a bitmask indicating which counters will be returned in queries on the new pool, as described below in Section 16.4, “Pipeline Statistics Queries”

However, what is the effect of enabling multiple query types for the same query pool? Would a query of 
`pipelineStatistics = VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_VERTICES_BIT | VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_PRIMITIVES_BIT
` be a sum of input vertices + input primitives?

Enabling more than one flag causes the NV driver for example to spit out "invalid enumeration" upon vkGetQueryResult.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.9 spec update. @Saulzar, please open a separate issue to address your questions - this issue was just about the typo.
