### ISSUE TITLE
vkUpdateDescriptorSets does not have complete common parent VU

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1581]
As per https://stackoverflow.com/questions/68409048/using-different-vkdevice-for-image-and-its-view/68409418#68409418 the `vkUpdateDescriptorSets` is missing some common parent VUs. E.g. that `pDescriptorWrites[0].pBufferInfo->buffer` is created from `device`.

**Comment by Tobski** [comment]
Thanks for the report - I'll raise a fix for this internally.

**Comment by oddhack** [comment]
This should be fixed in the 1.2.189 spec update.
