### ISSUE TITLE
Separate depth stencil layout not allowed

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1583]
Sentence in Image Layouts chapter says that separate depth and stencil layouts are not allowed:

> The image layout is per-image subresource, and separate image subresources of the same image **can** be in different layouts at the same time with one exception - depth and stencil aspects of a given image subresource **must** always be in the same layout.

But I believe it was later allowed with `VK_KHR_separate_depth_stencil_layouts`.

**Comment by oddhack** [comment]
This should be fixed in the 1.2.189 spec update.
