### ISSUE TITLE
Can suboptimal or out_of_date swapchain become optimal again?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1584]
Can `VK_SUBOPTIMAL_KHR` or `VK_ERROR_OUT_OF_DATE_KHR` swapchain become optimal again?

The main usecase is if the app become minimized (and the surface becomes 0x0). Is it guaranteed that the pre-minimization swapchain would still work when the app is activated again?

Additionally the information might generally be relevant for making code valid. If one command returns `VK_ERROR_OUT_OF_DATE_KHR` but other command could subsequently return `VK_SUCCESS`, it might make some code that does not expect it glitchy.

> further presentation requests using the swapchain will fail

This leans towards "no".

Same does not seem to be said for `VK_SUBOPTIMAL_KHR`. Common sense kinda implies that if the size changes back to the optimal, it could become `VK_SUCCESS` again?

**Comment by stonesthrow** [comment]
As I recall, but I will go check on this, we said somewhere that OUT_OF_DATE is sticky, that is the swapchain never comes out of that state.
SUBOPTIMAL - if you rotate your tablet, and then rotate back; and its back to its original size, then one would think that that would be optimal again. Let me check in on that and make sure that is expected behavior, and get some text added if not.

**Comment by stonesthrow** [comment]
In WSI section vkAcquireNextImahe() is this text:
_"If the swapchain images no longer match native surface properties, either VK_SUBOPTIMAL_KHR or VK_ERROR_OUT_OF_DATE_KHR must be returned. If VK_ERROR_OUT_OF_DATE_KHR is returned, no image is acquired and attempts to present previously acquired images to the swapchain will also fail with VK_ERROR_OUT_OF_DATE_KHR. Applications need to create a new swapchain for the surface to continue presenting if VK_ERROR_OUT_OF_DATE_KHR is returned."_
This tells you that OUT_OF_DATE never return to optimal.

**Comment by krOoze** [comment]
Hm, seems strong enough. Though possibly not general enough.

E.g. the opposite is not there: that after present fails with `VK_ERROR_OUT_OF_DATE_KHR`, then subsequent `vkAcquire*`s also fail. Also there are some other commands that return `VK_ERROR_OUT_OF_DATE_KHR`, and it is not clear if it sticks for those.

**Comment by stonesthrow** [comment]
I will try to follow up and 1. be clear in all OUT_OF_DDATE that Swapchain must be recreated. 2. Suboptimal - yes, a Swapchain can be come optimal again, agreed by WSI WG. Need to add text to spec.
