### ISSUE TITLE
Orphaned `vkCreateSwapchainKHR` paragraphs

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1585]
There are paragraphs belonging to `vkCreateSwapchainKHR` that are orphaned.

It starts with:

> As mentioned above, if `vkCreateSwapchainKHR` succeeds

It is split from `vkCreateSwapchainKHR` by `vkGetSwapchainCounterEXT` and `vkSetLocalDimmingAMD`,

**Comment by stonesthrow** [comment]
I see that just below "Return Codes" for vkGetSwapchainCounterEXT. 
Thank you. I will look into it.
