### ISSUE TITLE
Clarify that only storage images with Unknown format must have the NonReadable/Writable decoration.

### ISSUE THREAD

**Issue by Kangz** [KhronosGroup/Vulkan-Docs#1588]
Bringing this up because the check was implemented as written in the spec in the VVL https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2777 and produces an error as soon as you try sampling an image.

In "Runtime SPIR-V validation" the Vulkan spec says:

> If shaderStorageImageWriteWithoutFormat is not enabled and an OpTypeImage has “Image Format” operand of Unknown, any variables created with the given type must be decorated with NonWritable.
>
> If shaderStorageImageReadWithoutFormat is not enabled and an OpTypeImage has “Image Format” operand of Unknown, any variables created with the given type must be decorated with NonReadable.

As written this should apply to all `OpTypeImage`, including just sampled images. However SPIRV disallows applying these decorations to sampled images:

> NonWritable
> Must be applied only to memory object declarations or members of a structure type. Any such memory object declaration, or any memory object declaration that contains such a structure type, must be one of:
> - A storage image (see OpTypeImage).
> - A block in the StorageBuffer storage class, or in the Uniform storage class with the BufferBlock decoration.
> - Missing before version 1.4: An object in the Private or Function storage classes.

I also checked and glslang doesn't produce such a decoration. I think it is clear that the Vulkan spec should only ask that these decorations be present for "storage images" and the text should be updated to be more precise.

**Comment by llandwerlin-intel** [comment]
Thanks, I've proposed a change on the khronos gitlab (4723).

**Comment by oddhack** [comment]
This should be fixed in the 1.2.187 spec update.
