### ISSUE TITLE
queue priority

### ISSUE THREAD

**Issue by konstantinegorov** [KhronosGroup/Vulkan-Docs#1589]
How to create multiple queues from the same family, but with different global priorities? For example, one compute queue with low priority and one compute queue with normal?

**Comment by r-potter** [comment]
Duplicate of https://github.com/KhronosGroup/Vulkan-Docs/issues/1398?

**Comment by konstantinegorov** [comment]
Oh, I'm sorry. Yes, it is a duplicate
