### ISSUE TITLE
Definition of "pitch" in VkSubresourceLayout not clear

### ISSUE THREAD

**Issue by moongoal** [KhronosGroup/Vulkan-Docs#1593]
Hi,

The [Vulkan spec 1.2.186](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap12.html#VkSubresourceLayout) defines pitch as:

> * rowPitch describes the number of bytes between each row of texels in an image.
> * arrayPitch describes the number of bytes between each array layer of an image.
> * depthPitch describes the number of bytes between each slice of 3D image.

I think this is not clear since the distance between two consecutive elements (rows, array layers or slices) can be defined as the size of the gap between the two, while the pitch should always be defined as the size of one element plus the size of the gap - from the start of the first element, to the start of the second.

This is the same issue as [this](https://github.com/KhronosGroup/Vulkan-Docs/issues/1575#event-5073517253).

Probably a little less interesting than the previous issue, since reading the formula for `address(x,y,z,layer)` makes it obvious that pitch is the size of the full element including padding, but maybe still worth reviewing.

**Comment by oddhack** [comment]
@sfricke-samsung my notes at the time were that you would reply to this but I neglected to assign you to it.

**Comment by sfricke-samsung** [comment]
@moongoal Sorry for the delay

Did you have a potential suggestion for how it could be reworded such that we can eliminate all ambiguity

**Comment by sfricke-samsung** [comment]
Closing for now, feel free to reopen if you have a suggestion on how you would want to reword the spec to eliminate the ambiguity you see
