### ISSUE TITLE
VK_ERROR_OUT_OF_DEVICE_MEMORY vs maxMemoryAllocationSize

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1595]
The spec says:

> Some platforms **may** have a limit on the maximum size of a single allocation. For example, certain systems **may** fail to create allocations with a size greater than or equal to 4GB. Such a limit is implementation-dependent, and if such a failure occurs then the error `VK_ERROR_OUT_OF_DEVICE_MEMORY` **must** be returned. This limit is advertised in `VkPhysicalDeviceMaintenance3Properties::maxMemoryAllocationSize`.

But recent VU added:

> `allocationSize` **must** be less than `VkPhysicalDeviceMaintenance3Properties::maxMemoryAllocationSize`.

The VU is inconsistent with above paragraph that makes it a defined behavior to pass a larger size.

Additionally it feels the VU breaks compatibility guarantees.

**Comment by llandwerlin-intel** [comment]
Thanks, this is mistake on my side. We'll remove this VU in the next update.

**Comment by oddhack** [comment]
This should be fixed in the 1.2.189 spec update.
