### ISSUE TITLE
Clarify what primitives/fill-modes depth bias applies to.

### ISSUE THREAD

**Issue by Jonathan-Weinstein** [KhronosGroup/Vulkan-Docs#1596]
D3D docs on depth bias contain a useful sentence like "Bias is not applied to any point or line primitives, except for lines drawn in wireframe mode."  https://docs.microsoft.com/en-us/windows/win32/direct3d11/d3d10-graphics-programming-guide-output-merger-stage-depth-bias

However, section 27.12.3. Depth Bias from the Vulkan spec doesn't contain any wording like that, unless I'm missing something.
Vulkan also has more interesting cases than D3D, such as an input primitive of triangles with VK_POLYGON_MODE_POINT (I think OpenGL did support depth bias for this case, enabled by GL_POLYGON_OFFSET_POINT).

I think it would be helpful to explicitly mention what primitives/fill-modes are affected by depth bias. I don't need depth bias to apply to point-filled triangles, but it would be good to clarify the behavior for that case and others, which could perhaps be "implementation defined".

**Comment by oddhack** [comment]
Thanks. We'll take a look at this - may take  a while to figure out if it's indeed implementation dependent behavior.

**Comment by c0d1f1ed** [comment]
This has led to the addition of the spec text "Depth bias is applied to triangle topology primitives received by the rasterizer regardless of [polygon mode](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#primsrast-polygonmode). Depth bias **may** also be applied to line and point topology primitives received by the rasterizer."

This is tested by `dEQP-VK.draw.renderpass.depth_bias.depth_bias_*`: https://github.com/KhronosGroup/VK-GL-CTS/commit/02f9d2af46710af305827fcd993dd7b6ff305dc4

**Comment by awkr** [comment]
hi @c0d1f1ed, so depth bias may not be well supported in LINE polygon mode?
