### ISSUE TITLE
Broken VUID link for vkGetPhysicalDeviceSurfaceFormatsKHR

### ISSUE THREAD

**Issue by martty** [KhronosGroup/Vulkan-Docs#1598]
On 
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceSurfaceFormatsKHR.html
the VUID 06211 is broken and shows:
![image](https://user-images.githubusercontent.com/395730/128421816-ca6ed1a3-153f-45e6-a792-617ee388706a.png)

In the chunked spec it points to an NV extension.

**Comment by oddhack** [comment]
Thanks. This will be fixed soon, it was just a markup oversight.

**Comment by oddhack** [comment]
This should be fixed in the 1.2.188 spec update.
