### ISSUE TITLE
Missing documentation for initialLayout field of VkImageCreateInfo

### ISSUE THREAD

**Issue by JonMarbach** [KhronosGroup/Vulkan-Docs#160]
Hi there! I hope I'm not mis-reporting this, I know some of the docs pages say "don't open GitHub issues", so bear with me and let me know if you don't want this kind of report.

This page:
[https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkImageCreateInfo.html](https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkImageCreateInfo.html)

Current doesn't list initialLayout in the Fields section of the page with the other fields. Doesn't sound like a big deal but I overlooked this field when implementing some code because I tend to use the Fields section as a checklist.

**Comment by oddhack** [comment]
The ref pages are just not up to date with the core spec, unfortunately. The latter is where we're concentrating our energy at present. So I believe it's a valid issue but can't give you any estimate on when it might be fixed.

**Comment by oddhack** [comment]
This should be fixed now.
