### ISSUE TITLE
Clarify the behavior of abandoned queue ownership transfers

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/Vulkan-Docs#1600]
One thing that's not clear with queue ownership transfers is what happens if you do a release, but never do the matching acquire. 
E.g queue 0 releases a resource to queue 1, but queue 1 never does the acquire. Later on, queue 0 wants to use that resource again.
In the case of image resources it seems like queue 0 can re-use the resource as ownership is re-acquired by queue 0 by doing a layout change using a srcLayout of UNDEFINED. Is that assumption correct? If so, it may be worth mentioning.
Thanks

**Comment by krOoze** [comment]
#1050

**Comment by mbechard** [comment]
Ah thanks, that covers it. I'll close this one

**Comment by krOoze** [comment]
@Tobski any news on the front?
