### ISSUE TITLE
VkShaderModuleCreateFlagBits Reference Gives 404 Error

### ISSUE THREAD

**Issue by samwalls-arm** [KhronosGroup/Vulkan-Docs#1601]
The following link gives me a 404 error currently: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkShaderModuleCreateFlagBits.html

I found the link on the reference page for [VkShaderModuleCreateFlag](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkShaderModuleCreateFlags.html).

**Comment by oddhack** [comment]
This should be fixed in the 1.2.190 spec update.
