### ISSUE TITLE
`unnormalizedCoordinates` not allowed on 3D textures, despite mentioning Z axis.

### ISSUE THREAD

**Issue by Wunkolo** [KhronosGroup/Vulkan-Docs#1602]
While using the latest validation layers, I ran into this validation message recently where using `unnormalizedCoordinates` on a `VK_IMAGE_VIEW_TYPE_3D` seems to be disallowed:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/fe2b768fac9702f3513bdfd386e642b14e489632/layers/descriptor_sets.cpp#L1337-L1354

I had been able to do this just fine on most hardware for ages now, only to recently find out that it goes against the spec to do so.
From the [spec](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkSamplerCreateInfo.html) for `VkSamplerCreateInfo`:
> `unnormalizedCoordinates` controls whether to use unnormalized or normalized texel coordinates to address texels of the image. When set to `VK_TRUE`, the range of the image coordinates used to lookup the texel is in the range of zero to the image dimensions for x, y <ins>and **z**</ins>. When set to `VK_FALSE` the range of image coordinates is zero to one.
> 
> When `unnormalizedCoordinates` is VK_TRUE, images the sampler is used with in the shader have the following requirements:
> <ins>The viewType must be either `VK_IMAGE_VIEW_TYPE_1D` or `VK_IMAGE_VIEW_TYPE_2D`</ins>.

`unnormalizedCoordinates` is not allowed on `VK_IMAGE_VIEW_TYPE_3D`. Despite this, it is mentioned that it will use the texel-space domain for X and Y **and Z** in the specification.

Is there a reason `unnormalizedCoordinates` is disallowed on `VK_IMAGE_VIEW_TYPE_3D`?

**Comment by Tobski** [comment]
Thanks for your feedback! The "and z" part there is kind of misleading, it's definitely intentional that this doesn't work for 3D as some hardware simply can't handle this. Note that this functionality is basically texture rectangles from OpenGL which were always 2D.

We've got an internal fix pending to change the parameter to say "maximum value in each dimension" rather than "x, y and z" to avoid the apparent conflict. We can't relax the 1D/2D requirement from the core specification.

**Comment by Wunkolo** [comment]
Thank you for the clarification!

> it's definitely intentional that this doesn't work for 3D as some hardware simply can't handle this
Maybe Unnormalized 3D coordinates could possibly be an advertised feature at some point? It certainly works on some of my hardware but if there is a chance it may not work on others it may be worth knowing this somehow!

**Comment by Tobski** [comment]
If you want to make a formal feature request, please describe the use cases for this, and any other relevant information that could help us triage/prioritise it.

**Comment by oddhack** [comment]
This should be fixed in the 1.2.189 spec update.
