### ISSUE TITLE
`VK_HEADER_VERSION` define not updated from 187 -> 188

### ISSUE THREAD

**Issue by Friz64** [KhronosGroup/Vulkan-Docs#1603]
In the newest Vulkan 1.2.188 spec update (https://github.com/KhronosGroup/Vulkan-Docs/commit/f1eda2cb1656363ccd67e07f5654a80fc13b47af), the `VK_HEADER_VERSION` define was not updated in `vk.xml` and its value is still `187`.

This breaks code that relied on this value.

**Comment by oddhack** [comment]
I updated vk.xml and the v1.2.188 tag in this repo, but am not comfortable doing that in Vulkan-Headers without signoff from the SDK developers, so https://github.com/KhronosGroup/Vulkan-Headers/pull/225 will be outstanding there until they decide what to do with it. Sorry about the error.

**Comment by oddhack** [comment]
@friz64 the SDK folks think that changing the tag in Vulkan-Headers will be disruptive to their builds and don't want to do that. I left the question of whether to accept the MR which updates the header update number to them, but probably that won't be accepted before the next spec update (next Tuesday, probably) resolves it going forward.

**Comment by Friz64** [comment]
Thank you for your efforts! Also cc @charles-lunarg

**Comment by oddhack** [comment]
1.2.189 spec update should have fixed this.
