### ISSUE TITLE
Unclear behaviour of vkGetInstanceProcAddr

### ISSUE THREAD

**Issue by Dav1dde** [KhronosGroup/Vulkan-Docs#1605]
Currently calling `vkGetInstanceProcAddr(valid_instance, "vkEnumerateInstanceExtensionProperties")` returns the correct handle for `vkEnumerateInstanceExtensionProperties` (using https://github.com/KhronosGroup/Vulkan-Loader), which can be verified very easily in [the code](https://github.com/KhronosGroup/Vulkan-Loader/blob/b0841ad150f921bd65db6b8bfd345f2a32a906b6/loader/trampoline.c#L52).

On Android this call returns `null`: https://issuetracker.google.com/issues/190077299

An Android Team member brought up a valid point about the behaviour, according to the [spec section 4.1](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#initialization-functionpointers) footnote 2, this is wrong:

> The returned function pointer must only be called with a dispatchable object (the first parameter) that is instance or a child of instance, e.g. VkInstance, VkPhysicalDevice, VkDevice, VkQueue, or VkCommandBuffer.

since `vkEnumerateInstanceExtensionProperties` cannot be called with either of `VkInstance, VkPhysicalDevice, VkDevice, VkQueue, or VkCommandBuffer`.

Is this a bug in the specification or actually a bug in the Vulkan-Loader?

**Comment by oddhack** [comment]
This should be fixed in the 1.2.193 spec update.
