### ISSUE TITLE
Discontinuous descriptor set indices

### ISSUE THREAD

**Issue by Duttenheim** [KhronosGroup/Vulkan-Docs#161]
If a shader implements descriptor sets with indexes which is not a continuous series, is the shader still valid? If you have one set which is decorated as layout(set=1) and another where you have layout(set=3), should the vkCreatePipelineLayout then define only two sets (1 and 3) or should they define the entire range 1..3 inclusively?

In the eventuality a range of sets is the valid way, are you supposed to implement the 2'nd (in the example) descriptor set layout in the range to be empty by setting the pBindings to NULL and the bindingCount to 0?

The Khronos reference compiler doesn't raise an error or warning if the sets are not a continuous series, neither does the LunarG validation layers when creating descriptor layouts, pipeline objects or when creating shader modules.

**Comment by NicolBolas** [comment]
> If a shader implements descriptor sets with indexes which is not a continuous series, is the shader still valid?

The rest of your question talks about set indices, rather than binding indices. So I'll assume that's what you mean by "indexes".

The specification does not require added clarification on this matter. From the docs for `VkPipelineLayoutCreateInfo`:

>  If `setLayoutCount` is not 0, `pSetLayouts` must be a pointer to an array of `setLayoutCount` valid `VkDescriptorSetLayout` handles

By definition, the NULL handle is not a valid `VkDescriptorSetLayout`. Therefore, you must use some properly constructed `VkDescriptorSetLayout` for the set.

> are you supposed to implement the 2'nd (in the example) descriptor set layout in the range to be empty by setting the pBindings to NULL and the bindingCount to 0?

I don't know what you mean by "supposed to". But if you want to have a descriptor set with no bindings, the specification with `VkDescriptorSetLayoutCreateInfo` makes it clear whether that's possible or not:

>   If `bindingCount` is not 0, `pBindings` must be a pointer to an array of `bindingCount` valid `VkDescriptorSetLayoutBinding` structures

There is no explicit prohibition of `bindingCount == 0`, so it must be allowed. And it therefore will create a descriptor set with 0 bindings.

This is a bug list, not a forum. If you have questions about the behavior of Vulkan and what the spec says, they can be answered [here](https://forums.khronos.org/) or [here](http://stackoverflow.com/questions/tagged/vulkan). But this is not the place to get answers. This is the place to report actual problems with the specification.

And as I've stated, the specification is not problematic here.

**Comment by Duttenheim** [comment]
Sorry if I was being unclear in my first post. The issue I found is regarding the compatibility of a pipeline layout and a shader module, if the shader code has a discontinuous series of descriptor set decorators.

I've been in contact with AMD (https://community.amd.com/thread/198224) and they suggested me raising this with you. Hopefully our conversation can shed some more light on the issue.

**Comment by NicolBolas** [comment]
Then take it up with NVIDIA. The Vulkan specification is very clear: `bindingCount` is allowed to be 0. Therefore, if their driver crashes when you use a descriptor set with a `bindingCount` of zero, then their driver is broken.

Though I am curious as to exactly why you want to make empty descriptor sets at all. Here's what I mean.

Let's say you have two pipeline programs, A and B, which each use the same descriptor sets 0 and 5. Vulkan's pipeline layout compatibility rules explicitly state that set 5 is not compatible between the two unless sets 1-4 are *also* compatible between the two. So if A uses sets 1-4 and B doesn't, then it doesn't matter if they use the same set 5. The layout between 0 and 5 is not compatible, so set 5 is not compatible between the two.

This is why the specification strongly suggests ordering sets in increasing frequency of changes.

The correct way to handle the above case, to allow set 5 to remain compatible between the two, is to build A and B with the *same layouts*. Even though no shaders in B will use the data in sets 1-4, they should still use the same layout.

Generally speaking, you probably shouldn't be changing pipeline layouts very often.

**Comment by jeffbolznv** [comment]
> Then take it up with NVIDIA. The Vulkan specification is very clear: bindingCount is allowed to be 0. Therefore, if their driver crashes when you use a descriptor set with a bindingCount of zero, then their driver is broken.

AFAIK NVIDIA's driver handles this correctly, and there is some CTS coverage for it. Based on a brief skim of the other thread, it seems more likely that the bug is that using set 5 violates the maxBoundDescriptorSets limit. (And FYI, this limit will increase in future drivers).

**Comment by Duttenheim** [comment]
@jeffbolznv Ah, okay. Maybe the validation layers just didn't pick up on that then. I can do a quick test to see if that was the issue all along.

@NicolBolas The issue is not when binding descriptor sets. The issue is when creating a pipeline object, because the vkCreatePipelineLayout doesn't dictate whether or not the set layout in pSetLayouts at some index N must correspond to some descriptor set decorated in the shader code using the same index N. So for example

`layout(set=0) sampler2D someSampler;`
`layout(set=5) sampler2D someOtherSampler;`

Has two possible scenarios for creating a compatible pipeline layout. 

1. Have 6 descriptor set layouts, ranging from 0 to 5 where 1..4 is just empty (no pBindings for vkCreateDescriptorSetLayout).
2. Have 2 descriptor set layouts, one with a sampler in each.

The person I talked to on the AMD forums just mentioned that they interpreted it by having to define the entire range, meaning case 1. Now the issue I might have had with the NVIDIA driver might be what @jeffbolznv mentioned, so I will have to test that. What I know is that AMD representative interpreted it as being a closed range, from the lowest set to the highest, but they also said that the specification doesn't recognize the concept of descriptor sets with a discontinuous numbering, and thus they didn't deem it invalid to do so.

I understand this is easily resolved, but this is testing an edge case.

**Comment by NicolBolas** [comment]
> The issue is when creating a pipeline object, because the vkCreatePipelineLayout doesn't dictate whether or not the set layout in pSetLayouts at some index N must correspond to some descriptor set decorated in the shader code using the same index N.

Yes, it does. `pSetLayouts` contains an array of `VkDescriptorSetLayout` objects. And `VkDescriptorSetLayout` does not specify what set index it uses. Just look at `VkDescriptorSetLayoutCreateInfo` There is _no parameter_ there which specifies a set index. Therefore, the `VkDescriptorSetLayout` object must be completely blind to the descrptor set index you will eventually use it with.

Given that, there is only one possible place where the mapping from a descriptor set layout and a set index is made: in `vkCreatePipelineLayout`, through `pSetLayouts`. And that's just an array of `VkDescriptorSetLayout` objects, which as previously stated are completely blind to the set index you use.

Therefore, the placement of a layout within `pSetLayouts` is the *only possible place* where the mapping from layout to set index could happen. That is, the index into that array _is the set's index_ in the overall pipeline layout.

Or we could just look at the specification:

> A variable identified with a **DescriptorSet** decoration of `s` and a **Binding** decoration of `b` indicates that this variable is associated with the `VkDescriptorSetLayoutBinding` that has a binding equal to `b` in `pSetLayouts[s]` that was specified in `VkPipelineLayoutCreateInfo`.

I do not know how that could possibly be clearer.

Therefore:

> Has two possible scenarios for creating a compatible pipeline layout. 

No, there is only option 1. Option 2 is not possible, as previously stated.

**Comment by Duttenheim** [comment]
Yes, that is very clear, and you are correct in that it leaves me with option 1.  I must have been unable to find that in the spec myself and was lead to believe it was an issue. And 13.2.1 also explains that empty descriptor set layouts are valid, meaning it is okay to implement unused indices into pSetLayouts as descriptor set layouts with no bindings.

I stand corrected and I apologize for taking up your time.

**Comment by oddhack** [comment]
@Duttenheim if the issue has been resolved to your satisfaction, please close it. Thanks!
