### ISSUE TITLE
Link in Chapter 13 'undefined'

### ISSUE THREAD

**Issue by SWinxy** [KhronosGroup/Vulkan-Docs#1621]
The extension-less [sampler chapter](https://www.khronos.org/registry/vulkan/specs/1.2/html/chap13.html) tries to link to `VK_KHR_sampler_mirror_clamp_to_edge`, but links to https://www.khronos.org/registry/vulkan/specs/1.2/html/undefined instead, where it defines `VkSamplerAddressMode`.

> * VK_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE specifies that the mirror clamp to edge wrap mode will be used. This is only valid if [samplerMirrorClampToEdge](https://www.khronos.org/registry/vulkan/specs/1.2/html/chap31.html#features-samplerMirrorClampToEdge) is enabled, or if the [[VK_KHR_sampler_mirror_clamp_to_edge]](https://www.khronos.org/registry/vulkan/specs/1.2/html/undefined) extension is enabled.

**Comment by krOoze** [comment]
There are, I think, way more dead links than that. It can be checked with https://validator.w3.org/checklink. Problem is some of them are very hard to eliminate. Particularly if they are part of a VU. Links to extension names feel to me relatively benign, though that the click on it does nothing is mildly annoying. At least in html build though it is telegraphed with the `[]`.

**Comment by oddhack** [comment]
As krOoze says. We could instrument the spec build to make these live links only in the specs that are built with those extensions included, though the changes would be annoyingly pervasive on the markup. We expect that most people are referring to the 1.2 + all extensions spec build most of the time.

**Comment by oddhack** [comment]
We discuss in the WG - wontfix at this time.
