### ISSUE TITLE
Description of VkDeviceQueueInfo2's pNext chain mentioning "image parameters"

### ISSUE THREAD

**Issue by pixelcluster** [KhronosGroup/Vulkan-Docs#1622]
In the description of the `pNext` member of `VkDeviceQueueInfo2`, the spec states:
> pNext is NULL or a pointer to a structure extending this structure. The pNext chain of VkDeviceQueueInfo2 is used to provide additional image parameters to vkGetDeviceQueue2.

The term "image parameters" is used, but it is not defined in the context of device queues anywhere else in the spec. The only place it is used elsewhere is in the context of image properties. The `pNext` description of `VkPhysicalDeviceImageFormatInfo2` looks similar to the one of `VkDeviceQueueInfo2`:
> pNext is NULL or a pointer to a structure extending this structure. The pNext chain of VkPhysicalDeviceImageFormatInfo2 is used to provide additional image parameters to vkGetPhysicalDeviceImageFormatProperties2.

The `pNext` chain of `VkDeviceQueueInfo2` seems to not be used for anything, as currently the Valid Usage states:
> pNext must be NULL.

**Comment by oddhack** [comment]
That looks like a cut & paste error. Probably should say "additional device queue parameters" or just "additional parameters".

The 'must be Null or a pointer...' is boilerplate that avoids the need for complex asciidoctor conditionals in the source markup depending on how the spec is built. In the future if extending structures are defined for this struct, there's no need to change that language.

**Comment by oddhack** [comment]
This should be fixed in the 1.2.192 spec update.

**Comment by pixelcluster** [comment]
Looks good, thanks!
