### ISSUE TITLE
Primitive topology list restart VUIDs missing "and primitiveRestartEnable is VK_TRUE" clause

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-Docs#1623]
I believe that in both VUID-VkPipelineInputAssemblyStateCreateInfo-topology-06252 and VUID-VkPipelineInputAssemblyStateCreateInfo-topology-06253, the listed topologies should only be invalid if the primitiveTopologyListRestart feature is not enabled AND primitiveRestartEnable is true.  If primitiveRestartEnable is false, I don't think either of the VUIDs apply.

**Comment by oddhack** [comment]
@Tony-LunarG if you are comfortable doing it, please propose a gitlab MR with fixes. If not assign to @TomOlson and we'll find someone in the WG to do it.

**Comment by Tony-LunarG** [comment]
Fixed in 1.2.193
