### ISSUE TITLE
vkGetDeviceGroupSurfacePresentModesKHR with non-device-group VkDevice

### ISSUE THREAD

**Issue by ziga-lunarg** [KhronosGroup/Vulkan-Docs#1625]
The spec says for vkGetDeviceGroupSurfacePresentModesKHR :

> To query the supported device group present modes for a particular surface

But I am unsure if this is prohibited if the VkDevice passed into the function is not a device group.

Same with vkGetDeviceGroupSurfacePresentModes2EXT.

**Comment by krOoze** [comment]
There are no devices that are not a device group. Every device is at least a device group of one:

> A logical device created without using `VkDeviceGroupDeviceCreateInfo`, or with `physicalDeviceCount` equal to zero, is equivalent to a `physicalDeviceCount` of one and `pPhysicalDevices` pointing to the `physicalDevice` parameter to `vkCreateDevice`.

**Comment by ziga-lunarg** [comment]
That clears it up, thanks!
