### ISSUE TITLE
vkCmdCopyImage/vkCmdCopyBuffer valid usage

### ISSUE THREAD

**Issue by mark-lunarg** [KhronosGroup/Vulkan-Docs#163]
In the valid usage section under **VkImageCopy**, there are two entries:

`The aspectMask member of srcSubresource must specify aspects present in the calling command’s srcImage`
`The aspectMask member of dstSubresource must specify aspects present in the calling command’s dstImage`

VkImages don't directly have associated aspectMasks and this doesn't seem to be valid for this type of operation in any case.

There are a couple-three similar cases in **VkCmdCopyBuffer** as well.

**Comment by oddhack** [comment]
This should be addressed in the 1.0.18 spec update.
