### ISSUE TITLE
The purpose of fragmentDensityMapDynamic is unclear

### ISSUE THREAD

**Issue by TheMostDiligent** [KhronosGroup/Vulkan-Docs#1631]
Hello!

We are trying to understand the meaning of the `fragmentDensityMapDynamic` property, especially what happens if `fragmentDensityMapDynamic=false`.

[From the spec](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPhysicalDeviceFragmentDensityMapFeaturesEXT.html):

> `fragmentDensityMapDynamic` specifies whether the implementation supports dynamic fragment density map image views. If this feature is not enabled, `VK_IMAGE_VIEW_CREATE_FRAGMENT_DENSITY_MAP_DYNAMIC_BIT_EXT` must not be included in `VkImageViewCreateInfo::flags`

Then [for this flag](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkImageViewCreateFlagBits.html):

> `VK_IMAGE_VIEW_CREATE_FRAGMENT_DENSITY_MAP_DYNAMIC_BIT_EXT` specifies that the fragment density map will be read by device during `VK_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT`

And finally, [for this stage](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPipelineStageFlagBits.html):

> `VK_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT` specifies the stage of the pipeline where the fragment density map is read to generate the fragment areas.

So it appears that if `fragmentDensityMapDynamic=false`, then we can't set the `VK_IMAGE_VIEW_CREATE_FRAGMENT_DENSITY_MAP_DYNAMIC_BIT_EXT` flag, which in turn means that VRS view will not be read at `VK_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT`. But how it should be used then?

There is also a description [here](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_fragment_density_map2.html#_improved_host_latency) that does not really add clarity:

By default, the fragment density map is locked by the host for reading between `vkCmdBeginRenderPass` during recording and `VK_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT` during draw execution.

Again, with `fragmentDensityMapDynamic=false`, we apparently can't use the view at this stage at all, but even if we could it still does not make sense: in our usage scenario we update the VRS texture by copying the data to it on the device. The copy command is recorded and submitted to the command buffer, so what is the point of locking the map on the host since the copy will be performed on the device and the data is not going to be available until later?

The only theory we have is that `fragmentDensityMapDynamic=false` means that `VK_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT` stage is executed by the host, and if `fragmentDensityMapDynamic=true`, it is executed by device. But if this is really the case, I can't imagine a more confusing way to describe this in the documentation.

**Comment by jackohound** [comment]
This other language from the spec clarifies the case where `fragmentDensityMapDynamic=false` which requires that 'VK_IMAGE_VIEW_CREATE_FRAGMENT_DENSITY_MAP_DYNAMIC_BIT_EXT' is not set:

> The fragment density map is read at an implementation-dependent time with the following constraints determined by the  attachment’s image view flags:
>
> - VK_IMAGE_VIEW_CREATE_FRAGMENT_DENSITY_MAP_DYNAMIC_BIT_EXT specifies that the fragment density map will be read by the device during VK_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT
>
> - VK_IMAGE_VIEW_CREATE_FRAGMENT_DENSITY_MAP_DEFERRED_BIT_EXT specifies that the fragment density map will be read by the host during vkEndCommandBuffer of the primary command buffer that the render pass is recorded into
>
> - Otherwise the fragment density map will be read by the host during vkCmdBeginRenderPass
>
> The fragment density map may additionally be read by the device during VK_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT for any mode.

I believe the above addresses your question, but let me know things are still unclear.  In your usage scenario, assuming you set  `fragmentDensityMapDynamic=false`, I believe you will need to ensure that the fragment density map has been updated and can be read by the host at the time vkCmdBeginRenderPass is recorded.

**Comment by TheMostDiligent** [comment]
Yes, that answers my question. Thank you!
