### ISSUE TITLE
Provenance of VkDeviceAddress

### ISSUE THREAD

**Issue by martty** [KhronosGroup/Vulkan-Docs#1636]
The 1.2 spec says VkDeviceAddress is provided by VK_VERSION_1_0, but this is not true - this typedef does not exist in the 1.0 specification.

https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap3.html#VkDeviceAddress

**Comment by oddhack** [comment]
This should be fixed in the 1.2.192 spec update. There was an XML / spec markup inconsistency.

**Comment by martty** [comment]
Thank you for looking into this, but I am a bit surprised at the solution - I thought that VkDeviceAddress was cored in 1.2, after promotion of VK_KHR_buffer_device_address - but your fix suggests the definition was backported to 1.0. Why is that?

**Comment by r-potter** [comment]
We discovered that there are published extensions that use the `VkDeviceAddress` type and don't declare a dependency on 1.2/VK_KHR_buffer_device_address in the XML. Given the choice between updating the dependency requirements of shipping extensions, or backporting a simple typedef, we went with the option that had the lowest risk of breaking anything.

**Comment by martty** [comment]
Thank you for the explanation - makes sense.
