### ISSUE TITLE
Do WSI fence and semaphore have to be signaled in finite time?

### ISSUE THREAD

**Issue by DadSchoorse** [KhronosGroup/Vulkan-Docs#1639]
In update for version 1.2.185 the following clarification was added:
> If vkAcquireNextImageKHR is called when the number of images that the application has currently acquired is less or equal than the difference between the number of images in swapchain and the value of VkSurfaceCapabilitiesKHR::minImageCount, vkAcquireNextImageKHR must return in finite time with an allowed VkResult code.

> Note :
Returning a result in finite time guarantees that the implementation cannot deadlock an application, or suspend its execution indefintely with correct API usage. Acquiring too many images at once may block indefinitely, which is covered by valid usage when attempting to use UINT64_MAX. For example, a scenario here is when a compositor holds on to images which are currently being presented, and there are not any vacant images left to be acquired.

Despite this addition, I think there's still potential for deadlocks, with the following scenario:
vkAcquireNextImageKHR returns in finite time, but the fence and/or semaphore never get signaled.

**Comment by stonesthrow** [comment]
Ack. Try to get back to you ASAP.

**Comment by stonesthrow** [comment]
@cubanismo , @Tobski for comment.

**Comment by stonesthrow** [comment]
@DadSchoorse "Despite this addition, I think there's still potential for deadlocks, with the following scenario:
vkAcquireNextImageKHR returns in finite time, but the fence and/or semaphore never get signaled."

No, only returns when an Image can be acquired in finite time and the fence/semaphore will be signaled.

**Comment by cubanismo** [comment]
I was hoping to find some spec language to back this up. The closest I can find is this:

"If semaphore is not VK_NULL_HANDLE, the application may assume that, once vkAcquireNextImageKHR returns, the semaphore signal operation referenced by semaphore has been submitted for execution."

I'm assuming at some point this was trivially equivalent to a forward-progress guarantee, but I'm having trouble deriving that in current spec language.

Also, I can't find a similar guarantee for the fence, but it was the intent that both be considered submitted and hence would signal in finite time. We could certainly clarify the spec a bit in this regard, but signaling of these synchronization objects in finite time is intended to be guaranteed, and hence a forward progress guarantee was intended to be provided.

**Comment by stonesthrow** [comment]
Have we answered this? What is follow up?
