### ISSUE TITLE
Buffer Alignment Limit Constraint

### ISSUE THREAD

**Issue by bjornbytes** [KhronosGroup/Vulkan-Docs#1640]
Are the `minTexelBufferOffsetAlignment`, `minUniformBufferOffsetAlignment`, and `minStorageBufferOffsetAlignment` limits required to be power of two?  If this were specified, applications could safely use `&` instead of `%` to check whether  a buffer offset satisfies the alignment requirement.  I didn't see anything about this in the Limits section or in `VkDescriptorBufferInfo` valid usage.

**Comment by nanokatze** [comment]
In 12.7. Resource Memory Association, note that
> The alignment member is a power of two.
and
> The alignment member satisfies the buffer descriptor offset alignment requirements associated with the VkBuffer’s usage:
> 
>    * If usage included VK_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT or VK_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT, alignment must be an integer multiple of VkPhysicalDeviceLimits::minTexelBufferOffsetAlignment.
> 
>    * If usage included VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT, alignment must be an integer multiple of VkPhysicalDeviceLimits::minUniformBufferOffsetAlignment.
> 
>    * If usage included VK_BUFFER_USAGE_STORAGE_BUFFER_BIT, alignment must be an integer multiple of VkPhysicalDeviceLimits::minStorageBufferOffsetAlignment.

Clearly, if x = ny and x is a power of two, it follows that n and y are also powers of two!

**Comment by bjornbytes** [comment]
Makes sense.  I don't think this is as clear as it could be, but I'll defer to spec editors.
