### ISSUE TITLE
Clarify that an acceleration structure can be updated in-place by setting `srcAccelerationStructure` and `dstAccelerationStructure` to the same structure

### ISSUE THREAD

**Issue by expenses** [KhronosGroup/Vulkan-Docs#1641]
The spec page for [`VkAccelerationStructureBuildGeometryInfoKHR`](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VkAccelerationStructureBuildGeometryInfoKHR) mentions that:

> `srcAccelerationStructure` is a pointer to an existing acceleration structure that is to be used to update the dst acceleration structure when mode is `VK_BUILD_ACCELERATION_STRUCTURE_MODE_UPDATE_KHR`.

[Ray Tracing Gems II](https://link.springer.com/content/pdf/10.1007%2F978-1-4842-7185-8.pdf), Chapter 16, Introduction to Vulkan Ray Tracing (page 239) says this:

> To update an acceleration structure, call `vkCmdBuildAccelerationStructuresKHR()` as was shown on pages 229 and 233, but with both `VkAccelerationStructureBuildGeometryInfoKHR`’s `srcAccelerationStructure` and `dstAccelerationStructure` fields set to the acceleration structure to update and with its mode field set to `VK_BUILD_ACCELERATION_STRUCTURE_MODE_UPDATE_KHR`.

I had been unable to get acceleration structures working on my own personal project until I tried this.

Assuming that the book is correct, it'd be lovely to get a line clarifying that this is a possibility into the spec.

**Comment by yuriy-odonnell-epic** [comment]
Hi, 
I'd like to better understand what the initial non-working code looked like. Was it using a `null` source acceleration structure during an update? If so, then I think there is indeed some room for improving `VkAccelerationStructureBuildGeometryInfoKHR` to make the common intended usage pattern more clear.

Right now there is this [VU text](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-04630): 
> For each element of pInfos, if its mode member is VK_BUILD_ACCELERATION_STRUCTURE_MODE_UPDATE_KHR, its srcAccelerationStructure member must not be VK_NULL_HANDLE

It is attached to the vkCmdBuildAccelerationStructuresKHR, rather than VkAccelerationStructureBuildGeometryInfoKHR. Unfortunately, splitting useful information between structure and command docs is a common pattern in the spec (presumably because structure validation can only happen when it's consumed by a command).

Yuriy

**Comment by expenses** [comment]
Hi Yuriy, no the VU text is clear.

What I was doing previously was:

1. Creating a new acceleration structure
2. Setting `dstAccelerationStructure` to that and `srcAccelerationStructure` to the previous acceleration structure
3. Performing the build
4. Doing a descriptor set write to set the new structure

On a single-buffered setup with only 1 set of synchronization primitives and resources (1 acceleration structure), the update didn't seem to happen at all. It might be that I wasn't using the right pipeline barriers, but I feel like I tried a few combinations of things and none of them worked.

On a double-buffered setup with 2 sets of sync primitives and 2 acceleration structures that are used for alternate frames, the update worked on every second frame, creating a flickering effect.

When I switched to setting `dstAccelerationStructure` and `srcAccelerationStructure` both to the same existing structure, it worked perfectly under both conditions.

**Comment by yuriy-odonnell-epic** [comment]
Oh ok. Is this in the context of bottom level acceleration structures, where just the vertex positions are different? Would you be able to perhaps provide a repro app for the non-working case? The described behavior suggests either a driver or an application bug of some sort.

To the best of my understanding, using a _compatible-but-separate_ acceleration structure as an update source is a supported valid API usage (in-place update is not a _requirement_ but only one of the possibilities).

I can also see that [DXR spec](https://microsoft.github.io/DirectX-Specs/d3d/Raytracing.html#d3d12_build_raytracing_acceleration_structure_desc) calls out identical source and destination addresses as a special case that performs an in-place update. It also has the following explicit text:
> Acceleration structure updates can happen either in-place, or use separate source and destination buffers.  

We could potentially add a similar explicit call-out to VKRT spec, as the intention is to keep behavior as close as possible around these things.

**Comment by expenses** [comment]
This is in the context of a top level acceleration structure, where the transformation matrix of one instance is changed.

> We could potentially add a similar explicit call-out to VKRT spec, as the intention is to keep behavior as close as possible around these things.

Yep, that sounds good!

I'll see if I can make a repro app for the non-working case.

**Comment by expenses** [comment]
Closed by https://github.com/KhronosGroup/Vulkan-Docs/commit/2a43f68f2841054d7f2fb6a44c637c533a549dbb.
