### ISSUE TITLE
Allow VkPolygonMode to be set dynamically

### ISSUE THREAD

**Issue by gvcallen** [KhronosGroup/Vulkan-Docs#1645]
It is common for some applications to want to e.g. draw a model using VK_POLYGON_MODE_FILL in one moment and then VK_POLYGON_MODE_LINE in another to be able to switch between "solid" and "wireframe" drawings.

This issue suggests adding the ability to allow this option to be set as another dynamic state. Metal allows for this with "MTLRenderCommandEncoder::setTriangleFillMode" suggesting it is possible at a hardware level. This is much more convenient than creating multiple pipelines.

A suggestion for the function signature would be:
vkCmdSetPolygonMode(VkCommandBuffer commandBuffer, VkPolygonMode polygonMode);

Hopefully this is trivially implementable for GPU driver manufacturers.

**Comment by pdaniell-nv** [comment]
This should be covered by the new VK_EXT_extended_dynamic_state3 extension: https://github.com/KhronosGroup/Vulkan-Docs/issues/1961
