### ISSUE TITLE
Potentially conflicting or confusing requirements for `attachmentCount` in graphics pipeline creation

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-Docs#1656]
Consider these two VUIDs:
- VUID-VkGraphicsPipelineCreateInfo-attachmentCount-00746
If the pipeline is being created with fragment output interface state, and the subpass uses color attachments, the `attachmentCount` member of `pColorBlendState` **must** be equal to the `colorAttachmentCount` used to create `subpass`
- VUID-VkGraphicsPipelineCreateInfo-rasterizerDiscardEnable-04493
If the pipeline is being created with fragment output interface state, `pColorBlendState->attachmentCount` **must** be greater than the index of all color attachments that are not `VK_ATTACHMENT_UNUSED` for the `subpass` index in `renderPass`

This seems to mean that `attachmentCount` must simultaneously match the number of color attachments, and be numerically greater than the highest attachment index. One could imagine creating a render pass with 2 attachments, of which index 0 is used as color attachment in the first subpass, and index 1 as color attachment in the second subpass. This seems like a perfectly legal render pass to create. But in this situation, for a graphics pipeline targeting the second subpass, these requirements appear to say that `attachmentCount` must both equal 1 (the `colorAttachmentCount` of the second subpass) and be greater than 1 (the highest attachment index in the second subpass), which is obviously impossible.

**Comment by Rua** [comment]
It looks like these VUIDs were renamed in the meantime. The new ones are:
- VUID-VkGraphicsPipelineCreateInfo-renderPass-06042
- VUID-VkGraphicsPipelineCreateInfo-renderPass-06045

**Comment by oddhack** [comment]
This should be fixed in the 1.2.203 spec update.
