### ISSUE TITLE
Missing VUID for `VK_DYNAMIC_STATE_DISCARD_RECTANGLE_EXT` at draw time

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-Docs#1657]
There is no VUID specifying which state needs to be set at draw time, when the pipeline was created with `VK_DYNAMIC_STATE_DISCARD_RECTANGLE_EXT`. I assume that all discard rectangle slots from 0 to the pipeline's `discardRectangleCount` must be set?

**Comment by spencer-lunarg** [comment]
This was added as `VUID-vkCmdDraw-None-07751` in 1.3.236 spec (also made Validation Layer change already!)

**Comment by spencer-lunarg** [comment]
@pdaniell-nv actually looking that this now, should there be an additional VU for making sure all the `discardRectangleCount` are set? (If so I can make the VU)

**Comment by oddhack** [comment]
This should be fixed in the 1.3.239 spec update.
