### ISSUE TITLE
1.0.7 spec ambiguity in describing queue families

### ISSUE THREAD

**Issue by GertyP** [KhronosGroup/Vulkan-Docs#166]
In the 1.0.7 spec, chapter 2.2 (Execution Model), there's a short, general description of queues -

> The queues supported by a device are divided into families, each of which supports one or more types of functionality and may contain multiple queues with similar characteristics

Unfortunately, I think there is some gramatical ambiguity over whether the subject is the queue/queues or the device, which leaves this open to misinterpretation.

If the subject is the queues, then it is the queues that can be divided, potentially leading the reader to believe a queue is composed of multiple things called families, which, in turn, can contain other queues.  If the subject is the device, then it is the device that is divided into families of queues.

If the intention is the second interpretation, it would be less ambiguous to either say that specifically the "device is divided into families of queues" or that a "device's queues are grouped into families".

**Comment by pimanttr** [comment]
The subject is families. Each device has one or more families, each of which has one or more queues.

Maybe "partitioned" or "grouped" as you suggest would be more precise than "divided"

**Comment by hpablo** [comment]
What is "divided into families" is the *set* of queues, not the queues themselves. Indeed "partitioned" (as in "The queues supported by a device are partitioned into families") would be the most appropriate word, because queues cannot belong to more than one family.

**Comment by GertyP** [comment]
'Partitioned' is synonymous with divided, which I'd hoped to illustrate as being ambiguous, if not misleading, in the original context.
The sentence, "The cakes supported by a table are divided into slices" is fairly clear that it is the cakes that are themselves divided up into slices.  In sentence grammar, the 'subject' (the thing to which the verb 'divided' applies) can only be the cakes.  Changing divided to partitioned results in the same meaning.  Exactly the same sentence structure is used in the specification, misleading the reader to believe that it is the queues that are divided up into (or composed of) families.
It would be unambiguous if changed to, "A device's queues are grouped into families..."

**Comment by oddhack** [comment]
This should be fixed in the 1.0.11 spec update.
