### ISSUE TITLE
Clarification on vertex attribute alignment requirements (`attribAddress`)

### ISSUE THREAD

**Issue by achalpandeyy** [KhronosGroup/Vulkan-Docs#1661]
The spec gives this formula for the calculation of `attribAddress`:
```
bufferBindingAddress = buffer[binding].baseAddress + offset[binding];

if (bindingDesc.inputRate == VK_VERTEX_INPUT_RATE_VERTEX)
    vertexOffset = vertexIndex * bindingDesc.stride;
else
    if (divisor == 0)
        vertexOffset = firstInstance * bindingDesc.stride;
    else
        vertexOffset = (firstInstance + ((instanceIndex - firstInstance) / divisor)) * bindingDesc.stride;

attribAddress = bufferBindingAddress + vertexOffset + attribDesc.offset;
```
and this section on its alignment requirements:
> For each attribute, raw data is extracted starting at attribAddress and is converted from the VkVertexInputAttributeDescription’s format to either floating-point, unsigned integer, or signed integer based on the base type of the format; the base type of the format must match the base type of the input variable in the shader. The input variable in the shader must be declared as a 64-bit data type if and only if format is a 64-bit data type. If format is a packed format, attribAddress must be a multiple of the size in bytes of the whole attribute data type as described in Packed Formats. Otherwise, attribAddress must be a multiple of the size in bytes of the component type indicated by format (see Formats).

1. What is meant by the `baseAddress` member of `buffer[binding]` and how can I query it? Do I _have_ to use `vkGetBufferDeviceAddress`, and, consequently are device address and base address for the buffer identical?
Can `baseAddress` reasonably be assumed 0 for alignment calculations?

2. Now, assuming `bindingDesc.inputRate == VK_VERTEX_INPUT_RATE_VERTEX`, the formula boils down to:

```
bufferBindingAddress = buffer[binding].baseAddress + offset[binding];
vertexOffset = vertexIndex * bindingDesc.stride;
attribAddress = bufferBindingAddress + vertexOffset + attribDesc.offset;
```

- If I have a single vertex buffer binding, bound at offset 0:
```
offset[binding] = 0
so, bufferBindingAddress = buffer[binding].baseAddress
```
- If my `bindingDesc.stride` is `stride` (say) and `vertexIndex` is in the range [0,3], then:
```
vertexOffset = vertexIndex*stride
vertexOffset = any of { 0*stride, 1*stride, 2*stride, 3*stride }
```
- For the first vertex attribute I have:
```
attribDesc.offset = 0
```

Putting it all together,
```
attribAddress =  buffer[binding].baseAddress + vertexIndex*stride + 0
```
Is this how this calculation supposed to go?

According to the spec "attribAddress must be a multiple of the size in bytes of the component type indicated by format". Which brings to me to my last question:
3. What _exactly_ is meant by "size in bytes of the component type indicated by format" ? Say, I have the format R32B32G32_SFLOAT, would the size value be 12 (4 + 4 + 4) bytes or 4 bytes for just one component (channel)?

**Comment by HansKristian-Work** [comment]
For vertex attributes the alignment is covered by this wording:

If format is a packed format, attribAddress must be a multiple of the size in bytes of the whole attribute data type as described in Packed Formats. Otherwise, attribAddress must be a multiple of the size in bytes of the component type indicated by format (see Formats).

R32G32B32_SFLOAT is not a packed format, so the alignment required is R32_SFLOAT, i.e. 4 bytes.

> buffer[binding].baseAddress

This would be the value of the vkCmdBindVertexBuffers offset. For purposes of alignment, the VkBuffer itself will always be well aligned for any usage, so there's no need to consider buffer device addresses.

**Comment by oddhack** [comment]
@achalpandeyy if @HansKristian-Work's comment answers your question, please close the issue. Thanks.
