### ISSUE TITLE
`vkWaitForPresentKHR` doesn't list `VK_ERROR_OUT_OF_DATE_KHR` as a return code

### ISSUE THREAD

**Issue by rtryan98** [KhronosGroup/Vulkan-Docs#1664]
While the description states that this code may be returned, it is not listed as a return code inside the spec page.
Most likely put it into the "On failure" category.

**Comment by stonesthrow** [comment]
Edit xml/vk.xml, find:
<command successcodes="VK_SUCCESS,VK_TIMEOUT" errorcodes="VK_ERROR_OUT_OF_HOST_MEMORY,VK_ERROR_OUT_OF_DEVICE_MEMORY,VK_ERROR_DEVICE_LOST">
            <proto><type>VkResult</type> <name>vkWaitForPresentKHR</name></proto>

Add VK_ERROR_OUT_OF_DATE_KHR to the list of errorcodes.

**Comment by stonesthrow** [comment]
Looks like this has been added. So this issue can be closed.

**Comment by stonesthrow** [comment]
@chadversary
