### ISSUE TITLE
Typo in extension promotion example

### ISSUE THREAD

**Issue by jeremyong-az** [KhronosGroup/Vulkan-Docs#1665]
https://github.com/KhronosGroup/Vulkan-Docs/blob/9dc6dfbb7aea0999f4108ad0faeee099d0adb173/chapters/extensions.txt#L820

I believe `ename:VK_COLOR_SPACE_SRGB_NONLINEAR_KHR` here should read `ename:VK_COLOR_SPACE_SRGB_NONLINEAR` without the `KHR` suffix correct?

**Comment by stonesthrow** [comment]
All of the WSI is made of extensions because its not a required set of features; you can have a valid Vulkan driver without all or any of the WSI, so its not core. I believe this was part of the initial VK_KHR_surface extension. So the suffix stays. Thanks for keen eyes.

**Comment by stonesthrow** [comment]
The text you reference is the fact that it was VK_COLORSPACE and that changed to VK_COLOR_SPACE and some aliases were created. But won't be promoted per the rule given. But WSI has not been promoted to core spec.
    VK_COLORSPACE_SRGB_NONLINEAR_KHR = VK_COLOR_SPACE_SRGB_NONLINEAR_KHR,

**Comment by jeremyong-az** [comment]
OK thanks I might have misunderstood then thanks
