### ISSUE TITLE
Clarification of `vkSetDebugUtilsObjectName/TagEXT` for instance handles

### ISSUE THREAD

**Issue by pixelcluster** [KhronosGroup/Vulkan-Docs#1668]
In section 45.1.1, in the definition of `vkSetDebugUtilsObjectNameEXT`, the `device` parameter is described as follows:
> `device` is the device that created the object.

This, for me, implies that objects passed in `VkDebugUtilsObjectNameInfoEXT::objectHandle` must have been created from that device. However, this can't be the case for instances or handles created from it, like physical devices, or the device itself. There is also no Valid Usage requirement that would require handles to be created from the device.

This also applies to the definition of `vkSetDebugUtilsObjectTagEXT`.

From experimenting, it seems to be the case that it is valid to pass any valid device handle.

Could the description of the `device` parameter in these commands be expanded to define the behaviour of naming handles that weren't created from any device?

**Comment by baldurk** [comment]
I'd say for objects not created from the device it should require the inverse - that the device is created from them. i.e. the `VkInstance` and `VkPhysicalDevice` it was created from. Other `VkPhysicalDevice` from the instance which weren't used to create the device are a bit ambiguous, I'd be fine with either banning or allowing them though that would require careful wording.

**Comment by oddhack** [comment]
@charles-lunarg Karen suggested you to take a look at this and respond further / perhaps propose an MR as needed.

**Comment by charles-lunarg** [comment]
(Funnily enough I asked baldurk to weigh in on the matter)

I think its sensible to allow the `VkPhysicalDevice`/`VkInstance` that the device was created from to be named. Trickier to word, but hopefully is straight forward to implement. My main concern is changing the spec (to allow it) and it requiring changes to validation layers/renderdoc/other tools for what I perceive to be a low benefit feature. Multi-gpu is the first use case that comes to mind, and that is pretty uncommon. Simple blanket banning it would be better if others think the implementation is unreasonably complex. Inverting dependencies like this can sometimes be tricky.

**Comment by charles-lunarg** [comment]
To follow up:
The people who implement or will implement this feature should be the ones making a final say. EG, renderdoc, validation layers, any other layers & tools which use naming. I'm going to nominate @jeremyg-lunarg to look at this further since he is a VVL maintainer.

**Comment by jeremyg-lunarg** [comment]
> To follow up: The people who implement or will implement this feature should be the ones making a final say. EG, renderdoc, validation layers, any other layers & tools which use naming. I'm going to nominate @jeremyg-lunarg to look at this further since he is a VVL maintainer.

I don't see any problems with implementing this proposal in Vulkan-Validation layers. We already have infrastructure to get to the VkInstance used to create a device and then do lookups for other handles created from the instance (VkPhysicalDevice, VkSurfaceKHR, and VkDisplayModeKHR)

**Comment by krOoze** [comment]
Messengers are created from Instance. Looks like a mistake it is dispatched from a Device. Should probably just add Instance versions of these commands and depracate the device versions.

**Comment by oddhack** [comment]
@pixelcluster #2034 has been published in the current specification update. If that completely addresses this issue, please close it.

**Comment by pixelcluster** [comment]
It does, thanks a lot!
