### ISSUE TITLE
Are offset alignments a power of two?

### ISSUE THREAD

**Issue by plasmacel** [KhronosGroup/Vulkan-Docs#1669]
Unlike `VkMemoryRequirements::alignment`, the spec doesn't give any guarantee that `VkPhysicalDeviceLimits::minTexelBufferOffsetAlignment`, `VkPhysicalDeviceLimits::minUniformBufferOffsetAlignment`, and `VkPhysicalDeviceLimits::minStorageBufferOffsetAlignment` are a power of two. The same for `VkPhysicalDeviceLimits::nonCoherentAtomSize`, `VkPhysicalDeviceLimits::optimalBufferCopyOffsetAlignment`, and `VkPhysicalDeviceLimits::optimalBufferCopyRowPitchAlignment`.

While in practice I expect them to always be a power of two, there is no such wording. Is this intentional or just missing from the spec?

It should be clarified, since this makes a difference at computing the least common multiple of different offset alignment limits, so `std::max` cannot be used instead of `std::lcm`.

**Comment by sfricke-samsung** [comment]
also related https://github.com/KhronosGroup/Vulkan-Docs/issues/1442

I think this just needs CTS tests confirming these all are indeed being power of two and then have the spec explicitly say if or if they aren't required to

**Comment by sfricke-samsung** [comment]
All of these are required for being a power of 2. The 1.2.202 Spec now says this for all cases. Thanks for bringing this up!
