### ISSUE TITLE
VkAccelerationStructureBuildRangeInfoKHR::primitiveCount should be uint64_t.

### ISSUE THREAD

**Issue by spnda** [KhronosGroup/Vulkan-Docs#1670]
`VkAccelerationStructureBuildRangeInfoKHR::primitiveCount` is a `uint32_t`, but `VkPhysicalDeviceAccelerationStructurePropertiesKHR::maxPrimitiveCount` and `VkPhysicalDeviceAccelerationStructurePropertiesKHR::maxInstanceCount` are both `uint64_t`. That doesn't make sense at all, `primitiveCount` *should*  be `uint64_t` as well.

- `maxPrimitiveCount` (uint64_t) ([as per the spec](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPhysicalDeviceAccelerationStructurePropertiesKHR.html#_members)) defines the maximum number of **triangles** a BLAS can have.
- `maxInstanceCount` (uint64_t) defines the maximum number of **instances** a TLAS can have.

- `primitiveCount` (uint32_t) ([as per the spec](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkAccelerationStructureBuildRangeInfoKHR.html#_description)) is number of **triangles** or the amount of **instances** that one specific AS will have for building.

So I theoretically could do `primitiveCount = static_cast<uint32_t>(asProperties.maxPrimitiveCount)` but that would truncate the size of the integer and scale the value down. And as a result of this (probably not intended) it is currently a limitation of the spec that you cannot exceed the `maxPrimitiveCount` and `maxInstanceCount` of any device that has a higher maximum than `UINT32_MAX`. [According to vulkan.gpuinfo.org](https://vulkan.gpuinfo.org/displayextensionproperty.php?extensionname=VK_KHR_acceleration_structure&extensionproperty=maxPrimitiveCount&platform=all) no device is anywhere even close to that (yet) so it's not a major issue.
I also understand that it isn't possible to directly patch this into the docs/header as this would break compatibility with older versions (primitiveCount and primitiveOffset would overlap), but it's worth mentioning and to keep in mind for the future (1.3?).

**Comment by dgkoch** [comment]
This does seem like a bit of an oversight, and it seems like the same issue applies to the maxGeometryCount limit.

On the AS  build side - there is also the `pMaxPrimitiveCounts` parameter to `vkGetAccelerationStructureBuildSizesKHR` and `VkAccelerationStructureBuildGeometryInfoKHR::geometryCount` which are limited to 32-bits as well. 

As you guessed, there is no way we could change it at this point, so our proposed direction is to just add a note in the properties structures noting that the limits should never be bigger than UINT32_MAX.

**Comment by dgkoch** [comment]
Added the following statement in 1.2.199: 

https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#limits-maxPrimitiveCount

"Due to the fact that the geometry, instance, and primitive counts are specified at acceleration structure creation as 32-bit values, maxGeometryCount, maxInstanceCount, and maxPrimitiveCount must not exceed 232-1."
