### ISSUE TITLE
specialization constants and "statically used" definition

### ISSUE THREAD

**Issue by konstantinegorov** [KhronosGroup/Vulkan-Docs#1671]
```
layout(constant_id = 0) const bool useTex1 = true;

layout(binding = 0) uniform sampler2D tex1;
layout(binding = 1) uniform sampler2D tex2;

layout(location = 0) out vec4 outColor;

void main()
{
  if (useTex1)
    outColor = texture(tex1, vec2(0.0));
  else
    outColor = texture(tex2, vec2(0.0));
}
```

Will the "tex2" binding be considered statically used if a pipeline has been specialized with useTex1 = true?

**Comment by r-potter** [comment]
Discussed in the WG today.

Polarina is correct. Static use rules don't assume that compilers will do dead code elimination (or similar transformations), and so tex2 is still statically used.

@konstantinegorov Can we close this as answered, or do you have followup questions/comments?

**Comment by konstantinegorov** [comment]
Thanks for the answer. The issue can be closed.
