### ISSUE TITLE
[1.2.197] `VK_PIPELINE_RASTERIZATION_STATE_CREATE_*` enum variant is not a common prefix of `VK_PIPELINE_CREATE`

### ISSUE THREAD

**Issue by MarijnS95** [KhronosGroup/Vulkan-Docs#1676]
All enum variants have a common prefix that match the name of the enum, and for `VkPipelineCreateFlagBits` this is `VK_PIPELINE_CREATE_*`. However, the `VK_PIPELINE_RASTERIZATION_STATE_CREATE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR` and `VK_PIPELINE_RASTERIZATION_STATE_CREATE_FRAGMENT_DENSITY_MAP_ATTACHMENT_BIT_EXT` variants do not share this prefix.

As far as I'm aware they should be named `VK_PIPELINE_CREATE_RASTERIZATION_STATE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR` and `VK_PIPELINE_CREATE_RASTERIZATION_STATE_FRAGMENT_DENSITY_MAP_ATTACHMENT_BIT_EXT` instead.

**Comment by MarijnS95** [comment]
This has previously also been a problem in at least #1531, should there be some CI/validation that makes sure all enum variant names adhere to these (unwritten?) conventions?

**Comment by oddhack** [comment]
> This has previously also been a problem in at least #1531, should there be some CI/validation that makes sure all enum variant names adhere to these (unwritten?) conventions?

That's reasonable. This is a documented rule in the style guide but there's a lot of stuff in the style guide that people may not think of at the time the initial naming error is made. Similarly there is a notional naming review as part of our release process but human errors still occur.

Likely we will end up creating "spelling aliases" for this as we have in other cases.

**Comment by MarijnS95** [comment]
> > This has previously also been a problem in at least #1531, should there be some CI/validation that makes sure all enum variant names adhere to these (unwritten?) conventions?
> 
> That's reasonable. This is a documented rule in the style guide but there's a lot of stuff in the style guide that people may not think of at the time the initial naming error is made. Similarly there is a notional naming review as part of our release process but human errors still occur.

Good to know, at least we have generators that rely on this property to simplify the names and catch such mistakes.

> Likely we will end up creating "spelling aliases" for this as we have in other cases.

Unfortunately that means we'll have to keep growing our list of edgecases (enum variants that shouldn't be renamed or not made public in the API at all). Understandably so the extension has been published and fixing these names will be considered an API break :(

**Comment by MarijnS95** [comment]
@oddhack Now that I have you here, going through our existing edegecases it seems only:

```xml
        <enum               name="VK_QUERY_SCOPE_COMMAND_BUFFER_KHR" alias="VK_PERFORMANCE_COUNTER_SCOPE_COMMAND_BUFFER_KHR"/>
        <enum               name="VK_QUERY_SCOPE_RENDER_PASS_KHR" alias="VK_PERFORMANCE_COUNTER_SCOPE_RENDER_PASS_KHR"/>
        <enum               name="VK_QUERY_SCOPE_COMMAND_KHR" alias="VK_PERFORMANCE_COUNTER_SCOPE_COMMAND_KHR"/>
```

Are lacking the typical `comment="Backwards-compatible alias containing a typo"`. Can that be added?

**Comment by Tobski** [comment]
Ah whoops - during development of VK_KHR_dynamic_rendering this was at one point a flag on [VkPipelineRasterizationStateCreateInfo](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPipelineRasterizationStateCreateInfo.html)::flags - but I moved them at some point and forgot to rename. Thanks for spotting this!

**Comment by oddhack** [comment]
This should be fixed in the 1.2.200 spec update. The RASTERIZATION_STATE portion of the name was also changed in the new enum to reflect the move @tobski refers to above, and I updated the comments on enum typos for consistency and added an explanatory paragraph in the fundamentals section.

**Comment by oddhack** [comment]
I'm not going to promise that the comment will always get used. There's nothing enforcing that other than feedback. A better test is likely to be to treat as a typo alias, an enum alias that is in the same \<require> block as the thing it's aliasing - that should be much more reliable.

**Comment by MarijnS95** [comment]
Or I'll just keep poking here whenever the comment is inconsistent :wink: - should be good enough feedback.

Perhaps we can even error out when not finding this comment after detecting that `<require>`, but I'll have to see how much effort it takes to get our generator to extract such information in the first place (we're scheduling a rewrite to pull such "analysis" stages apart from "codegen").

One mismatch seems to be in:

```xml
<enum           extends="VkSamplerAddressMode"                  name="VK_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE_KHR" alias="VK_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE" comment="Alias introduced for consistency with extension suffixing rules"/>
```

We really only need the prefix to be the same - stripping off extension suffixes is an optional stage - but we're using this information to decide whether to add the comment as a comment or as a deprecation annotation (fwiw `#[doc = "comment"]` vs `#[deprecated = "comment"]` in Rust).
