### ISSUE TITLE
border color when sampling depth image

### ISSUE THREAD

**Issue by pc-john** [KhronosGroup/Vulkan-Docs#1681]
Vulkan spec does not say much about border color when sampling depth image. Nvidia and Intel seems to always return 0 when sampling outside of depth image valid coordinates.

When looking into spec, the most relevant parts are in [Texel Replacement section](https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/html/chap16.html#textures-texel-replacement) that is included in Image Operations chapter. I expected that setting border color to VK_BORDER_COLOR_FLOAT_OPAQUE_WHITE or VK_BORDER_COLOR_INT_OPAQUE_WHITE would result in sampler returning depth value of 1 when sampling border, but 0 is always returned. Is spec missing something, or is there something I overlooked?

My sampler uses unnormalizedCoordinates, texelFetch on sampler2D with int texture coordinates, VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER, and depth image in one of valid depth formats. All values read from the image seems correct except those outside of image that shall return border value but return 0 instead. Is it my mistake or is spec missing something?

**Comment by HansKristian-Work** [comment]
texelFetch, or fetch operations in general don't take samplers to begin with, so border color does not apply. Sampling outside the bounds hits https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#textures-integer-coordinate-validation

Depth formats are either UNORM or SFLOAT, and those always map to FLOAT types in border color or shaders, similar to color images.

**Comment by pc-john** [comment]
Thanks!
It is interesting how many places we need to study to get the full picture: samplers, texel replacement, resource types (to know that texelFetch uses the same layouts as image samplers, unlike imageRead), image operations overview (to know that sampler is not used in texelFetch), all this texel validation and coordinate system, and finally all these formats - thanks for pointing out that UNORM is FLOAT. I intuitively expected that it is INT, because it is stored as INT. How easily we can be confused..., but it is logical it is FLOAT.
