### ISSUE TITLE
Use of {depth, color} buffer in the specification

### ISSUE THREAD

**Issue by martty** [KhronosGroup/Vulkan-Docs#1684]
The specification talks about depth buffers and sometimes color buffers - this seems like legacy language that describes what Vulkan calls attachments in most contexts. Is there a difference that is not obvious to me?

If there isn't, would a PR be welcome that removes this language in favor of {depth, color} attachments?

**Comment by oddhack** [comment]
Yes, please do make a PR. Can't guarantee there will be no iteration, but we think it's a pretty straightforward fix on casual inspection. Thanks!
