### ISSUE TITLE
VK_EXT_pci_bus_info and VK_EXT_physical_device_drm misclassified?

### ISSUE THREAD

**Issue by haasn** [KhronosGroup/Vulkan-Docs#1685]
These are listed as device extensions, but the only thing they introduce are extensions to `vkGetPhysicalDeviceProperties2`, which is an *instance*-level command. As such, they seem to be more correctly classified as instance-level extensions, such as for example `VK_KHR_external_memory_capabilities`.

Edit: Ah, I see this wording in the spec:

> Each structure included in the pNext chain **must* be defined at runtime by either:
> - ...
> - a supported device extension in the case of physical-device-level functionality added by the device extension

So this is indeed legal as-is, and I suppose the intent is that it's device-level so that ICD vendors are not required to support it?

If this is intentional, feel free to close.

**Comment by r-potter** [comment]
Hi @haasn. It looks like you've made it to the right conclusion. Extensions that add functionality at the physical-device level are regarded as device extensions, even though physical-devices are children of the instance. These extensions can typically be implemented within a single GPU vendors implementation without the need to modify the loader.

There are a few exceptions to this rule, mainly older extensions dating back to the 1.0 days before we developed a preference for limiting instance extensions to cases where they were absolutely necessary. `VK_KHR_external_memory_capabilities` looks to me like it falls into that category.

I think you've answered your own question, so I'm closing this, but please feel free to reopen if you have further questions.
