### ISSUE TITLE
VkWriteDescriptorSet-descriptorType-00322 contradicts section 14.2.8. Push Descriptor Updates

### ISSUE THREAD

**Issue by conor42** [KhronosGroup/Vulkan-Docs#1686]
14.2.8 states:
> To push an immutable sampler, use a VkWriteDescriptorSet with dstBinding and dstArrayElement selecting the immutable sampler’s binding. If the descriptor type is VK_DESCRIPTOR_TYPE_SAMPLER, the pImageInfo parameter is ignored and the immutable sampler is taken from the push descriptor set layout in the pipeline layout.

While VkWriteDescriptorSet-descriptorType-00322 states:
> pImageInfo must be a valid pointer to an array of descriptorCount valid VkDescriptorImageInfo structures

**Comment by oddhack** [comment]
This should be fixed in the 1.2.203 spec update. 00322 was split and moved up into the commands to which VkWriteDescriptorSet is passed, with changes for vkCmdPushDescriptorSetKHR.
