### ISSUE TITLE
Firefox VUID paragraph icons cannot be followed by clicking.

### ISSUE THREAD

**Issue by charles-lunarg** [KhronosGroup/Vulkan-Docs#1690]
Opening up the html spec in firefox, I cannot use the paragraph icons to quickly open/copy the link they. 

For instance, I should be able to click it to get a link like this https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkQueueSubmit.html#VUID-vkQueueSubmit-pSignalSemaphores-00067 but it does nothing.

Chromium works as expected.

**Comment by krOoze** [comment]
It works in singlepage spec, so it must be something wrong with the refpages.

**Comment by oddhack** [comment]
> It works in singlepage (PS: also in chunked) spec, so it must be something wrong with the refpages. The links are added in postprocessing script, so likely it is just not run for refpages.

That sounds right to me. @charles-lunarg can you confirm if the issue you're seeing is confined to the refpages?

**Comment by charles-lunarg** [comment]
I was seeing the issue in the chunked spec, not the ref pages. However, I didn't specify the OS I was using which was linux. On my windows box everything works as expected (in firefox)

I can confirm seeing that the ref pages have the issue.

**Comment by oddhack** [comment]
> I was seeing the issue in the chunked spec, not the ref pages. However, I didn't specify the OS I was using which was linux. On my windows box everything works as expected (in firefox)
> 
> I can confirm seeing that the ref pages have the issue.

Going to https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap29.html#VUID-VkPipelineColorBlendStateCreateInfo-pAttachments-parameter on Firefox 78.15.0esr / Debian 11 I see something like 

![vu](https://user-images.githubusercontent.com/4693344/142130975-032a92be-4cc4-454b-8ce8-6e0febc61c1e.gif)

and hovering over the VUID text brings up a paragraph icon. Clicking on the icon directs to that anchor. This is exactly the same behavior as Chromium 90.0 AFAICT. Can you describe exactly what you're doing and how it differs from other browsers?

**Comment by charles-lunarg** [comment]
The behavior I saw was that the anchor would appear, but attempting to click on it would do nothing. Right clicking on it also wouldn't bring up the 'context menu' with 'open link, in new tab, copy link, etc'. I will try to get a screenshot of it tomorrow when I am back in front of that machine.

**Comment by oddhack** [comment]
I hate to be that guy, but please try to reproduce this in a new Firefox instance with no accumulated state (extensions, cookies, etc.) and make sure you're actually clicking on the paragraph icon - it is really pretty small.

**Comment by oddhack** [comment]
N.b. my screenshot app can't image the context menu when I right-click on the icon because it can't grab the mouse away from the browser, but it's definitely there.

**Comment by charles-lunarg** [comment]
Please *do* be that guy. I tried to repro the issue today on the same machine: No dice. So apologies for the misleading bug report. But I think I have an idea of what was happening. The paragraph icon only appears if you hover over the VUID *then* move to the bullet point. I bet I was expecting the text itself to have the hyperlink, and not the icon. 
I'm going to close this as I think it was a wild goose chase...
