### ISSUE TITLE
Request for new format A1B5G5R5

### ISSUE THREAD

**Issue by Amjad50** [KhronosGroup/Vulkan-Docs#1691]
Hello,

I'm working on PSX emulator, and the PSX gpu's pixels format is `A1B5G5R5`.

I looked at opengl, and there seem to be the format `GL_UNSIGNED_SHORT_1_5_5_5_REV` which does what I need.
Vulkan has more formats than opengl, it has 3 similar formats, but not exactly the same
```
typedef enum VkFormat {
    VK_FORMAT_R5G5B5A1_UNORM_PACK16 = 6,
    VK_FORMAT_B5G5R5A1_UNORM_PACK16 = 7,
    VK_FORMAT_A1R5G5B5_UNORM_PACK16 = 8,
} VkFormat;
```
In the emulator, I receive 16-bit already packed pixel data, so I can't use `A1R5G5B5` for example and replace blue and red easily without manual transformation.

So, can this format be added?

Thanks

**Comment by lewa-j** [comment]
How about using A1R5G5B5 and imageView with VkComponentMapping?

**Comment by Amjad50** [comment]
Yes, I also got this suggestion [in the forum](https://community.khronos.org/t/request-for-new-format-a1b5g5r5/107988/5)

I think it should work, I'll test it later today. Thanks for the suggestion.

**Comment by Amjad50** [comment]
I tried using swizzle, but it does not work for rendering target. It only works for texturing.
In the end I used `A1R5G5B5`, and then used swizzling to copy the whole image to another manually using graphics pipeline. I'm not sure but is there a way to blit image with component swizzle?

**Comment by polarina** [comment]
@Amjad50 would it be possible for you to swizzle the outputs from within the fragment shader?

**Comment by Amjad50** [comment]
Sorry for the delay @polarina .

So for my project, I'm emulating an `image` as a VRAM. This VRAM accepts writes and reads in `A1B5G5R5` format. But since vulkan does not support it, I switched the image format to `A1R5G5B5` and I also output swizzled colored from the fragment shader like you suggest.
With all of that, the image will have the red and color components switched, so in order to display it correctly to the user I swizzle the blue and red components again to the swapchain images manually by rendering a texture rect.

This solution/workaround works, but it can be improved by:
- Supporting `A1B5G5R5` format, this will simplify the whole process and we wouldn't need to use any swizzling.
- Supporting swizzling for image blit, this way we won't need to use a full graphics pipeline just to copy from the VRAM image to the swapchain.

**Comment by krOoze** [comment]
I think most platforms will force you into different format for display, so you need to blit anyway. Until that point you could simply pretend R is B everywhere without any swizzling.

Image blit inside device memory is usually just syntactic sugar for compute shader anyway. So you are using full graphics pipeline anyway. Additionally if you piggyback the swizzle on some previous postprocessing step, it could even be faster than `vkCmdBlit`.

**Comment by jekstrand** [comment]
Adding a format to the spec is easy.  Guaranteeing support is hard.  For instance, Intel can't support this format.

**Comment by Amjad50** [comment]
@jekstrand thanks for the insight. As it's this much complicated, maybe it's better to not add it after all.

**Comment by oddhack** [comment]
@Amjad50 FYI this has been added as a feature request on the Vulkan working group's internal tracking list, but that's no guarantee of if/when this will get done.

**Comment by Amjad50** [comment]
Thank you, that's good enough

**Comment by stu-s** [comment]
This has been addressed in https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_maintenance5.html.  Please close this issue if it has been resolved.

**Comment by Amjad50** [comment]
Thanks @stu-s . This is fixed
