### ISSUE TITLE
More descriptive line rasterization behavior is needed from the PhysicalDeviceLimits

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/Vulkan-Docs#1697]
When strictLines == VK_FALSE, we need to know what the actual rasterization algorithm being used is, parallelogram or Bresenham style. Knowing that it's not strict isn't enough. To draw lines pixel perfect we need to know what the rasterization rules are the GPU is using. Can this be added to PhysicalDeviceLimits (2?) for future versions?
Thanks

**Comment by jeffbolznv** [comment]
Hi,

Thanks for the request. I've added this to the working group's internal tracking list, but that's no guarantee of if/when this will get done. Any additional information you could provide about why you need this would be helpful.

**Comment by mbechard** [comment]
Thanks. In my case I'd like to draw single pixel borders around UI elements. If I know the true line rasterization rule it helps me know where I need to place my lines within a pixel to ensure pixels are included in rasterization.

**Comment by mbechard** [comment]
Yep, seems like that does the trick. Thanks!
