### ISSUE TITLE
Freeing memory that is mapped

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-Docs#17]
As far as I can see there's no spec language that says memory which is mapped with `vkMapMemory` must then be unmapped with `vkUnmapMemory` before it is freed with `vkFreeMemory`.

Is this valid behaviour that unmap is optional if the memory is freed?

**Comment by slippah** [comment]
@baldurk, thanks - looks like a spec bug to me - missing validation condition - since having the driver track what memory is mapped seems pretty un-Vulkanlike. Will poll implementations asap and report.

**Comment by slippah** [comment]
Well, I got that wrong.  VkFreeMemory does an implicit unmap, so it is valid to free mapped memory. All the IHVs agree that this is cheap and won't slow the driver. We had language in the spec about freeing bound memory (that's legal too, just don't use the object), but we forgot to list this case. We will add it to the description of vkFreeMemory - should appear in the next weekly patch drop.

That leaves open the question of the crashing issue you referenced. Could certainly be a driver bug - I doubt there's a conformance test path for this yet, and it's a tough one to test rigorously anyway.  

I'll leave this open in case there's any update - will close when we add the new spec language.

**Comment by baldurk** [comment]
That makes sense, I just wanted to check what was legal and thought this might be a case where it's worth clarifying explicitly that the behaviour is valid. There's no rush from my side to get the spec language updated as long as I know the intention.

The crashing issue I referenced is within RenderDoc - my code was assuming a `vkUnmapMemory` would happen before a `vkFreeMemory` and so ended up with dangling references. I can fix that myself fairly easily, it's not a problem with any drivers/conformance tests.

**Comment by jeffbolznv** [comment]
FWIW, drivers (well, depending on the platform) already need to track the mapping to implement the VkMappedMemoryRange operations.

**Comment by oddhack** [comment]
Done in the 1.0.5 spec update.
