### ISSUE TITLE
vkAcquireNextImageKHR return values

### ISSUE THREAD

**Issue by ratchetfreak** [KhronosGroup/Vulkan-Docs#170]
> If timeout is 0, vkAcquireNextImageKHR will not block, but will either succeed or return VK_TIMEOUT.

However a bit down it says it can return:

> * VK_NOT_READY is returned if timeout is zero and no image was available.

And the return codes in valid usage don't mention VK_NOT_READY

**Comment by ratchetfreak** [comment]
in 1.0.10 it was updated but VK_NOT_READY is still not included in the valid return codes.

**Comment by ianelliottus** [comment]
Yes, we just discovered this, after it was too late for this week's release.  It will be in next week's release.  Thanks for catching this.

**Comment by oddhack** [comment]
Should have been fixed in the 1.0.10 spec update.
