### ISSUE TITLE
read-only depth stencil attachment and general layout

### ISSUE THREAD

**Issue by konstantinegorov** [KhronosGroup/Vulkan-Docs#1702]
> For depth/stencil attachments, each aspect can be used separately as attachment and non-attachment as long as the non-attachment accesses are also via an image subresource in either the VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL layout or the VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL layout, and the attachment resource uses whichever of those two layouts the image accesses do not.

Why cann't VK_IMAGE_LAYOUT_GENERAL be used for read-only depth/stencil attachment?

**Comment by HansKristian-Work** [comment]
The GENERAL layout allows writes, and for simultaneous use as non-attachment, you need to give the guarantee to the driver that the attachment is indeed read-only.

**Comment by oddhack** [comment]
Closing - question has been answered (if not, please reopen with additional comments).

**Comment by prideout** [comment]
See also #1340
