### ISSUE TITLE
VkPhysicalDeviceRasterizationOrderAttachmentAccessFeaturesARM lacks `structextends="VkPhysicalDeviceFeatures2,VkDeviceCreateInfo"`

### ISSUE THREAD

**Issue by DadSchoorse** [KhronosGroup/Vulkan-Docs#1703]
Trivial mistake but this breaks various generator scripts.
Also `returnedonly="true"` doesn't look quite right either.

**Comment by janharaldfredriksen-arm** [comment]
Thanks for catching this - don't know how I missed it.
Fix coming shortly.

**Comment by oddhack** [comment]
This should be fixed in the 1.2.201 spec update.
