### ISSUE TITLE
share memory between physical devices

### ISSUE THREAD

**Issue by Avokadoen** [KhronosGroup/Vulkan-Docs#1707]
[VK_KHR_external_memory] @cubanismo
Can this be used to share memory i.e image data between two independent physical devices, and would that require the data to pass through the CPU?

**Comment by jekstrand** [comment]
Sharing between distinct physical devices is explicitly out-of-scope for VK_KHR_external_memory.  Depending on your OS, there may be other ways to get at it.  On Linux, if your Vulkan implementation supports VK_EXT_external_memory_dma_buf, that can be used to share between distinct devices.  In that case, it will end up in system memory.  You can also potentially use VK_EXT_external_memory_host to import the same host pointer into two different devices.  Again, that's going land in system memory.

**Comment by Avokadoen** [comment]
Thank you for the answer @jekstrand! Too bad there isn't a portable (windows, linux & mac) solution to this but I can see why there isn't
