### ISSUE TITLE
[VK_NVX_binary_import] VkCuLaunchInfoNVX

### ISSUE THREAD

**Issue by sultim-t** [KhronosGroup/Vulkan-Docs#1709]
The paramCount, pParams, extraCount, pExtras should be marked as optional in https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkCuLaunchInfoNVX.html
These values can be null. Currently, they marked "must jot be 0"

Because of that ValidationLayers report those values like they're incorrect. Found while integrating DLSS SDK.

Detailed description:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3576

**Comment by oddhack** [comment]
This should be fixed in the 1.2.203 spec update.
