### ISSUE TITLE
VkPresentInfoKHR documentation contradicts itself

### ISSUE THREAD

**Issue by tomaka** [KhronosGroup/Vulkan-Docs#171]
[This line](https://github.com/KhronosGroup/Vulkan-Docs/blob/dc77785233fd17c96ce8d339ad04d732f9e4279f/doc/specs/vulkan/validity/structs/VkPresentInfoKHR.txt#L16) says:

> * The value of pname:waitSemaphoreCount must: be greater than `0`

But [this line](https://github.com/KhronosGroup/Vulkan-Docs/blob/dc77785233fd17c96ce8d339ad04d732f9e4279f/doc/specs/vulkan/chapters/VK_KHR_swapchain/wsi.txt#L498) says (about `VkPresentInfoKHR`):

>   * pname:waitSemaphoreCount is the number of semaphores to wait for before issuing the present request.  The number may: be zero.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.11 spec update.
