### ISSUE TITLE
Why does vkCmdCopyBufferToImage for the stencil aspect require bufferOffset to be a multiple of 4?

### ISSUE THREAD

**Issue by austinEng** [KhronosGroup/Vulkan-Docs#1712]
VUID-vkCmdCopyBufferToImage-bufferOffset-00193 requires a multiple of the texel block size instead for non-depth/stencil formats., however [VUID-vkCmdCopyBufferToImage-srcImage-04053](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdCopyBufferToImage.html#VUID-vkCmdCopyBufferToImage-srcImage-04053) requires that the bufferOffset of any of the copied regions be a multiple of 4.

The 4-byte requirement makes sense when the copied texels are 4-bytes wide. According to the spec is the case for:
 - the depth aspect of a VK_FORMAT_D32_SFLOAT or VK_FORMAT_D32_SFLOAT_S8_UINT format is tightly packed with one VK_FORMAT_D32_SFLOAT value per texel
 - the depth aspect of a VK_FORMAT_X8_D24_UNORM_PACK32 or VK_FORMAT_D24_UNORM_S8_UINT format is packed with one 32-bit word per texel...

However, for stencil, the spec says:
 - data copied to or from the stencil aspect of any depth/stencil format is tightly packed with one VK_FORMAT_S8_UINT value per texel

So, since the copied data is tightly packed 1-byte values, is it necessary to have the bufferOffset be a multiple of 4? Or could that restriction be lifted?

**Comment by sfricke-samsung** [comment]
This was brought up internally https://gitlab.khronos.org/vulkan/vulkan/-/issues/1701 a while ago

1 byte dst copies for stencil are apparently not supported in D3D11 and no one is in a need to push for something more flexible, so the `VUID-vkCmdCopyBufferToImage-srcImage-04053` was added a quick fix until someone was willing to push more for it (as in taking time to make sure there are CTS tests)

**Comment by Tobski** [comment]
@austinEng Is this causing implementation difficulties for you? Changing it would require some non-trivial effort (which is why we didn't do it in the first place) so we'd like to make sure there's a tangible benefit to doing this before we dive in. I think we're happy to do this if it's actually useful.

**Comment by oddhack** [comment]
@austinEng can you respond to @tobski above? Otherwise if this issue is no longer a concern for you, please close.
