### ISSUE TITLE
External synchronization requirements of UPDATE_UNUSED_WHILE_PENDING_BIT

### ISSUE THREAD

**Issue by plasmacel** [KhronosGroup/Vulkan-Docs#1713]
> **`VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT`** indicates that if descriptors in this binding are updated between when the descriptor set is bound in a command buffer and when that command buffer is submitted to a queue, then the submission will use the most recently set descriptors for this binding and the updates do not invalidate the command buffer. Descriptor bindings created with this flag are also partially exempt from the external synchronization requirement in `vkUpdateDescriptorSetWithTemplateKHR` and `vkUpdateDescriptorSets`. **Multiple descriptors with this flag set can be updated concurrently in different threads, though the same descriptor must not be updated concurrently by two threads.** Descriptors with this flag set can be updated concurrently with the set being bound to a command buffer in another thread, but not concurrently with the set being reset or freed.

and

> **`VK_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT`** indicates that descriptors in this binding can be updated after a command buffer has bound this descriptor set, or while a command buffer that uses this descriptor set is pending execution, as long as the descriptors that are updated are not used by those command buffers. If `VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT` is also set, then descriptors can be updated as long as they are not dynamically used by any shader invocations. If `VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT` is not set, then descriptors can be updated as long as they are not statically used by any shader invocations.

while

> Note that while `VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT` and `VK_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT` both involve updates to descriptor sets after they are bound, `VK_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT` is a weaker requirement since it is only about descriptors that are not used, whereas `VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT` requires the implementation to observe updates to descriptors that are used.

It seems that a descriptor binding with `VK_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT` is just an unsynchronized chunk of data, where the user is responsible to externally sync its updates within the set so no data races can happen on it between the CPU and GPU, i.e. if it the descriptor is unused, it can be updated even when the descriptor set is used on the GPU in shader invocations.

Is there any actual reason that in the spec `VK_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT` doesn't provide the external synchronization requirement relaxation 

> "Multiple descriptors with this flag set can be updated concurrently in different threads, though the same descriptor must not be updated concurrently by two threads. "

in `vkUpdateDescriptorSetWithTemplateKHR` and `vkUpdateDescriptorSets` similar to `VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT`?

**Comment by janharaldfredriksen-arm** [comment]
Thanks! We agree there are some inconsistencies here. The intent is to relax the external synchronization requirements for both vkUpdate* functions.

**Comment by plasmacel** [comment]
You also mean identically both for `UPDATE_AFTER_BIND_BIT ` and `UPDATE_UNUSED_WHILE_PENDING_BIT`?

**Comment by janharaldfredriksen-arm** [comment]
Yes.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.223 spec update.
