### ISSUE TITLE
Improve the wording of vkCmdBindDescriptorSets

### ISSUE THREAD

**Issue by plasmacel** [KhronosGroup/Vulkan-Docs#1714]
In most cases the spec uses the term *binding* to describe slots where something can be bound to, just like with `VkDescriptorSetLayoutBinding` and `VkVertexInputBindingDescription`, etc.

Then the wording of `vkCmdBindDescriptorSets`:

> `vkCmdBindDescriptorSets` causes the sets numbered `[firstSet.. firstSet+descriptorSetCount-1]` to use the bindings stored in `pDescriptorSets[0..descriptorSetCount-1]`

is semantically confusing at least.

`pDescriptorSets` store descriptor sets, not *bindings*, furthermore according to the consistent terminology, descriptor set *bindings* (i.e. binding points) are `[firstSet.. firstSet+descriptorSetCount-1]`.

I think the wording should be improved here.

**Comment by sfricke-samsung** [comment]
Hey @plasmacel the Working Group agreed the wording could be improved, but we first wanted to get your opinion on what you think the wording should sound like, to prevent us making a change and not solving the issue for you.

**Comment by plasmacel** [comment]
Since the wordings of `vkCmdBindDescriptorSets` consistently use the term **set number** to describe descriptor set binding slots, I think that

`vkCmdBindDescriptorSets` binds descriptor sets `pDescriptorSets[0..descriptorSetCount-1]` to set numbers `[firstSet.. firstSet+descriptorSetCount-1]` for subsequent bound pipeline commands set by `pipelineBindPoint`. Any bindings that were previously applied via these sets are no longer valid.

would be sufficient.

**Comment by oddhack** [comment]
@plasmacel would you be comfortable proposing a PR with this language, to help drive the issue?

**Comment by plasmacel** [comment]
This is fixed with commit #1732.
