### ISSUE TITLE
Vulkan robustBufferAccess vertex buffer OOB access clarification.

### ISSUE THREAD

**Issue by lokokung** [KhronosGroup/Vulkan-Docs#1715]
To cite the specs that relate to the ambiguity:

[[1]](https://www.khronos.org/registry/vulkan/specs/1.2/html/vkspec.html#:~:text=robustBufferAccess%20specifies%20that%20accesses%20to%20buffers%20are%20bounds%2Dchecked%20against%20the%20range%20of%20the%20buffer%20descriptor%20(as%20determined%20by%20VkDescriptorBufferInfo%3A%3Arange%2C%20VkBufferViewCreateInfo%3A%3Arange%2C%20or%20the%20size%20of%20the%20buffer))
```
robustBufferAccess specifies that accesses to buffers are bounds-checked against the range of the buffer descriptor (as determined by VkDescriptorBufferInfo::range, VkBufferViewCreateInfo::range, or the size of the buffer).
```

[[2]](https://www.khronos.org/registry/vulkan/specs/1.2/html/vkspec.html#:~:text=If%20a%20vertex%20input%20attribute%20is%20out%20of%20bounds,%20it%20will%20be%20assigned%20one%20of%20the%20following%20values:) 
```
If a vertex input attribute is out of bounds, it will be assigned one of the following values:

- Values from anywhere within the memory range(s) bound to the buffer, converted according to the format of the attribute.

- Zero values, format converted according to the format of the attribute.

- Zero values, or (0,0,0,x) vectors, as described above.
```

The problem is best explained via example that we saw occur with the simplified sequence here:
- Allocate, create, and fill buffer `buffer_0` starting at memory address `m` for 1024 bytes with value `x`.
- Recycle `buffer_0` back to memory pool.
- Allocate new vertex buffer `buffer_1` of size 16. Get requirements to bind `buffer_1` to memory address `m` and see that the size requirement is 256.
- Bind `buffer_1` at `m`.
- Invoke an OOB read in `buffer_1` and see that we get `x` from the read.

IIUC, the explanation is because of the first case in [2]. Normally, one way to make sure that we don't read `x` and read 0 instead would be to zero out all the memory between offset 16-256, however, this is not possible with the original buffer binding because filling a buffer does not allow writing in those OOB offsets. To work-around this, we are currently creating a second buffer handle with the size reflected in the requirement and then using that to zero out the "padding". It would be nice to clarify if this is the expected behavior and whether our workaround makes sense, or if there is a better way to do this.

**Comment by janharaldfredriksen-arm** [comment]
That seems about right to me. Implementations won't zero out memory that's recycled.

For the workaround, if the memory is host visible you could possibly use vkMapMemory instead of a separate buffer to zero out the memory range.

**Comment by jekstrand** [comment]
> To work-around this, we are currently creating a second buffer handle with the size reflected in the requirement and then using that to zero out the "padding".

This seems like the right workaround.  I'm not sure the spec actually guarantees this will work but I would expect it to work in practice.  There may be some spec work to do here to guarantee that, if your buffer size is aligned to `SOMETHING`, then you're guaranteed that the memory requirements size will equal the buffer size.  We don't have that in the spec now AFAIK but it doesn't seem like a crazy ask and I'd expect what you're doing to work in practice on sensible drivers.

**Comment by oddhack** [comment]
@lokokung if the responses above are sufficient, please close this. Thanks.

**Comment by lokokung** [comment]
Ah, yes sorry. Closing this for now then!
