### ISSUE TITLE
vkCmdCopyQueryPoolResults doesn't support timestamp queries on transfer queues

### ISSUE THREAD

**Issue by libcg** [KhronosGroup/Vulkan-Docs#1717]
According to the current spec, `vkCmdCopyQueryPoolResults` only supports graphics and compute queues. However `vkCmdWriteTimestamp` supports graphics, compute and transfer queues. Is there a technical reason for not being able to copy timestamp query results using a transfer queue? Thanks.

**Comment by jekstrand** [comment]
It's intentional.  Some hardware needs to be able to run a compute shader to do the diff operation to compute the final query result for non-timestamp queries that have begin/end.

**Comment by oddhack** [comment]
Closing per @jekstrand's comment.
