### ISSUE TITLE
`ppEnabledExtensionNames` erroneously referred to as `ppEnabledExtensions`

### ISSUE THREAD

**Issue by helenginn** [KhronosGroup/Vulkan-Docs#1719]
This comes with the caveat that I am entirely new to Vulkan as of yesterday.

In handling a validation error,

```VUID-VkDeviceCreateInfo-pProperties-04451(ERROR / SPEC): msgNum: 976972960 - Validation Error: [ VUID-VkDeviceCreateInfo-pProperties-04451 ] Object 0: handle = 0x7f8260e54900, type = VK_OBJECT_TYPE_PHYSICAL_DEVICE; | MessageID = 0x3a3b6ca0 | vkCreateDevice: VK_KHR_portability_subset must be enabled because physical device VkPhysicalDevice 0x7f8260e54900[] supports it The Vulkan spec states: If the VK_KHR_portability_subset extension is included in pProperties of vkEnumerateDeviceExtensionProperties, ppEnabledExtensions must include "VK_KHR_portability_subset" (https://vulkan.lunarg.com/doc/view/1.2.198.1/mac/1.2-extensions/vkspec.html#VUID-VkDeviceCreateInfo-pProperties-04451)```

I notice a reference to `ppEnabledExtensions` that, through context, I would have expected to be `ppEnabledExtensionNames`, and I cannot find `ppEnabledExtensions` mentioned anywhere on khronos.org. I am wondering if this is a typo in the validation error. Feel free to close if I missed something obvious.

Originally submitted to Vulkan-ValidationLayers, and advised to repost here ( https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3599 )

**Comment by ziga-lunarg** [comment]
To give more context, some VUIDs in the spec under VkDeviceCreateInfo use `ppEnabledExtensionNames`, but others use `ppEnabledExtensions`, which seems wrong.

**Comment by oddhack** [comment]
Thanks! That's a good catch, and has been lurking since Vulkan 1.2 was initially released :-( Hopefully will have a fix in the next spec update.

**Comment by oddhack** [comment]
This should be fixed in the 1.2.203 spec update.
