### ISSUE TITLE
Mistake in VkLayerProperties

### ISSUE THREAD

**Issue by faserg1** [KhronosGroup/Vulkan-Docs#172]
VkLayerProperties members is:
char layerName[VK_MAX_EXTENSION_NAME_SIZE];
uint32_t **specVersion**;
uint32_t implementationVersion;
char description[VK_MAX_DESCRIPTION_SIZE];

But description of structure members writed for layerName, **apiVersion**, implementationVersion, description.

**Comment by oddhack** [comment]
Thanks. We'll fix the typo, probably in next week's update.

**Comment by oddhack** [comment]
Should have been fixed in the 1.0.10 spec update.
