### ISSUE TITLE
Missing VK_TIME_DOMAIN_MAX_ENUM_EXT enum in VkTimeDomainEXT

### ISSUE THREAD

**Issue by skaarj1989** [KhronosGroup/Vulkan-Docs#1722]
**vulkan_core.h** in `Vulkan SDK 1.2.198.1`
![image](https://user-images.githubusercontent.com/34756939/147274207-8ba8e12f-6448-4cd1-9f41-f4b54b334389.png)

https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VkTimeDomainEXT
![image](https://user-images.githubusercontent.com/34756939/147274166-2e591802-8f1f-47ce-afa4-11f604fc1477.png)

**Comment by nanokatze** [comment]
This is intentional, you'll notice the same thing for other enums as well

**Comment by skaarj1989** [comment]
@nanokatze That's very unfortunate for a tool (like [glad](https://github.com/Dav1dde/glad)) that uses the specs to generate a loader.

**Comment by nanokatze** [comment]
Tools like glad use or should be using vk.xml to generate a loader. MAX_ENUM is not in there though, it's emitted by a generator, that uses vk.xml as its input.

**Comment by krOoze** [comment]
Also, code depending on the `MAX` enums is invalid:

> This special value exists only to ensure that C enum types are 32 bits in size. It is not part of the API, and **should** not be used by applications.
