### ISSUE TITLE
Variable-sized descriptor nomenclature

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#1724]
Descriptor indexing added the concept of "variable-sized descriptor"s. However, this terminology is not used universally in the spec.

For example, in the description for `VkDescriptorSetVariableDescriptorCountAllocateInfo`, it talks about a "variable count descriptor binding" or "variable descriptor count binding". Everywhere else uses the term "variable-sized descriptor" (with the hyphen).

It'd be really good if the same name were used everywhere, so that one could track down how this works more easily.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.207 spec update.
