### ISSUE TITLE
Capturing left/right keys in chunked HTML documentation is not good

### ISSUE THREAD

**Issue by adam-sawicki-a** [KhronosGroup/Vulkan-Docs#1734]
I noticed that recently the chunked online HTML documentation https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/index.html started capturing left/right keys for opening previous/next chapter. I tried to find an issue/PR ticket about it but I couldn't, so I'm creating a new one. I think this is a bad idea.

My use case is that I select some text (I use Chrome browser) and I want to narrow/extend the selection by using Ctrl+Shift+Left/Right keys. It used to work before.

Regardless of use case, I think that reloading the entire page to previous/next chapter is a rarely needed command that should not be assigned to simply left/right keys. Maybe it would be better to put some "<< Previous | Next >>" links at the beginning and end of each chapter page?

**Comment by oddhack** [comment]
I suggest moving this to the https://github.com/wshito/asciidoctor-chunker/ repository - for our purposes it's a black box which we feed the single-page HTML document into and get chunked output from, but the author may be able to offer some options if you want to follow up with them. Possibly custom CSS could be used if that's where the capture is occurring.

**Comment by adam-sawicki-a** [comment]
OK, I posted a comment in https://github.com/wshito/asciidoctor-chunker/issues/14.
