### ISSUE TITLE
Wrong naming in VkPhysicalDeviceDeviceGeneratedCommandsPropertiesNV 

### ISSUE THREAD

**Issue by DanielBaumert** [KhronosGroup/Vulkan-Docs#1736]
Extend the #1735 issue.

In the documentation, the members  ``minSequenceCountBufferOffsetAlignment`` and ``minSequenceIndexBufferOffsetAlignment`` of ``VkPhysicalDeviceDeviceGeneratedCommandsPropertiesNV`` doesn't seem to be aligned with the name used in the struct.
(missing ``s`` on the end of ``Sequence``)

Is this a coincidence or correct?

[VkPhysicalDeviceDeviceGeneratedCommandsPropertiesNV](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPhysicalDeviceDeviceGeneratedCommandsPropertiesNV.html)

Daniel Baumert

**Comment by pdaniell-nv** [comment]
This will also be fixed by https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5015. This wasn't intentional, just a mistake. Thanks for spotting and reporting it.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.205 spec update.
