### ISSUE TITLE
Clarification about oldSwapchain needing to be from the same logical device

### ISSUE THREAD

**Issue by CodingRays** [KhronosGroup/Vulkan-Docs#1737]
In the specifications of VkSwapchainCreateInfoKHR and vkCreateSwapchainKHR there is no information about whether or not it is valid usage to have an old swapchain that is from a different device than the newly created one. 

This seemed suspicious so i was wondering if this is actually valid usage and if that can be clarified in the spec?

**Comment by stonesthrow** [comment]
Thank you for catching this. It does need a clarification. Please give us a week, its on agenda for discussion and we'll decide a clarification and get back to you.

**Comment by stonesthrow** [comment]
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap3.html#fundamentals-objectmodel-overview
No this is not allowed.

**Comment by CodingRays** [comment]
Ok thank you for the clarification.

**Comment by stonesthrow** [comment]
Rather than just adding a VU for this, we have a lengthy discussion and are going to do something more systemic in the VU generation.
