### ISSUE TITLE
Question about defined future used enums in vk.xml

### ISSUE THREAD

**Issue by DanielBaumert** [KhronosGroup/Vulkan-Docs#1738]
In the Vk.xml there are a few types with a comment "[...]FlagBits [...] defined in the future" and three of them are defined as types. (VkQueryPoolCreateFlagBits, VkInstanceCreateFlagBits and VkDeviceCreateFlagBits)

What about the rest of the types with that comment, because they are missing at the moment? 
e.g.: 
```
VkPipelineInputAssemblyStateCreateFlags - Will add VkPipelineStateFlagBits when bits are defined in the future
VkPipelineLayoutCreateFlags - Will add VkPipelineLayoutCreateFlagBits when bits are defined in the future
VkPipelineMultisampleStateCreateFlags - Will add VkPipelineMultisampleStateCreateFlagBits when bits are defined in the future
VkPipelineRasterizationStateCreateFlags - Will add VkPipelineRasterizationStateCreateFlagBits when bits are defined in the future
VkPipelineTessellationStateCreateFlags - Will add VkPipelineTessellationStateCreateFlagBits when bits are defined in the future
VkPipelineVertexInputStateCreateFlags - Will add VkPipelineVertexInputStateCreateFlagBits when bits are defined in the future
VkPipelineViewportStateCreateFlags - Will add VkPipelineViewportStateCreateFlagBits when bits are defined in the future
```

Daniel Baumert

**Comment by oddhack** [comment]
We had some consistency issues about this. The FlagBits types are literally useless until some extension introduces bit reservations so they shouldn't appear in the headers, although there may be some legacy concerns about actually taking them out of the XML. I'll propose a change removing them and see if any IHVs push back.

**Comment by oddhack** [comment]
There are definitions of those three FlagBits types in vk.xml. However, the definitions will never be reached by the dependency chain of any API generated from the XML. The other FlagBits types which have no bits defined don't have a definition in the XML and will need one added at the point that an extension introduces such a bit. It is an inconsistency, agreed, but not one which should have any actual effect on consumers of the XML.

I realize that some people are consuming the XML using their own code. If that code is trying to do something with such an unreachable definition, it should not.

**Comment by oddhack** [comment]
Closing. I don't think there's something actionable for us here.
