### ISSUE TITLE
VUID-VkImageViewCreateInfo-image-04971: `flags` is used wrong

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-Docs#1740]
VUID-VkImageViewCreateInfo-image-04971 refers to the `flags` variable, which is one of the fields of the `VkImageViewCreateInfo` struct. However, in this VUID, what it actually intends to refer to is the `flags` that `image` was created with, not those of the view being created.

**Comment by sfricke-samsung** [comment]
You are right, the Validation Layers are using the correct image flags, but the spec could better express it means the `VkImageCreateInfo::flags`. Will get a spec fix in for this

**Comment by oddhack** [comment]
This should be fixed in the 1.3.205 spec update.
