### ISSUE TITLE
Missing SPV_KHR_device_group extension in vk.xml

### ISSUE THREAD

**Issue by ilkkasaa** [KhronosGroup/Vulkan-Docs#1745]
I found this problem while I was fixing validation errors in dEQP. dEQP test `dEQP-VK.compute.device_group.device_index` emits the following validation error:
 ```ERROR: Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-04146 ] Object 0: handle = 0x2576e3b9670, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xd80a42ae | vkCreateShaderModule(): A SPIR-V Extension (SPV_KHR_device_group) was declared that is not supported by Vulkan. The Vulkan spec states: pCode must not declare any SPIR-V extension that is not supported by the API, as described by the Extension section of the SPIR-V Environment appendix (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-04146) (code 0x00000000 from Validation at Device:ffffffffd80a42ae)```

Validation Layer seems to check properly that the used SPIR-V extensions are supported by Vulkan, but the problem is that the extension `SPV_KHR_device_group` is not listed the in vk.xml, and that is also used to generate the Validation Layer's list of supported extensions.

However, I can't find any reference to `SPV_KHR_device_group` in Vulkan spec, so I'm not completely sure, if this should be supported by Vulkan or not, but while the device group functionality has been promoted to Vulkan 1.1 and there's the `VK_KHR_device_group` extension for Vulkan 1.0, it seems that the SPIR-V extension should be supported too.

**Comment by sfricke-samsung** [comment]
The `DeviceGroup` capability is in the XML, but I think this is just a simple oversight that was missed when adding the auto-gen XML information because, as stated, `SPV_KHR_device_group` is not listed anywhere in the spec and it probably how I missed adding it in

Will get a fix for this!

**Comment by oddhack** [comment]
This should be fixed in the 1.3.205 spec update.
