### ISSUE TITLE
Need statement about when pointers to user memory are used.

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#175]
Consider the command `vkCmdPushConstants`. It takes a pointer to user-allocated host memory, and will copy that data somewhere. The question is... when does it perform the copy?

It could perform the copy immediately, thus storing the data in the command buffer. Or it could store the pointer and read the user's memory as the command buffer is executed. That is, at the time the `vkCmdPushConstants` function executes in the queue.

At present, the Vulkan specification does not explicitly state when it will read from user memory. And this is true of every Vulkan function that takes pointers to host objects (all of the `*CreateInfo` structs, etc). There is nothing in the specification preventing an implementation from reading from those pointers at a later date.

I think the Vulkan specification should have a general statement, perhaps in section 2.4, that states that, unless otherwise stated, all user-allocated host pointers will no longer be accessed after the function returns. With the allocator functions being an exception in many cases.

**Comment by tomaka** [comment]
Section 2.3.1 says:

> Application-owned memory is immediately consumed by any Vulkan command it is passed into. The application can alter or free this memory as soon as the commands that consume it have returned.

Is that what you were talking about?

**Comment by podain** [comment]
Implementation can copy allocator callbacks too. So allocator does not necessarily be an exception. Any exposed structure (not opaque) can be considered as a grouping of arguments. But I agree on the general statement that the user-allocated memory will no longer be accessed after the function returns.

**Comment by NicolBolas** [comment]
> Is that what you were talking about?

Fair enough.
