### ISSUE TITLE
Relationship between `format` of image view and sampler YCbCr conversion

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-Docs#1752]
Both `VkImageViewCreateInfo` and `VkSamplerYcbcrConversionCreateInfo` include a `format` field, and have various VUIDs mentioning that format. But what I can't seem to find is any explanation of how these two formats relate to each other when creating an image view *with* a sampler YCbCr conversion. Should they be identical, merely compatible, or something else? At the moment there are no VUIDs which restrict it, so almost any combination of formats is allowed, which is probably not intended.

**Comment by sfricke-samsung** [comment]
The WG agreed that the `format` should be the same and that this is really just missing a VU that I plan to get added... thanks for pointing this out

**Comment by oddhack** [comment]
This should be fixed in the v1.3.209 spec update.
