### ISSUE TITLE
Empty VkPrivateDataSlotCreateFlagBits Enum type

### ISSUE THREAD

**Issue by Dav1dde** [KhronosGroup/Vulkan-Docs#1754]
The spec contains empty enums, e.g.:
https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPrivateDataSlotCreateFlagBitsEXT.html

```
// Provided by VK_VERSION_1_3
typedef enum VkPrivateDataSlotCreateFlagBits {
} VkPrivateDataSlotCreateFlagBits;
```

Compiling that with gcc `gcc -c /tmp/a.c`:

```
/tmp/a.c:2:1: error: empty enum is invalid
    2 | } VkPrivateDataSlotCreateFlagBits;
      | ^
```

What is the recommended way of dealing with that?

**Comment by Dav1dde** [comment]
The approach I took in glad was to simply not generate empty enumerations, but this lead to problems with VK 1.3, since now there are aliases to empty enums. Now I also check if aliases refer to empty enums, which complicates the generation a bit.

**Comment by oddhack** [comment]
Ideally there would be a CI test preventing empty FlagBits types when building the headers. We were not good about enforcing this historically and it's painful to pull something out of the header and spec even when it has no utility in the API until some bits are defined.
