### ISSUE TITLE
Pageable device local memory clarification

### ISSUE THREAD

**Issue by georgeouzou** [KhronosGroup/Vulkan-Docs#1759]
Hello all,

Some questions about VK_EXT_pageable_device_local_memory:

The [spec](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_EXT_pageable_device_local_memory.html) says: 
_"When enabled the Vulkan implementation will allow device-local memory allocations to be paged in and out by the operating system"_

1) Does disabling the feature mean that paging for this application is strictly disallowed by the system? 
2) Does disabling the feature mean that allocations for this application that go beyond the local heap size will always return VK_ERROR_OUT_OF_DEVICE_MEMORY?
3) Do we get performance implications when enabling the feature but we are staying within the recommended budget? (by querying it through VK_EXT_memory_budget)
4) Does vkSetDeviceMemoryPriorityEXT overshadow the priority value specified through VkMemoryPriorityAllocateInfoEXT ?

**Comment by pdaniell-nv** [comment]
1. No, paging may still occur. The spec just guarantees it will occur when enabled, and not some other undefined behavior.
2. Possibly, but not necessarily on systems with paging. Some implementations might have returned VK_ERROR_OUT_OF_DEVICE_MEMORY, some might have permanently moved the allocation host memory, some might have dynamically moved to host memory. Also memory exhaustion was at the mercy of what else was going on in the system, which also lead to unpredictable results.
3. As long as nothing else causes the memory to page, like another foreground application needing the memory, the performance should be full speed. Querying the memory budget is a snapshot in time on a multi-application OS, so being within budget now might not be true moments from now. With a good paging implementation, once your application is the foreground application, and your memory usage easily fits within the physical capabilities of the device, you should have all your allocations in device local memory, and the memory allocation of background applications should be the ones paged out.
4. Yes, you can change the memory priority after allocation.

**Comment by georgeouzou** [comment]
Thanks @pdaniell-nv for the quick response. 
As for 3) isn't querying the budget from time to time and trying to stay below it recommended?

**Comment by pdaniell-nv** [comment]
3. The heapBudget and heapUsage come from the OS. For Windows that's documented [here](https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_4/ns-dxgi1_4-dxgi_query_video_memory_info). Keeping your heapUsage below your heapBudget should mean your foreground application can run full speed with nothing paged out. The heapBudget may get smaller if other applications (or the OS) reserves memory, but hopefully everybody is fair so the budget shouldn't go down too much. It's probably a good idea to monitor the budget.

**Comment by georgeouzou** [comment]
Thank you @pdaniell-nv for all the answers!

**Comment by Squall-Leonhart** [comment]
I see this is in the latest VK Beta drivers @pdaniell-nv, but only for Linux, is there a possibility of it coming to Windows, as emulators and DXVK(On Windows) would benefi.

**Comment by pdaniell-nv** [comment]
For Windows this extension has been supported in our general release drivers for quite a while on Turing+ (GTX 16x0+ and RTX 20x0+) GPUs. If you have an example of it not being exposed, can you share the vulkaninfo and I'll take a look. Thanks.

**Comment by Squall-Leonhart** [comment]
Ah, no support on Pascal than, thats disappointing.

The extension would be very useful on these older cards particularly at the 1060 3G and 1050 levels as such cards on a typical users system is already having a good portion of vram consumed by various accelerated apps (Discord, Chrome),  but if the MMU design for them doesn't allow it, its understandable.
