### ISSUE TITLE
VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT is valid for a compute queue?

### ISSUE THREAD

**Issue by GertyP** [KhronosGroup/Vulkan-Docs#176]
In 1.0.9, pg 96, "Table 6.1: Supported pipeline stage flags" shows that VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT is a valid pipeline stage for a queue that supports VK_QUEUE_COMPUTE_BIT.
A compute-only queue, according to this table, would qualify as supporting the ...DRAW_INDIRECT... pipeline stage, which is surprising.
Is this a bug in the docs or is it valid to refer to a 'draw indirect' pipeline stage of a compute-only queue?
If the intention is that, in the case of a compute queue, the 'VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT' is a substitute for the 'dispatch indirect' stage, could a note be added saying as much?  It might be nicer to make this explicit either through the addition of another ..._DISPATCH_INDIRECT_BIT with the same value or to rename that particular VkPipelineStageFlagBits value to something like 'VK_PIPELINE_STAGE_DRAW_OR_DISPATCH_INDIRECT_BIT'.

**Comment by NicolBolas** [comment]
> could a note be added saying as much?

There already is a note. Section 6.5.2, where it defines what `VK_PIPELINE_STATE_DRAW_INDIRECT` means:

> * `VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT`: Stage of the pipeline where Draw/DispatchIndirect data structures are consumed.

**Comment by GertyP** [comment]
OK. Thanks.
I hope the addition of a 'VK_PIPELINE_STAGE_DISPATCH_INDIRECT_BIT' with the same value as the ..._DRAW_... is considered to add clarity.

Throughout the rest of the spec, 'dispatch' and 'draw' are either clearly distinguished or, where the distinction is not necessary, they are used together ("draw/dispatch").  The name of this VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT seems like a minor anomaly, due to only the use of 'draw' and not 'dispatch', and requires a reader to go and find that its name can be misleading (in the case of a compute dispatch indirect), which is a slight shame, since the purpose of enum names is to aid, as much as possible, in readability.

**Comment by oddhack** [comment]
We discussed this and believe we would be adding more confusion than we would be removing by adding such an alias.
