### ISSUE TITLE
Headers 205: Missing C definition for `StdVideoEncodeH265SliceSegmentHeader`

### ISSUE THREAD

**Issue by Friz64** [KhronosGroup/Vulkan-Docs#1764]
Looks like the struct `StdVideoEncodeH265SliceSegmentHeader`, which is defined in the XML here

https://github.com/KhronosGroup/Vulkan-Docs/blob/9e4c847a9e93cccd5f46e173c3ccf752b89c35df/xml/video.xml#L641-L672

is missing a C definition. The generated Vulkan-Headers only reference it, but don't define it.

https://github.com/KhronosGroup/Vulkan-Headers/search?q=StdVideoEncodeH265SliceSegmentHeader

| ![image](https://user-images.githubusercontent.com/20155479/152529948-67eb736b-4ebd-413e-a81a-1b1b30c14aeb.png) |
|-|

**Comment by Friz64** [comment]
Not sure if this issue is specific to the Vulkan-Docs or the Vulkan-Headers repository. Feel free to move it.

**Comment by oddhack** [comment]
@zlatinski could you ask the Video TSG to propose an MR updating vk.xml to include the new structure? And in general as the provisional API evolves, track API changes into video.xml as needed. Thanks.

**Comment by mikes-lunarg** [comment]
@oddhack It looks like the correct name is already in video.xml, maybe the `codec_header` target didn't get built or copied for the 205 release?

**Comment by oddhack** [comment]
As @mikes-lunarg noted this was a problem with the release procedure. @Friz64 please check current Vulkan-Headers and if the problem has been resolved, note here and I'll update the repository tag and close this.

**Comment by Friz64** [comment]
It works for me now, thanks!

**Comment by oddhack** [comment]
Thanks for checking. https://github.com/KhronosGroup/Vulkan-Headers/releases/tag/v1.3.205 has been updated to HEAD and a note added to the tag comment.
