### ISSUE TITLE
XML Registry - `optional="true,false"`

### ISSUE THREAD

**Issue by Pernet** [KhronosGroup/Vulkan-Docs#1766]
`pDrmFormatModifierProperties` member of `VkDrmFormatModifierPropertiesListEXT` struct is a pointer to an array.
This pointer is nullable, but if not null, this array must contain some `VkDrmFormatModifierPropertiesEXT` struct.
`optional` attribute of this `member` should be "true", and not "true,false".

`pDrmFormatModifierProperties` member of `VkDrmFormatModifierPropertiesList2EXT` struct is a pointer to an array.
This pointer is nullable, but if not null, this array must contain some `VkDrmFormatModifierProperties2EXT` struct.
`optional` attribute of this `member` should be "true", and not "true,false".

I think the correct use of `optional="true,false"` is in `ppGeometries` member of `VkAccelerationStructureBuildGeometryInfoKHR` struct : this is a pointer to an array of pointers.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.207 spec update.
