### ISSUE TITLE
Question: Are some limitations to vkCmdCopyImage are really neccesary?

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/Vulkan-Docs#177]
Hi,

quick question why image copies are restricted by:

> If either of the calling command’s srcImage or dstImage parameters are of VkImageType VK_IMAGE_TYPE_3D, the baseArrayLayer and layerCount members of both srcSubresource and dstSubresource must be 0 and 1, respectively

If someone wants to update a slice of a 3d image with a layer of a 2d array image (to try to work around the limitation outlined in #149).
The current limitation requires a round trip through a buffer (e.g 2d array -> buffer -> 3d).
At least one implementation (appears to) ignore this limitation and work as (naively) expected.

**Comment by jeffbolznv** [comment]
I agree, this seems like it should only apply to the subresource of the image that is 3D.

**Comment by TiemoJung** [comment]
@jeffbolznv I am correct to assume that VK_KHR_maintenance1 did address this issue? If yes, the issue can be closed.

**Comment by pdaniell-nv** [comment]
Yes, VK_KHR_maintenance1 should resolve this issue. Drivers are already available if you want to try it out.
