### ISSUE TITLE
Invalid feature requirement VUIDs for promoted extensions whose features weren't promoted

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-Docs#1770]
A number of extensions promoted to 1.3 explicitly do not promote the `VkPhysicalDevice*Features*` struct, so those features do not exist in Vulkan 1.3 anymore. But many of the affected functions still have VUIDs stating that those features must be enabled, which is probably an error. For example, VUID-vkCmdSetFrontFace-None-03383 states
> The [extendedDynamicState](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/chap41.html#features-extendedDynamicState) feature **must** be enabled

That feature only exists on a struct exposed through the `VK_EXT_extended_dynamic_state` extension, which was not included in the promotion. The VUID should probably be changed to apply the rule only if the effective API version (supported by device and limited by `VkApplicationInfo::apiVersion`) is less than 1.3?

**Comment by pdaniell-nv** [comment]
Thanks for spotting this issue. We have a spec fix pending for this, and also a validation fix was accepted [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3732).

**Comment by oddhack** [comment]
This was fixed back in the 1.3.206 spec update, but we neglected to close this at  the time.
