### ISSUE TITLE
XML Registry - `VkPhysicalDeviceShaderIntegerDotProductProperties` should be `returnedonly`

### ISSUE THREAD

**Issue by Pernet** [KhronosGroup/Vulkan-Docs#1771]
Structure `VkPhysicalDeviceShaderIntegerDotProductProperties` extends structure `VkPhysicalDeviceProperties2`, and should be `returnedonly="true"`, as all `VkPhysicalDevice*Properties*`.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.206 spec update.
