### ISSUE TITLE
XML Registry - Handle in `VkDeviceMemoryReportCallbackDataEXT` should be marked

### ISSUE THREAD

**Issue by Pernet** [KhronosGroup/Vulkan-Docs#1772]
In `VkDeviceMemoryReportCallbackDataEXT` structure:
- `objectType` member is of type `VkObjectType`
- `objectHandle` member is of type `uint64_t`

`objectHandle` member should be marked with a `objecttype` attribute that points to `objectType` member.

This is the same pattern as in `VkDebugMarkerObjectNameInfoEXT`, `VkDebugMarkerObjectTagInfoEXT`, `VkDebugUtilsObjectNameInfoEXT` and `VkDebugUtilsObjectTagInfoEXT`, but these structures are correct.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.206 spec update.
