### ISSUE TITLE
Missing layout requirements for resolve attachments

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-Docs#1777]
https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/chap8.html#attachment-type-imagelayout in the spec gives possible layouts for color, depth/stencil and input attachments, but not for resolve attachments. I also can't find any VUIDs saying what the layout of a resolve attachment should be, other than VUID-VkSubpassDescription2-None-04439 which refers to the aforementioned section. However, the related `vkCmdResolveImage` command does have a VUID:
> VUID-vkCmdResolveImage-dstImageLayout-01401
> `dstImageLayout` **must** be `VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR`, `VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL` or `VK_IMAGE_LAYOUT_GENERAL`

I would imagine that these same layout requirements, or something similar, also apply to resolve attachments?

**Comment by krOoze** [comment]
`VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR`, `VK_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL_KHR`, or `VK_IMAGE_LAYOUT_GENERAL`

**Comment by Rua** [comment]
> `VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR`, `VK_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL_KHR`, or `VK_IMAGE_LAYOUT_GENERAL`

Where are those listed?

**Comment by krOoze** [comment]
It is how those layouts are defined. And it is the same as color attachment requirements. But it is not sufficiently listed.

**Comment by janharaldfredriksen-arm** [comment]
I agree  resolve attachments should be mentioned in that section - and that it's the same as for color attachments.

**Comment by krOoze** [comment]
fyi It is missing (extension) depth resolve attachment layout info too.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.212 spec update.
