### ISSUE TITLE
vkCmdResolveImage: Missing VU for non-color formats?

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/Vulkan-Docs#1778]
My understanding is that vkCmdResolveImage doesn't work for images with depth/stencil formats.

This is implied by the man page (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkCmdResolveImage.html):

> To resolve a multisample color image to a non-multisample color image, call:

And stated by the KHR_depth_stencil_resolve extension (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_KHR_depth_stencil_resolve.html):

> The vkCmdResolveImage command does not allow for depth/stencil images.

... but it's a little odd that there's no VU for vkCmdResolveImage. Should there be one?

**Comment by martty** [comment]
There is VUID-vkCmdResolveImage-dstImage-02003, which only allows color formats for dstImage:
> VUID-vkCmdResolveImage-dstImage-02003
The [format features](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkCmdResolveImage.html#resources-image-format-features) of dstImage must contain VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT

Along with 
> VUID-vkCmdResolveImage-srcImage-01386
srcImage and dstImage must have been created with the same image format

I think this forbids non-color formats.

**Comment by zeux** [comment]
Ah, thank you! I missed this.
