### ISSUE TITLE
VkCommandBufferAllocateInfo valid usage

### ISSUE THREAD

**Issue by yavn** [KhronosGroup/Vulkan-Docs#178]
`VkCommandBufferAllocateInfo` doesn't impose a range limit on `commandBufferCount`. I expect this value should be greater than 0. Other similar structures have this limit, e.g. `VkDescriptorSetAllocateInfo`.

Validation layers are reporting an error if `commandBufferCount` is 0.

> ParameterValidation(ERROR): object: 0 type: 0 location: 160 msgCode: 1: vkAllocateCommandBuffers: value of pAllocateInfo->commandBufferCount must be greater than 0

**Comment by oddhack** [comment]
Should be fixed in the 1.0.14 spec update.
