### ISSUE TITLE
Multiple import structures in the `VkMemoryAllocateInfo` chain

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-Docs#1782]
The spec says, though not in a VUID:
> A `VkMemoryAllocateInfo` structure defines a memory import operation if its pNext chain includes one of the following structures:
> - [VkImportMemoryWin32HandleInfoKHR](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImportMemoryWin32HandleInfoKHR.html) with a non-zero `handleType` value
> - [VkImportMemoryFdInfoKHR](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImportMemoryFdInfoKHR.html) with a non-zero `handleType` value
> - [VkImportMemoryHostPointerInfoEXT](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImportMemoryHostPointerInfoEXT.html) with a non-zero `handleType` value
> - [VkImportAndroidHardwareBufferInfoANDROID](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImportAndroidHardwareBufferInfoANDROID.html) with a non-NULL `buffer` value
> - [VkImportMemoryZirconHandleInfoFUCHSIA](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImportMemoryZirconHandleInfoFUCHSIA.html) with a non-zero `handleType` value
> - [VkImportMemoryBufferCollectionFUCHSIA](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImportMemoryBufferCollectionFUCHSIA.html)

It seems logical to me that memory can only be imported from one of these sources at a time. But there is no VUID explicitly stating that only one of the structures can appear in the chain. The validation layer seems to assume that only one will appear, as it validates the first one it finds and ignores the rest.

**Comment by sfricke-samsung** [comment]
The WG agreed that it would never make sense to import from multiple `handleType`s at once. Will be adding an explicit VUID and testing/support in the Validation Layers

**Comment by oddhack** [comment]
This should be fixed in the v1.3.209 spec update.
