### ISSUE TITLE
VK_KHR_deferred_host_operations appendix has errors

### ISSUE THREAD

**Issue by aitor-lunarg** [KhronosGroup/Vulkan-Docs#1784]
There's a missing `)` here: https://github.com/KhronosGroup/Vulkan-Docs/blob/main/appendices/VK_KHR_deferred_host_operations.txt#L103

https://github.com/KhronosGroup/Vulkan-Docs/blob/main/appendices/VK_KHR_deferred_host_operations.txt#L42 should remove `EXT` from `vkDoSomethingExpensiveEXT` since `vkDoSomethingExpensive` is used in the Code Examples. `VkExpensiveOperationArgsEXT` mentioned but not used in Code Examples, it could be a good idea to remove it.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.207 spec update.
