### ISSUE TITLE
Not clear if R32_UINT <-> YUY2 vkCopyImage is allowed or not handled by some vendors.

### ISSUE THREAD

**Issue by Jonathan-Weinstein** [KhronosGroup/Vulkan-Docs#1789]
"YUY2" here is used as shorthand for `VK_FORMAT_G8B8G8R8_422_UNORM`.

The documentation for `vkCmdCopyImage` says:
 - "vkCmdCopyImage allows copying between size-compatible compressed and uncompressed internal formats" (e.g: R32G32_UINT <-> BC4, R32G32B32A32_UINT <-> BC5).
 - "`_422` image formats that are not multi-planar are treated as having a 2×1 compressed texel block for the purposes of these rules".

The above makes it sound like e.g R32_UINT <-> YUY2 copies are allowed. I tried a R32_UINT -> YUY2 copy and indeed the validation layer produced no errors. However, I got a `VK_ERROR_DEVICE_LOST` on the Nvidia 510.47.03 Linux driver when waiting for the submitted commands to be idle.

If this is not supposed to be allowed, maybe the spec could make that clearer and the validation layer can check for this? If this is allowed, then this might be an NV driver bug and a conformance test could be helpful.

Below is some of my code that does a R32_UINT -> YUY2 vkCopyImage that causes a VK_ERROR_DEVICE_LOST on NV's 510.47.03 Linux driver. It produces no validation errors.

```C++
    // NumBlocksX = 128, NumBlocksY = 256;
    {
        VkImageCreateInfo info = { VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO };
        info.flags = VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT;
        info.imageType = VK_IMAGE_TYPE_2D;
        info.format = VK_FORMAT_G8B8G8R8_422_UNORM; // YUY2
        info.extent = { NumBlocksX * 2, NumBlocksY * 1, 1 };
        info.mipLevels = 1;
        info.arrayLayers = 1;
        info.samples = VK_SAMPLE_COUNT_1_BIT;
        info.tiling = VK_IMAGE_TILING_OPTIMAL;
        info.usage = VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_SAMPLED_BIT;
        vkuDedicatedImage(vk.device, info, &yuy2, vk.memProps, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    }

    {
        VkImageCreateInfo info = { VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO };
        info.flags = VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT;
        info.imageType = VK_IMAGE_TYPE_2D;
        info.format = VK_FORMAT_R32_UINT;
        info.extent = { NumBlocksX, NumBlocksY, 1 };
        info.mipLevels = 1;
        info.arrayLayers = 1;
        info.samples = VK_SAMPLE_COUNT_1_BIT;
        info.tiling = VK_IMAGE_TILING_OPTIMAL;
        info.usage = VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_SAMPLED_BIT |
                     VK_IMAGE_USAGE_STORAGE_BIT;
        vkuDedicatedImage(vk.device, info, &r32ui, vk.memProps, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    }

    VkImageMemoryBarrier imgbar = {
        VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER, nullptr,
        0, // srcAccessMask,
        VK_ACCESS_TRANSFER_WRITE_BIT,
        VK_IMAGE_LAYOUT_UNDEFINED,
        VK_IMAGE_LAYOUT_GENERAL,
        VK_QUEUE_FAMILY_IGNORED,
        VK_QUEUE_FAMILY_IGNORED,
        VkImage(),
        { VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1 }
    };
    imgbar.image = yuy2.image;
    vkCmdPipelineBarrier(cmdbuf, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT, 0x0,
                         0, nullptr, 0, nullptr, 1, &imgbar);
    imgbar.image = r32ui.image;
    vkCmdPipelineBarrier(cmdbuf, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT, 0x0,
                         0, nullptr, 0, nullptr, 1, &imgbar);
    /* 1: Init R32_UINT image: */
    VkBufferImageCopy bufImgCopy = { };
    bufImgCopy.imageSubresource = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1 };
    bufImgCopy.imageExtent = { NumBlocksX, NumBlocksY, 1 };
    bufImgCopy.bufferRowLength = NumBlocksX;
    bufImgCopy.bufferImageHeight = NumBlocksY;
    vkCmdCopyBufferToImage(cmdbuf, upload.buffer, r32ui.image, VK_IMAGE_LAYOUT_GENERAL, 1, &bufImgCopy);
    VkMemoryBarrier membar = {
        VK_STRUCTURE_TYPE_MEMORY_BARRIER, nullptr,
        VK_ACCESS_TRANSFER_WRITE_BIT,
        VK_ACCESS_TRANSFER_WRITE_BIT | VK_ACCESS_TRANSFER_READ_BIT
    };
    vkCmdPipelineBarrier(cmdbuf, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT, 0x0,
                         1, &membar, 0, nullptr, 0, nullptr);
    /* 2: Copy from R32_UINT image to YUY2 image; results in VK_ERROR_DEVICE_LOST on NV when waiting: */
    VkImageCopy imgCopy = { };
    imgCopy.extent = { NumBlocksX, NumBlocksY, 1 }; // use src (r32ui) pixel dims, so do not *2
    imgCopy.srcSubresource = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1 };
    imgCopy.dstSubresource = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1 };
    vkCmdCopyImage(cmdbuf, r32ui.image, VK_IMAGE_LAYOUT_GENERAL, yuy2.image, VK_IMAGE_LAYOUT_GENERAL, 1, &imgCopy);
    vkCmdPipelineBarrier(cmdbuf, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT, 0x0,
                         1, &membar, 0, nullptr, 0, nullptr);
    /* 3: Copy from YUY2 image to host-cached buffer: */
    bufImgCopy.imageExtent.width *= 2;
    bufImgCopy.bufferRowLength *= 2;
    vkCmdCopyImageToBuffer(cmdbuf, yuy2.image, VK_IMAGE_LAYOUT_GENERAL, readback.buffer, 1, &bufImgCopy);
    membar.dstAccessMask = VK_ACCESS_HOST_READ_BIT;
    vkCmdPipelineBarrier(cmdbuf, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_HOST_BIT, 0x0,
                         1, &membar, 0, nullptr, 0, nullptr);
```

**Comment by pdaniell-nv** [comment]
@Jonathan-Weinstein what queue family are you using in the above repro?

**Comment by pdaniell-nv** [comment]
Using the exact code snippet above I wasn't able to reproduce a problem with an Ampere GPU (RTX 3070) on Windows with a similar driver version. My test used a universal queue. What GPU did you use?

**Comment by Jonathan-Weinstein** [comment]
My test also uses a universal queue. The device lost happens on a Quadro P1000 GPU. I just tested it with an RTX 3070 on Linux with the same 510.54 driver, which does indeed handle it correctly.

The full code can be seen here: https://github.com/Jonathan-Weinstein/vktest/blob/main/yuy2_r32_copy.cpp
On Windows there is a `vktest.vcxproj` that might be portable. On Linux, it can be built and run as follows on Linux:
```
# only submodule is volk:
git clone --recurse-submodules https://github.com/Jonathan-Weinstein/vktest.git
cd vktest
git pull --recurse-submodules
make
./vktest.out
# can optionally pass --gpuindex=%d, --coreval, --syncval
```
If you do decide to look at it, please excuse the repo has a bunch of unrelated files and is kinda messy at the moment.

**Comment by pdaniell-nv** [comment]
Hi @Jonathan-Weinstein, thanks for the repro for this issue. Sorry I haven't had a chance to continue looking at it. I haven't forgotten, and I hope to get to it soon.

**Comment by pdaniell-nv** [comment]
I had a chance to take a quick look at this. I was able to reproduce the problem locally. I think the application is fine, and this is a driver bug. I think the fix should be straight forward.

**Comment by Jonathan-Weinstein** [comment]
Thanks! I was able to implement a workaround and this is probably not a hot path in my application. I'm fine without a fix if it doesn't end up being straightforward or would complicate the driver. Otherwise a fix would be quite appreciated.

**Comment by pdaniell-nv** [comment]
Hi @Jonathan-Weinstein. There is a new Vulkan beta driver version 516.63 and 515.49.06 at https://developer.nvidia.com/vulkan-driver, which should have a fix for this issue. If you get a chance, let me know how it works out for you. Thanks.

**Comment by Jonathan-Weinstein** [comment]
Hi @[pdaniell-nv](https://github.com/pdaniell-nv). I just tried the new July 2nd, 2022 Linux 515.49.06 beta driver. With it, the R32_UINT -> YUY2 vkCmdCopyImage test now works on my Quadro P1000. Thank you very much for being a great help.

**Comment by pdaniell-nv** [comment]
> Hi @[pdaniell-nv](https://github.com/pdaniell-nv). I just tried the new July 2nd, 2022 Linux 515.49.06 beta driver. With it, the R32_UINT -> YUY2 vkCmdCopyImage test now works on my Quadro P1000. Thank you very much for being a great help.

Awesome. Many thanks for trying it out and reporting back.
