### ISSUE TITLE
vkCmdExecuteCommands valid usage

### ISSUE THREAD

**Issue by yavn** [KhronosGroup/Vulkan-Docs#179]
The valid usage section for `vkCmdExecuteCommands` (chapter 5.6) incorrectly refers to `VkCommandBufferBeginInfo`:

> If commandBuffer has a VK_QUERY_TYPE_OCCLUSION query active, then each element of pCommandBuffers must have been recorded with VkCommandBufferBeginInfo::occlusionQueryEnable set to VK_TRUE

The members `occlusionQueryEnable`, `queryFlags`, `pipelineStatistics` belong to `VkCommandBufferInheritanceInfo`.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.14 spec update.
