### ISSUE TITLE
Feature Request: Vulkan Compute <-- OpenCL-Next Interop? (#42)

### ISSUE THREAD

**Issue by Daasin** [KhronosGroup/Vulkan-Docs#1796]
Feature Request: 

Title of issue: Release As Mentioned In:  #https://github.com/KhronosGroup/Vulkan-Ecosystem/issues/42 
 
  
 
 _Was wondering whether there was any update on OpenCL-Next and the WIP for the interop or 'convergence where possible' with Vulkan Compute?_

**Comment by Daasin** [comment]
Asking due to mixed messages seen online about future work on compatibility between the two

**Comment by oddhack** [comment]
@neiltrevett perhaps you could provide an update from the OpenCL WG perspective?
