### ISSUE TITLE
Does vulkan 1.3 require VK_ANDROID_external_memory_android_hardware_buffer

### ISSUE THREAD

**Issue by Bobby-RobertQ** [KhronosGroup/Vulkan-Docs#1798]
[VK_ANDROID_external_memory_android_hardware_buffer] @critsec
<<Here describe the issue or question you have about the VK_ANDROID_external_memory_android_hardware_buffer extension>>

Hi, I was wondering if the ARCore support in Vulkan is finally resolved with Vulkan 1.3 requirements.
is VK_ANDROID_external_memory_android_hardware_buffer in Vulkan 1.3?

And if Vulkan 1.3 is compatible with all OpenGL ES 3.1 devices (mostly), does this mean the current rule still stands where device makers just need to optionally push out an update for Vulkan 1.3 on those devices?

Is there any known instances where device makers will push out Vulkan updates to devices older than their traditionally 2-3 year software update schedules?
( i do know some push security updates, but how about vulkan updates)

Thank you so much for your time,
Robert Quinones

**Comment by sfricke-samsung** [comment]
> is VK_ANDROID_external_memory_android_hardware_buffer in Vulkan 1.3?

Yes, it is also in Vulkan 1.0, Android vendors add the extension if supports

> Does vulkan 1.3 require VK_ANDROID_external_memory_android_hardware_buffer

No, non-Android Vulkan implementations are not **required** to have the AHB functionality

>  device makers

Not sure what you are referring to here

**Comment by Bobby-RobertQ** [comment]
It was in reference to this post. 
https://github.com/google-ar/arcore-android-sdk/issues/258

"
[tweenk](https://github.com/tweenk) commented [on Mar 28, 2018](https://github.com/google-ar/arcore-android-sdk/issues/258#issuecomment-377042924)
I'm not on the AR team, but can answer the question. Internally, SurfaceTexture is a mutable texture: the same texture ID is used in multiple calls to glEGLImageTargetTexture2DOES to point the texture at different native buffers (gralloc buffers). Mutable textures do not exist in Vulkan and therefore it's not possible to add Vulkan support to SurfaceTexture. The Vulkan-compatible equivalent of SurfaceTexture is AImageReader, but using it with camera frames requires Vulkan 1.1 and the extension VK_ANDROID_external_memory_android_hardware_buffer, which is not supported by any GPU drivers yet.
"

so i was hoping Vulkan 1.3 fixed this by making a requirement for the necessary optional extensions from 1.0-1.2 needed for AR Core to support Vulkan.

Thank you for clarifying that it will remain optional in Vulkan 1.3.

Are there any plans to make it a requirement for Vulkan 1.4 to have the necessary extensions for AR Core?

**Comment by oddhack** [comment]
There are no plans for Vulkan 1.4 yet. We just released 1.3 and historically are running about 2 years between core updates. This might be something to pursue through the new profile mechanism.

**Comment by r-potter** [comment]
This is really a platform requirement, rather than a core API requirement. It's already required in the [Android Compatibility Definition Document](https://source.android.com/compatibility/10/android-10-cdd) requirement. From Android 10, any device that ships Vulkan 1.1 is required to support the extension:

> If device implementations include support for Vulkan 1.1 and declare any of the Vulkan feature flags, they:
> 
> [C-3-1] MUST expose support for the SYNC_FD external semaphore and handle types and the  VK_ANDROID_external_memory_android_hardware_buffer extension.

**Comment by oddhack** [comment]
@Bobby-RobertQ if discussion on the thread has answered your question, please close this. Otherwise please clarify what remains to be said.
