### ISSUE TITLE
Confusing valid usage statements for VkFramebufferCreateInfo

### ISSUE THREAD

**Issue by luckyxxl** [KhronosGroup/Vulkan-Docs#1800]
Many "Valid Usage" statements for `VkFramebufferCreateInfo` (i.e.`VUID-VkFramebufferCreateInfo-attachmentCount-00876`) imply that `renderPass` may be `VK_NULL_HANDLE`. Yet the "Valid Usage (Implicit)" section states that `renderPass must be a valid VkRenderPass handle`.

**Comment by luckyxxl** [comment]
Also note that the capitalization of `renderpass` in the "Valid Usage" text differs from the `renderPass` member of `VkFramebufferCreateInfo` in many cases.

**Comment by Tobski** [comment]
Thanks for your report - looks like this was an editorial mistake leftover from an earlier iteration of VK_KHR_dynamic_rendering, I'll make sure we get this fixed ASAP. `renderPass` is always required here, and the "If renderpass is not VK_NULL_HANDLE" clauses you've identified are redundant.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.210 spec update.
