### ISSUE TITLE
Enabling VK_KHR_sampler_ycbcr_conversion

### ISSUE THREAD

**Issue by M-Gjerde** [KhronosGroup/Vulkan-Docs#1801]
[VK_KHR_sampler_ycbcr_conversion] @fluppeteer
Hello

I am trying to enable the VK_KHR_sampler_ycbcr_conversion extension, but even though I have the extension in my RTX 3060 (check through vulkaninfo) I am failing to enabling it.
On the [manual page](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_KHR_sampler_ycbcr_conversion.html) it lists in particular one dependency, VK_KHR_get_physical_device_properties2 which I do not support. I'm a bit curious if I really cant enable because I dont have the dependency: VK_KHR_get_physical_device_properties2 when this latter extension is only supported on 0.2% of devices according to vulkan.gpuinfo.org
Or am I missing something here?

Best regards
Magnus

**Comment by lewa-j** [comment]
VK_KHR_get_physical_device_properties2 is not a device extension but an instance extension. http://vulkan.gpuinfo.org/listreports.php?instanceextension=VK_KHR_get_physical_device_properties2

**Comment by M-Gjerde** [comment]
Ah I see. Thank you for your reply!
