### ISSUE TITLE
Potentially unintended requirements for `extent.depth` in `vkCmdCopyImage`

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-Docs#1804]
On the one hand, there is this pair of VUIDs:
> VUID-vkCmdCopyImage-srcOffset-00147
> For each element of `pRegions`, `srcOffset.z` and (`extent.depth` + `srcOffset.z`) **must** both be greater than or equal to `0` and less than or equal to the depth of the specified `srcSubresource` of `srcImage`

> VUID-vkCmdCopyImage-dstOffset-00153
> For each element of `pRegions`, `dstOffset.z` and (`extent.depth` + `dstOffset.z`) **must** both be greater than or equal to `0` and less than or equal to the depth of the specified `dstSubresource` of `dstImage`

On the other, there are these two:
> VUID-vkCmdCopyImage-srcImage-01791
> If `srcImage` is of type `VK_IMAGE_TYPE_2D`, and `dstImage` is of type `VK_IMAGE_TYPE_3D`, then for each element of `pRegions`, `extent.depth` must equal `srcSubresource.layerCount`

> VUID-vkCmdCopyImage-dstImage-01792
> If `dstImage` is of type `VK_IMAGE_TYPE_2D`, and `srcImage` is of type `VK_IMAGE_TYPE_3D`, then for each element of `pRegions`, `extent.depth` must equal `dstSubresource.layerCount`

These latter two VUIDs are special case to allow copying between layers of a 2D image and depth of a 3D image. But if for the 2D image, the z-offset is 0, then `extent.depth` must be 1 in order to satisfy the first pair of VUIDs, which would then mean that its `layerCount` must also be 1 to satisfy the second pair. Is it really the intent that the special 2D-3D layer copy operation is restricted only to one layer at a time? I would guess that if you have a 2D-3D image pair, `extent.depth` should be considered to be 1 for the 2D image regardless of its actual value.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.211 spec update.
