### ISSUE TITLE
`vkCmdResolveImage` missing image usage VUID?

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-Docs#1809]
At the moment, there are no VUIDs for `vkCmdResolveImage` that put any requirement on usage flags of the source and destination images. Other copy commands require `TRANSFER_SRC` and `TRANSFER_DST`, so this may be an accidental omission?

**Comment by Tobski** [comment]
Hi @Rua thanks for spotting this - totally looks like an omission to us. Would you be willing to put together a PR to add these?

**Comment by Rua** [comment]
I can try, sure. I noticed that VUIDs for format feature flags are also missing, but then I'm not sure what flag should actually be used for resolves, `TRANSFER_SRC/DST_BIT` or `BLIT_SRC/DST_BIT`?

**Comment by Tobski** [comment]
Thanks! It should be done as TRANSFER_SRC/DST_BIT, as resolve counts as a regular copy command, unlike blit.

**Comment by Rua** [comment]
What VUID number should I use for the new ones? Should I use the same numbers as used on `vkCmdCopyImage`? I have no idea how this works.

**Comment by krOoze** [comment]
@Rua  https://www.khronos.org/registry/vulkan/specs/1.3/styleguide.html#appendix-vuid-creating
