### ISSUE TITLE
Clarify *_SIMULTANEOUS_USE_BIT behavior for secondary command buffers

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-Docs#182]
Currently spec section "5.3 Command Buffer Recording" contains the paragraph:

`A secondary command buffer is considered to be pending execution from the time its execution is recorded into a primary buffer (via vkCmdExecuteCommands) until the final time that primary buffer’s submission to a queue completes. If, after the primary buffer completes, the secondary command buffer is recorded to execute on a different primary buffer, the first primary buffer must not be resubmitted until after it is reset with vkResetCommandBuffer.`

However, section "5.6 Secondary Command Buffer Execution" contains two statements which seem to contradict the last sentence above as long as VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT is set for the secondary command buffer(s) in question. First, the the following valid usage statement:

`Any given element of pCommandBuffers must not be already pending execution in any other VkCommandBuffer, unless it was created with the VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT flag`

Then in the final statement of that section:

`Once vkCmdExecuteCommands has been called, any prior executions of the secondary command buffers specified by pCommandBuffers in any other primary command buffer become invalidated, unless those secondary command buffers were recorded with VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT.`

I propose that the last sentence of the spec 5.3 section above should be updated to include an exception for VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT, similar to the two statements from section 5.6. Here is how the updated section 5.3 would read:

`A secondary command buffer is considered to be pending execution from the time its execution is recorded into a primary buffer (via vkCmdExecuteCommands) until the final time that primary buffer’s submission to a queue completes. If, after the primary buffer completes, the secondary command buffer is recorded to execute on a different primary buffer, the first primary buffer must not be resubmitted until after it is reset with vkResetCommandBuffer unless the secondary command buffer was recorded with VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT.`

**Comment by oddhack** [comment]
This should be fixed in the 1.0.13 spec update.
