### ISSUE TITLE
VK_KHR_dynamic_rendering should require VK_KHR_depth_stencil_resolve

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-Docs#1830]
The `VkResolveModeFlagBits` enum is used in the `VkRenderingAttachmentInfo` structure, and this enum is introduced by the VK_KHR_depth_stencil_resolve extension and promoted to Vulkan 1.2. Since VK_KHR_dynamic_rendering does not require Vulkan 1.2, it should require the VK_KHR_depth_stencil_resolve extension to be enabled. Otherwise, on Vulkan versions below 1.2, VK_KHR_dynamic_rendering would be missing one of its types.

**Comment by oddhack** [comment]
Adding a dependency on the enum from the XML extension block would be appropriate, I agree. Would you want to propose a PR to that effect?

**Comment by oddhack** [comment]
N.b. while we are trying these days to enumerate all the dependencies in the extension block, there is no mechanical reason for doing this, just human convenience; the scripts transitively follow all dependencies when asked to generate an extension.
