### ISSUE TITLE
`VK_ATTACHMENT_UNUSED` in `vkCmdClearAttachments` with dynamic rendering

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-Docs#1835]
The first three VUIDs of `vkCmdClearAttachments` are:

> VUID-vkCmdClearAttachments-aspectMask-02501
> If the `aspectMask` member of any element of `pAttachments` contains `VK_IMAGE_ASPECT_COLOR_BIT`, then the `colorAttachment` member of that element **must** either refer to a color attachment which is `VK_ATTACHMENT_UNUSED`, or **must** be a valid color attachment

> VUID-vkCmdClearAttachments-aspectMask-02502
> If the `aspectMask` member of any element of `pAttachments` contains `VK_IMAGE_ASPECT_DEPTH_BIT`, then the current subpass' depth/stencil attachment **must** either be `VK_ATTACHMENT_UNUSED`, or **must** have a depth component

> VUID-vkCmdClearAttachments-aspectMask-02503
> If the `aspectMask` member of any element of `pAttachments` contains `VK_IMAGE_ASPECT_STENCIL_BIT`, then the current subpass' depth/stencil attachment **must** either be `VK_ATTACHMENT_UNUSED`, or **must** have a stencil component

These VUIDs make reference to `VK_ATTACHMENT_UNUSED`, which is used when creating a render pass object, but not with dynamic rendering. Rather, in dynamic rendering, you set the `imageView` to `VK_NULL_HANDLE` to mark an attachment slot as unused, or in the case of depth and stencil attachments, set these members to `NULL`. The text of these VUIDs should probably be updated to reflect this alternative.

In addition, the latter two VUIDs mention the depth/stencil attachment, but with dynamic rendering you specify depth and stencil separately. If provided, they both must refer to the same image view and thus have the same format, but unlike with a classic render pass, you have the ability to set the depth and stencil components to `NULL` individually. This leads to a situation that didn't occur before: if either the depth or stencil attachment is `NULL`, but the format of the other attachment includes both a depth and a stencil component, then is that component considered present in the attachment or not? And does it count as the depth/stencil attachment having both components for the purposes of these VUIDs?

**Comment by HansKristian-Work** [comment]
I think there is missing wording here taking dynamic rendering into account, yes. I'll try to word something.

> if either the depth or stencil attachment is NULL, but the format of the other attachment includes both a depth and a stencil component, then is that component considered present in the attachment or not?

For dynamic rendering, yes. The NULL attachment would be nooped.
