### ISSUE TITLE
[Specification] Lod clamping

### ISSUE THREAD

**Issue by Retrofractal** [KhronosGroup/Vulkan-Docs#1836]
In Vulkan, `shaderResourceMinLod` allows sampled image operations to specify a per-instruction min lod clamp, in addition to the usual sampler clamps. This `MinLod` effectively works like a conventional sampler clamp; the maximum of the shader and sampler clamp is selected as the effective sampler clamp. DirectX however appears to require more _robust_ clamping behaviour, as applied to its per-sample min lod clamp. It guarantees that image levels below the specified threshold will not be selected. Consequently, an out of bounds result is returned whenever the min lod exceeds the max image level: `MinLod > q` (in Vulkan terms). This seems to be behaviour that could be included in the Vulkan spec, as part of `robustImageAccess2`. Note that DirectX also specifies that the min lod clamp takes precedence if it exceeds the sampler max lod, but the spec currently accommodates this by conceding that the lod is undefined in this case, leaving the implementer to decide how to handle it.

Another potential issue affects `imageViewMinLod`. DirectX does not specify how and when magnification vs minification is determined with respect to these clamps. I think it may be helpful to allow an implementation the freedom to choose which filter is selected when `imageViewMinLod > baseMipLevel`. It seems like it might make more sense for an implementation to choose the filter mode after all clamps are applied, to avoid an arbitrary transition between filtering mode in the actual magnification domain (e.g a full unconstrained unbiased mipmap chain with `imageViewMinLod = 1` will currently employ the minification filter up to 2x magnification).

I note the interaction between `robustImageAccess2` and `ImageViewMinLod`. If this is going to be honoured fully, I believe a further condition needs to be added whereby out of bounds is returned for any (ordinary) gather instruction acting on an image with `minLodInteger_imageView > 0`.

Finally, there appears to be an error in the definition of `d_lo`. I think it should just be the ceiling of `d_l`. `minLod` is restricted to be less than or equal to `baseMipLevel + q` so there is no need to apply further clamping (note the ceiling will not take the value above a maximum integer clamp i.e. `q`). In any event, if you were going to clamp `d_lo`, it needs to be clamped against `baseMipLevel + q`, not `q`.

**Comment by pdaniell-nv** [comment]
Does this help:
https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_EXT_image_view_min_lod.html

**Comment by Retrofractal** [comment]
Hi, the second and third paragraphs above relate to that extension. Is there something in particular you would like to draw my attention to?

**Comment by pdaniell-nv** [comment]
Oh sorry, that wasn't obvious to me you were referring to that new extension. I was only pointing it out in case you weren't aware of its existence, but clearly you are. Your issue will take more study.

**Comment by Retrofractal** [comment]
Ah, sorry, I should have been a bit clearer - spent too much time staring at this! The first paragraph is about the shader lod clamp and the fourth paragraph is just pointing out an error in the spec, I believe.

**Comment by Retrofractal** [comment]
And I need to correct paragraph 3 so that it reads "gather instruction acting on an image with `minLodInteger_imageView > baseMipLevel`" since gather instructions read from the base level.

**Comment by HansKristian-Work** [comment]
## Shader sampler clamp

From the Vulkan formulas:
- lambda_base takes shader parameter
- lambda then clamps the LOD based on sampler_max. I.e. sampler_max takes precedence here.
- The lambda is translated into a LOD selection by clamping against the image view.

So, a very high minLOD in shader will result in sampling the lowest resolution mip in the view.

> DirectX does not specify how and when magnification vs minification is determined with respect to these clamps.

Are you referring to this?

> It is undefined whether LOD clamping based on MinLOD and MaxLOD Sampler states should happen before or after deciding if magnification is occuring.

That seems to even cover the basic sampler min/max LOD. It seems like Vulkan behavior is more strict here, which is hopefully covered by conformance testing. Is there evidence to suggest this is not how hardware behaves?

D3D:

Is `5.9.4.5.4 Per-sample MinLOD Clamp` what you're referring to here? It seems to suggest that MinLOD will trip OOB. There seems to be disagreement what happens here and the formulation of the order of clamping is kinda vague. It refers to variables which don't exist anywhere else, i.e. `max(fShaderMinLODClamp,fComputedLOD)`. Do we have tests that verify behavior? I would imagine hardware only does one of these two.

## Image view min LOD clamp

> any (ordinary) gather instruction acting on an image with minLodInteger_imageView > 0.

I guess similar rules as fetch would apply here.

> In any event, if you were going to clamp d_lo, it needs to be clamped against baseMipLevel + q, not q.

That looks like a typo, yes.

**Comment by Retrofractal** [comment]
Hi, thanks for taking a look at this!

> lambda_base takes shader parameter

Since we're talking about the optional image operand `MinLod` (as opposed to `Lod`), lambda_base uses the implicit calculation. We have `lod_min = max(sampler.lod_min, shaderOp.lod_min)` and that lambda is undefined whenever `lod_min > lod_max`.

> Are you referring to this? Is there evidence to suggest this is not how hardware behaves?

I am indeed, yes. My suggestion here is that I don't think it is desirable to determine magnification vs minification before applying the image view clamp and that the spec should ideally allow the implementation the freedom to choose (without falling back to something as loose as DirectX; filter selection after sampler clamping is a defensible position to adopt). No comment re hardware behaviour.

> Is 5.9.4.5.4 Per-sample MinLOD Clamp what you're referring to here? 

Aye, that's the blighter! I definitely agree that this this is not the best worded part of the DirectX spec, but it is clear that out of bounds behaviour can be invoked by the shader min lod under _some_ conditions, poorly stated as they are. If you refer back to `5.8.5 Empty-Set Cases` and the examples given in `5.8.6 Per-Resource Clamp Examples`, it should be clear that an "empty-set case" is one in which the per-resource min lod clamp (in view space) exceeds the maximum image view level. This has nothing to do with the sampler clamps so I think it is misleading to explicitly refer to them in the following paragraph:

> If the result of applying the Per-sample LOD clamp and any other LOD clamps defined in the sampler is an empty set, the result is the same out of bounds access result as the per-Resource minLOD clamp: 0 for components in the surface format and defaults for missing components.

If you look at `5.8.6.2 Case 2: Per-Resource Clamp falls within SRV, but outside Sampler clamp`, you can see that the range of available image levels is determined solely by the shader resource view and not the sampler clamps; despite the (view space) per-resource min lod exceeding the sampler max lod, an out of bounds result does not occur because the image level is still accessible within the view.

> Do we have tests that verify behavior? I would imagine hardware only does one of these two.

I haven't looked at the relevant conformance tests, but I've interpreted this to mean that all clamps should be applied: sampler, per-resource and per-sample, with the latter two capable of generating out of bounds results.

Taking a step back, I believe the intention for both per-resource and per-sample clamps is to **guarantee** that image levels below the specified threshold will never be accessed, which seems reasonable, given that they were introduced in the context of Tiled Resources. A sampler clamp, on the other hand, can be as large as you like, but if only a single image level is available, then level zero will always be read (and there's no reason why that behaviour should change if a per-sample min lod clamp is supplied e.g. sampler min lod exceeding max image level but zero per-sample min lod should not generate out of bounds).

> I guess similar rules as fetch would apply here.

Sure, I think this just needs to be worked into the spec. Incidentally, it looks like `16.10 Image Operation Steps` could be updated to explicitly indicate which instructions employ the section `16.7. Integer Texel Coordinate Operations`. In principle, gather instructions could be included here if we wanted an alternative way to allow a non-base level image level to be specified in SPIR-V code (notwithstanding an existing extension)) ;).

> That looks like a typo, yes

Great, thanks for confirming (still prefer removing the clamp entirely)!

**Comment by HansKristian-Work** [comment]
> Since we're talking about the optional image operand MinLod (as opposed to Lod), lambda_base uses the implicit calculation. We have lod_min = max(sampler.lod_min, shaderOp.lod_min) and that lambda is undefined whenever lod_min > lod_max.

Uh, right. That was the Explicit LOD thing, not minLOD. Using high minLOD does indeed become undefined here, so that would explain why robustness2 could try to make it well defined. I guess we'll need to confirm this with new CTS.

**Comment by HansKristian-Work** [comment]
Going back to min/mag filtering.

> If λ is less than or equal to zero, the texture is said to be magnified, and the filter mode within a mip level is selected by the magFilter in the sampler. If λ is greater than zero, the texture is said to be minified, and the filter mode within a mip level is selected by the minFilter in the sampler.

This is affected by sampler clamps, but indeed, not image minLOD. This comes afterwards.

Do I understand it correctly that it's desirable to make it implementation defined what happens for the case where 0 < d' <= imageView_minLOD? We should probably test this as well (or it might already be tested for all I know). If all implementations of VK_EXT_image_view_min_lod behave the same, it makes sense to keep spec as-is, if not, adjust it.

**Comment by Retrofractal** [comment]
> Using high minLOD does indeed become undefined here, so that would explain why robustness2 could try to make it well defined.

Ah, well to match DirectX, you may want to have lambda equal lod_min whenever `lod_min > lod_max`. The out of bounds result, on the other hand, should only occur when `shaderOp.lod_min > q`. Note that the analogous image view min lod clamp out of bounds condition is excluded since 

> `minLod` **must** be less or equal to `level_base + q`

> Do I understand it correctly that it's desirable to make it implementation defined what happens for the case where 0 < d' <= imageView_minLOD?

I think it should be that the filter mode is implementation-defined when `lambda <= 0` and `minLod_imageView > level_base` (it's in resource space). This is because a positive (sampler) min lod clamp will prevent the `magFilter` from ever being used. From one perspective, the magnification filter represents the non-positive lod domain so any positive clamping should prevent that domain from being accessed.

> If all implementations of VK_EXT_image_view_min_lod behave the same, it makes sense to keep spec as-is, if not, adjust it.

Seems fair :)

**Comment by HansKristian-Work** [comment]
It would be helpful to know if you have a use case that relies on this exact D3D behavior. Some of these requests require quite a lot of work to see through. The level_base + q clamp thing and image gather issues should be resolved though without too much issue. Changing sampler clamp rules seems to be non-trivial though and might require full extensions.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.227 spec update.
