### ISSUE TITLE
Duplicate `VkGraphicsPipelineCreateInfo` VUIDs

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-Docs#1838]
`VkGraphicsPipelineCreateInfo` contains these two VUIDs, which seem to say the same thing:

> VUID-VkGraphicsPipelineCreateInfo-renderPass-06055
> If `renderPass` is `VK_NULL_HANDLE` and the pipeline is being created with fragment output interface state, `pColorBlendState->attachmentCount` **must** be equal to VkPipelineRenderingCreateInfo::colorAttachmentCount

> VUID-VkGraphicsPipelineCreateInfo-renderPass-06060
> If the pipeline is being created with fragment output interface state and `renderPass` is `VK_NULL_HANDLE`, `pColorBlendState->attachmentCount` **must** be equal to the `colorAttachmentCount` member of the VkPipelineRenderingCreateInfo structure included in the `pNext` chain

**Comment by sjfricke** [comment]
I agree, looking at the Validation layers both are being validated slightly different, but the test hits both VUs. 

`06060` is wrapped in `ifdef::VK_KHR_multiview,VK_VERSION_1_1[]` and not sure if there was some multiview related working missing.
