### ISSUE TITLE
Typo in VkImageCreateInfo's Valid Usage section (11.3. Images)

### ISSUE THREAD

**Issue by nanley** [KhronosGroup/Vulkan-Docs#184]
To match the header, all occurrences of VkPhysicalDeviceLimits::max*Samples should have the "max" prefix removed on the field name, and the resulting first letter converted to lowercase. Here are the specific fields that need changing:

- maxFramebufferColorSamples
- maxFramebufferDepthSamples
- maxFramebufferStencilSamples
- maxSampledImageColorSamples
- maxSampledImageDepthSamples
- maxSampledImageIntegerSamples
- maxStorageImageSamples

**Comment by oddhack** [comment]
Thanks! I'll get that done in the next public update. BTW it's "framebufferColorSampleCounts" etc. so the rule you give is a bit off.

Ideally the validation scripts would catch this usage, but they're not clever enough to look for structure members that are part of structures other than the one being described, yet, so are of pretty limited utility here (e.g. raise many false positives).

**Comment by nanley** [comment]
Thanks and good catch on the rule error. Thankfully the spec has help from this open-source feedback cycle while the validation scripts are in the process of improving.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.11 spec update.
