### ISSUE TITLE
Not clear if memory access is an "operation"

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1842]
Documenting some loose ends in sync before I forget:

It is not immediately clear whether memory access is an "operation". If it is, it could lead to some problems in various uncareful usage of that "operation" word. For example:

>` VK_PIPELINE_STAGE_ALL_COMMANDS_BIT` specifies all operations performed by all commands supported on the queue it is used with.

This is ambiguous, because "all" here could be interpreted as memory accesses. And sync operations too for that matter.

Meanwhile the BIT is supposed to kinda mean only execution of "action" operations, and not memory side effects, which are supplied separately.

**Comment by HansKristian-Work** [comment]
A memory access is indeed an operation. The main thing to consider is that a memory operation completing isn't enough to make it available / visible. That's where the access masks come in. So waiting for "all operations" means that we wait for the memory access to complete, then we can make it available.
