### ISSUE TITLE
Specify more restrictions on sample count variables

### ISSUE THREAD

**Issue by nanley** [KhronosGroup/Vulkan-Docs#185]
To be in agreement with Table 11.1.'s implication that multisampled images must be 2D and non-cube compatible, more restrictions need to be specified on VkImageFormatProperties::sampleCounts and the fields in VkPhysicalDeviceLimits related to sample counts.

**Comment by nanley** [comment]
In addition to the above restrictions, the images should also have a format that supports being used as a color or depth/stencil attachment.

**Comment by janharaldfredriksen-arm** [comment]
Apologies for the late response. The working group agrees this needs to be fixed. I'm working on fixing this and a couple of related issues for future spec update.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.21 spec update.
