### ISSUE TITLE
GetPastPresentationTimingGOOGLE() is crashing with Android 13 beta version

### ISSUE THREAD

**Issue by RakeshSharanappa** [KhronosGroup/Vulkan-Docs#1854]
[VK_GOOGLE_display_timing]

We are observing a crash with GetPastPresentationTimingGOOGLE API on Android 13 beta version. Is this is a known issue?

Thanks,
Rakesh

**Comment by stonesthrow** [comment]
@chadversary

**Comment by chrisforbes** [comment]
Hi Rakesh,

Yes, this is a known issue with some early Android 13 builds. We're working on fixing it.

- Chris

**Comment by RakeshSharanappa** [comment]
Hi Chris,

Thanks for confirming this. Please let me know once the fix is made for this issue. 
Is there any workaround I can try for time being?

Regards,
Rakesh

**Comment by chrisforbes** [comment]
There's no workaround at this time other than not using the extension. I'll let you know (on this ticket) when a fix lands.

**Comment by RakeshSharanappa** [comment]
Hi Chris,

Great! Thanks for the update 👍

**Comment by chrisforbes** [comment]
@RakeshSharanappa looks like you can expect a fix in Beta 3.

**Comment by laurinagostiniHG** [comment]
@chrisforbes is there already a fix in Beta 3? I still can reproduce it on a Pixel 6 with Beta 3.1 (TPB3.220513.017.B1)

**Comment by chrisforbes** [comment]
My apologies; It looks like it's actually only in TPB3.220610.* which should be released shortly.
