### ISSUE TITLE
Ambiguous when surface can be NULL in connection with VK_GOOGLE_surfaceless_query

### ISSUE THREAD

**Issue by panos-lunarg** [KhronosGroup/Vulkan-Docs#1866]
In the [VK_GOOGLE_surfaceless_query](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VK_GOOGLE_surfaceless_query) description it is stated:
```
This extension allows the vkGetPhysicalDeviceSurfaceFormatsKHR and vkGetPhysicalDeviceSurfacePresentModesKHR functions to accept VK_NULL_HANDLE as their surface parameter, allowing potential surface formats, colorspaces and present modes to be queried without providing a surface. Identically, vkGetPhysicalDeviceSurfaceFormats2KHR and vkGetPhysicalDeviceSurfacePresentModes2EXT would accept VK_NULL_HANDLE in VkPhysicalDeviceSurfaceInfo2KHR::surface.
```
It explicitly states the functions `vkGetPhysicalDeviceSurfaceFormats(2)KHR()` and `vkGetPhysicalDeviceSurfacePresentModes(2)KHR()`.

However in the [valid usage](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkPhysicalDeviceSurfaceInfo2KHR-pSurfaceInfo-06526) of `VkPhysicalDeviceSurfaceInfo2KHR`, `vkGetPhysicalDeviceSurfaceCapabilities2KHR()` is also mentioned as a function that can accept `VK_NULL_HANDLE` as a surface when the extension is enabled.

If that's the case I think it would be more clear if `vkGetPhysicalDeviceSurfaceCapabilities2KHR()` is also mentioned in the extension's description.

**Comment by ShabbyX** [comment]
Fixed in the latest spec release.
