### ISSUE TITLE
Mistake in figure: push constants are shown as inside descriptor sets

### ISSUE THREAD

**Issue by NeonSky** [KhronosGroup/Vulkan-Docs#1867]
[Figure 2. Block diagram of the Vulkan pipeline](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/chap10.html) suggests that push constants are part of descriptor sets, while the rest of the documentation suggests otherwise. For instance, they are treated as separate when [creating pipeline layouts](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineLayoutCreateInfo.html).

One option is to place push constants outside of the descriptor sets region, as seen [here](https://i.stack.imgur.com/33UO6.png).

**Comment by oddhack** [comment]
This should be fixed in the 1.3.219 spec update.
