### ISSUE TITLE
A question about execution dependency chain, what does the highlighted parts mean?

### ISSUE THREAD

**Issue by Ma-Y** [KhronosGroup/Vulkan-Docs#1872]
Chapter 7.1 Execution and Memory Dependencies

An execution dependency chain is a sequence of execution dependencies that form a happens-before relation between the first dependency’s ScopedOps 1 and the final dependency’s ScopedOps2 . For each consecutive pair of execution dependencies, `a chain exists if the intersection of Scope 2nd in the first dependency and Scope 1st in the second dependency is not an empty set. `

**Comment by krOoze** [comment]
Vaguely dup of #1815.
