### ISSUE TITLE
Is Vulkan's VkMemoryHeapFlagBits missing Zero value ?

### ISSUE THREAD

**Issue by AlessandroBorges** [KhronosGroup/Vulkan-Docs#188]
Hi !

At Vulkan specs 1.0.9 (pg. 180), we have the following:

    typedef struct VkMemoryHeap {
      VkDeviceSize size;
      VkMemoryHeapFlags flags;
    } VkMemoryHeap;

and this description:

> • size is the total memory size in bytes in the heap.

>• flags is a bitmask of attribute flags for the heap. The bits specified in flags are:

    typedef enum VkMemoryHeapFlagBits {
    VK_MEMORY_HEAP_DEVICE_LOCAL_BIT = 0x00000001,
    } VkMemoryHeapFlagBits;

But when I query `VkPhysicalDeviceMemoryProperties`  I've got flags with zero values. My code matches the output from Vulkan SDK vkjson_info.exe tool, which output a JSON file with properties from my GPU.

Is something missing here ?

**Comment by krOoze** [comment]
(I am not Khronos member, so my answer have no authority here)
Hi,
unless otherwisely specified, zero flags are allowable. In this case, it would mean NOT HEAP_DEVICE_LOCAL (essentially Host Local).

Though at least one of your heaps MUST be DEVICE_LOCAL.

As a matter of style, I would myself welcome named 0 flag (if it has meaning), perhaps without the _BIT suffix.

BTW: quote newest spec, which is 1.0.10 right now.

**Comment by oddhack** [comment]
Agreed with @krOoze - as long as you have one heap with DEVICE_LOCAL_BIT set it's OK to have another with no flags set:

    Each memory type returned by flink:vkGetPhysicalDeviceMemoryProperties must:
    have its pname:propertyFlags set to one of the following values:
    
    * 0
    * (various other valid flag combinations)

If you don't have a DEVICE_LOCAL heap, that sounds like a violation of the spec (and something the conformance tests should catch, if they don't already test for that) - but judging from the report in #189, that's not a concern. So unless I'm missing something in your issue, there's nothing actually wrong here and I'm closing the issue.
