### ISSUE TITLE
Suggestion for another VkFormat: VK_FORMAT_R11G11B10_UFLOAT_PACK32

### ISSUE THREAD

**Issue by alexpanter** [KhronosGroup/Vulkan-Docs#1886]
Release Task List

Title of issue:  Task list for `Vulkan 1.3.219 Specification: VkFormat` release

The task list for the `Vulkan 1.3.219 Specification: VkFormat` release is:

This issue is a minor suggestion for an added `VkFormat` enum value. This is the reference:

 - [ ] Vulkan Specification:  [VkFormat(3) Manual Page](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkFormat.html)

Certain rendering algorithms (like bloom) benefit from having 3 color channels packed together in 32 bits. We already have the
`VK_FORMAT_B10G11R11_UFLOAT_PACK32 = 122` format, but the color channels are "swizzled". This stands in contrast to OpenGL where we have the `GL_R11F_G11F_B10F` internal format available for the function `glTexImage2D` ([glTexImage2D](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glTexImage2D.xhtml)).

I'm quite new to Vulkan, so I assume that this can be circumvented by modifying the swizzle flags of a `VkImageView`. But since many other formats explicitly have swizzled formats, e.g. `VK_FORMAT_R8G8B8A8_UNORM = 37` <> `VK_FORMAT_B8G8R8A8_UNORM = 44`, so I can only assume there must be some good reason for this.

So I suggest, if it is a good idea, considering adding another format, which would be of the form:
```
VK_FORMAT_R11G11B10_UFLOAT_PACK32
```

Perhaps this would also be more intuitive when reading from an image of such format into a framebuffer with similar color channel order, e.g. `VK_FORMAT_B8G8R8A8_UNORM`.

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by krOoze** [comment]
The color channels are not swizzled. Just stored in blue-endian fashion. For what reason is the order the driver stores the colors important to you?

**Comment by alexpanter** [comment]
So let's say I have a 2d image sampler around an image that use the format `VK_FORMAT_B10G11R11_UFLOAT_PACK32`. Would I not need to explicitly swizzle the channels in the fragment shader when I expect the colors to be RGB and not BGR? Example:
```glsl
layout (binding = 1) uniform sampler2D texSampler;
layout (location = 0) in vec2 texCoord;
void main()
{
    vec3 rgb = texture(texSampler, texCoord).bgr; // <-- since the channels are stored differently?
}
```

Pardon me if I'm mistaken..

**Comment by nanokatze** [comment]
VK_FORMAT_B10G11R11_UFLOAT_PACK32 and GL_R11F_G11F_B10F are the same format

**Comment by nanokatze** [comment]
VK_FORMAT_B10G11R11_UFLOAT_PACK32 and GL_R11F_G11F_B10F are the same format. Packed formats specify bit layout within a word, not byte layout, and in Vulkan it's specified in MSB to LSB, which can be somewhat surprising. This does mean that for example VK_FORMAT_R8G8B8A8_UNORM and VK_FORMAT_A8B8G8R8_UNORM_PACK32 have the same layout in little-endian environment (i.e. everywhere)

**Comment by alexpanter** [comment]
I see. Thank you for taking your time to answer this. I appreciate it!
