### ISSUE TITLE
Is VkMemoryPropertyFlagBits missing Zero value ?

### ISSUE THREAD

**Issue by AlessandroBorges** [KhronosGroup/Vulkan-Docs#189]
Hi !

I have the same enumeration problem described at issue #188, but with VkMemoryPropertyFlagBits 

>The definition of VkMemoryType is:

    typedef struct VkMemoryType {
     VkMemoryPropertyFlags propertyFlags;
     uint32_t heapIndex;
    } VkMemoryType;

and this description:

> •  heapIndex describes which memory heap this memory type corresponds to, and must be less than
memoryHeapCount from the VkPhysicalDeviceMemoryProperties structure.
> • propertyFlags is a bitmask of properties for this memory type. The bits specified in propertyFlags are:

    typedef enum VkMemoryPropertyFlagBits {
      VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT = 0x00000001,
      VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT = 0x00000002,
      VK_MEMORY_PROPERTY_HOST_COHERENT_BIT = 0x00000004,
      VK_MEMORY_PROPERTY_HOST_CACHED_BIT = 0x00000008,
      VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT = 0x00000010,
    } VkMemoryPropertyFlagBits;

But, in the same way as pointed at Issue #188,  when I query `VkPhysicalDeviceMemoryProperties`  I've got flags with zero values. 
My code matches the output from Vulkan SDK vkjson_info.exe tool, which output a JSON file with properties from my GPU:

My gpu.json output:

	(...)
	"memory":	{
		"memoryTypeCount":	4,
		"memoryTypes":	[{
				"propertyFlags":	0,
				"heapIndex":	1
			}, {
				"propertyFlags":	1,
				"heapIndex":	0
			}, {
				"propertyFlags":	6,
				"heapIndex":	1
			}, {
				"propertyFlags":	14,
				"heapIndex":	1
			}],
		"memoryHeapCount":	2,
		"memoryHeaps":	[{
				"size":	"0x0000000040000000",
				"flags":	1
			}, {
				"size":	"0x00000000c0000000",
				"flags":	0
			}]
	}
	(...)

**Comment by krOoze** [comment]
As replied in issue #188 it is valid. 0 flag means "neither of the above". In this case it is explicitely listed in spec as valid output.
Though it is odd type of memory to have - Host Local non-mappable memory solely for unefficient device use.

**Comment by oddhack** [comment]
Again, agreed with @krOoze . It is allowable to have memory types with propertyFlags of 0, so long as you satisfy the other constraints - see the VkMemoryType definition in the spec.

**Comment by philiptaylor** [comment]
> ~~Though it is odd type of memory to have - Host Local non-mappable memory solely for unefficient device use (Is this BIOS reserved RAM for Intel integrated GPU by any chance?).~~

(That gpu.json looks like NVIDIA's memory layout, and NVIDIA always seems to set up heap 1 to contain nearly the entire host RAM, and I guess non-host-visible host-local memory is useful as an overflow or swap area when you want more capacity than the device-local heap can provide.)

**Comment by krOoze** [comment]
(I realized so, hence the striked text. It pretty much offers the same Heap as any Type you want, including as non-mappable type; potentialy space for optimalizations if the user chooses the Type with least capabilities for his task. But e.g. my AMD offers it always as mappable)
