### ISSUE TITLE
Task list for VK_EXT_metal_objects release

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/Vulkan-Docs#1898]
In a Vulkan implementation that is layered on top of Metal on Apple device platforms, this extension provides the ability to import and export the underlying Metal objects associated with specific Vulkan objects.

In a Vulkan implementation that is layered on top of Metal on Apple device platforms, this extension provides the ability to import and export the underlying Metal objects associated with specific Vulkan objects.

As detailed in the [extension proposal document](https://github.com/KhronosGroup/Vulkan-Docs/tree/main/proposals/VK_EXT_metal_objects.asciidoc), this extension adds one new Vulkan command, [vkExportMetalObjectsEXT](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkExportMetalObjectsEXT.html), to export underlying Metal objects from Vulkan objects, and supports importing the appropriate existing Metal objects when creating Vulkan objects of types [VkDeviceMemory](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDeviceMemory.html), [VkImage](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkImage.html), [VkSemaphore](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSemaphore.html), and [VkEvent](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkEvent.html).

The intent is that this extension will be advertised and supported only on implementations that are layered on top of Metal on Apple device platforms.
The intent is that this extension will be advertised and supported only on implementations that are layered on top of Metal on Apple device platforms.

The task list for the `VK_EXT_metal_objects` release is:

 - [x] Vulkan Specification:  https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_EXT_metal_objects.html
 - [x] SDK released: 
     - [x] Validation layer: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4279

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by spnda** [comment]
The merged commit from the referenced VVL PR is part of the sdk-1.3.224 tag: https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/285dbdcd30581237e73fb05708ecc6ca737f062e

All tasks should be checked off now.

**Comment by marty-johnson59** [comment]
Yes, all done.  Closing this tracker.
