### ISSUE TITLE
VkRenderingInfo.renderArea granularity

### ISSUE THREAD

**Issue by konstantinegorov** [KhronosGroup/Vulkan-Docs#1899]
Should the render area in dynamic rendering match some kind of granularity for optimal performance?

**Comment by Tobski** [comment]
Hi Konstantine, we did discuss this but there was some awkwardness with it, and no IHV has expressed a sufficient performance advantage to adding it. So no, use whatever alignment you like. We'll update the proposal document to call this out in an issue.

**Comment by oddhack** [comment]
Proposal document updated in v1.3.224 spec update.
