### ISSUE TITLE
"Subset" in device memory type ordering

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#190]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#memory-device says:

> Given two memory types X and Y, the preorder defines X <= Y if:
> * the memory property bits set for X are a subset of the memory property bits set for Y. Or,
> * the memory property bits set for X are the same as the memory property bits set for Y, and X uses a memory heap with greater or equal performance (as determined in an implementation-specific manner). 

Any set is a subset of itself, by the conventional definition of "subset", which makes the second bullet point redundant. The first bullet point should say "proper subset" (or "strict subset" or "subset of, but not equal to," etc) instead of "subset", so that it doesn't apply when the sets are equal.

**Comment by oddhack** [comment]
Thanks. Folding this in with the fix to #191 and noting "strict subset" vs. subset in the style guide.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.12 update.
