### ISSUE TITLE
Setting dynamic state with graphics libraries (VK_EXT_graphics_pipeline_library)

### ISSUE THREAD

**Issue by ncesario-lunarg** [KhronosGroup/Vulkan-Docs#1902]
Is it legal to set dynamic state associated with pipeline state subset X during creation of a pipeline library that does not contain state subset X?

For example, is it legal to include `VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY`--which is associated with the vertex input subset of state--in the dynamic state of a pre-rasterization library not including any vertex input state? I haven't had a chance to test this out, but it sounds like @zmike has encountered a crash in a driver related to this. If this is indeed invalid, is there a VU?

CC @pdaniell-nv @Tobski

**Comment by zmike** [comment]
I'm not sure about any crashes being related to this (though it's possible), but I do know (from discussions during GPL development) that this is invalid behavior. After searching the spec, however, I don't see any VU for dynamic state in relation to pipeline libraries, nor do I see a normative list of which dynamic states belong to which pipeline stages.

**Comment by Tobski** [comment]
Setting dynamic state in a subset that doesn't include it has no effect, it's completely ignored (hence no VU) - if you want the state to by dynamic it has to be set in the subset where it's actually included.

**Comment by ncesario-lunarg** [comment]
> I'm not sure about any crashes being related to this

Sorry, I meant "invalid behavior" (that's what I get for posting this late at night :/)

> Setting dynamic state in a subset that doesn't include it has no effect, it's completely ignored (hence no VU) - if you want the state to by dynamic it has to be set in the subset where it's actually included.

Right, that's why I created this issue. That doesn't seem to be what implementations are expecting, and I'm wondering why that is. More specifically: do implementations have to make a fix, or do we need a VU for it (which is why I looped @pdaniell-nv in, since lavapipe and nvidia are the only implementations I'm currently aware of).

**Comment by Tobski** [comment]
What is the behavior you're seeing?

**Comment by zmike** [comment]
Potentially this may have been crashing the NVIDIA driver I was testing on, but I haven't yet done a followup run after fixing the (application) usage to verify.

**Comment by Tobski** [comment]
I've created an internal change to make this behavior clearer, and requested new CTS tests to ensure this works.

**Comment by pdaniell-nv** [comment]
It should be fine to enable dynamic state on pipeline libraries that don't intersect with that state. It should be ignored. If you have more details about the crash on NVIDIA I would love to hear about it.

**Comment by zmike** [comment]
> It should be fine to enable dynamic state on pipeline libraries that don't intersect with that state. It should be ignored. If you have more details about the crash on NVIDIA I would love to hear about it.

I was mistaken and thought this was the sources of my GPL-related crashes. It wasn't.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.228 spec update.
