### ISSUE TITLE
VkAccelerationStructureTypeKHR in VK_KHR_acceleration_structure: manpage describes VK_ACCELERATION_STRUCTURE_TYPE_GENERIC_KHR unhelpfully

### ISSUE THREAD

**Issue by mcclure** [KhronosGroup/Vulkan-Docs#1904]
Say I need to know what values are allowed for `VkAccelerationStructureTypeKHR`. I type "VkAccelerationStructureTypeKHR" into Google. It brings up [this web page](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkAccelerationStructureTypeNV.html).

It lists three values in the enum. _TOP_ and _BOTTOM_ I understand what they mean from the tutorial and also the text on the manpage is helpful.

But there is a third value (emphasis mine)

> VK_ACCELERATION_STRUCTURE_TYPE_GENERIC_KHR is an acceleration structure whose type is determined at build time used **for special circumstances**.

"For special circumstances" is deeply unhelpful and there is nothing here to indicate where to look for more information.

When I google further I find a [press release](https://videocardz.com/press-release/khronos-releases-vulkan-ray-tracing-final-specification) with more detail, but not enough:

> We also added a new acceleration structure type for layering – VK_ACCELERATION_STRUCTURE_TYPE_GENERIC_KHR. This can be used at acceleration structure creation time in cases where the actual acceleration structure type (top or bottom) is not yet known. The actual acceleration structure type must be specified as VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_KHR or VK_ACCELERATION_STRUCTURE_TYPE_BOTTOM_LEVEL_KHR when the build is performed and cannot be changed. Applications written directly for Vulkan should not use VK_ACCELERATION_STRUCTURE_TYPE_GENERIC_KHR as this could affect capabilities or performance in the future

What does "directly" mean? I asked for more information in the Discord and "CharlesG - LunarG", who I think is somehow involved with the spec committee explained

> This is in the VK_KHR_acceleration_structure extension spec, so its definitely meant for translation layers.
> in other words, yes, don't use it unless your goal is to translate dx12 raytracing into vulkan raytracing

This gave me the information I needed. (When I went to file this bug I discovered that the [extension document "Issues"](https://github.com/KhronosGroup/Vulkan-Docs/blob/8dcc7469b01529600b712596a5a48ec8c710e228/appendices/VK_KHR_acceleration_structure.txt#L366) contained similarly helpful text, but I failed to find this in normal searching).

<hr>

**"Expected behavior"**: My personal "use case" is I am on a project writing a Lua wrapper for Vulkan. So the information I needed looking up the enum is *under what circumstances, if any, would one of my users use this value?* This means there are two pieces of information I needed communicated, of which the second is the more important.  

1. The GENERIC value is only for calls "early" in the acceleration structure lifecycle, and must permanently change to TOP or BOTTOM eventually.
2. The GENERIC value *should not be used* except specifically in DirectX (or Metal?) emulation layers, under pain of possible forward incompatibility.

The enum manpage is the closest thing we have to a "reference" and I should be able to get this information from the manpage. Currently the manpage communicates the first thing unclearly and the second not at all.

I am not sure what document needs to be modified exactly to change the man page, the page itself says it is autogenerated from the spec.

**Comment by sjfricke** [comment]
not able to answer the core questions, but

> I am not sure what document needs to be modified exactly to change the man page

It just needs to be edited this repo
https://github.com/KhronosGroup/Vulkan-Docs/blob/8dcc7469b01529600b712596a5a48ec8c710e228/chapters/resources.txt#L5675-L5677

**Comment by oddhack** [comment]
Assigning to Raytracing TSG.

**Comment by dgkoch** [comment]
> The enum manpage is the closest thing we have to a "reference" and I should be able to get this information from the manpage. 

Disagree here. The specification is the reference, and one shouldn't expect to learn all the details of the API from a man page. 

I'll add a note to the spec which tries to explain this in more detail, but it's unlikely to end up in the man page.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.226 spec update.
