### ISSUE TITLE
Add an official name for all commands that are tied to a pipeline binding state

### ISSUE THREAD

**Issue by sjfricke** [KhronosGroup/Vulkan-Docs#1908]
There are many times in various Vulkan related projects where the `vkCmdDraw*`/`vkCmdDispatch*`/`vkCmdTraceRays*` are grouped together, but there is no good "official" name for these "action commands"

I think it would be both simple and helpful to add a term to the glossary (and probably under `vkCmdBindPipeline`) to have a single name for these.

(Sorry in advance for any potential naming conversation time spent on this :smile: )

**Comment by Tobski** [comment]
Can you explain the context that this would be useful in?

**Comment by sjfricke** [comment]
Recently wasted an hour chasing a "bug" in the Validation layers for ray tracing stuff because from legacy naming things are called [DrawDispatch](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/drawdispatch.cpp#L46) even though it really includes `vkCmdTraceRays` too... would love to rename it. 

In another unlisted project I also have the same issue and rather not just call it the function/class `DrawAndDispatchCommands` but its annoying there is no dedicated name for these commands.

**Comment by Tobski** [comment]
I wouldn't want to define a name/term in the Vulkan spec if it's not actually going to be used _in_ the Vulkan spec, otherwise it's likely to just be removed incidentally at some point because there will be no clear reason for it to exist. If we can find a good use for this inside the spec though then it'd be a reasonable thing to add, so it needs some thought.

**Comment by sjfricke** [comment]
that is a fair point... I guess I would compare it to `ICD` where it is not actually "used in the spec", defined in the glossary, and everyone just agrees on a single name to make things consistent everywhere

**Comment by sjfricke** [comment]
Closing because decided to just use the name these `Provoke Commands` because the spec already says

> Drawing commands (commands with Draw in the name) provoke work in a graphics pipeline
>
> Dispatching commands (commands with Dispatch in the name) provoke work in a compute pipeline
>
> Ray tracing commands provoke work in the ray tracing pipeline

and feel that is enough to justify a name change where I want
