### ISSUE TITLE
VK_IMG_filter_cubic is tricubic filtering supported?

### ISSUE THREAD

**Issue by Devaniti** [KhronosGroup/Vulkan-Docs#1911]
[VK_IMG_filter_cubic] @tobski
Reading documentation, this sentence sounds confusing. `VK_IMG_filter_cubic adds an additional, high quality cubic filtering mode to Vulkan, using a Catmull-Rom bicubic filter.`. Does it allow for tricubic filtering?

**Comment by Tobski** [comment]
Hi Devaniti, I'm afraid it doesn't. Mip filtering is done by a separate enum, which is not extended: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSamplerMipmapMode.html

It is entirely plausible to implement tricubic yourself using shader instructions though (been too long so I am afraid I don't remember the details...), so I'd look into that if it's something you want to use.

**Comment by oddhack** [comment]
Closing this as @Tobski has answered the question.
