### ISSUE TITLE
Interaction between VK_NV_mesh_shader and line width

### ISSUE THREAD

**Issue by pascal-gw** [KhronosGroup/Vulkan-Docs#1914]
Hi,

Graphics pipelines:
- can have a line width (within the range given by `VkPhysicalDeviceLimits::lineWidthRange`).
- are used by mesh shaders (`VK_NV_mesh_shader`).

I couldn't find a reference in the spec mentioning that this line width is not supported by mesh shaders (it works as expected with vertex+fragment shaders). But in practice it doesn't work (tested on a GeForce RTX 3080 with the driver 516.59).

Cheers,
Pascal.

**Comment by pdaniell-nv** [comment]
Line width should work just fine with mesh shaders. Do you have a simple repro you can share?

**Comment by pascal-gw** [comment]
I sadly can't share the code. While isolating a simple repro I found out the root of the issue.
The line width is only taken into account with mesh shaders when the polygon mode from the `VkPipelineRasterizationStateCreateInfo` is set to `VK_POLYGON_MODE_LINE`, not with `VK_POLYGON_MODE_FILL`. This behavior is different from the regular vertex shaders and there is an inconsistency.

**Comment by pdaniell-nv** [comment]
Thanks for your analysis. This appears to be a driver bug. Please continue to set polygonMode=VK_POLYGON_MODE_LINE as a work-around when your mesh shaders draw lines. We'll get this fixed asap.

**Comment by pdaniell-nv** [comment]
I think this issue is also fixed in the latest Vulkan beta driver, which you can use for development purposes. That driver can be found here: https://developer.nvidia.com/vulkan-driver.

**Comment by pascal-gw** [comment]
Thanks for your help Daniell :) I can then close the issue.
