### ISSUE TITLE
pNext structure chaining

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#192]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#fundamentals-validusage says:

> Any parameter that is a structure containing a void* pNext member must have a value of pNext that is either NULL, or points to a valid structure defined by an extension. If that extension is supported by the implementation, then it must be enabled. Any component of the implementation (the loader, any enabled layers, and drivers) must ignore extension structures with sType values defined by extensions not supported by that component.

I don't remember seeing any restrictions on what can be a "valid structure defined by an extension", so how can an implementation test the sType value of an arbitrary extension structure whose layout it knows nothing about? It might not have an sType, or it might have one that's not the first member.

It should be defined somewhere that if an extension defines a new structure that can be put in a pNext member, then that new structure must start with a "VkStructureType sType" member.

Also, is it intended that the implementation will stop reading down a chain of pNext structures the first time it reaches one that it doesn't support? I think that's what the current spec indicates ("must ignore extension structures ..." implying it'll ignore the structure's pNext), but that means it's impossible to have two enabled layers that each support a different extension structure on the same command, because the second layer won't read past the unsupported first extension structure.

I think it should say that whenever an extension defines a new structure, then that new structure must start with "VkStructureType sType" and "const void* pNext" members, and every component of the implementation must continue to follow the pNext chain even if it doesn't recognise sType. (I think https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#_extension_interactions is suggesting that chaining behaviour, but it doesn't specify the necessary constraints on extension structures to make it possible.)

**Comment by oddhack** [comment]
Yes, that's a good catch. We'll take care of it. I think there was a notion that some extensions might introduce their own APIs that didn't use structure chaining and not want the overhead of pNext/sType chaining, and some structures (e.g. VkExtend2D) are so basic as not to need extensibility, but we should drill down on when it's required.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.12 update.
