### ISSUE TITLE
Autogen SPIR-V and Vulkan Image Format Compatibility table?

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Docs#1920]
Suggested by @sjfricke in https://github.com/KhronosGroup/Vulkan-Docs/pull/1916#discussion_r948427455 . If you're not planning to do the \<\<spirvenv-image-formats>> table generator, let me know and I'll take this, though probably not in the immediate future. Slightly annoying to end up writing more generator script than the length of the table but OTOH reducing duplication is always a good thing.

**Comment by sjfricke** [comment]
I will take this (soon) as when I made that comment I also realized I never got around to generating more of the spec tables from the new XML `<format>` tag added
