### ISSUE TITLE
VK_KHR_format_feature_flags2 buffer view VU confusion

### ISSUE THREAD

**Issue by sjfricke** [KhronosGroup/Vulkan-Docs#1923]
@djdeath add this change in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4101 to help solve https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4049 (cc @pdaniell-nv)

So The VU says

> VUID-vkCmdDraw-OpTypeImage-07030
Any **VkBufferView** being read as a storage texel buffer where the image format field of the OpTypeImage is Unknown then the view’s **buffer features** must contain VK_FORMAT_FEATURE_2_STORAGE_READ_WITHOUT_FORMAT_BIT

But we changed the code to check for the `VkFormatProperties3::linearTilingFeatures` which seems to contradict this VU and the wording in `VkFormatProperties3`

If this **was** the correct change to the Validation Layers I would expect the VU to say `linear features` instead of `buffer features` and then add to `linearTilingFeatures` spec

> linearTilingFeatures is a bitmask of [VkFormatFeatureFlagBits2](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VkFormatFeatureFlagBits2) specifying features supported by images created with a tiling parameter of VK_IMAGE_TILING_LINEAR **or buffers accessed as images**.

**Comment by sjfricke** [comment]
The spec also has a section that says

> The following bits may be set in bufferFeatures, specifying that the features are supported by [buffers](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VkBuffer) or [buffer views](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VkBufferView) created with the queried [vkGetPhysicalDeviceFormatProperties2](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#vkGetPhysicalDeviceFormatProperties2)::format:
>
> VK_FORMAT_FEATURE_2_STORAGE_READ_WITHOUT_FORMAT_BIT specifies that buffer views created with this format can be used as [storage texel buffers](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#descriptorsets-storagetexelbuffer) for read operations without specifying a format.

adding more to my confusion why we are validating the `linearTilingFeatures`

**Comment by Tobski** [comment]
Validation got changed in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4101 before we discussed this in the working group, and we made a _different_ change to what that MR expected. It seems the validation layers haven't caught up to the change yet, but the spec is correct, validation layers are wrong.

**Comment by sjfricke** [comment]
closed with https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4479
