### ISSUE TITLE
vkCmdDrawIndexed and friends have no VUID for index buffer being bound

### ISSUE THREAD

**Issue by Eearslya** [KhronosGroup/Vulkan-Docs#1924]
`vkCmdDrawIndexed` and other indexed draw commands have no VUID which states that an index buffer must be bound at the time of execution.

The closest we currently have is `VUID-vkCmdDrawIndexed-firstIndex-04932` which forbids accessing the bound index buffer out of bounds. The wording of this VUID is such that it seems to assume an index buffer must always be bound. (Emphasis mine)

> VUID-vkCmdDrawIndexed-firstIndex-04932
> (indexSize × (firstIndex + indexCount) + offset) must be less than or equal to the size *__of the bound index buffer__*, with indexSize being based on the type specified by indexType, where the index buffer, indexType, and offset are specified via vkCmdBindIndexBuffer

**Comment by sjfricke** [comment]
So the Validation Layers currently validate this (in `CoreChecks::ValidateDrawStateFlags`) and mark it as

> VUID-vkCmdDrawIndexed-commandBuffer-02701
If the VkPipeline object bound to the pipeline bind point used by this command requires any dynamic state, that state must have been set or inherited (if the [VK_NV_inherited_viewport_scissor](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VK_NV_inherited_viewport_scissor) extension is enabled) for commandBuffer, and done so after any previously bound pipeline with the corresponding state not specified as dynamic

**Comment by paul-lunarg** [comment]
Validation layers have a check for this under the wrong VUID : 
```
VUID-vkCmdDrawIndexed-commandBuffer-02701(ERROR / SPEC): msgNum: -1468188274 - Validation Error: [ VUID-vkCmdDrawIndexed-commandBuffer-02701 ] Object 0: handle = 0x17d06bc7020, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xa87d398e | VkCommandBuffer 0x17d06bc7020[]: Index buffer object not bound to this command buffer when Indexed Draw attempted. The Vulkan spec states: If the VkPipeline object bound to the pipeline bind point used by this command requires any dynamic state, that state must have been set or inherited (if the VK_NV_inherited_viewport_scissor extension is enabled) for commandBuffer, and done so after any previously bound pipeline with the corresponding state not specified as dynamic (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdDrawIndexed-commandBuffer-02701)
    Objects: 1
        [0] 0x17d06bc7020, type: 6, name: NULL
```

**Comment by sjfricke** [comment]
So I think `04932` is already a mouth-full and this should just be a dedicated VU 

Made a PR, happy to also move the Validation VU to it after if approved

**Comment by krOoze** [comment]
Isn't it simply allowed to run without vertex and index buffer?

E.g. `vkCmdDraw*` simply invokes N shader executions. There do not have to be any associated data.

**Comment by Eearslya** [comment]
Running without vertex/index buffers makes sense for the non-indexed commands because the shader can simply use `gl_VertexIndex` or equivalent to determine which vertex to render. But the point of the indexed draw commands is that you're explicitly giving it a list of `gl_VertexIndex` values. It might make sense to run `vkCmdDrawIndexed` without a vertex buffer, but without an index buffer makes no sense.

**Comment by krOoze** [comment]
@Eearslya Hm, makes sense.

Although it is not that farfetched to believe that `vkCmdDrawIndexed( indexCount, firstIndex, vertexOffset )` could just revert to `vkCmdDraw( vertexCount = indexCount, firstVertex = vertexOffset)` if there is no index buffer. Though for compatibility reasons it is cleaner to just ban things in case of ambiguity.

Also what if `instanceCount` or `indexCount` is `0`? Or what if the `gl_VertexIndex` is not accessed?
