### ISSUE TITLE
Allow depth clipping to be disabled dynamically

### ISSUE THREAD

**Issue by gvcallen** [KhronosGroup/Vulkan-Docs#1925]
VkPipelineRasterizationDepthClipStateCreateInfoEXT::depthClipEnable allows depth clipping to be set at the pipeline stage, however it might be necessary to set this option dynamically e.g. in CAD software.

This issue suggests adding a function to do this. A suggested signature would be:
vkCmdSetDepthClipEnable(VkCommandBuffer commandBuffer, VkBool32 depthClipEnable).

This would be a lot more convenient than having to create multiple pipelines.

**Comment by pdaniell-nv** [comment]
This should be covered by the new VK_EXT_extended_dynamic_state3 extension: https://github.com/KhronosGroup/Vulkan-Docs/issues/1961
