### ISSUE TITLE
Typo error in section 29.2.3. wl_device should be wl_display.

### ISSUE THREAD

**Issue by podain** [KhronosGroup/Vulkan-Docs#193]
> Some Vulkan functions may send protocol over the specified wl_device connection when using a swapchain or presentable images created from a VkSurfaceKHR referring to a wl_surface. Applications must therefore ensure that both the wl_device and the wl_surface remain valid for the lifetime of any VkSwapchainKHR objects created from a particular wl_device and wl_surface. Also, calling vkQueuePresentKHR will result in Vulkan sending wl_surface.commit requests to the underlying wl_surface of each VkSwapchainKHR objects referenced by pPresentInfo. Therefore, if the application wishes to synchronize any window changes with a particular frame, such requests must be sent to the Wayland display server prior to calling vkQueuePresentKHR.

Check this last paragraph of the section 29.2.3.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.13 spec update.
