### ISSUE TITLE
Duplicated VkGraphicsPipelineCreateInfo member description.

### ISSUE THREAD

**Issue by native-m** [KhronosGroup/Vulkan-Docs#1934]
`VkGraphicsPipelineCreateInfo` contains two similar member description for `pInputAssemblyState`.

> pInputAssemblyState is a pointer to a VkPipelineInputAssemblyStateCreateInfo structure which determines input assembly behavior, as described in Drawing Commands. It is ignored if the pipeline includes a mesh shader stage.

> pInputAssemblyState is a pointer to a VkPipelineInputAssemblyStateCreateInfo structure which determines input assembly behavior for vertex shading, as described in Drawing Commands.

**Comment by ShabbyX** [comment]
Looks like a merge conflict resolution error when VK_EXT_mesh_shader was rebased.

**Comment by native-m** [comment]
Yeah, probably.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.227 spec update.
