### ISSUE TITLE
Clarify the behavior when freeing a memory object which has resources bound to it.

### ISSUE THREAD

**Issue by psionic12** [KhronosGroup/Vulkan-Docs#1937]
According to spec of `vkFreeMemory`:

> If there are still any bound images or buffers, the memory object’s payload **_may_** not be immediately released by the implementation, but must be released by the time all bound images and buffers have been destroyed. 

What will happen to resources if an implementation choose to release the memory object immediately when `vkFreeMemory` is called? 

 If the resource is unbound to the memory implicitly, will re-bind a resource to another memory trigger `VUID-vkBindImageMemory-image-01044(image must not already be backed by a memory object)` validation rules? 

I did a test, the validation layer warn me about 

> previous bound to memory that has since been freed. Memory bindings are immutable in Vulkan so this attempt to bind to new memory is not allowed.

But not VUID-vkBindImageMemory-image-01044.

I guess this means that the validation considered the image is unbound, so it will not trigger `VUID-vkBindImageMemory-image-01044`, but the validate layer also think this is invalid, though it is not mentioned as validation rules in spec.

So please clarify this behavior.

**Comment by psionic12** [comment]
I can safely regard "backed" as "bound" in Vulkan spec? The spec didn't explain this, but used everywhere, I took some time to understand this and think it is same as "bound", but not for sure.

By the way, I can help to create a PR to update the validation rule.

**Comment by r-potter** [comment]
Yes. Bound and backed are the same thing here. Thanks for the offer on the PR, but I produced an internal PR this morning which should get reviewed in our next maintenance meeting.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.230 spec update.
