### ISSUE TITLE
ShaderViewportIndexLayerEXT requirements with version 1.2

### ISSUE THREAD

**Issue by ziga-lunarg** [KhronosGroup/Vulkan-Docs#1948]
From the spec:

> If the VK_EXT_shader_viewport_index_layer extension is not supported, support for the ShaderViewportIndexLayerEXT SPIR-V capability is optional. Support for this feature is defined by VkPhysicalDeviceVulkan12Features::shaderOutputViewportIndex and VkPhysicalDeviceVulkan12Features::shaderOutputLayer when queried via vkGetPhysicalDeviceFeatures2.

But vk.xml lists only:
```
<spirvcapability name="ShaderViewportIndexLayerEXT">
    <enable extension="VK_EXT_shader_viewport_index_layer"/>
</spirvcapability>
```

The problem also seems to be that the xml schema currently does not allow for multiple features to be required.

**Comment by sjfricke** [comment]
So I think

```xml
<spirvcapability name="ShaderViewportIndexLayerEXT">
    <enable extension="VK_EXT_shader_viewport_index_layer"/>
    <enable struct="VkPhysicalDeviceVulkan12Features" feature="shaderOutputViewportIndex" requires="VK_VERSION_1_2"/>
    <enable struct="VkPhysicalDeviceVulkan12Features" feature="shaderOutputLayer" requires="VK_VERSION_1_2"/>
</spirvcapability>
```

fixes this

**Comment by ziga-lunarg** [comment]
> > The problem also seems to be that the xml schema currently does not allow for multiple features to be required.
> 
> It does... so I think
> 
> ```
> <spirvcapability name="ShaderViewportIndexLayerEXT">
>     <enable extension="VK_EXT_shader_viewport_index_layer"/>
>     <enable struct="VkPhysicalDeviceVulkan12Features" feature="shaderOutputViewportIndex" requires="VK_VERSION_1_2"/>
>     <enable struct="VkPhysicalDeviceVulkan12Features" feature="shaderOutputLayer" requires="VK_VERSION_1_2"/>
> </spirvcapability>
> ```
> 
> fixes this

But I believe this only requires one of the features, while if I'm understanding the spec correctly, both should be required?

The setup that produces this issue is using vulkan version 1.2 and not enabling the `VK_EXT_shader_viewport_index_layer` extension and then using the `ShaderViewportIndexLayerEXT` capability, in this case the validation layers will complain, and that code is autogenerated from vk.xml.

**Comment by sjfricke** [comment]
Ok, Looking at the SPIR-V spec

> 4.36. Changes from Version 1.4
    Extensions Incorporated into SPIR-V 1.5:
        **SPV_EXT_shader_viewport_index_layer**, with changes: Replaced the single **ShaderViewportIndexLayerEXT** capability with the two new [capabilities](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Capability) **ShaderViewportIndex** and **ShaderLayer**. Declaring both is equivalent to declaring **ShaderViewportIndexLayerEXT**.
        
So I am now re-convinced that there is **no issue here** and that if an application wants to use `ShaderViewportIndexLayerEXT` in a Vulkan 1.2 app with no `VK_EXT_shader_viewport_index_layer` they need to break it into the 2 new capabilities

**Comment by oddhack** [comment]
That's a relief. Should we tweak the spec language to make this more clear? No idea if this is a one-off or this sort of dependency / promotion interaction is common.

**Comment by sjfricke** [comment]
I can purpose a spec clarification. Also definitely a one off, it the nature of the extension forgetting the feature bit and not sure if SPIRV ever split another Capability bit like this before
