### ISSUE TITLE
No VUID for requirement that image usage must be supported by format

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-Docs#1949]
The documentation of `VkImageCreateInfo` mentions in a "note" section that usage bits can only be used if supported by the format. But if `VK_IMAGE_CREATE_EXTENDED_USAGE_BIT` is included, then usage bits don't have to be supported by the format as long as there is a potential image view format that supports it.

As far as I've been able to tell, there is no VUID that requires either of these two points. Should there be one?

**Comment by ncesario-lunarg** [comment]
I might be conflating this with another issue, but I thought image + format validity was checked at image creation time [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/92ed21f6a188b02dfc62a88c0ac40d5153429704/layers/buffer_validation.cpp#L1959) and then at image view creation time [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/92ed21f6a188b02dfc62a88c0ac40d5153429704/layers/buffer_validation.cpp#L5843-L5878).

More specifically we use `vkGetPhysicalDeviceImageFormatProperties` to determine if the format + usage is valid; is this not sufficient?

**Comment by Rua** [comment]
I wasn't aware that calling that function was sufficient to satisfy that requirement, sorry.

**Comment by ncesario-lunarg** [comment]
I vaguely recall a discussion where this was explained in more detail, but can't find it now. I will reference it here if I can find it.

**Comment by Rua** [comment]
Is `vkGetPhysicalDeviceImageFormatProperties` in some sense a mini validator for part of the members of `VkImageCreateInfo`? If so, are there any VUIDs on `VkImageCreateInfo` that can be validated by calling this function?

**Comment by krOoze** [comment]
> VUID-VkImageCreateInfo-imageCreateMaxMipLevels-02251
Each of the following values (as described in _Image Creation Limits_) **must** not be undefined : `imageCreateMaxMipLevels`, `imageCreateMaxArrayLayers`, `imageCreateMaxExtent`, and `imageCreateSampleCounts`

**Comment by ncesario-lunarg** [comment]
@Rua was your original question answered? To add to spec language that we are relying on: https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap44.html#vkGetPhysicalDeviceImageFormatProperties
> If format is not a supported image format, or if the combination of format, type, tiling, usage, and flags is not supported for images, then vkGetPhysicalDeviceImageFormatProperties returns VK_ERROR_FORMAT_NOT_SUPPORTED.

I don't think `VK_IMAGE_CREATE_EXTENDED_USAGE_BIT` is an exception here, AFAIK.
