### ISSUE TITLE
Can format VK_FORMAT_D24_UNORM_S8_UINT be used in VkSamplerCustomBorderColorCreateInfoEXT

### ISSUE THREAD

**Issue by ziga-lunarg** [KhronosGroup/Vulkan-Docs#1950]
`VUID-VkSamplerCustomBorderColorCreateInfoEXT-format-04013` says:

> If provided format is not VK_FORMAT_UNDEFINED then the VkSamplerCreateInfo::borderColor type must match the sampled type of the provided format, as shown in the SPIR-V Sampled Type column of the https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#formats-numericformat table

But this format has a UNORM part which requires float and UINT part which requires int, does that mean this format can not be used with `VkSamplerCustomBorderColorCreateInfoEXT`?

**Comment by sjfricke** [comment]
To my knowledge, `VK_EXT_custom_border_color` was never intended to be used on depth/stencil images, but also can't find anything in the spec saying `VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER` can't be used with depth/stencil

**Comment by jekstrand** [comment]
This should all be fine.  As quoted above, the border color type must match the SPIR-V and the SPIR-V is required to match the aspect in the `VkImageView` it's combined with at sampling time.  Any given `VkImageView` used for sampling must only specify one of depth or stencil.  It cannot specify both.  If it specifies depth, it must be combined with a float sampler in SPIR-V which, if it uses custom border color, must use `VK_BORDER_COLOR_FLOAT_CUSTOM_EXT` and, if it specifies stencil, it must be combined with an int sampler in SPIR-V which, if it uses custom border color, must use `VK_BORDER_COLOR_INT_CUSTOM_EXT`.  In either case, the `VkFormat` specified in the sampler custom border color must match the `VkFormat` used by the image view.  I don't see any ambiguity.

**Comment by ziga-lunarg** [comment]
@jekstrand Thanks!

**Comment by ziga-lunarg** [comment]
Reopening as I have a further question on this. You said required format is determined at sampling time, but `VUID-VkSamplerCustomBorderColorCreateInfoEXT-format-04013` already checks the format when the sampler is created. Does the VUID need a fix?

**Comment by jekstrand** [comment]
Yeah, probably....

**Comment by jekstrand** [comment]
I've made an internal spec MR which should resolve this.

**Comment by ziga-lunarg** [comment]
Thanks!
