### ISSUE TITLE
Is pInputAssemblyState required when tessellation shaders are used?

### ISSUE THREAD

**Issue by ziga-lunarg** [KhronosGroup/Vulkan-Docs#1956]
`VUID-VkGraphicsPipelineCreateInfo-pStages-00736` says:

> If the pipeline is being created with pre-rasterization shader state and pStages includes tessellation shader stages, the topology member of pInputAssembly must be VK_PRIMITIVE_TOPOLOGY_PATCH_LIST

But `VUID-VkGraphicsPipelineCreateInfo-pStages-02098` says `pInputAssemblyState` is only required if the pipeline is being created with vertex input state.

Does that mean `pInputAssemblyState` is also required when tessellation shaders are used?

**Comment by HansKristian-Work** [comment]
Yes, the spec as written intends that PATCH_LIST must be specified for tessellation pipelines and pInputAssemblyState is required.

**Comment by ziga-lunarg** [comment]
@HansKristian-Work Thanks!
