### ISSUE TITLE
Clarification about shading rate extension and RenderPass2

### ISSUE THREAD

**Issue by theWatchmen** [KhronosGroup/Vulkan-Docs#1957]
[VK_KHR_fragment_shading_rate] @tobski
Hi, according to the spec for this extension:
> Requires [VK_KHR_create_renderpass2](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VK_KHR_create_renderpass2) to be enabled for any device-level functionality

Is this still a requirement when using FSR with the `VK_KHR_dynamic_rendering` extension? With the dynamic rendering extension, calling `BeginRenderPass` is no longer required.

I am asking because at the moment I am simply passing an image view in the `VkRenderingFragmentShadingRateAttachmentInfoKHR` structure (with correct layout), but `gl_ShadingRateEXT` always returns 0 in the fragment shader.

I think the image contains the correct values, 0x0 for 1x1 rate and 0x5 for 2x2 rate. I am not using this extension to modify the rates per-primitive or pipeline. Is there anything else required for the correct behaviour of this extension?

The device I am running on supports Vulkan 1.3.201 and all of the extensions required. The Vulkan SDK I am using is 1.2.198.1.

Many thanks,

Marco

**Comment by r-potter** [comment]
In this case, the requirement to enable `VK_KHR_create_renderpass2` is mainly a side-effect of how we define dependencies between extensions in the `vk.xml` file. It's not intended to imply that you need to create `VkRenderPass` objects or call `vkCmdBeginRenderPass2` with dynamic rendering. The validation layers will complain if you don't enable `VK_KHR_create_renderpass2`, and there is unlikely to be a performance cost to doing so, so we recommend that you do enable  the extension.

With that said, it's unlikely that whether or not you enabled `VK_KHR_create_renderpass2` is modifying the internal behaviour of an implementation in a way that would result in the issues you are seeing here.

**Comment by theWatchmen** [comment]
Thanks for your reply. I recently upgraded the Vukan SDK to the latest version and it's flagging some errors with how I use this extension. It's likely causing the issue I mentioned.

Slightly unrelated to the original question, do I understand correctly that `minFragmentShadingRateAttachmentTexelSize` is the minimum "area" size that can be represented by a texel in a shading rate image?

So if `minFragmentShadingRateAttachmentTexelSize` is 16x16, that's the maximum granularity the shading rate image can have?

**Comment by r-potter** [comment]
> Slightly unrelated to the original question, do I understand correctly that `minFragmentShadingRateAttachmentTexelSize` is the minimum "area" size that can be represented by a texel in a shading rate image?
> 
> So if `minFragmentShadingRateAttachmentTexelSize` is 16x16, that's the maximum granularity the shading rate image can have?

This is correct.

**Comment by theWatchmen** [comment]
Great, thanks for your help!
