### ISSUE TITLE
"Availability" vs "Visibility" for Image and Buffer Barriers

### ISSUE THREAD

**Issue by Snosixtyboo** [KhronosGroup/Vulkan-Docs#1958]
## Issue
The sections on image and buffer memory barriers in the Synchronization chapter make the following claim: 

> The second access scope is limited to access to memory through the specified buffer range, via access types in the destination access mask specified by dstAccessMask. If dstAccessMask includes VK_ACCESS_HOST_WRITE_BIT or VK_ACCESS_HOST_READ_BIT, available memory writes are also made visible to accesses of those types, as those access types are not performed through a resource.

This seems to transcend the statements in the Memory Model appendix, which state, with regard to memory dependencies: 

> If the destination access mask includes VK_ACCESS_HOST_READ_BIT or VK_ACCESS_HOST_WRITE_BIT, then the dependency includes a memory domain operation from device domain to host domain.

Also, the description of vkInvalidateMappedMemoryRanges states:

> vkInvalidateMappedMemoryRanges guarantees that device writes to the memory ranges described by pMemoryRanges, which have been made available to the host memory domain using the VK_ACCESS_HOST_WRITE_BIT and VK_ACCESS_HOST_READ_BIT, are made visible to the host.

Going by the first definition, using image or buffer memory barriers would make the use of vkInvalidateMappedMemoryRanges redundant, even with non-host-coherent memory, as it is already made visible. 

## Suggestion

If I interpreted this correctly as an inconsistency, I would suggest changing "visible to accesses of those types" for the description of image and buffer memory barriers in a manner consistent with the remaining sections, e.g., by describing it as a domain operation or by stating that data is made "available" on the host, rather than "visible".

**Comment by krOoze** [comment]
They are made _visible to_, just stays on the wrong domain:

Read this:

> An operation that performs a memory dependency generates:
> - If the source access mask includes VK_ACCESS_HOST_WRITE_BIT, then the dependency includes a memory domain operation from host domain to device domain.
> - An availability operation with source scope of all writes in the first [access scope](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#synchronization-dependencies-access-scopes) of the dependency and a destination scope of the device domain.
> - **A visibility operation with source scope of the device domain and destination scope of the second access scope of the dependency.**
> - If the destination access mask includes VK_ACCESS_HOST_READ_BIT or VK_ACCESS_HOST_WRITE_BIT, then the dependency includes a memory domain operation from device domain to host domain.

**Comment by Snosixtyboo** [comment]
> * of the device domain and destination scope of the second acces

So am I understanding this right, it means the data would become **visible** to VK_ACCESS_HOST_READ_BIT access types made via the device, but not via the host because, although there is a domain operation, the visibility operation occurs in the device domain only?

**Comment by krOoze** [comment]
You are reading the same text I do. First AV ops happen within the device domain, then the domain op happens after it (which makes stuff available-from in one domain also available-from on another domain).

I mean there probably is no difference. Visibility to a pipeline stage the device does not use might be meaningless. But it is likely there for consistency.

Should indeed probably not call it out (and the " as those access types are not performed through a resource" neither) since it is uninportant and confusing. Instead should mention it makes the barrier to include a domain op, which is much more important.

**Comment by HansKristian-Work** [comment]
I think it makes sense to clarify the

> If dstAccessMask includes VK_ACCESS_HOST_WRITE_BIT or VK_ACCESS_HOST_READ_BIT, available memory writes are also made visible to accesses of those types, as those access types are not performed through a resource.

to refer to memory domain operations instead. I've raised this internally.
