### ISSUE TITLE
Unable to build Vulkan/X11 on MacOS

### ISSUE THREAD

**Issue by tnagorran** [KhronosGroup/Vulkan-Docs#1959]
Undefined symbols for architecture x86_64:
  "_vkCreateXlibSurfaceKHR", referenced from:
      _demo_create_surface in <>
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

X11 works on MacOS, it would be nice to add the support for porting old programs

**Comment by oddhack** [comment]
@tnagorran are you using MoltenVK as your Vulkan implementation? If so then this issue should be moved over there, else to wherever your implementation comes from. This repository is just for the specification documents and headers, not implementation issues.

**Comment by tnagorran** [comment]
yes I use MoltenVK
