### ISSUE TITLE
LAZILY_ALLOCATED VkBuffer is allowed

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#196]
In ch. 11.6. Resource Memory Association, there is nicely:

> The memoryTypeBits member must not refer to a VkMemoryType with a propertyFlags that has the VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT bit set if the VkImage does not have VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT bit set in the usage member of the VkImageCreateInfo structure passed to vkCreateImage. 

Similar restriction is missing for the case of a VkBuffer.
I assume, buffer is not allowed to be allocated lazily (ch 10.2.2.):

> A memory type with this flag set is only allowed to be bound to a VkImage whose usage flags include VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT.

Possible resolution:
rewrite to
> The memoryTypeBits member must not refer to a VkMemoryType with a propertyFlags that has the VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT bit set unless the requirements are of a VkImage, that was created using VkImageCreateInfo structure with the VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT bit set in it's usage member.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.15 spec update.
