### ISSUE TITLE
pImmutableSamplers member is listed under Description

### ISSUE THREAD

**Issue by MennoVink** [KhronosGroup/Vulkan-Docs#1964]
My apologies if this is not the correct place to report this issue. I couldn't find the text being shown in this repo or any other.

https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDescriptorSetLayoutBinding.html#_description

On this page the pImmutableSamplers member is listed under "Description". I think it should be listed under "Members".

**Comment by oddhack** [comment]
It is the correct place - thanks! This is due to a trivial markup error and will be fixed in the next spec update.

**Comment by oddhack** [comment]
This is fixed in the 1.3.231 spec update.
