### ISSUE TITLE
The benefits of using arrays as function input parameters

### ISSUE THREAD

**Issue by psionic12** [KhronosGroup/Vulkan-Docs#1970]
TL;ND:
 There are lots of functions which takes an array as input in Vulkan, I wondered is this just a code style, or batching input parameters will actually get a better performance for these functions.

Detail:
At first, I think if a function takes an array as input, it means that batching parameters is good for performance, so I will collect parameters into an array as much as possible. But since not all the inputs are sits in memory continuously, I'm always thinking creating a space on heap and copy parameters is worth it. (And this also makes the code of my render a little complicated, but it's not important).

But one day I read the [best practice](https://developer.nvidia.com/blog/vulkan-dos-donts/) wrote by NVIDIA, and there's a suggestion like this: 

> Parallelize command buffer recording, image and buffer creation, descriptor set updates, pipeline creation, and memory allocation / binding.

This is somehow conflicted with Vulkan API: `vkUpdateDescriptorSets`, since in Vulkan, the API suggests putting all descriptor sets together and call at once, which will update then in one thread.

So in this case (update descriptor sets), who is right?
Furthermore, when I meet an API which takes an array as input, is it guaranteed that batching parameters is good for performance?

**Comment by krOoze** [comment]
Vulkan specification gives almost no guarantees about performance, so the question is  somewhat unanswerable. You can assume batching parameters together **may** be good for performance.

**Comment by psionic12** [comment]
So it looks a code style to me, right? Since we don't know whether the batching is good for performance, we just design the API as accepting inputs as an array, in case the driver could benefit from it?

**Comment by krOoze** [comment]
No, if it **might** lead to better performance, then the API design practically has to do it. That is not just esthetics, right?

I must reiterate the specifiction does not and cannot make guarantees about performance. For example, CPU emulation can be a Vulkan implementation too, in which case any performance assumptions would be entirelly different from average GPU.

**Comment by ShabbyX** [comment]
If you are looking for data points, we found out that batching `vkUpdateDescriptorSets` leads to considerable save on CPU performance. That said, if you have different threads doing updates, each could batch their respective updates and the CPU time is divided between the threads. I don't really see batching and parallelism being in conflict here.

**Comment by oddhack** [comment]
@psionic12 if your question has been addressed, please close this.
