### ISSUE TITLE
Descriptor set update with template should have a way to ignore entries

### ISSUE THREAD

**Issue by Dolkar** [KhronosGroup/Vulkan-Docs#1971]
With the addition of `VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT`, it is a common use case to avoid updating certain descriptors that are known to be unused by the pipeline. For both `vkUpdateDescriptorSet` and `vkUpdateDescriptorSetWithTemplate`, all descriptors provided are required to be valid. With regular descriptor set updates, this is not a problem as we can easily omit those descriptors from the update, but with `vkUpdateDescriptorSetWithTemplate`, this appears to not be possible without creating a separate template for every combination of omitted descriptors.

The design of descriptor update templates encourages applications to manage a cpu-side data structure storing the most up-to-date descriptor data, which are then pushed to Vulkan descriptor sets as needed. However, this can currently only be leveraged when this data structure is fully populated, even with partially-bound descriptor bindings.

This could be handled by stating that data entries with NULL handles are ignored by the update, but that may conflict with the nullDescriptor feature. Alternatively, the user could provide a list of booleans as a mask for which descriptors or entries in the update template should be updated. This way, we can keep using a single update template per descriptor layout while being able to selectively omit updating certain descriptors.

**Comment by HansKristian-Work** [comment]
Normally, when I think of PARTIALLY_BOUND_BIT, I'm thinking bindless where descriptors are updated sparsely and not in a big batch. Templates are tuned for the more traditional use case where you allocate one descriptor set and then update all bindings in one go in an optimized fashion. In my understanding these API features are used in very different use cases.

Do you have a concrete use case where you need to use PARTIALLY_BOUND_BIT on non-bindless descriptor sets?

Adding more edge cases (code paths) for a descriptor update template to handle does not seem to be ideal. Would it work to just use nullDescriptor in lieu of not writing a descriptor?

**Comment by Dolkar** [comment]
> Do you have a concrete use case where you need to use PARTIALLY_BOUND_BIT on non-bindless descriptor sets?

Yes, and it seems like a fairly common use case to me, too: Shaders that conditionally read a resource depending on some uniform flag. Examples could be textures that not all materials using this shader have, decals, animation buffers, or even global resources like shadow maps, light & fog grids, reflection probes, etc, whose features may be disabled for some options or scenes. We know at draw time that the descriptors won't be read, but without the PARTIALLY_BOUND_BIT we are obligated to define them anyway. There are alternative ways to handle it, but they all have downsides:
1. Compiling pipelines for each specific set of features that are to be used leads to a combinatorial explosion of pipeline counts. 
2. Binding dummy resources works in cases where it allows us to read the resource unconditionally inside the shader, but otherwise it's just extra overhead to fulfill API obligations. We would need many such dummy resources for various resource types and in some cases in various formats to satisfy valid usage.
3. The nullDescriptor feature that isn't universally supported and brings unknown performance implications.

Note that this can also extend beyond the PARTIALLY_BOUND_BIT functionality. For example, we define a single descriptor set layout for all those global resources such as shadow maps, which is then used in most pipeline layouts as set number 0. This then allows us to switch between pipelines without disturbing the 0th global descriptor set. But this again leads to draws that don't even statically use a resource in the bound descriptor set, but whose templated updates still need to provide a valid descriptor for.

Personally, I feel like the cleanest solution would be to allow null descriptors even in the base API, in both `vkUpdateDescriptorSet` and `vkUpdateDescriptorSetWithTemplate` for the sake of consistency. They would not be considered as valid descriptors, unless the nullDescriptor feature is enabled, in which case it provides robustness guarantees just like reading out of bounds would.

**Comment by HansKristian-Work** [comment]
> Compiling pipelines for each specific set of features that are to be used leads to a combinatorial explosion of pipeline counts.

Would it be possible to just have different descriptor update templates in that case? Not sure why you'd need different pipelines. A descriptor update template does not have to update every descriptor if it does not want to.

> The nullDescriptor feature that isn't universally supported and brings unknown performance implications.

It's not universally supported, no. It's a native hardware feature and is not expected to change performance however.

**Comment by Dolkar** [comment]
> Would it be possible to just have different descriptor update templates in that case? Not sure why you'd need different pipelines.
In that paragraph, I was explaining why we need PARTIALLY_BOUND_BIT outside of a bindless setup. Otherwise, if we don't have different pipelines (and thus the shader branches on a dynamic uniform), then the resources are still statically used and must be valid at the time of the draw call.

It would be possible to use PARTIALLY_BOUND_BIT and have one pipeline with multiple descriptor update templates, but then we must still create a template for every combination of features that can be toggled on or off. At runtime, we would look up which update template to use based on the set of active features / resources. It's doable, but I have my doubts about it being any more efficient than the driver just uploading garbage descriptor data / skipping over entries, or if it's even worth the trouble compared to non-template descriptor updates.

> It's a native hardware feature and is not expected to change performance however.
But it's a part of VK_EXT_robustness2 which states:
> These additional requirements may be expensive on some implementations, and should only be enabled when truly necessary.
Though it's unclear whether that applies to null descriptors as well. If not, I think it's worth pointing out in the spec that it is not expected to change performance unlike other robustness features.
