### ISSUE TITLE
Wrong Vulkan version requirement for VK_EXT_mesh_shader

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Docs#1976]
The version dependencies for [VK_EXT_mesh_shader](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_mesh_shader.html) only require support for Vulkan 1.0

But VK_EXT_mesh_shader also requires support for [VK_KHR_spirv_1_4](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_spirv_1_4.html), which in turn requires Vulkan 1.1

That looks contradictious. Shouldn't VK_EXT_mesh_shader then also at least require Vulkan 1.1?

**Comment by oddhack** [comment]
Thanks. Plausibly there are other cases where this transitive mis-dependency exists but we'll fix this one in the next spec update.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.235 spec update.

**Comment by krOoze** [comment]
Hm, why does `VK_KHR_spirv_1_4` require 1.1 though...
