### ISSUE TITLE
Require binding input attachment in a descriptor set even when statically not used?

### ISSUE THREAD

**Issue by hrydgard** [KhronosGroup/Vulkan-Docs#1979]
I'm wondering about `VUID-vkCmdDraw-None-02686`: "Every input attachment used by the current subpass must be bound to the pipeline via a descriptor set".

What about draw calls that have shaders that statically do not read from the input attachment at all? 

Let's say in a subpass that has an input attachment, I first make a few draws with a pipeline that doesn't care about input attachments, the fragment shader just has regular outputs. Then, I make some draws that do care and do read from the input attachment.

Do those first draws really need to have the input attachment bound in their descriptor sets, even though they very statically don't read from it? From an IHV perspective the answer is likely "no", but the validation layers have another opinion, since https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4519

**Comment by HansKristian-Work** [comment]
Yes, this is an oversight, it should follow the normal use on static use here. I'll propose the change.

**Comment by spencer-lunarg** [comment]
So this was updated in 1.3.236

new section was also added to describe this interaction
https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#compatibility-inputattachment

There is a validation layers issue to cover this from here now that the spec was updated.

@hrydgard if you feel there is something left, please feel free to reopen with concerns

**Comment by hrydgard** [comment]
Nice! Just the clarification that was needed. Will test newer validation layers once resolved on that side.
