### ISSUE TITLE
Clarification for VkDescriptorBufferInfo.range with dynamic offset descriptors

### ISSUE THREAD

**Issue by luckyxxl** [KhronosGroup/Vulkan-Docs#1981]
To me, the wording `static size` in the following sentence in the `Descriptor Set Updates` chapter is unclear.

```
For VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC and VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC
descriptor types, offset is the base offset from which the dynamic offset is applied
and range is the static size used for all dynamic offsets.
```

Does this mean that `range` denotes the memory size that is visible to shaders after the dynamic offset has been applied, or does `range` denote the memory size in which all dynamic offsets + shader access offsets must be contained?

In other words, consider a uniform buffer that holds 4 structs with size `minUniformBufferOffsetAlignment`. I want to call `vkCmdBindDescriptorSets` 4 times, each time with a dynamic offset pointing to a different element in this buffer[1]. Would `VkDescriptorBufferInfo.range` have to be `minUniformBufferOffsetAlignment` or `4 * minUniformBufferOffsetAlignment`?

[1] so `pDynamicOffsets[ i ] = 0`, `pDynamicOffsets[ i ] = minUniformBufferOffsetAlignment`, `pDynamicOffsets[ i ] = 2 * minUniformBufferOffsetAlignment`, ...

**Comment by spencer-lunarg** [comment]
> Would VkDescriptorBufferInfo.range have to be minUniformBufferOffsetAlignment or 4 * minUniformBufferOffsetAlignment?

it is `minUniformBufferOffsetAlignment` as that is the size of that data you want to actually use in the shader

There is a chapter about descriptor dynamic offset in the Vulkan Guide that might help https://github.com/KhronosGroup/Vulkan-Guide/blob/master/chapters/descriptor_dynamic_offset.adoc

so if you have

```glsl
layout(set = 0, binding = 0) uniform uniformBuffer {
    MyStruct data; // size of minUniformBufferOffsetAlignment
} ubo;
```

and your data was laid out in a `VkBuffer` as

```cpp
MyStruct buffer[4];
```

you would go

```cpp
VkDescriptorBufferInfo bufferInfo = {
    buffer,
    0, // offset
    minUniformBufferOffsetAlignment // range
};
```

and then at draw time

```cpp
uint32_t dynamicOffsets[4] = {
    minUniformBufferOffsetAlignment * 0,
    minUniformBufferOffsetAlignment * 1,
    minUniformBufferOffsetAlignment * 2,
    minUniformBufferOffsetAlignment * 3,
}

vkCmdBindPipeline();
vkCmdBindDescriptorSets(/* */, 1, &dynamicOffsets[0]); // buffer[0]
vkCmdDraw();
vkCmdBindDescriptorSets(/* */, 1, &dynamicOffsets[1]); // buffer[1]
vkCmdDraw();
vkCmdBindDescriptorSets(/* */, 1, &dynamicOffsets[2]); // buffer[2]
vkCmdDraw();
vkCmdBindDescriptorSets(/* */, 1, &dynamicOffsets[3]); // buffer[3]
vkCmdDraw();
```
