### ISSUE TITLE
Minor issues with the html generation and a question about the "See Also" list

### ISSUE THREAD

**Issue by elect86** [KhronosGroup/Vulkan-Docs#1984]
I'm going throw the raw docs (`.adoc`) to generate docs for a kotlin binding and I noticed a couple of issues:
- `undefined:` isn't rendered properly as bold as, for example: `must:` ([here](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkFlags.html))
- `VkFlags64` in the footnote isn't clickable 

Also, always in the footnote, since we are at it, where will be deduced `VkColorComponentFlags, VkFlags64`? I cant find anything in the `apimap.py` about it..

**Comment by oddhack** [comment]
undefined: isn't intended to generate markup, but the : is an internal signal that the WG has reviewed the usage and agreed that the behavior is indeed undefined.

The lack of internal linkage for VkFlags64 should be fixed - I'll take a look at it though it will not be a high priority.

I'm not sure which footnote you're referring to?

**Comment by elect86** [comment]
Sorry, under the
> See Also

in the [VkFlags](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkFlags.html)

**Comment by oddhack** [comment]
The markup for VkFlags explicitly lists VkColorComponentFlags as a cross-reference because it's referred to in the text - see chapters/fundamentals.adoc around line 916. Not all such linkages can be captured from the XML for various reasons.

**Comment by elect86** [comment]
Ah, interesting.

Thanks

Ps: are there any other cross-references other than in `/gen` and `/chapters`?

**Comment by oddhack** [comment]
Some of the xrefs are to appendices. They are all internal to the document.

**Comment by elect86** [comment]
In `synchronization.adoc`, at 
`[open,refpage='VK_WHOLE_SIZE',desc='Sentinel value to use entire remaining array length',type='consts']`

> It can: be specified for slink:VkBufferMemoryBarrier::pname:size and other
structures.

the first `:` looks wrong

**Comment by oddhack** [comment]
can: is correct markup for the normative term.

It would help provide some context if you could say what you're doing with the markup as part of your bindings.

**Comment by oddhack** [comment]
@elect86 I believe all the issues originally brought up have been addressed, or responded to, at this point. Can this be closed?

**Comment by elect86** [comment]
Yes, I'll give you more background as soon as I have a moment
