### ISSUE TITLE
VK_EXT_fragment_density_map Issue

### ISSUE THREAD

**Issue by chenyangchenyang** [KhronosGroup/Vulkan-Docs#1985]
[VK_EXT_fragment_density_map] @mnetsch
*Here describe the issue or question you have about the VK_EXT_fragment_density_map extension*

When create device, I added extension VK_EXT_fragment_density_map (Supported By Device) (means VkDeviceCreateInfo.ppEnabledExtensionNames = "xxx"...,"VK_EXT_fragment_density_map",..."")

But Found a Validation Error:
[ VUID-vkCmdPipelineBarrier-dstStageMask-04093 ] Object 0: handle = 0x70d9740c00, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x2660d4fc | vkCmdPipelineBarrier(): .dstStageMask includes VK_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT when the device does not have fragmentDensity feature enabled. The Vulkan spec states: If the fragment density map feature is not enabled, pname:dstStageMask must not contain VK_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkCmdPipelineBarrier-dstStageMask-04093

Why??

**Comment by spencer-lunarg** [comment]
You are missing the `VkPhysicalDeviceFragmentDensityMapFeaturesEXT::fragmentDensity` feature which is different than the extension

There is a Vulkan Guide chapter on this that explains this
https://github.com/KhronosGroup/Vulkan-Guide/blob/master/chapters/querying_extensions_features.adoc

as well as instructions how to enable the feature bit
https://github.com/KhronosGroup/Vulkan-Guide/blob/master/chapters/enabling_features.adoc

**Comment by chenyangchenyang** [comment]
Thanks~
