### ISSUE TITLE
Intent of VUID-vkCmdWaitEvents2-srcStageMask-03842 regarding `HOST_BIT`

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-Docs#1986]
This VUID mentions two possible values for `srcStageMask`, either "only pipeline stages valid for the queue family" or "only `VK_PIPELINE_STAGE_2_HOST_BIT`". However, the first option includes the second, because `VK_PIPELINE_STAGE_2_HOST_BIT` is valid for all queue families, following the information in https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap7.html#synchronization-pipeline-stages-supported. So the part that says "only `VK_PIPELINE_STAGE_2_HOST_BIT`" seems redundant.

The fact that it's explicitly mentioned in the VUID makes me think that the VUID really intended something else: that the first option must not include `VK_PIPELINE_STAGE_2_HOST_BIT`. In other words, if `srcStageMask` includes `VK_PIPELINE_STAGE_2_HOST_BIT`, it must not include any other bits. If that was indeed the original intent of the VUID, then the wording, as well as that of VUID-vkCmdWaitEvents2-dstStageMask-03843 possibly, would need to be changed. A VUID to the same effect might be helpful to have on `vkCmdSetEvent2` as well.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.270 spec update.
