### ISSUE TITLE
Incorrect returnedonly="true" on VkSubresourceLayout

### ISSUE THREAD

**Issue by afrantzis** [KhronosGroup/Vulkan-Docs#1988]
In the `VkImageDrmFormatModifierExplicitCreateInfoEXT` function, an array of struct `VkSubresourceLayout` is used to pass information from the application to the API:

```
<type category="struct" name="VkImageDrmFormatModifierExplicitCreateInfoEXT" structextends="VkImageCreateInfo">
    <member values="VK_STRUCTURE_TYPE_IMAGE_DRM_FORMAT_MODIFIER_EXPLICIT_CREATE_INFO_EXT"><type>VkStructureType</type> <name>sType</name></member>
    <member optional="true">const <type>void</type>* <name>pNext</name></member>
    <member><type>uint64_t</type> <name>drmFormatModifier</name></member>
    <member optional="false"><type>uint32_t</type> <name>drmFormatModifierPlaneCount</name></member>
    <member len="drmFormatModifierPlaneCount">const <type>VkSubresourceLayout</type>* <name>pPlaneLayouts</name></member>
</type>
```

This contradicts the `returnedonly="true"` flag on `VkSubresourceLayout` (the flag was correct before the introduction of the `VK_EXT_image_drm_format_modifier` extension). What is the policy on updating the`returnedonly` flag  in such cases?

Thanks!

**Comment by oddhack** [comment]
This was fixed in the 1.3.236 spec update.
