### ISSUE TITLE
missed s/:apiname:/Vulkan/ in WSI

### ISSUE THREAD

**Issue by ratchetfreak** [KhronosGroup/Vulkan-Docs#199]
There are 10 places where `:apiname:` wasn't replaced properly with Vulkan.

They all are under the valid usage of vk*SurfaceCreateInfor for the XServer-based extensions (VkXcbSurfaceCreateInfoKHR  and VkXlibSurfaceCreateInfoKHR)

**Comment by oddhack** [comment]
Ping @TobiasHector . Not sure if you missed one of the extension branches or I did, when merging them up with 1.0 prior to pushing to github?

**Comment by TobiasHector** [comment]
Whoops. This is an issue in the registry - didn't realise anyone had used {apiname} in a validity statement and I failed to update the xml. Fix is easy enough though.

NB: This affects all WSI extensions since they all include that validity statement.

**Comment by TobiasHector** [comment]
Oh I see - I missed some actual text in those extensions too. Not entirely sure how I missed them - but still - simple fix.

**Comment by TobiasHector** [comment]
Ah - the reason I missed those extra :apiname:'s is because they are delimited with colons instead of curly braces - didn't even know that worked. I only looked for {apiname}.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.13 spec update.
