### ISSUE TITLE
【mali gpu 】 About VK_EXT_fragment_density_map

### ISSUE THREAD

**Issue by chenyangchenyang** [KhronosGroup/Vulkan-Docs#1993]
Hi,

[VK_EXT_fragment_density_map] @mnetsch

About VK_EXT_fragment_density_map(VkPhysicalDeviceFragmentDensityMapFeaturesEXT) ([registry.khronos.org/.../vkspec.html](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#features-fragmentDensityMap))

when used VK_EXT_fragment_density_map , **mali gpu (Device1 & Device2)** has crashed In vkCmdEndRenderPass (crash stack in attachment , **No Validation Error**)，and **Adreno  gpu (Device3)** has succeed

Device1(mali)

 Oppo Reno5 Pro 5G
 GpuFamily：ARM Mali-G77 MC9
 AndroidVersion：12
GlVersion：OpenGL ES 3.2 v1.r32p1-01eac0.111ce79c0e85a639772bd634d9e734cf,) 
VulkanVersion: 1.1.177
Device2(mali)

GpuFamily: Mali-G77 MC9
AndroidVersion: 11
GlVersion: OpenGL ES 3.2 v1.r26p0-01eac0.bed3b8f44871361148086fa6397ba747
VulkanVersion: 1.1.131
Device3(Adreno)

vivo
GpuFamily: Adreno (TM) 660
AndroidVersion: 11
GlVersion: OpenGL ES 3.2 V@0525.0 (GIT@f7fceaaafa, I5121de8c99, 1605177106) (Date:11/12/20)
VulkanVersion: 1.1.128

Code Setting:

VK_EXT_fragment_density_map be Supported （By vkEnumerateDeviceExtensionProperties）
VkPhysicalDeviceFragmentDensityMapFeaturesEXT.fragmentDensityMap is true (By vkGetPhysicalDeviceFeatures2)
When create device, I added extension VK_EXT_fragment_density_map (Supported By Device) (means VkDeviceCreateInfo.ppEnabledExtensionNames = "xxx"...,"VK_EXT_fragment_density_map",..."") & pNext to VkPhysicalDeviceFragmentDensityMapFeaturesEXT (means VkDeviceCreateInfo.pNext = ... &VkPhysicalDeviceFragmentDensityMapFeaturesEXT ....)

Is  driver (mali)  bug ?
[Mali_VK_EXT_fragment_density_map_Crash_CallStack.txt](https://github.com/KhronosGroup/Vulkan-Docs/files/10051393/Mali_Vulkan.txt)

**Comment by janharaldfredriksen-arm** [comment]
Hi,
Based on the information posted here, it may be a bug in our driver - or it's a bug in the application that somehow only triggers on our driver.
I see you have already reported the issue in the Mali support forums.

I don't see any indication of a spec issue at this point - so can we close this issue and follow up in the Mali support forums?

**Comment by chenyangchenyang** [comment]
> Hi, Based on the information posted here, it may be a bug in our driver - or it's a bug in the application that somehow only triggers on our driver. I see you have already reported the issue in the Mali support forums.
> 
> I don't see any indication of a spec issue at this point - so can we close this issue and follow up in the Mali support forums?

thanks~
