### ISSUE TITLE
One of the bindings in VkDescriptorSetLayout must: have an offset for descriptor buffer of 0.

### ISSUE THREAD

**Issue by Cherser-s** [KhronosGroup/Vulkan-Docs#1994]
I'm wondering if there is any guarantee for `VK_EXT_descriptor_buffer` that when user calls `vkGetDescriptorSetLayoutBindingOffsetEXT` for any `VkDescriptorSetLayout` created earlier with `VK_DESCRIPTOR_SET_LAYOUT_CREATE_DESCRIPTOR_BUFFER_BIT_EXT` flag has at least one binding with an offset of `0`?

This would help save up memory space when dealing with descriptor buffers and ensure that descriptor buffers with single binding will work without creating a `VkDescriptorSet` and querying an offset beforehand.

**Comment by HansKristian-Work** [comment]
I raised this as well, but there wasn't a lot of enthusiasm to carve out special cases here at this time. The expectation is that one binding will return 0 offset here, but there's no guarantee either. There were some concerns that some descriptors could not be placed at offset 0 from base for example (weird as that sounds).

Stronger support for application controlled descriptor set layouts is a known request that we're considering, however.

**Comment by oddhack** [comment]
@Cherser-s if your question has been addressed, please close this issue.
