### ISSUE TITLE
Is descriptorBufferOffsetAlignment meant to require a power of two value?

### ISSUE THREAD

**Issue by Trark** [KhronosGroup/Vulkan-Docs#1995]
VkPhysicalDeviceDescriptorBufferPropertiesEXT::descriptorBufferOffsetAlignment is currently documented as
> descriptorBufferOffsetAlignment indicates the required alignment in bytes when setting offsets into the descriptor buffer.

Unlike most other alignment values specified in other structs, this does not explicitly require the value be a power of two. The description mentions setting the offset. vkCmdSetDescriptorBufferOffsetsEXT has the limit of
> VUID-vkCmdSetDescriptorBufferOffsetsEXT-pOffsets-08061
The offsets in pOffsets must be aligned to [VkPhysicalDeviceDescriptorBufferPropertiesEXT](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPhysicalDeviceDescriptorBufferPropertiesEXT.html)::descriptorBufferOffsetAlignment

Which on its own could theoretically support non power of two aligned offsets. However vkCmdBindDescriptorBuffersEXT also has the restriction:
> VUID-VkDescriptorBufferBindingInfoEXT-address-08057
address must be aligned to [VkPhysicalDeviceDescriptorBufferPropertiesEXT](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPhysicalDeviceDescriptorBufferPropertiesEXT.html)::descriptorBufferOffsetAlignment

This also does not mention power of two alignment, but I believe as the address is from a device memory it is effectively required that the alignment has to be a power of two - as vkAllocateMemory has to return memory aligned for any use case.

Is it meant to be guaranteed that descriptorBufferOffsetAlignment is a power of two or is the implementation able to return something else?

**Comment by HansKristian-Work** [comment]
It's meant to be a POT alignment, yes. Address alignment does not make sense if it's not POT.

vkCmdSetDescriptorBufferOffsetsEXT should be seen as "bind SSBO, bind UBO" or some similar mechanism where hardware needs the base address to be aligned. From that aligned base, individual descriptors can be read with non-POT offsets. E.g. a descriptor size can be 48 or something like that.

**Comment by Trark** [comment]
Thank you for the confirmation.

**Comment by oddhack** [comment]
@trark if your question has been addressed, please close this issue.
