### ISSUE TITLE
vkCmdSetEvent2 and VK_PIPELINE_STAGE_HOST_BIT

### ISSUE THREAD

**Issue by plasmacel** [KhronosGroup/Vulkan-Docs#1996]
According to the current specification, `vkCmdSetEvent2` doesn't share the limitation of `vkCmdSetEvent`:

> [stageMask must not include VK_PIPELINE_STAGE_HOST_BIT](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdSetEvent.html#VUID-vkCmdSetEvent-stageMask-01149)

Does it mean that `srcStageMask/dstStageMask` are allowed to be `VK_PIPELINE_STAGE_HOST_BIT` for `vkCmdSetEvent2`, or the lack of the VUID is a mistake in the spec?

**Comment by Rua** [comment]
This is probably related to #1986.

**Comment by plasmacel** [comment]
The validation layers gives the following error at this case:

> vkQueueSubmit2(): pSubmits[2].pSignalSemaphoreInfos[0].stageMask stage mask must not include VK_PIPELINE_STAGE_HOST_BIT as the stage can't be invoked inside a command buffer.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.268 spec update.
