### ISSUE TITLE
Reentrancy and VkAllocationCallbacks

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#20]
Is it safe for a VkAllocationCallbacks function to call into the Vulkan API? I don't see this specified anywhere.

I think reentrancy is not exactly the same as thread-safety: some functions are defined as internally synchronized, in which case it's safe for many threads to call them concurrently, but it might *not* be safe for an allocation callback to call them, because they might try to acquire an implementation-internal lock that's already held by the caller of the allocation callback, leading to deadlock.

(I can't think of any plausible reason why an application would want to do that, so it should probably just be forbidden.)

**Comment by oddhack** [comment]
We're taking this under discussion internally to get clarification. Thanks.

**Comment by jeffbolznv** [comment]
Internally agreed to forbid this.

**Comment by oddhack** [comment]
Done in the 1.0.5 spec update.
