### ISSUE TITLE
signaled vs unsignalled?

### ISSUE THREAD

**Issue by blitmap** [KhronosGroup/Vulkan-Docs#201]
Hi -

I notice in the docs there are uses of both "signaled" and "unsignalled" - with a single `L` or double.  I'm sure this reflects a European vs American spelling difference - my issue is with the inconsistency.

It might be an improvement to pick 1 stick with it?  :smile:

https://github.com/KhronosGroup/Vulkan-Docs/blob/75bbb5f4d52321eed41337cc463aa036748a1352/src/spec/vk.xml#L2637-L2638

^ It just seems very strange to see both spellings right next to each other.

(there are more files where these appear)

It's a dumb argument to raise but because software dev is so focused in the West perhaps it would also make sense to mandate American English for the entire project.

I'm sorry if this sounds offensive, I'm just suggesting this by who will probably see the docs most.

**Comment by oddhack** [comment]
That's a good catch - thanks. We wrote the spec in a distributed fashion with small groups working on each chapter, so there are lots of little inconsistencies which are gradually being resolved. I will take care of it in the next spec update.

**Comment by krOoze** [comment]
As european non-english speaking country citizen, I must second that. American english aligns nicely with international/non-native english too I think. E.g. color (US) not ~~colour~~ (UK), counter-clockwise (US) not ~~anticlockwise~~(UK), traveler not ~~travellller~~ and so on.

**Comment by oddhack** [comment]
I assume "travellller" is how it is spelled in Welsh English :-)

**Comment by oddhack** [comment]
This should be fixed in the 1.0.13 spec update.

**Comment by blitmap** [comment]
Cool beans - great turnaround :smile:
