### ISSUE TITLE
h.265 reference list specification maybe not be clear

### ISSUE THREAD

**Issue by airlied** [KhronosGroup/Vulkan-Docs#2010]
I've been working on implementing H265 decode along with @cyanreg and ran into a bit of a problem, and I'm not sure how NVIDIA decoder is handling this, @zlatinski maybe you can help clarify.

So HEVC has 3 sets of reference indexes, CurrBefore, CurrAfter and LtCurr. Where do we define what these are indexes into? or  These are defined to be indexes into RefPicList. However Vulkan doesn't specify RefPicList and doesn't really say what that should be generated from.

Now in my hw decoder for radv, I generate RefPicList from the user supplied reference picture array. So if the user gives me 5 reference pictures with slot index [3, 4, 5, 6, 7], I make a RefPicList of [3, 4, 5, 6, 7].  Now we have ffmpeg decoder working on radv with this, but it doesn't work with NVIDIA so there must be something missing in the spec around how RefPicList and the slot index list correspond or how they should be matched up on the driver/decoder side.

**Comment by airlied** [comment]
I've changed radv so that it generates a RefPicList of [0x7f, 0x7f, 0x7f, 3, 4, 5, 6, 7] now and that seems to work.

But I'm not sure the spec is clear enough here, or where to clarify it.

**Comment by zlatinski** [comment]
Hi [airlied](https://github.com/airlied),
The three sets of reference indexes, CurrBefore, CurrAfter and LtCurr are the application managed list of dpb slot indexes. Those are the same dpb slots indexes used within pReferenceSlots->slotIndex within both VkVideoBeginCodingInfoKHR::pReferenceSlots and VkVideoDecodeInfoKHR::pReferenceSlots.

> Now we have ffmpeg decoder working on radv with this, but it doesn't work with NVIDIA so there must be something missing in the spec around how RefPicList and the slot index list correspond or how they should be matched up on the driver/decoder side.

With these lists, nothing else has to be done. I'm aware of the issue and we'll try to debug FFMPEG on NVIDIA's implementation after the new app release on 19th. I tried looking at this the other day but got no meaningful decoded output from FFMPEG.

Thanks!

**Comment by oddhack** [comment]
This should be fixed in the 1.3.239 spec update.
