### ISSUE TITLE
Feature request: vkGetPhysicalDeviceFromLogicalDevice

### ISSUE THREAD

**Issue by JoniSt** [KhronosGroup/Vulkan-Docs#2023]
Dear Khronos group,

I've repeatedly found myself wanting to query properties from the underlying `VkPhysicalDevice` given only a `VkDevice` in the context of resource management (i.e. when initializing a memory pool); however, Vulkan doesn't appear to have a way to retrieve the `VkPhysicalDevice` that was used to create a given `VkDevice`.

It seems to me that such a function should be simple for drivers to implement, therefore I'd like to propose the following new Vulkan function:
```
//Returns the VkPhysicalDevice used to create the given VkDevice
VkPhysicalDevice vkGetPhysicalDeviceFromLogicalDevice(VkDevice);
```

Thank you very much for your support,
JoniSt

**Comment by polarina** [comment]
How would such a command function in the presence of multiple physical
devices backing the logical device, in the context of device groups?

**Comment by JoniSt** [comment]
Ah, I forgot about that particular extension...

It'd have to be something like this, then:
```
VkResult vkGetPhysicalDevicesFromLogicalDevice(VkDevice logicalDevice, uint32_t *pPhysicalDeviceCount, VkPhysicalDevice *pPhysicalDevices);
```
(Similar to how `vkEnumerateInstanceExtensionProperties` works)

This would be very useful for library developers in particular.

**Comment by krOoze** [comment]
In Vulkan, context tracking is the responsibility of the application, not the driver.

**Comment by JoniSt** [comment]
Okay, that's fair enough! It does make getting device limits etc a little more difficult, but I guess the advantage of that approach is simpler, and therefore less buggy, drivers.
