### ISSUE TITLE
[vk_ext_descriptor_buffer] Why VkDescriptorBufferBindingInfoEXT takes a VkDeviceAddress instead of a buffer handle?

### ISSUE THREAD

**Issue by psionic12** [KhronosGroup/Vulkan-Docs#2028]
According to the doc, structure `VkDescriptorBufferBindingInfoEXT` is used for descriptor binding, and it looks weird to me that it doesn't take a buffer handle, instead, it takes a `VkDeviceAddress`:
```
// Provided by VK_EXT_descriptor_buffer
typedef struct VkDescriptorBufferBindingInfoEXT {
    VkStructureType       sType;
    void*                 pNext;
    VkDeviceAddress       address;
    VkBufferUsageFlags    usage;
} VkDescriptorBufferBindingInfoEXT;
```
It seems that the standard wants the implementation to find the proper buffer by `address`, but as far as I know, lots of implementations doesn't maintain a map for this, let along the user could pass an address with an offset. And of course this map takes a lot of memories.

So may I ask what is the purpose of this? Is there a considerable decision to make even if it cost extra memories?

**Comment by nanokatze** [comment]
You might have noticed Vulkan is moving away from VkBuffer in the new APIs. Most implementations don't maintain a map because they don't need to turn VkDeviceAddress into a VkBuffer-offset pair, there won't be any extra memory taken up nor CPU time.

**Comment by psionic12** [comment]
Hi @nanokatze, I'm sorry I didn't read much about new APIs, does that means at some time, I can totally get rid of VkBuffer, and use VkDeviceAddress instead? In other word, there's no need to bind a buffer to a memory object anymore?

**Comment by nanokatze** [comment]
No, you still need to bind VkBuffer before you can get the address of the underlying VkDeviceMemory object (or buffer itself, if it's a sparse buffer) and you still need keep VkBuffer-offset pairs for various APIs that are yet to receive VkDeviceAddress treatment (such as vkCmdBind{IndexBuffer,VertexBuffers} at the time of writing this comment.) But other new APIs such as vkCmdBuildAccelerationStructureKHR or vkCmdTraceRaysKHR all use VkDeviceAddress instead of VkBuffer and offset pairs for example.

**Comment by psionic12** [comment]
Hi, I mean that, does use VkDeviceAddress instead of VkBuffer and offset pairs is to get rid of VkBuffer **in the future**? Or is there any other reason why these new APIs takes VkDeviceAddress?

The reason I asked is that MoltenVK team do have problems implement `vk_ext_descriptor_buffer`, they had to maintain a map to get the buffer+offset from a `VkDeviceAddress`.

**Comment by nanokatze** [comment]
> Hi, I mean that, does use VkDeviceAddress instead of VkBuffer and offset pairs is to get rid of VkBuffer in the future?

Maybe

> The reason I asked is that MoltenVK team do have problems implement vk_ext_descriptor_buffer, they had to maintain a map to get the buffer+offset from a VkDeviceAddress.

Ideally this would be addressed in Metal, there's no technical reason it can not be

**Comment by pdaniell-nv** [comment]
As a general forward direction we've been trying to move away from using VkBuffer and instead use VkDeviceAddress. We hope at some point in the near future apps will have the option to not have to use VkBuffer to specify buffer addresses. As we move in that direction there are still legacy reasons VkBuffer still needs to be used, but hopefully that won't be true for long.
