### ISSUE TITLE
Feature request: Support for more advanced global illumination techniques and shadow volumes extensions?

### ISSUE THREAD

**Issue by ADormant** [KhronosGroup/Vulkan-Docs#2031]
1. We currently have ray tracing, which is a pretty basic form of global illumination. Are you planning to add any extensions for more advanced global illumination like Recursive ray tracing, Metropolis Light Transport, Distributed Ray Tracing, Volumetric Path Tracing, Cone Tracing, Beam Tracing , Energy Redistribution Path Tracing, Light Propagation Volumes, Lightcuts etc. 

2. I think shadow volumes look better than shadow mapping but modern games don't use them because they are slow with everything else modern games are using. Could you add a Vulkan extension for shadow volumes?

These would require new hardware but Intel, Nvidia and AMD will probably add it eventually if you expand the API.

**Comment by HansKristian-Work** [comment]
Implementing graphical techniques is in the domain of application programmers, I don't see how this is directly relevant to Vulkan? If there's any scenario where specific hardware acceleration is **required**, that would be in the domain of Vulkan I think.

**Comment by krOoze** [comment]
There's bit of a reverse dependency implied. HW vendors consider what is possible to be done on a hardware level, and then the API is expanded appropriately. APIs do not prescribe what upcoming HW should do; that is a recipe for disaster.

**Comment by oddhack** [comment]
@ADormant basically same comments as #2032 - please close if you agree. BTW in general, hardware drives the APIs, rather than the other way around. When hardware starts emerging that can perform GI, the APIs will evolve to allow access to it.

**Comment by oddhack** [comment]
Closing per my previous comment.
