### ISSUE TITLE
What does "Requires X to be enabled for any device-level functionality" mean?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#2035]
What does "Requires X to be enabled for any device-level functionality" in extension appendices means?

The "for any device-level functionality" part is confusing what exactly it implies\requires.

**Comment by r-potter** [comment]
As per the glossary, this:

> Device-Level Functionality::
    All device-level commands and objects, and their structures, enumerated
    types, and enumerants.

It's essentially saying that you need to follow the rules in Valid Usage for Extensions and explicitly enable anything that the extension in question builds/relies upon. The device-level wording exists as a carve out to allow the use of physical device functionality prior to logical device creation (and device extension enables).

**Comment by krOoze** [comment]
I do know what a device-level functionality is, which makes it even more confusing.

There are two kinds of requirements in the appendices:
1) "Requires {X} to be enabled"  
and
2) "Requires {X} to be enabled for any device-level functionality"

1 is clear. But I am not clear what 2 is actually saying and how it differs from 1. How do you enable extension for some device-level functionality, and which "any" device-level functionality does it even mean?

**Comment by HansKristian-Work** [comment]
Device-level is anything that uses VkDevice or any derived object from that. Entry points taking VkPhysicalDevice are not device-level functionality.

**Comment by r-potter** [comment]
1. Should always refer to instance extensions.
    There shouldn't be a situation where you are allowed to use anything defined in an instance extension prior to enabling that extension.

2. Should always refer to device extensions. 
   These introduce a mixture of commands/structures/flags etc. that can be used prior to logical device creation (anything that's required at the physical device enumeration/query stage) and those that cannot (any command that operates on a logical device or it's children, or is used as a parameter to those commands).

> Anyway, how would you enable Device Extension dependency before creating a device? That's not satisfiable.

That's exactly the reason for the difference. We cannot require that you must have satisfied any dependency to operate at the physical-device level, only post logical-device creation for functionality that impacts the behaviour of the logical device or it's children.

**Comment by HansKristian-Work** [comment]
Seems like we forgot to close this one. It should be resolved a long while ago now.
