### ISSUE TITLE
Documentation VkPhysicalDevicePushDescriptorPropertiesKHR suspicous

### ISSUE THREAD

**Issue by siliace** [KhronosGroup/Vulkan-Docs#2036]
Hello,

The documentation of the member `maxPushDescriptors` of the structure `VkPhysicalDevicePushDescriptorPropertiesKHR` from the extension `VK_KHR_push_descriptor` states: `maxPushDescriptors is the maximum number of descriptors that can be used in a descriptor set created with VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT_KHR set`.

But `VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT_KHR` is a flag to create a descriptor set **layout**, not a descriptor set.

I think the right statement would be: `maxPushDescriptors is the maximum number of descriptors that can be used in a descriptor set layout created with VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT_KHR set`.

Does my understanding of the spec is right or am I missing something ?

Thanks

**Comment by oddhack** [comment]
Would you be willing to propose a PR to this effect? The WG agrees with your proposed resolution.
