### ISSUE TITLE
About `VK_EXT_extended_dynamic_state3` and `VK_EXT_conservative_rasterization` (not mentioned interaction)

### ISSUE THREAD

**Issue by ghost** [KhronosGroup/Vulkan-Docs#2039]
From `VK_EXT_extended_dynamic_state3` extension, I see `vkCmdSetConservativeRasterizationModeEXT` and `VK_DYNAMIC_STATE_CONSERVATIVE_RASTERIZATION_MODE_EXT`, but it's extension feature from `VK_EXT_conservative_rasterization`. There is no any mentions about interaction between of these extensions. Needs it's to fix?

And what a strange, amazing coincidence. Not so long ago I implemented dynamic state in my projects. NVIDIA has rolled out another driver with support for this feature (yes, I'm including conservative rasterization).

**Comment by pdaniell-nv** [comment]
I believe this should be resolved now in the latest spec. The dependencies between EDS3 and other extensions is expression in the XML and reflected in the generated spec docs. For example, with `vkCmdSetConservativeRasterizationModeEXT` the spec indicates `// Provided by VK_EXT_conservative_rasterization with VK_EXT_extended_dynamic_state3, VK_EXT_conservative_rasterization with VK_EXT_shader_object` and the related VUs require the application to have enabled the `VK_EXT_conservative_rasterization` extension before they apply.
