### ISSUE TITLE
Which which

### ISSUE THREAD

**Issue by MrVallentin** [KhronosGroup/Vulkan-Docs#204]
Just another mistake in a sentence. :smile:

> `flags` is a bitmask controlling the operation. Bits **which which** can be set include:

[Found on line 139 in doc/specs/vulkan/chapters/cmdbuffers.txt](https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/doc/specs/vulkan/chapters/cmdbuffers.txt#L139)

**Comment by krOoze** [comment]
Now the dilema which which to remove from the which which which is to be fixed. :smile:

**Comment by oddhack** [comment]
I will flip a Bitcoin :-)

**Comment by krOoze** [comment]
@oddhack also seems fixed in 1.0.13. close?

**Comment by oddhack** [comment]
Yes, thanks for catching this.
