### ISSUE TITLE
Task list for VK_EXT_pipeline_library_group_handles release

### ISSUE THREAD

**Issue by HansKristian-Work** [KhronosGroup/Vulkan-Docs#2041]
This extensions allow ray tracing group handles to be queried on pipeline libraries. It also guarantees that group handles remain bitwise identical when they are linked into other libraries.

The task list for the VK_EXT_pipeline_library_group_handles release is:

 - [x] Vulkan Specification:  [VK_EXT_pipeline_library_group_handles](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_pipeline_library_group_handles.html)
 - [x] Conformance tests released:
 - [x] SDK released:

     - [x] Validation layer:

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by Tony-LunarG** [comment]
Validation complete at https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5202
