### ISSUE TITLE
Does the implementation free to return different alignments of similar buffers?

### ISSUE THREAD

**Issue by psionic12** [KhronosGroup/Vulkan-Docs#2045]
For example, a user creates a lot of buffers, all these buffers are created from the same `VkBufferCreateInfo`, except that the sizes are different. In this case, as an implementation:

1. Do I free to return different memoryTypeBits?
2. Do I free to return different alignments?

I check the doc for a while, but it seems that the doc doesn't talk about this. Sorry if I missed anything.

**Comment by spencer-lunarg** [comment]
> The implementation guarantees certain properties about the memory requirements returned by vkGetBufferMemoryRequirements2, vkGetImageMemoryRequirements2, vkGetDeviceBufferMemoryRequirements, vkGetDeviceImageMemoryRequirements, vkGetBufferMemoryRequirements and vkGetImageMemoryRequirements:

has a section that lists all the things that an implementation must return related to `memoryTypeBits` and `alignments`

**Comment by psionic12** [comment]
Thanks, I found it:

> The alignment member is identical for all VkBuffer objects created with the same combination of values for the usage and flags members in the [VkBufferCreateInfo](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VkBufferCreateInfo) structure passed to [vkCreateBuffer](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#vkCreateBuffer).
