### ISSUE TITLE
Specification Version does not match Release Version

### ISSUE THREAD

**Issue by FatalSleep** [KhronosGroup/Vulkan-Docs#2046]
Release Task List

Title of issue:  Specification Version does not Match Vulkan Release Version

The task list for the  release is:

 - [ ] Vulkan Specification: 1.3.24.0 [VK_EXT_extended_dynamic_state3](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap54.html#VK_EXT_extended_dynamic_state3)
 - [ ] Vulkan Implementation: 1.3.239.0

Latest release of Vulkan, v1.3.239 includes support for device extension `VK_EXT_extended_dynamic_state3` (along with several other features). However, the specification version does not match the Vulkan release version, which makes checking for availability of extensions between releases confusing.

**Comment by oddhack** [comment]
This extension was initially released in the 1.3.230 specification update. What are you referring to by "Vulkan Implementation" - an SDK release, or a specific vendor driver, or something else?

**Comment by FatalSleep** [comment]
> 

Right and this is the problem. If you google the spec and search you get v1.3.240.0 and this shows everywhere. It's misleading. The specification version should match the Vulkan release version.

Maybe its a minor issue, but imagine you're using a previous version of Vulkan and interested in using a new feature. You look up the feature in the spec book and you see the version is v1.3.240.0. The specification states that `dynamic state3` has been promoted to Vulkan 1.3. Which I am on Vulkan 1.3 (version 1.3.224.1), so I attempt to use the feature and it's unavailable. Then pull up the spec book, the only other indication is that the spec book is v1.3.240.0 and the latest release is 1.3.239.0, the assumption is then that the feature has been released in 1.3.240.0 (spec version) and that version of Vulkan hasn't released yet (latest 1.3.239.0).

**Comment by krOoze** [comment]
The equivalent version of the specification is included in the SDK manual at https://vulkan.lunarg.com/doc/sdk. Nevertheless, you still might want to otherwisely read the latest version anyway, because it includes bugfixes of the text.

**Comment by oddhack** [comment]
> Right and this is the problem. If you google the spec and search you get v1.3.240.0 and this shows everywhere. It's misleading. The specification version should match the Vulkan release version.
> 
> Maybe its a minor issue, but imagine you're using a previous version of Vulkan and interested in using a new feature. You look up the feature in the spec book and you see the version is v1.3.240.0.

It sounds like you're reading something into the spec revision number that isn't there. The '1.3' part means it describes what's in Vulkan 1.3. The 'with all registered Vulkan extensions' in the title means that this build of the document includes all the extensions we know about. The '.240' [patch version](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap44.html#_patch_versions) number [indicates bug fixes, clarifications, and language improvements have been incorporated into the specification](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap44.html#extendingvulkan-coreversions-versionnumbers) and doesn't tell you anything about what extensions are supported.

> The specification states that `dynamic state3` has been promoted to Vulkan 1.3.

I don't think the spec states this; if it does, please point to the specific language so we can fix 
 it. EXT_eds3 is not part of Vulkan 1.3 core, and it can in principle be supported with any core Vulkan API version all the way back to Vulkan 1.0. That is a choice driver implementations make, and apps always need to check if the extensions they want to use are actually supported.

**Comment by oddhack** [comment]
@FatalSleep can this issue be closed? The meaning of the spec revision numbers should hopefully be more clear now, and I don't see an action that should be taken with the specification.

**Comment by oddhack** [comment]
Closing this per earlier comments.
