### ISSUE TITLE
Clarify VK_PIPELINE_STAGE*_COLOR_ATTACHMENT_OUTPUT_BIT

### ISSUE THREAD

**Issue by martty** [KhronosGroup/Vulkan-Docs#2047]
The spec says:
> VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT specifies the stage of the pipeline after blending where the final color values are output from the pipeline.

yet when we consult VK_ACCESS_2_COLOR_ATTACHMENT_READ_BIT, we see
> VK_ACCESS_2_COLOR_ATTACHMENT_READ_BIT specifies read access to a color attachment, such as via blending, logic operations, or via certain subpass load operations. Such access occurs in the VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT pipeline stage.

I think this suggests that the COLOR_ATTACHMENT_OUTPUT stage *is* the stage where blending (and logic operations) are performed, and not after. Could you please clarify this?

**Comment by TomOlson** [comment]
@martty thanks - the first set of language you quote is incomplete at best, and "after" is misleading/wrong. Quite a bit happens in COLOR_ATTACHMENT_OUTPUT including blending and logic op. Fix under discussion, should not take long.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.243 spec update.
