### ISSUE TITLE
Leaving `VkPipelineRenderingCreateInfo` out of the `pNext` chain of `VkGraphicsPipelineCreateInfo` does not trigger a warning

### ISSUE THREAD

**Issue by NotAPenguin0** [KhronosGroup/Vulkan-Docs#2056]
When using `VK_KHR_dynamic_rendering`, `VkPipelineRenderingCreateInfo` can be added to the `pNext` chain of `VkGraphicsPipelineCreateInfo` to fill in attachment formats. The spec says (from https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPipelineRenderingCreateInfoKHR.html): 

> If this structure is not specified, and the pipeline does not include a [VkRenderPass](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkRenderPass.html), viewMask and colorAttachmentCount are 0, and depthAttachmentFormat and stencilAttachmentFormat are VK_FORMAT_UNDEFINED.

While adding this structure is technically optional, omitting it is generally not the desired behaviour and can lead to obscure bugs. In my instance the rendering would work fine, except blending wouldn't work as expected. 

It would probably be good if this triggered a validation layer warning, possibly only if the render pass started actually has attachments added to it.

**Comment by spencer-lunarg** [comment]
As @HansKristian-Work pointed out, this was discussed and the working group agrees this is not "invalid" but I created a tracker to get this added to the Best Practice layers https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5292 

Closing this as it is not a spec issue now
