### ISSUE TITLE
vk_format_utils.h & vk_enum_string_helper.h

### ISSUE THREAD

**Issue by juan-lunarg** [KhronosGroup/Vulkan-Docs#2059]
Currently there is a re-occurring problem with the `Vulkan Validation Layers` impacting the Vulkan Ecosystem.

That problem is `VkLayer_utils`

`VkLayer_utils` is an unofficial deliverable of `Vulkan Validation Layers`
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/2a8826a149c79e2b02e63ecd281e23af83f02dbc/layers/CMakeLists.txt#L17

The only intended deliverable of the `Vulkan Validation Layers` is the `dll`/`so`/`dylib` and the accompanying `json` file.

`VkLayer_utils` is a static library, that is largely a build artifact introduced due to historical reasons.

However, it has useful header files that people want to use.

We have had multiple issues about this in vvl:
- https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3233
- https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5289
- https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5073
- https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4872
- https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/562
- etc.

Currently list of files from `VkLayerUtils` which would be better served living in Vulkan-Headers:
```
generated/vk_format_utils.h
generated/vk_enum_string_helper.h
```

EX:

We could add `vk_enum_string_helper.h` to `Vulkan-Headers` and actually make it C compliant since Vulkan is a C API.

EDIT:

I've narrowed down the scope of this issue to 2 main header files. While there are other minor issues. These are the 2 most prominent ones affecting users of the SDK.

**Comment by oddhack** [comment]
Is there an action regarding this for the spec repo? I don't think any of those files are sourced from here.

**Comment by juan-lunarg** [comment]
Note: I've edited the list down to 3 files.

I think these 3 files can better live in Vulkan-Headers instead of Vulkan-Validation-Layers.

**Comment by juan-lunarg** [comment]
I've narrowed down the scope of this issue to 2 main header files. While there are other minor issues. These are the 2 most prominent ones affecting users of the SDK.

**Comment by krOoze** [comment]
@oddhack Well, this repo is the source of the `vk.xml`, from which string helpers should be generated from. One could argue it belongs here more than to some layer repo.

**Comment by juan-lunarg** [comment]
Essentially both of these files are just helper files for the meta data enums provide.

vk_enum_string_helper.h helps turns enums into strings. Which is good for logging, tools, etc.

vk_format_utils.h helps given very useful metadata about the enums.

EX: bool FormatIsUNORM(VkFormat format);

This is good for application developers, driver developers, and the entire vulkan ecosystem. As correctly brought up by @tomilov.

**Comment by oddhack** [comment]
Maybe there should be a Vulkan-Utils repo for such things. I'm not eager to adopt this in the spec repository because it's not the useful utility repository, and someone would need to own it and the underlying generator code. Also ISTM that it is most useful to package this in the SDK in some fashion rather than just have some C code online somewhere - no matter where the generator script lives, VVL or otherwise.

Another possibility is to have the generator script live in the Vulkan-Headers repo and create the helper code from that in CI.

**Comment by juan-lunarg** [comment]
Closing since vk_format_utils.h isn't a standalone header file (has a corresponding cpp file) so moving this to vulkan-headers isn't going to work. cc @christophe-lunarg 

Furthermore the vk_enum_string_helper.h has a more dedicated/concise issue on the gitlab.

**Comment by juan-lunarg** [comment]
https://github.com/KhronosGroup/Vulkan-Utility-Libraries

**Comment by krOoze** [comment]
Yet another utils repo? 🤔
