### ISSUE TITLE
Clicking on VK_REMAINING_3D_SLICES_EXT produces 404

### ISSUE THREAD

**Issue by juan-lunarg** [KhronosGroup/Vulkan-Docs#2063]
![image](https://user-images.githubusercontent.com/114601453/220199126-10d14870-90a3-4ea4-a576-d0a35eab300b.png)

@zmike clicking on VK_REMAINING_3D_SLICES_EXT creates a 404:
https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_REMAINING_3D_SLICES_EXT.html

**Comment by oddhack** [comment]
Thanks. This will be fixed in the next spec update.

**Comment by oddhack** [comment]
This wasn't signed off in time for the spec update I put out earlier today but should go out this week.

**Comment by oddhack** [comment]
This is fixed in the 1.3.243 spec update.
