### ISSUE TITLE
VK_DEFINE_HANDLE fails MSVC compilation when used to redeclare a handle

### ISSUE THREAD

**Issue by amaiorano** [KhronosGroup/Vulkan-Docs#2067]
`VK_DEFINE_HANDLE` was [recently updated](https://github.com/KhronosGroup/Vulkan-Headers/commit/bd6443d28f2ebecedfb839b52d612011ba623d14) so that instead of:

```
#define VK_DEFINE_HANDLE(object) typedef struct object##_T* object;
```

It is now:
```
#define VK_DEFINE_HANDLE(object) typedef struct object##_T* (object);
```

Unfortunately, under MSVC, when using `VK_DEFINE_HANDLE` to redeclare the same handle type (e.g. to forward-declare the type in a header), MSVC fails to compile. For example:

```
VK_DEFINE_HANDLE(VmaAllocator)
VK_DEFINE_HANDLE(VmaAllocator)
```

MSVC fails to compile with `error C2059: syntax error: '<parameter-list>'`. 

I put together [this Compiler Explorer example](https://godbolt.org/z/6vrTzeEsf) that demonstrates the error.

I work at Google, and ANGLE uses this forward-declaration strategy to manage dependencies by [forward-declaring the types in the header]((https://source.chromium.org/chromium/chromium/src/+/main:third_party/angle/src/libANGLE/renderer/vulkan/vk_mem_alloc_wrapper.h;l=15-19?q=vk_mem_alloc_wrapper.h&ss=chromium)), and then [effectively including vulkan_core.h](https://source.chromium.org/chromium/chromium/src/+/main:third_party/angle/src/libANGLE/renderer/vulkan/vk_mem_alloc_wrapper.cpp;l=12) in the cpp file.

This seems to be a bug with how MSVC handles re-declaration of typedef'd pointers when wrapping the typedef name in parentheses. I will likely open a MSVC bug for this. However, in the meantime, I'm wondering why this change was made? Does adding the parenthesis to the typedef name fix another problem?

Furthermore, I wonder if, as a workaround, VK_DEFINE_HANDLE could be conditionally compiled for C++ codebases to use `using` instead of `typedef`, so something like:

```
#ifdef __cplusplus
#define VK_DEFINE_HANDLE(object) using object = struct object##_T*;
#else
#define VK_DEFINE_HANDLE(object) typedef struct object##_T* object;
#endif
```

**Comment by oddhack** [comment]
We did it to share the definition with Vulkan SC, which I believe does this because it's a MISRA-C requirement. Probably the simplest thing to do is restore the old behavior when building the Vulkan headers, which is straightforward. @dgkoch could you comment on this for SC?

**Comment by dgkoch** [comment]
The specific Mirsa rule was: 
    - add parenthesis around macro parameters (for VK_DEFINE_*HANDLE) (Rule 20.7)

**Comment by amaiorano** [comment]
FYI, I [opened this MSVC bug](https://developercommunity.visualstudio.com/t/Redeclaration-of-typedef-pointer-to-stru/10288006).

**Comment by oddhack** [comment]
Thanks. BTW, is it possible to point the Compiler Explorer site at an external URL containing the Vulkan headers? Possibly we could use it in CI since there's no way for us to validate changes like this against every compiler someone uses.

Since this sounds urgent, we intend to revert the macro to the previous behavior for Vulkan headers and provide the alternate definition along an SC-only path, hopefully by tomorrow.

**Comment by amaiorano** [comment]
> Thanks. BTW, is it possible to point the Compiler Explorer site at an external URL containing the Vulkan headers? Possibly we could use it in CI since there's no way for us to validate changes like this against every compiler someone uses (edit: without some such tool).

It should be possible to add Vulkan-Headers to Compiler Explorer. For a given compiler, you can select libraries via the Libraries button:
![image](https://user-images.githubusercontent.com/6893883/220668146-6c11c89b-2b2e-4ae4-ac84-6d0c4f04c0de.png)

AFAICT, the list of libraries needs to be added to the official GitHub repo for it to appear on the official Compiler Explorer, like [this one for PEGTL](https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/c%2B%2B.amazon.properties#L3014).

Having said that, I'm not sure if Compiler Explorer can be used to validate builds in CIs. I don't see anything against doing so in the LICENSE or usage information, but it's something to validate.

> Since this sounds urgent, we intend to revert the macro to the previous behavior for Vulkan headers and provide the alternate definition along an SC-only path, hopefully by tomorrow.

Thanks, that would be greatly appreciated!

**Comment by oddhack** [comment]
BTW, is this happening with MSVC compiling in C mode, C++ mode, or both?

**Comment by oddhack** [comment]
@amaiorano can you try the generated vulkan_core.h uploaded in https://github.com/KhronosGroup/Vulkan-Docs/pull/2068#issuecomment-1441273380 and comment on that PR?

**Comment by amaiorano** [comment]
> BTW, is this happening with MSVC compiling in C mode, C++ mode, or both?

C++. Not sure about C, haven't tested that.

> @amaiorano can you try the generated vulkan_core.h uploaded in https://github.com/KhronosGroup/Vulkan-Docs/pull/2068#issuecomment-1441273380 and comment on that PR?

Will do!

**Comment by oddhack** [comment]
Vulkan-Headers has been updated with this change.
