### ISSUE TITLE
Clarification: How does enum `offset` value calculation work?

### ISSUE THREAD

**Issue by Lokathor** [KhronosGroup/Vulkan-Docs#2069]
Under [tag:require](https://github.com/KhronosGroup/Vulkan-Docs/blob/main/registry.adoc#contents-of-tagrequire-and-tagremove-tags), an enum tag can have `attr:offset` to declare the value. The registry docs say:

> The actual numeric value of the enumerant is computed as defined in the “Layers and Extensions” appendix of the Vulkan Specification.

However, when I go to [Appendix E: Layers & Extensions (Informative)](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#extensions) of the spec it doesn't seem to give a formula.

Given the actual values listed in the generated docs, such as for [VkResult](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkResult.html), it seems to be something like
```
1000000000 + (ext_num-1)*1000 + offset
```
and possibly negative if `dir` is negative.

But I'd like to be more sure than just a guess.

**Comment by oddhack** [comment]
Thanks for catching that. It was an old reference, and the description was moved to the Vulkan ["Style Guide"](https://registry.khronos.org/vulkan/specs/1.3/styleguide.html#_assigning_extension_token_values) a long time ago. #2071 fixes that along with some related citation issues.
