### ISSUE TITLE
Calculating the effective extent of a corner sample image

### ISSUE THREAD

**Issue by juan-lunarg** [KhronosGroup/Vulkan-Docs#2074]
[VK_NV_corner_sampled_image] @dgkoch

This line in the extension description is currently confusing me:

`Calculation of the next higher lod size goes according to ⌈dim / 2⌉ rather than ⌊dim / 2⌋`

dim/2 rather than dim/2 ?

I want to make sure I get this right for this PR in the vulkan validation layers where I calculate the effective extent and have to account for corner sampled images.

PR: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5403

**Comment by martty** [comment]
⌈dim / 2⌉ = ceil(dim / 2)
⌊dim / 2⌋ = floor(dim / 2)

**Comment by dgkoch** [comment]
Correct - that is the mathematical notation of ceiling vs floor.
