### ISSUE TITLE
VkSemaphore ERROR !!!!!!!

### ISSUE THREAD

**Issue by tigerssj** [KhronosGroup/Vulkan-Docs#2075]
Hi, guys.  in my program, Vulkan-ValidationLayers reported follow error:
[Error] Validation Error: [ UNASSIGNED-CoreValidation-DrawState-QueueForwardProgress ] Object 0: handle = 0x3e362800000001b7, name = cmd_main pass_F_0_T_0_notify_semaphore, type = VK_OBJECT_TYPE_SEMAPHORE; Object 1: handle = 0x1ecf72bb0c0, type = VK_OBJECT_TYPE_QUEUE; Object 2: handle = 0x1ecf72bb0c0, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0xe825f293 | vkQueueSubmit(): pSubmits[0].pSignalSemaphores[0] is signaling VkQueue 0x1ecf72bb0c0[] (VkSemaphore 0x3e362800000001b7[cmd_main pass_F_0_T_0_notify_semaphore]) that was previously signaled by VkQueue 0x1ecf72bb0c0[] but has not since been waited on by any queue.
j:\hsengine\trunk\engine\src\vulkanrender\tvulkanrender.cpp (6071): symbol: TVulkanRender::logv
j:\hsengine\trunk\engine\src\vulkanrender\tvkinstance.cpp (660): symbol: debug_callback_handler
j:\hsengine\trunk\engine\src\vulkanrender\tvkdebugmessage.cpp (58): symbol: TDebugMessenger::callback_handler_ext_debug_utils
F:\pr\Vulkan\build\Vulkan-ValidationLayers\layers\vk_layer_logging.cpp (199): symbol: debug_log_msg
F:\pr\Vulkan\build\Vulkan-ValidationLayers\layers\vk_layer_logging.cpp (436): symbol: LogMsg
F:\pr\Vulkan\build\Vulkan-ValidationLayers\layers\generated\chassis.h (4041): symbol: ValidationObject::LogError
F:\pr\Vulkan\build\Vulkan-ValidationLayers\layers\core_checks\synchronization_validation.cpp (175): symbol: SemaphoreSubmitState::ValidateSignalSemaphore
F:\pr\Vulkan\build\Vulkan-ValidationLayers\layers\core_checks\synchronization_validation.cpp (293): symbol: CoreChecks::ValidateSemaphoresForSubmit
F:\pr\Vulkan\build\Vulkan-ValidationLayers\layers\core_checks\queue_validation.cpp (163): symbol: CoreChecks::PreCallValidateQueueSubmit
F:\pr\Vulkan\build\Vulkan-ValidationLayers\layers\generated\chassis.cpp (1135): symbol: vulkan_layer_chassis::QueueSubmit
F:\pr\Vulkan\build\Vulkan-ValidationLayers\layers\generated\chassis.cpp (1135): symbol: vkDestroyDescriptorPool
j:\hsengine\trunk\engine\src\vulkanrender\tvkqueue.cpp (649): symbol: TVkQueue::submit
j:\hsengine\trunk\engine\src\vulkanrender\tvkqueue.cpp (713): symbol: TVkCmdCommitSystem::do_cmd_task
j:\hsengine\trunk\engine\src\vulkanrender\tvkqueue.cpp (766): symbol: TVkCmdCommitSystem::do_task
j:\hsengine\trunk\engine\src\vulkanrender\tvkqueue.cpp (918): symbol: TVkCmdCommitSystem::thread_run
j:\hsengine\trunk\engine\src\vulkanrender\tvkqueue.cpp (1560): symbol: do_commit_thread
j:\hsengine\trunk\engine\src\comment\tthreadwindow.cpp (327): symbol: TThread::start
j:\hsengine\trunk\engine\src\comment\tthreadwindow.cpp (166): symbol: TThread::TThreadHandle::threadFunc
j:\hsengine\trunk\engine\src\comment\tthreadwindow.cpp (166): symbol: BaseThreadInitThunk

My render engine cache max 3 frames.

in frame 0:
![image](https://user-images.githubusercontent.com/3362783/223905820-ce2c80bb-a012-484d-8024-b7335fb87850.png)
I create a VkSemaphore 0x3E362800000001B7 which used to notify present engine to start present swapchian image when gpu finished vkCommandBuffer(end_frame_0(0)_gpu_seg_1).

and the log message(vkFence): "gpu finished  graphics fence cmd: end_frame_0(0)_gpu_seg_1 to gpu, task count: [0] = 0" told me that the gpu has finished it.

in frame 3:
![image](https://user-images.githubusercontent.com/3362783/223906708-b9789ca9-1da0-4180-81ac-1983dcb62e7a.png)
I reuse the VkSemaphore 0x3E362800000001B7 by the same way,  however, Vulkan-ValidationLayers reports the error "UNASSIGNED-CoreValidation-DrawState-QueueForwardProgress".

WHY?

**Comment by oddhack** [comment]
@tigerssj we agree with the response above - programming questions are best directed to forums like the [Vulkan Discord](https://discord.com/channels/427551838099996672/1020038373198528512). This repo is about the specification itself. Please close the issue if you agree.

**Comment by oddhack** [comment]
Closing - as noted above, please use the Discord for programming questions.

**Comment by tigerssj** [comment]
ok
