### ISSUE TITLE
VK_EXT_headless_surface not supported now?

### ISSUE THREAD

**Issue by CuteLoong** [KhronosGroup/Vulkan-Docs#2085]
[VK_EXT_headless_surface] @chengtianww
*Here describe the issue or question you have about the VK_EXT_headless_surface extension*

Query vulkaninfo, there is no extension related to headless。
if I want to create a headless surface, what should I do?

My Vulkan version is 1.3.236, GPU: RTX4090,driver:530.30.02

**Comment by TomOlson** [comment]
@CuteLoong it is of course NVIDIA's decision whether to support the extension directly in their driver, but there is a Vulkan layer that implements VK_EXT_headless_surface in the MESA repository at https://gitlab.freedesktop.org/mesa/vulkan-wsi-layer/-/tree/master/wsi/headless. You could try that if you are comfortable building and installing layers. (See also https://gitlab.freedesktop.org/mesa/vulkan-wsi-layer.) The EXT_headless_surface implementation is tested regularly with the Arm Mali driver, and is meant to be GPU-agnostic, though we don't know whether anyone it is using it with the NVIDIA driver. Hope this helps!

**Comment by TomOlson** [comment]
Since that's all the information we have, we'll close this for now. Feel free to reopen if needed.
