### ISSUE TITLE
Odd layout of Chapter 19.

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#209]
Chapter 19 is called "Drawing Commands". It starts off talking about what drawing commands are made of, then makes a clunky segue into Section 19.1: "Primitive Topologies".

Under that section is the subsection 19.1.13: "Programmable Primitive Shading". While there is some relationship between shaders and topologies, this section isn't really about topologies. Indeed, it isn't *really* about even primitive shading.

It's really about drawing commands. 3 paragraphs into the section, it switches topics into the details of the behavior of Vulkan's actual drawing commands.

At the very least, subsection 19.1.13 shouldn't be listed under the "Primitive Topologies" section at all. It should be section 19.2. Also, it seems very strange that the section that details the drawing commands doesn't even have the word "draw" in the name.

Overall, the layout of the information in Chapter 19 is just.. odd. Really, I'd put all of 19.1.13 in front of 19.1. Especially since the description of the drawing commands don't actually talk much about primitive typologies.

**Comment by oddhack** [comment]
i agree 19.1.13 should move up a level. I think the description of primitive topologies follows on naturally enough from the topology member of VkPipelineInputAssemblyStateCreateInfo at the beginning of the chapter, though.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.13 spec update.
