### ISSUE TITLE
Request for clarification in `28.12.1. Basic Polygon Rasterization`

### ISSUE THREAD

**Issue by imrodriguezro** [KhronosGroup/Vulkan-Docs#2091]
Hi all,
In the section `28.12.1. Basic Polygon Rasterization`, the specification says 

> Special treatment is given to a sample whose sample location lies on a polygon edge. In such a case, if two polygons lie on either side of a common edge (with identical endpoints) on which a sample point lies, then exactly one of the polygons must result in a covered sample for that fragment during rasterization.

Can you please clarify whether:
1. `with identical points` means bitwise equal float positions? (as in `[-0.7604213 , -0.25456164]` not equal to `[-0.76042169, -0.25456066]` in normalized device coordinates)
2. `two polygons` can come from different drawing instances?

To give a bit more context, I'm getting holes on the shared edges of two polygons I'm rendering and I'm afraid that happens because of the points not being "identical".

Thank you in advance.

**Comment by imrodriguezro** [comment]
Thanks for your quick reply!

1. In order to rule out the difference in fixed-point rounding, I forced the vertex positions to be bitwise identical in my code. However, this didn't solve the problem :/. Does this point to a faulty driver? Or do you think I should take a look somewhere else?
2. In my code, the positions come from the same `VkPipeline`, just from difference instances as in `vkCmdDrawIndexed(6, 25)` (with 25 instances, two of them sharing an edge).

**Comment by HansKristian-Work** [comment]
> Does this point to a faulty driver? Or do you think I should take a look somewhere else?

Probably best to contact the IHV in question. Sounds buggy to me.

**Comment by imrodriguezro** [comment]
@HansKristian-Work I double-checked my tests and I was not setting correctly the vertices. After forcing them to be (finally) bitwise identical, the are no gaps between both polygons. I'm closing this ticket. Thank you.
