### ISSUE TITLE
Clarify when it is safe to release pointers used for deferred commands

### ISSUE THREAD

**Issue by Neo-Zhixing** [KhronosGroup/Vulkan-Docs#2092]
Section [35.1 Requesting Deferral](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap35.html#deferred-host-operations-requesting) says:

> Parameters to the command requesting a deferred operation may be accessed at any time until the deferred operation enters the pending state.

Does that imply that once the deferred operation enters the pending state, command parameters will no longer be accessed?

However, this is contradictory to what goes next:

> While a deferred operation is pending:
> - Externally synchronized parameters must not be accessed.
> - Pointer parameters must not be modified (e.g. reallocated/freed).
> - The contents of pointer parameters which may be read by the command must not be modified.
> - The contents of pointer parameters which may be written by the command must not be read.
> - Vulkan object parameters must not be passed as externally synchronized parameters to any other command.

So please clarify when is it safe to release command parameter pointers - right after calling the command, or until the deferred operation is complete?

**Comment by krOoze** [comment]
Does not seem contradictory; it seems complementary. You can't access it before it is pending AND you can't access it while it is pending.

**Comment by Neo-Zhixing** [comment]
> The deferred operation becomes pending when an operation has been successfully deferred with that deferred operation object.

So basically when you submit a command that uses the deferred operation, it immediately becomes pending when the command returns (as long as the deferral is successful). The lifetime between its submission to when it becomes pending therefore matches the lifetime of the function call. Stating that "You can't access it before it's pending" seems redundant, because this is the case for any function call - of course you can't access function arguments before the function returns!

For a normal English reader, this sentence must therefore imply "it's ok to modify the content after it becomes pending" or else it conveys no meaning at all.

If we change this sentence into "until the deferred operation enters the **complete** state" this sentence would make sense and it will also match drivers behavior in the real world. So please clarify - is this an error in the specification?

**Comment by krOoze** [comment]
> "You can't access it before it's pending" seems redundant, because this is the case for any function call

True. It is human nature though to repeat oneself for redundancy, and tough habit to break when writing a specification. I remember Bjarne Stroustrup talking on that point reminiscing on pre-ISO c++.

Anyway, point being, sometimes it gonna sneak in. Maybe the author had an urge to emphasize that restriction still applies. Seems the author thought that by the nature of the deferring, the driver does not have a reason to access it, so it bears reiterating that indeed the driver does reserve the right to access it.

> For a normal English reader,

"normal English reader" should not read a specification. In any specification one should not make leaps to conclusions that are not explicitly written down. If a specification describes behavior in some condition, one should not assume anything about the complement of that condition.

Yes, colloquially you can say "If it rains, I will stay inside.", implying if it doesn't rain you intended to go outside. But in technical English you never make this assumption.

> If we change this sentence into "until the deferred operation enters the complete state" this sentence would make sense and it will also match drivers behavior in the real world.

The two guarantees seem to differ a bit. At least the deferred variant of the guarantee goes in much more detail, differentiating between reading and modifying commands.

>  is this an error in the specification

Well, we will see what official people will say on the matter. But seems esthetical at best to me, therefore not an "error".

**Comment by r-potter** [comment]
@dgkoch Somewhat related to #2100, which we just assigned to RT TSG

**Comment by JoshuaBarczak-Intel** [comment]
> So please clarify when is it safe to release command parameter pointers - right after calling the command, or until the deferred operation is complete?

It should be after completion

> Parameters to the command requesting a deferred operation may be accessed at any time until the deferred operation enters the pending state.

I suspect that we meant to write: "accessed **by the implementation** until the deferred op enters the **completed** state."  We'll take an AR to clean this up.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.248 spec update.
