### ISSUE TITLE
What is the state to allow using timeline semephore in swapchain extensions?

### ISSUE THREAD

**Issue by psionic12** [KhronosGroup/Vulkan-Docs#2095]
It is a little weird to me that timeline semaphore cannot be using in swapchain extensions is defined at a standard level, which is not the same as other new features. When coming to normal new features, the standard just defines new APIs as extensions to let the vendor choose whether to implement it or not. 

So my questions are: 
1. Why in this case, Vulkan don't define an extension to let timeline semaphore be used in swapchain extensions?
2. Does Vulkan standard intend to allow this? If yes, what's the progress?
3. What's the reason it is hard to implement? Does it somehow relate than to present queue, the semaphore to be host synchronized? (This is also confused to me, which means `VkPresentQuene` need to write to semaphore, while any other place uses semaphores do not need it to be host synchronized)?

**Comment by cubanismo** [comment]
> What's the reason it is hard to implement

The main problem is the wait-before-signal semantics of timeline semaphores. Many windowing systems have presentation APIs with definitions based on the assumption that an image submitted for presentation will be ready to present in finite time, and/or require the use of synchronization primitives with similar properties. To define a general swapchain API that allows presentation to be blocked by synchronization primitives which do not yet have a corresponding signal submitted requires seeing how at least a few windowing systems will implement such a mechanism. So far I only know of one OS that allows this, and only on some of its presentation paths.

**Comment by psionic12** [comment]
Hi @cubanismo, do you know why a semaphore needs to be written when calling `vkQueuePresentKHR`? According to the doc of `vkQueuePresentKHR`:

> Host access to pPresentInfo->pWaitSemaphores[] must be externally synchronized

This looks to me that when calling `vkQueuePresentKHR` needs to modify the semaphore on the CPU side, so it needs to be synchronized. In my mind a semaphore is just a handle of something inside the GPU, you can't even get the state of a semaphore, this synchronization safety statement in the doc confused me a little, and it's a little difficult to write some read/write safe API wrappers without a lock (I'm writing a Vulkan wrapper for Rust).

**Comment by cubanismo** [comment]
A semaphore is roughly just a handle to something on the GPU, and waiting on them potentially manipulates internal state of that wrapper, so their use must be synchronized. For this function, that use is externally synchronized.
