### ISSUE TITLE
"GPU Upload Heaps" in Vulkan

### ISSUE THREAD

**Issue by ghost** [KhronosGroup/Vulkan-Docs#2096]

**Comment by SaschaWillems** [comment]
Vulkan already exposes those memory types. This has been available for quite some now.

**Comment by krOoze** [comment]
https://gpuopen.com/learn/vulkan-device-memory/

`VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT|VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT`
