### ISSUE TITLE
Object Lifetime chapter does not take deferring into account

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#2100]
This in Object Lifetime chapter:

> The ownership of application-owned memory is immediately acquired by any Vulkan command it is passed into. Ownership of such memory **must** be released back to the application at the end of the duration of the command, so that the application **can** alter or free this memory as soon as all the commands that acquired it have returned.

does not seem to take deferred commands into account, which I think are supposed to waive the memory releasing restriction on implementations. (And therefore application cannot free the memory this soon, despite what this claims.)

----
I am gonna piggyback this query in this Issue. In the Deferred chapter it says:

> The contents of pointer parameters which **may** be written by the command **must** not be read.

Not sure this should be in the spec. Or at least it should say "should" instead of "must". Unless I miss something it does not look like a conventional undefined behavior situation. If the application is curious, it technocally can read it (although getting a dirty value), and hell will not break loose, right?

**Comment by JoshuaBarczak-Intel** [comment]
> This in Object Lifetime chapter does not seem to take deferred commands into account, which I think are supposed to waive the memory releasing restriction on implementations. (And therefore application cannot free the memory this soon, despite what this claims.)

I agree this is an oversight.  

> Not sure this should be in the spec. Or at least it should say "should" instead of "must". 

While we're not aware of a situation where it would break, it's not a useful or safe thing for an app to do, so our preference is to disallow it outright unless a reasonable use case can be found.

**Comment by krOoze** [comment]
> it's not a useful or safe thing for an app to do, so our preference is to disallow it outright unless a reasonable use case can be found.

It's more of a matter of principle. In general, you should be specifying what Vulkan does\how it behaves, not police what the applications do in their own time. If I read restriction like this, I assume the driver would misbehave if it is not honored.

The distinction is important when I do not have complete control over the application. E.g. if I am making some kind of middleware (maybe for a browser where it must never crash). If it is "must not" I must somehow sanitize the access before passing it to Vulkan. But if it does not break the driver, I need not care and let it be the problem of the user whether he accesses it wrong.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.248 spec update.
