### ISSUE TITLE
[VK_EXT_graphics_pipeline_library] AMD Vulkan driver support

### ISSUE THREAD

**Issue by stanlu1013** [KhronosGroup/Vulkan-Docs#2106]
[VK_EXT_graphics_pipeline_library] @tobski
Will AMD vulkan driver support this extension in the future?
Thanks!

**Comment by Rua** [comment]
I think you'll have to ask AMD for that?

**Comment by stanlu1013** [comment]
ohh, sorry, thanks for both of you.
next time for vendor-specific feature, i will ask to their official community.
Thanks again.
