### ISSUE TITLE
Contradicting validation requirements on vkGetImageSubresourceLayout

### ISSUE THREAD

**Issue by haasn** [KhronosGroup/Vulkan-Docs#2109]
The spec says both:

[VUID-vkGetImageSubresourceLayout-format-04461](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap12.html#VUID-vkGetImageSubresourceLayout-format-0446):
>  If format is a color format, the aspectMask member of pSubresource must be VK_IMAGE_ASPECT_COLOR_BIT

and (respectively)

[VUID-vkGetImageSubresourceLayout-tiling-08717](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap12.html#VUID-vkGetImageSubresourceLayout-tiling-08717):
> If the tiling of the image is VK_IMAGE_TILING_LINEAR and has a [multi-planar image format](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap47.html#formats-requiring-sampler-ycbcr-conversion), then the aspectMask member of pSubresource must be a single valid [multi-planar aspect mask](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap47.html#formats-planes-image-aspect)

[VUID-vkGetImageSubresourceLayout-tiling-02271](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap12.html#VUID-vkGetImageSubresourceLayout-tiling-02271):
>  If the tiling of the image is VK_IMAGE_TILING_DRM_FORMAT_MODIFIER_EXT, then the aspectMask member of pSubresource must be VK_IMAGE_ASPECT_MEMORY_PLANE_i_BIT_EXT and the index i must be less than the VkDrmFormatModifierPropertiesEXT::drmFormatModifierPlaneCount associated with the image’s format and VkImageDrmFormatModifierPropertiesEXT::drmFormatModifier

So according to spec, when exporting a typical color image (e.g. R8G8B8A8) as a dmabuf (with drm format modifier), I should set `aspectMask` to both `VK_IMAGE_ASPECT_COLOR_BIT` *and* `VK_IMAGE_ASPECT_MEMORY_PLANE_0_BIT_EXT`?

It seems also that this is somehow a recent addition, at least to the validation layers, because I never hit this VUID in the past when I was developing my dmabuf export/import code.

**Comment by HansKristian-Work** [comment]
The first VU needs to be updated with "if not multi-planar or DRM"

**Comment by oddhack** [comment]
This should be fixed in the 1.3.250 spec update.
