### ISSUE TITLE
Document atexit handler installed by vkCreateInstance

### ISSUE THREAD

**Issue by msharov** [KhronosGroup/Vulkan-Docs#2110]
vkCreateInstance appears to install an atexit handler that modifies VkFence objects and thus requires them to be externally synchronized.

This atexit handler causes a problem if the app installs its own atexit handler for cleanup. The common C++ pattern of a singleton App object, cleaning up in its destructor, does this. If this App object also manages a thread that waits in vkWaitForFences, as recommended in #310 and described in #2107, and normally shuts it down in the destructor, then there will be a validation error if the thread is in vkWaitForFences at exit or a segfault if it is in vkGetFenceStatus.

To avoid the crash, the app must install an atexit handler to stop the waiter thread, or to call vkDeviceWaitIdle to the same effect. This handler must be installed after calling vkCreateInstance to be called before the one vkCreateInstance installs.

I'm not sure if this is just undocumented behavior, or if should not allowed by the spec and the driver should not be doing it. This is on Linux x86_64, NVidia 530.41.03.

Either way, the spec should explain in more detail what the handler is doing and its exact synchronization requirements.

**Comment by cubanismo** [comment]
I don't think there's anything to clarify or fix here. Vulkan requires a certain teardown sequence. Operating systems implement a certain teardown sequence. I believe the issue you're running into is that the driver library is loaded as part of vkCreateInstance(), and hence that's when that library's destructors are registered. I don't believe our driver actually uses atexit(), because that wouldn't catch situations like dlclose(), but it does clean up some global resources in __attribute__((destructor)) functions. Obviously you can't use a library once it is unloaded, and the order in which libraries are unloaded/destructed at process teardown is beyond the scope of Vulkan, so it's up to the app to devise a method to exit cleanly considering the native OS behavior and vulkan's requirements. It could be this means that atexit() or process teardown handlers are not an appropriate place to clean up your threads that use Vulkan. There are other options for this than those you're enumerating above.

**Comment by msharov** [comment]
If that were true, and the library was unloaded before atexit handlers run, or in one of them, then all Vulkan functions would have stopped working after that. Once I install a cleanup atexit after vkCreateInstance, everything destructs properly, with no errors. The validation layers still work in the App destructor; I still got validation errors from thread cancellation when the device was destroyed.

Secondly, you can't just say that Vulkan can not be used in an atexit handler. Error handling and cleanup must happen somehow. Do you expect the application to just dump core and crash on every error, without even trying to cleanup Vulkan objects? I don't think I'm the only one to consider this unacceptable. So what are those other options for this that you mentioned?

**Comment by cubanismo** [comment]
I didn't say you necessarily can't use Vulkan in an atexit() handler. I said it's outside the scope of Vulkan to define the order of teardown handling at the system level. As I say, our driver isn't using atexit(). I don't see any calls to it in the loader source, so I took a guess that you were referring to library destructors instead. If that's not the case, I don't know what the specific issue is, but again, Vulkan can only:

1) Lay out its valid usage
2) Behave correctly when that valid usage is obeyed.

atexit() is not the only way to handle cleanup in an application. If its semantics on a given system fit within Vulkan valid usage, great. If not, it can't be used.

**Comment by msharov** [comment]
> As I say, our driver isn't using atexit(). I don't see any calls to
> it in the loader source, so I took a guess that you were referring
> to library destructors instead.

I am not referring to anything other than the problem as I observe it. When the application is exiting, after main() exits and before the App object destructor is executed, something happens that breaks the active VkFence being waited on. I don't know how to list atexit handlers, or how to trace into them without debugging information on the vulkan library, so I am making my best guess at what's happening. atexit() handlers are the only code that should be executing during the interval in question. Since none of my code is destroying the offending VkFence, it must be Vulkan internals that are doing it. I have no other explanation.

> If that's not the case, I don't know
> what the specific issue is, but again, Vulkan can only:
> 
> 1. Lay out its valid usage

That's precisely what I am asking for here. What is the valid usage of Vulkan objects during the time when atexit handlers are being executed?

> 2. Behave correctly when that valid usage is obeyed.

My code as currently written does not deviate from valid usage. It is valid to wait in vkWaitForFences or to call vkGetFenceStatus on an existing fence that is about to be set by a queue submission. Instead of behaving correctly, Vulkan crashes. Therefore, either the spec is incomplete, or the Vulkan driver has a bug in it. Which is it?

> atexit() is not the only way to handle cleanup in an application.

atexit() *is* the only way to handle cleanup in an application. You can also use dtor sections, which is what you get when using global objects, but in practice that gives the same result as atexit other than being setup at link time, so that will not solve the vkGetFenceStatus crash.

**Comment by msharov** [comment]
I discovered another curious side effect of the mysterious atexit handler. If I create the pipeline before creating the swapchain, then there occurs a pause of several seconds during vkDestroyInstance. The window remains visible during the pause. If I install an atexit handler to wait_idle and destroy the swapchain, then there is no pause.

I tried breaking into the debugger during the pause with inconclusive results. The debugger is unresponsive to ^C for a random amount of time, after which it sometimes breaks on poll from xcb_flush called from the nvidia driver. Another time I broke into something unknown under dlclose.

The standard does not say that the swapchain must be created first, and since it does not refer to the pipeline at all, it is difficult to understand what is going on.

Again, not complaining, just reporting weird behavior.

**Comment by ShabbyX** [comment]
Is anything else in the UI responsive during the "several seconds"? On Nvidia/X11 at least, I always notice a few seconds of system freeze when there's a device loss until the system recovers. It could be that some bug (likely in your own software) is causing a driver crash

**Comment by msharov** [comment]
Yes. I can switch back to the terminal from the app. It is only the debugger that is not responding to ^c. The driver, or at least the part that is linked into my process, does not crash, and will exit normally. If there is a bug, it is not reported by the validation layers. It is also difficult to imagine what kind of a bug could be triggered simply by reordering pipeline and swapchain creation.

**Comment by krOoze** [comment]
Drivers have no legitimate reason to use `atexit`, so I don't think there's anything to document here. If they want any static cleanup, they should use `DllMain` resp `__attribute__((destructor))`, I think.

Blame order starts with the application, so I think it is a case for a minimal complete example\repro. And then sending it to the appropriate driver vendor if no errors are discovered.

**Comment by msharov** [comment]
I generally agree that a minimal complete example is a good idea, but with Vulkan, the prospect of making one horrifies me. My project started with vulkan-tutorial.com, which is 1500 lines plus a boatload of dependencies, rewriting it into a more general UI framework. After quite a few months of work I have over 5000 lines of code with maybe double that of relevant code in supporting libraries. I have no idea how long it would take me to condense this into a standalone simple testcase. I guess I'll try sometime, but if you really want to require one, you may as well just give up and close this issue as norepro.

**Comment by versalinyaa** [comment]
Without a steps to reproduce nor a detailed analysis with logs and backtraces, there is no further action we can take here. And the fundamental premise of this issue, `atexit()` handlers in the Vulkan stacks, is contradicted by James in https://github.com/KhronosGroup/Vulkan-Docs/issues/2110#issuecomment-1517018104 because he found no usage of `atexit()` in his Nvidia driver nor the Vulkan loader.

Regardless of reproducibility, the specification of driver internals lies far outside the scope of the Vulkan spec. The exact method that the driver uses for teardown will always remain an undocumented driver detail.

@msharov If you are able to provide to provide a testcase that reproduces the bug, and can supply supporting evidence that the bug is located in the Vulkan driver or loader, or a Khronos-provided layer, then please re-open this issue.

**Comment by msharov** [comment]
I have encountered a curious valgrind error that appears related to this problem. I have been running without atexit cleanup for a while, and there have been no crashes. Sometimes, however, I see the following valgrind error during exit:
```
Invalid read of size 1
   at 0x108EB95F: findIdx<long unsigned int> (robin_hood.h:1426)
   by 0x108EB95F: find (robin_hood.h:1973)
   by 0x108EB95F: vl_concurrent_unordered_map<unsigned long, unsigned long, 4, HashedUint64>::pop(unsigned long const&) (vk_layer_utils.h:710)
   by 0x108CB96A: DispatchDestroySemaphore(VkDevice_T*, VkSemaphore_T*, VkAllocationCallbacks const*) (layer_chassis_dispatch.cpp:822)
   by 0x107A148E: vulkan_layer_chassis::DestroySemaphore(VkDevice_T*, VkSemaphore_T*, VkAllocationCallbacks const*) (chassis.cpp:1871)
   by 0x1C2CFD: vk::Device::Semaphore::destroy() (device.cc:656)
   by 0x1BDF59: vk::Device::Semaphore::~Semaphore() (device.h:138)
   by 0x1C4931: void std::destroy_at<vk::Device::Semaphore>(vk::Device::Semaphore*) (cxxabi.h:144)
   by 0x1C43B5: void std::destroy<vk::Device::Semaphore*>(vk::Device::Semaphore*, vk::Device::Semaphore*) (cxxabi.h:152)
   by 0x1C4117: std::array<vk::Device::Semaphore>::destroy_all() (array.h:29)
   by 0x1C32ED: std::array<vk::Device::Semaphore>::~array() (array.h:41)
   by 0x1BE951: vk::Device::~Device() (device.cc:35)
   by 0x19C6DA: VApp::~VApp() (app.cc:53)
   by 0x5117FA0: __run_exit_handlers (exit.c:108)
 Address 0x124c52c2 is 914 bytes inside a block of size 977 free'd
   at 0x48458CF: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x1083E51C: destroy (robin_hood.h:2479)
   by 0x1083E51C: destroy (robin_hood.h:2464)
   by 0x1083E51C: ~Table (robin_hood.h:1705)
   by 0x1083E51C: vl_concurrent_unordered_map<unsigned long, unsigned long, 4, HashedUint64>::~vl_concurrent_unordered_map() (vk_layer_utils.h:634)
   by 0x5117FA0: __run_exit_handlers (exit.c:108)
   by 0x511806D: exit (exit.c:138)
   by 0x50FEC8E: (below main) (libc_start_call_main.h:74)
 Block was alloc'd at
   at 0x4842788: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x108EBE39: initData (robin_hood.h:2330)
   by 0x108EBE39: robin_hood::detail::Table<true, 80ul, unsigned long, unsigned long, HashedUint64, std::equal_to<unsigned long> >::rehashPowerOfTwo(unsi
   by 0x108EC4B3: increase_size (robin_hood.h:2453)
   by 0x108EC4B3: std::pair<unsigned long, robin_hood::detail::Table<true, 80ul, unsigned long, unsigned long, HashedUint64, std::equal_to<unsigned long>
   by 0x108EC681: operator[]<> (robin_hood.h:1731)
   by 0x108EC681: void vl_concurrent_unordered_map<unsigned long, unsigned long, 4, HashedUint64>::insert_or_assign<unsigned long>(unsigned long const&,
   by 0x108F1FC7: WrapNew<VkDescriptorSet_T*> (chassis.h:2441)
   by 0x108F1FC7: DispatchAllocateDescriptorSets(VkDevice_T*, VkDescriptorSetAllocateInfo const*, VkDescriptorSet_T**) (layer_chassis_dispatch_manual.cpp
   by 0x10797D21: vulkan_layer_chassis::AllocateDescriptorSets(VkDevice_T*, VkDescriptorSetAllocateInfo const*, VkDescriptorSet_T**) (chassis.cpp:943)
   by 0x1C537D: vk::DescriptorSetLayout::Pool::allocate_set(vk::DescriptorSetLayout const&, VkDescriptorSet_T**) (dslayout.cc:79)
   by 0x1C5B6C: vk::DescriptorSetLayout::allocate_set(VkDescriptorSet_T**, vk::DescriptorSetLayout::Pool**) (dslayout.cc:147)
   by 0x1B7C99: vk::DescriptorSet::create(vk::Resources&, std::string_view const&, vk::DescriptorSetLayout&) (descset.cc:19)
   by 0x1A40AB: vk::CommandBuffer::create_descriptor_set(vk::DescriptorSetLayout&) (cbuf.cc:90)
   by 0x1B3812: vk::CommandWriter::prepare_for_draw() (cw.cc:1305)
   by 0x1B3CFB: vk::CommandWriter::Draw_draw(unsigned int, unsigned int, unsigned int, unsigned int) (cw.cc:1343)
```
There are numerous additional errors like it, for the various semaphores that are still alive in the App destructor. For example:
```
Invalid read of size 8
   at 0x108EB9CD: vl_concurrent_unordered_map<unsigned long, unsigned long, 4, HashedUint64>::pop(unsigned long const&) (vk_layer_utils.h:714)
   by 0x108CB96A: DispatchDestroySemaphore(VkDevice_T*, VkSemaphore_T*, VkAllocationCallbacks const*) (layer_chassis_dispatch.cpp:822)
...(the rest is the same as the first error)

Invalid read of size 1
   at 0x108EB9D1: shiftDown (robin_hood.h:1403)
   by 0x108EB9D1: erase (robin_hood.h:2038)
   by 0x108EB9D1: vl_concurrent_unordered_map<unsigned long, unsigned long, 4, HashedUint64>::pop(unsigned long const&) (vk_layer_utils.h:715)

Invalid write of size 1
   at 0x108EBA45: shiftDown (robin_hood.h:1410)
   by 0x108EBA45: erase (robin_hood.h:2038)
   by 0x108EBA45: vl_concurrent_unordered_map<unsigned long, unsigned long, 4, HashedUint64>::pop(unsigned long const&) (vk_layer_utils.h:715)
   by 0x108F4F42: DispatchDestroyCommandPool(VkDevice_T*, VkCommandPool_T*, VkAllocationCallbacks const*) (layer_chassis_dispatch_manual.cpp:1240)

Invalid write of size 1
   at 0x108EBA45: shiftDown (robin_hood.h:1410)
   by 0x108EBA45: erase (robin_hood.h:2038)
   by 0x108EBA45: vl_concurrent_unordered_map<unsigned long, unsigned long, 4, HashedUint64>::pop(unsigned long const&) (vk_layer_utils.h:715)
   by 0x108DF45A: DispatchDestroyDebugUtilsMessengerEXT(VkInstance_T*, VkDebugUtilsMessengerEXT_T*, VkAllocationCallbacks const*) (layer_chassis_dispatch
```
In every case, I am seeing what appears to be a global destructor for a Table object that is run before my App destructor. I am loading validation layers, so this object might be coming from there. There is no robin_hood.h in the validation layers repository, but it is included in layers/containers/custom_containers.h.

I have not seen any crashes at exit, or at least, none that were logged. Nevertheless, I think I better restore the cleanup atexit. Just thought you might be interested.
