### ISSUE TITLE
Clarify the relationship between invocation group uniformity and subgroup uniformity

### ISSUE THREAD

**Issue by magcius** [KhronosGroup/Vulkan-Docs#2112]
I am limiting scope of this to draw calls for now -- compute dispatches have some extra spec language I have not fully taken the time to understand yet.

The basic question here is whether subgroups can contain invocations from multiple invocation groups. Or in more informal language,  whether wavefronts can straddle different draw calls.

The only text I can find in the Vulkan specification related to this can be found in the [Subgroup chapter](https://registry.khronos.org/vulkan/site/spec/latest/chapters/shaders.html#shaders-scope-subgroup):

> For [shaders that have defined workgroups](https://registry.khronos.org/vulkan/site/spec/latest/chapters/shaders.html#shaders-scope-workgroup), ...
>
> In other shader stages, each invocation in a subgroup must be in the same [device scope instance](https://registry.khronos.org/vulkan/site/spec/latest/chapters/shaders.html#shaders-scope-device).

This implies that drivers have the ability to fill subgroups with invocations not only between draw calls, but between render passes and even queues. While I find it extremely unlikely that they would exercise their power to do this, the spec does not appear to place any limits here from my reading of it.

However, the SPIR-V specification strongly suggests in a few places that the subgroup might be a subset of the invocation group. First, in the [Uniformity chapter](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#_uniformity):

> An \<id\> is defined to be [dynamically uniform](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#DynamicallyUniform) for a dynamic instance of an instruction if all invocations (in an invocation group) that execute the dynamic instance have the same value for that <id>.
> 
> While the names may suggest otherwise, nothing forbids an <id> from being decorated as both Uniform and NonUniform. **Because dynamically uniform is at a larger scope (invocation group) than the default Uniform scope (subgroup)**, it is even possible for the <id> to be uniform at the subgroup scope but not dynamically uniform.

"Larger scope", and the rest of the text implies that the subgroup is a subset of the invocation group here.

And viewing the NonUniform decoration with IHV-tinted glasses makes similar hints here. NonUniform is often used in the form of e.g. HLSL's NonUniformResourceIndex, where the idea here is that you're telling a compiler that a resource index might not be uniform across *both* the subgroup and the invocation group. If it does not have this assurance, the compiler might need to generate a loop through all of the resource indexes to perform loads/stores on each resource individually.

If vendors *can* pack draw calls across subgroups, then NonUniform does not quite help those vendors, because even if something is missing the NonUniform hint and is invocation group uniform, it might still not be subgroup uniform and would still need the loop. So, it can be assumed that since the hint was added for *some* reason, that it needs to provide some additional expressive power, e.g. implying that it should imply both non-dynamically uniform and non-subgroup uniform. Was this considered during the development of NonUniform at all?

If it is decided that subgroups *are* a subset of the invocation group, then we should clear up the Vulkan specification to make that extra clear.

If it is decided that subgroups *are not* a subset of the invocation group, then we should clear up the SPIR-V specification to remove the misleading language.

##

While it's not directly related in this case, there are cases of ISVs shipping code relying on subgroups being a subset of either the invocation group, or some further partition of the invocation group. e.g. in [this article](https://gpuopen.com/learn/porting-detroit-3/), AMD and Quantic Dream suggest using readFirstInvocationARB on the InstanceID to scalarize it across the warp.

Even if we decide subgroups are a subset of the invocation group, I still don't think this code would be correct, as I believe multiple instances are still considered part of the same invocation group *. But it still shows a danger here. ISVs rely on wave scalarization tricks to improve performance, and it would be nice to have some assurance about what tricks are valid going forward here.

It might be "obvious" to some that InstanceID is not subgroup uniform and can't be scalarized, but I don't think that's very well documented here. Is DrawID guaranteed to be subgroup uniform? Are uniforms variables guaranteed to be subgroup uniform? Are we willing to make any such statements about anything yet? Regardless of our answers here, I think documentation could be improved as well about which builtins, if any, are subgroup uniform.

## * Footnote on invocation group definition

This is more of an unrelated footnote, but while looking into this, I did find a confusing spec ambiguity in the [Command chapter](https://registry.khronos.org/vulkan/site/spec/latest/chapters/shaders.html#shaders-scope-command) of the specification. The text says:

> For indirect drawing commands with drawCount greater than one, invocations from separate draws are in separate command scope instances.
>
> For shaders without defined [workgroups](https://registry.khronos.org/vulkan/site/spec/latest/chapters/shaders.html#shaders-scope-workgroup), this set of invocations forms an invocation group as defined in the [SPIR-V specification](https://registry.khronos.org/vulkan/site/spec/latest/chapters/introduction.html#spirv-spec).

Carving out indirect multi-draw *only* (and not also, say, direct multi-draw) seemed a bit confusing as a single edge case and can easily be misread, but that's fine. But my question is whether the text "this set of invocations" refers to the invocations in a single command scope instance, or across all the command scope instances generated.

**Comment by jeremyong** [comment]
As an additional note, if it turns out IHVs are allowed to repack subgroups (e.g. ray trace reordering), it would be useful to know if resource uniformity semantics expressed w.r.t. subgroups would be forced to be relaxed as nonuniform resource access by the IHV. It seems as though so long as the semantic intent of any subgroup and resource access in shader code is honored, we are in OK territory but agree with Jasper that additional clarity would be appreciated.

**Comment by HansKristian-Work** [comment]
Made a public PR to clarify it and allow some public discussion on the issue.

**Comment by magcius** [comment]
Here's maybe a weird question: are there any cases "dynamically-uniform-but-not-subgroup-uniform" is an important concept?

For non-uniform resource access where vendors can avoid waterfall loops, I believe this requires both dynamic uniformity and subgroup uniformity. Dynamic uniformity alone isn't enough to skip the waterfall loop (and there are [https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/16709/](some public driver fixes) you can find about this).
