### ISSUE TITLE
`VUID-VkImageCreateInfo-format-00943` not displaying on website

### ISSUE THREAD

**Issue by juan-lunarg** [KhronosGroup/Vulkan-Docs#2113]
`VUID-VkImageCreateInfo-format-00943` isn't showing up:
https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkImageCreateInfo.html

**Comment by spencer-lunarg** [comment]
```
ifndef::VK_ANDROID_external_memory_android_hardware_buffer[]
  * [[VUID-VkImageCreateInfo-format-00943]]
    pname:format must: not be ename:VK_FORMAT_UNDEFINED
endif::VK_ANDROID_external_memory_android_hardware_buffer[]
```

can find it at https://registry.khronos.org/vulkan/specs/1.3/html/vkspec.html#VUID-VkImageCreateInfo-format-00943

**Comment by oddhack** [comment]
There's nothing to be done here, at least until the codified VU idea is accepted and lots of stuff is converted over. This is not the only VU in the spec which won't be rendered in the all-extensions build (from which the refpages are made). Suggest closing this.
