### ISSUE TITLE
Null micromap handle in `VkAccelerationStructureTrianglesOpacityMicromapEXT`?

### ISSUE THREAD

**Issue by Saancreed** [KhronosGroup/Vulkan-Docs#2114]
[`VUID-VkAccelerationStructureTrianglesOpacityMicromapEXT-micromap-parameter`](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkAccelerationStructureTrianglesOpacityMicromapEXT-micromap-parameter) states that `micromap` must be a valid `VkMicromapEXT` handle. However, the textual description of `VkAccelerationStructureTrianglesOpacityMicromapEXT` contains the following note:

> If `micromap` is `VK_NULL_HANDLE` then every value read from `indexBuffer` must be one of the values in `VkOpacityMicromapSpecialIndexEXT`.

This seemingly contradicts `VUID-VkAccelerationStructureTrianglesOpacityMicromapEXT-micromap-parameter` which forbids passing invalid (including null) handles in `micromap`. Should `VK_NULL_HANDLE` be actually allowed or is the note incorrect?

**Comment by oddhack** [comment]
This should be fixed in the 1.3.249 spec update.
