### ISSUE TITLE
`VUID-VkImageCreateInfo-imageType-00954`

### ISSUE THREAD

**Issue by juan-lunarg** [KhronosGroup/Vulkan-Docs#2117]
Currently `VUID-VkImageCreateInfo-imageType-00954` is 
> If imageType is VK_IMAGE_TYPE_2D and flags contains VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT, extent.width and extent.height must be equal and arrayLayers must be greater than or equal to 6

However the first half is redundant due to `VUID-VkImageCreateInfo-flags-00949`
> If flags contains VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT, imageType must be VK_IMAGE_TYPE_2D

So `VUID-VkImageCreateInfo-imageType-00954` can become
> If flags contain VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT, extent.width and extent.height must be equal and arrayLayers must be greater than or equal to 6

Furthermore this can be split up into 2 separate VUIDs:

> If flags contain VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT then extent.width and extent.height must be equal

> If flags contain VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT then arrayLayers must be greater than or equal to 6

This is beneficial to the validation layers. Since the validation layers reports the VUID to the user and it's nicer to have a more concise VUID explaining what the user did.

This makes the validation for `VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT` cleaner since it avoids an extra conditional check and provides a shorter error message to the user.

**Comment by juan-lunarg** [comment]
My thoughts for this issue came from working on this PR for the validation layers. Which may help with context.
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5761

**Comment by oddhack** [comment]
This should be fixed in the 1.3.250 spec update.
