### ISSUE TITLE
About VK_EXT_image_compression_control

### ISSUE THREAD

**Issue by chenyangchenyang** [KhronosGroup/Vulkan-Docs#2122]
[VK_EXT_image_compression_control] @janharaldfredriksen-arm

hi,
How to get all VkFormat(s) that is supported by VK_EXT_image_compression_control

**Comment by janharaldfredriksen-arm** [comment]
There are many implementation-specific factors that influence whether compression is supported for a given image - including the format, usage flags, etc. The extension does not require support for any particular set for VkFormats. The support needs to be queried:

>To determine the compression rates that are supported for a given image format, add a VkImageCompressionPropertiesEXT structure to the pNext chain of the VkImageFormatProperties2 structure in a call to vkGetPhysicalDeviceImageFormatProperties2.


For Arm's initial implementation, there are some details on what's supported in this presentation: https://vulkan.org/user/pages/09.events/vulkanised-2023/vulkanised_2023_getting_started_on_mobile_and_best_practices_for_arm_gpus.pdf
