### ISSUE TITLE
Graphics pipelines with rasterization and no fragment shader

### ISSUE THREAD

**Issue by jlegg0** [KhronosGroup/Vulkan-Docs#2123]
VUID-VkGraphicsPipelineCreateInfo-None-06573 says:
> the pipeline must be created with a complete set of state.

(or, depending on how the docs are built, VUID-VkGraphicsPipelineCreateInfo-graphicsPipelineLibrary-06607, with an extra "if the graphicsPipelineLibrary feature is not enabled" qualification).

Section 10.2 (Pipelines / Graphics Pipelines) says:
> 	Fragment shader state is defined by:
> 		• A VkPipelineShaderStageCreateInfo entry for the fragment shader

\<snip\>

> 	If the value of VkPipelineRasterizationStateCreateInfo::rasterizerDiscardEnable in the pre-rasterization shader state is VK_FALSE or the VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE dynamic state is enabled fragment shader state and fragment output interface state is included in a complete graphics pipeline.

Is the intention that a fragment shader is required when not using `rasterizerDiscardEnable`, or is the fragment shader state still correctly defined if there is no `VkPipelineShaderStageCreateInfo` entry for a fragment shader? This isn't totally clear to me.

Section 28.1 (Rasterization / Discarding Primitives Before Rasterization) says:
> Primitives are discarded before rasterization if the rasterizerDiscardEnable member of VkPipelineRasterizationStateCreateInfo is enabled.

and section 29 (Fragment operations) says:
> Fragments produced by rasterization go through a number of operations to determine whether or how values produced by fragment shading are written to the framebuffer.

However, section 29.5: (Fragment Operations / Fragment Shading) says:
> If no fragment shader is included in the pipeline, no fragment shader is executed, and undefined values may be written to all color attachment outputs during this fragment operation.

Similarly, section 29.6. (Fragment Operations / Multisample Coverage) has wording for when no fragment shader is active.

If either no primitives could be rasterized or a fragment shader is required, then the quoted part of section 29.5 is unnecessary since the situation it describes could only happen due to a bug. However, if the fragment shader is optional, then the validation layer is detecting false positive violations of VUID-VkGraphicsPipelineCreateInfo-None-06573. If permitted, rasterization without a fragment shader would have applications in depth only rendering and occlusion testing.

**Comment by HansKristian-Work** [comment]
> Is the intention that a fragment shader is required when not using rasterizerDiscardEnable, or is the fragment shader state still correctly defined if there is no VkPipelineShaderStageCreateInfo entry for a fragment shader? This isn't totally clear to me.

It's valid to omit the fragment shader, even when not using rasterizer discard. This is used for e.g. depth-only rendering.

> Fragment shader state is defined by:
• A VkPipelineShaderStageCreateInfo entry for the fragment shader

I think this is just trying to say that *if* fragment shader is added to the PSO, it belong in the fragment shader state subset, it does not imply that particular shader is required to have complete fragment shader state.

There might be some clarification needed.

**Comment by jlegg0** [comment]
Okay. If you think it is clear enough we can close this issue.

The validation layer false positive I mentioned in the first comment has been fixed. I had difficulty building it, so I didn't bisect to an exact revision, but the 1.3.243 SDK required a fragment shader whereas the 1.3.250 SDK does not.
