### ISSUE TITLE
Add info on initial signal state for vkCreateEvent

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Docs#213]
The documentation for vkCreateEvent does not have any information on the initial signal state for a newly created event. 

Contrary to fences (VK_FENCE_CREATE_SIGNALED_BIT), there are no flags (yet) for setting the initial signal state of the event upon creation, and thus there is no paragraph talking about it's initial state.

Adding a small paragraph that clearly states the initial state of an event as not set could avoid some confusion.

**Comment by yavn** [comment]
It's true that there's currently no way to create an event in signaled state. But the information about the initial state is present in the spec, next to `VkEventCreateInfo` description:

> The flags member of the VkEventCreateInfo structure pointed to by pCreateInfo contains flags defining the behavior of the event. Currently, no flags are defined. When created, the event object is in the unsignaled state.

Do you have a use case where creating a signaled event would be useful?

**Comment by SaschaWillems** [comment]
> Do you have a use case where creating a signaled event would be useful?

No, but I wasn't sure at first in which state an event is created, and as such I was missing this information in man pages.

> It's true that there's currently no way to create an event in signaled state. But the information about the initial state is present in the spec, next to VkEventCreateInfo description:

I could not find such a note in the docs, that's why I opened up the issue. But you're right, it's present in the spec but not in the man pages as far as I can tell.

**Comment by oddhack** [comment]
The ref pages are slated to get entirely replaced by simply extracting the relevant bits of the API spec in the (relatively near) future, anyway, so we're disinclined to spend time updating the current pages. (relatively near) means it's dependent on some other toolchain issues that need to be resolved, but I'm hoping for sometime in the next month. So wontfixing this.
