### ISSUE TITLE
SPV_EXT_opacity_micromap missing from SPIR-V extension table

### ISSUE THREAD

**Issue by Saancreed** [KhronosGroup/Vulkan-Docs#2131]
The SPIR-V extension table does not have an entry for SPV_EXT_opacity_micromap but VK_EXT_opacity_micromap requires it to be supported. This seems to cause calls to `vkCreateShaderModule` when validation layers are enabled to generate an error message like this:

> VUID-VkShaderModuleCreateInfo-pCode-04146(ERROR / SPEC): msgNum: -670416210 - Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-04146 ] Object 0: handle = 0x7f916cfdf930, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xd80a42ae | vkCreateShaderModule(): A SPIR-V Extension (SPV_EXT_opacity_micromap) was declared that is not supported by Vulkan. The Vulkan spec states: pCode must not declare any SPIR-V extension that is not supported by the API, as described by the Extension section of the SPIR-V Environment appendix (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-04146)

But it sounds strange because it suggests that there's no way to actually use RT opacity micromap capability in any shader.

**Comment by spencer-lunarg** [comment]
yes, seems this is just missing from the XML

```xml
        <spirvextension name="SPV_EXT_opacity_micromap">
            <enable extension="VK_EXT_opacity_micromap"/>
        </spirvextension>
```

I made an internal spec fix, so this should be up for the next header release, thanks for bringing to our attention

**Comment by spencer-lunarg** [comment]
This was added in https://github.com/KhronosGroup/Vulkan-Docs/commit/45b5ba66f8128be493745da2d45f0bb407d9296a (1.3.251 spec)

Will be in the Validation Layers soon when bring in the new headers
