### ISSUE TITLE
VK_NV_cuda_kernel_launch missing from vk.xml

### ISSUE THREAD

**Issue by jdtatz** [KhronosGroup/Vulkan-Docs#2133]
It was announced at the end of 2021 as the successor to `VK_NVX_binary_import`, but is missing from the spec

**Comment by oddhack** [comment]
@dgkoch can you triage this for NVIDIA?

**Comment by dgkoch** [comment]
Yes - we haven't published this yet. I've poked the extension author to get this wrapped up.

**Comment by dgkoch** [comment]
This is now published in the 1.3.269 spec https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VK_NV_cuda_kernel_launch
