### ISSUE TITLE
[VK_QCOM_render_pass_shader_resolve] Valid rasterizationSamples value clarification.

### ISSUE THREAD

**Issue by nwessing** [KhronosGroup/Vulkan-Docs#2136]
[VK_QCOM_render_pass_shader_resolve] @wwlk

From the spec [VUID-VkRenderPassCreateInfo2-rasterizationSamples-04905](https://registry.khronos.org/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkRenderPassCreateInfo2-rasterizationSamples-04905)

I don't understand how I am supposed to resolve down to a single sampled image from a multisampled image if the `rasterizationSamples` of the pipeline used for the resolve must match the sample count of the input attachments. It would make sense to have `rasterizationSamples` match the sample count of the color and depth/stencil attachments (not the input attachments). I have spent the last week working the use of this extension into my application and it seems like the documentation here is just wrong, seems like the `rasterizationSamples` should indeed match the sample count of the images that are being rendered too.

**Comment by oddhack** [comment]
@jackohound - @wwlk doesn't seem to be very active so assigning to you.

**Comment by jackohound** [comment]
Hi @nwessing,

If you want to use VK_QCOM_render_pass_shader_resolve to resolve down to a single sampled image from a multisampled image then you don't need to use VK_SUBPASS_DESCRIPTION_FRAGMENT_REGION_BIT_QCOM at all.  

Refer to the [Framebuffer Region Dependencies](https://registry.khronos.org/vulkan/specs/1.1-extensions/html/vkspec.html#synchronization-framebuffer-regions) chapter in the spec. The use case you are describing is a case where `M does not equal N`.

The intended use of VK_SUBPASS_DESCRIPTION_FRAGMENT_REGION_BIT_QCOM is limited to those cases where `M equals N`. 
 For those cases (where the input attachment sample count does match the pipeline `rasterizationSamples`), then including the new flag changes the framebuffer-region from sample-sized to fragment-sized.    The impact is described in the note that starts with "Practically, the pixel vs. sample granularity dependency...".

I'll leave this issue open to see if you have further questions, but I suspect that for your use-case, you should remove the VK_SUBPASS_DESCRIPTION_FRAGMENT_REGION_BIT_QCOM flag.

**Comment by nwessing** [comment]
@jackohound thanks for answering, I can see now that the spec allows fragment region sampling without the use of the extension. I am still curious if it is worth using this extension for `VK_SUBPASS_DESCRIPTION_SHADER_RESOLVE_BIT_QCOM`. From my reading of the spec, I don't think this flag is necessary to make what I want actually work (I see language in the spec that details what does not happen when I enable that flag, but not what actually does happen). I am wondering what this flag actually does? Is it a performance hint that allows the driver to optimal tile sizing?

**Comment by jackohound** [comment]
VK_SUBPASS_DESCRIPTION_SHADER_RESOLVE_BIT_QCOM provides the flexibiliy of shader-baesed resolve while also providing other spec language guarantees that allow the Adreno implementation to maximize efficiency of tile memory.   If you need shader-based resolved, then use of the extension will allow Adreno to more efficiently allocate tile memory to the attachments while saving bandwidth because we can replace the StoreOp with the shader-based resolve.  So yes, it allows for more optimal tile-based implementation.

**Comment by nwessing** [comment]
Thanks for the assistance!
