### ISSUE TITLE
Is it possible to use layout transition from initialLayout to first subpass correctly?

### ISSUE THREAD

**Issue by Themaister** [KhronosGroup/Vulkan-Docs#215]
The rules for subpass transitions currently state:

```
The automatic image layout transitions from initialLayout to the first used layout (if it is different) are performed
according to the following rules:

• If the attachment does not include the VK_ATTACHMENT_DESCRIPTION_MAY_ALIAS_BIT bit and there is no
subpass dependency from VK_SUBPASS_EXTERNAL to the first subpass that uses the attachment, then it is as if there
were such a dependency with srcStageMask = srcAccessMask = 0 and dstStageMask and dstAccessMask
including all relevant bits (all graphics pipeline stages and all access types that use image resources), with the
transition executing as part of that dependency. In other words, it may overlap work before the render pass instance and
is complete before the subpass begins.
```

However, srcStageMask and srcAccessMask are 0 here, so it will ignore any pipeline barriers and semaphores (at least if pDstWaitStages = COLOR_ATTACHMENT_OUTPUT_BIT) is used. For a common case of rendering to a swapchain image, this becomes impossible since the layout transition from PRESENT_SRC/UNDEFINED to COLOR_ATTACHMENT will happen potentially before the semaphore signals due to the nature of pDstWaitStages. Similar with render passes that are written multiple times with a write-after-write hazard for depth buffers.

Is this intended behavior? Unless the initial layout transition observes barriers in some way it seems impossible to use it correctly in an application.

**Comment by ratchetfreak** [comment]
I would presume that you would need to include a external dependency for the first subpass using the swapchain image.

> * If the attachment does not include the VK_ATTACHMENT_DESCRIPTION_MAY_ALIAS_BIT bit and there is a subpass dependency from VK_SUBPASS_EXTERNAL to the first subpass that uses the attachment, then the transition executes as part of that dependency and according to its stage and access masks. It **must not** overlap work that came before the render pass instance that is included in the source masks, but it may overlap work in previous subpasses.

**Comment by Themaister** [comment]
I see. Yes, that does explain things.

**Comment by oddhack** [comment]
@Themaister does @ratchetfreak's answer address your issue? If so, please close the issue.

**Comment by oddhack** [comment]
Closing. If there's still an issue, please open a new issue against the current spec.
