### ISSUE TITLE
`VK_EXT_descriptor_buffer`: NVidia driver crash w/out validation error when `VK_DESCRIPTOR_SET_LAYOUT_CREATE_DESCRIPTOR_BUFFER_BIT_EXT` omitted

### ISSUE THREAD

**Issue by goulash32** [KhronosGroup/Vulkan-Docs#2150]
I had an embarrassingly long debugging session trying to figure out why my app was crashing upon calling `vkCmdSetDescriptorBufferOffsetsEXT()` after binding my descriptor buffers. This was on the latest Vulkan SDK (1.3.250.0) on the latest Windows 10 update, with the current release drivers (536.23) for my GeForce RTX 2070 Max-Q.

I did many back-and-forth comparisons with Sascha Willem's example (which ran fine on my machine), but ultimately it turns out I had neglected to include the `VK_DESCRIPTOR_SET_LAYOUT_CREATE_DESCRIPTOR_BUFFER_BIT_EXT` flag when creating my descriptor set layouts. Mea culpa, but it would have been great to have an informative validation error message in such a scenario.

**Comment by krOoze** [comment]
Validation layers are this way -> https://github.com/KhronosGroup/Vulkan-ValidationLayers

**Comment by goulash32** [comment]
Whoops! Thank you.
