### ISSUE TITLE
vulkan.h includes stdint.h through vk_video/*.h even if VK_NO_STDINT_H is defined

### ISSUE THREAD

**Issue by chloekek** [KhronosGroup/Vulkan-Docs#2155]
`vulkan.h` includes `vulkan_core.h`.
`vulkan_core.h` includes `vk_video/vulkan_video_codec_h264std.h` (and others).
`vk_video/vulkan_video_codec_h264std.h` (and others) includes `stdint.h` even if `VK_NO_STDINT_H` is defined.

I expect that `vk_video/vulkan_video_codec_h264std.h`, and all other Vulkan headers, also honor `VK_NO_STDINT_H`.

**Comment by oddhack** [comment]
@aqnuep could you bring this to the Video TSG? Makes sense, we would just change the definition in video.xml to bracket the include with the protection symbol.

**Comment by aqnuep** [comment]
Of course, we'll resolve this in the Video TSG. Thanks for letting me know about it.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.258 spec update - please check and reopen with a comment if not. Thanks!
