### ISSUE TITLE
Add include-what-you-use pragmas to vulkan headers; vulkan.h and vulkan.hpp are the primary files to include

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/Vulkan-Docs#2158]
Some of our partners use an include-what-you-use checker to keep their headers clean.
See https://github.com/include-what-you-use/include-what-you-use/tree/master#instructions-for-users for details, but in short it means that when a .c or .cpp needs a declaration, then it should include the header file that has that declaration, rather than on an intervening header.  This helps readability and maintainability.

The issue our partners have is:  Their code should #include "vulkan/vulkan.h"
But the include-what-you-use checker complains that that doesn't actually contain the definitions they use.  Instead the definitions are in other files like vulkan_core.h or vulkan_android.h

It would help if we could inform the include-what-you-use (IWYU) tool that vulkan.h is the public interface and the other sibling files are private.
To do so, we would modify vulkan.h so it would add "export" pragmas. For example, where today it has:

      #include "vulkan_android.h"

we would change that to

      #include "vulkan_android.h"  /* IWYU pragma: export */`

This says that definitions in vulkan_android.h should be deemed as being provided by vulkan.h itself.

**Comment by dneto0** [comment]
If such a change is acceptable, I'd be happy to post a PR for this.

**Comment by dneto0** [comment]
To make this concrete, the intended interface headers are the ones that would get the 'export' pragma.  My understanding is that the intended interface headers are:

 vulkan/vulkan.h
 vulkan/vulkan.hpp

 vk_video/vulkan_video_codec_h264std_decode.h
 vk_video/vulkan_video_codec_h264std_encode.h
 vk_video/vulkan_video_codec_h265std_decode.h
 vk_video/vulkan_video_codec_h265std_encode.h

**Comment by dneto0** [comment]
Oh, additionally vulkan/vulkan_core.h is also an export interface.

(See https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap56.html#boilerplate-vulkan-core )

**Comment by cubanismo** [comment]
I think the include checkers are accurate, actually. vulkan.h is a compatibility thing. It is intended that modern apps, and certainly ones that are this pedantic about their include structure, include vulkan_core.h, vulkan_android.h, etc. directly.

**Comment by oddhack** [comment]
If you wanted this change in vulkan.hpp you would need to ask on the Vulkan-Headers repo.
