### ISSUE TITLE
Missing extension list in pdf

### ISSUE THREAD

**Issue by Starielora** [KhronosGroup/Vulkan-Docs#2159]
Hi,
In online version of the spec there's a list of extensions, which can be clicked to move to description. PDF version seems to be missing this list. Is it intended?

I've used these links for comparison:
https://registry.khronos.org/vulkan/specs/1.3/pdf/vkspec.pdf
https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#extensions

Sorry if this was answered previously, or it's mentioned somewhere in documentation. I didn't find it.

**Comment by oddhack** [comment]
We publish several builds of the specification and these are different builds - the PDF is just the Vulkan core with no extensions, the HTML is all extensions. The  PDF corresponding to the HTML is https://registry.khronos.org/vulkan/specs/1.3-extensions/pdf/vkspec.pdf
