### ISSUE TITLE
Two 'Cooperative Matrices' sub-chapters

### ISSUE THREAD

**Issue by qbojj** [KhronosGroup/Vulkan-Docs#2162]
Currently there are two 'Cooperative Matrices' sub-chapters in the 'Shaders' chapter: one for `VK_NV_cooperative_matrix` and other for `VK_KHR_cooperative_matrix`.

Shouldn't there be an distinction in the titles of those two chapters?

**Comment by kpet** [comment]
This has been fixed internally and should be addressed in the next release. Apologies this was not spotted before release.
