### ISSUE TITLE
Does `VK_ACCESS_SHADER_READ_BIT` include uniform reads?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#2169]
Since it is a major compatibility breaking change introduced in 1.2.180, and not explicitly called out in changelog, I want to doublecheck if intentional:

Does `VK_ACCESS_SHADER_READ_BIT` really include uniform reads (which do have their own bit)?

**Comment by Tobski** [comment]
Hi @krOoze, thanks for spotting this! That does seem like an accident, but it's not entirely clear what was supposed to happen here - sync2's equivalent bit DID include uniform buffer reads, and this was done to make sync1 consistent. We've raised an internal issue to poll IHVs and make sure appropriate tests are in place if we decide they are supposed to be included.

**Comment by Tobski** [comment]
After looking into this, it looks like it was never tested for sync2 either, and multiple implementations treat them separately; so we're going back to having uniform read be fully separated for both sync1 and sync2 This should be fixed in the next spec update.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.262 spec update.
