### ISSUE TITLE
pipeline stage lacks a glossary entry.

### ISSUE THREAD

**Issue by ratchetfreak** [KhronosGroup/Vulkan-Docs#217]
The term "pipeline stage" is used very often and is crucial to understanding the sync behavior however there is no explanation of the term or which vkCmd\* touch which stage(s). 

Similarly there is barely any explanation about when which VkAccessFlagBits are appropriate.

**Comment by krOoze** [comment]
And e.g. (Image) Layout,Tiling, Format, Layer and Extension. Also WSI and extension terms seem to be missing too like Swapchain and Surface and Presentation Mode.

BTW: I would argue Glosary is a bad fit for a specification. I would like an index more, that is link(s) to the place those terms are properly defined.

BTW2: It would be nice, if half of those terms would be explained/introduced in some Vulkan Architecture/Design Overview in chapter 1 or 2.

BTW3: In HTML glossary is unnumbered and placed after appendices. In PDF it's numberd and placed before appendices. It should perhaps be made consistent...

**Comment by NicolBolas** [comment]
> BTW2: It would be nice, if half of those terms would be explained/introduced in some Vulkan Architecture/Design Overview in chapter 1 or 2.

On that point, the ISO C++ specification has a glossary in the front. It's interesting to note that they don't define all, or most, terms within it. Instead, they select which terms need definitions based on the frequency of their use. For less frequently used terms, the index is how you find definitions.

**Comment by oddhack** [comment]
I'd like to have an index too, but it's a major editing task and won't happen in the near future. A lot of this is a judgement call as to how fundamental a term is - there are a lot of things marked off with italics in the spec body that are sort of placeholders for potential glossary or indexable items, when we get around to it. I'm deferring this because it's an open-ended issue with no particular endpoint in sight and I can't be confident when we would get to it other than incrementally.

**Comment by ratchetfreak** [comment]
There is still the underlying issue of the lack of explanation of what a pipeline stage is and how it interacts with barriers (and what commands touch which stages). 

I've written a short I've written up [a short summary of what I've gleaned and assumed](https://gist.github.com/ratchetfreak/62b9e795d452f93bcbdcee3664acca0e) but I don't think it's fit to be included in the spec in its current form. You (or anyone in Khronos) are free to take it and adapt it if you want.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.35 spec update, as part of the synchronization language rewrite.
