### ISSUE TITLE
vkCmdUpdatePipelineIndirectBuffer missing NV suffix.

### ISSUE THREAD

**Issue by Joshua-Ashton** [KhronosGroup/Vulkan-Docs#2171]
vkCmdUpdatePipelineIndirectBuffer is from VK_NV_device_generated_commands_compute, an NVIDIA vendor extension, and is thus missing NV suffix.

This is pretty severe as it implies this function is core which it definitely is not.

It is likely this can be fixed in a spec revision as a driver supporting this extension has not been released yet.

https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdUpdatePipelineIndirectBuffer.html

**Comment by oddhack** [comment]
Thanks for catching that - looks like naming review did not. I have created an internal tracker assigned  to the extension author at NV as they don't seem to be part of this organization on github.

**Comment by dgkoch** [comment]
Indeed - I obviously missed that in my final review 😢 

Fix is prepared internally, and we're updating the driver before releasing it.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.259 spec update (please confirm & close if you agree).
