### ISSUE TITLE
Missing StdVideoH265LongTermRefPicsSps

### ISSUE THREAD

**Issue by DanielBaumert** [KhronosGroup/Vulkan-Docs#2174]
Hello, 

today our analyzer hit a fatal error at the "StdVideoH265LongTermRefPicsSps"-struct. 
It couldn't find it anywhere in the xml defined; its also not present in any header?

We tried to figure out how the structure looks like, but we also didn't find it manually in the https://github.com/KhronosGroup/Vulkan-Docs/blob/2c1e07a72b43f53cc7866c55ae32afe97d933621/xml/video.xml#L1170 or somewhere else.

Is this by design?

@baetz-daniel  @DanielBaumert - @exomia

**Comment by oddhack** [comment]
It was accidentally left in during some recent refactoring of video.xml, and should be fixed in the 1.3.259 spec update just pushed. Please reopen if you're still seeing the problem.
