### ISSUE TITLE
VK_MESA_video_decode_av1 “Provisional” spec and headers release?

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/Vulkan-Docs#2175]
Hi,
seeing supported by latest NV VK dev driver and also a PR for RADV support (https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/21173) and finally supported by ffmpeg (and also mpv) it isn’t time to include in a vulkan spec release? even in beta form, similar to vk encode extensions..
After all, for exampe h265 encode ext even it isn’t supported by Nv driver, yet it’s published..
Thanks..

**Comment by oddhack** [comment]
This should be directed towards the Mesa developers - they're the only ones who can document their own extension. We'd like to be able to include spec language and XML for every extension that's shipping in some form, but we don't have any mechanism to require that.

**Comment by oscarbg** [comment]
Thanks, will do..

**Comment by oscarbg** [comment]
Reuqested here:
https://gitlab.freedesktop.org/mesa/mesa/-/issues/9451
