### ISSUE TITLE
About Android (Google) stance on Vulkan Video

### ISSUE THREAD

**Issue by arm64-v9a** [KhronosGroup/Vulkan-Docs#2176]
https://source.android.com/docs/compatibility/13/android-13-cdd#7142_vulkan
>[C-1-11] MUST NOT enumerate support for the VK_KHR_video_queue, VK_KHR_video_decode_queue, or VK_KHR_video_encode_queue extensions.

Why are you blocking Vulkan Video in CDD? MediaCodec is too high level. There are many scenarios where a low-level hardware acceleration API is needed, such as supporting Dolby video playback on devices without Dolby Vision codec via libplacebo.

**Comment by ianelliottus** [comment]
Please file an issue with the Android issue tracker.  Please see: https://source.android.com/docs/setup/contribute/report-bugs

**Comment by ianelliottus** [comment]
Closing this
