### ISSUE TITLE
Image barriers valid usage

### ISSUE THREAD

**Issue by faserg1** [KhronosGroup/Vulkan-Docs#218]
Vulkan spec:
`srcAccessMask` is a bitmask of the classes of memory accesses performed by the first set of commands that will participate in the dependency.
But as I understand, there can be zero value if `oldLayout` is `VK_IMAGE_LAYOUT_UNDEFINED`.

**Comment by krOoze** [comment]
Yes there can. Unless otherwisely specified. Or what is the _issue_ exactly?

Thinking is, zero is also a bitmask. As in: "empty set is a set".

Similar to issue #188 and #189 .
