### ISSUE TITLE
Cut off descriptions for VK_NV_device_generated_commands_compute

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Docs#2184]
The description for `VkComputePipelineIndirectBufferInfoNV` seems to be cut off:

"VkComputePipelineIndirectBufferInfoNV - Structure describing the device address where pipeline"

The sentence just ends after the "where pipeline".

See https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_NV_device_generated_commands_compute.html

Same for `vkGetPipelineIndirectDeviceAddressNV`:

"vkGetPipelineIndirectDeviceAddressNV - Get pipeline"

See https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetPipelineIndirectDeviceAddressNV.html

In General the man pages for the structs and functions of `VK_NV_device_generated_commands_compute` seem to be "very light" in regards to descriptions.

**Comment by oddhack** [comment]
There should be some improvements in the next spec update (there was some missing markup in one or two cases, that messed up the refpages), but at least the first example is still there AFAICT.

@dgkoch could you ask Vikram to send me their github handle, so I can add them to KhronosGroup and they can be assigned here?

**Comment by oddhack** [comment]
Thanks. That's odd, the assignee box didn't complete previously when I tried assigning to you.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.261 spec update.
