### ISSUE TITLE
VK_QUERY_RESULT_WITH_STATUS_BIT_KHR for performance queries?

### ISSUE THREAD

**Issue by Erellu** [KhronosGroup/Vulkan-Docs#2185]
Per **[`VUID-vkGetQueryPoolResults-queryType-03230`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetQueryPoolResults.html#VUID-vkGetQueryPoolResults-queryType-03230)**:
> If the `queryType` used to create `queryPool` was `VK_QUERY_TYPE_PERFORMANCE_QUERY_KHR`, `flags` **must** not contain `VK_QUERY_RESULT_WITH_AVAILABILITY_BIT`, `VK_QUERY_RESULT_PARTIAL_BIT` or `VK_QUERY_RESULT_64_BIT`.

This seems unnatural to me that `VK_QUERY_RESULT_WITH_STATUS_BIT_KHR` would be valid for performance queries if `VK_QUERY_RESULT_WITH_AVAILABILITY_BIT` is not. This also seems to conflict with
>  If the `queryPool` was created with `VK_QUERY_TYPE_PERFORMANCE_QUERY_KHR`, results for each query are written as an array of the type indicated by [VkPerformanceCounterKHR](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPerformanceCounterKHR.html)::`storage` for the counter being queried.

I am however not sure this isn't just me overthinking...

**Comment by aqnuep** [comment]
Indeed `VK_QUERY_RESULT_WITH_STATUS_BIT_KHR` should not be allowed in this case either.

Thanks for your report.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.261 spec update.
