### ISSUE TITLE
Erronous description for VkPerformanceCounterResultKHR

### ISSUE THREAD

**Issue by Erellu** [KhronosGroup/Vulkan-Docs#2186]
The [description of `VkPerformanceCounterResultKHR`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPerformanceCounterResultKHR.html#_description) states (emphasis mine):

> Performance query results are returned in an array of `VkPerformanceCounterResultKHR` unions containing the data associated with each counter in the query, stored in the same order as the counters supplied in pCounterIndices when creating the performance query. The **[`VkPerformanceCounterKHR`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPerformanceCounterKHR.html)::unit** enumeration specifies how to parse the counter data.

This is erronous. The correct member to check is `storage`, which [\[specifies\] the storage type that the counter’s data uses](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPerformanceCounterKHR.html).

**Comment by oddhack** [comment]
This should be fixed in the 1.3.262 spec update.
