### ISSUE TITLE
VK_NV_optical_flow clarification vs Optical Flow SDK

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/Vulkan-Docs#2195]
[VK_NV_optical_flow] @crohde

Hey Carsten,

Just looking for clarification. The optical_flow extension seems like it can be functional on it's own. However the Optical Flow SDK uses an extra binary (nvofapi64.dll) instead of calling vkCmdOpticalFlowExecuteNV() directly. Can you elaborate on what the difference between these workflows are?
Thanks
Malcolm

**Comment by crohdewm** [comment]
Hi Malcom,

Primary goal was to add vulkan support to the Optical Flow SDK and keep the API similar to the existing APIs CUDA, DX11 and especially DX12. In case of vulkan, you are right, it's possible to use the VK_NV_optical_flow extension on it's own, using Optical Flow SDK is only for convenience.

-Carsten

**Comment by oddhack** [comment]
@mbechard if this addressed your question, please close the issue. Thanks.
