### ISSUE TITLE
VkImportMemoryHostPointerInfoEXT pHostPointer non-const

### ISSUE THREAD

**Issue by martty** [KhronosGroup/Vulkan-Docs#2197]
In the struct [VkImportMemoryHostPointerInfoEXT](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap11.html#VkImportMemoryHostPointerInfoEXT) `pHostPointer` is defined as a non-const pointer - as far as I can tell this is an input parameter and should be const. 

Is there something that is unsaid in the spec (or that I am missing) that necessitates it being non-const?

**Comment by krOoze** [comment]
As for pointer being mutable, that feels like a common practice in C\C++. Things are mutable in API, and possibly redefined `const` in implementation.

As for pointee being mutable, than seems somewhat natural consitering it might be R/W memory that is being imported, and might be written to it by Vulkan at some point during the memory's use.

**Comment by cubanismo** [comment]
Right, the difference Vs. other input pointer parameters is that the value of the pointer is itself the input itself here, rather than it pointing to some structure in memory that contains the const input values. I.e., there's no indirection in this parameter.

Agreed with @krOoze on why non-const is actually more accurate.

**Comment by martty** [comment]
> For example the same pointer could be later returned from vkMapMemory() (as non-const).

In that case you'd get a different a pointer back (it doesn't matter if it points to the same address).

As it stands, it takes a mutable pointer, with the meaning that this call can mutate the values at the pointed location. I think this meaning is unlikely.

If the function operates on addresses (and not pointers), then it could've taken uintptr_t instead of void*.

**Comment by krOoze** [comment]
> In that case you'd get a different a pointer back (it doesn't matter if it points to the same address).

Well, it does matter. Either way I covered both cases in previous comment.

Values (passed by copy) are typically not `const`ed in interface declarations. This is common in C++ and Vulkan-wise consistent with e.g. `vkCreateInstance::pCreateInfo`: it is `const VkInstanceCreateInfo*`, not `const VkInstanceCreateInfo* const`.

And neither it is pointer to const value (or in this case untyped memory span), because the memory may be modified, say, with `vkCmdFillBuffer()`, and that can't happen without at some point const-casting or doing semantically equivalent dark magic.

`uintptr_t` is optional in C99. The standard itself does not use it with its own stuff, like say `realloc`. And feels like it would be too smartistic. `*` already means address, and `void` already means no type behind the address.

**Comment by martty** [comment]
To be clear, I am suggesting the type should be `const void*`, consistent with all input parameters, not some other form of constness.

Creating a pointer-to-const doesn't mean the pointed memory is immutable, it simply means it can't be modified through that specific pointer (as a contract) - this is why it doesn't matter if one passes it through this interface. If the memory is mapped, the returned pointer is a different one, which is correctly non-const.

> uintptr_t is optional in C99.
So are the other sized integer types, yet the official headers use them. In any case, my preference would be the `const void*`.

**Comment by krOoze** [comment]
> If the memory is mapped, the returned pointer is a different one, which is correctly non-const.

I don't follow your logic. That would semantically be a const cast.

Yea sure I can do:
```
int* why_are_you_modifying_yourself(const int* p){
    const auto your_p_is_my_p = (uintptr_t)(p);
	const auto am_different_pointer_cant_stop_me = your_p_is_my_p + 4;
	return (int*)(am_different_pointer_cant_stop_me);
}

int main(){
	int my_valuable_values[] = {42, 69};
	auto p = why_are_you_modifying_yourself(my_valuable_values);
	*p = 13;
}
```

But that does not feel healthy.

> So are the other sized integer types

They are required if the underlying type exists on the platform. And Vulkan specification [demands that they do](https://registry.khronos.org/vulkan/specs/1.0/html/vkspec.html#fundamentals-host-environment).

**Comment by martty** [comment]
There are no semantic concerns here: as the API user, the mapped pointer you get back is a different pointer. If the implementation chooses to retain this pointer you passed in to give later back casted, so be it - this is an implementation detail.

What matters is what the API means. A non-const pointer - output parameter. It is inconsistent with every other interface. This is why I said that if it must be a different meaning (not actually a pointer), then one could use `uintptr_t`. But personally I just think it should be `const void*`.

> The integer types are required if they exist on the platform. And Vulkan does [demand that they exist](https://registry.khronos.org/vulkan/specs/1.0/html/vkspec.html#fundamentals-host-environment).

Yes, so there is no point in bringing this up, Vulkan could require this to exist the very same - I would expect you won't actually find a platform without it. (Although after the bitfield shenanigans in the RT ext this is an a strange point to make)

**Comment by krOoze** [comment]
I find it surprising you consider const cast an implementation detail. That shouts API contract violation, and "safe" languages like Rust would not even permit it.

Mutable pointer means "mutable", not necessarily output. In this case it is neither input, nor output. It is import.

**Comment by HansKristian-Work** [comment]
krOoze's last comment is accurate here. The pointer given to Vulkan can be written to later, so it should be `void *`.
