### ISSUE TITLE
Note that spec Makefile may need ASCIIDOC etc. paths changed/set in the environment for some platforms

### ISSUE THREAD

**Issue by teamblubee** [KhronosGroup/Vulkan-Docs#22]
I had trouble running the makefile to build the documents as is. I had to make these slight modifications

```Makefile
APINAME=Vulkan
QUIET?=@
ASCIIDOC ?= asciidoc
A2X ?= a2x
DBLATEX ?= dblatex
```

Just basically removing the .py extensions.
I am on debian jessie 8.3

**Comment by oddhack** [comment]
I have those set in the environment when I'm building on Debian. If you have any clever ideas on configuring the Makefile to autodetect which filename the programs are under, I'd be happy to review a pull request helping fix the issue, but we do have to support a pretty wide variety of build environments.

**Comment by teamblubee** [comment]
I don't have any clever tricks to fix this but if anyone else comes across this error this issue might help them solve the problem.

**Comment by oddhack** [comment]
I'll make a note of this in the doc/specs/vulkan/README.{txt,html}, at least.

**Comment by oddhack** [comment]
I've updated the doc/specs/vulkan/README.{txt,html} to describe this scenario, which is all we're likely to do with the build system until we run out of public spec issues to deal with and have some time for ancillary activities like this.
