### ISSUE TITLE
Suggestion for new `VkFormat` value specifically for normal maps

### ISSUE THREAD

**Issue by alexpanter** [KhronosGroup/Vulkan-Docs#2202]
# Motivation

Many 3d rendering applications use a deferred approach with a color attachment containing 3d normal vectors.
But this takes up a lot of disk space, since each x,y,z component of a normal vector might need more than 8 bits to avoid loss of precision when computing light and reflections.

We can observe that since a normal vector should always be of unit magnitude, if we store only the x and y components, we should be able to solve for z using algebra. The problem of this is that such a computation has 2 solutions:

```
n = [ x y z ]
||n|| = sqrt(x*x + y*y + z*z) = 1

1^2 = x*x + y*y + z*z
z*z = 1 - x*x - y*y
z = sqrt(1 - x*x - y*y)
```

This yields a situation where both z/-z are valid solutions. So we need to know in which direction the 3d normal is pointing.

---

And this got me thinking: If we create a dedicated `VkFormat` value for a normal map, we would need 2 color components of sufficient precision, and a single bit indicating the sign of the z-component. The suggestion could look like this:

```
VK_FORMAT_R16G15A1_NORMAL_MAP_PACK32
```

It should be possible to obtain all 3 components of a normalized vector with minimized loss of precision.

## Unpacking the normal vector

The texture sampler could be specified to do a number of (convenient) operations, as this format would be _dedicated_ storage format for 3d normals:

```
uint32 pack = read_pixel(u, y)
uint32 x = pack >> 16
uint32 y = (p & 0x0000FFFF) >> 1
uint32 a = pack & 0x01
float fx = (float(x) / 65535.0f) * 2.0f - 1.0f
float fy = (float(y) / 32767.0f) * 2.0f - 1.0f
float fa = (a == 1) ? -1.0f : 1.0f
float fz = sqrt(1.0f - (fx*fx + fy*fy)) * fa
return { fx, fy, fz }
```

This would unpack the 32 bits and reconstruct the z-component. It would be optimal if all this could be handled by the texture unit so that in the concern of the user, sampling from an image of this format would simply return a normalized and _signed_ 3d float vector (coordinate space arbitrary).

And as an added feature, it is not necessary to normalize the vector after sampling from the texture.

## Packing the normal vector

And when writing to an image of this format, the shader should not do the trick of renormalizing the vector from [-1,1] to [0,1], as this would _also_ be handled automatically by the implementation. The interface should be equivalent to `VK_FORMAT_R16G16B16_SFLOAT`, but with smaller memory footprint.

These operations (inverse of procedure above) would pack a 3d normal vector:

```
vec3 n; // [x y z] as requested to store inside a color attachment (fragment shader)
float ufx = (n.x + 1.0f) * 0.5f
float ufy = (n.y + 1.0f) * 0.5f
uint32 ux = uint32(round(ufx * 65535.0f)) // 2^16 - 1
uint32 uy = uint32(round(ufy * 32767.0f)) // 2^15 - 1
uint32 ua = (n.z < 0.0f) ? 1 : 0
uint32 pack = (ux << 16) | (uy << 1) | ua
return pack
```

## More

It might even be possible to support more formats with this idea in mind, such as:

```
VK_FORMAT_R8G7A1_NORMAL_MAP_PACK16
VK_FORMAT_R32G31A1_NORMAL_MAP_PACK64
```

Compared to storing with `VK_FORMAT_R16G16B16_SFLOAT` or similar formats, these should still save memory bandwith and storage space, which is the intention. Plus, these suggested formats might even work better with alignment requirements.

Furthermore, the suggestions presented here seems akin to the (somewhat canonical) approach for compression normal maps using ASTC L+A. However, whereas ASTC can be used when loading images from disk, the format(s) proposed here should be used only for framebuffer attachments.

## Code example

In order to keep this post as short as possible, I have published some code [here](https://github.com/alexpanter/normal-compression/blob/master/pack.cpp).
The epsilon used to test the difference of a normal vector before/after packing is 0.005, which is probably not a good value for testing floating-point equality in general, but loss of precision is expected with a method like this.

---

This is all just an idea. I'm sure it can be optimized further. And I also don't really have a good overview of whether or not this is even a good idea, which is why I just post it here.

Also, I don't know if this is even the right place to post this. :)

**Comment by krOoze** [comment]
If you really want two number, why not Euler angles\longitude+latitude?

**Comment by alecazam** [comment]
There have already been many 2d (and 3d) data stored into compressed texture formats.  Doom3 was an early pioneer.  I keep seeing this math below repeated, but it's incorrect.   It doesn't feel like there's every been a need for a specialized format, although ATI had ATI2N.

The math you have doesn't account for compressed or normalized textures that store fx and fy as signed data.  I have a better formula for z reconstruct in my kram texture engine.  And trust me, the values do exceed 1 no matter best efforts to prevent that, and also with mips.    Even 1.0 - 1.005 is a NaN.

fz = sqrt(1.0f - (fx*fx + fy*fy)) * fa

say fx = 1, fy =1
fz = sqrt(1.0f - (1.0 + 1.0)) * fa

fx = sqrt( -1 ) * fa = NaN

**Comment by alexpanter** [comment]
> If you really want two numbers, why not Euler angles\longitude+latitude?

@krOoze Euler angles are infamous for exhibiting gimbal problems. I'm not really sure how this would work with a normal pitch of exactly -90 degrees. Asides from this, we would need trigonometry to reconstruct the vectors. I _think_ .

**Comment by alexpanter** [comment]
> The math you have doesn't account for compressed or normalized textures that store fx and fy as signed data. I have a better formula for z reconstruct in my kram texture engine. And trust me, the values do exceed 1 no matter best efforts to prevent that, and also with mips. Even 1.0 - 1.005 is a NaN.

@alecazam The math that I use assume sampling from a texture using the storage format suggested, ie. non-compressed and non-signed. It's probably misleading that I call it `VK_FORMAT_R16G15A1_NORMAL_MAP_PACK32`, because it's not a normal map - rather a gbuffer normal attachment!

With regards to the invalid square root, do you think it would be a good idea to clamp the input, ie:
```
fz = sqrt(saturate(1.0f - (fxfx + fyfy))) * fa
```

Also, if you don't mind sharing I'm really curious to hear which formula you are using for z reconstruct.

**Comment by redorav** [comment]
I would take a look at the following links

- https://aras-p.info/texts/CompactNormalStorage.html
- https://knarkowicz.wordpress.com/2014/04/16/octahedron-normal-vector-encoding/

You'll find links in there that will take you to other places where you can investigate further. It has been a struggle in the industry to find an accurate way to store normals that is also blendable (for decals). People seem to have settled on octahedral encoding these days (it isn't blendable though). The downside of doing it yourself is that you pay for some ALU cost, but that's not a big deal.

**Comment by krOoze** [comment]
@alexpanter Gimbal lock does not happen with two gimbals. This is literally how GPS coordinates work. Trigonometry not that bad considering you are already happy with sqrt.

Basically "Method #3: Spherical Coordinates" in above link I think.

**Comment by TomOlson** [comment]
@alexpanter thanks for taking the time to write up your idea so clearly. As @redorav points out, the industry has pretty much converged on the solution of decoding 3D normals from 2D on the fly in the shader engine, rather than putting a hardwired converter into the texture unit. It's a classic GPU architecture tradeoff: a hardwired path would save a few cycles and a bit of power, but those transistors would be useless for anything *but* decoding unit vectors, while a faster shader engine makes pretty much everything better.  All of the GPU vendors out there today have come to the same conclusion, so that's what we're exposing in Vulkan.

We could define formats and sampler operations to hide the (frankly non-obvious) math in @redorav's references, but that would just be syntactic sugar and we have no plans to do it. We'd rather encourage the growth of ecosystem resources that make these sorts of tricks easy to find.

**Comment by alecazam** [comment]
@alexpanter 
see toNormal() on line 213 here
https://github.com/alecazam/kram/blob/main/kramv/Shaders/KramShaders.metal

This makes sure that n.z is reconstructed properly regardless of drift from compression snapping, bi/trilinear/aniso sampling, etc.  The number can exceed the normalized value.

About the best approximation is this  n.z = sqrt( saturate( 1.0 - x * x - y * y) ), but it's skewed if x or y are too long.
This overflows to negative n.z = sqrt( 1.0 - saturate( x * x - y * y) )
And this is just wrong n.z = sqrt( 1.0 - x * x - y * y )

**Comment by oddhack** [comment]
@alexpanter as Tom noted, we will not be doing this. The various comments should help with shader programming to the same effect.
