### ISSUE TITLE
Should `VK_KHR_swapchain_mutable_format` `require` `VkImageFormatListCreateInfoKHR` in `vk.xml`?

### ISSUE THREAD

**Issue by MarijnS95** [KhronosGroup/Vulkan-Docs#2203]
[`VK_KHR_image_format_list`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_image_format_list.html) provides [`VkImageFormatListCreateInfoKHR`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkImageFormatListCreateInfoKHR.html) (stabilized as `VkImageFormatListCreateInfo` in Vulkan 1.2), but [`VK_KHR_swapchain_mutable_format`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_swapchain_mutable_format.html) independently relies on this type (alias) without seemingly enabling it in in the XML.

I'm expecting `<type name="VkImageFormatListCreateInfoKHR"/>` to be in the `<require>` list for `<extension name="VK_KHR_swapchain_mutable_format" ...>`, is this a sensible expectation?

**Comment by r-potter** [comment]
In this case, it should just be inherited through the extension dependencies. `VK_KHR_swapchain_mutable_format` requires:

* VK_KHR_swapchain
* VK_KHR_maintenance2 or VK_VERSION_1_1
* VK_KHR_image_format_list or VK_VERSION_1_2

We typically add types to the `<require>` list directly either when the extension is introducing a new type for the first time, or where relying on an extension dependency would force developers to unconditionally enable an extension that may not make sense/be available. You can see an example of this with `VK_QCOM_tile_properties`, where forcing developers to enable `VK_KHR_dynamic_rendering` unconditionally to resolve the `VkRenderingInfoKHR` when they may just want to work with traditional framebuffers was undesireable.

**Comment by MarijnS95** [comment]
Ah thanks, I totally missed that this extension _requires_ `VK_KHR_image_format_list or VK_VERSION_1_2`, that clarifies!

(Not sure why I didn't originally _expect_ `VK_KHR_swapchain_mutable_format` to imply `VK_KHR_image_format_list`, because it is just extending its reach to `VkSwapchain` while still needing the functionality beyond that on `VkImage`)
