### ISSUE TITLE
VK_PIPELINE_STAGE_2_ALL_GRAPHICS_BIT suspiciously missing flag bits

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#2211]
It is suspicious that `VK_PIPELINE_STAGE_2_ALL_GRAPHICS_BIT` is missing `VK_PIPELINE_STAGE_2_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR`, which is part of "graphics primitive\mesh pipeline". Possibly others?

**Comment by oddhack** [comment]
@tobski we were not sure if the omission from the \<syncequivalent> tag for ALL_GRAPHICS_BIT is intentional or accidental, do you know?

**Comment by Tobski** [comment]
This was originally in the list of synchronization bits in the spec for ALL_GRAPHICS_BIT; looks like when \<syncequivalent> got added it got dropped from the list. @artem-lunarg @spencer-lunarg any thoughts on this one? I'm fairly sure it should just go in.

**Comment by Tobski** [comment]
Actually now I look at it, VK_PIPELINE_STAGE_2_SHADING_RATE_IMAGE_BIT_NV is in that list which is an alias - I don't know why that was preferred in the list; we should probably swap it out or just add both? Not sure what the correct resolution here would be as I don't know how that list is consumed.

**Comment by oddhack** [comment]
> Actually now I look at it, VK_PIPELINE_STAGE_2_SHADING_RATE_IMAGE_BIT_NV is in that list which is an alias - I don't know why that was preferred in the list; we should probably swap it out or just add both? Not sure what the correct resolution here would be as I don't know how that list is consumed.

In the spec artifacts, it only affects the autogenerated include appearing in the VkPipelineStageFlagBits2 language. Probably it affects downstream artifacts like VVL as well? Our general rule of thumb is to use the most-promoted version of a token but it's easy to overlook that when a promotion happens.

**Comment by Tobski** [comment]
@artem-lunarg Thanks for confirming! I'll raise an MR internally to fix this since it's a trivial change.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.265 spec update.
