### ISSUE TITLE
VK_INCOMPLETE - any advice on how to investigate it

### ISSUE THREAD

**Issue by timprepscius** [KhronosGroup/Vulkan-Docs#2216]
I'm porting a Vulkan application from iOS (minimum 2016 SE Ver 1), to Android (minimum 23, test phone is Experia X 2016.

I have a vert+frag shader that, during createGraphicsPipelineUnique, returns VK_INCOMPLETE.  Actually since I'm using the vulkan.hpp it throws it.

Starting tomorrow, I going to go on a coding binary search for the offending code segment.
And then a coding, "remove until it works," odyssey.

If I were a god of Vulkan (as you all are), is there a better way I would go about this?

Do I really have to run this thing 1000 times, with mini edits, to find out what works on android?
It's time consuming and exhausting.

**Comment by oddhack** [comment]
vkCreateGraphicsPipeline is documented to not return VK_INCOMPLETE, but because the call to that is buried inside wrappers generated by Vulkan-Hpp, we can't advise whether this is a driver bug or an Hpp issue - if your debugging can get inside the wrapper to the actual Vulkan call to determine where this return code is coming from, that may point you in the right direction before binary searching on your shader code. You may also want to bring this up on the Vulkan Discord - this repo is really just for issues with the specification, not general Vulkan programming advice.

**Comment by krOoze** [comment]
>  is there a better way I would go about this?

Validation layers (with all the extras checks enabled) as last defense. Being error avoidant when doing low-level as the first line. Problem with low-level is that even if it seems to work, it does not automatically imply your program is correct.

**Comment by timprepscius** [comment]
@krOoze Yeah, I think with Android, I'm not guaranteed *anything* will work all of the time.

I'm using this 2016 phone, hoping that if it works there, it will probably run on newer phones.
But again, this is android, so who knows.

In my case the phone driver doesn't handle something to do with uint16_t.
I never actually figured out what it couldn't handle.  Because some places uint16_t seemed fine.
Also, I figure there is optimization going on with the shader compiler, so I'm also not sure if the code I wrote is the code being run.  I don't know if that makes much sense.

Anyhow, after hundreds of attempts at isolating what actually was causing the problem, I finally gave up, and just got rid of all of the uint16_t - and now things run.

Thank you all for replying.  These days I seem to have the most difficult time getting helpful search results.

Thank you again.

**Comment by krOoze** [comment]
@timprepscius Yea I have a phone that is stuck at like 1.0.20, i.e. before even the sync was somewhat properly described in the spec. It doesn't help that some of these Android drivers had such riddiculously newbie bugs like failure to accept `VK_REMAINING_*` values. It probably makes sense to blacklist some too old devices, say roughly anything prior 1.1.

I don't think unupdated 2016 device would support `uint16_t`. That requires buncha extensions.

**Comment by oddhack** [comment]
Closing as OP seems to have found a solution.

**Comment by timprepscius** [comment]
I didn't find a solution.  Vulkan is horrendous on android.  It's better on iOS which is ironic.  Actually on iOS it's pretty amazing.  Which I guess means that Metal is amazing.

I'm probably going to have to make a test suite which does "do you see a triangle?" "how about now?" "how about now?" "how about now?"  to figure out why one phone doesn't handle something.

So lame, and so many hours.
