### ISSUE TITLE
How do non-Vulkan APIs access VkDeviceMemory?

### ISSUE THREAD

**Issue by DUOLabs333** [KhronosGroup/Vulkan-Docs#2217]
I'm writing a Vulkan driver that streams commands between 2 computers over TCP. One of the major problems is sharing memory. For vkMapMemory, I'm planning to have corresponding buffers on both ends, and synchronize them whenever a synchronization primitive is sent. However, with the external memory extension, it's not clear if MapMemory is called on the OpenGL side, so I can make a buffer I can synchronize. So, how would external device memory be accessed outside Vulkan?

**Comment by spencer-lunarg** [comment]
Vulkan has an entire section on External Memory and Synchronization (Vulkan Guide chapter to help 
https://github.com/KhronosGroup/Vulkan-Guide/blob/main/chapters/extensions/external.adoc)

**Comment by DUOLabs333** [comment]
Oh, ok, I think I get it --- external APIs can't just important a Vulkan memory handle. Vulkan must first export it (which means I can keep a buffer open to sync), and then the API can use it. This is perfect, thank you.

**Comment by spencer-lunarg** [comment]
yes, there are various API calls to go to/from a `VkDeviceMemory`/`VkSemaphore` for various platforms to allow for external use
