### ISSUE TITLE
How to get the memory used by `VK_OBJECT_TYPE_SHADER_MODULE`

### ISSUE THREAD

**Issue by Zydiii** [KhronosGroup/Vulkan-Docs#2218]
[VK_EXT_device_memory_report] @zhangyiwei
Hi, I would like to get the memory used by shadermodule. But when I call createshadermodule/destroyshadermodule, `VK_EXT_device_memory_report` didn't call the callback to get the object of `VK_OBJECT_TYPE_SHADER_MODULE`.
May I ask how to get the device memory used by shader through this extension? Thanks!

**Comment by zhangyiwei** [comment]
As Ralph has replied, associated pipeline objects are the ones to check. Shader compilation happens at pipeline creation time. Compiled shader binaries are the ones that consume _device memory_ (e.g. a drm gem bo).

If just checking cpu allocations used upon shader module creation, `VkAllocationCallbacks` is the one to hook up.

Let me know if you have more questions ; )

**Comment by Zydiii** [comment]
Thank you for your answers. It‘s very helpful to me, thanks!
