### ISSUE TITLE
[Roadmap Feedback] Example "Roadmap Feedback" issue

### ISSUE THREAD

**Issue by marty-johnson59** [KhronosGroup/Vulkan-Docs#2220]
## Problem statement: 

Can Vulkan evolve to enable HPC use cases so I can run the full range of compute solutions (including OpenCL, SYCL, etc.) across all Vulkan platforms?

## Use Case Example(s): 

I need to target multiple end-user platforms with my HPC compute application which is written with C++ kernel languages (OpenCL, SYCL) in order to deploy on both DT and mobile platforms. There are currently no solutions for this beyond more limited programming modes (HLSL, GLSL, etc.)

## (Optional) Suggested Solution(s) (via opening an MR on vulkan-docs repo and creating a Proposal Document) : 

Reduce delta between SPIR-V compute and graphics capabilities so Vulkan scan support what’s needed for HPC use cases

**Comment by oddhack** [comment]
@marty-johnson59 is this just for testing? Does not seem like it belongs on the Wednesday call agenda.

**Comment by marty-johnson59** [comment]
Correct.  We're asking the community for input on future roadmaps for Vulkan and wanted an example for reference (this issues is referenced from our posts on social).  We can leave this open for a few weeks and then close.  We may (hopefully) be getting a few of these kinds of issues opened for the WG to consider - but these won't be topics for the maintenance call.

**Comment by oddhack** [comment]
@marty-johnson59 should we close this now, with several actual RF issues files?

N.b. I added the "Roadmap Feedback" Label per last week's telecon. Going forward I will try not to add these to the Maintenance telecon and make sure they're labelled, so DevRel can find them more easily.
