### ISSUE TITLE
Some redundant shader VUIDs

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-Docs#2222]
VUID-VkPipelineShaderStageCreateInfo-stage-00712 is redundant to VUID-CullDistance-CullDistance-04197, and is also incomplete (it's missing the mesh shader stages).

VUID-VkPipelineShaderStageCreateInfo-stage-00718 is redundant to VUID-CullDistance-CullDistance-04198.

**Comment by spencer-lunarg** [comment]
I agree, we validate `04197`/`04198` in `spirv-val` and don't check `00712`/`00718` at all (because it would hit the others first)

**Comment by oddhack** [comment]
This should be fixed in the 1.3.265 spec update.
