### ISSUE TITLE
VK_AMDX_shader_queue proposal: VkDispatchGraphCountInfoAMDX struct is defined twice in a row in section 3.1.3

### ISSUE THREAD

**Issue by Hugobros3** [KhronosGroup/Vulkan-Docs#2225]
https://github.com/KhronosGroup/Vulkan-Docs/blob/886f6e05a829ec377860c9fa5148299f26bf249c/proposals/VK_AMDX_shader_enqueue.adoc?plain=1#L174

`VkDispatchGraphCountInfoAMDX` is defined twice in that code block, in the exact same way, looks like an oversight.

@Tobski

**Comment by oddhack** [comment]
Assigned to @tobski as vendor extension issue.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.265 spec update.
