### ISSUE TITLE
Byte mappings table for A8 seems wrong (Maintenance5)

### ISSUE THREAD

**Issue by K0bin** [KhronosGroup/Vulkan-Docs#2234]
The entry for A8_UNORM in the byte mappings table seems wrong.

![image](https://github.com/KhronosGroup/Vulkan-Docs/assets/1131720/348b58fb-16b0-40d8-8cd4-fc655d2e1c8b)

This suggests that it's a 4 byte format and the first 3 bytes are 0.
That doesn't match the description of the format:
> • VK_FORMAT_A8_UNORM_KHR specifies a one-component, 8-bit unsigned normalized format that has a
single 8-bit A component

Instead it should basically look like the R8 entry, except with the alpha component at byte 0.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.268 spec update.
