### ISSUE TITLE
Command buffer recording

### ISSUE THREAD

**Issue by faserg1** [KhronosGroup/Vulkan-Docs#224]
The description of one of the members:

> `pInheritanceInfo` is a pointer to a `VkCommandBufferInheritanceInfo` structure, which is used if commandBuffer is a secondary command buffer. If this is a primary command buffer, then this value is ignored.

So, the pointer will be ignored, if recording primary command buffer. But in the description of `queryFlags` I see this:

> If this is a primary command buffer, then this value is ignored.

So, that `pInheritanceInfo` will not be ignored in the primary command buffer or I don't understand something?

Also, in VkCommandBufferInheritanceInfo no description for `sType` & `pNext`.

**Comment by krOoze** [comment]
Yes, and I see some more:

- The Valid Usage section does not acknowledge the value ignoring either
- The restrictions on `renderPass` is outside Valid Usage section
- `subpass` is not restricted in Valid Usage section
- There is "if it was allocated with the X", though the X flag is supplied to begin, not allocate
- The Valid Usage section of `VkCommandBufferBeginInfo` restricts (what should perhaps be in Valid Usage section of) `VkCommandBufferInheritanceInfo`

**Comment by oddhack** [comment]
The original issue should be fixed in the 1.0.29 spec update. The remaining issues have probably been dealt with as well according to some internal commentary by @TobiasHector, whom I've asked to respond here to try and close this out.

**Comment by TobiasHector** [comment]
@oddhack It looks like we missed the sType and pNext descriptions for VkCommandBufferInheritanceInfo?

As for most of @krOoze's points:

> * The Valid Usage section does not acknowledge the value ignoring either

vkBeginCommandBuffer's validity states:
"If pname:commandBuffer is a secondary command buffer, the pname:pInheritanceInfo member of pname:pBeginInfo must: be a valid sname:VkCommandBufferInheritanceInfo structure"
Which covers the fact that it's only necessary to be valid when it's a secondary.

> * The restrictions on renderPass is outside Valid Usage section
* subpass is not restricted in Valid Usage section

These are both there - just not where you might expect: See vkCmdExecuteCommands. Remember that valid usage statements are supposed to be statements that operate on COMPLETE information, so you can't say "if this is going to be used in a render pass it must..." in the valid usage section. We could say that in the main spec text if it's useful to point out though?

> * The Valid Usage section of VkCommandBufferBeginInfo restricts (what should perhaps be in Valid Usage section of) VkCommandBufferInheritanceInfo

Again, this is the right place for this, even if it doesn't seem intuitive from reading the spec. Complete information is only available in VkCommandBufferBeginInfo.


I don't remember what your other point refers to anymore (maybe it got fixed?):

> There is "if it was allocated with the X", though the X flag is supplied to Begin(), not Allocate()

**Comment by krOoze** [comment]
ad 4) Was fixed in 1.0.24

ad 1), 2), 3), 5) I see (indeed all restrictions seems to be there). Apparently May me missed something &mdash; what an ignorant guy that! :smile:.

Similarly to 3) in #375 should perhaps not mention `renderPass` parameter specifically in `subpass` parameter description.

> We could say that in the main spec text if it's useful to point out though?

Generally, might be nice to mention such things. Perhaps useful for future maintanace too. But I understand you have higher priority issues at hand.

> See vkCmdExecuteCommands

Now you mention it I would object to the "recorded with"(is `begin()` "recorded"?) and missing mention of  `VkCommandBufferInheritanceInfo` structure and the `renderPass` parameter name in the `vkCmdExecuteCommands` VU.

So for my part original issues are resolved.

**Comment by TobiasHector** [comment]
> Now you mention it I would object to the "recorded with"(is begin() "recorded"?) and missing mention of VkCommandBufferInheritanceInfo structure and the renderPass parameter name in the vkCmdExecuteCommands VU.

Begin is supposed to === start of recording. If you don't think this is clear I'd suggest another bug because this is littered throughout the VU and other bits of the spec...

**Comment by oddhack** [comment]
I'll fix the sType/pNext thing in this week's update. Hopefully we can just close out this bug now.

**Comment by krOoze** [comment]
@TobiasHector Will do.
@oddhack Close away then.
