### ISSUE TITLE
Can an implementation change a VkAllocationCallbacks's pUserData after it has been defined?

### ISSUE THREAD

**Issue by DUOLabs333** [KhronosGroup/Vulkan-Docs#2241]
Let's say I have Callbacks structure `callback`. Let's say `callback->pUserData=d1` when it is passed into a command. Can an implementation later do `callback->pUserData=d2`, then call `callback->pfnAllocation` with `d2`?

**Comment by r-potter** [comment]
If you are asking if the *application* can change the value of `pUserData` between uses of the allocator, then the answer is yes:

> pUserData is a value to be interpreted by the implementation of the callbacks.
> When any of the callbacks in sname:VkAllocationCallbacks are called, the Vulkan implementation will pass this value as the first parameter to the callback.
>  This value can: vary each time an allocator is passed into a command, even when the same object takes an allocator in multiple commands.

**Comment by DUOLabs333** [comment]
I was asking whether an Vulkan implementation (for example, MoltenVK) can change it.

**Comment by r-potter** [comment]
Then no. The implementation is supposed to call `pfnAllocation` with the value that `pUserData` had when the `VkAllocationCallbacks` structure was passed to the API call.

**Comment by DUOLabs333** [comment]
Thank you for the clarification --- it wasn't clear from the documentation.
