### ISSUE TITLE
`VkDescriptorSetAllocateInfo` has a VUID with no number/tag

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-Docs#2244]
The VUID that starts with
> If `pSetLayouts`[i] was created with an element of `pBindingFlags` [...]

Is missing a VUID number.

**Comment by spencer-lunarg** [comment]
This was discovered already and @oddhack is going to have a fix to the process that caused this and VUID for the next header update

**Comment by oddhack** [comment]
This should be fixed in the 1.3.268 spec update.
