### ISSUE TITLE
Clarify the need for VkOpticalFlowImageFormatInfoNV in VkImageCreateInfo in the example

### ISSUE THREAD

**Issue by space2** [KhronosGroup/Vulkan-Docs#2249]
[VK_NV_optical_flow] @crohde

I tried to follow the example to use the nVidia optical flow extension, but got garbage data out, until I realised that when creating the images, the VkOpticalFlowImageFormatInfoNV struct must be used as an extension to VkImageCreateInfo.
Might be worth mentioning this in the example.

**Comment by oddhack** [comment]
@jeffbolznv @ewerness-nv OP tried to assign to Carsten, but they are not a member of KhronosGroup or the Vulkan team, AFAICT - if they're still at NV could you verify that @crohde is their handle (or what their handle is) so I can send an invite? In the meantime, passing over to you as a vendor issue.

**Comment by crohdewm** [comment]
You can assign it to me (@crohdewm)

**Comment by crohdewm** [comment]
@space2 I'm not exactly sure what you're referring to.

In the example there is:

VkOpticalFlowImageFormatInfoNV ofFormatInfo = {
VK_STRUCTURE_TYPE_OPTICAL_FLOW_IMAGE_FORMAT_INFO_NV };
ofFormatInfo.usage = VK_OPTICAL_FLOW_USAGE_INPUT_BIT_NV;

...

VkImageCreateInfo imageCreateInfo = { VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO,
&ofFormatInfo };
...

That means that VkOpticalFlowImageFormatInfoNV is chained to VkImageCreateInfo.

**Comment by space2** [comment]
I'm sorry, my bad... I missed that (I thought ofFormatInfo was used only in vkGetPhysicalDeviceOpticalFlowImageFormatsNV)
