### ISSUE TITLE
timeline semaphore lifetime

### ISSUE THREAD

**Issue by konstantinegorov** [KhronosGroup/Vulkan-Docs#2250]
Can I destroy a timeline semaphore immediately after waiting for it?

```
vkQueueSubmit(signal: semaphore);

vkWaitSemaphores(semaphore);

vkDestroySemaphore(semaphore);
```

Or should I use a fence to determine if I can destroy the semaphore or not?

```
vkQueueSubmit(signal: semaphore, fence)

vkWaitForFences(fence)

vkDestroySemaphore(semaphore)
```

**Comment by krOoze** [comment]
`VUID-vkDestroySemaphore-semaphore-01137` states:

All submitted batches that refer to semaphore **must** have completed execution

Successful `vkWaitSemaphores` implies that batches it refers to in `VkSemaphoreWaitInfo` have completed execution, does it not?

**Comment by HansKristian-Work** [comment]
> Can I destroy a timeline semaphore immediately after waiting for it?

Yes. Just be careful if you're waiting on timeline semaphore A and destroy semaphore B. If A and B were signalled in the same VkSubmitInfo batch, they are signalled out of order. Split into separate batches to make that case well defined.
