### ISSUE TITLE
Framebuffer-framebuffer compatibility not described

### ISSUE THREAD

**Issue by chrisforbes** [KhronosGroup/Vulkan-Docs#226]
Valid usage for `vkCmdExecuteCommands` says:

> If vkCmdExecuteCommands is being called within a render pass instance, and any given element of pCommandBuffers was recorded with VkCommandBufferInheritanceInfo::framebuffer not equal to VK_NULL_HANDLE, that VkFramebuffer must be compatible with the VkFramebuffer used in the current render pass instance

Nowhere is it described what it means for a framebuffer to be compatible with another framebuffer. I assume that the intent is that the secondary command buffer's framebuffer, if specified, should compatible with the renderpass used in the current renderpass instance, as per 7.2 ?

CV implements this as requiring the handles be equal, if the secondary command buffer specifies a framebuffer -- which doesn't sound like the right thing.

**Comment by krOoze** [comment]
[Render pass compatibility](https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#renderpass-compatibility):

> A framebuffer is compatible with a render pass if it was created using the same render pass or a compatible render pass.

**Comment by oddhack** [comment]
@chrisforbes, does @krOoze's response address the issue for you, or do you think spec changes are still needed?

**Comment by chrisforbes** [comment]
@oddhack I think the spec rule is still iffy. It does appear that it's redundant with the other constraints. If that's the case, can we remove it, or adjust it to be a note? I'm just trying to make sure we end up with validation code that's clearly mappable to spec language, and does exactly the right thing.

**Comment by chrisforbes** [comment]
@oddhack After thinking about this a bit more, I don't think the interpretation above is correct.

The framebuffer provided as part of `BeginCommandBuffer` is a hint:

> framebuffer refers to the VkFramebuffer object that the VkCommandBuffer will be rendering to if it was allocated with the VK_COMMAND_BUFFER_USAGE_RENDER_PASS_CONTINUE_BIT set. It can be VK_NULL_HANDLE if the framebuffer is not known.
>
>[Note]	Note
Specifying the exact framebuffer that the secondary command buffer will be executed with may result in better performance at command buffer execution time.

Compatibility via renderpasses as above is an obvious minimum bar-- but is `CmdExecuteCommands` trying to require something stronger -- that is, if a framebuffer is provided as a hint, it has to be a /good/ hint? If not, in the case where a framebuffer /is/ provided to `BeginCommandBuffer`, the implementation needs to record /both/ a general version, and a specialized version taking advantage of the framebuffer information?

**Comment by krOoze** [comment]
I don't follow. Can you elaborate more?

not correct, how?

require something stronger than what? `CmdExecuteCommands()` if I am not mistaken, is the only thing that consumes secondary buffers and all of that seems to be it's requirements directly or indirectly.

**Comment by chrisforbes** [comment]
@krOoze @oddhack Suppose I record a secondary command buffer, providing a framebuffer. The implementation takes advantage of that to produce better hw commands in some way (looks at the dimensions, looks into the ImageViews, etc).

Suppose I then record `CmdExecuteCommands` into a primary command buffer, whose current renderpass instance uses a different framebuffer -- compatible with the same renderpass, but different in every other way, such that any specialization done in the secondary command buffer recording would be invalid -- is that intended to be acceptable?

It seems possible that the intent of this valid usage rule is to limit that.

If that's the case, then there needs to be a definition of framebuffer-framebuffer compatibility that guarantees any framebuffer-derived assumptions in the secondary command buffer recording actually hold.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.16 spec update. The discussion got kinda complex, feel free to reopen/open a new issue if something was missed.
