### ISSUE TITLE
Conflicting documation for VkCudaLaunchInfoNV::pParams

### ISSUE THREAD

**Issue by expipiplus1** [KhronosGroup/Vulkan-Docs#2262]
Distinct from https://github.com/KhronosGroup/Vulkan-Docs/issues/2261

The spec states both: 

- pParams is a pointer to an array of paramCount pointers, corresponding to the arguments of function
- If paramCount is not 0, and pParams is not NULL, pParams must be a valid pointer to an array of paramCount bytes

This is caused by the `optional=true` on `pParams`, which indicates that despite a non-zero `paramCount` value, `pParams` may still be null.

(this also applies to `pExtras`)

**Comment by tlorach** [comment]
removing  optional=true for pParam sounds the right choice. 
Now, I it should be valid that paramCount = 0 and pParams = NULL ... in other words, pParam can only be NULL if paramCount = 0
