### ISSUE TITLE
Does creating VkShaderEXT with VK_SHADER_CODE_TYPE_BINARY_EXT require equivalent VkShaderCreateInfoEXT?

### ISSUE THREAD

**Issue by qbojj** [KhronosGroup/Vulkan-Docs#2273]
After reading the Docs I haven't found any information if creating `VkShaderEXT` with `VK_SHADER_CODE_TYPE_BINARY_EXT` require equivalent `VkShaderCreateInfoEXT`.

The only VUs about `VK_SHADER_CODE_TYPE_BINARY_EXT` are that `pCode` must be aligned to 16 bytes.

IMO:
- in `VkShaderCreateInfoEXT`:
  - If `codeType` is `VK_SHADER_CODE_TYPE_BINARY_EXT`, all members other than `codeType`, `codeSize`, and `pCode` must be equivalent to those from `VkShaderCreateInfoEXT` used to create `VkShaderEXT` from which `pCode` was acquired.

- in `vkCreateShadersEXT`:
  - with questionable wording: 
    If the `flags` member of any element of `pCreateInfos` includes `VK_SHADER_CREATE_LINK_STAGE_BIT_EXT` and its `codeType` is `VK_SHADER_CODE_TYPE_BINARY_EXT`, the element of `pCreateInfos` whose `flags` member includes `VK_SHADER_LINK_STAGE_BIT_EXT` must be equivalent to element with same `stage` member  of `pCreateInfos` from which `VkShaderEXT` was created.

  - maybe:
    If the `flags` member of any element of `pCreateInfos` includes `VK_SHADER_CREATE_LINK_STAGE_BIT_EXT` and its `codeType` is `VK_SHADER_CODE_TYPE_BINARY_EXT`, the `codeType` member of all other elements of `pCreateInfos` whose `flags` member includes `VK_SHADER_LINK_STAGE_BIT_EXT` must be `VK_SHADER_CODE_TYPE_BINARY_EXT`.

**Comment by pdaniell-nv** [comment]
I agree with your assumption that the parameters need to match between when the original shader object was created and when it later used to create a shader object from a binary. If there are mismatches in the descriptor set layouts, push constants, or specialization data the implementation may return VK_ERROR_INCOMPATIBLE_SHADER_BINARY_EXT.

**Comment by qbojj** [comment]
But `VK_ERROR_INCOMPATIBLE_SHADER_BINARY_EXT` error is defined as: "The provided binary shader code is not compatible with this device."

But if the specified binary is compatible with the device (from UUID+version) wouldn't returning it be invalid?

**Comment by pdaniell-nv** [comment]
You're right that's what the spec for `VK_ERROR_INCOMPATIBLE_SHADER_BINARY_EXT` currently says, but our implementation will use `VK_ERROR_INCOMPATIBLE_SHADER_BINARY_EXT` to also indicate the binary is incompatible with the descriptor set layouts, push constants, or specialization data. I think the next step would be to tweak the definition of `VK_ERROR_INCOMPATIBLE_SHADER_BINARY_EXT` to cover this, and to also be clear what parameters of `VkShaderCreateInfoEXT` need to match for the binary to stay compatible.
