### ISSUE TITLE
Does dynamic rendering allow swizzled attachments?

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-Docs#2275]
For rendering with a render pass object, the spec is clear. Image views used as attachments must be identity swizzled:
> VUID-VkFramebufferCreateInfo-pAttachments-00884
> If `flags` does not include `VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT`, each element of `pAttachments` must have been created with the identity swizzle

> VUID-VkRenderPassAttachmentBeginInfo-pAttachments-03219
> Each element of `pAttachments` must have been created with the identity swizzle

But I noticed that there are no VUIDs with that requirement for `vkCmdBeginRendering` or its parameter structs. This feels like an accidental omission in the spec to me. If it's not an omission, I wonder what makes render passes vs dynamic rendering different in this regard?

**Comment by Tobski** [comment]
Thanks for raising this! This is functionally useless since the swizzle only applies to sampling operations, but it's not tested and wasn't really intended, so we'll add VUs for this.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.274 spec update.
