### ISSUE TITLE
For mesh shader outputs, what is "dependent on `ViewIndex`"?

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-Docs#2287]
The section "Mesh Shader Output" has a formula near the end for calculating the total size of the output variables of a mesh shader. It mentions variables that are or are not "dependent on `ViewIndex`". But `ViewIndex` is specified only on input variables, while this concerns output variables. What is meant here with being "dependent"?

The NV version of mesh shaders includes a `PerViewNV` decoration, which perhaps is what is indicated here. But the EXT version has no such decoration; does that mean that no variables are dependent on `ViewIndex`, or are you meant to figure it out some other way?

**Comment by kthangudu-nv** [comment]
When using a multiview renderpass, any output that is calculated as a function of `ViewIndex` is view dependent (or per-view). Since each view dependent  output variable consumes on output per enabled view, the formula is accounting for them separately.

**Comment by oddhack** [comment]
@Rua if @kthangudu-nv answered your question, please close this.
