### ISSUE TITLE
VK_KHR_swapchain page has bad markup text

### ISSUE THREAD

**Issue by Wallbraker** [KhronosGroup/Vulkan-Docs#2288]
The page https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_swapchain.html looks like the below, which doesn't seem right.

![image](https://github.com/KhronosGroup/Vulkan-Docs/assets/57528/a0e60fa2-da9d-4c7d-bb71-6ebac4a1ad58)

**Comment by SaschaWillems** [comment]
This seems to affect all extensions with an "Interacts with" bullet point. See also https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_video_encode_queue.html, https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_video_decode_queue.html, https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_NV_linear_color_attachment.html and probably some more.

**Comment by oddhack** [comment]
This will be fixed in the next spec update - I've already committed an internal fix.

**Comment by oddhack** [comment]
This is fixed in the 1.3.275 spec update.

**Comment by Wallbraker** [comment]
Thanks
