### ISSUE TITLE
Question about VK fragment_shader_interlock ordering

### ISSUE THREAD

**Issue by wuweiwhu** [KhronosGroup/Vulkan-Docs#2289]
[VK_EXT_fragment_shader_interlock] @pdaniell-nv
Hi daniell,
I have a question about vulkan fragment shader interlock,
Vulkan/Spirv spec says "guarantees that the critical section for multiple shader invocations with "overlapping" coverage will be executed in primitive order, as defined by the Primitive Order section of the Vulkan specification."
I also noticed that D3D spec says: "guaranteeing order of UAV accesses for any pair of overlapping Pixel Shader invocations. “Overlapping” means that the invocations are generated by the same Draw* API call and share the same pixel coordinate when in pixel-frequency execution mode, and same pixel and sample coordinate in sample-frequency mode."
Since "Primitive Order" also includes ordering defined by draw submission, 
does it mean D3D only guarantees ordering within a single draw call while Vulkan guarantees ordering cross draw call boundaries besides ordering within a single draw?

**Comment by pdaniell-nv** [comment]
I'm sure D3D has well defined primitive ordering between draw calls, so the behavior of Vulkan and D3D should be the same. I'm not familiar with the D3D spec so I can't comment where this is specified. Both D3D and Vulkan run on the same hardware where this ordering is implemented.

**Comment by oddhack** [comment]
@wuweiwhu if this addressed your question, please close the issue.
