### ISSUE TITLE
How many locations/components does a built-in variable consume?

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-Docs#2291]
The spec section "15.1.4. Location Assignment" contains a table of the limits of the number of locations available for each shader stage. It states that both user-defined and built-in variables count towards this limit. However, the start of the section states
> This section describes `Location` assignments for user-defined variables and how many `Location` slots are consumed by a given user-variable type.

So this begs the question, if those limits are expressed as location/component counts, and this section only says how to calculate that for user-defined variables, how do you calculate it for built-in variables?

**Comment by spencer-lunarg** [comment]
- Built-in can't have explicit `Location` assigned to them (`VUID-StandaloneSpirv-Location-04915`)
- There must be no more than one built-in interface block per shader per interface

so from these two, you can take the built-in block and calculate the number of bytes it consumes and using the `Location Assignment` part of the spec, you can find this information as if it was any normal user-defined variables with a `Location = 0` start

**Comment by spencer-lunarg** [comment]
there is a `GetBuiltinComponents` function in the Validation Layers as reference as well if you want to take a look

**Comment by Rua** [comment]
I just noticed that VUID-RuntimeSpirv-Location-06272, the VUID that is actually supposed to ensure those limits are followed, does not take built-ins into account. Oops?
