### ISSUE TITLE
Question about `vkCmdUpdateBuffer`

### ISSUE THREAD

**Issue by evyatark2** [KhronosGroup/Vulkan-Docs#2294]
Why does this command have a hard-bound of 65536 bytes? Wouldn't it be more flexible to have a `VkPhysicalDeviceLimits::maxBufferUpdateSize` limit that has a minimum requirement of 65536 and let implementations go up from there (or even have no limit by setting it to `0`/`UINT32_MAX`)?

As an example, I used this command with more than 64KiB using Mesa and it seems that it accepts it without truncating data although the validation layer obviously still reports this as an error (I haven't read the source code so maybe it was just plain luck?).

**Comment by jeffbolznv** [comment]
The working group had wanted to discourage use of this for large updates, and vkCmdCopyBuffer should be used instead. The data has to be copied into the command buffer and this potentially puts stress on the command memory allocator. The application can theoretically loop and call it many times to emulate large updates, but it would be better for the app to prepare the data in buffer memory and use vkCmdCopyBuffer to copy it without another memcpy of the data. There's a note about this in the spec:

```
Buffer updates performed with vkCmdUpdateBuffer first copy the data into command buffer memory when the command is recorded (which requires additional storage and may incur an additional allocation), and then copy the data from the command buffer into dstBuffer when the command is executed on a device.

The additional cost of this functionality compared to [buffer to buffer copies](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#copies-buffers) means it is only recommended for very small amounts of data, and is why it is limited to only 65536 bytes.

Applications can work around this by issuing multiple vkCmdUpdateBuffer commands to different ranges of the same buffer, but it is strongly recommended that they should not.
```

**Comment by evyatark2** [comment]
Yeah, I have read this note, but I guess I didn't interpret it as a discouragement to use `vkCmdUpdateBuffer` for large update.

Thanks!
