### ISSUE TITLE
DescriptorIndexingFeatures.descriptorBindingUniformBufferUpdateAfterBind is 

### ISSUE THREAD

**Issue by runner0353** [KhronosGroup/Vulkan-Docs#2301]
This feature is not supported in Nvidia 1060 driver

**Comment by oddhack** [comment]
@pdaniell-nv can you comment for NVIDIA?

**Comment by oddhack** [comment]
@runner0353 also, like your other issue, this sounds like basically a feature request for NVIDIA, which is not something we can do anything about in this repo.

**Comment by pdaniell-nv** [comment]
This feature is available in Turing+ GPUs (GTX 16xx+ and RTX 20xx+), but not GTX 1060, which is a Pascal GPU.
