### ISSUE TITLE
GTX1060 not support Device Features :: RayQuery 

### ISSUE THREAD

**Issue by runner0353** [KhronosGroup/Vulkan-Docs#2302]
Validation error:
SPIR-V Capability RayQueryKHR was declared, but one of the following requirements is required (VkPhysicalDeviceRayQueryFeaturesKHR::rayQuery)

**Comment by oddhack** [comment]
@runner0353 as a general matter, problems with an IHV's driver should be taken up on the appropriate IHV support channels. This repo is intended for issues with the Vulkan specification, not the implementations arising from the spec. So if you can speak to how the specification is at fault for what at least superficially appears to be an implementation choice of which features to expose, that would be helpful.

**Comment by runner0353** [comment]
Thanks for reminding, The rayQuerySupportedFeatures.rayQuery
![RayQuery](https://github.com/KhronosGroup/Vulkan-Docs/assets/36179001/f0e863a8-426c-40ff-a873-ccdf8de97396)
 is not support in nvidia 1060 driver
