### ISSUE TITLE
Does Windows not support VK_EXT_filter_cubic

### ISSUE THREAD

**Issue by L-Aidan** [KhronosGroup/Vulkan-Docs#2313]
I tried to search VK_EXT_filter_cubic in https://vulkan.gpuinfo.org/listdevicescoverage.phpplatform=windows&extension=VK_EXT_filter_cubic, 
and found it is not supported in Windows device. My code also makes errors if I use VK_EXT_filter_cubic.
Is it really not supported? Why and when it will be supported?
Looking forward to your reply.
![image](https://github.com/KhronosGroup/Vulkan-Docs/assets/61683410/bda840fc-2d00-4cc9-a489-0d31d6c0e5c6)

**Comment by oddhack** [comment]
@Rua that's right. @L-Aidan it is a question for vendors as to when / whether they will support the extension, so please close this - Khronos has no ability to require vendors support this extension.

**Comment by L-Aidan** [comment]
Thank you!
