### ISSUE TITLE
VK_BUFFER_USAGE_2_VIDEO_ENCODE_{SRC|DST}_BIT_KHR still in beta-extension guard

### ISSUE THREAD

**Issue by qbojj** [KhronosGroup/Vulkan-Docs#2314]
`VK_BUFFER_USAGE_2_VIDEO_ENCODE_{SRC|DST}_BIT_KHR` are still in beta-extension guard even when its extension `VK_KHR_video_encode_queue` is no longer beta.

Also its "1" - counterparts are not it those guards.

It is probably vk.xml defect so I am posting here.

**Comment by oddhack** [comment]
The current headers posted in the Vulkan-Headers repository don't have this issue AFAICT. If you're using the headers from another source it probably has not yet been updated to match, and that's outside our control here.

Please close, unless you can verify the problem behavior is from a source we have control over.

**Comment by qbojj** [comment]
https://github.com/KhronosGroup/Vulkan-Headers/blob/31aa7f634b052d87ede4664053e85f3f4d1d50d3/include/vulkan/vulkan_core.h#L11160-L11165

https://github.com/KhronosGroup/Vulkan-Headers/blob/31aa7f634b052d87ede4664053e85f3f4d1d50d3/include/vulkan/vulkan_enums.hpp#L7000-L7003

And from the XML:
```xml
<require depends="VK_KHR_video_encode_queue">
    <enum bitpos="15" extends="VkBufferUsageFlagBits2KHR"    name="VK_BUFFER_USAGE_2_VIDEO_ENCODE_DST_BIT_KHR" protect="VK_ENABLE_BETA_EXTENSIONS"/>
    <enum bitpos="16" extends="VkBufferUsageFlagBits2KHR"    name="VK_BUFFER_USAGE_2_VIDEO_ENCODE_SRC_BIT_KHR" protect="VK_ENABLE_BETA_EXTENSIONS"/>
</require>
```

**Comment by oddhack** [comment]
Thanks. I was just looking at vulkan_beta.h itself. Will fix in the near future.

**Comment by oddhack** [comment]
This should be fixed in the current spec update.
