### ISSUE TITLE
Blog about synchronization mentions vkWaitEvents

### ISSUE THREAD

**Issue by jeroenbakker-atmind** [KhronosGroup/Vulkan-Docs#2315]
Unsure this is the correct location to report this. So please close/redirect me if there is a better location.

https://www.khronos.org/blog/understanding-vulkan-synchronization mentions `vkWaitEvents`. I believe this might be a typo. I was expecting `vkCmdWaitEvents`.

**Comment by janharaldfredriksen-arm** [comment]
Hi,
Yes, that's a typo. I'll see if we can get it updated.

**Comment by janharaldfredriksen-arm** [comment]
@jeroenbakker-atmind the blog post has now been updated to correct this typo. Thanks for spotting and reporting it!

Resolving issue.
