### ISSUE TITLE
Missing VUIDs for `stride` in VK_EXT_draw_multi commands

### ISSUE THREAD

**Issue by marc0246** [KhronosGroup/Vulkan-Docs#2323]
There seem to be missing VUIDs:
- For `vkCmdDrawMulti`, saying that the stride must be at least 8.
- For `vkCmdDrawMultiIndexed`, saying that the stride must be at least 12.

This seems like an oversight because there's no meaningful way to use these commands with a stride argument like this, and it's also inconsistent with other commands that take a stride.

**Comment by spencer-lunarg** [comment]
agreed in Working Group meeting this seems like an oversight, going to make an internal spec PR for these (and will follow-up with adding them to the validation layers after)

thanks for reporting these

**Comment by oddhack** [comment]
This should be fixed in the 1.3.281 spec update.
