### ISSUE TITLE
Missing Valid usage in vkBeginRenderpass

### ISSUE THREAD

**Issue by ratchetfreak** [KhronosGroup/Vulkan-Docs#233]
https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#vkCmdBeginRenderPass

The valid usage is missing a bullet that would make the layout of the attachment image match the corresponding initialLayout of the renderpass attachment.

If I match the language of the other points then it would be something like:

* If any of the `initialLayout` members of the `VkAttachmentDescription` structures specified when creating the render pass specified in the renderPass member of `pRenderPassBegin` is not `VK_IMAGE_LAYOUT_UNDEFINED` or `VK_IMAGE_LAYOUT_PREINITIALIZED` then it must: be equal to the current layout of the corresponding attachment image of the framebuffer specified in the framebuffer member of `pRenderPassBegin`.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.17 spec update.
