### ISSUE TITLE
No changelog entry for 1.3.280

### ISSUE THREAD

**Issue by qbojj** [KhronosGroup/Vulkan-Docs#2330]
As stated in the title there is no changelog entry for 1.3.280.

**Comment by oddhack** [comment]
Thanks. I changed the formatting of the file slightly to improve asciidoc formatting, and that defeated the auto-inclusion of the latest release notes. Will fix it shortly, although I'm going to leave the tag pointing at the current commit as changing it could have disruptive effects on LunarG downstream repos.
