### ISSUE TITLE
Request: AV1 encode extension planned (VK_KHR_video_encode_h265)?

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/Vulkan-Docs#2335]
Hi,
in late 2022 as VK decode exts were released as stable it was told in the press release to expect by late 2023 both final encode extensions and also AV1 decode ext..
Both have been released now.. so seems only thing missing now in encode vs decode is AV1 encode support..
but AV1 encode hasn't been mentioned is coming in late 2024 in any of Vulkan encode stable release press release or AV1 decode press release..
and since it's supported on all recent Intel,AMD, Nvidia GPUs and upcoming Qualcomm SOCs just questioning if it's planned for this year or early 2025..
thanks..

**Comment by aabdelkh** [comment]
Yes, Video TSG is actively working on the AV1 encode extension.  The goal is to release this extension later this year.  Thank you for your patience and interest in Vulkan Video!

**Comment by oscarbg** [comment]
thanks for sharing the good news!
