### ISSUE TITLE
Some questions on VK_AMDX_shader_enqueue extension..

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/Vulkan-Docs#2336]
[VK_AMDX_shader_enqueue] @tobski
some questions on this exciting VK_AMDX_shader_enqueue extension:

1) at first sight, seeing the spec, seemed no GLSL support so no glslang support but now from sample I see ext is supported in shading languages (both GLSL and HLSL) via GL_EXT_spirv_intrinsics ext so both glslang and DXC are supported.. question is if stable spec is planned to include a GLSL EXT? (GL_AMD_shader_enqueue?) (and of course glslang support) or will remain using GL_EXT_spirv_intrinsics..

2) Seeing new D3D12 work graphs going stable and AMD demoing "mesh nodes" which support mesh shaders as leaf nodes of work graphs.. does this extension support "mesh nodes" already? seems not as it mentions:
>Shaders in pStages must be in the GLCompute execution model

but anyway also seen:
>For compute nodes, can the input payload be modified?

https://github.com/KhronosGroup/Vulkan-Docs/blob/main/proposals/VK_AMDX_shader_enqueue.adoc#41-resolved-for-compute-nodes-can-the-input-payload-be-modified-if-so-what-sees-that-modification
so clearly graphics nodes are in mind also..

D3D12 mesh nodes are coming this year seems.. so hoping also to a revision of AMDX ext, supporting mesh shader nodes in the same time? which brings to next question..

3) can share 8 months since release how far approx. EXT is from becoming stable (either as AMD,EXT or KHR)?

thanks..

**Comment by Tobski** [comment]
Hi Oscar,

1. There's currently no plans for a GLSL extension; we're focussed on HLSL as the machinery for work graphs is already being developed there.
2. The current iteration only supports compute, originally we had intended to support draw nodes as in the early DX spec, but they have, for now, been omitted.
3. I cannot provide any timeframes for a stable spec, but we are still actively developing it.

**Comment by oscarbg** [comment]
many thanks @Tobski for answering!!
only comment remaining in my mind is, if focused on HLSL suuport only, hope by final release, AMD can submit DXC support for generating SPIR-V (using SPV_AMD_shader_enqueue) from "standard DX12 HLSL work graphs shaders" using only the "-spirv" DXC flag and not needing the current EXT_spirv_intrinsics extension mechanism..

**Comment by Tobski** [comment]
Hi @oscarbg, to answer both questions at once: We provided a single preview driver, and I would expect in the future that we ship further drivers with updated support; but I can't comment on how or when that might happen.

**Comment by Tobski** [comment]
Yes: https://gpuopen.com/learn/gpu-workgraphs-mesh-nodes-vulkan/
