### ISSUE TITLE
Windows ARM64 Vulkan SDK release mid year?

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/Vulkan-Docs#2339]
Hi,
seems Qualcomm will ship (Adreno) Vulkan drivers on Windows ARM64 for SOCS based on Elite X onwards..
so there is Vulkan support/drivers on Windows on ARM64 platform, so asking for "native" Windows ARM64 SDK builds..
thanks..

**Comment by Degerz** [comment]
https://developer.qualcomm.com/forums/software/adreno-gpu-sdk?

Above link is likely a better outlet to discuss the topic ...

**Comment by oddhack** [comment]
@KarenGhavam-lunarG is this something we should move to a SDK repo, and if so, which one? It's not actionable here.

**Comment by KarenGhavam-lunarG** [comment]
> @KarenGhavam-lunarG is this something we should move to a SDK repo, and if so, which one? It's not actionable here.

Yes, this issue is in the wrong place. It is an issue for the SDK and should be submitted to the SDK issue tracker at vulkan.lunarg.com

It should be noted there are already issues asking for Windows ARM64 SDK in that issue tracker. The enhancement request is known about.

**Comment by dgkoch** [comment]
Closing in favor of LunarG SDK tracker issue.
