### ISSUE TITLE
VkPhysicalDeviceFeatures specifies shaderFloat64, Int16 and Int64 but not Float16

### ISSUE THREAD

**Issue by Themaister** [KhronosGroup/Vulkan-Docs#234]
I'm not why Float16 is not a physical device feature as SPIR-V has an OpFloat16 capability which does not depend on kernel.

**Comment by krOoze** [comment]
I think chapter A.2. Capabilities apply here:

> The application must not pass a SPIR-V module containing any of the following to vkCreateShaderModule:
- any OpCapability not listed above
- [...]

And Float16 (and Int8) are not listed above. So, it would seem Vulkan (intentionaly or not) doesn't support those at the moment.
