### ISSUE TITLE
rasterizerDiscardEnable disable need to not write to a geometry shader pointsize

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/Vulkan-Docs#2347]
moved from https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5129

Do these VUs still happen when rasterization is disabled (`VkPipelineRasterizationStateCreateInfo::rasterizerDiscardEnable` = `VK_TRUE`) such as when using transform feedback.

![image](https://github.com/KhronosGroup/Vulkan-Docs/assets/115671160/e79ae373-1e3b-48e9-b602-ce456994a31e)

**Comment by oddhack** [comment]
@spencer-lunarg was the resolution that you will document this in a NOTE in the spec?
