### ISSUE TITLE
Dynamic state setting valid usage doesn't mention pipeline

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-Docs#235]
In the various functions that set dynamic state like `vkCmdSetViewport`, the language isn't very explicit about when the function can be used, just says where the viewports come from in the dynamic and non-dynamic cases:

> If the bound pipeline state object was not created with the VK_DYNAMIC_STATE_VIEWPORT dynamic state enabled, viewport transformation parameters are specified using the pViewports member of VkPipelineViewportStateCreateInfo in the pipeline state object. If the pipeline state object was created with the VK_DYNAMIC_STATE_VIEWPORT dynamic state enabled, the viewport transformation parameters are dynamically set and changed with the command

Which someone could mistake for meaning that the dynamic state is ignored when you try to set it, perhaps setting it before binding a dynamic pipeline. Earlier in Chapter 9 right above section 9.1 it is very clear that calling any of these dynamic state setting functions is undefined if the pipeline isn't dynamic in that way:

> Modifying dynamic state that is not set as dynamic by the pipeline state object will lead to undefined results.

I think it'd be useful and not out of place to include some valid usage to each of the `vkCmdSetViewport` and friends, similar to:

> `commandBuffer` must: be in the recording state

something like:

> The currently bound graphics pipeline must: have the `VK_DYNAMIC_STATE_VIEWPORT` state enabled.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.16 spec update.
