### ISSUE TITLE
`VUID-VkMemoryMapInfoKHR-flags-09572` and `VUID-VkMemoryMapInfoKHR-flags-09574` seem needlessly restrictive

### ISSUE THREAD

**Issue by marc0246** [KhronosGroup/Vulkan-Docs#2350]
[`VUID-VkMemoryMapInfoKHR-flags-09572`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkMemoryMapInfoKHR.html#VUID-VkMemoryMapInfoKHR-flags-09572) and [`VUID-VkMemoryMapInfoKHR-flags-09574`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkMemoryMapInfoKHR.html#VUID-VkMemoryMapInfoKHR-flags-09574) only accept `VK_WHOLE_SIZE` and not also the rest of the allocation size like the rest of the APIs that can take `VK_WHOLE_SIZE`. For example, without using the `VK_EXT_map_memory_placed` extension, one can specify the rest of the allocation or `VK_WHOLE_SIZE`. Same applies to `VkMappedMemoryRange`, you can use both the rest of the allocation size or `VK_WHOLE_SIZE`. It feels weird to have this special case only when using this extension. It means that, since we never used and don't intend on using `VK_WHOLE_SIZE`, we are currently special casing this such that the rest of the allocation size is translated to `VK_WHOLE_SIZE`, only when using this extension. That feels rather strange, and I think it would be better if the rest of the allocation size was also permitted natively.

**Comment by spencer-lunarg** [comment]
cc @gfxstrand

**Comment by cubanismo** [comment]
Thanks for the @. I've asked the engineer that implemented this to check.

**Comment by cubanismo** [comment]
We expect this will work fine on our implementation as-is, so fine with us to make the change.
