### ISSUE TITLE
Confusiing wording in docs for VkAttachmentLoadOp

### ISSUE THREAD

**Issue by not-magic** [KhronosGroup/Vulkan-Docs#2353]
The docs for the `VkAttachmentLoadOp` page specify:

```VkAttachmentLoadOp - Specify how contents of an attachment are initialized at the beginning of a subpass```

However the docs in `VkAttachmentDescription` say:

```loadOp is a VkAttachmentLoadOp value specifying how the contents of color and depth components of the attachment are treated at the beginning of the subpass where it is first used.```

That context at the end `where it is first used` should be included in the docs for `VkAttachmentLoadOp` because otherwise it suggests the load op is applied on every subpass.

Similar issues exist on `VkAttachmentStoreOp`

**Comment by oddhack** [comment]
I will fix the short description in the refpage to be consistent, thanks.
