### ISSUE TITLE
Cross vendor version of `VK_AMDX_shader_enqueue`

### ISSUE THREAD

**Issue by BeastLe9enD** [KhronosGroup/Vulkan-Docs#2354]
Hey :) It would be great to have a cross vendor extension of `VK_AMDX_shader_enqueue` (maybe an EXT extension) to have something similar to D3D12 work graphs

**Comment by Degerz** [comment]
https://github.com/KhronosGroup/Vulkan-Docs/issues/2153

**Comment by oddhack** [comment]
See https://github.com/KhronosGroup/Vulkan-Docs/issues/2153#issuecomment-1613763161 - this is a duplicate so closing.
