### ISSUE TITLE
Missing note that VK_EXT_load_store_op_none was partially promoted to Vulkan 1.3

### ISSUE THREAD

**Issue by spnda** [KhronosGroup/Vulkan-Docs#2357]
The [Appendix D](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#versions-1.3) does not list `VK_EXT_load_store_op_none` as being (partially) promoted, but Vulkan 1.3 added support for `VK_ATTACHMENT_STORE_OP_NONE` (just not `VK_ATTACHMENT_LOAD_OP_NONE_EXT`). Also, the [extension document](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_load_store_op_none.html) does not mention that it was (partially) promoted.

**Comment by oddhack** [comment]
It was promoted as part of VK_KHR_dynamic_rendering, not from the EXT.
