### ISSUE TITLE
Typo: vkCreateShaderModule creates a render pass

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#236]
In the description of `vkCreateShaderModule`, it says:

> `pShaderModule` points to a `VkShaderModule` handle in which the resulting **render pass object** is returned.

Emphasis added. Looks like a simple copy&paste bug.

**Comment by oddhack** [comment]
That will be fixed in the next public update.

**Comment by oddhack** [comment]
Fixed in 1.0.16.
