### ISSUE TITLE
Tessellation diagrams don't say what the inner tessellation levels are.

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#237]
The diagrams for the tessellation examples are unlabeled. It's difficult to understand visually what the triangle diagrams in particular depict without knowing what inner tessellation level (a) and (b) use.

The similar diagrams in the OpenGL specification are much clearer because they are labeled.

**Comment by oddhack** [comment]
I haven't figured out how to get long or formatted captions on figures in asciidoc yet. LaTeX allows giving a short label for the LOF and a long multi-paragraph caption. The caption text is sitting commented-out in the source until that's sorted out.

**Comment by oddhack** [comment]
N.b. while you can inject text of arbitrary (AFAICT) length into a caption, it all comes out as one paragraph, formatting can't be used. The caption could be put in a separate NOTE or part of the text, but then it wouldn't float with the figure.

**Comment by oddhack** [comment]
I added "Caption" sidebar blocks in the 1.0.29 spec update for these long captions. There really is no way to associate them directly with the figure, according to Mr. Asciidoc himself, so this will have to do.
