### ISSUE TITLE
Unreadable formatting for formulas on Fragment Density Map page

### ISSUE THREAD

**Issue by camilleqcamille** [KhronosGroup/Vulkan-Docs#2373]
Repo path:     antora/spec/modules/ROOT/pages/chapters/fragmentdensitymapops.adoc

Webpage:    https://docs.vulkan.org/spec/latest/chapters/fragmentdensitymapops.html

See webpage for evidence of formatting errors.

**Comment by oddhack** [comment]
Thanks. We're aware of this but haven't been able to dig down into the guts of the asciidoctor-mathjax extension to figure out what's going wrong, yet.

Closing as duplicated of https://github.com/KhronosGroup/Vulkan-Site/issues/39
