### ISSUE TITLE
MediaCodec or vulkan h264 265 extension ?

### ISSUE THREAD

**Issue by MetaTooy** [KhronosGroup/Vulkan-Docs#2374]
on the context that there already exists MediaCodec on android and video toolbox on apple， why does vulkan h264 265 extension publish and in which situation does it suits?

And is there any performance comparison between them? I just wonder whether vulkan extension is more efficient

**Comment by aqnuep** [comment]
The Vulkan Video extensions are not currently supported on Android or by MoltenVK (for Apple platforms). There are also no plans currently to support them on these platforms.
