### ISSUE TITLE
unclear interaction between vkCmdClearColorImage and R64 formats

### ISSUE THREAD

**Issue by AlexRouSg** [KhronosGroup/Vulkan-Docs#2375]
since vkCmdClearColorImage only takes 32 bits per component in the VkClearColorValue, it is unclear what happens with formats that have 64 bits per component. does it only set the lower 32 bits? does it clear the upper 32 bits? does it read the first 64 bits of VkClearColorValue? or is it completely invalid to call vkCmdClearColorImage on formats > 32 bits?

**Comment by HansKristian-Work** [comment]
We have a spec fix in flight that clarifies this.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.287 spec update
