### ISSUE TITLE
Inconsistency of unit of bufferRowLength and bufferImageHeight

### ISSUE THREAD

**Issue by litherum** [KhronosGroup/Vulkan-Docs#2378]
The [description of `VkBufferImageCopy`](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap20.html#VkBufferImageCopy)  says:

> `bufferRowLength` and `bufferImageHeight` specify in texels a subregion of a larger two- or three-dimensional image in buffer memory, and control the addressing calculations.

Specifically, that "in texels" indicates the unit for these fields is texels.

However, the [top of the section](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap20.html#copies-buffers-images) says:

> For each (x,y,z,layer) coordinate, bytes in the buffer are accessed at offsets in the range [texelOffset, texelOffset + blockSize), where:
> 
> texelOffset = bufferOffset + (x × blockSize) + (y × rowExtent) + (z × sliceExtent) + (layer × layerExtent)
> 
> blockSize is the size of the block in bytes for the format
> 
> rowExtent = max(bufferRowLength, ⌈imageExtent.width / blockWidth⌉ × blockSize)
> 
> sliceExtent = max(bufferImageHeight, imageExtent.height × rowExtent)
> 
> layerExtent = imageExtent.depth × sliceExtent

Specifically, that "bytes in the buffer are accessed at offsets" indicates that the unit of `texelOffset` is bytes, which means each term in the sequence of additions has to have the same unit of bytes. `y` is a count (dimensionless), so `rowExtent` must also have the unit of bytes, which then means that `bufferRowLength` must also have the unit of bytes given its definition. The same logic can be applied to `bufferImageHeight`.

**Comment by litherum** [comment]
From experimentation, the unit appears to be texels, not bytes.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.290 spec update. If you do not agree, please reopen with additional context.
