### ISSUE TITLE
Odd versions in appendix E

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#238]
There are odd versions mentioned in WSI chapter, like dependency "written against 0.151.0 Vulkan API" or 0.138.0. The branches are named **1.0**-VK_KHR_X, so I think it should be "written against 1.0 Vulkan API" instead.

**Comment by oddhack** [comment]
This should be addressed in the 1.0.18 spec update. And yes, I also noticed that it says "revision 1.0" and not "version 1.0" in most of them, but given how tediously painful it is to make edits in 10 different branches, nobody in the WSI subgroup wants to touch it again any time soon.

**Comment by krOoze** [comment]
^ lol :smirk:
well, then merge them to one or whatever would make your jobs easier and more enjoyable...
