### ISSUE TITLE
[VK_EXT_device_memory_report] How to report memoryobjId when binding a resource to device memory?

### ISSUE THREAD

**Issue by ShenghuaLinINTEL** [KhronosGroup/Vulkan-Docs#2390]
[VK_EXT_device_memory_report] @zhangyiwei

Considering such a case, app called vkAllocateMemory to allocate a piece of device memory, size is 1G, so driver should notify app about this allocation: assume memory obj id is 0.
then app called vkBindBufferMemory to bind the first 1MB of the device memory to a buffer, so driver should notify app about this allocation, assume memory obj id is 1.

when memory profiling tool compute memory usage, the result will be size of 0 + size of 1 = 1G + 1Mb. the result is wrong.
since the buffer object 's physical memory overlapped with device memory (objId==0), so should driver report this buffer's memory obj Id also as 0?
in this case, app will receive two allocation events with the same memobjId but with different size/handleId/handleType.

**Comment by zhangyiwei** [comment]
> then app called vkBindBufferMemory to bind the first 1MB of the device memory to a buffer, so driver should notify app about this allocation, assume memory obj id is 1.

Driver won’t notify the app here. Suballocation at VkDeviceMemory level is managed by the app.

This extension is mainly to allow driver to report internal device memory allocations (not cpu heap allocs that are already visible to tools). e.g. various binding pools that can lazily grow, compiled pipeline objects, command streams, etc

**Comment by ShenghuaLinINTEL** [comment]
thanks for the clarification. So this extension reports both app-visible and non-visible device memory events and most of them are non visible - descriptor pool, pipeline objects, command buffer pool, query pool, etc. 

The only app visible device memory event need to be reported is vkAllocateMemory/vkFreeMemory (which also contains import/unimport), right?

**Comment by zhangyiwei** [comment]
> The only app visible device memory event need to be reported is vkAllocateMemory/vkFreeMemory (which also contains import/unimport), right?

Yes, that’s the baseline to be reported, but the most boring part. The interesting part are those not visible to the app at this point, which can help app devs to optimize memory usage for perf gains.

> Besides, driver will make internal device memory allocations that can't be associated to any Vulkan objects, for example, global trtt page table used for sparse binding. since the callback requires objectType and objectHandle, so driver won't report device memory allocations that can't be associated to a specific Vulkan objects, right?

Most such global BO alloc can still be tied to the logical VkDevice. For those beyond it, they are also out of the interest of this extension since not actionable for app devs.

**Comment by ShenghuaLinINTEL** [comment]
completely cleared. thanks!
