### ISSUE TITLE
[Registry] Incorrect information regarding member, proto, and param tags

### ISSUE THREAD

**Issue by Waffl3x** [KhronosGroup/Vulkan-Docs#2394]
https://registry.khronos.org/vulkan/specs/1.3/registry.html#_contents_of_member_tags
"Builtin C types should not be wrapped in type tag"
https://registry.khronos.org/vulkan/specs/1.3/registry.html#_contents_of_proto_tags
"Builtin C types, and any derived types which are expected to be found in other header files, should not be wrapped in type tags."
https://registry.khronos.org/vulkan/specs/1.3/registry.html#_contents_of_param_tags
"Builtin C types, and any derived types which are expected to be found in other header files, should not be wrapped in type tags."

The described behavior would be inconsistent and depending on the library used, it would be harder to handle these tags if this were true. Luckily, vk.xml does not follow the described rule, "char" is still contained in a type tag despite being a builtin type.

In my opinion this is a documentation error, not an error in the registry as I noted it would be inconsistent to not have such types tagged.

**Comment by oddhack** [comment]
Agreed. At some point we made that change and did not reflect it in the schema doc. For builtin types they are just stub definitions but for external types like video Std*, the definitions trigger includes of the relevant header.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.291 spec update.
