### ISSUE TITLE
[Registry] Incorrect(?) description of unused attributes

### ISSUE THREAD

**Issue by Waffl3x** [KhronosGroup/Vulkan-Docs#2395]
https://registry.khronos.org/vulkan/specs/1.3/registry.html#_attributes_of_feature_tags
```sortorder - optional. A decimal number which specifies an order relative to other feature tags when calling output generators. Defaults to 0. Rarely used, for when ordering by name is insufficient.```
It seems to me like "Rarely used" is incorrect as the registry currently does not make use of this attribute. I think "currently unused" would be more accurate.
```protect - optional. An additional preprocessor token used to protect a feature definition. Usually another feature or extension name. Rarely used, for odd circumstances where the definition of a feature or extension requires another to be defined first.```
Same thing here.

**Comment by oddhack** [comment]
I'd rather not switch the language back and forth as we may need to use it at some point, and may stop using it afterwards if so, and this applies across multiple Khronos repositories that use basically the same schema. So I suggest closing this as WONTFIX.

**Comment by Waffl3x** [comment]
I would settle for a note below, just anything to save myself or others in the future the time investigating whether it actually needs to be handled or not. Besides, trying to handle for it when it's not even used, who's to say it would be done properly, the only logical thing is to immediately error out if you do encounter it so you know you have to rework code to handle it going forward.

**Comment by oddhack** [comment]
The 1.3.294 spec update includes new language from #2417 closing this issue. Hopefully that will suffice.
