### ISSUE TITLE
Effect of rendering when a fragment shader does not write to an attachment

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#240]
If you have several images attached for rendering during a subpass, but one of your fragment shaders does not write to an output that is linked to one of them... what happens? Is the value of the fragment color undefined (as in OpenGL)? The Vulkan specification does not seem to say.

The specification merely says that FS outputs are directed to color attachments based on locations. The section on blending says that the source values are those written by the FS. It says nothing about what happens if the FS doesn't write anything.

This is important, because it ought to be possible to set the write mask for such a fragment color output. That way, even if the output color is undefined, it won't have an effect on the rendered output.

**Comment by krOoze** [comment]
It says:

> When the fragment stage is present in a pipeline, the fragment shader outputs **form an interface** with the output attachments of the current subpass.

So I would assume, unless whole fragment gets discarded, that then it falls into a SPIR-V specification domain. And that, I think, would just pass the interfaced `OpVariable` (with undefined value) even if you do not `OpStore` anything into it.

**Comment by oddhack** [comment]
This should be addressed in the 1.0.18 spec update.

**Comment by oddhack** [comment]
N.b. there was another update related to this in the 1.0.21 spec update.
