### ISSUE TITLE
Really minor - vkGetPhysicalDeviceDisplayPropertiesKHR should link to VkDisplayPropertiesKHR

### ISSUE THREAD

**Issue by mikejsavage** [KhronosGroup/Vulkan-Docs#2401]
On https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetPhysicalDeviceDisplayPropertiesKHR.html, in the parameters section, the "VkDisplayPropertiesKHR" in "pProperties is either NULL or a pointer to an array of VkDisplayPropertiesKHR structures." should be a link to the VkDisplayPropertiesKHR page.

I looked at the adoc and couldn't figure out why there's no link here when generally there would be, so I'm making an issue for it instead.

**Comment by oddhack** [comment]
Thanks. I've fixed this internally and it will show up in the next spec update.

**Comment by oddhack** [comment]
Fixed in the 1.3.293 spec update.
