### ISSUE TITLE
Tweak signature of `vkCmdSetBlendConstants`

### ISSUE THREAD

**Issue by myaaaaaaaaa** [KhronosGroup/Vulkan-Docs#2403]
If possible, I would like the following change to be made:

```diff
 void vkCmdSetBlendConstants(
 	VkCommandBuffer commandBuffer,
-	const float     blendConstants[4]);
+	const float*    blendConstants);
```

The proposed signature should be semantically identical to the old one, but it removes an edge case for code generators when processing `vk.xml`

**Comment by oddhack** [comment]
There are a couple of other commands where this style is used. Is this the only one you're concerned about?

**Comment by oddhack** [comment]
We discussed and are not inclined to do this - there are concerns about impact on existing code generators and other downstreams that already have to handle this case, and it has potential to cause more problems than it solves. We suggest closing this, unless you have additional information / interest from additional people to help make the case for it.

**Comment by myaaaaaaaaa** [comment]
Okay, thanks for considering!
