### ISSUE TITLE
Are write masks disabled by disabling blending?

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#241]
Write masks are part of the `VkPipelineColorBlendAttachmentState`. This allows masking state to be applied per color attachment.

However, the language of section 26.1 does not make it clear if write masks are actually _part of_ blending. Indeed, the fact that the description of the effects of write masks are in a section named "Blending" strongly suggests that disabling blending also disables write masking. The language for `blendEnable` simply says that setting it to false turns off blending. It says nothing about write masking.

If the intent is that writes can be masked even if blending is not used, then the write masking part ought to be extracted out of section 26.1, perhaps placed in a new 26.2. And if the intent is that write masks require blending to be active before it can work, the spec needs to make this unmistakably clear.

**Comment by krOoze** [comment]
26.1.3. Blend Operations

> The colorWriteMask is applied regardless of whether blending is enabled.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.43 spec update.
