### ISSUE TITLE
Missing require for `VK_MAX_PIPELINE_BINARY_KEY_SIZE_KHR` in `VK_KHR_pipeline_binary` (vk.xml)

### ISSUE THREAD

**Issue by Macdu** [KhronosGroup/Vulkan-Docs#2422]
The newly released `VK_KHR_pipeline_binary` defines the enum constant `VK_MAX_PIPELINE_BINARY_KEY_SIZE_KHR`. However this enum definition is missing in `VK_KHR_pipeline_binary`'s require block (line 23925 of vk.xml, I can't get a permalink because the file is too big).

In previous extensions, when a new enum constant was defined, it was also added in the require part: for example `VK_EXT_shader_module_identifier` defines the enum constant `VK_MAX_SHADER_MODULE_IDENTIFIER_SIZE_EXT` and properly says it requires it (vk.xml, line 23460).

However, this line is missing for VK_MAX_PIPELINE_BINARY_KEY_SIZE_KHR  in VK_KHR_pipeline_binary in vk.xml as of release 1.3.294.

**Comment by oddhack** [comment]
@stu-s FYI. This shouldn't be a functional problem since generators are responsible for following dependencies from the structure's use of the constant to its definition, but it does mean that it will not appear in the API list in the extension appendix where only the direct dependencies in the extension tag are cited.

**Comment by oddhack** [comment]
Also there should be a corresponding API definition block analogous to VK_MAX_PHYSICAL_DEVICE_NAME_SIZE (devsandqueues.adoc) or VK_MAX_DESCRIPTION_SIZE (memory.adoc). That should be added immediately after the refpage block describing the structure this constant is used in.

**Comment by stu-s** [comment]
Fix [here](https://github.com/KhronosGroup/Vulkan-Docs/pull/2423)

**Comment by Macdu** [comment]
Closing as the fix as been merged
