### ISSUE TITLE
Naming problem: color vs colour in vulkan video structs

### ISSUE THREAD

**Issue by kanashimia** [KhronosGroup/Vulkan-Docs#2428]
Why in `StdVideoH264SequenceParameterSetVui` there is a field named `colour_primaries` but in `StdVideoH264SpsVuiFlags` another field is named `color_description_present_flag` ???? And for H265 it is named `colour_description_present_flag` ?
In the `h264` spec it is named as `colour_description_present_flag`, but I think it is reasonable to just forbid spelling `color` as `colour` everywhere for consistency, as Vulkan uses american spelling, and to prevent someone in the future accidentally using "wrong" spelling when writing extensions for new codecs.
Or like at least it should be consistent within a single a single coding format.

Not sure if you can actually rename it at this point, you still do breaking changes to the video headers, right?

---

Looking at the past discussions it seems that it was decided that naming (and casing) should be exactly like it is in the standard, for the ease of searching the standard, which it isn't now. Although with H.264 having multiple standards over the years there are some fields that were renamed anyways. But it seems that most coding related programs seem to follow original spelling and casing, with slight naming differences depending on the version of the standard that they've used, so I guess it may be reasonable to do so too. Which in turn means that everything related to the H.264 / H.265 spec will use "colour" spelling and for AV1 will use "color" spelling. That's is pretty error prone for the vk video definitions writers though.

**Comment by aqnuep** [comment]
The names are coming from the H.264 and H.265 specs, hence the `colour` spelling.

In general, all video std definitions are supposed to be following the naming defined in the corresponding video compression standards, which in case of H.264 and H.265 do use British English spelling.

The video std definitions are not directly part of the Vulkan API, hence they do not adhere to the American English spelling rules, they should be looked at more as platform headers such as `Windows.h`.

Apparently, `color_description_present_flag` is a typo, it should be `colour_description_present_flag`, as defined in the H.264 specification.

We will look into whether we could find a way to fix this in a backward-compatible way or at least clarify in the spec why there is a name mismatch between the video std header definition and the codec spec.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.296 spec update.
