### ISSUE TITLE
[WSI] Can swapchain image format be reinterpreted?

### ISSUE THREAD

**Issue by Themaister** [KhronosGroup/Vulkan-Docs#243]
For sRGB purposes it seems useful to be able to reinterpret the format when creating image views against the framebuffer. However, it is unclear to me if this is possible.

The specification states that MUTABLE_FORMAT_BIT must be used for this in vkCreateImage, but it is not possible to pass such a flag to vkCreateSwapchainKHR, so I would like some clarification if any interpretation of formats on swapchains is illegal, or if MUTABLE_FORMAT_BIT is implied for swapchain images.

**Comment by krOoze** [comment]
Generally speaking, all these Image states are not (and should be) specified:
- any from the `ImageCreateInfo` `flags`
- `imageType` (likely 2D, but who knows what future will bring :wink: )
- `mipLevels` (likely 1 - but who knows, could be useful to the OS)
- `samples` ( In the FAQ it is mentioned it's 1 )
- `tiling` (likely OPTIMAL; which can be tiled or even linear underneath anyway)

**Comment by oddhack** [comment]
This should be fixed in the 1.0.21 spec update.
