### ISSUE TITLE
(Docs) stride attribute is not specified for command prototype param tags

### ISSUE THREAD

**Issue by Waffl3x** [KhronosGroup/Vulkan-Docs#2435]
```xml
        <command queues="graphics" renderpass="inside" cmdbufferlevel="primary,secondary" tasks="action">
            <proto><type>void</type> <name>vkCmdDrawMultiEXT</name></proto>
            <param externsync="true"><type>VkCommandBuffer</type> <name>commandBuffer</name></param>
            <param optional="true"><type>uint32_t</type> <name>drawCount</name></param>
            <param noautovalidity="true" len="drawCount" stride="stride">const <type>VkMultiDrawInfoEXT</type>* <name>pVertexInfo</name></param>
            <param><type>uint32_t</type> <name>instanceCount</name></param>
            <param><type>uint32_t</type> <name>firstInstance</name></param>
            <param><type>uint32_t</type> <name>stride</name></param>
        </command>
```
In this example the 3rd param pVertexInfo has a stride attribute, this is not specified in the registry docs.
https://registry.khronos.org/vulkan/specs/1.3/registry.html#tag-command:param:attr

This is specified correctly for member tags, it's simply missing from param tags.
https://registry.khronos.org/vulkan/specs/1.3/registry.html#_attributes_of_member_tags

**Comment by spencer-lunarg** [comment]
(note this was added internally here https://gitlab.khronos.org/vulkan/vulkan/-/commit/b2fe6378bf)

**Comment by oddhack** [comment]
@spencer-lunarg it looks like this was correctly added to the RNC schema but the description was added to registry.adoc for the struct tag instead. ISTM we should suppport it for both structs and commands, though there are very few use cases today. If you like I'll do that MR, or you could.

**Comment by spencer-lunarg** [comment]
>  If you like I'll do that MR, or you could.

I would rather you just do it correct, I just did the digging because I never seen this `stride` before and was curious who needed it
