### ISSUE TITLE
VK_EXT_shader_object push constant vs VkPipelineLayout push constants.

### ISSUE THREAD

**Issue by nikitablack** [KhronosGroup/Vulkan-Docs#2444]
Hello. The documentation for the extension is not clear regarding descriptor set layout and push constant ranges in `VkShaderCreateInfoEXT`. There's already an open [issue](https://github.com/KhronosGroup/Vulkan-Docs/issues/2099) with a question about descriptors layout, and it seems that there is a missing functionality to set layout at runtime. I assume it's the same with push constants - the shader create info requires to provide ranges, but to push constants the `vkCmdPushConstants` function should be used, which requires a pipeline layout. Providing `VK_NULL_HANDLE` does not work. Using ranges in either pipeline layout or shader create info also does not work - they have to be set in both places. Should they match (documentation doesn't say that)?

Another question is the possibility to set multiple ranges with a single `VkShaderCreateInfoEXT`. But it seems that one info describes a single shader, so there can't be more than one range per shader. The Specification forbids to use the same stage flags for multiple ranges:

> Any two elements of pPushConstantRanges must not include the same stage in stageFlags

When do we need to use multiple ranges in a single `VkShaderCreateInfoEXT`?

**Comment by pdaniell-nv** [comment]
The pipeline layout used to create each of the shader objects that will eventually be bound together need to all be compatible (https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#descriptorsets-compatibility), and the pipeline layout used for the vkCmdPushConstants call also needs to be compatible with the bound shader objects.

**Comment by oddhack** [comment]
@nikitablack if @pdaniell-nv's response answers your question, please close the issue, or clarify what additional information you need. Thanks!

**Comment by nikitablack** [comment]
I got it that the Spec requires to do the redundant work and define the same information twice - in a pipeline layout and in a shader object. It would be interesting to know why and if it's gonna change. Because this requirement kinda destroys the purpose of a shader object - instead of assembling a pipeline dynamically at runtime I have to care about descriptors layout and push constant ranges upfront. Which usual vulkan pipelines do.

And the second part of the question was not answered at all - why there's a requirement to specify a push constant as an array for a shader object? One shader object means one shader stage - it's technically impossible to have multiple entries.

**Comment by pdaniell-nv** [comment]
The VkShaderCreateInfoEXT uses pushConstantRangeCount and pPushConstantRanges to match the equivalent parameters VkPipelineLayoutCreateInfo, and it follows the same rules. There can be stageFlags in elements of pPushConstantRanges that don't match the shader stage being created, but keeping it consistent with the pipeline layout used for vkCmdPushConstants will ensure compatibility.

We know this API isn't ideal and we are considering ways to make it much cleaner. In the meantime, if you have access to an implementation with VK_NV_per_stage_descriptor_set with the dynamicPipelineLayout feature enabled, you have the option of skipping the pipeline layout creation when using vkCmdPushConstants2KHR.
