### ISSUE TITLE
(again) Undesired unicode replacements (⇐ instead of ≤, → instead of ->)

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#245]
Similar as in issue #239 ,
in the [new 1.0.16 changes to features.txt](https://github.com/KhronosGroup/Vulkan-Docs/commit/5de77cf663c84cc2edfa355c49319dca0a869eb2#diff-7e6dee71ddb41acf30a28931d6bc5033), it creates Unicode arrow ⇐ instead of ≤.
Do not use `<=` in that context!  :no_entry_sign:

UPDATE: still not fixed in 1.0.17. And BTW neither is the similar prematurely closed issue #239 .

UPDATE 2: also C arrow operators -> are replaced with Unicode → all over the place.

consult http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#text-replacement 
but that seems to be all.
Only found some inconsistent em dash usage (some with space around, some not). And in three cases the desired arrow is made using the latexmath instead of making use of the text replacement feature (or direct Unicode).

**Comment by oddhack** [comment]
There are no ⇐ symbols in the 1.0.18 spec update, AFAICT.

No plans to do anything about the → issue. They are appearing in places where they're either perfectly fine, like the table row headings, or just explanations in VU statements - not code samples people can cut and paste. I believe the meaning is clear. There are lots of higher priorities so nobody is motivated to deal with minor markup issues of this sort.

Finally, nobody is at all eager to use non-ASCII Unicode characters in the spec sources at present. We've tried to do that previously and had trouble with differing results on the toolchains that create HTML and PDF output, respectively.
