### ISSUE TITLE
VK_KHR_video_encode_av1?

### ISSUE THREAD

**Issue by colinmarc** [KhronosGroup/Vulkan-Docs#2451]
Is an encode extension for AV1 still planned for Vulkan Video? Is there an issue I can follow for progress updates?

Thanks!

**Comment by r-potter** [comment]
The AV1 encode extension is progressing well and we hope to have something to share soon. Unfortunately, there is no publicly accessible issue for this.

**Comment by r-potter** [comment]
The AV1 encode extension was released yesterday: https://www.khronos.org/blog/khronos-announces-vulkan-video-encode-av1-encode-quantization-map-extensions

Since the extension is now released, I'll close the issue, but please feel free to reopen if you have further questions.
