### ISSUE TITLE
VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT and implicit command buffer reset

### ISSUE THREAD

**Issue by ntsh-oni** [KhronosGroup/Vulkan-Docs#2458]
When creating a VkCommandPool, a [VkCommandPoolCreateFlagBits](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkCommandPoolCreateFlagBits.html) can be passed to the create info structure.

This VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT flag, specifies that the command buffers created from this command pool can be resetted to the initial state "either by calling [vkResetCommandBuffer](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkResetCommandBuffer.html), or via the implicit reset when calling [vkBeginCommandBuffer](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkBeginCommandBuffer.html)".

When does this "implicit reset" happens? [vkBeginCommandBuffer](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkBeginCommandBuffer.html) has valid usage _VUID-vkBeginCommandBuffer-commandBuffer-00049_: "commandBuffer must not be in the [recording or pending state](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#commandbuffers-lifecycle)", which means that after submission, the command buffer can't really be resetted to initial state by this function, as it is in the pending state when recording it.

**Comment by fknfilewalker** [comment]
Based on this observation it is not clear if my situation is invalid usage or a (driver) bug.

When creating a Pool with VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT and a cmd buffer with VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT, not reseting the cmd buffer results in a memory leak. 

```c++
evk::CommandPool commandPool{ device, queueFamilyIndex.value(), vk::CommandPoolCreateFlagBits::eResetCommandBuffer };
auto cb = commandPool.allocateCommandBuffer();
while (true) {
    //stcb.reset(); // memory leak fix
    cb.begin(vk::CommandBufferBeginInfo{ vk::CommandBufferUsageFlagBits::eOneTimeSubmit });
    cb.end();
    device->getQueue(queueFamilyIndex.value(), 0).submitAndWaitIdle(vk::SubmitInfo{ {}, {}, *cb }, nullptr);
}
```

**Comment by ntsh-oni** [comment]
Sascha Willems linked me to [this issue](https://github.com/KhronosGroup/Vulkan-Docs/issues/471) on the Vulkan Discord server so I understand better why it has been worded this way.

It looks like what @fknfilewalker is doing is valid so the next step is to check if it is a driver issue (not freeing if not explicitly resetting the command buffer).
