### ISSUE TITLE
Tessellation outer and inner level confusion

### ISSUE THREAD

**Issue by Silverdaru** [KhronosGroup/Vulkan-Docs#246]
I apologize if this is actually not an issue. I started to read up on Vulkan and found it quiet confusing that in the specification (14.6) and the quick reference you consistently write that the built-in shader variable "TessLevelOuter" is an array of two elements and "TessLevelInner" is a four element array. Shouldn't it be the other way round? "TessLevelOuter" having four elements and "TessLevelnner" having two? At least that is what my understanding of tessellation levels and chapter 21 of the specification suggest.

**Comment by oddhack** [comment]
I believe you're correct. The language in the tessellation chapter certainly refers to four elements in the outer array and that's consistent with GL/ES specs. Probably just a typo in transferring GL tessellation language to Vulkan - I'll check it out with the WG but this seems like an obvious error. Thanks!

**Comment by oddhack** [comment]
This should be fixed in the 1.0.17 spec update.
