### ISSUE TITLE
Does Vulkan support YcbcrConversion of QCOM TP10_UBWC format?

### ISSUE THREAD

**Issue by 894665169** [KhronosGroup/Vulkan-Docs#2460]
I tried to render hdr-10 video with Vulkan. When the output formats are YCbCr_420_P010_VENUS, YCbCr_420_SP_VENUS and YCbCr_420_SP_VENUS_UBWC, the display is normal, but this goes wrong when hardwarebuffer format is YCbCr_420_TP10_UBWC.
It seems that the layout of TP10 is a packed format and much different from nv12 and P010, does vulkan ycbcrconversion support such format?

**Comment by 894665169** [comment]
![Uploading screenshot.png…]()

**Comment by mnetsch** [comment]
Our drivers support sampling from this format through the Android Hardware Buffer interface. Please use our qualcomm developer support forums for discussions on snapdragon devices.
