### ISSUE TITLE
Inconsistent removal of type or function with vulkansc

### ISSUE THREAD

**Issue by asuessenbach** [KhronosGroup/Vulkan-Docs#2469]
The command `vkCmdPushDescriptorSetWithTemplate` is listed as required with `VK_VERSION_1_4`, for both "vulkan" and "vulkansc".
It uses the type `VkDescriptorUpdateTemplate` as one of its params.
That type is listed as required with `VK_VERSION_1_1`, for both "vulkan" and "vulkansc", but explicitly listed as removed with `VKSC_VERSION_1_0`, just for "vulkansc", of course.

Should the type `VkDescriptorUpdateTemplate` not be removed or should the command `vkCmdPushDescriptorSetWithTemplate` be removed as well for "vulkansc"?

**Comment by oddhack** [comment]
@dgkoch. Likely I just made a cut & paste oversight by adding 'vulkansc' to the VK_VERSION_1_4 requirements, though.

**Comment by dgkoch** [comment]
> @dgkoch. Likely I just made a cut & paste oversight by adding 'vulkansc' to the VK_VERSION_1_4 requirements, though.

We needed to add "vulkansc" to VK_VERSION_1_4 or a lot of other build steps don't work cleanly. I'll take a look at what to do with vkCmdPushDescriptorSetWithTemplate, but it should probably be removed for VKSC as well.

**Comment by dgkoch** [comment]
See https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7049

**Comment by oddhack** [comment]
This should be fixed in the 1.4.304 spec update.
