### ISSUE TITLE
PREINITIALIZED not supposed to be in VU?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#248]
In 11.4. Image Layouts:

> [...] when performing a layout transition on the image subresource, the old layout value must either equal the current layout of the image subresource (at the time the transition executes), or else be VK_IMAGE_LAYOUT_UNDEFINED [...].

Yet in VU for ImageMemoryBarrier:

> oldLayout must be VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_PREINITIALIZED or the current layout of the image region affected by the barrier

which would allow PREINITIALIZED even if that is not the current layout.

**Comment by jeffbolznv** [comment]
In today's meeting we agreed to remove PREINITIALIZED from this valid usage rule.

**Comment by ratchetfreak** [comment]
Then it must also be removed from the vkCmdBeginRenderPass valid usage concerning initialLayout.

**Comment by jeffbolznv** [comment]
Agreed, I've added that to the change.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.19 spec update.

**Comment by krOoze** [comment]
I found this in Memory Aliasing chapter:
> If any image subresources are made undefined due to writes to an alias, then each of those image subresources must have its layout transitioned from VK_IMAGE_LAYOUT_UNDEFINED to a valid layout before it is used, or from VK_IMAGE_LAYOUT_PREINITIALIZED if the memory has been written by the host.

In the light of the changes, is this to be interpreted as the image (subresource) changing its current layout to UNDEFINED or PREINITIALIZED (depending on the situation)?
