### ISSUE TITLE
Buffer memory barrier  and render pass dependencies? 

### ISSUE THREAD

**Issue by vlj** [KhronosGroup/Vulkan-Docs#249]
I have a 2 passes algorithm that uses image and buffer atomic read write operation in the first pass while the second one reads the buffer and image. 
I'm wondering if it's possible to use a single render pass with 2 surpass. I'm not sure how surpass dependencies are interacting with non attachment memory object. 

As far as I understand on most implementation src and dst access mask are used to determine if a cache flush is needed or not. However cmdpipelineresource command takes a buffer or an image as parameter. I think in most arch cache flush work on all resource in cache so the semantic maybe broader to allow implementation to optimize some cases. 

On the other hand the subpass dependencies don't take image or buffer as parameter. Can I assume that the access mask in src and dst will work on every resource? 
The fact is that it's possible to add subpass self dependency when using image barrier transition inside a render pass, which hints that access mask in subpasssdep are not intended to replace cmdpipelineresource in case of resource not declared as an attachment. Since buffer barrier are not allowed in a render pass this means I'll have to use 2 renderpasses
Regards,  Vincent

**Comment by TobiasHector** [comment]
Hi Vincent,

There's a struct called "VkMemoryBarrier" which you can use for regular pipeline barriers or events which flushes "all memory" in the way you're asking about. The reason for specific buffer/image barriers is if you are able to do something a bit more fine grained - these operations also handle image transitions and transfer of queue ownership.

The subpass dependencies do exactly the same thing - they operate on all memory. So you can use these to have a dependency on your first pass to your second pass for both resources, as long as you're not changing the layout of the image (use the GENERAL layout if you have to).

**Comment by vlj** [comment]
Thanks for your answer !

**Comment by oddhack** [comment]
@vlj if @TobiasHector's response answers your question, please close this issue.
