### ISSUE TITLE
"ckCmdDraw" typo on quick reference PDF index page

### ISSUE THREAD

**Issue by iamgreaser** [KhronosGroup/Vulkan-Docs#250]
Rev. 0216 of the quick reference has "ckCmdDraw" on the index page. This is clearly a typo.

I'm not sure if this is the right bug tracker for the Vulkan 1.0 Quick Reference.

**Comment by oddhack** [comment]
Thanks. I'll pass this along to the authors of the document, but I don't know how soon it might get updated.

**Comment by oddhack** [comment]
I believe this is fixed now.
