### ISSUE TITLE
BindBufferMemory valid usage assumes buffer size == backing memory size

### ISSUE THREAD

**Issue by chrisforbes** [KhronosGroup/Vulkan-Docs#251]
Spec says, for `BindBufferMemory`:

> The size of _buffer_ must be less than or equal to the size of _memory_ minus _memoryOffset_

This doesn't take into account additional padding that may be required within the allocation (and is, for at least one implementation). Should refer instead to the size returned in VkMemoryRequirements::size.

Exact wording should probably mirror that for `BindImageMemory`:

> The size member of the VkMemoryRequirements structure returned from a call to vkGetImageMemoryRequirements with image must be less than or equal to the size of memory minus memoryOffset

Ref discussion on KhronosGroup/Vulkan-LoaderAndValidationLayers#648, @DominikWitczakAMD

**Comment by oddhack** [comment]
@chrisforbes since you're a Khronos member, we'll ask you to do an internal (gitlab) MR for review. Discussion today approved the direction you suggest above.

**Comment by chrisforbes** [comment]
@oddhack sorry to leave this in limbo for a week -- I've now proposed !1406 internally.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.19 spec update.
