### ISSUE TITLE
Make doc error also has installed asciidoc

### ISSUE THREAD

**Issue by yjjxwx** [KhronosGroup/Vulkan-Docs#252]
I find that in make file, you include asciidoc.py and a2x.py, this occure error when make doc, 

Error message follows:
asciidoc.py: not found.
I replace  to asciidoc and a2x, and then remake it. successfully.

**Comment by oddhack** [comment]
Unfortunately the scripts are named differently on Windows and Linux asciidoc installs. Please set the ASCIIDOC and A2X environment variables in your environment before doing a make. We will have some sort of autoconf script eventually, but it's not a big priority.
