### ISSUE TITLE
vkCmdBlitImage sRGB format conversions

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#253]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#vkCmdBlitImage says:

> If vkCmdBlitImage is used on images of different formats, the following conversion rules apply:
> * ...
> * In case of sRGB source format, nonlinear RGB values are converted to linear representation prior to filtering.
> * After filtering, the float values are first clamped and then cast to the destination image format. In case of sRGB destination format, linear RGB values are converted to nonlinear representation before writing the pixel to the image.

Conversion to/from linear RGB is important for bilinear filtering (e.g. mipmap generation only works properly in linear space), but this says you'll only get that behaviour if the formats are different.

That means you could generate good mipmaps by converting from `R8G8B8A8_SRGB` to `A8B8G8R8_SRGB_PACK32` (which I think are identical representations on little-endian systems), but it won't work properly if your source and destination are both `R8G8B8A8_SRGB`. You might have to do nasty tricks with aliasing to get the good behaviour.

Is that intentional? or should the sRGB-to-linear conversion apply even when the formats are the same?

If it's intentional, it seems a silly API design to me - it doesn't sound like a useful optimisation given that devices already have to support sRGB conversion for different-but-very-similar formats, and bilinear filtering in sRGB space is never a meaningful operation that anyone would actually want.

Also, more pedantically, the spec doesn't actually say what conversion rules apply when vkCmdBlitImage is used on images of the same format.

**Comment by jekstrand** [comment]
The intent here is that the conversion rules get applied all of the time with the understanding that most will be no-ops for images with the same format.  Obviously, in the case of sRGB scaling, you would like the filtering to happen in the linear colorspace.

**Comment by philiptaylor** [comment]
Maybe it would be sufficient to just remove the "If vkCmdBlitImage is used on images of different formats" phrase, and assume implementors are able to work out for themselves when the conversion is a no-op and can be optimised away.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.19 spec update.
