### ISSUE TITLE
MaxDescriptorSet* limits shouldn't always be 6 time the MaxPerStage*  limit

### ISSUE THREAD

**Issue by ratchetfreak** [KhronosGroup/Vulkan-Docs#254]
In the limits section each of the MaxDescriptorSet* limit with a annotation of 6 times the perStage.

Presumably the 6 comes from the number of programmable stages. However not all of those are required to be supported or enabled.

So the logical thing would be to say number of enabled stages * the perStage limit.

**Comment by dgkoch** [comment]
Yes, the 6 comes from the number of programmable stages. 

The limit should depend on the number of stages supported by the hardware, not the number enabled. This is the VkPhysicalDeviceLimits structure, which is queried on a Physical device, and feature enablement is on logical devices. 

Will propose a patch for this.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.28 spec update.
