### ISSUE TITLE
vkUpdateDescriptorSets overflow with sparse layouts

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#256]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#descriptorsets-updates-consecutive says:

> If the dstBinding has fewer than descriptorCount array elements remaining starting from dstArrayElement, then the remainder will be used to update the subsequent binding - dstBinding+1 starting at array element zero. This behavior applies recursively, with the update affecting consecutive bindings as needed to update all descriptorCount descriptors. All consecutive bindings updated via a single VkWriteDescriptorSet structure must have identical descriptorType and stageFlags, and must all either use immutable samplers or must all not use immutable samplers.

The behaviour with sparse descriptor set layouts is unclear to me.

E.g. if I have a descriptor set layout corresponding to

```
layout (set=0, binding=0) uniform texture2D a[4];
layout (set=0, binding=2) uniform texture2D b[4];
```

and call vkUpdateDescriptorSets with VkWriteDescriptorSet with dstBinding=0, dstArrayElement=0, descriptorCount=8, what happens?

Presumably "subsequent binding" is being defined to be binding number 1 (though it's not phrased very clearly as a definition), but that binding does not have a defined descriptorType or stageFlags so it's not meaningful to consider whether they're identical or not.

I guess it should be an error, but it's also just about plausible that an implementation might be expected to skip over unspecified bindings (by assuming they have an implicit descriptorCount of 0, or by reading "subsequent" as the next defined binding).

I think an explicit validity condition should be added, maybe like "All consecutive bindings updated via a single VkWriteDescriptorSet structure must have been defined by a VkDescriptorSetLayoutBinding in the layout of dstSet, and must have identical descriptorType and stageFlags, ..." or something.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.34 spec update.
