### ISSUE TITLE
vkGetImageMemoryRequirements on SPARSE_BINDING but not-SPARSE_RESIDENCY images

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#257]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#resources-association says:

> Resources created with any of the sparse creation flags are considered sparse resources. Resources created without these flags are non-sparse.

> To determine the memory requirements for a non-sparse image resource, call: `void vkGetImageMemoryRequirements(...)`

So an image with `flags=VK_IMAGE_CREATE_SPARSE_BINDING_BIT` is a sparse image resource, and this says `vkGetImageMemoryRequirements` is not the right thing to use for that image.

But https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#sparsememory-memory-requirements says:

> Query sparse memory requirements for an image by calling: `void vkGetImageSparseMemoryRequirements(...)`
>
> If the image was not created with `VK_IMAGE_CREATE_SPARSE_RESIDENCY_BIT` then `pSparseMemoryRequirementCount` will be set to zero and `pSparseMemoryRequirements` will not be written to.

So `vkGetImageSparseMemoryRequirements` won't give useful output for an image that is only `SPARSE_BINDING` and not `SPARSE_RESIDENCY`.

If I understand correctly, that makes it impossible to determine memory requirements for such an image.

I suspect `vkGetImageMemoryRequirements` is actually the right thing to use for such images. I suspect it's needed for sparse-resident images too, because the spec says "As with buffers and fully resident images, the `VkMemoryRequirements::alignment` field denotes the bindable sparse block size in bytes for the image." and I think you can only get that from alignment from `vkGetImageMemoryRequirements`.

So the misleading reference to "non-sparse image resource" in the definition of `vkGetImageMemoryRequirements` should be removed.

Same applies to `vkGetBufferMemoryRequirements` - the reference to "non-sparse buffer resource" should be removed since you probably need it for alignment etc.

**Comment by jeffbolznv** [comment]
In today's meeting we agreed to remove the "non-sparse" for both of these.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.19 spec update.
