### ISSUE TITLE
Should vkCreateDevice (still) return VK_ERROR_LAYER_NOT_PRESENT?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#259]
Should `vkCreateDevice` (still) return VK_ERROR_LAYER_NOT_PRESENT after the device layer deprecation, as is stated in the Return Codes section?

BTW:
1) *_NOT_PRESENT is not explained there same way as is newly done for the `vkCreateInstance`.

There is a paragraph in `vkCreateInstance` description explaining when VK_ERROR_{LAYER|EXTENSION}_NOT_PRESENT is returned. I found it odd, the same is not done for `vkCreateDevice` for the now remaining VK_ERROR_EXTENSION_NOT_PRESENT (or possibly of course vice-versa why it **is** explained for `vkCreateInstance`)

2) maybe the `VkResult` descriptions "is not supported" is a bit misleading and so is the new "cannot be found". I think, it is supposed to be simply "failed to enable" instead...

The "is not supported" wording is in 2.6.2. Return Codes chapter for VK_ERROR_{LAYER|EXTENSION}_NOT_PRESENT. And the "cannot be found" is in the description section for `vkCreateInstance` command.
I simply found those wordings too specific for the purpose(and as such misleading). I thought, those errors are meant to be simply returned when the relevant `create*` command is unable to enable the specified layer/extension for whatever reason (not only for some "failure of finding" or "supporting", whatever those mean).

**Comment by courtney-g** [comment]
Have made pull request !260 to address this. krOoze, Please verify as I'm not certain I've covered everything listed in the issue (BTW items).

**Comment by krOoze** [comment]
@courtney-g Obvious fix. But no, not really addressing the "BTW" items at all (yet?). Was I not clear with their description, or why do you ask for verification? I will explain them more precisely in the original post...

**Comment by courtney-g** [comment]
Updated patch should address issue #1.

As for:
> 2) maybe the VkResult descriptions "is not supported" is a bit misleading and so is the new "cannot be found". I think, it is supposed to be simply "failed to enable" instead...

I'd be curious to see what other interested parties think is a good description for the error code VK_ERROR_LAYER_NOT_FOUND.

1) (current spec) VK_ERROR_LAYER_NOT_PRESENT: A requested layer is not present or could not be loaded.

2) (proposed change, IIRC) VK_ERROR_LAYER_NOT_PRESENT: Failed to enable a requested layer.

In either case, the user action is the same, they have to figure out what is needed on their system to support that extension/layer. Which definition "directs" the user to the proper action?

**Comment by krOoze** [comment]
I withdraw BTW 2) in light of the discussion in pr #260 . `VK_ERROR_*_NOT_PRESENT` is not specified to catch all relevant errors at the moment (though it probably does in implementations) and so "Failed to enable a requested *" would be more misleading.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.19 spec update.
