### ISSUE TITLE
Device memory type ordering

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#26]
Section 10.2 (Device Memory) says:

> Memory types are ordered in the list such that X is assigned a lesser memoryTypeIndex than Y if X≤Y according to the partial order.

That implies X is always assigned a lesser memoryTypeIndex than X (because X <= X), which is impossible. It should use a strict partial order instead, i.e. say X is assigned lesser than Y if X < Y (which is equivalent to saying X <= Y && !(Y <= X) using the earlier definition of '<=').

> Note that the list of all allowed memory property flag combinations above satisfies this partial order

No it doesn't. E.g. "VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT" is a subset of "VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT | VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT" but comes later in that list.

Rearranging the list doesn't sound like a good solution, because then the slower non-DEVICE_LOCAL ones would be preferred over the DEVICE_LOCAL ones. Maybe the definition of the order should be changed to ignore DEVICE_LOCAL in the bits comparison (and rely on the performance clause to prefer the DEVICE_LOCAL ones).

> Given two memory types X and Y, the partial order defines X≤Y if:

I think mathematically it's a preorder, not a partial order, under the widely-accepted definitions of those terms (e.g. http://mathworld.wolfram.com/PartialOrder.html, http://mathworld.wolfram.com/Preorder.html).

You could have two distinct memory types X != Y (e.g. they have different heapIndexes, or the same heapIndex and just different memoryTypeIndex) that have the same propertyFlags and the same performance, so that X <= Y and Y <= X. A partial order is defined to have antisymmetry, i.e. X <= Y && Y <= X implies X = Y, which is not true in this case. A preorder is a partial order without antisymmetry, which means two elements can be equivalent but non-equal, which is what we want here.

...But maybe that's possibly being too pedantic about terminology.

**Comment by jeffbolznv** [comment]
> Rearranging the list doesn't sound like a good solution, because then the slower non-DEVICE_LOCAL ones would be preferred over the DEVICE_LOCAL ones.

The intent really was for the non-DEVICE_LOCAL memory types to be earlier in the list, but this does not make them "preferred". We made each memory property bit be phrased in a "positive" way, such that getting a bit you didn't ask for is harmless (e.g. it is OK if you get coherent memory when you didn't ask for it, or if you get faster device-local memory when you only cared that it was host-visible). Thus an application can first search for their optimal memory type, and if that fails fallback to searching for a guaranteed memory type.

Agreed on all the other issues, I'll fix it.

**Comment by philiptaylor** [comment]
> Thus an application can first search for their optimal memory type, and if that fails fallback to searching for a guaranteed memory type.

That section says:

> The goal of this ordering is to enable applications to use a simple search loop in selecting the proper memory type, along the lines of:
>
>     // Searching for the best match for "properties"
>     for (i = 0; i < memoryTypeCount; ++i)
>         if ((memoryTypes[i].propertyFlags & properties) == properties)
>             return i;

which makes me think the application would just search once for the properties that it absolutely requires (which would typically be 0 or HOST_VISIBLE|HOST_COHERENT), and it will get the "best" one that satisfies the requirements. And DEVICE_LOCAL is "the most efficient for device access", which I'd interpret as "best".

It sounds like you're suggesting the application nearly always needs do the loop twice, first with the required properties plus DEVICE_LOCAL, and (if that fails) with the required properties minus DEVICE_LOCAL. In that case, I think the example code should be updated to make that clearer.

**Comment by slippah** [comment]
Still working on this. It's pretty clear that doing a high-quality, hardware-neutral job of memory type / heap selection is inherently messy. The original example code would definitely return a suboptimal result if you asked for HOST_VISIBLE on hardware that exposes host-visible memory in both DEVICE_LOCAL and ~DEVICE_LOCAL forms. We are working on both the example code and the surrounding language to give better guidance. After that we'll work on getting the SDK and examples updated.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.9 spec update.
