### ISSUE TITLE
[WSI] Overriden must word in vkAcquireNextImageKHR description

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#262]
In description of `vkAcquireNextImageKHR`:
> `vkAcquireNextImageKHR` **must** not be called when a > n - m; in such a case, and if `timeout` is `UINT64_MAX`, `vkAcquireNextImageKHR` **may** block indefinitely.

The second "**may**" sentence defines what may happen if I do not do what I **must** always without exception do (which is weird/mutually-negating).

And what is supposed to happen with finite `timeout`. Is it undefined in that case (including perhaps even also blocking indefinitely) as the "**must**" would imply, OR does it return (validly) some success code as opposite to the "**may** block indefinitely" of `timeout=UINT64_MAX` case?

BTW Is there a reason this is not inside VU section of `vkAcquire`? Seems it is a precondition of that command and seems relatively easily checked by validation layers too.

**Comment by TobiasHector** [comment]
The first "must" should should probably be a "should". The latest update clarifies what a valid usage statement is, and when it should exist - this would not be a valid usage statement, as it has defined behavior.

**Comment by krOoze** [comment]
> this would not be a valid usage statement, as it has defined behavior.

Of course. If it's truly meant to be "**should**", then it doesn't belong in the VU.

**Comment by TobiasHector** [comment]
I'll put in a change to fix this and it should be in the next update unless someone disagrees with me.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.19 spec update.
