### ISSUE TITLE
Tessellation spacing placement and "should" vs. "must".

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#264]
The Vulkan specification rigidly defines how it uses terms that put requirements on implementations or users. In this case, this is what it says about "should":

> This word, or the adjective **recommended**, means that there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications must be understood and carefully weighed before choosing a different course.

However, the section on tessellation spacing, 21.3, says:

> The two additional segments **should** be placed symmetrically on opposite sides of the subdivided edge.

This section was copied from the OpenGL specification, so it simply may be a difference in the use of terminology. The OpenGL wording is unclear since it doesn't have as strict definitions as Vulkan. The current Vulkan wording however makes symmetric placing of the short segments a recommendation rather than a guarantee.

Was that the intent, or is this just a copy/paste bug and "should" ought to be changed to "must"?

**Comment by oddhack** [comment]
This should be fixed in the 1.0.19 spec update.
