### ISSUE TITLE
Invalid externsync atribute of param tag

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#265]
The xml schema Readme says `externsync` attribute of `<param>` must be either omitted or `="true"`.

Yet there are many occurences where it has different value (assumably some list of concrete objects needing ext. synchronization):

https://github.com/KhronosGroup/Vulkan-Docs/blob/eb9997129d/src/spec/vk.xml#L3108
https://github.com/KhronosGroup/Vulkan-Docs/blob/eb9997129d/src/spec/vk.xml#L3264
https://github.com/KhronosGroup/Vulkan-Docs/blob/eb9997129d/src/spec/vk.xml#L3662
https://github.com/KhronosGroup/Vulkan-Docs/blob/eb9997129d/src/spec/vk.xml#L3681
https://github.com/KhronosGroup/Vulkan-Docs/blob/eb9997129d/src/spec/vk.xml#L3683
https://github.com/KhronosGroup/Vulkan-Docs/blob/eb9997129d/src/spec/vk.xml#L3757
https://github.com/KhronosGroup/Vulkan-Docs/blob/eb9997129d/src/spec/vk.xml#L4578

**Comment by TobiasHector** [comment]
@oddhack I believe you made this particular change - not me. I mean I can give it a go at documenting it if you like, but I'm not 100% sure what the semantics here are, so it might be guesswork :).

**Comment by oddhack** [comment]
Hm, I've forgotten. If you happen to know the internal MR/issue that led to this change, maybe I can track down whatever happened. I vaguely recall getting improper VU statements and wanting to fix it but that's about it.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.32 spec update.
