### ISSUE TITLE
[Feature request] Extension to obtain PRIME fd for an image

### ISSUE THREAD

**Issue by flto** [KhronosGroup/Vulkan-Docs#266]
this could be useful for a number of reasons, e.g. rendering to framebuffer

**Comment by krOoze** [comment]
why would it need to be a full-blown extension?

**Comment by NicolBolas** [comment]
What is a "PRIME fd" anyway?

**Comment by ratchetfreak** [comment]
I think he's talking about [drm](https://en.wikipedia.org/wiki/Direct_Rendering_Manager) buffer sharing. There a chunk of vram is described as a file descriptor and can be passed to other processes for zero-copy sharing.

**Comment by cubanismo** [comment]
Various issues related to this are under discussion in Khronos.  We're aware of the usefulness of such a feature.

**Comment by krOoze** [comment]
By any chance, can this be achieved by using `VK_EXT_external_memory_dma_buf` extension?

**Comment by timofonic** [comment]
@flto @NicolBolas @tomaka @ratchetfreak @oddhack @cubanismo @krOoze Any news?

**Comment by ratchetfreak** [comment]
@timofonic extensions VK_KHR_external_memory and VK_EXT_external_memory_dma_buf matches what is requested here.

**Comment by krOoze** [comment]
@oddhack This looks closeable.

**Comment by krOoze** [comment]
@oddhack @flto This looks closeable.
