### ISSUE TITLE
Pipeline barrier inside a subpass dependency attachment layouts

### ISSUE THREAD

**Issue by ratchetfreak** [KhronosGroup/Vulkan-Docs#267]
currently when describing the limitations of a pipeline barrier inside a subpass with a self-dependency there is this line:

> If a VkImageMemoryBarrier is used, the image and image subresource range specified in the barrier must be a subset of one of the image views used by the framebuffer in the current subpass. Additionally, oldLayout must be equal to newLayout,

This layout should also be equal to the layout specified in the subpass description.

Should this be made explicit or left implicit as it is now?

**Comment by TobiasHector** [comment]
It's kind of hard to figure that out directly right now, but not sure if the spec language should call it out. A valid usage statement would probably be appropriate?

**Comment by ratchetfreak** [comment]
Then technically the entire **6.5.1. Subpass Self-dependency** section should be in the valid usage. As it has several important _must_ statements about the pipeline barrier.

**Comment by TobiasHector** [comment]
It should - that doesn't mean it shouldn't also have spec language though. Most (all?) of what's in the self-dependency section is stuff that isn't implied anywhere else.

**Comment by TobiasHector** [comment]
It doesn't feel like a spec language change is necessary here, but I will add the explicit validity statement.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.22 spec update.
