### ISSUE TITLE
Image layouts in renderpass creation

### ISSUE THREAD

**Issue by ratchetfreak** [KhronosGroup/Vulkan-Docs#268]
Currently there are not restrictions in the valid use in renderpass creation about the image layouts.

However ImageLayout states that Undefined and Preinitialized can only appear as initialLayout. 

So finalLayout should have the limitation that it cannot be Undefined or Preinitialized. Same with the layout in the VkAttachmentReference.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.22 spec update.
