### ISSUE TITLE
Inconsistent handling of VK_IMAGE_LAYOUT_PREINITIALIZED

### ISSUE THREAD

**Issue by chrisforbes** [KhronosGroup/Vulkan-Docs#269]
Spec is inconsistent about mismatches between oldLayout / renderpass initialLayout and the actual previous layout of an image subresource when the oldLayout / renderpass initialLayout is `VK_IMAGE_LAYOUT_PREINITIALIZED`.

Is the intent to support mismatches in the same manner as `VK_IMAGE_LAYOUT_UNDEFINED` ?

In VU for `CmdBeginRenderPass`:
>If any of the initialLayout members of the VkAttachmentDescription structures specified when creating the render pass specified in the renderPass member of pRenderPassBegin is not one of VK_IMAGE_LAYOUT_UNDEFINED or VK_IMAGE_LAYOUT_PREINITIALIZED, then each such initialLayout must be equal to the current layout of the corresponding attachment image subresource of the framebuffer specified in the framebuffer member of pRenderPassBegin.

In _11.8 Memory Aliasing_, the text seems to suggest a mismatch is useful for recovering an image subresource that has been made undefined by host access to an incoherent alias.

However, _11.4 Image Layouts_ says:
>The image layout of each image subresource must be well-defined at each point in the image subresource’s lifetime. This means that when performing a layout transition on the image subresource, the old layout value must either equal the current layout of the image subresource (at the time the transition executes), or else be VK_IMAGE_LAYOUT_UNDEFINED (implying that the contents of the image subresource need not be preserved).

**Comment by krOoze** [comment]
Duplicate of #248 ?

**Comment by chrisforbes** [comment]
So it is, thanks.
