### ISSUE TITLE
Clarification: Do subpass layout transitions occur for preserve/resolve attachment references?

### ISSUE THREAD

**Issue by chrisforbes** [KhronosGroup/Vulkan-Docs#270]
7.1 says: (emphasis mine)
> pInputAttachments is an array of VkAttachmentReference structures (defined below) that lists which of the render pass’s attachments can be read in the shader during the subpass, _and what layout the attachment images will be in during the subpass._ Each element of the array corresponds to an input attachment unit number in the shader, i.e. if the shader declares an input variable layout(input_attachment_index=X, set=Y, binding=Z) then it uses the attachment provided in pInputAttachments[X]. Input attachments must also be bound to the pipeline with a descriptor set, with the input attachment descriptor written in the location (set=Y, binding=Z).
> ...
> pColorAttachments is an array of colorAttachmentCount VkAttachmentReference structures that lists which of the render pass’s attachments will be used as color attachments in the subpass, _and what layout the attachment images will be in during the subpass._ Each element of the array correponds to a fragment shader output location, i.e. if the shader declared an output variable layout(location=X) then it uses the attachment provided in pColorAttachments[X].
> ...
> (no mention of layout for preserve/resolve)

Then in the description of VkAttachmentReference:
> /attachment/ is the index of the attachment of the render pass, and corresponds to the index of the corresponding element in the pAttachments array of the VkRenderPassCreateInfo structure. If any color or depth/stencil attachments are VK_ATTACHMENT_UNUSED, then no writes occur for those attachments.
> /layout/ is a VkImageLayout value specifying the layout the attachment uses during the subpass. The implementation will automatically perform layout transitions as needed between subpasses to make each subpass use the requested layouts.

For the preserved attachments and resolve attachments, are layout transitions specified in those VkAttachmentReference structures intended to occur, or are they ignored? (Is this actually a useful thing to do?)

I feel there should be a note to clarify the intended behavior.

**Comment by janharaldfredriksen-arm** [comment]
I think the layout transition will occur for resolve attachments since those attachments are accessed / written to by the subpass.

For preserved attachments the layout transition would effectively be ignored. Those attachments will either be used in a later subpass, in which case a new layout will be specified, or preserved all the way to the end of the render pass, in which case the VkAttachmentDescription::finalLayout will kick in.

**Comment by jeffbolznv** [comment]
Preserve attachments don't use VkAttachmentReference - they are just uint32_t's. So there is no layout and no layout transition for those. Resolve attachments do use the requested layout, though it may not be observable except as a performance side effect. IMO the spec should be consistent in how it describes all the attachment references, so I'll make a small change to how pResolveAttachments is specified.

**Comment by chrisforbes** [comment]
Oh of course, re preserve attachments :). Sounds good to me.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.22 spec update.
