### ISSUE TITLE
Vulkan and SPIR-V data structure layout rules seem unclear about corner cases.

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#274]
SPIR-V defines rules for applying `Offset`, `MatrixStride`, and `ArrayStride` to structure members used in `PushConstant` and `Uniform` blocks. As part of its validation rules for shader capabilities, it says that every member of a struct used for such blocks must have an `Offset`. In particular, it says:

> The `ArrayStride`, `MatrixStride`, and `Offset` Decorations must be large enough to hold the size of the objects they affect (that is, specifying overlap is invalid).

The parenthesized statement is the key one here, though I'm not quite sure how the rest of the statement leads to that conclusion. But let's take this to mean that two declarations in the same struct are not allowed to overlap in space.

How exactly is "overlap" defined? Allow me to explain.

Obviously, if two members have the same `Offset`, then they overlap. And if one member's `Offset` places it within another member's `Offset`+size, then they overlap. But there's a corner case here that's important: alignment: how do you determine the size?

Vulkan, section 14.5.4 specifies certain rules for the base alignment of various structures. And it specifies that `Offset`s cannot break those rules. For example, the base alignment of a 3-element vector is the same as the base alignment of a 4-element vector.

However, does that mean that a 3-element vector has the same _size_ as a 4-element vector? Would the following Vulkan-GLSL code trigger the "specifying overlap is invalid" clause in SPIR-V:

```
layout(std140) uniform UBO
{
  layout(offset = 0) vec3 a;
  layout(offset = 12) float b;
};
```

This would seem to violate *none* of the rules of Vulkan offsets and layouts. The `Offset` for `b` is a multiple of the base alignment of `b`. And `b` does not "immediately following a structure or an array;" the preceding declaration is a vector, which is neither a structure nor an array. As such, there is no requirement that `b`'s `Offset` be "greater than or equal to the next multiple of the base alignment of that structure or array."

The only rule that could disallow this is SPIR-V's rule about forbidding overlap. But the rules of Vulkan which say that `a` has a base alignment of a `vec4` doesn't actually say that it is the _size_ of a `vec4`. So by some readings of the specification, SPIR-V's overlap rule doesn't apply in this case. Given that reading of the specification, this would be allowed.

Is permitting such a declaration the intent of the specification? In either case, I think the wording needs to be made more clear.

FYI: the OpenGL specification seems equally nebulous about this. GLSL says that `offset` cannot place a variable "within the previous member of the block", but the OpenGL specification, like Vulkan, does not say that expanding the alignment of a type expands its size.

----

It should also be noted that there is nothing forbidding the declaration of variables out of order, either in SPIR-V or Vulkan:

```
layout(std140) uniform UBO
{
  layout(offset = 16) float b;
  layout(offset = 0) vec3 a;
};
```

That's explicitly forbidden in GLSL, which requires that each offset be larger than the previous one. But the equivalent SPIR-V code would be allowed, and nothing in Vulkan prevents this.

Is that intended? If it is intended (and it's not unreasonable), then that would complicate the fix for the previous issue, since the previously declared variable doesn't have to be the one preceding it. So a better way to be to simply declare in Vulkan that alignment based padding makes the type bigger. So any `offset`-based overlap would be forbidden explicitly by SPIR-V's rules.

**Comment by yavn** [comment]
I'm pretty sure the intent of "no overlap" is to forbid the case when fields alias each other, i.e. writing through one filed would modify the contents of another. Kind of like pointer aliasing.

float placed after vec3 both taking the size of vec4 seems perfectly legal to me. No alignment rules are violated. As for the overlap, no bits of float number would affect the value of vec3, so that's also fine.

Not sure about the out of order declaration, but in OpenGL you can have interface matching based on variable names and definition order only, rather than by explicit location assignment (as in Vulkan). That could explain the difference.

**Comment by NicolBolas** [comment]
> float placed after vec3 both taking the size of vec4 seems perfectly legal to me. No alignment rules are violated. As for the overlap, no bits of float number would affect the value of vec3, so that's also fine.

So what about this case:

```
layout(std140) uniform UBO
{
  layout(offset = 0) vec3 a[1];
  layout(offset = 12) float b;
};
```

That's actually _explicitly illegal_ in Vulkan. Why? Because of this rule:

> The `Offset` Decoration of a member immediately following a structure or an array must be greater than or equal to the next multiple of the base alignment of that structure or array.

Because `a` is an array, and `b` follows `a`, then `b`'s offset cannot be 12, since the base alignment of `a` is 16.

Is it reasonable for the padding of a `vec3`'s alignment to be able to be reused, yet not the padding of an array? Or that of a struct which happens to contain a `vec3`?

This seems _really_ inconsistent. If alignment/stride-based padding does not increase the size of a declaration, then padding should be able to be reused _everywhere_ it appears. And if it can't, if they want certain padding to be special and certain padding not to be, then the spec needs to be much clearer on which is which.

Also, given the above rule, this is may not be illegal:

```
layout(std140) uniform UBO
{
  layout(offset = 0) vec3 a[1];
  layout(offset = 16) float b;
  layout(offset = 12) float c;
};
```

Why? Because `c` is not a "member immediately following a structure or array". So 12 should be fine. Unless you consider "immediately following" to mean in the order of offsets, rather than in declaration order.

My main point is that *all of this* seems really unclear. If the intent is to allow variables to use padding bytes, then I say that there should be an _explicit_ statement to that effect. If the intent is to allow declarations and offsets to be ordered differently, then an explicit statement to that effect should be used and the "immediately following" language should be clarified.

**Comment by johnkslang** [comment]
Agree with @yavn.

An object, like a vec3 is just a vec3, it is not bigger than a vec3, and it contains no padding. Padding would be the space between the end of the vec3 and the beginning of the next member. The size of an object is the size of what it is, without padding.  The overlap means the objects themselves, which the spec says by:

> ...large enough to hold the size of the objects...

we might further clarify by adding "without padding"; will log this request.

You are indeed allowed to do this, as you noted the spec. allows:

```
layout(std140) uniform UBO
{
  layout(offset = 0) vec3 a;
  layout(offset = 12) float b;
};
```

> Is permitting such a declaration the intent of the specification?

Yes.  This is the intent and, as you figured out, there is nothing to disallow it.

And, yes, the rules are different for an array than they are for non-arrays.  This has historical roots, in hardware, that we won't be revisiting right now.  We just need to be clear what the rule set is, so everyone is on the same page.

I will bring back to Khronos the question about allowing out-of-order offsets.

**Comment by johnkslang** [comment]
For reference, the rules don't come only from the SPIR-V specification, but also from the Vulkan specification, at https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#interfaces-resources-layout.

**Comment by johnkslang** [comment]
Update: Khronos clarified that block-member offsets can be specified out of order. This clarification will appear in upcoming specification updates. As discussed earlier, there is still a requirement that the members don't overlap, which applies to the members proper, not their padding, in addition to the other requirements.

**Comment by johnkslang** [comment]
This is clarified in section 14.5.4 of the most recently published Vulkan API specification.
