### ISSUE TITLE
NULL vs VK_NULL_HANDLE inconsistency

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#276]
1)
The spec uses C's `NULL` (for pointers/arrays/cstrings) and then defines `VK_NULL_HANDLE` for handles ("Vulkan objects"):

> The reserved handle `VK_NULL_HANDLE` **can** be passed in place of valid object handles [...]

The generator script ( https://github.com/KhronosGroup/Vulkan-Docs/blob/5de77cf663c84cc2edfa355c49319dca0a869eb2/src/spec/generator.py#L1465 ) uses `NULL` for **dispatchable handles** instead. E.g. generates this in VU statement:

> If `instance` is not **`NULL`**, instance **must** be a valid `VkInstance` handle

OK, why not, but in that case: `VK_NULL_HANDLE` is used for dispatchable handle here:

>  `pCommandBuffers` **must** be a pointer to an array of `commandBufferCount` `VkCommandBuffer` handles, each element of which **must** either be a valid handle or `VK_NULL_HANDLE`
- [x] the above was changed to NULL in 1.0.27
- [ ] either dispatchable handles need to be specified as exception or the validity generator should use `VK_NULL_HANDLE`

2)
`oldSwapchain` uses NULL in the descriptive text ( "non-NULL")
- [x] Fixed in 1.0.21

3)
sometimes VK_NULL_HANDLE is `code:` and sometimes `sname:`
- [x] Fixed in 1.0.20 for core
- [ ] Still needs fixing in ~~WSI~~ extensions ( core chosen `dlink:`/`dname:` for this)

Most notably `debug_report_EXT` uses some unspecified VK_NULL_OBJECT and NULL for handles.

**Comment by courtney-g** [comment]
I've submitted this as a Khronos internal issue for discussion. Issue 393.

**Comment by oddhack** [comment]
This should be partly fixed in the 1.0.21 spec update. I think @courtney-g may have some further updates planned; if not, he can let me know to close this.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.41 spec update.

**Comment by krOoze** [comment]
@courtney-g There is still some problem with `object` of debug report extension which can be both dispatchable or non-dispatchable (but only `VK_NULL_HANDLE` is accepted in the spec).

**Comment by courtney-g** [comment]
Current text is:
  * pname:object gives the object where the issue was detected.
    pname:object may be ename:VK_NULL_HANDLE if there is no object
    associated with the event.

That seems to be okay. Or is there another spot I'm missing?

**Comment by krOoze** [comment]
@courtney-g I suppose that is okay - this being `uint64_t` is possibly bigger problem type-wise than this.
I just do assume the `object` is actually of the type `objectType` (even if null). AIS just being pedantic...

**Comment by courtney-g** [comment]
Yeah, the uint64_t is messy type-wise, but seemed better than having a couple dozen different callbacks each with their own object type.
