### ISSUE TITLE
Ability to update descriptor set if the command buffer is freed rather than executed.

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#277]
In 13.2.5, the specification says:

> The descriptor set contents bound by a call to `vkCmdBindDescriptorSets` may be consumed during host execution of the command, or during shader execution of the resulting draws, or any time in between. Thus, the contents must not be altered (overwritten by an update command, or freed) between when the command is recorded and when the command completes executing on the queue.

This implies that if you call `vkCmdBindDescriptorSets`, then destroy/reset the command buffer without executing those commands, that it is not legal to ever update those descriptor sets. I would expect that there be something about command buffers being destroyed or reset that would release that obligation.

**Comment by krOoze** [comment]
Reading it literally, If it's never executed, then the interval is non-existent. Therfore you would not violate that requirement, because your modification cannot be "between".

Freeing/resetting command buffers should release any and all resources, no? It can hardly be read in between if it's not longer even stored by the implementation.

**Comment by TobiasHector** [comment]
We discussed this internally and agree with @krOoze - destroying a command buffer means there's no execution, thus no interval. Re-clarifying here just seems like adding words to repeat something that's already quite well described - we'd have to make the same clarification in a bunch of other places, adding unnecessary verbage.

If there's some subtlety here we're missing then feel free to reopen the bug or raise a new one, but for now I'm going to call this resolved and close it.
