### ISSUE TITLE
[Specification][WSI] VkSurfacePropertiesKHR still exists in WSI spec where it should be renamed VkSurfaceCapabilitiesKHR

### ISSUE THREAD

**Issue by THofstee** [KhronosGroup/Vulkan-Docs#279]
Correct me if I'm mistaken, but there are still multiple instances in the WSI spec (primarily in revision notes and examples for `VkSwapchainKHR`) where the code is using `VkSurfacePropertiesKHR` to query for information about a surface. Nowhere in the WSI spec does it say that `VkSurfacePropertiesKHR `was renamed to `VkSurfaceCapabilitiesKHR`, nor are there any examples using `VkSurfaceCapabilitiesKHR`, but they seem to be the same thing.

I'd suggest adding a note in the revision history saying `VkSurfacePropertiesKHR `was renamed to `VkSurfaceCapabilitiesKHR`, and rewriting the example code to demonstrate this and avoid confusion.

**Comment by THofstee** [comment]
#207 also brings up similar points about `vkGetSurfaceFormatsKHR()`. There are a lot of deprecated functions present in the spec without being updated to their newer counterparts.

**Comment by krOoze** [comment]
Well...
> Renamed this extension and all of its enumerations, types, functions, etc. This makes it compliant with the proposed standard for Vulkan extensions.

Or it may be one of those changes with internal issue number which we have no access to (there they secretly store their evil plan to take over the world or something :smiling_imp: ).

What I am trying to say is the revision history is currently almost useless to us (as non-members). Besides, that change occured before 1.0.0. Therefore I think such note is not necessary.

As for the examples, I would doubt that is the only problem in them.... (e.g. 1. the unnecessary loading and thus using non-canonical command names in them 2. overflows the code block). It is simple enough (if annoying) job, I would offer to PR it (though I have enough unaccepted PRs as it is and not sure if I create some copyrighty-political problem instead by them deterring progress)

**Comment by oddhack** [comment]
@krOoze until we are able to sort out a contributor license agreement that allows us to accept PRs from outside Khronos without risk of IP contamination, we will be unable to accept any but the most trivial PRs. I wish this had been resolved already, but corporate IP lawyers are involved and it will get done whenever it gets done. There probably isn't much point in your creating additional PRs at this time, vs. creating issues which we'll be able to respond to more rapidly.

There's an active issue on reviewing all the code samples to make sure they're actually valid code, but the review is not complete yet.

**Comment by ianelliottus** [comment]
I'll look at this next week (I'm on vacation most of this week).

**Comment by oddhack** [comment]
Ian's changes are in the 1.0.26 spec update. I believe the WSI folks plan to move the remainder of the WSI sample code entirely out of the spec and refer to the LunarG demos instead, in the near future.
