### ISSUE TITLE
Validity of information obtained from `vkGet` and `vkEnumerate` is insufficiently specified

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#280]
In the specification it is not (usually) specified under what conditions information returned from `vkGet*` and `vkEnumerate*` commands remains valid (i.e. if the information still matches the internal state of Vulkan).

Of course, sometimes it is common sense it is invariable, sometimes the opposite. Sometimes it is even prerequisite to be constant for rest of Vulkan to work correctly. But that actually makes it worse (you can't form an assumption common to all the commands).

Anyway, I think it should get explicitly specified, lest people will get ideas e.g.:
1) http://stackoverflow.com/questions/38296181/can-vulkan-layers-change-at-runtime
2) issue #247

**Comment by oddhack** [comment]
This should be fixed in the 1.0.26 spec update.
