### ISSUE TITLE
a2x.py not found.

### ISSUE THREAD

**Issue by renelindsay** [KhronosGroup/Vulkan-Docs#281]
When following the "Build The Spec" instructions in README.html, I have installed all the dependencies, listed under "Software Dependencies", but when I run "make all", I get the following error:

/bin/sh: 1: a2x.py: not found
Makefile:145: recipe for target '../../../out/1.0/xhtml/vkspec.html' failed
make: *** [../../../out/1.0/xhtml/vkspec.html] Error 127

It seems the Makefile references a2x.py, but this file is not included in Vulkan-Docs, or any of its listed dependencies.

**Comment by baldurk** [comment]
I think the a2x executable depends on platform and maybe other things.

Try running `A2X=a2x make`. You might also need `ASCIIDOC=asciidoc` also.

**Comment by renelindsay** [comment]
That works for me (Ubuntu 16.04), thanks Baldur.
Would it be prudent to fix this in the Makefile, or make a note of it in the Readme.html?

**Comment by baldurk** [comment]
There's nothing to 'fix' necessarily, it's just a platform configuration setting with a default that doesn't work for you. The makefile could maybe be made smarter or have a wrapper script to detect the right executable and use it but I imagine that's very low priority behind more important issues for @oddhack to sort out. See also: #22 #252.

It would be worth noting in the readme though - I actually thought Jon had added a note to the readme but upon scanning through I can't see anything.

**Comment by renelindsay** [comment]
How about tweaking the makefile to check the current OS, and then select the appropriate filename,?Maybe something along these lines?

ifeq ($(OS),Windows_NT)
      ASCIIDOC ?= asciidoc.py
      A2X ?= a2x.py
else
      ASCIIDOC ?= asciidoc
      A2X ?= a2x
endif

**Comment by oddhack** [comment]
@renelindsay there are a variety of environments being used on Windows (Cygwin for sure, and I think two others have been mentioned). So I'm not sure that changing the invocation names purely based on the OS variable. But I'm willing to try it out with the Khronos members and see if anyone reports problems.

**Comment by krOoze** [comment]
Hmm... wouldn't simple check for the existence of `a2x.py` file suffice?

**Comment by renelindsay** [comment]
Hi Petr,

Do you mean something like this?

ifneq ($(wildcard /usr/bin/a2x),)
ASCIIDOC ?= asciidoc
A2X ?= a2x
else
ASCIIDOC ?= asciidoc.py
A2X ?= a2x.py
endif

**Comment by krOoze** [comment]
^ Yeah, something (exactly) like that.
I am not much used to Makefile and Shell script. Does it have to be absolute path in the condition expr?

**Comment by renelindsay** [comment]
The condition expr failed without the absolute path, which is why I checked
for OS instead.

**Comment by krOoze** [comment]
what about `which a2x.py` (includes PATH and returns 0 on found and 1 if no such file found)?

**Comment by renelindsay** [comment]
I'm happy with whatever solution works on both windows and linux.
On Windows, "which" would require Cygwin though.

**Comment by krOoze** [comment]
^ Oh right, damn. What about `ifneq ($(shell a2x.py --version),)`? :sweat_smile:

**Comment by renelindsay** [comment]
That works for me. :)
But, how about:

ifneq ($(shell a2x.py --version 2>/dev/null),)

...to also suppress the "make: a2x.py: Command not found" error message.
(Thanks Dustin Graves.)

**Comment by oddhack** [comment]
@renelindsay we don't actually *know* the full range of build environments people are using, so it's hard to be confident that arbitrary shell and tool and Makefile recipes are available everywhere. The only way to really tell is to push a change and see if people complain about it :-( Maybe someone who knows autoconf can help us out?

**Comment by krOoze** [comment]
@renelindsay  Well, on pure Windows, it will create/write to X:\dev\null file. But I think the rest of the `Makefile` is reliant on Unix-like anyway, so I say go with it.

I tried to silence stderr output or extract exit code from Makefile side(in platform agnostic matter), but apparently even those elementary things are impossible to do in make.

BTW Is the switch even needed anymore? I have both `a2x.py` and `a2x` even on Windows/Cygwin anyway.

**Comment by oddhack** [comment]
I revamped the Makefile in the 1.0.22 spec update to invoke asciidoc / dblatex or asciidoc / xsltproc explicitly instead of via a2x. This is also helpful because a2x obscures or completely suppresses visibility of errors in the intermediate stages. I don't think this really *solves* the general problem, but it probably solves the specific complaint in this issue, so closing.
