### ISSUE TITLE
vulkan.h does not properly detects LP64 on x32 platform

### ISSUE THREAD

**Issue by khimru** [KhronosGroup/Vulkan-Docs#282]
If I understand correctly VK_DEFINE_NON_DISPATCHABLE_HANDLE is supposed to used 64-bit int as a handle on 32-bit platforms and 64-bit pointer on 64-bit platform.

The existing check does not work for x32 platform ( https://en.wikipedia.org/wiki/X32_ABI ) because it defines `__x86_64__` symbol and thus pointer is used in place of 64 bit int.

Both GCC and CLANG (two compiler with x32 support) define `_ILP32` and `__ILP32__` in that mode and also `__SIZEOF_POINTER__` is defined as 4. Additionally CLANG (but not GCC!) defines `__POINTER_WIDTH__` as 32 in that mode (it's 64 in 64bit mode).

**Comment by THofstee** [comment]
If you use a backtick `` ` `` on either side of your word like so: `` `hello` `` then it gets formatted as a code black and lets you enter `__POINTER_WIDTH__`

**Comment by ratchetfreak** [comment]
You can also hit the `<>` button in the toolbar.

**Comment by krOoze** [comment]
Yes, it must be 64 bit integer type (Object Model chapter):
> Non-dispatchable handle types are a 64-bit integer type

Do you have reason to believe `__x86_64__` (BTW non-standard) macro is defined on non 64-bit environments?

Of course the `__LP64__` might be better as you propose.

**Comment by TobiasHector** [comment]
Well I suppose this was bound to happen eventually :D.

So I was the one who added these macros a while ago, and we basically added MORE macros to make sure that every platform was covered.

We should, at a minimum, add an assert to check the size of the handles IMO.

I'll have a think about how to solve this for x32 without breaking other platforms...

**Comment by philiptaylor** [comment]
The x32 ABI specification (https://sites.google.com/site/x32abi/documents) chapter 7 defines the preprocessor symbols that should be available (where "ILP32" means "x32", and "LP64" is the traditional 64-bit mode). https://wiki.debian.org/X32Port suggests "`defined(__x86_64__) && defined(__ILP32__)`" is the most portable combination to check.

**Comment by krOoze** [comment]
I see, they hijacked the old macro for x32 purposes...
Well then, robustly that would be  `( defined(__LP64__) || defined( __x86_64__) ) && ! defined(__ILP32__)` to account for both old and new behavior. (That's deliciously ugly :yum: )

BTW what about the `else` `uint64_t` case? Shouldn't that be something like `typedef struct object##_t{ uint32_t handle; } object;` to enjoy the same type safety?

**Comment by philiptaylor** [comment]
If you mean their use of `__x86_64__`, I don't think that's hijacking - x86-64 is the name of an ISA, not an ABI, and the x32 ABI still uses the x86-64 ISA, so it seems perfectly legitimate.

Non-dispatchable handles can be set to `VK_NULL_HANDLE`, and I don't think that would be possible if you had type-safe structs.

**Comment by ratchetfreak** [comment]
@philiptaylor unless you override the assignment operator or used another implicit conversion, but that's C++ at least.

**Comment by krOoze** [comment]
@philiptaylor Legitimate hijacking is still hijacking.... could have just as easily used new predefined macro.

Oh... darn you C. There must be some evil hack for that too :imp:...
I wonder if: `#define VK_NULL_HANDLE {0}` would work...

**Comment by jeffbolznv** [comment]
FWIW, we tried to do type-safe structs before release, and gussied it up as best we could with C++, but it ultimately had problems we couldn't resolve and we abandoned it.

**Comment by krOoze** [comment]
Well, it's C, no point trying to teach old dog new things.
It's bad the layers can't probably catch all errors of this kind.

**Comment by philiptaylor** [comment]
I think a layer should be able to check type-correctness of non-dispatchable handles by mapping every (type, uint64_t value) pair onto a unique uint64_t before returning them to the application, and then doing the opposite mapping and verifying the type when receiving handles from the applications. It looks like `VK_LAYER_GOOGLE_unique_objects` doesn't do that now, it maps just the values and ignores types, but I don't see why it couldn't check types too. (Still wouldn't be as good as compile-time checking, but better than nothing.)

**Comment by ratchetfreak** [comment]
if unique_objects is closest to the implementation then the other layers will check correctness by ensuring only known handles get through.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.22 spec update (at least, there's a platform-detection macro improvement; I'm not sure if the full suite of issues discussed in this issue are addressed or not).
