### ISSUE TITLE
[Specification][Markup/Editing] Missing pname:s for vkGetPhysicalDeviceImageFormatProperties

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#286]
There are several missing `pname:`s in parameter descriptions for `vkGetPhysicalDeviceImageFormatProperties` command (e.g. `slink:VkImageCreateInfo.format` missing `pname:` before `format`):
https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/doc/specs/vulkan/chapters/features.txt#L3660

**Comment by oddhack** [comment]
This should be fixed in the 1.0.22 spec update.
