### ISSUE TITLE
Swapchain imageExtent type mismatch

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#289]
https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#VkSwapchainCreateInfoKHR says:

> A swapchain image is equivalent to a non-swapchain image created with the following VkImageCreateInfo parameters:
>
> VkImageCreateInfo Field | Value
> ------------------------|------
> extent | pCreateInfo->imageExtent

`VkImageCreateInfo::extent` is a `VkExtent3D`, but `VkSwapchainCreateInfoKHR::imageExtent` is a `VkExtent2D`, so there is a type mistmatch.

The value should probably be specified as `{ pCreateInfo->imageExtent.width, pCreateInfo->imageExtent.height, 1 }` or equivalent.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.24 update.
