### ISSUE TITLE
Wrong allowed extent values in Additional Image Capabilities

### ISSUE THREAD

**Issue by Dolkar** [KhronosGroup/Vulkan-Docs#290]
The allowed values are specified as:

>  For VK_IMAGE_TYPE_1D:
> - _maxExtent.width ≤ VkPhysicalDeviceLimits.maxImageDimension1D_
> - _maxExtent.height = 1_
> - _maxExtent.depth = 1_
> 
> For VK_IMAGE_TYPE_2D:
> - _maxExtent.width ≤ VkPhysicalDeviceLimits.maxImageDimension2D_
> - _maxExtent.height ≤ VkPhysicalDeviceLimits.maxImageDimension2D_
> - _maxExtent.depth = 1_
> 
> For VK_IMAGE_TYPE_3D:
> - _maxExtent.width ≤ VkPhysicalDeviceLimits.maxImageDimension3D_
> - _maxExtent.height ≤ VkPhysicalDeviceLimits.maxImageDimension3D_
> - _maxExtent.depth ≤ VkPhysicalDeviceLimits.maxImageDimension3D_

However, the entire point of the additional image capabilities is to express support beyond the minimum capabilities of the physical device by returning _maxExtent_ values greater than the appropriate _maxImageDimension_ limit as hinted here:

> In addition to the minimum capabilities described in the previous sections (Limits and Formats), implementations may support additional capabilities for certain types of images. For example, larger dimensions or additional sample counts for certain image types, or additional capabilities for linear tiling format images.

In addition, I believe the allowed extent values specification should take into account whether an image of type _2D_ has the _VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT_ set and compare against _VkPhysicalDeviceLimits.maxImageDimensionCube_ instead if it does.

**Comment by janharaldfredriksen-arm** [comment]
I agree on both points.

**Comment by TobiasHector** [comment]
> I agree on both points.

Ditto. I didn't realise we hadn't fixed the first point already, actually.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.44 spec update.
