### ISSUE TITLE
VU would allow creating cube non-2D image

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#293]
There's no VU statement for `VkImageCreateInfo` that would disalow creating `VkImage` with `VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT` and `VK_IMAGE_TYPE_1D` or `VK_IMAGE_TYPE_3D`.

(I assume only `VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT` + `VK_IMAGE_TYPE_2D` combination is supposed to be valid.)

**Comment by oddhack** [comment]
Should be fixed in the 1.0.24 update.
