### ISSUE TITLE
xcb_connection_t* constant when passed to a command?

### ISSUE THREAD

**Issue by Mervill** [KhronosGroup/Vulkan-Docs#295]
Shouldn't `xcb_connection_t*` here be `const`?
```xml
<command>
<proto><type>VkBool32</type> <name>vkGetPhysicalDeviceXcbPresentationSupportKHR</name></proto>
<param><type>VkPhysicalDevice</type> <name>physicalDevice</name></param>
<param><type>uint32_t</type> <name>queueFamilyIndex</name></param>
<param><type>xcb_connection_t</type>* <name>connection</name></param>
<param><type>xcb_visualid_t</type> <name>visual_id</name></param>
</command>
```
```xml
<param>const <type>xcb_connection_t</type>* <name>connection</name></param>
```

Context: I'm writing C# bindings for Vulkan. The binding generator I've written assumes that non-constant pointers represent objects that should be returned to the caller, since the lack of `const` suggests that the value will be mutated.

The same issue might exist for `wl_display*` in `vkGetPhysicalDeviceWaylandPresentationSupportKHR`

```xml
<command>
<proto><type>VkBool32</type> <name>vkGetPhysicalDeviceWaylandPresentationSupportKHR</name></proto>
<param><type>VkPhysicalDevice</type> <name>physicalDevice</name></param>
<param><type>uint32_t</type> <name>queueFamilyIndex</name></param>
<param>struct <type>wl_display</type>* <name>display</name></param>
</command>
```
```xml
<param>const struct <type>wl_display</type>* <name>display</name></param>
```

And also for `MirConnection*` in `vkGetPhysicalDeviceMirPresentationSupportKHR`

```xml
<command>
<proto><type>VkBool32</type> <name>vkGetPhysicalDeviceMirPresentationSupportKHR</name></proto>
<param><type>VkPhysicalDevice</type> <name>physicalDevice</name></param>
<param><type>uint32_t</type> <name>queueFamilyIndex</name></param>
<param><type>MirConnection</type>* <name>connection</name></param>
</command>
```
```xml
<param>const <type>MirConnection</type>* <name>connection</name></param>
```

**Comment by cubanismo** [comment]
No, I don't think we can assume these values are constant.  Performing operations such as sending data over the connections may mutate them.

**Comment by ianelliottus** [comment]
I'd like clarity on whether these values should be constant.

If they are, I'm wondering if there's more to it than what's proposed in this issue.  I'm looking at the "vulkan.h" header, and I see that pointers of these types are not "const" for the Vk*SurfaceCreateInfoKHR structs.  I also see that the Display pointer for the Xlib struct/function are also not "const", and it seems like they should be (unless @cubanismo is correct, that these values can be mutated when the Vulkan implementation uses them).

Thoughts?

**Comment by cubanismo** [comment]
Sorry, I should have been less ambiguous: I know they can't be const.  Using them in almost any way will mutate them, and they're there so the drivers implementing the WSI functions can use them when determining support for a given display server instance.  These are pointers to structures that represent the state of a connection to a native window system, and contain variables such as mutexes, available buffer space, event status, and other library internals that are modified by most of the native connection layer functions that a driver would use to communicate with the display servers they represent.

If anyone still doubts this, please see the source code to the X, Wayland, and Mir client libraries.

**Comment by ianelliottus** [comment]
Thanks for the explanation @cubanismo.  I was looking into this when your answer came.  I agree.  I think this issue should be closed, with no change.  I'm hoping that @Mervill will agree.  True?

To summarize:

Putting a "const" in front of those parameters/members (e.g. "const Display* dpy" or "const xcb_connection_t* connection") would mean that everything within the structs couldn't be changed, which would destroy the usefulness of those pointers to the the ICD.  Putting a "const" after the "*" (e.g. "xcb_connection_t* const connection") would mean that the pointer can't change, but the items within the struct can.  I don't see that as particularly needed/useful to the ICD.  Thus, no change seems warranted.

**Comment by oddhack** [comment]
@Mervill (speaking as someone unfamiliar with C#) does it make a difference to the C# interface whether a pointer parameter is used as "out" vs "in/out" (modified in place)? What would you want to do differently in those cases, if so? There's no way to express that distinction in C AFAIK..

**Comment by Mervill** [comment]
My C# code generator reads the Vulkan spec and generates bindings. If the generator gets a command that has return type `void` or `VkResult` (and the spec says the only valid success code is `VK_SUCCESS`) it looks for a non-constant pointer in the arguments and transforms it into a return type.

So for example 

``
VkResult vkCreateInstance(..., VkInstance* pInstance)
``

Becomes

```
// edited for brevity
public static Instance CreateInstance(...)
{
	var instance = new Instance();
	var result = vkCreateInstance(..., &instance);
	if(result != Result.Success)
		throw ...
	return instance;
}
```

So because `xcb_connection_t*` is not constant, my generator would erroneously generate a binding with `xcb_connection_t` as the return type of `vkGetPhysicalDeviceXcbPresentationSupportKHR`, which has the side-effect of squashing the actual `VkBool32` return value.

Anyways, another issue with my generator has created a fix that will avoid this issue. Thanks to @cubanismo for confirming that `xcb_connection_t` is mutated, which is also helpful.
