### ISSUE TITLE
RENDER_PASS_CONTINUE secondary buffers executed outside of render passes

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#297]
`vkCmdExecuteCommands` says:

> If `vkCmdExecuteCommands` is being called within a render pass instance, any given element of `pCommandBuffers` must have been recorded with the `VK_COMMAND_BUFFER_USAGE_RENDER_PASS_CONTINUE_BIT`

But I don't see anything specifying the opposite of that, i.e. that if it's being called outside a render pass instance then the secondary buffers must have been recorded without `RENDER_PASS_CONTINUE`.

I think that means I could record a bare `vkCmdDraw` (with no render pass commands) into a `RENDER_PASS_CONTINUE` secondary buffer, then execute it in a primary buffer outside of a render pass, which wouldn't make sense and ought to be forbidden.

**Comment by krOoze** [comment]
Well, you still can't do that because:
> [`pInheritanceInfo`->]`renderPass` is a `VkRenderPass` object that **must** be compatible with the one that is bound when the VkCommandBuffer is executed if the command buffer was allocated with the `VK_COMMAND_BUFFER_USAGE_RENDER_PASS_CONTINUE_BIT` set.

^ BTW the "allocated with" is wrong and should be "begun".

also perhaps more clear hint:
> `VK_COMMAND_BUFFER_USAGE_RENDER_PASS_CONTINUE_BIT` indicates that a secondary command buffer is **considered to be entirely inside a render pass**. If this is a primary command buffer, then this bit is ignored.

**Comment by philiptaylor** [comment]
The first of those statements doesn't really say you mustn't execute the `vkCmdExecuteCommands` outside a render pass - it just says something that's nonsensical if you do (because it's falsely assuming there is a `VkRenderPass` bound).

I agree the intention is that it shouldn't be allowed, but I think in general the specification's requirements need to be explicitly stated, they shouldn't have to be deduced through reductio ad absurdum.

I interpret the second of those statements as simply meaning that it's treated as inside a render pass for the purposes of vkCmd commands that says "This command must only be called inside of a render pass instance", and not implying anything about how it can be used in a `vkCmdExecuteCommands`.

**Comment by krOoze** [comment]
> The first of those statements doesn't really say you mustn't execute the vkCmdExecuteCommands outside a render pass [...]

It kinda does imply it (if you declare RENDER_PASS_CONTINUE). You simply can't do it (maybe for different reason -- but still can't -- that was my point)

But yeah definitely, improvements should (and can) be made.

Also AIS said, there is already one error in that paragraf. And it's something that looks definitely like it belongs in some VU section. It was probably forgotten there and should be revised....

> I interpret the second of those statements as simply meaning that it's treated as inside a render pass for the purposes of vkCmd commands

Speaking reductio ad absurdum...
but yeah, I quoted it as "hint", because the descriptive texts usually have looser language and it is bit harder to decode if they are specifying anything or are more semantic.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.24 update.
