### ISSUE TITLE
Implications of aliasing on size/alignment requirements

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#298]
Consider some hypothetical but plausible-seeming device with the following behaviour:

Say I allocate a 4-byte buffer with usage=`VK_BUFFER_USAGE_STORAGE_BUFFER_BIT`, which `VkGetBufferMemoryRequirements` says has a size requirement of 4 and an alignment requirement of 64 (which (in this hypothetical device) is the cache line size of the shader unit's non-coherent L1 cache that is used for all shader buffer accesses).

Then I allocate a 4-byte buffer with usage=`VK_BUFFER_USAGE_TRANSFER_DST_BIT`, which has a size requirement of 4 and an alignment requirement of 1 (because the transfer unit bypasses the caches and can write to arbitrary bytes in RAM).

Then I allocate a 64-byte `VkDeviceMemory`, bind the first buffer with `memoryOffset`=0, and bind the second buffer with `memoryOffset`=4.

According to https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#resources-memory-aliasing , these two buffers are not aliased because their memory ranges don't intersect. That means I can safely write to both buffers with no execution dependencies or memory dependencies between them. But what might actually happen is:

* A shader wants to write to the first buffer, so it reads the whole 64-byte cache line from RAM into the shader cache and updates the first 4 bytes of it in the cache.
* A transfer operation wants to write to the second buffer, so it writes straight to RAM.
* The shader cache eventually gets flushed, which writes the whole 64-byte cache line back to RAM, which clobbers the transfer's write.

Or a slightly different case:

* A compute shader wants to write to the first buffer, so it reads the whole 64-byte cache line from RAM into the shader cache and updates the first 4 bytes of it in the cache.
* A memory barrier executes on the second buffer with `dstStageMask`=`COMPUTE_SHADER`, `dstAccessMask`=`SHADER_WRITE`. That gets implemented as a cache invalidation operation on the shader cache - but it's invalidating a dirty cache line that contains the update from the first buffer, and some cache designs will simply drop the line without writing it back to RAM, losing the update. (I assume Vulkan doesn't want to mandate that `dstAccessMask` will get implemented as flush-then-invalidate instead of just invalidate, because I imagine that might be more expensive on some real devices.)

Those situations would be bad. The implication is that to avoid the problems, the implementation of `VkGet(Buffer/Image)MemoryRequirements` needs to ensure both size and alignment are multiples of the largest cache line size of all the non-coherent caches indicated by the buffer's usage flags (or something close to that, I think). That way, accesses/invalidations of one buffer won't touch cache lines that are shared by another buffer (unless they match the aliasing definition, in which case it's the application's responsibility to add barriers).

My concern is that that seems like a fairly subtle implication, and the specification doesn't give any signs that implementers need to think about this - it seems to ignore the issue of cache lines entirely, except for `nonCoherentAtomSize` - and it's impossible to write reliable conformance tests for this problem, so I find it hard to trust that every implementer would get it completely right. And as an application developer reading the spec, it makes me worry that I've missed some other alignment requirement specified elsewhere.

(At least the current Intel Mesa implementation does return size and alignment smaller than a cache line, although I think it's saved in most cases by the details of its cache design, but I'm not sure if that's intentional or luck, and I'm not convinced it won't fail in some more obscure cases.)

I'd be happier if the definition of `VkMemoryRequirements` included a comment like:

"Note: The implementation must determine size and alignment in a way that is consistent with the requirements for Memory Aliasing, for example by always rounding both up to the cache line granularity. If two buffers or images bound to the same `VkDeviceMemory` do not overlap according to their reported size and alignment, the application can access them concurrently without any observable aliasing issues being introduced by the underlying memory architecture."

That would at least provide some peace of mind that the issue has been considered, and a clear statement to point at when reporting bugs to implementers.

(I care about this now since I'm thinking about validation of memory accesses, which depends on an accurate understanding of aliasing and caches etc, so I want to make sure I agree with the spec.)

**Comment by jeffbolznv** [comment]
We did consider these sorts of issues before 1.0 release, and the only case we could come up with where concurrent accesses to neighboring memory are a problem (other than nonCoherentAtomSize, which is specific to CPU caching) were for framebuffer attachments (think compression). And we concluded that this spec language:

```
Image subresources used as attachments mustnot: be used via any
non-attachment usage for the duration of a render pass instance.
```

was sufficient to cover that one case.

**Comment by philiptaylor** [comment]
Do you mean you think there isn't a problem with concurrent writes to neighbouring memory (in the same cache line) through two different paths that aren't cache-coherent with each other (e.g. shader writes and transfers in some hypothetical device)?

I may be misunderstanding how GPU caches behave but I don't see how that can work - if a single cache line is made dirty in two caches at once (because there's no coherency protocol to stop it) then it's impossible to correctly merge the writes together again, so the application has to be prevented from ever getting into that situation (and I don't think the spec is currently clear about how to prevent that).

**Comment by krOoze** [comment]
I think it's a bad precedence to tell implementation **how** to do its job.

You assume some particular hardware architecture. For all we know it can run on unicorns supported by hierarchy of hampster wheels. A note would only tie everyone down to your assumed HW.

As long as the implementation can trick anyone that it upholds the API contract, then there's nothing wrong. I mean, if you can't even trust GPU to sandbox two separate/non-aliasing buffers from each other, then you can't trust anything.

**Comment by philiptaylor** [comment]
A note wouldn't tie anyone down since it's just a note, not a normative requirement. The Sparse Resources section already has quite a lot of implementation notes, which I think are very helpful for both implementers and application developers to understand how the features are expected to work on typical hardware architectures, even if it's possible that some other implementations might be quite different internally.

The spec already assumes a lot about the GPU hardware architecture, and particularly the memory dependencies and Coherent decorations etc imply a certain kind of cache architecture (i.e. a two-level design with multiple non-coherent caches split along the stage / access type boundaries and a second level that's coherent across the whole device, and sort of a third level that can be accessed from the host). It has to have a realistic conceptual model of typical hardware to drive the API design, so that drivers won't have to do complicated expensive translations of the API onto their own hardware to make it work correctly and efficiently. (Most real hardware is probably simpler than the conceptual model, with fewer caches and more coherency, but it's easy to translate the API onto a simpler model, so that's okay). I want that conceptual model to be more clearly defined, so it's possible to reason about it while being confident that implementations will be working from the same understanding of it.

**Comment by jeffbolznv** [comment]
> I may be misunderstanding how GPU caches behave but I don't see how that can work - if a single cache line is made dirty in two caches at once (because there's no coherency protocol to stop it) then it's impossible to correctly merge the writes together again

There are solutions to this - e.g. the L1 caches could have a coherency protocol, or could only write out dirty bytes. And based on the review we did, we concluded that it is only problematic in that one scenario on all the hardware we were considering.

**Comment by krOoze** [comment]
> A note wouldn't tie anyone down since it's just a note, not a normative requirement.

I remember the funny situation about MemoryTypes, when implementers implemented it acording to the simple sounding (also wrong) note, instead of reading the normative text (someone had the funny idea to describe the simplest thing by PhD level math there so everyone just TL;DR'd it :smile:)

AIS the spec already says what aliases and what doesn't. Do you see some hole/grey area in that definition or, respectfuly, what more do you want? Patronize the implementers to implement correctly what is already written, on their custom HW (which they are supposed to know best)?

BTW I found a statement in spec that is very similar to your proposed note:
> Adjacent buffers' or adjacent images' memory ranges can be closer than bufferImageGranularity, provided they meet the alignment requirement for the objects in question.

**Comment by philiptaylor** [comment]
> There are solutions to this - e.g. the L1 caches could have a coherency protocol, or could only write out dirty bytes. And based on the review we did, we concluded that it is only problematic in that one scenario on all the hardware we were considering.

Ah, thanks, that makes a bit more sense to me now - if it's safe to assume every cache is either read-only, or coherent, or write-through for non-thread-private data, or write-back with per-byte dirty tracking, (it sounds like those are the most common choices), or some equivalent magic, then I accept there shouldn't be any problems here.

(I was guessing some obscure ones might be more like CPU caches that I think are normally write-back with per-line dirty tracking, but if they're not then that's okay. I've tried to do a bit more research now, but it seems quite hard to understand as a layperson - I just see some scattered documentation of some aspects of shader data caches of some GPUs, and even less about any of the non-shader-data caches :-( .)

For framebuffer attachments, I think there are still some slightly tricky cases: you might be able to allocate two 2x2-pixel linear-tiled images, pack them side-by-side into a 32-byte VkDeviceMemory (if the implementation reports tight size/alignment requirements), and use one of them as a framebuffer attachment (in implementations that support linear-tiled attachments) concurrently with using the other as a transfer destination, without violating the "Image subresources used as attachments mustnot: be used via any non-attachment usage" requirement. Or you could allocate a single 2x2-pixel 2-array-layer image (where the implementation might not add much padding between layers), then use the first layer as an attachment and the second layer as a transfer destination, since the layers are separate subresources. Tiny linear images won't have framebuffer compression though, so as long as implementations with funny framebuffer attachment caches are aware if/when they need extra padding between images and between layers, I suppose it's all fine.

(Incidentally, "Image subresources used as attachments must not be used via any non-attachment usage for the duration of a render pass instance." seems unclear since I'm not sure what the "duration of a render pass instance" really means. Can I take a `VK_IMAGE_LAYOUT_GENERAL` image and render to odd-numbered pixels as an attachment, while a second queue does a `vkCmdCopyBufferToImage` that writes every even-numbered pixel, with no memory dependencies between them?)

> AIS the spec already says what aliases and what doesn't. Do you see some hole/grey area in that definition or, respectfuly, what more do you want?

Currently I don't trust the spec to be entirely correct and/or comprehensible on anything related to synchronisation, and it's hard to tell if a weird-sounding bit is a mistake or if it's poorly explained but actually sensible or if I'm just missing the point, so I'd like clarity on the weird-sounding bits (ideally as text in the spec so other people can understand it too).

**Comment by philiptaylor** [comment]
After thinking a bit more, I think I still understand why my concern here was invalid, so I'll close this.

About the more general issue of not knowing the rationale behind the spec's memory requirements, making it hard to understand the spec and hard to use it with some kind of reasonable intuition rather than just following arbitrary-sounding rules, I tried writing some rough explanation at https://github.com/philiptaylor/vulkan-sync/blob/master/memory.md (which has been endorsed by one person as "[not] horribly wrong", so I'm happy enough with that until someone points out more mistakes).
