### ISSUE TITLE
Inconsistent use of Vk*Flags vs Vk*FlagBits

### ISSUE THREAD

**Issue by 3b** [KhronosGroup/Vulkan-Docs#30]
Flags are defined as a pair of types: `Vk*Flags`, which is a typedef for `uint32_t`, and `Vk*FlagBits` which is an actual `enum`. Both are used to as the types of struct members and command params, so it isn't clear if there is some distinction being made or if all of the uses should have been `Vk*Flags`.

In particular, `VkSurfaceTransformFlagsKHR ` and `VkSurfaceTransformFlagBitsKHR` are both used as type of members in `VkSurfaceCapabilitiesKHR`.
Other examples include `VkShaderStageFlags`, `VkCompositeAlphaFlagsKHR`,  and `VkDisplayPlaneAlphaFlagsKHR ` where the `Flags` variant is used in some members and `FlagBits` is used in others, and `VkPipelineStageFlags ` where both variants are used as function params.

**Comment by 3b** [comment]
After reading the docs a bit more closely, I guess the difference is that `Vk*Flags` is a combination of the possible values, while `Vk*FlagBits` is only 1 specific value from the set.

**Comment by oddhack** [comment]
That's right. It gives a smidgen of additional compile-time safety in cases where we know only one bit can ever be set.
