### ISSUE TITLE
Incorrect 'optional' for 'vkEnumerateDeviceLayerProperties::physicalDevice' in the XML

### ISSUE THREAD

**Issue by andrewjw1995** [KhronosGroup/Vulkan-Docs#301]
If I'm not mistaken, the `physicalDevice` parameter should just be `optional="false"`, or have no optional attribute at all:
> physicalDevice must be a valid VkPhysicalDevice handle

It actually looks like the optional tag has just been copy-pasted from the pPropertyCount parameter below.

    <command successcodes="VK_SUCCESS,VK_INCOMPLETE" errorcodes="VK_ERROR_OUT_OF_HOST_MEMORY,VK_ERROR_OUT_OF_DEVICE_MEMORY">
        <proto><type>VkResult</type> <name>vkEnumerateDeviceLayerProperties</name></proto>
        <param optional="false,true"><type>VkPhysicalDevice</type> <name>physicalDevice</name></param>
        <param optional="false,true"><type>uint32_t</type>* <name>pPropertyCount</name></param>
        <param optional="true" len="pPropertyCount"><type>VkLayerProperties</type>* <name>pProperties</name></param>
    </command>

**Comment by oddhack** [comment]
Thanks. We agree and will fix it in the next spec update.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.23 update.
