### ISSUE TITLE
Editorial issues: Image and image view parameter compatibility table

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#304]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#resources-image-views says:

> Table 11.1. Image and image view parameter compatibility requirements
> ...
> `subResourceRange` and `viewType` must be compatible with the image, as described in the table below 

The table is above, not below. (And maybe it should refer to the table by name/number in case somebody is reading the spec without hyperlinks.)

---

The "View parameters" column refers to arrayLayers, but I think it should be layerCount instead, since presumably it's implicitly referring to the view's subresourceRange.

---

The table says:

> arrayLayers = 6×N

for cube arrays. It doesn't say N>0, so that implies arrayLayers = 0 is compatible, which doesn't sound right since the others all require arrayLayers >= 1. (Could be solved by #303 - if you can't create a subresource range with 0 layers then you can't have N=0 here.)

---

Each cell in the table is sensibly spread over multiple lines in the PDF spec, but squashed onto a single line in the HTML spec, which makes it a little bit harder to read.

**Comment by krOoze** [comment]
Also shouldn't the first column use the proper enums instead?
And what is the purpose of the "sampled" in the table (there's no difference where applicable)?

**Comment by oddhack** [comment]
I'll take a look at this. Most of it is straightforward. Sometimes convincing the various asciidoc toolchains to respect line breaks in the same way is not straightforward.

**Comment by oddhack** [comment]
Most of this will get addressed this week. The "purpose of MS/samples" question from @krOoze is because the "Image parameters" cell is different for the MS/non-MS cases. The line breaks inside cell issue is going to be relegated to the magical land of "we hope this will be cleaned up by asciidoctor when we finally manage to move to that" because none of us want to put a lot of time into figuring out what has to be tweaked. Or we might move over to the asciidoc HTML5 output format, which does seem to handle this properly, in the interim.

**Comment by krOoze** [comment]
@oddhack Well, obviously, but if I am not blind only the sample count changes. There are other Image parameters that could be in the first and change the second column (but are not). The question is, why is it important to have that there (i.e. why is it important WRT the ImageView -- what does it change in the third column)?

**Comment by philiptaylor** [comment]
It looks like it's sort of expressing the same information as the "Rules for viewType" at https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#textures-input-validation , regarding the `Dim`, `Arrayed`, `MS` properties of `OpTypeImage` relative to the image and image view.

It's not quite the same though, since that section says:

> If the image's `samples` is not equal to `VK_SAMPLE_COUNT_1_BIT`, the instruction must have `MS` = 1.

but it fails to say that if it *is* `1_BIT` the instruction must have `MS` = 0. The compatibility table does indicate that `MS`=1 is only valid with samples > 1, so it's a bit stricter.

Maybe it would help to label the table's column as "OpTypeImage parameters (Dim, Arrayed, MS)" so it's clear what those names are referring to, and then make sure it's consistent with the SPIR-V rules later on. Or remove that column entirely, to avoid being redundant with the SPIR-V rules.

(There's also this earlier line:

> This table also shows which SPIR-V OpTypeImage Dim and Arrayed parameters correspond to each image view type.

which is incomplete since it doesn't mention `MS`. It ought to end up being consistent with the table.)

**Comment by krOoze** [comment]
^ I see. The table multitasks... still could be nicer in two separate tables (one being Image creation vs ImageView creation, the second being SPIR-V compatibility VS Image.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.23 update. If there's something specifically actionable in the followon discussion, feel free to raise it as a new issue, but there's been a lot of drift from the original topic.

**Comment by krOoze** [comment]
@oddhack managed to fix the formating(PR #324).

I noticed one more thing. If the table does describe Image <=> ImageView compatibility, then the `baseArrayLayer` should be taken into account (e.g. should be `arrayLayers` &ge; `baseArrayLayer` + 1)
