### ISSUE TITLE
bufferImageGranularity aliasing range

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#307]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#resources-memory-aliasing says:

> A memory range aliased between an image and a buffer is defined to be the intersection of the memory ranges bound to the two resources, where each range is first bloated to be aligned to the `bufferImageGranularity`.

But https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#resources-bufferimagegranularity defines it in terms of (buffer | linear image) vs optimal image. A buffer and a linear image can be closer than `bufferImageGranularity` without aliasing.

To be consistent, I think it should be changed to something like:

> A memory range aliased between two resources where one is a buffer or a linear image, and the other is an optimal image, is defined to be the intersection of the memory ranges bound to the two resources, where each range is first bloated to be aligned to the `bufferImageGranularity`.

**Comment by oddhack** [comment]
Thanks. Agreed and we'll try to get this in this week (also, we are going to use "padded" instead of "bloated" as it's a more meaningful / formal term).

**Comment by oddhack** [comment]
This should be fixed in the 1.0.23 update.
