### ISSUE TITLE
VK_KHR_swapchain code examples out of date (?!)

### ISSUE THREAD

**Issue by PtrMan** [KhronosGroup/Vulkan-Docs#308]
There are multiple issues here, the code is old, sloppy, untested, not in git...

For example in Example 3 there is this comment:
// Need to transition image from presentable state before being able to render
which seems tbe wrong to me because my (modified) imlementation of this leads to a debug layer error:

layerprefix=DS message=Cannot submit cmd buffer using image (0x4) [sub-resource: aspectMask 0x1 array layer 0, mip level 0], with layout VK_IMAGE_LAYOUT_UNDEFINED when first use is VK_IMAGE_LAYOUT_PRESENT_SRC_KHR

which is done right (haven't tested it jet) in for example the intel tutorial
https://software.intel.com/en-us/articles/api-without-secrets-introduction-to-vulkan-part-2
at "Recording Command Buffers"

---

I think the prototypes of the functions got changed too. Thre are as I can recall some functions with missing parameters, wrong order, etc...

---

If you provide Code it should work with the latest sdk(s) (for validation). Don't include sloppy code examples because they are not helpful.

In an ideal world you could link github code samples in the doc.

**Comment by krOoze** [comment]
It was proclaimed in issue #279 that they are being reviewed.

**Comment by oddhack** [comment]
They are being reviewed pretty much at the bottom of our priority list. Personally I'd rather move them out into a sample code area where they could actually be compiled, and not have the spec full of difficult-to-test code fragments, but I don't know if anyone else in the WG agrees with me.

**Comment by cubanismo** [comment]
I prefer to keep them in the spec, and perhaps even make them a little more visible via links or moving them up into the spec proper.  People already frequently ask us how to do things that are clearly shown in the WSI example code, so I think further hiding them is a step in the wrong direction.

**Comment by krOoze** [comment]
@cubanismo Specification is not a tutorial.
I think they are in the spec partly by accident in the first place (because they are part of the "extension card" which contains changelog, name of the authors and other miscellanea, which are imported in whole into the spec)

**Comment by cubanismo** [comment]
@KrOoze Not that we can't revisit the decision, but it was not included by accident.

The rest of the spec includes example code inline where it is useful to clarify the concepts.  I don't see why the WSI code should be any different.  If it helps, the WSI example code could be refactored to be more in the style of informative snippets rather than the current lengthy stand-alone compilable excerpts.

Of course regardless of this discussion, the typos should and will be fixed.

**Comment by ianelliottus** [comment]
I will look at this (I'll work with @cubanismo) next week (on vacation most of this week).  I will look at some other WSI code-example problems as well.

**Comment by oddhack** [comment]
@ianelliottus please check if this can be closed after #279.

**Comment by krOoze** [comment]
It is a bit moot if they are to be removed as claimed in the Note.

Example 1 text should perhaps avoid "shouldn't" (potentially RFC word confusion; also shortened form).

Example 1: "Other examples, will directly call the relevant command, not through a function pointer."
Weird sequence of words and punctuation...

Example 3 period at the end of intro text (other example has it)

Examples 5 and 6 have enum markup issues

**Comment by ianelliottus** [comment]
As @krOoze pointed out, we intend to remove the WSI example code from the appendix part of the spec, at least for the VK_KHR_{surface|swapchain} extensions.  We intend for the cube demo (shipping in the Khronos/LunarG SDK) to serve as the up-to-date example code.  Please look there and file any remaining issues there (i.e. https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/demos/cube.c).  Thanks!
