### ISSUE TITLE
src/dstQueueFamilyIndex != IGNORED when not transferring ownership

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#309]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#VkImageMemoryBarrier says:

> - `srcQueueFamilyIndex` is the queue family that is relinquishing ownership of the image subresource(s) to another queue, or `VK_QUEUE_FAMILY_IGNORED` if there is no transfer of ownership).
> - `dstQueueFamilyIndex` is the queue family that is acquiring ownership of the image subresource(s) from another queue, or `VK_QUEUE_FAMILY_IGNORED` if there is no transfer of ownership).

Is it permitted to have `srcQueueFamilyIndex == dstQueueFamilyIndex`, when neither are `IGNORED`?

The Valid Usage doesn't forbid that case. But there isn't really any transfer of ownership happening, nor any relinquishment to nor acquisition from another queue family, so the above quote implies they're meant to be set to `IGNORED` instead.

If `srcQueueFamilyIndex == dstQueueFamilyIndex` is meant to be a permitted way of not transferring ownership, and is expected to have no performance cost, then I think it would be helpful to add a sentence to clarify that intention.

(I noticed this pattern in https://software.intel.com/en-us/articles/api-without-secrets-introduction-to-vulkan-part-2#_Toc445674489 and wasn't sure if it's a problem.)

(Also, the mention of "to/from another queue" should really be "queue family", and there's a trailing ")".)

**Comment by krOoze** [comment]
In that case, in VU should be stated the `srcQueueFamilyIndex` must be the current owner of the Image (not any valid QF).

**Comment by TobiasHector** [comment]
So I think this is deliberately allowed - much in the same way that you are *allowed* to call vkDraw with a count of `0`. It's redundant but not a real problem to do it. Possibly it should be a warning in the validation layers that it's suboptimal - maybe raise a bug there? I don't think we could guarantee that there's *no* performance cost, at least not without polling everyone...

There are obviously some other minor things that need fixing though, I'll raise an MR internally for those.

**Comment by TobiasHector** [comment]
Whoops this should've been closed a few weeks ago. The following paragraph recently added to the spec makes this clear:

> If the values of srcQueueFamilyIndex and dstQueueFamilyIndex are equal, no ownership transfer is performed, and the barrier operates as if they were both set to VK_QUEUE_FAMILY_IGNORED.

So, src==dst means no ownership transfer, and that usage is fine.

Tobias
