### ISSUE TITLE
Buffer view sizes

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#31]
Section 11.2 (Buffer Views) says:

> * range is a size in bytes of the buffer view. If range is equal to VK_WHOLE_SIZE, the range from offset to the end of the buffer is used. If VK_WHOLE_SIZE is used and the remaining size of the buffer is not a multiple of the element size of format, then the nearest smaller multiple is used.
> * [...]
> * The value of range must be greater than 0

So I'm not allowed to create a buffer view with range == 0, but I am allowed to create one with offset == size_of_buffer and range == VK_WHOLE_SIZE which will have size zero. That seems inconsistent - if the implementation is happy to accept an empty buffer view via VK_WHOLE_SIZE, I don't see why it can't accept an explicit size of 0. Or if it's not happy with an empty buffer view, it shouldn't be happy with zero size via VK_WHOLE_SIZE either.

> * If range is not equal to VK_WHOLE_SIZE, the sum of offset and range must be less than or equal to the size of buffer 

What happens if offset > size_of_buffer and range == VK_WHOLE_SIZE? I don't see anything restricting it to point inside the buffer.

See also #27 about vkMapMemory which has a similar offset+size interface but with quite different requirements. I think it'd be less confusing if all the similar APIs had similar requirements.

**Comment by jeffbolznv** [comment]
We should resolve this consistently with #27: require offset < size of buffer, range <= size of buffer - offset.

**Comment by oddhack** [comment]
Done in the 1.0.5 spec update.
