### ISSUE TITLE
An logical error of example code in vkspec_wsi.pdf 

### ISSUE THREAD

**Issue by hustwarhd** [KhronosGroup/Vulkan-Docs#311]
There is an code error in F.4.7 Examples:
if ((pPlaneProps[j].currentDisplay == VK_NULL_HANDLE) **&&**
(pPlaneProps[j].currentDisplay == display))
bestPlane = j;
else
continue;

It should be:
if ((pPlaneProps[j].currentDisplay == VK_NULL_HANDLE) **||**
(pPlaneProps[j].currentDisplay == display))
bestPlane = j;
else
continue;

**Comment by krOoze** [comment]
@hustwarhd You can make code listing block by indenting it (or using the `<>` button)

It is somewhat known, the examples need some love (#308)...

**Comment by ianelliottus** [comment]
I will work on this, next week (on vacation most of this week).  I will look at some other WSI code-example problems as well.

**Comment by oddhack** [comment]
@ianelliottus please check if this can be closed after #279.

**Comment by ianelliottus** [comment]
A decision was made to remove the WSI example code from the specification appendix.  The example code for the VK_KHR_{surface|swapchain} extensions is being maintained in the cube demo that is shipped as part of the official Khronos SDK.

The example code mentioned in this issue (for the VK_KHR_display extension) is not included in the cube demo at this point.  A Khronos member is working on creating a suitable demo for that functionality.  I will ask that he update this issue when that is done.

**Comment by oddhack** [comment]
The sample code has been removed in the 1.0.30 spec and points to the cube demo. So the issue as posed has been solved, though hopefully the updated demo will result in an update to this issue when it's ready.
