### ISSUE TITLE
Review of the vk_platform.h chapter

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#314]
1)
> In addition to the macros described for `vulkan.h`, platform-specific macros specified and used in the included `vk_platform.h` file are described in this section.

a) s/described for/defined in OR in OR from vulkan.h, described in chapter X/ ? (BTW this is not the first time I noticed curious usage of "for" in the spec)

b) the second part of the sentence is bit twisted.

Let me suggest more direct:
> While previous section describes only macros from `vulkan.h`, this section describes macros in `vk_platform.h` file, which is itself included by `vulkan.h`.

2)
>  If not empty, the interpretation of this macro depends on the platform and compiler in use [...]

a) If I remember correctly, that applies even (and perhaps especially) with them empty.

b) Also interpretation should perhaps be prevented and the macro should be defined exactly to the intended behavior on given platform. So I am not sure what the sentence's purpose is other to remind us of the nature of language extensions.

3)
- [x] Fixed in 1.0.24

> If the `VK_NO_STDINT_H` macro is defined at compile time, it indicates that the system `<stdint.h>` does not define some required integer types, and `vk_platform.h` will declare fallback definitions of those types.

a) It is not clear whether Vulkan defines it or the user (aka the Application) is supposed to define it.

b)  Inspecting `vk_platform.h` I see that if the `VK_NO_STDINT_H` is defined then neither `<stdint.h>`  nor fallback definitions are created -- making the whole statement false.

4)
> When using different window systems with Khronos extensions, header files for those window systems **must** be included at compile time in order for the corresponding extension definitions to compile.

a) s/different/various/

b) s/window systems/windowing systems/

c) I think s/with/via/ is more appropriate.

d) s/compile time/compile-time/ ("compile time" more often means "time spent compiling")

e) s/to compile/to compile successfully/ is I think less colloquial

5)
> The Vulkan header files cannot determine whether or not an external header is available at compile time, so applications **must** include macros enabling those headers.

a) s/include/define

b) I let it slide in the previous sentence, but here it seems even less appropriate to use "**must**" here. I don't think I **must** (e.g. in a headless app). (The intended context seems to be "if you want to use PLATFORM_SURFACE", but that is not perfectly clear -- I think, sentences using the RFC keywords should have all the neccessary information to parse the introduced requirement, for it to have no ambiguity)

c) Not sure if stating motivation of the specificator in the specification is useful here.

6)
- [x] Changed to "Microsoft Windows" in 1.0.26 (may not be ideal if more platforms on Windows are added)

> Windows Win32

They use "Windows API", because of the obvious problem with the old name.

**Comment by oddhack** [comment]
(3) is fixed in the 1.0.24 spec update. Most of the rest is wordsmithing which is a low priority compared to other backlogged issues, but we'll get to it eventually.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.28 spec update.
