### ISSUE TITLE
MS SPIR-V flag for single-sampled images

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#316]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#textures-input-validation says:

> If the image's samples is not equal to `VK_SAMPLE_COUNT_1_BIT`, the instruction must have `MS` = 1.

But it doesn't say the opposite, i.e. that if samples is `1_BIT` the instruction must have `MS` = 0. I assume it ought to say that (otherwise the `MS` flag would seem a bit pointless, you could just always set it to 1 iff `Dim`=2D).

(Originally mentioned in #304.)

**Comment by oddhack** [comment]
This should be fixed in the 1.0.25 spec update.
