### ISSUE TITLE
VkCopyDescriptorSet with srcSet == dstSet

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#32]
In Section 13.2.4 (Descriptor Set Updates), VkCopyDescriptorSet is defined as copying descriptors from one set to another.

What happens if srcSet == dstSet? Is it like memcpy where only non-overlapping ranges are okay, or like memmove where overlapping ranges are okay, or is it not okay at all? The behaviour or restrictions should be specified.

**Comment by jeffbolznv** [comment]
It should be legal to copy within a set, and IMO we should follow memcpy rules.

**Comment by oddhack** [comment]
Done in the 1.0.5 spec update.
