### ISSUE TITLE
VK_FRONT_FACE(_COUNTER)_CLOCKWISE is misleading

### ISSUE THREAD

**Issue by tim37021** [KhronosGroup/Vulkan-Docs#320]
According to the spec,
_If frontFace is set to VK_FRONT_FACE(_COUNTER)_CLOCKWISE, a triangle with positive area is considered front-facing. If it is set to VK_FRONT_FACE_CLOCKWISE, a triangle with negative area is considered front-facing. Any triangle which is not front-facing is back-facing, including zero-area triangles._

The formula to calculate area that's used by vulkan has different sign from OpenGL's and the formula we usually use.
The spec has no mistake. Front face is defined by area. However the marco name VK_FRONT_FACE_COUNTER_CLOCKWISE will mislead someone that vertices declared in counter-clockwise order is considered front face.

I hope Vulkan can add additional macro like VK_FRONT_FACE_POSTIVE_AREA.

**Comment by krOoze** [comment]
You know, you can make that macro for yourself.
Otherwise it should be the same Winding Order nomenclature everybody expects.
It is somewhat made harder to mentally process, since the Y axis points down now (I just wish everybody would stick to one set of conventions - preferably the scientific one. Oh well...)

**Comment by tim37021** [comment]
I think vulkan spec should have clear definition on what is counter-clockwise order. In vulkan, counter-clockwise is the order we see on screen (or in vulkan's NDC coordinate which Y axis points down). For now, the spec only define counter-clockwise indirectly by sign of the area.

**Comment by pimanttr** [comment]
Keep in mind that images/framebuffers may not be on screen, so "down" is not a directly meaningful concept in the core spec.
That said, for images presented to the WSI, the convention "Y down" is used, and that's consistent with all supported windowing systems. This is opposed to OpenGL, hence why the sign of the formula was changed. A triangle with a positive area (according to the Vulkan formula) will appear counter-clockwise when presented to the windowing system.

**Comment by krOoze** [comment]
It's a specification, not a tutorial. One definition is exactly the amout of definitions you want in a specification.

Problem is perhaps on the reference pages, where altenative less mathy description of faceness could be provided.

**Comment by oddhack** [comment]
I don't see anything actionable in this issue, and the definition has been explained by @pimanttr, so closing.
