### ISSUE TITLE
Automatic layout transition dependency issues

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#322]
In `VkSubpassDependency` descriptions:

> [...] there is no subpass dependency from `VK_SUBPASS_EXTERNAL` to the first subpass that uses the attachment, then it is as if there were such a dependency with `srcStageMask` = `srcAccessMask` = `0` [...]

What does `srcStageMask` of `0` mean? (It is forbidden in dependencies, barriers, events and semaphore waits &mdash; i.e. everywhere else, so there's no analogy). Shouldn't that be `STAGE_TOP_OF_PIPE` instead?

> Similar rules apply for the transition to the `finalLayout`, using dependencies with `dstSubpass` equal to `VK_SUBPASS_EXTERNAL`

Is this sufficient description? Also the rules are not similar, they are more of a opposite.
And what about the no `VK_SUBPASS_EXTERNAL` dependency case?

**Comment by oddhack** [comment]
This should be fixed in the 1.0.35 spec update, as part of the synchronization language rewrite.
