### ISSUE TITLE
Description of VkPhysicalDeviceMemoryProperties refers to pMemoryRanges

### ISSUE THREAD

**Issue by cneumann** [KhronosGroup/Vulkan-Docs#325]
In the bullet list that describes the members of VkPhysicalDeviceMemoryProperties it currently says:
 - memoryTypeCount is the number of valid elements in the pMemoryRanges array. 

It should probably be: ... in the memoryTypes array.
 - memoryHeapCount is the number of valid elements in the pMemoryRanges array. 

It should probably be: ... in the memoryHeaps array.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.28 spec update.
