### ISSUE TITLE
typo: tesselation 

### ISSUE THREAD

**Issue by ratchetfreak** [KhronosGroup/Vulkan-Docs#327]
there are 3 instances of tesselation instead of tessellation 

in 14.6. Built-In Variables in the sections for `PointSize`, `Position` and `PrimitiveId`

each time in the sentence: 

> In a **tesselation** control, tessellation evaluation, or geometry shader, any variable decorated with ...

**Comment by krOoze** [comment]
The styleguide prescribes US spelling, so the tesse**l**ation is, I think, the correct variant.

**Comment by oddhack** [comment]
That will be the first entry in an exception list. We're not going to change the API and the term appears repeatedly there with LL.

**Comment by NicolBolas** [comment]
> The styleguide prescribes US spelling, so the "tesselation" is, I think, the correct variant.

That assumes that the US spelling is "tesselation". The Oxford English dictionary, in its catalog of *US spellings*, [makes it clear that "tessellation" is a perfectly valid US spelling](http://www.oxforddictionaries.com/us/definition/american_english/tessellation). Dictionary.com again [shows that "tessellation" is the preferred spelling, based on the Random House Dictionary](http://www.dictionary.com/browse/tessellation?s=t). Merriam-Webster (says that "tesselation" isn't in the dictionary](http://www.merriam-webster.com/dictionary/suggestions/tesselation).

Even *Google* will correct your spelling if you only use one "l". Indeed, it shows the results for "tessellation" by default, only showing the one "l" version if you insist by clicking a link.

I would say that there's enough evidence that "tessellation" is the preferred US spelling.

**Comment by krOoze** [comment]
Right! It's from "tessell".

Nobody probably has time to read styleguides anyway :smirk:. So probably wasted effort...

Hmmm, automatic spell check could be added. It just needs to skip some elements and keywords...

**Comment by oddhack** [comment]
The spelling is consistent in the 1.0.25 spec update. With two 'l's.
