### ISSUE TITLE
[Ecosystem(build)] Broken styleguide build

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#329]
`make styleguide` fails on a fresh copy of the repo, when done first.

It is missing the output folder check here:
https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/doc/specs/vulkan/Makefile#L227
as other targets have:
https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/doc/specs/vulkan/Makefile#L328

**Comment by oddhack** [comment]
This should be fixed in the 1.0.25 spec update.
