### ISSUE TITLE
[Specification] Bad table captions

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#330]
There are missing table captions for the following tables:

 - `vkGetEventStatus` return values table &mdash;  https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/doc/specs/vulkan/chapters/synchronization.txt#L429

- SPIR-V <-> Vulkan Image Format compatibility &mdash;  https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/doc/specs/vulkan/appendices/spirvenv.txt#L211

There are missing `etext:` or `ename:` decoration in the following:

 - Bit mappings table &mdash;  https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/doc/specs/vulkan/chapters/features.txt#L2785

 - Layout for pipeline cache table &mdash; https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/doc/specs/vulkan/chapters/pipelines.txt#L669

(decorative) In LOT MathJax elements are not properly underlined as a link:
 - Border Color _B_ table &mdash; probably MathJax bug, but could be easily fixed with small CSS tweak.

**Comment by oddhack** [comment]
The titles should be fixed in the 1.0.25 spec update. The MathJax thing we are not going to address.
