### ISSUE TITLE
List of name decoration/markup issues

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#331]
This is a consolidated list of minor formating issues not worth making separate Issue for each one.

I am gonna **add** to this list as I see something reading the spec and I am gonna **remove** fixed items (from time to time).

- Probably missing decoration for "height" and "depth" several times in `VkImageCreateInfo` VU section.
- All  auto-generated composite names in VU or in Synchronization section (e.g. `commandBufferCount` and `commandPool` in `vkAllocateCommandBuffers` VU and Synchronization section. or e.g. `pWaitSemaphores` and `pSignalSemaphores` in Synchronization section of `vkQueueSubmit`)
- `sizeof()` operators should perhaps be decorated too (e.g. in `vkCmdDrawIndirect` vkCmdDrawIndirect VU)
- In VU for `vkCmdSetDepthBias` there is some problem with the `o.0`
- lot of the extension appendixes (or how do you call em?) have various undecorated names (e.g. `gl_Position.y` in `VK_KHR_maintenance1`, or `sType` and `pName` in `VK_KHR_get_physical_device_properties2` extension appendix
- Words like "required" and variants are not purple (e.g. last item in `VkShaderModuleCreateInfo` VU)
- The extension names should perhaps have some decoration &mdash; they look weird in plain text. (e.g. "VK_KHR_surface" in 30.2. WSI Surface)
- Undecorated `may`s in 31. Extended Functionality chapter (counted 3x)
- In Features, Limits, and Formats ch. there's "Note on extensibility". I think the styleguide does not allow such type of Note.
- "NOTE" (in capitals) in 30.2.1. Android Platform
- There is twice "z coordinate" in plain text in vkCmdBlitImage description. ("z" should perhaps be italicized or something)
- Undecorated NULL in `vkEnumerateInstanceExtensionProperties` and `vkEnumerateDeviceExtensionProperties`
- Undecorated "may" in `object` desc. of `vkDebugReportMessageEXT`
- Undecorated `VK_ERROR_MEMORY_MAP_FAILED` in Note in memory chapter
- Undecorated `VK_ERROR_OUT_OF_DATE_KHR` in `vkGetSwapchainCounterEXT` descriptions.
- Undecorated and misnamed `DebugReportCallback` in `pUserData` parameter desc. of `PFN_vkDebugReportCallbackEXT`
- Undecorated `VkDisplayKHR` in `vkGetRandROutputDisplayEXT` descriptions
- Undecorated `VkInstance` in Note below `PFN_vkAllocationFunction`
- IMO mostly all the Vulkan entities should be turned into links for convenience
- Some composite names have unnecessary space around the `::` and `.`
- There are some "can not"s in the spec (should be "cannot")
- Badly decorated `slink::VkViewport::height` in `VK_KHR_maintenance1` appendix
- Undecorated "should" in `VK_KHR_incremental_present` appendix
- Undecorated `VkRectLayerKHR` under its VU
- `pName` instead of `pObjectName` in `VkDebugMarkerObjectNameInfoEXT` descriptions
- In Supported Queue Types row of table, if there are multiple types, then only the first one has first letter capitalized
- undecorated `device` in first VU of `VkSwapchainCreateInfoKHR`
- undecorated "vkCmd*" in Recording state definition
- weirdly decorated pAllocateInfo::commandBufferCount of `vkAllocateCommandBuffers`
- code:*PerViewNV in `VK_SUBPASS_DESCRIPTION_PER_VIEW_ATTRIBUTES_BIT_NVX` desc.
- undecorated PerViewNV
- undecorated VkDevice in 4.3.4. Queue Priority
-  `VkCmdPipelineBarrier` with capital V in `VK_EXT_sample_locations` appendix
- undecorated VK_ACCESS_COLOR_ATTACHMENT_READ_BIT in `advancedBlendCoherentOperations` descriptions
- undecorated `descriptorSetCount` in `vkAllocateDescriptorSets` VU
- `VkDescriptorSetLayoutCreateInfo` `flags` description links to `Flags` instead of `Bits`
- () after `vkAcquireNextImageKHR`  several times (e.g. after VkPresentTimeGOOGLE definition)
- clock_gettime (in `VkPresentTimeGOOGLE` desc.) should be decorated somehow
- "cthen" in `VkBufferImageCopy` VU
- "the the" (4x occurence in the spec)
- visible pname macro (4x: `vkCmdExecuteCommands` VU, `VkSubpassSampleLocationsEXT` VU, `VkBufferCreateInfo` VU, `VkBindImageMemoryInfoKHR` VU )
- unnecessary(\missing?) ";" in VK_KHR_shader_draw_parameters appendix
- VK_KHR_mirror_clamp_to_edge instead of VK_KHR_sampler_mirror_clamp_to_edge in `VK_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE` desc
- Broken Katex math in `VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM_KHR` desc.
- `features-limits-maxDiscardRectangles` link anchor exists twice if `VK_EXT_discard_rectangles` enabled
- misformated blocks below `oldSwapchain` description introduced in 1.0.62 and of the VU blocks
- " be already be" and undecorated VK_NULL_HANDLE in paragraph below the swapchain image creation parameters table
- vlCmdDrawIndexedIndirectCountAMD typo in changelog
- misformated block in Identification of Formats chapter
- undecorated VkExportSemaphoreWin32HandleInfoKHR in `VkExportSemaphoreWin32HandleInfoKHR` VU
- VkSurfaceTransformFlagBitsKH in `VkDisplaySurfaceCreateInfoKHR::transform desc.
- could use decoration for `s` in FragStencilRefEXT desc.
- misdecorated "*PerViewNV[] " in VkRenderPassMultiviewCreateInfoKHX desc.
- quotes should be "\` `"
- undecorated Terminology in Note of `VkSwapchainCreateInfoKHR::imageExtent`
- “_422” before `vkCmdImage copy VU s.
- weird markup of `maxMemoryAllocationCount` below `vkAllocateMemory`, which is both a link and a pname (introducing plink could help?)
- 3 broken links above vkGetDeviceQueue

**Comment by courtney-g** [comment]
vkEnumerateInstanceExtensionProperties does take a pLayerName so could return VK_ERROR_LAYER_NOT_PRESENT

**Comment by krOoze** [comment]
@courtney-g Of course. I know. But all of those above are only markup issues.
It actually **prints** "ename: " in the output html or pdf document! That is the problem.

**Comment by courtney-g** [comment]
Ah, okay, there is a space where there shouldn't be.

**Comment by oddhack** [comment]
I'm going to try and deal with this stuff, but TBH I'd like you to hold off on more minor typos of this nature. If it doesn't actually affect the functionality that's being described, it's really time-consuming for you to find it, quote it, create an issue, send it to us to figure out where in the text or XML it's being talked about, create an internal MR, get that signed off and into the update pipeline... it is just not worth any of our valuable time for this really minor stuff when there are lots of real specification and functionality issues to be worked.

I get that it can be offensive to people's sense of aesthetics to have something in an an inconsistent font or a parenthesis in the wrong size or any of a hundred other tiny things. It should be consistent, we have a style guide, all of this is very true.

But it *just takes too much time* to try and deal with this stuff in our current processes. Hopefully in the future when we get the contributor licensing agreement sorted out and it's possible to accept PRs on github there will be a lighter-weight path to the people who see these problems, proposing their own fixes for them.

**Comment by krOoze** [comment]
I just add issues indiscriminately as I find them (otherwise I would forget them, or have to keep my own book-keeping until you are willing to accept them). **I** am doing it for free, so technically it's a hobby, not wasted time :laughing: 

In this instance, I thought even it would be beneficial to make a consolidated issue, before people start adding these one item per issue. Then imagine the process, and net wasted time...

I understood your situation (seeing number of open issues constantly grow). I tried to mark those items, that break the text too much to be considered only esthetical.

On a positive note, I don't expect to make very many more esthetical Issues after this, #352 and those others existing ones that need finalization (and also after the asciidoctor transition hopefuly improving math loading). 

No offense, but that does sound like _issue tracker anxiety_. You are trying to fix it on the wrong side. Just gimme appropriate tag or milestone for such low-priority stuff.

It **is** a bit perverted seeing high-profile developers I see here (and know from all those conference videos) assumably fixing these. That contributor licence was needed from the start, while there are simple things to fix, oh well (still awesome choice having it O-S)...

**Comment by krOoze** [comment]
I am abandoning this for the sake of PR #600 , where I can show the formatting issues more directly.
