### ISSUE TITLE
Clarity on the what "device-specific" means for vkGetDeviceProcAddr

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#332]
Currently, the Vulkan specification says this about device-specific function pointers:

>  The overhead of this internal dispatch can be avoided by obtaining device-specific function pointers for any commands that use a device or device-child object as their dispatchable object. Such function pointers can be obtained with the command:

That is all it says; they're "device-specific". One would assume that they are specific to the `VkDevice` that they are passed. But since Vulkan recognizes the concept of physical devices, it is possible that it could allow the use of those pointers with multiple `VkDevice` objects from the same physical device.

Now, that's almost certainly not the intent, but it would be good to make that more clear. Perhaps adding this statement somewhere:

> Calling device-specific functions with any object that is not the `VkDevice` from which it was fetched, or with device-child objects from a device other than the `VkDevice` from which it was fetched, is undefined behavior.

Indeed, if multi-device features start showing up in Vulkan 1.1 or later, then we will need a stronger statement about device function pointer compatibility. A statement like the above would be a good start.

**Comment by krOoze** [comment]
PR #321 of @courtney-g posted for public review should fix that. It lists the functions in table form and for those obtained from GDPA states they must be called with the same `device`. (And of course the same for GIPA and the appropriate commands get that way).

**Comment by oddhack** [comment]
This should be addressed in the 1.0.27 spec update.
