### ISSUE TITLE
Missing captions of Figures

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#334]
These figures are missing captions:
- Texel coordinate system  linear &mdash; https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/doc/specs/vulkan/chapters/textures.txt#L121
- Texel coordinate system nearest &mdash; https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/doc/specs/vulkan/chapters/textures.txt#L149
- Texel derivative functions &mdash; https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/doc/specs/vulkan/chapters/textures.txt#L819

BTW they load slowly in Firefox having excesive ~ 2500x1500 resolution in PNG. They could benefit from conversion to SVG.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.32 spec update.
