### ISSUE TITLE
vkCreateDebugReportCallbackEXT can succeed, but never errors.

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#337]
vk.xml has a `successcodes` attribute for the `vkCreateDebugReportCallbackEXT` command. But it has no corresponding `errorcodes` attribute. That suggests that the function returns `VkResult`, but can only ever succeed. It is the only such function that has successes but no errors.

**Comment by krOoze** [comment]
It takes allocation callbacks, so at least `VK_ERROR_OUT_OF_HOST_MEMORY` should be in there (and so return a VkResult)...

**Comment by oddhack** [comment]
This should be fixed in the 1.0.25 spec update.
