### ISSUE TITLE
required values for sType members in vk.xml not in useful form

### ISSUE THREAD

**Issue by 3b** [KhronosGroup/Vulkan-Docs#34]
The `sType` struct members (and a few others) have xml comments saying they "Should be" or "Must be" some value. Parsing it out of the comment by hand is annoying, particularly when the surrounding text is inconsistent. An attribute on the member would be much more useful.

**Comment by oddhack** [comment]
That should be pretty straightforward, given that we're already capturing possible error codes elsewhere in the XML. I'll take a swat at it. Thanks for the suggestion.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.23 update.
