### ISSUE TITLE
Why is this still a thing???? /bin/sh: 1: asciidoc.py: not found

### ISSUE THREAD

**Issue by salamanderrake** [KhronosGroup/Vulkan-Docs#341]
Its been how long and yet this still hasn't been changed?

**Comment by philiptaylor** [comment]
It's still a thing because it's a low priority and there's an easy workaround (probably `make ASCIIDOC=asciidoc`), and it's always a bit tricky to make platform-dependent changes since they might break other platforms, and there are plenty of other problems for people to spend their time on first.

**Comment by salamanderrake** [comment]
Thats a lame excuse, its a simple fix.

**Comment by oddhack** [comment]
If you know of a robust way of detecting and setting asciidoc vs. asciidoc.py in the Makefile at build time, using GNU make functionality that will actually work on all the OSes and the various Windows Unix emulation environments that people are building in, that would be handy. Setting the variables in a login script solves the problem, is noted in the README.html in the build directory, and we have many higher priorities. Nobody is up for setting up autoconf or cmake or any other alternative build process at this time.

**Comment by krOoze** [comment]
It's not robust and multi-platform in the first place (e.g. pure Windows would not have `rm` command).

Continuing the hackery brainstorm from #281, what about:

    $(info ComSpec=$(ComSpec))
    ifneq ($(ComSpec),)
         NULLFILE := NUL
    else
        NULLFILE := /dev/null
    endif

    ifneq ($(shell asciidoc.py --version 2>$(NULLFILE)),)
        ASCIIDOC ?= asciidoc.py
    else ifneq ($(shell asciidoc --version 2>$(NULLFILE)),)
        ASCIIDOC ?= asciidoc
    else
        $(info No asciidoc found automagically. Please provide one through ASCIIDOC variable.)
    endif

    ifneq ($(shell a2x.py --version 2>$(NULLFILE)),)
        A2X ?= a2x.py
    else ifneq ($(shell a2x --version 2>$(NULLFILE)),)
       A2X ?= a2x
    else
        $(info No a2x found automagically. Please provide one through A2X variable.)
    endif

This works for me in Cygwin, MinGW, Ubuntu. Hell, would probably work on vanilla Windows with some tweaks to the rest of the Makefile.

**Comment by krOoze** [comment]
@oddhack I assume this is no longer a thing since the move to asciidoctor?

**Comment by oddhack** [comment]
Hopefully not. Closing.
