### ISSUE TITLE
Format description error?

### ISSUE THREAD

**Issue by mark-lunarg** [KhronosGroup/Vulkan-Docs#342]
In the 1.0.24 of the spec, section 31.3.1. Format Definition, the following description appears:

VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK
A four-component, ETC2 compressed format where each 64-bit compressed texel block encodes a 4x4 rectangle of unsigned normalized RGBA texel data with the first 64 bits encoding alpha values followed by 64 bits encoding RGB values with sRGB nonlinear encoding applied.

This appears to say the block is 64-bits with two 64-bit components, while the block size should be 128-bits.

**Comment by oddhack** [comment]
Since you're at LunarG, fastest way to address this is for you to file an MR on the internal Khronos gitlab.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.57 spec update.
