### ISSUE TITLE
vkQueuePresentKHR interaction with Resource Sharing

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#344]
Usage of Images created with VK_SHARING_MODE_EXCLUSIVE must conform to the Resource Sharing Mode chapter. Swapchain images can be created with that enum and so are no different.

The chapter prescribes, that there must be a "releasing" barrier recorded in one queue, and identical "acquiring" barrier in the other.

But in the Example ~~3~~ 4 of the Swapchain appendix chapter the Image seems to be transfered without need for "acquiring" barrier on presentation queue before presenting, and without need for "releasing" barrier on presentation queue after presenting. I did not find such behavior explained anywhere else in the spec text.

So which requirement is the correct one? Is "acquiring" barrier necessary in this case or not?

**Comment by oddhack** [comment]
This should be fixed in the 1.0.32 spec update.
