### ISSUE TITLE
Swapchain descendancy can be confused with parent/child

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#345]
In the `oldSwapchain` description:

> The new swapchain will: be a descendant of oldSwapchain. Further, any descendants of the new swapchain will also be descendants of oldSwapchain.

I assume "descendancy" is something else than the parent/child relationship (otherwise correct me).

It is easily confused with parent/child relationship, so wouldn't "successor" be better?

It also seems to have special meaning for one sentence later on, so it could perhaps be italicized.

**Comment by cubanismo** [comment]
This can be assigned to me to clarify my clarifications.

**Comment by krOoze** [comment]
This should be fixed in the 1.0.62 spec update.
