### ISSUE TITLE
Odd text formatting in Texel Replacement

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#348]
In chapter 15.3.3, the following admonition appears:

![vulkanfmt](https://cloud.githubusercontent.com/assets/905466/17956444/e6fe8ad6-6a57-11e6-9eff-fe94acfda7e3.jpg)

Note that only the first half of `VK_BORDER_COLOR_*TRANSPARENT_BLACK` appears within code formatting. The screenshot above comes from the PDF, but it also shows up in the HTML version.

**Comment by oddhack** [comment]
There's probably a logic error in the regular expression for the etext macro in config/vkspec.conf. It's supposed to allow imbedded wildcards in things that otherwise look like enumerant names. If you can see what the error is on casual inspection, I will fix it. Otherwise this is low priority.

**Comment by krOoze** [comment]
I already have it in the list in issue #331.

**Comment by krOoze** [comment]
Seems fixed in 1.0.26 update.

**Comment by NicolBolas** [comment]
Fixed, as noted above.
