### ISSUE TITLE
Case for more liberal licence in additional files

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#350]
This is a follow-up of point 5) of #328 as instructed.

1) Some files do not have obviously stated licence making them hard to handle for a law-abidin' citizen.
Files: /doc/specs/vulkan/\*shell scripts, some /doc/specs/vulkan/\*.py, /doc/specs/vulkan/config/\*.\*

2) There's no good reason to protect them.
Files: \*.\* except /doc/specs/vulkan/chapters/, /doc/specs/vulkan/appendices/ and vk.xml

3) People need to modify Makefile to make it work without being criminals (for some reason still uses the speccopyright)
Files: /doc/specs/vulkan/Makefile

4) Could have saved you months of time and work of your high-profile overkill-for-this developers.
This is about the Makefile again. Also bit about the asciidoctor transition. Well, and about fixing trivial errors in the spec text and source too. You could have tapped that comunity resource while Vulkan is new and exciting for people.

5) Would be nice to adjust format and MathJax settings without being a fellon
Files: /doc/specs/vulkan/config/\*.\*

EDIT: LOL, original title not intended :smile:

**Comment by oddhack** [comment]
This is mostly dealt with. Random little bits of CSS, Javascript, and XSL in config/ are not a concern to us, besides which some of them are modified from asciidoc or docbook bits that themselves don't have copyrights. I'm not willing to put in the time to figure out what some other project that didn't put a copyright on their little bit of infrastructure wants done in order that we can put a copyright on some little bit of infrastructure that we have as little interest in what people do with as they seem to.

**Comment by krOoze** [comment]
For completeness:

asciidoc has whole tree `COPYING` licence which is GPLv2

docbook has `COPYING` in the `\xsl directory`. Which is some custom permissive licence.

@oddhack 
You have `copyright.txt` in your `\doc\vulkan` directory.

Maybe that is confusing, whether it is the "default" copyright for the directory or just to be used as an asciidoc source text. If the second case, would you perhaps made that clear &mdash; e.g. by renaming it or changing the extension?
