### ISSUE TITLE
GL_KHR_vulkan_glsl should expose more of SPIR-V

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#353]
I'm not 100% positive that this bug should go here rather than to the glslangValidator project. But I imagine that it needs to be addressed by both, since it involves a specification.

There are a number of SPIR-V features that are useful for Vulkan which are not exposed by GLSL or the KHR_vulkan_glsl extension. These are generally small things but they can be useful for optimization purposes:
1. Selection Control hints from section 3.22
2. Loop Control hints from section 3.23
3. Function Control hints from section 3.24

I imagine that providing these would require actual new grammar, similar to C++11's attribute syntax.

**Comment by krOoze** [comment]
> I'm not 100% positive that this bug should go here

Well, `KHR_vulkan_glsl` **is** hosted here...

**Comment by johnkslang** [comment]
Late in closing this.  [The GL_EXT_control_flow_attributes extension](https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GL_EXT_control_flow_attributes.txt), posted in January, addressed this.

So, this can be closed now.

**Comment by timofonic** [comment]
@NicolBolas @krOoze @joey-lunarg @oddhack Any news?

**Comment by Tobski** [comment]
As per @johnkslang's comment, closing.
