### ISSUE TITLE
valid usage of vkAllocateMemory when exceeding maxMemoryAllocationCount 

### ISSUE THREAD

**Issue by ratchetfreak** [KhronosGroup/Vulkan-Docs#356]
The behavior is well defined however the limitation is also mentioned in the valid usage section.

> There is an implementation-dependent maximum number of memory allocations which can be simultaneously created on a device. This is specified by the maxMemoryAllocationCount member of the VkPhysicalDeviceLimits structure. If maxMemoryAllocationCount is exceeded, vkAllocateMemory will return VK_ERROR_TOO_MANY_OBJECTS.
> 
> **Valid usage**
> [...]
> - The number of currently valid memory objects, allocated from device, must be less than VkPhysicalDeviceLimits::maxMemoryAllocationCount

And the TOO_MANY_OBJECTS error code is in the possible return values.

This does not match that "Valid usage conditions do not cover conditions where well-defined behavior (including returning an error code) exists." in the section about valid usage.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.66 spec update.
