### ISSUE TITLE
LoaderAndLayerInterface.md links issues

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#359]
There are two references to the LoaderAndLayerInterface.md document.

1) It should perhaps be in the ch 1.4. Normative References instead

2) One of the links points to a "sdk-1.0.13" version (which is obsolete &mdash; latest release version is sdk-1.0.~~24~~26)

3) Second reference "link" to that document in ch 30.1. Layers is awkwardly formated in quote marks.

**Comment by courtney-g** [comment]
Have submitted CL to working group to address. #1 will require discussion. Others are simple.

**Comment by oddhack** [comment]
Fixed in 1.0.27.

**Comment by krOoze** [comment]
@courtney-g What's with the extensions chapter link immediatelly followed by the document link. That looks like some mistake.

**Comment by courtney-g** [comment]
Can you give me more context?

**Comment by krOoze** [comment]
@courtney-g Sure.

Ch. 30.2.1. Instance Extensions and Device Extensions:
> #### Note
Instance extensions generally require support in the Vulkan loader. This is especially true for commands that are dispatched from instances and physical devices. Additional information about supporting instance-level commands may be found in the [extensions]() ["Vulkan Loader Specification and Architecture Overview"]() document,
Please see the "Architectural overview of layers and loader" section for information about how both instance-level and device-level commands are supported and dispatched.

1) The "extensions" is a separate link that looks like it doesn't belong there.
2) (While at it) Not sure if the second link needs to be in qoutes
3) The whole sentence ends with comma not period.

**Comment by courtney-g** [comment]
Got it. Yeah, that looks like it shouldn't be there or missing some context.

**Comment by courtney-g** [comment]
Should be fixed in the next spec update.

**Comment by oddhack** [comment]
Done in 1.0.29 spec update.
