### ISSUE TITLE
C99 designated intializers

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-Docs#36]
Since you made the excellent choice of basing Vulkan on C99, why not use its very useful syntax when instantiating structs? For example, this code sample from the specifications:

```C
const VkSpecializationMapEntry entries[] =
{
    {
        0,                    // constantID
        0 * sizeof(int32_t),  // offset
        sizeof(int32_t)       // size
    },
    {
        12,                   // constantID
        1 * sizeof(int32_t),  // offset
        sizeof(float)         // size
    }
};
```

can be written as:

```C
const VkSpecializationMapEntry entries[] =
{
    [0] = {
        .constantId = 0,
        .offset     = 0 * sizeof(int32_t),
        .size       = sizeof(int32_t),
    },
    [1] = {
        .constantId = 12,
        .offset     = 1 * sizeof(int32_t),
        .size       = sizeof(float)
    }
};
```

This not only makes the comments unnecessary, but is also future proof, in the sense that now you don't require the struct to actually contain the elements in that order. Overall, this is a safer way to initialize a struct. (I added `[x] = ` as well for array initialization because it made sense in the context of where this code sample was introduced, but I'm mainly commenting on the struct initialization).

**Comment by jeffbolznv** [comment]
We chose to make the spec examples use the coding style from the CTS (see https://github.com/KhronosGroup/Vulkan-CTS/blob/vulkan-cts-1.0/external/vulkancts/modules/vulkan), minus tabs. So I expect this issue to be closed wontfix.

**Comment by ShabbyX** [comment]
The CTS is in C++, so it doesn't accept this feature from C99 (which is the language of Vulkan). I was trying to promote a beneficial syntax, but I also understand reservations against it because of C++.

**Comment by elfring** [comment]
I am also curious on [the consistent use of designated initialisers](http://en.cppreference.com/w/c/language/struct_initialization "Safe initialisation of data structures") in provided source files.

**Comment by oddhack** [comment]
Closed per @jeffbolznv's comment above.
