### ISSUE TITLE
Small usage issue in VkComputePipelineCreateInfo

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#362]
One of the usages in `VkComputePipelineCreateInfo` says:

> `layout` must be consistent with all shaders specified in `pStages`

But `VkComputePipelineCreateInfo` doesn't ahve a `pStages` member; it only has a single `stage` member. I'd guess that this is a copy-and-paste bug from `VkGraphicsPipelineCreateInfo`

**Comment by sheredom** [comment]
Good spot @NicolBolas - I'll get this fixed, thanks! :smile:

**Comment by oddhack** [comment]
This should be fixed in the 1.0.29 spec update.
