### ISSUE TITLE
[Editing][Specification] Link to Fences chapter leads to Semaphores

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#365]
In the `vkQueueSubmit()` descriptions:

> Information about these additional constraints can be found in the [semaphore](https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#synchronization-semaphores) and [fence](https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#synchronization-semaphores) sections of [the synchronization chapter](https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#synchronization).

The [fence](https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#synchronization-semaphores) links to the Semaphore chapter instead.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.28 spec update.
