### ISSUE TITLE
vkClearColorValue floating-point types

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#369]
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#VkClearColorValue says:

> `float32` are the color clear values when the format of the image or attachment is floating point, unorm, snorm, uscaled, packed float, or sRGB. Floating point values are automatically converted to the format of the image, with the clear value being treated as linear if the image is sRGB.

I think this should include "sscaled" too.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.30 spec update.
