### ISSUE TITLE
Invariance rules refer to program objects.

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#372]
In E.3, the Vulkan specification says:

> The wording “the same shader” means a **program object** that is populated with the same SPIR-V binary, which is used to create pipelines , which is used to create pipelines, possibly multiple times, and which **program object** is then executed using the same Vulkan state vector.

Vulkan does not have program objects. I rather suspect that this is a copy&paste bug, since the OpenGL specification uses similar wording.

This invariance rule should be cleared up to more accurately use Vulkan/SPIR-V terms in this regard.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.30 spec update.
