### ISSUE TITLE
Vulkan Variables Simplified

### ISSUE THREAD

**Issue by calvinvalerian** [KhronosGroup/Vulkan-Docs#373]
When it comes to the source code what we want is a readable functioning program.
 
But readability is no longer a priority when it comes to gaming.
 
I want to introduce my method to push the speed of Vulkan a little bit further.
 
Here's how:
Duplicate source code to a new location.
 
Create a new program that replaces every variable in all duplicated source to a consecutive alphabetical order.
 
Therefore no modification is made in the original source code and that's where you're going to compile the program.
 
I recommend to first replace all variable names with capitals (e.g: "VARNAME") rather than "varName" pattern.
 
Here's a bash script example:
 
**# BEFORE SIMPLIFICATION PROCESS**
#!/bin/bash
FIRSTNAME=Steve
LASTNAME=Jobs
 
for X in $FIRSTNAME $LASTNAME" do
     echo $X
done
 
**# WHAT TO DO**
We're going to replace a total of 3 variables to alphabet consecutively starting from "a": a b c.
FIRSTNAME > a
LASTNAME > b
X > c
 
**# AFTER SIMPLIFICATION PROCESS**
#!/bin/bash
a=Steve
b=Jobs
 
for c in $a $b; do
     echo $c
done
 
The reason I prefer alphabet more than digit is because alphabet comprise of 26 characters before it adds new character length whereas digit is only 10, hence more efficient than digits.
 
When a - z is used up, increase the character length to "aa", "aaa" and so on so forth.

**Comment by krOoze** [comment]
I am not sure how this applies to Vulkan (being C + bSPIR-V).
Is this perhaps for some interpreted language binding, where name minimization can be beneficial?

**Comment by ratchetfreak** [comment]
There is no current interpreter that cares about performance will keep reparsing the source over and over. Instead they will at the very least compile the scripts to bytecode or even to machine code at which point variable names don't matter anymore.

If you have an interpreter that doesn't have a JIT compile to at least bytecode to be reused in future invocations then it's better to replace it with one that does.

**Comment by oddhack** [comment]
I'm equally unclear on why making variable names shorter makes the sample code run faster, which (seems) to be the motivation. Unless there's an underlying different reason for proposing this change, please close the issue.

**Comment by calvinvalerian** [comment]
I'll close this issue since I just knew that variable names are not in the resulting bytecode.
