### ISSUE TITLE
Graphics Pipeline–Render Pass compatibility underspecified

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#375]
During `VkPipeline` creation `VkGraphicsPipelineCreateInfo` takes these parameters:

>  - `renderPass` is a handle to a render pass object describing the environment in which the pipeline will be used; the pipeline **can** be used with an instance of any render pass compatible with the one provided. See [Render Pass Compatibility]() for more information.
 - `subpass` is the index of the subpass in `renderPass` where this pipeline will be used.

1) The "can" seems like it should be "must only".

2) In any case, I can't find restriction on what render pass and graphics pipelines can be used together in any places I would expect it. I would most expect this to be in VUs of commands affected by bound pipeline (e.g. `vkCmdDraw`). Something like:
> - The render pass this command is called in must be compatible with the `VkGraphicsPipelineCreateInfo::renderPass` of the currently bound pipeline to `VK_PIPELINE_BIND_POINT_GRAPHICS`.
> - The subpass index this command is called in must be equal to `VkGraphicsPipelineCreateInfo::subpass` of the currently bound pipeline to `VK_PIPELINE_BIND_POINT_GRAPHICS`.

3) It is not obvious from the text, how the render pass compatibility translates to the `subpass`. Its description mentions `renderPass` specifically (and no other render pass &mdash; not even compatible one)

4) Same for `VkCommandBufferInheritanceInfo::subpass`

**Comment by janharaldfredriksen-arm** [comment]
I agree with your first two points.

On 3) - are you referring to the description of the subpass parameter to VkGraphicsPipelineCreateInfo? If so, I think that description could be changed to about "the render pass" instead of the renderPass parameter.

**Comment by krOoze** [comment]
@janharaldfredriksen-arm Yes, in 3) I refer to the

> - `subpass` is the index of the subpass in `renderPass` where this pipeline will be used.

and mentioning the `renderPass` specifically to be used in the command buffer environment (while the intent seems to be compatible one can be used).

**Comment by janharaldfredriksen-arm** [comment]
Thanks. I then suggest changing it to something like:
"subpass is the index of the subpass in the render pass where this pipeline will be used."
.. since the description of "renderPass" already covers the render pass compatibility issue.

**Comment by krOoze** [comment]
Also `VkCommandBufferInheritanceInfo::subpass` description has the same problem as 3).

**Comment by janharaldfredriksen-arm** [comment]
Thanks - fixing (4) in a similar way.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.31 spec update.
