### ISSUE TITLE
Document which headers are required for VK_USE_PLATFORM_xxx

### ISSUE THREAD

**Issue by haasn** [KhronosGroup/Vulkan-Docs#376]
There is a table listed of `VK_USE_PLATFORM_xxx` symbols that the vulkan header will consult to determine which platform-specific extensions to compile in.

From this table/appendix alone it is not clear to me under what circumstances I should enable these definitions. What I'm looking for is a list mapping each `VK_USE_PLATFORM_xxx` to the header files that must be present to enable it without a compile-time failure, so I can insert a configuration step to enable only platforms that have their corresponding headers available.

**Comment by haasn** [comment]
Note: It currently very easily possible to read this information out of the vulkan.h header itself.

Extension | Header
--------- | ------
`VK_USE_PLATFORM_XLIB_KHR` | `X11/Xlib.h`
`VK_USE_PLATFORM_XCB_KHR` | `xcb/xcb.h`
`VK_USE_PLATFORM_WAYLAND_KHR` | `wayland-client.h`
`VK_USE_PLATFORM_MIR_KHR` | `mir_toolkit/client_types.h`
`VK_USE_PLATFORM_ANDROID_KHR` | `android/native_window.h`
`VK_USE_PLATFORM_WIN32_KHR` | `windows.h`

All I'm asking for is for this information to be included in the table.

**Comment by oddhack** [comment]
That seems useful. I'll try to get to it soon. But note that this is the sort of indirect dependency that is difficult to keep up to date. In principle all the header dependencies are extractable from vk.xml, but we don't have any code to do that and create the asciidoc table. So it comes down to someone remembering to update the spec source whenever the header dependencies of the various extensions with USE_PLATFORM macros change. On the upside, such changes should be quite rare.

**Comment by krOoze** [comment]
@oddhack Would like to add it is not immediately obvious from the (canonical) `vk.xml` either  which guard belongs to which header.

**Comment by NicolBolas** [comment]
It may not be *immediately* obvious, but it can be computed.

For example, the extension `VK_KHR_win32_surface` has a `protect` attribute of `VK_USE_PLATFORM_WIN32_KHR`. It also includes the type `VkWin32SurfaceCreateInfoKHR`. And that `struct` type includes the type `HWND`. And that type has a `requires` clause that says it is defined in `windows.h`.

If the goal is to match extensions with `protect` attributes to the headers they include, then vk.xml has you covered. It shouldn't be too difficult to write a script to scan through them and build such a mapping.

**Comment by oddhack** [comment]
Yes, it can. It's not an amount of work I feel worth the trouble for 6 words. If the header mapping gets changed in the future, I'm sure the more detail-oriented participants here will let us know about it.

**Comment by haasn** [comment]
Incidentally, something like this might be a better way to handle platform-specific includes: Instead of using these VK_USE_PLATFORM_xxx variables, move the platform-dependent definitions out to a separate file, e.g. `#include <vulkan/xlib.h>` instead of `#define VK_USE_PLATFORM_XLIB_KHR`.

To give feedback about whether it would be safe to enable a particular header or not, they could be disabled at configure time of libvulkan itself. (So as an application writer I would have to check for presence of `vulkan/xlib.h` to find out whether `VK_USE_PLATFORM_xxx` is supported or not.)

This also solves the issue of potential backwards-compatibility. If libvulkan ever moves to support a new surface backend, and I write an application that depends on this surface backend being available, the many-headers approach would allow me to guard for support at configure time (rather than failing at compile time).

**Comment by oddhack** [comment]
We had a lot of discussion about ways to structure this including what you suggest, and landed where we are now. There are pros and cons to all approaches of course.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.28 spec update.

**Comment by krOoze** [comment]
@oddhack 
`VK_NV_external_memory_win32` and `VK_NV_win32_keyed_mutex` also do use `VK_USE_PLATFORM_WIN32_KHR`. That should probably be written somewhere. The table looks like a natural place. Also if that is to be allowed, the chapter should not say they are window system specific.
