### ISSUE TITLE
ArrayStride/MatrixStride vs base alignment

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#38]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#interfaces-resources-layout says:

> Any ArrayStride or MatrixStride decoration must equal the base alignment of the array or matrix from above.

If I have

    struct A {
        vec4 a, b; // base alignment of each member is 16
    }; // base alignment of struct is largest of its members (16) rounded up to 16

    uniform blk {
        A x[2]; // base alignment of array is equal to element (16) rounded up to 16
    };

then I think this says the ArrayStride of x must be equal to its base alignment of 16. But sizeof(A) == 32, so the stride is smaller than the element size, which doesn't sound right.

Perhaps this meant the ArrayStride must be a multiple of the base alignment. (And specifically a positive multiple, or larger than or equal to the element size, or something.)

**Comment by oddhack** [comment]
Done in the 1.0.5 spec update.
