### ISSUE TITLE
KHR_surface issue 2) says queries should not operate on phys. device

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#381]
`VK_KHR_surface` issue 2) says queries should not operate on phys. device and be in `VK_KHR_swapchain`:

> 2) Should the vkGetSurfacePropertiesKHR(), vkGetSurfaceFormatsKHR(), and vkGetSurfacePresentModesKHR() functions from VK_KHR_swapchain be modified to operate on physical devices and moved to this extension to implement the resolution of issue 1?
> 
> RESOLVED: No, [...]

Yet it seems that is exactly what did happen at some point.

And relatedly, issues for those commands are still in the `VK_KHR_swapchain` appendix (and have wrong names).

**Comment by krOoze** [comment]
Some do-gooder changed the function names in 1.0.44 to the already physical device dependent ones, so now the in-spec issue question makes no sense whatsoever.

**Comment by krOoze** [comment]
@timofonic Probably should just ignore Issue sections in the Extension Appendices, which may be obsolete. Still, needs to be corrected or removed...

BTW: Do you plan to ping every open Issue?

**Comment by oddhack** [comment]
@alonorbach I have some internal notes saying you were going to propose an MR for this. Is that still planned?
