### ISSUE TITLE
`texelSize` needs explanation

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-Docs#382]
There are occasional uses of `texelSize` and `texel size` in the specifications without any apparent definition (at least not with this terminology). For example, in the definition of `VkSubresourceLayout`, Vulkan says:

    // (x,y,z,layer) are in texel coordinates
    address(x,y,z,layer) = layer*arrayPitch + z*depthPitch + y*rowPitch + x*texelSize + offset

Without explaining what `texelSize` is (or more importantly, how to get it). In the pseudocode for image/buffer addressing, Vulkan says:

    texelSize = <texel size taken from the src/dstImage>;

Again, without specifying how this size is taken from the image.

One could guess the sizes from the name of the format, but it would be nice if "texel size" was given a formal definition. Even better would be if `VkFormatProperties` would contain `texelSize`!

**Comment by oddhack** [comment]
This should be fixed in the 1.0.31 spec update.
