### ISSUE TITLE
VkWin32SurfaceCreateInfoKHR missing hinstance and hwnd VU

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#383]
VkWin32SurfaceCreateInfoKHR is missing Valid Usage sentences for `hinstance` and `hwnd`. (Also some other platforms missing such for non-pointer arguments.)

BTW: Other platform extensions do say it has to be pointer to some value. They should probably say they have to be valid platform handles too in the context of the given platform.

**Comment by MarkY-LunarG** [comment]
This is a good point.  I'll be looking at bringing the Windows section up to parity with the other WSI sections.

**Comment by MarkY-LunarG** [comment]
Actually, looking at the spec, the Windows sections are in line with the others.  The only valid usage statements in the other sections are if the API expects a pointer for a Windowing-system specific value.  In that case, the valid usage is indicating it must be a valid pointer.  Other than that it does not make any statements about valid usage of the actual object value.  Vulkan is ignorant of Windowing-system values and can't verify whether it is or is not valid.

**Comment by krOoze** [comment]
It is not ignorant of Windowing-system values. I assume if I pass something bad it will crash horibly.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.35 spec update.
