### ISSUE TITLE
Output only VkSurfaceCapabilitiesKHR has VU

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#384]
`VkSurfaceCapabilitiesKHR` has a Valid Usage section restraining Flag usages. I think that's undesired. The structure is only used as output and application would want to pass an uninitialized structure instead.

UPDATE:
Same problem for `VkSurfaceFormatKHR`.

**Comment by critsec** [comment]
Yes, I noticed this recently too. Fix has been made internally and is on track to be in the next spec release. Fixed structs were:
- VkDisplayPropertiesKHR
- VkDisplayPlanePropertiesKHR
- VkDisplayModePropertiesKHR
- VkDisplayPlaneCapabilitiesKHR
- VkSurfaceCapabilitiesKHR
- VkSurfaceFormatKHR

**Comment by critsec** [comment]
Fixed in 1.0.29.
