### ISSUE TITLE
Minimal presentation capabilities requirement

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#385]
Shouldn't there be minimal requirements for these:
- `minImageCount` (e.g. at least one)
- `maxImageCount` (possibly `0` or &ge; `minImageCount`)
- `minImageExtent`, `currentExtent`, `maxImageExtent` (possibly `minImageExtent` &le; `currentExtent` &le; `maxImageExtent` except for `currentExtent` = `UINT32_MAX`)
- `maxImageArrayLayers` (e.g. at least one)
- `supportedTransforms` (e.g. at least one flag raised)
- `currentTransform` (e.g. exactly one flag raised)
- `supportedCompositeAlpha` (e.g. at least one flag raised)
- `pSurfaceFormatCount` and `pSurfaceFormats` (e.g. at least one returned if queries said presentation is supported)

**Comment by oddhack** [comment]
maxImageCount already defines 0 as meaning "an unlimited number", but > min seems sensible.

I'm unclear what "if queries said presentation is supported" means. Can you translate that into spec-like language?

**Comment by krOoze** [comment]
> maxImageCount already defines 0 as meaning "an unlimited number", but ≥ min seems sensible.

Yes, I meant the `0` as an exception to the proposed ≥ min requirement for completeness.

> I'm unclear what "if queries said presentation is supported" means. Can you translate that into spec-like language?

By that I meant `vkGetPhysicalDeviceSurfaceSupportKHR` returning `TRUE`.
I think such Surface should support at least one format, otherwise it is just another query of presentation support.

It could support at least one even if the query returns `FALSE`, but I just didn't know if that's reasonable expectation... The `CreateSurface` commands accept any kind of window and has no reasonable `VkResult` to fail. And it is possibly concievable obscure chance they could have formats incompatible with Vulkan.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.37 spec update.
