### ISSUE TITLE
VK_SHARING_MODE_CONCURRENT resource use should be restricted to given families

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#386]
I do not see anywhere Images, Swapchain Images and Buffers created with `VK_SHARING_MODE_CONCURRENT` to be restricted with strong enough language to the queue families Application provided during their creation.

That should perhaps be in the Valid Usage section of `vkQueue*` commands.

[enhancement] Shouldn't perhaps `queueFamilyIndexCount==0` be repurposed to mean "all queue families" on the resource creation?

**Comment by oddhack** [comment]
This should be fixed in the 1.0.32 spec update.
