### ISSUE TITLE
vkCreateSwapchainKHR can fail?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#389]
`minImageCount` description of `VkSwapchainCreateInfoKHR` structure says:

> `minImageCount` is the minimum number of presentable images that the application needs. The platform will either create the swapchain with at least that many images, or will fail to create the swapchain.

But how does it fail exactly? Shouldn't perhaps `VK_ERROR_INITIALIZATION_FAILED` be in the Return Codes section of `vkCreateSwapchainKHR`?

**Comment by ianelliottus** [comment]
Another way of wording the second sentence that you quoted is:

> If the swapchain is successfully created, the platform will create a swapchain with at least that many images.

The idea we attempted to convey in that sentence is that there are times when a platform will create a swapchain with more images than requested in minImageCount.  There are implementation-specific reasons for this.  For example, I know of cases where certain VkSwapchainCreateInfoKHR::presentMode values will trigger an implementation to increase the number of images created for the swapchain.

Are you wondering about failures related to minImageCount?  That wasn't the intent of that sentence, but I will try to address possible questions.  There are multiple reasons why swapchain creation can fail, and 5 return codes to address those reasons.  Of those error codes, VK_ERROR_OUT_OF_DEVICE_MEMORY is the most-likely reason that swapchain creation would fail in a manner related to minImageCount (followed by VK_ERROR_OUT_OF_HOST_MEMORY).  For example, if VkSurfaceCapabilitiesKHR::maxImageCount has the value of 0, and an application requests a swapchain with 1000's of images, VK_ERROR_OUT_OF_DEVICE_MEMORY may be the result.

I will also point out that there are two Valid Usage statements regarding minImageCount.  These are checked by the validation layers.

Did this adequately address your concern(s)?

**Comment by krOoze** [comment]
That sounds reasonable. It is only natural `VK_ERROR_OUT_OF_HOST_MEMORY` and `VK_ERROR_OUT_OF_DEVICE_MEMORY` could happen during Image allocation (and no other types of errors because of `VkSurfaceCapabilitiesKHR`).

I think I was thinking of some situation caused by issue #388 (where `VkSurfaceCapabilitiesKHR` could change between the query and swapchain creation, which could open some space for non-memory platform related error). Let's consider it duplicate of that,
