### ISSUE TITLE
Unclear render pass VU for vkCmdExecuteCommands

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#390]
Render pass restriction from `vkCmdExecuteCommands` VU:

> If vkCmdExecuteCommands is being called within a render pass instance, any given element of pCommandBuffers must have been recorded with a render pass that is compatible with the current render pass - see Section 7.2, “Render Pass Compatibility”

It is unclear what "recorded with a render pass" means. I suggest it should mention `VkCommandBufferInheritanceInfo::renderPass`. (It was similarly fixed for the `subpass` parameter in 1.0.14, but this somehow remained.)

It would be made clear with fixing as above, but I would also object to the "recorded with" (used here and few other places to refer to `vkBeginCommandBuffer()`'s parameters). To cite the spec:

> Commands are recorded into a command buffer by calling API commands of the form `vkCmd*`. 

 `vkBegin*()` commands do not start with `Cmd`.
Also they switch the buffer to a recording state, which itself cannot be considered recorded operation (or it would be replayed on each submission).

**Comment by oddhack** [comment]
This should be fixed in the 1.0.35 spec update.

**Comment by oddhack** [comment]
There was an additional tweak in the 1.0.36 spec update addressing the "recorded with" issue.

**Comment by krOoze** [comment]
@oddhack 
The change broke the text (the `pname::pBeginInfo::` is visible; `pname` should have only one `:` I think).

Besides, why was only that one sentence singled out? There are many more instances of this in the spec (even around the changed one).
