### ISSUE TITLE
vkCreateDescriptorSetLayout with multiple descriptors having the same binding

### ISSUE THREAD

**Issue by tomaka** [KhronosGroup/Vulkan-Docs#391]
When you call `vkCreateDescriptorSetLayout` you need to pass a list of descriptors, each element having a `binding` member describing which bind point the element corresponds to.

Nothing in the specs says that it's forbidden to pass multiple descriptors with the same binding. My guess is that it probably should be.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.32 spec update.
