### ISSUE TITLE
Incorrect refBegin for VkDebugReportFlagBitsEXT 

### ISSUE THREAD

**Issue by FacticiusVir** [KhronosGroup/Vulkan-Docs#392]
The refBegin entry for VkDebugReportFlagBitsEXT in [doc/specs/vulkan/chapters/VK_EXT_debug_report.txt](https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/doc/specs/vulkan/chapters/VK_EXT_debug_report.txt#L52) is incorrectly set to VkDebugReportCallbackCreateInfoEXT; I've added a fix in https://github.com/KhronosGroup/Vulkan-Docs/pull/380

**Comment by oddhack** [comment]
This should be fixed in the 1.0.31 spec update.
