### ISSUE TITLE
PrimitiveId, ambiguous description on decorations for fragment shaders

### ISSUE THREAD

**Issue by Ashalah** [KhronosGroup/Vulkan-Docs#393]
In chapter 14.6 of Vulkan spec 1.0.30, PrimitiveId is described as:

> In a fragment, tessellation control or tessellation evaluation shader, any variable decorated with PrimitiveId must be declared using the output storage class.

And just below that:

> When the PrimitiveId decoration is applied to an output variable in the geometry shader, the resulting value is seen through the PrimitiveId decorated input variable in the fragment shader.

I'm still reading the spec for the first time so I may have misunderstood, but I'm not sure if there's a problem or the text is just unclear.

**Comment by janharaldfredriksen-arm** [comment]
There is an error in the first section you quote: "output" should be "input".

We have a fix for this in the pipeline.

**Comment by Ashalah** [comment]
OK, close the issue at your discretion. If I have to close it, let me know.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.31 spec update.

**Comment by oddhack** [comment]
My bad - the internal MR for this was approved but I overlooked including it in the 1.0.31 update. It will be in the next public spec update, however.
