### ISSUE TITLE
manhtmlpages for extensions are not created

### ISSUE THREAD

**Issue by McNopper** [KhronosGroup/Vulkan-Docs#394]
When trying to create the manhtmlpages (each function etc. in a separate file), only the core ones are created.
For PDF and everything else, the extension documentation is created.

**Comment by lordheavy** [comment]
somehow duplicated with https://github.com/KhronosGroup/Vulkan-Docs/issues/367

**Comment by oddhack** [comment]
If I say 'makeAllExts man/apispec.txt', the generated asciidoc sources include extension pages. However, the Makefile defines MANSOURCES = $(CORESOURCES), which is explicitly just the core API pages. MANSOURCES could be changed to include extensions.

We have a tension between publishing a version of the ref pages including lots of extensions, and no indication in the core pages as to *where* they have been extended, or just publishing the 1.0 core pages, and have so far chosen the latter. This is definitely not ideal but the toolchain is somewhat constraining - all the conditional inclusion takes place when building output documents, and things like the lists of valid enumerants in an enum type are also generated at this step, depending on the set of extensions specified to the build process.

It would probably be possible using Asciidoctor.js or other in-browser technology to dynamically regenerate pages with different chosen sets of extensions included - it's just a lot more work than any of us have signed up for, so far.

**Comment by oddhack** [comment]
Closing - the 1.1 refpages we post in the registry include all published extension interfaces as well as core.
