### ISSUE TITLE
Is VK_SUBOPTIMAL_KHR optional for driver?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#396]
It is unclear to me from the spec text when `VK_SUBOPTIMAL_KHR` is returned and when not.

Return Codes and vkAcquireNextImageKHR desc. resp.:

> `VK_SUBOPTIMAL_KHR` A swapchain no longer matches the surface properties exactly, but **can** still be used to present to the surface successfully.
> 
> `VK_SUBOPTIMAL_KHR` is returned if an image became available, and the swapchain no longer matches the surface properties exactly, but **can** still be used to present to the surface successfully.

It is a bit muddy. Would size change be included in this? If not, what even is?

Note the "is" would imply it is always returned in such situation.

vkAcquireNextImageKHR desc.:

>   **Note**
> This **may** happen, for example, if the platform surface has been resized but the platform is able to scale the presented images to the new size to produce valid surface updates. It is up to applications to decide whether they prefer to continue using the current swapchain indefinitely or temporarily in this state, or to re-create the swapchain to better match the platform surface properties.

Why "**may**"? Is it possible that the implementation **may** not inform of such situation using `VK_SUBOPTIMAL_KHR`?

vkAcquireNextImageKHR desc.:

> If the native surface and presented image sizes no longer match, presentation **may** fail. If presentation does succeed, parts of the native surface **may** be undefined, parts of the presented image **may** have been clipped before presentation, and/or the image **may** have been scaled (uniformly or not uniformly) before presentation. It is the application’s responsibility to detect surface size changes and react appropriately. If presentation fails because of a mismatch in the surface and presented image sizes, a `VK_ERROR_OUT_OF_DATE_KHR` error will be returned.

Still doesn't say how it succeds. Is `VK_SUCCESS` permissible in such situation making the `VK_SUBOPTIMAL_KHR` (success code) truly optional for the implementation to return?

How is the application supposed to detect size changes? Through `VK_SUBOPTIMAL_KHR` (and `VK_ERROR_OUT_OF_DATE_KHR`) or through platform dependent API?

EDIT (1.0.69):
The above was removed and this was added:

> If the swapchain images no longer match native surface properties, either `VK_SUBOPTIMAL_KHR` or `VK_ERROR_OUT_OF_DATE_KHR` **must** be returned.

That is much clearer. Still the note above should be changed to match (**may** &rarr; **must**, or "happens for example" to avoid RFC keyword)

**Comment by alonorbach** [comment]
> Why "**may**"? Is it possible that the implementation **may** not inform of such situation using `VK_SUBOPTIMAL_KHR`?

That's right. Implementations may or may not decide to report back `VK_SUBOPTIMAL_KHR` in the case of presentation being scaled. The purpose of this success code (it is **not** an error code!) is to allow platforms to indicate to an application that they may get better performance if they re-create their swapchain. The intention was not to mandate that it must be returned in specific scenarios.  

> Still doesn't say how it succeds. Is `VK_SUCCESS` permissible in such situation making the `VK_SUBOPTIMAL_KHR` (success code) truly optional for the implementation to return?

The spec for vkAcquireNextImageKHR says  "VK_SUCCESS is returned if an image became available." 
The section you quote explains that if presentation fails, a 'VK_ERROR_OUT_OF_DATE' must be returned. Neither `VK_SUBOPTIMAL_KHR` nor 'VK_SUCCESS` would be an acceptable return code in such a situation.

> How is the application supposed to detect size changes? Through `VK_SUBOPTIMAL_KHR` (and `VK_ERROR_OUT_OF_DATE_KHR`) or through platform dependent API?

The application is notified about size changes that necessitate or merit creating a new swapchain by the `VK_ERROR_OUT_OF_DATE_KHR` and `VK_SUBOPTIMAL_KHR` return codes, respectively. It can then call vkGetPhysicalDeviceSurfaceCapabilitiesKHR to determine the current extent (if it has changed) alongside other surface properties, and use these to create a new swapchain. If an application wants to detect any change to the window size, whether or not this affects the swapchain, then this needs to be done via a platform-specific API.

**Comment by alonorbach** [comment]
Hi @krOoze. Okay to close this issue, or anything further to raise here?

**Comment by krOoze** [comment]
@alonorbach Well, I would suggest some wording tweaks to that, but I have nothing new to add. Close at your discretion.

The suggestions:

1)
> `VK_SUBOPTIMAL_KHR` is returned if an image became available, and the swapchain no longer matches the surface properties exactly, but can still be used to present to the surface successfully.

The "is" sounds too much like "will be". The "if" is reversed. The sentence logic currently is `if(surface not matches) return VK_SUBOPTIMAL_KHR`. Based on your answer it should be `if( returned VK_SUBOPTIMAL_KHR) surface not matches`. One way to fix it would be to change "is returned" to "may be returned".

2)
> It is the application’s responsibility to detect surface size changes and react appropriately.

It is conflated with the `VK_ERROR_OUT_OF_DATE_KHR`. It could deserve its own paragraph. It could note `VK_ERROR_OUT_OF_DATE_KHR` and `VK_SUBOPTIMAL_KHR` may not be sufficient for the purpose of detection.

3)
The Note is largely redundant, because the following paragraf lists all possible effects exhaustively.

4)
> If the native surface and presented image sizes no longer match, presentation may fail. If presentation does succeed, parts of the native surface may be undefined, parts of the presented image may have been clipped before presentation, and/or the image may have been scaled (uniformly or not uniformly) before presentation. It is the application’s responsibility to detect surface size changes and react appropriately. If presentation fails because of a mismatch in the surface and presented image sizes, a `VK_ERROR_OUT_OF_DATE_KHR` error will be returned.

The first and last sentence says the same thing, exept the last does it better. Together with 2. it makes the paragraph hard to digest.


5)
> If the native surface and presented image sizes no longer match, **presentation** may fail. If **presentation** does succeed, parts of the native surface may be undefined, parts of the **presented** image may have been clipped before presentation, and/or the image may have been scaled (uniformly or not uniformly) before presentation. It is the application’s responsibility to detect surface size changes and react appropriately. If **presentation** fails because of a mismatch in the surface and presented image sizes, a `VK_ERROR_OUT_OF_DATE_KHR` error will be returned.

It discusses presentation and not `vkAcquire` at all so should perhaps be moved appropriately.

6)
BTW Is the size the only concern? What about the arrayness change (maybe if the native surface switches from stereo to conventional 2D)? (Well, that's possibly tied to Issue #388)

**Comment by oddhack** [comment]
Closing this, since it sounds like it was adequately covered.

**Comment by krOoze** [comment]
@oddhack  I am unclear now what the resolution is. @alonorbach above says the driver does not have to report it, but at some point this appeared in the spec:

> If the swapchain images no longer match native surface properties, either `VK_SUBOPTIMAL_KHR` or `VK_ERROR_OUT_OF_DATE_KHR` **must** be returned.

Which says the driver has to report it.

**Comment by krOoze** [comment]
@oddhack May I have a reopen. This seems still valid Issue per previous comment.

There is:

> The implementation **may** return `VK_SUBOPTIMAL_KHR` if the swapchain no longer matches the surface properties exactly

but also

> If the swapchain images no longer match native surface properties, either `VK_SUBOPTIMAL_KHR` or `VK_ERROR_OUT_OF_DATE_KHR` **must** be returned.

may vs must

Additionally the new extension now added:

> Scaling is done and `VK_SUCCESS` or `VK_SUBOPTIMAL_KHR` is returned

implying there may be scaling but not `VK_SUBOPTIMAL_KHR`.
