### ISSUE TITLE
[question][WSI] Why not VK_IMAGE_LAYOUT_GENERAL with vkQueuePresentKHR? And VU

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#397]
1)
In several places it is written `VK_IMAGE_LAYOUT_PRESENT_SRC_KHR` must be used (exclusively) with `vkQueuePresentKHR`. `VK_IMAGE_LAYOUT_GENERAL` **must** not be used.

That makes it bit of an exception. I wonder why?

2)
That information is not around `vkQueuePresentKHR`, where I would most expect it. Should perhaps even be in the VU section of `vkQueuePresentKHR`? (Other commands do have Image Layout restrictions there.)

**Comment by jozefkucia** [comment]
The spec is a bit inconsistent as well. In the section "11.4. Image Layouts" the VK_IMAGE_LAYOUT_PRESENT_SRC_KHR is called a device access (it's listed under "The type(s) of device access supported by each layout are:"). In the same list the VK_IMAGE_LAYOUT_GENERAL is defined as "Supports all types of device access." which makes it ambiguous. It may be a good idea to separate VK_IMAGE_LAYOUT_PRESENT_SRC_KHR and to say explicitly that the  vkQueuePresentKHR() is not a device access but "the presentation engine access".

**Comment by krOoze** [comment]
@jozefkucia But there is no reason to disallow `VK_IMAGE_LAYOUT_GENERAL` with `vkQueuePresentKHR()`, is there (if it is allowed for all the other operations)? I would prefer it to be fixed that way.
It would be backward-compatible (but not forward compatible). Should be allowed in the patch versions (at least there was such changes in the past).

**Comment by jozefkucia** [comment]
@krOoze There are probably reasons why it's disallowed. The best explanation I've found in the spec is the following: 

> "The presentation engine may be synchronous or asynchronous with respect to the application and/or logical device. Some implementations may use the device’s graphics queue or dedicated presentation hardware to perform presentation."

**Comment by oddhack** [comment]
This should be fixed in the 1.0.34 spec update.

**Comment by krOoze** [comment]
I feel the question is unanswered. But I suppose "because specification says so" is sufficient reason enough.

@jozefkucia Doesn't really follow. Same might apply to any other command (which is required to handle `GENERAL` silently anyway).

**Comment by TobiasHector** [comment]
@krOoze AFAIK the basic premise is that "GENERAL" covers all uses by the device itself. The Presentation Engine (which is what consumes a presentable image) is not necessarily part of the device - it is often external to the GPU, or managed by the OS.

In some cases this effectively means that it has to be converted to TILING_LINEAR, or some other format that the GPU can't natively consume. Trying to make this work in the face of unknown external entities would be nigh impossible - it would definitely require us to use "driver magic" which is against the spirit of the spec, and would possibly lead to performance degradation when using a windowing system vs. not.

Things would get even worse in the face of multiple external entities existing at once...

Note that I'm just speaking from what I believe to be the case, there may be other reasons I'm not aware of as I wasn't part of the original design discussions here.
