### ISSUE TITLE
Add the implicitly synchronized parameters to the per-function host synchronization block

### ISSUE THREAD

**Issue by ratchetfreak** [KhronosGroup/Vulkan-Docs#398]
In chapter 2.5 there is a list "Implicit Externally Synchronized Parameters" which says which objects must be synchronized on that aren't explicitly passed as parameters. 

The ones for vkCmd\* aren't mentioned in the "Host Synchronization" blocks in the per-function valid usage blocks. However the ones for vkDeviceWaitIdle and vkResetDescriptorPool are repeated there.

**Comment by TobiasHector** [comment]
I spotted this a couple of days ago as a result of another bug - fix is in flight already :)

**Comment by oddhack** [comment]
This should be fixed in the 1.0.33 spec update.
