### ISSUE TITLE
Bad vkDebugReportMessageEXT VU

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#399]
1) In VU(implicit) of `vkDebugReportMessageEXT` it reads:

> - `pLayerPrefix` **must** be a pointer to a valid
> - `pMessage` **must** be a pointer to a valid

2) When that is fixed, the non-implicit VU contains redundant versions of the above:

>  `pLayerPrefix` **must** be a `NULL` terminated string
> `pMessage` **must** be a `NULL` terminated string

3)

> `object` **may** be a Vulkan object

Does this mean `object` can be non-Vulkan object?
Shouldn't it be handle to `objectType` object (or `VK_NULL_HANDLE`)?

EDIT: If it should be `objectType` type, then since 1.0.41 `object` should perhaps be `NULL` or `VK_NULL_HANDLE` if dispatchable or non-dispatchable respectively.

4) Description lists `objType`. Should be `objectType`.
Also in `PFN_vkDebugReportCallbackEXT`.

5) Description contains `VK_NULL_OBJECT`. There's no such thing in spec or even `vulkan.h`.
Also in `PFN_vkDebugReportCallbackEXT`.

**Comment by courtney-g** [comment]
Now that you mention it, the object VU (object may be a Vulkan object) can probably go away. This structure is for the application sending and event down the chain that will cause a call-back using this data. The validation layers do not care what the contents of object are and simply copy it to the debug report sent to the application at the end of the chain.

**Comment by baldurk** [comment]
The validation layers aren't the only layers that exist, other layers or the ICD may care about the object parameter. Unless there's a compelling reason to allow invalid objects to be passed, I'd say it's better to just clarify that the objects must be valid or `VK_NULL_OBJECT`.

**Comment by krOoze** [comment]
Seems largely fixed, except 5.
Also seems to me `object` should be restricted to `objectType` type (unless `VK_DEBUG_REPORT_OBJECT_TYPE_UNKNOWN_EXT`). Or do I misunderstand the purpose of `objectType`?

**Comment by courtney-g** [comment]
I've submitted patch to change VK_NULL_OBJECT to VK_NULL_HANDLE

**Comment by krOoze** [comment]
This is largely fixed long ago. I am exporting the emergent Issue/Question, Closing this.
