### ISSUE TITLE
RGB to Shared Exponent Conversion

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#40]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#textures-RGB-sexp says:

> exp' = \max(-B-1, \left \lfloor \log_2(max_{clamped}+1+B) \right \rfloor)

I won't pretend to understand what this is actually doing, but adding 1+B before the log_2 seems weird to me (because it's a number of bits so why would you log it?). And I think that always results in exp' >= 4.

The similar equation in OpenGL looks more like

> exp' = \max(-B-1, \left \lfloor \log_2(max_{clamped} \right \rfloor) + 1 + B

although I think that's also broken because max_{clamped} can be 0 and log(0) is undefined.

Maybe doing the max inside the log is better:

> exp' = \left \lfloor \log_2(max(2^{-B-1}, max_{clamped})) \right \rfloor + 1 + B

which should give you a number 0 <= exp' <= E_max, which is hopefully closer to what's wanted, with no asymptotically undefined behaviour.

**Comment by oddhack** [comment]
Thanks! That looks like it might be a typo in converting the equation from the GL spec. We'll check into it.

**Comment by slippah** [comment]
Nice catch. Confirmed, this was a transcription error from the GL spec.  Fix in flight.

**Comment by oddhack** [comment]
Done in the 1.0.5 spec update.
