### ISSUE TITLE
PFN_vkFreeFunction doesn't indicate allocation scope

### ISSUE THREAD

**Issue by blajzer** [KhronosGroup/Vulkan-Docs#400]
In VkAllocationCallbacks, both the allocation and reallocation functions provide an allocation scope. The free function, however, does not. This seems like an oversight since if an appropriate allocator is chosen in alloc/realloc based on the allocation scope it's impossible to know which allocator to free from.

I realize that the spec ostensibly indicates that the allocation callbacks aren't provided for performance reasons, but the current signatures of the callback functions indicate otherwise. It also makes a lot of sense on embedded or memory-limited platforms to use different allocators based on allocation/deallocation frequency: i.e. using a frame allocator for command allocations to prevent memory fragmentation, but a normal heap for other allocations.

I can work around the non-uniformity between alloc and free by having multiple allocation callback structs that get passed into the relevant vkCreate*() calls, but it would be a lot better/cleaner to just have this information available in the free function.

**Comment by blajzer** [comment]
> In many parts of the Vulkan API it forces the user to do the book-keeping so it does not have to do it itself. E.g. you are supposed to remember the current layout of a image (and provide it back to Vulkan commands that need to know that).

I recognize and accept that.

Imagine the following pseudo-code:
````
void* alloc(..., VkSystemAllocationScope scope) {
    if (scope == VK_SYSTEM_ALLOCATION_SCOPE_COMMAND) {
        return alloc_from_frame_heap();
    } else {
        return alloc_from_persistent_heap();
    }
}
````

When attempting to free though, we now don't know which heap to call free on. Maintaining a bookkeeping structure in this case (array/map/hash table/whatever) defeats the purpose due to both the increased memory usage and the cost of traversing said structure to figure out which heap the allocation came from. Contrast this with the couple extra machine code instructions it would take to just pass the allocation scope into the free.

**Comment by krOoze** [comment]
@blajzer Usually you would overallocate and store it in the extra space. E.g. the scope could be in `p[-2]` and size in `p[-1]`. Then the free would have similar if-else structure using `p[-2]`.

**Comment by ratchetfreak** [comment]
Personally, I dislike that the classic malloc api forces overallocation like that. I'd prefer if some meta data of the allocation also get tracked by the caller.

Though I'm pretty sure that drivers will implement their own suballocators on top of the memory callbacks if the allocation becomes performance critical for them.
