### ISSUE TITLE
ISO date format typo with vulkan 1.0.27

### ISSUE THREAD

**Issue by Tele42** [KhronosGroup/Vulkan-Docs#402]
Good day,
I was skimming over the vulkan specs and encountered some Last Modified: 2016-14-01 date fields which does not match the date formatting elsewhere. This appears to have been a minor typo with the 1.0.27 spec update for [VK_KHR_surface](https://github.com/KhronosGroup/Vulkan-Docs/commit/ef053e7c82447b292c96470a24dd135f2da78b10#diff-f8a8bb2b0394e28abf9bf95131efef9eR14) and [VK_KHR_android_surface](https://github.com/KhronosGroup/Vulkan-Docs/commit/ef053e7c82447b292c96470a24dd135f2da78b10#diff-4c03723b7fd166e58d763323c29b52afR14).

**Comment by oddhack** [comment]
Thanks. This will be fixed in the next weekly update. It's such a minor thing that I'm not going to bother tracking it in the ChangeLog.txt - already fixed in our internal repository.
