### ISSUE TITLE
Release number instead of release date in git

### ISSUE THREAD

**Issue by atom-symbol** [KhronosGroup/Vulkan-Docs#405]
Hello

Some people are confused by the fact that git releases/tags aren't using the release number. This can be fixed by replacing the pattern `v1.0-core-20161025` with one of these:

- `v1.0.32-core`
- `v1.0.32`

https://github.com/KhronosGroup/Vulkan-Docs/releases

Please take a look at the development of the Go programming language:

- https://github.com/golang/go/releases?after=go1.2rc3
- https://github.com/golang/go/releases?after=weekly.2012-01-20

Golang was using dates until version 1. After version 1, golang switched from pattern `weekly.2012-01-15` to pattern `go1.1.2`. --- Version 1 of Vulkan-Docs has already been released, so avoiding the date in git is logical if golang is taken for a positive example.

**Comment by oddhack** [comment]
We agreed to start using this convention with future weekly update tags.

**Comment by oddhack** [comment]
Done starting with the 1.0.33-core tag.

**Comment by krOoze** [comment]
@oddhack Stupid Q: what does the "core" stand for?

**Comment by oddhack** [comment]
Core API, vs. API with extensions. Has little use now that we've moved to the single-branch model. We might take that off the tags in the future.
