### ISSUE TITLE
HOST_WRITE useful or validation layers wrong?

### ISSUE THREAD

**Issue by qnope** [KhronosGroup/Vulkan-Docs#406]
In the specs about HOST_WRITE_BIT it is write : 

> For host writes to be seen by subsequent command buffer operations, a pipeline barrier from a source of VK_ACCESS_HOST_WRITE_BIT and VK_PIPELINE_STAGE_HOST_BIT to a destination of the relevant device pipeline stages and access types must be performed. Note that such a barrier is performed implicitly upon each command buffer submission, so an explicit barrier is only rarely needed

Rachet Freak wrote [here](https://github.com/KhronosGroup/Vulkan-Docs/issues/261):
> However mapped memory already gets an implicit vkCmdPipelineBarrier from Host to All_Commands on vkSubmit (without waiting on the semaphores with waitStageMask containing Host?).

However, when you transition (through a vkCmdPipelineBarrier (so in a commandBuffer)) one image from PREINITIALIZED layout with a srcAccessMask to 0 instead of HOST_WRITE_BIT, you get an error : 
> validation layer: Source AccessMask 0 [None] must have required access bit 16384 [VK_ACCESS_HOST_WRITE_BIT]  when layout is VK_IMAGE_LAYOUT_PREINITIALIZED, unless the app has previously added a barrier for this transition.

Is there an error from the specs? From the validation layers? Is the barrier we are talking about is a pure execution barrier and not a memory one? Am I missing something?

PS : (I wrote it on SO, but since I receive no answer, I believe more that it is possible that there is an error in Layers (though i am not an expert at all))

**Comment by krOoze** [comment]
> PS : (I wrote it on SO, but since I receive no answer, I believe more that it is possible that there is an error in Layers (though i am not an expert at all))

You just did receive one 😄
I think it belongs to [validation layers](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/), which [do not seem to acknowledge this corner case](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/8567fecbf563420f5900ade277ca68908aa87259/layers/core_validation.cpp#L9005), but we shall see...

**Comment by TobiasHector** [comment]
> Is there an error from the specs? From the validation layers? Is the barrier we are talking about is a pure execution barrier and not a memory one? Am I missing something?

As @krOoze suggested on SO, the validation layer is wrong in this case. The only time HOST_WRITE_BIT is actually required here would be if you were to submit a command buffer with the read op waiting on an event, and having the host submit that command buffer, then write some values and then signal the event.

You should raise an issue against the validation layers.
