### ISSUE TITLE
VkEventCreateInfo missing parameter descriptions

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#407]
`VkEventCreateInfo` is missing boilerplate descriptions for `sType` and `pNext` parameters.

**Comment by TobiasHector** [comment]
Fix in flight for this already as part of the sync chapter rewrite which I *promise* is nearly done...

**Comment by oddhack** [comment]
This should be fixed in the 1.0.35 spec update, as part of the synchronization language rewrite.
