### ISSUE TITLE
VkDisplayKHR/VkDisplayModeKHR VkDebugReportObjectTypeEXT enum entries missing

### ISSUE THREAD

**Issue by mark-lunarg** [KhronosGroup/Vulkan-Docs#408]
It appears that **VkDebugReportObjectTypeExt** enums are not defined for **VkDisplayKHR** or  **VkDisplayModeKHR** objects.  Validation relies heavily on these debug report object type definitions.

**Comment by mark-lunarg** [comment]
See PR #413

**Comment by oddhack** [comment]
@mark-lunarg can you resubmit this as an internal Khronos MR? Until we get the licensing issue resolved, changes need to flow only in that direction.

**Comment by mark-lunarg** [comment]
Closed PR and opened Gitlab MR 1717.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.37 spec update.
