### ISSUE TITLE
vkCreateSwapchainKHR failing with 'Invalid SwapchainKHR, SurfaceKHR object' no matter what I do [UE1]

### ISSUE THREAD

**Issue by CacoFFF** [KhronosGroup/Vulkan-Docs#411]
Trying to learn the API by creating a renderer for Unreal Tournament (99) and I'm unable to get past vkCreateSwapchainKHR without crashing the game (more like triggering the game's exception handlers).

For the Vulkan initialization code I tried using C, C++ twice, even dynamically loading the VK library and methods (despite the renderer being a plugin) with the same results so I decided to load the validation layers.
This is pretty much the output mixed up with some status logging, the two object tracker errors at the end of the log are always the same in every single scenario. (callback taken from cube.c)

> Init: [VK] Init | 1280x960@4 f=16
> Init: DEBUG: [DebugReport] Code 1 : Added callback
> XC_UCC: === Last line repeats 4 times.
> Init: INFORMATION: [ObjectTracker] Code 0 : OBJ[0x1] : CREATE Debug Report object 0x3a61cf8
> Init: DEBUG: [DebugReport] Code 1 : Added callback
> XC_UCC: === Last line repeats 1 times.
> Init: INFORMATION: [ObjectTracker] Code 0 : OBJ[0x2] : CREATE Physical Device object 0x3aa5338
> Init: Checking GPU 0...
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_KHR_sampler_mirror_clamp_to_edge (C:\Windows\SysWow64\.\amdvlk32.dll) version 0.0.1
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_KHR_swapchain (C:\Windows\SysWow64\.\amdvlk32.dll) version 0.0.68
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_AMD_rasterization_order (C:\Windows\SysWow64\.\amdvlk32.dll) version 0.0.1
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_AMD_shader_ballot (C:\Windows\SysWow64\.\amdvlk32.dll) version 0.0.1
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_AMD_shader_trinary_minmax (C:\Windows\SysWow64\.\amdvlk32.dll) version 0.0.1
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_AMD_shader_explicit_vertex_parameter (C:\Windows\SysWow64\.\amdvlk32.dll) version 0.0.1
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_AMD_gcn_shader (C:\Windows\SysWow64\.\amdvlk32.dll) version 0.0.1
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_AMD_draw_indirect_count (C:\Windows\SysWow64\.\amdvlk32.dll) version 0.0.1
> Init:  - Name: AMD Radeon (TM) R7 360 Series
> Init:  - Vendor ID: 4098
> Init:  - API Version: 4194325
> Init:  - Driver Version: 4206592
> Init: Queue indices: Graphics=0, Compute=1, Transfer=2
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_KHR_sampler_mirror_clamp_to_edge (C:\Windows\SysWow64\.\amdvlk32.dll) version 0.0.1
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_KHR_swapchain (C:\Windows\SysWow64\.\amdvlk32.dll) version 0.0.68
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_AMD_rasterization_order (C:\Windows\SysWow64\.\amdvlk32.dll) version 0.0.1
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_AMD_shader_ballot (C:\Windows\SysWow64\.\amdvlk32.dll) version 0.0.1
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_AMD_shader_trinary_minmax (C:\Windows\SysWow64\.\amdvlk32.dll) version 0.0.1
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_AMD_shader_explicit_vertex_parameter (C:\Windows\SysWow64\.\amdvlk32.dll) version 0.0.1
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_AMD_gcn_shader (C:\Windows\SysWow64\.\amdvlk32.dll) version 0.0.1
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_AMD_draw_indirect_count (C:\Windows\SysWow64\.\amdvlk32.dll) version 0.0.1
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_KHR_sampler_mirror_clamp_to_edge (Unknown) version 0.0.1
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_KHR_swapchain (Unknown) version 0.0.68
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_AMD_rasterization_order (Unknown) version 0.0.1
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_AMD_shader_ballot (Unknown) version 0.0.1
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_AMD_shader_trinary_minmax (Unknown) version 0.0.1
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_AMD_shader_explicit_vertex_parameter (Unknown) version 0.0.1
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_AMD_gcn_shader (Unknown) version 0.0.1
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_AMD_draw_indirect_count (Unknown) version 0.0.1
> Init: DEBUG: [loader] Code 0 : Chain: device: Loading layer library D:\VulkanSDK\1.0.30.0\Bin32\.\VkLayer_unique_objects.dll
> Init: INFORMATION: [loader] Code 0 : Insert device layer VK_LAYER_GOOGLE_unique_objects (D:\VulkanSDK\1.0.30.0\Bin32\.\VkLayer_unique_objects.dll)
> Init: DEBUG: [loader] Code 0 : Chain: device: Loading layer library D:\VulkanSDK\1.0.30.0\Bin32\.\VkLayer_swapchain.dll
> Init: INFORMATION: [loader] Code 0 : Insert device layer VK_LAYER_LUNARG_swapchain (D:\VulkanSDK\1.0.30.0\Bin32\.\VkLayer_swapchain.dll)
> Init: DEBUG: [loader] Code 0 : Chain: device: Loading layer library D:\VulkanSDK\1.0.30.0\Bin32\.\VkLayer_core_validation.dll
> Init: INFORMATION: [loader] Code 0 : Insert device layer VK_LAYER_LUNARG_core_validation (D:\VulkanSDK\1.0.30.0\Bin32\.\VkLayer_core_validation.dll)
> Init: DEBUG: [loader] Code 0 : Chain: device: Loading layer library D:\VulkanSDK\1.0.30.0\Bin32\.\VkLayer_image.dll
> Init: INFORMATION: [loader] Code 0 : Insert device layer VK_LAYER_LUNARG_image (D:\VulkanSDK\1.0.30.0\Bin32\.\VkLayer_image.dll)
> Init: DEBUG: [loader] Code 0 : Chain: device: Loading layer library D:\VulkanSDK\1.0.30.0\Bin32\.\VkLayer_object_tracker.dll
> Init: INFORMATION: [loader] Code 0 : Insert device layer VK_LAYER_LUNARG_object_tracker (D:\VulkanSDK\1.0.30.0\Bin32\.\VkLayer_object_tracker.dll)
> Init: DEBUG: [loader] Code 0 : Chain: device: Loading layer library D:\VulkanSDK\1.0.30.0\Bin32\.\VkLayer_parameter_validation.dll
> Init: INFORMATION: [loader] Code 0 : Insert device layer VK_LAYER_LUNARG_parameter_validation (D:\VulkanSDK\1.0.30.0\Bin32\.\VkLayer_parameter_validation.dll)
> Init: DEBUG: [loader] Code 0 : Chain: device: Loading layer library D:\VulkanSDK\1.0.30.0\Bin32\.\VkLayer_threading.dll
> Init: INFORMATION: [loader] Code 0 : Insert device layer VK_LAYER_GOOGLE_threading (D:\VulkanSDK\1.0.30.0\Bin32\.\VkLayer_threading.dll)
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_KHR_sampler_mirror_clamp_to_edge (C:\Windows\SysWow64\.\amdvlk32.dll) version 0.0.1
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_KHR_swapchain (C:\Windows\SysWow64\.\amdvlk32.dll) version 0.0.68
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_AMD_rasterization_order (C:\Windows\SysWow64\.\amdvlk32.dll) version 0.0.1
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_AMD_shader_ballot (C:\Windows\SysWow64\.\amdvlk32.dll) version 0.0.1
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_AMD_shader_trinary_minmax (C:\Windows\SysWow64\.\amdvlk32.dll) version 0.0.1
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_AMD_shader_explicit_vertex_parameter (C:\Windows\SysWow64\.\amdvlk32.dll) version 0.0.1
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_AMD_gcn_shader (C:\Windows\SysWow64\.\amdvlk32.dll) version 0.0.1
> Init: DEBUG: [loader] Code 0 : Device Extension: VK_AMD_draw_indirect_count (C:\Windows\SysWow64\.\amdvlk32.dll) version 0.0.1
> Init: INFORMATION: [ObjectTracker] Code 0 : OBJ[0x3] : CREATE Device object 0xe8eef80
> Init: INFORMATION: [ObjectTracker] Code 0 : OBJ[0x4] : CREATE Command Pool object 0x1
> Init: INFORMATION: [ObjectTracker] Code 0 : OBJ[0x5] : CREATE Queue object 0xe8ef69c
> Init: INFORMATION: [ObjectTracker] Code 0 : OBJ[0x6] : CREATE Queue object 0xe8ef6cc
> Init: INFORMATION: [ObjectTracker] Code 0 : OBJ[0x7] : CREATE Queue object 0xe8ef6b4
> Init: INFORMATION: [ObjectTracker] Code 0 : OBJ[0x8] : CREATE Semaphore object 0x2
> Init: INFORMATION: [ObjectTracker] Code 0 : OBJ[0x9] : CREATE Semaphore object 0x3
> Init: INFORMATION: [ObjectTracker] Code 0 : OBJ[0xa] : CREATE SurfaceKHR object 0x4
> Init: ERROR: [ObjectTracker] Code 4 : Invalid SwapchainKHR Object 0x326bf800000000
> Init: ERROR: [ObjectTracker] Code 4 : Invalid SurfaceKHR Object 0x200000000

Also, are there any specific VS 2015 project settings that are critical to properly running the api?
Asking because UE1 packages need a very specific set of macros/directives to properly load into the game.
Is there any chance the AMD driver is at fault?

Also adding an overview of the intialization directives:
```
UBOOL UVulkanRenderDevice::Init(UViewport* InViewport, INT NewX, INT NewY, INT NewColorBytes, UBOOL Fullscreen)
{
	guard(UVulkanRenderDevice::Init);

	debugf( NAME_Init, TEXT("[VK] Init | %ix%i@%i f=%i"), NewX, NewY, NewColorBytes, Fullscreen);
	VkResult Res = VK_SUCCESS;
	
#define XC_VK_CHECK(n,f,e) guard(n); if ( Res=f) appErrorf(NAME_Init,TEXT(e ##": %s"), TranslateVkError(Res)); unguard;
	LoadAPI();
	XC_VK_CHECK(CreateInstance, Vulkan.CreateInstance(true),"Failed to create instance")
	LoadInstanceLevelEntryPoints(Vulkan);
	XC_VK_CHECK(CreateDebugCallback, Vulkan.CreateDebugCallback(),"Failed to create debug callback")
	XC_VK_CHECK(SelectGPU, Vulkan.SelectGPU(),"Failed to select GPU")
	XC_VK_CHECK(CreateDevice, Vulkan.CreateDevice(), "Failed to create logical device")
	LoadDeviceLevelEntryPoints(Vulkan);
	XC_VK_CHECK(GraphicsCommandPool, Vulkan.CreateCommandPool(Vulkan.GraphicsCommandPool, Vulkan.GraphicsQueueFamilyIndex), "Failed to create graphics command pool" )
	GetDeviceQueue();
	CreateSemaphores();
	XC_VK_CHECK(CreateSurface, Vulkan.CreateSurface((HWND)InViewport->GetWindow()),"Failed to create presentation surface")
	XC_VK_CHECK(CreateSwapchain, Vulkan.CreateSwapChain( (uint32_t*)&NewX, (uint32_t*)&NewY, UseVSync!=0),"Failed to create swapchain")
...
```

**Comment by krOoze** [comment]
I am not sure debugging help belongs in Issues on this repo, but I ready to help.

I need to see your Vulkan.CreateSwapChain() implementation, values and values you supply to it.
Or you need to supply api_dump log.

**Comment by CacoFFF** [comment]
I scrapped my original c++ implementation, but I got these two.
Same error messages in both cases.
[CreateSwapChain.txt](https://github.com/KhronosGroup/Vulkan-Docs/files/592798/CreateSwapChain.txt)

**Comment by krOoze** [comment]
From the log the objects are invalid.

My guess using uninitialized value for oldSwapchain (needs to be `VK_NULL_HANDLE` for the first use).

From the log you appaerently use different Surface than the one you created (0x200000000 vs 0x4). Looks like shifted or something.

**Comment by CacoFFF** [comment]
This is weird, decided to put the VK initialization code in a static library and simply have the UE1 package link to it and call functions.
Got a couple of failures in functions that required passing elements of my 'VkDrvCpp' struct (that has pretty much all of the pointers, refs, etc).
When I rewrote the functions so that nothing is passed as parameters (except for X,Y dimensions and HWND) everything created fine.

The whole issue was probably the result of a struct alignment/typedefs messing up the compiler, UE1 is very picky with that.
Feel free to close, but still we could use some documentation regarding compiler directives, I suppose VK doesn't run with everything yet...

> Init: INFORMATION: [ObjectTracker] Code 0 : OBJ[0x3] : CREATE Device object 0xa2cd020
> Init: INFORMATION: [ObjectTracker] Code 0 : OBJ[0x4] : CREATE Command Pool object 0x1
> Init: INFORMATION: [ObjectTracker] Code 0 : OBJ[0x5] : CREATE Queue object 0xa2cd73c
> Init: INFORMATION: [ObjectTracker] Code 0 : OBJ[0x6] : CREATE Queue object 0xa2cd76c
> Init: INFORMATION: [ObjectTracker] Code 0 : OBJ[0x7] : CREATE Queue object 0xa2cd754
> Init: INFORMATION: [ObjectTracker] Code 0 : OBJ[0x8] : CREATE Semaphore object 0x2
> Init: INFORMATION: [ObjectTracker] Code 0 : OBJ[0x9] : CREATE Semaphore object 0x3
> Init: INFORMATION: [ObjectTracker] Code 0 : OBJ[0xa] : CREATE SurfaceKHR object 0x4
> Init: INFORMATION: [ObjectTracker] Code 0 : OBJ[0xb] : CREATE SwapchainKHR object 0x5
> Init: INFORMATION: [ObjectTracker] Code 0 : OBJ[0xc] : CREATE SwapchainImage object 0x6
> Init: INFORMATION: [ObjectTracker] Code 0 : OBJ[0xd] : CREATE SwapchainImage object 0x7
> Log: Bound to Galaxy.dll
> Init: Galaxy is using DirectSound
> ...
