### ISSUE TITLE
vkCmdExecuteCommands and "pending execution" state counter-intuitive

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#414]
`vkCmdExecuteCommands` if taken literaly from the spec puts the secondary buffer straight into "pending execution" state:

> A secondary command buffer is considered to be _pending execution_ from the time its execution is recorded into a primary buffer (via `vkCmdExecuteCommands`) until the final time that primary buffer’s submission to a queue completes.

This wording creates some ambiguity what state the buffer is in if its primary buffer is never submitted.

Even the layers does not seem to decide what is correct interpretation and behave differently depending on what particular (state dependent) command was used (sometimes treating the buffer as "busy", sometimes there's exception for the case and sometimes it simply does not seem to check) as discovered here:  
http://stackoverflow.com/questions/40749420/rerecording-secondary-command-buffers/40749614#40749614

The spec wording strategy marks the duration as "pending execution" retrospectively (i.e. only after it is known which submission is the final one) making it further hard to read and interpret. I think the wording should be more direct, e.g.:

> Secondary command buffer is _pending execution_ when its primary command buffer (into which it is recorded via `vkCmdExecuteCommands`)  is in pending execution or recording state.

Also the quote is in `vkBeginCommandBuffer` section. That does not seem like a proper place. It should perhaps be in the chapter intro (where state is discussed, but somehow the _pending execution_ one is missing there).

**Comment by TobiasHector** [comment]
I think we've run into this a few times; "pending execution" is used as a general term to either mean "submitted to a queue" or "cmdexecutecommands has been called on it", but there's a few places where that doesn't quite make sense. We sort of need separate terms for both of these separate states, we've just not done that yet.

As written, it *is* intended that a secondary command buffer is "pending execution" as soon as it's put into a primary, not when that primary has been submitted - and at least in some cases that constraint is actually meaningful. There are other times where it's not accurate and confuses things, like what you've run into.

Fixing this unfortunately means combing the spec and finding all of the uses of "pending execution" and figuring out what they actually intended. Definitely worth doing, but it might take a little while to get done.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.43 spec update.
