### ISSUE TITLE
Table 6.2 doesn't mention COMMAND_PROCESS_BIT_NVX

### ISSUE THREAD

**Issue by ratchetfreak** [KhronosGroup/Vulkan-Docs#415]
It is unclear which memory access flag(s) are used by the VK_PIPELINE_STAGE_COMMAND_PROCESS_BIT_NVX stage and the example code for the extension appendix doesn't include the full barriers.

**Comment by TobiasHector** [comment]
We noticed this internally before we pushed the spec, but unfortunately didn't have time to rectify it before we pushed the release, and with Thanksgiving in the US the spec authors weren't available to do work on the fix anyway! Hopefully we'll have a fix in short order though.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.37 spec update.
