### ISSUE TITLE
[Vulkan Quick Reference] VkExtensionProperties: layerName should be extensionName

### ISSUE THREAD

**Issue by hesiod** [KhronosGroup/Vulkan-Docs#418]
I don't think the [Quick Reference card](https://www.khronos.org/registry/vulkan/specs/1.0/refguide/Vulkan-1.0-web.pdf) is generated from this repo (?), but I wanted to have this issue written down somewhere:

On page 10, section Extended Functionality, it says that `VkExtensionProperties` has a field named `layerName`, but it's actually called `extensionName`.

**Comment by krOoze** [comment]
No, it is made by external company (according to the footer info). The sources are available but only hosted on the Khronos registry page. This is the correct place to report issues if any...

While at it, gonna piggy-back these here:
1) It's missing `VK_ERROR_FRAGMENTED_POOL`

2) In `VK_ERROR_FRAGMENTED_POOL` it has wrong (old) type for `pData`.

3) Does not address `VK_COLORSPACE_SRGB_NONLINEAR_KHR` -> `VK_COLOR_SPACE_SRGB_NONLINEAR_KHR` change

4) It has problem deciding if pointer `*` should stick to the types or to the names. Choose one.

5) 
  a) Some of the spec macros (e.g. version handling ones) maybe should be there.

  b) Also maybe `VkStructureType`. Concise way to do it would be to note how to transform `struct` name into `VkStructureType` name.

  c) Also perhaps note about `pNext` (that it is `NULL` unless extensions say so).

6) The card does not document `VK_EXT_debug_report` yet it has `VK_ERROR_VALIDATION_FAILED_EXT` in there.

7) It has a revision number in the footer and it was not incremented after the last edit. Please don't forget to increment it next time.

**Comment by oddhack** [comment]
@slippah we need to get Kathleen & Dave to address feedback like this, but neither is on github yet AFAIK.

**Comment by slippah** [comment]
I'll ping them and see if we can't get them tracking.  We may want a specific label for the Quick Ref card.

**Comment by oddhack** [comment]
@hesiod @krOoze please review the new 1.1 reference card https://www.khronos.org/registry/vulkan/specs/1.1/refguide/Vulkan-1.1-web.pdf and see if these issues were dealt with. The feedback was passed on to the ref card authors but I don't know how much of it was addressed. Unfortunately the authors aren't active on github and the document sources, while available in the Vulkan registry, are in the proprietary InDesign format which very few people have access to.

**Comment by krOoze** [comment]
@oddhack Nope, still `layerName` in `VkExtensionProperties` in 1.1 version.
The 1.0 version (which is still hosted) was not touched at all.

**Comment by oddhack** [comment]
We'll work on getting a 1.1 ref card update including this stuff. It's unlikely a 1.0 ref card update will be done at this point.

**Comment by oddhack** [comment]
The 1.1 card was updated in November 2018 and I believe addressed all this stuff with the exception of @krOoze's point #5. Those were all enhancement requests rather than errors, and I suspect the refcard authors left them out due to space limitations, so closing this now.
