### ISSUE TITLE
Addition of a document type definition for safe API specification

### ISSUE THREAD

**Issue by elfring** [KhronosGroup/Vulkan-Docs#42]
A document type definition can help to work with corresponding explanations because it describes the involved data structures to some degree. [Such a DTD](https://en.wikipedia.org/wiki/Document_type_definition "Description for document type definitions") can be added so that further improvements will become easier for the safe data exchange around [this evolving software library](https://github.com/KhronosGroup/Vulkan-Docs/blob/d204ac2f6991f75fab2ebc22136fd179d692f84f/src/spec/vk.xml#L1 "Update candidate: API specification").

A DTD format was standardised as a basis for XML documents. Some technical challenges and limitations were noticed so that [another standard like W3C XML Schema](https://en.wikipedia.org/wiki/XML_Schema_%28W3C%29 "Description for the XML Schema standard") evolved. Such a XML schema definition can also be added so that corresponding handling of provided [application programming interfaces](https://en.wikipedia.org/wiki/Application_programming_interface "Description for the usage of application programming interfaces") might become more consistent.

**Comment by oddhack** [comment]
vk.xml comes with a Relax NG Compact schema (registry.rnc in the same directory), which serves the same function as a DTD for our current needs (if there's something you need to do specifically beyond validation of the XML that the RNC schema will not support, please identify that here). I think there may be tools to convert RNC to DTD if you specifically require that format - not sure.

AFAICT, DTDs are on the way out (per Wikipedia entry at https://en.wikipedia.org/wiki/Document_type_definition - "As of 2009, newer XML namespace-aware schema languages (such as W3C XML Schema and ISO RELAX NG) have largely superseded DTDs. A namespace-aware version of DTDs is being developed as Part 9 of ISO DSDL[1]. DTDs persist in applications that need special publishing characters, such as the XML and HTML Character Entity References, which derive from larger sets defined as part of the ISO SGML standard effort.").

The current RNC schema could stand to be augmented to better  constrain attribute and tag values, something I've not had time for, and if that were something you were interested in contributing to it would be welcome.

**Comment by elfring** [comment]
* I wonder on details around XML attributes like "successcodes" and "errorcodes".
* Can [your Relax NG schema](https://github.com/KhronosGroup/Vulkan-Docs/blob/d204ac2f6991f75fab2ebc22136fd179d692f84f/src/spec/registry.rnc#L22 "Update candidate: XML schema") work together with [the object constraint language](https://en.wikipedia.org/wiki/Object_Constraint_Language "Description for the object constraint language")?

**Comment by NicolBolas** [comment]
> Such a XML schema definition can also be added so that corresponding handling of provided application programming interfaces might become more consistent.

A well-constructed Relax NG document can be automatically converted into an XML Schema. There are tools for doing this already. The DocBook project uses these tools; the Relax NG schema is the normative one, with the XML Schema being automatically generated.

If you find that those tools are unable to convert the given Relax NG schema, you should specify what problems you had so that the schema can be adjusted.

**Comment by elfring** [comment]
>What is the importance of this?

* Would you like to see that [data type constraints](https://en.wikipedia.org/wiki/Data_type#Overview "Usage of data types") will be expressed in a precise way?
* Do you care for [proper categorisation](https://en.wikipedia.org/wiki/Taxonomy_%28general%29 "Usage of taxonomies") of the provided functions and data structures?

**Comment by NicolBolas** [comment]
@elfring : No, to both of those.

We're not talking about something massively complex here. We're talking about a hundred or so functions, some data structures, and some enumerators. This doesn't need to be that complicated.

We're talking about a piece of data who's _sole purpose_ is to generate Vulkan entrypoints/bindings for various languages. I don't see what having a "precise way" to specifiy "data type constraints" will do towards that end. I don't see how "proper categorization" will help, beyond the categories that already exist.

"Good enough" in this case is good enough.

Maybe "what is the importance of this" was not precise enough. The better question is "What are you trying to do that you _need_ this?"

**Comment by oddhack** [comment]
+1 @NicolBolas . Abstract CS framework questions can be entertaining, but they aren't actionable. If there's a specific reason you need a DTD instead of the RNC schema, there's a way to obtain that. If there are specific enhancements to the XML that you need, please identify what those are (and preferably, post a PR showing how to modify the schema/XML to express them)

**Comment by elfring** [comment]
Will the clarification about the advanced use of [the provided Relax NG schema](https://github.com/KhronosGroup/Vulkan-Docs/blob/d204ac2f6991f75fab2ebc22136fd179d692f84f/src/spec/registry.rnc#L246 "Extensions for the API description?") be continued with other feature requests (or bug reports) like "[Performing ordinary work in an easy way](https://github.com/KhronosGroup/Vulkan-Docs/issues/58 "Can API usage become more convenient?")"?

**Comment by elfring** [comment]
>If there's a specific reason you need a DTD instead of the RNC schema, there's a way to obtain that.

* Would you like to share any more experiences for the support of [the data format "RELAX NG schema"](http://relaxng.org/ "RELAX NG home page") in current tools like internet browsers?
* How do do you think about to [add any targets to the make file](https://github.com/KhronosGroup/Vulkan-Docs/blob/d204ac2f6991f75fab2ebc22136fd179d692f84f/src/spec/Makefile#L30 "Generate all outputs for Vulkan") for the conversion of the published Vulkan data model into alternative formats?
