### ISSUE TITLE
non-dispatchable handles defined as pointers on 64bit platforms

### ISSUE THREAD

**Issue by MaVo159** [KhronosGroup/Vulkan-Docs#420]
The spec states that non-dispatchable handles are just 64bit integers, which should not be interpreted as pointers since it is up to the implementation what they are. The way they are defined by default makes sense:
#define VK_DEFINE_NON_DISPATCHABLE_HANDLE(object) typedef uint64_t object;

However, on 64bit architectures they are defined like this:
#define VK_DEFINE_NON_DISPATCHABLE_HANDLE(object) typedef struct object##_T *object;

Is there a particular benefit to this? It seems identical to me. I am asking because this creates problems if vulkan.h is used in languages that can link directly against C libraries, if they care about what is a pointer and what isn't. In particular I am running into issues with Go (garbage collector scans stack pointers and notices that there is a pointer which doesn't point to a reasonable place).

The only reason for this I could come up with is that it may be desirable to express that the type is pointer sized on 64bit platforms, but in that case uintptr_t would do the job without (incorrectly) indicating pointer semantics.

Removing the special case for 64bit works fine for me.
What am I missing?

**Comment by krOoze** [comment]
I think it is a cheap way to add compile-time type safety in C99
Second (small) advantage is, that the implementation can potentially use it as a pointer.

**Comment by courtney-g** [comment]
Yes, primarily for type safety.
Compiler will complain if you try to pass a VkInstance where a VkDevice is needed. When defined as uint64_t compiler does not complain.

**Comment by ratchetfreak** [comment]
@courtney-g bad example there as both vkInstance and vkDevice are dispatchable handles (pointers)

vkFence vs. vkSemaphore are better examples.

**Comment by MaVo159** [comment]
How does this add compile time type safety? Or do you mean the whole typedef per handle type approach? I am only arguing for removing the special case for 64bit, so the type safety shouldn't change.

Regarding the second point: The define is encapsulated in a `#if !defined(VK_DEFINE_NON_DISPATCHABLE_HANDLE)`, so an implementation can easily override it if convenient.

**Comment by ratchetfreak** [comment]
A C compiler will refuse to assign a vkImage_T * to a vkBuffer_T* while it will happily assign a uint64 to a uint64. 

If C had strong typedefs (where there is no implicit conversion) this wouldn't be a problem.

**Comment by MaVo159** [comment]
```
VkFence a;
VkEvent b;
a=b;
```
I don't think this actually generates an error in C, only in C++. But I guess that doesn't change the point (and I would expect C compilers to at least give a warning).
Thanks for clarifying. How inconvenient that 32bit archs don't benefit from this in addition to the pointer semantics issue. But I guess the benefits outweigh the problems since people writing bindings can just override the define.
