### ISSUE TITLE
Redundant Valid Usage statements for VkImageBlit struct (in copies.txt)

### ISSUE THREAD

**Issue by daveh-lunarg** [KhronosGroup/Vulkan-Docs#421]
Section 18.5, Image Copies With Scaling, contains the following valid usage statements for the VkImageBlit struct: 

* The pname:layerCount member of pname:srcSubresource and pname:dstSubresource must: match
* The pname:layerCount member of pname:dstSubresource must: be equal to the pname:layerCount member of pname:srcSubresource

These appear to be redundant and should be collapsed into a single valid usage.

**Comment by TomOlson** [comment]
We agree, thanks. Asking for an internal MR from @MarkY-LunarG or @daveh-lunarg.

**Comment by daveh-lunarg** [comment]
MR submitted, https://gitlab.khronos.org/vulkan/vulkan/merge_requests/1829.

- Dave

**Comment by oddhack** [comment]
@daveh-lunarg - I removed the internal URL, there's no use to publishing those here as outside developers can't see them. Usual process is that we fix it internally, then close the public issue once the periodic github update containing that fix is done. Not a big deal, just a heads-up for future reference.

**Comment by daveh-lunarg** [comment]
MR approved.
