### ISSUE TITLE
Rendering to 3D textures requires VK_IMAGE_VIEW_TYPE_2D_ARRAY

### ISSUE THREAD

**Issue by BearishSun** [KhronosGroup/Vulkan-Docs#422]
The specification seems to be missing a part about using 3D textures as framebuffer attachments. More specifically, it never mentions that they need to be referenced using the VK_IMAGE_VIEW_TYPE_2D_ARRAY, instead of the VK_IMAGE_VIEW_TYPE_3D.

In fact the table here (https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#resources-image-views-compatibility), says that VK_IMAGE_TYPE_3D must be mapped with VK_VIEW_TYPE_3D.

Is this meant to be part of the spec, but missing? Or is this not part of the spec, and it's just something that my driver's implementation supports?

If its not meant to be part of the spec, what's the appropriate way to bind a 3D texture for rendering (i.e. using gl_Layer to output to different slices of the 3D texture).

**Comment by pdaniell-nv** [comment]
With the current Vulkan 1.0 spec there is no way to render to slices of a 3D image. This is something we are aware of and hope to resolve soon.

**Comment by slippah** [comment]
See also #149; we'll address both of these together.  It is new functionality so needs to be in a separately ratified spec of some sort.

**Comment by pdaniell-nv** [comment]
Today the Vulkan working group released new extension VK_KHR_maintenance1 (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_maintenance1) which adds support for rendering to a 3D slice. Conformant implementations will follow shortly. The latest Vulkan conformance 1.0.2.0 has test coverage for the new extension.
