### ISSUE TITLE
Is something submitted if vkQueueSubmit returns an OOM error?

### ISSUE THREAD

**Issue by tomaka** [KhronosGroup/Vulkan-Docs#423]
What happens if I call the `vkQueueSubmit` function with multiple batches, and the function returns an error? Is it possible that some of the batches or some of the command buffers get executed, or is it guaranteed that nothing has started execution? The specs don't say a word about it.

In the case of a device lost error it's not really a problem, because we're basically in panic mode. But what about out of memory errors?

It is important to specify this, because if it is possible that only some of the batches are executed and not all, then from the point of view of the vulkan user/game engine it is not possible to know whether the semaphores that are supposed to be waited and signaled by the elements of the batches were effectively waited or signaled.

**Comment by krOoze** [comment]
The "2.6.3. Return Codes" chapter seems to be insufficient in a general case too.

It only seems to cover get-like commands (those without side-effect) and the OOM errors:

> If a command returns a run time error, it will leave any result pointers unmodified, unless other behavior is explicitly defined in the specification.
> 
> Out of memory errors do not damage any currently existing Vulkan objects. Objects that have already been successfully created **can** still be used by the application.

And in the OOM error description it is ambiguous to me what "not damage" means (means "does not modify objects", or just "keeps objects valid"?).

Would be simpler and clearer to say that "unless otherwisely specified a _failed_ command has no effect".

<hr/>

For your particular case I found a relevant quote (possibly in unfortunate place and bit unfortunately worded) in "4.3.5. Queue Submission" chapter:

> All work described by a queue submission command **must** be submitted to the queue before the command returns.

So apart from the silent assuption that failed command does nothing, this seems to emphasize that it is all or nothing submitted situation.

**Comment by tomaka** [comment]
> For your particular case I found a relevant quote (possibly in unfortunate place and bit unfortunately worded) in "4.3.5. Queue Submission" chapter:

>    All work described by a queue submission command must be submitted to the queue before the command returns.

> So apart from the silent assuption that failed command does nothing, this seems to emphasize that it is all or nothing submitted situation.

The sentence says that the function must always submit everything, but obviously if the function returns an error then not all work has been submitted, otherwise there would be no point in returning an error. In other words I don't think this sentence is relevant.

In my opinion either they overlooked this situation, or they thought about it but didn't think it was worth mentioning.

**Comment by slippah** [comment]
Thanks for pointing this out. Agreed, behavior in this case is underspecified.  Guaranteeing all-or-nothing behavior is probably not an option, because a successful batch submit may consume resources and cause another batch to fail.  We'll have to poll IHVs and find out what they can commit to.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.44 spec update.
