### ISSUE TITLE
[Specification] "Performant" does not describe any physical value in which performance could be measured

### ISSUE THREAD

**Issue by zukas** [KhronosGroup/Vulkan-Docs#425]
Please use "well performing" or "adequate performance" instead of performant as it is not a word and means nothing.

**Comment by oddhack** [comment]
Reasonable people can differ about this. The term appears in nearly 30,000 English-language publications according to Google Scholar, many of them computer science-oriented. I believe there's enough established domain-specific usage that its meaning is well understood in the field, even if the definition hasn't made it into the OED.

**Comment by krOoze** [comment]
It respects the new word creation rules quite nicely:
defiance -> defiant
performance -> performant

Why this word makes people to have adequate level of annoyance?

**Comment by zukas** [comment]
Good day, I am sorry for being not very clear in regards to the reason why the word "performant" should not be used. 
Performance is the attribute of the software system which must describe "the rate of execution" of that system. Such attribute may be measured in cycles per millisecond or number of task per second and etc.
Performance attribute must also have a comparative baseline which is used to measure the variability of such attribute. 
Now, the word "performant" does not carry a value of nether the "rate of execution" nor the "improvement from the baseline" and therefore has no meaning and no descriptive power. Therefore, the use of such term in order to describe abstract relative value "not worse then other graphics systems and not better - we don't actually know", which is how "performant" is used in the specification, not only does not give any valid information, but actively mislead the reader.

I do apologize again for such misunderstanding.

**Comment by krOoze** [comment]
It is used three times in the spec and each time the sentence states the baseline.

**Comment by oddhack** [comment]
I'll ask if people feel like changing to some other terminology.

**Comment by zukas** [comment]
Thank you

**Comment by oddhack** [comment]
We discussed this in the Vulkan WG. We believe the current use of "performant" is clear and don't plan to change it.
