### ISSUE TITLE
Valid usage clarification for Vk*PipelineCreateInfo

### ISSUE THREAD

**Issue by mikes-lunarg** [KhronosGroup/Vulkan-Docs#426]
The following is applicable to both VkGraphicsPipelineCreateInfo and VkComputePipelineCreateInfo:

Valid Usage items 1 and 3:

- If flags contains the VK_PIPELINE_CREATE_DERIVATIVE_BIT flag, and basePipelineIndex is not -1, basePipelineHandle must be VK_NULL_HANDLE
- If flags contains the VK_PIPELINE_CREATE_DERIVATIVE_BIT flag, and basePipelineHandle is not VK_NULL_HANDLE, basePipelineIndex must be -1

attempt to enforce the following language from Section 9.5 Pipeline Derivatives:

> A derivative pipeline is created by setting the VK_PIPELINE_CREATE_DERIVATIVE_BIT flag in the Vk*PipelineCreateInfo structure. If this is set, then exactly one of basePipelineHandle or basePipelineIndex members of the structure must have a valid handle/index, and indicates the parent pipeline.

This valid usage wording is redundant for the case where basePipelineIndex != -1 && basePipelineHandle != VK_NULL_HANDLE and doesn't cover the invalid usage case where basePipelineIndex == -1 && basePipelineHandle == VK_NULL_HANDLE.  One way to fix this would be to reword the first valid usage statement as follows:

- If flags contains the VK_PIPELINE_CREATE_DERIVATIVE_BIT flag, and basePipelineHandle is VK_NULL_HANDLE, basePipelineIndex must not be -1

**Comment by oddhack** [comment]
Should be fixed in the 1.0.40 spec update.
