### ISSUE TITLE
Missing valid usage for vkCreate*Pipelines

### ISSUE THREAD

**Issue by mikes-lunarg** [KhronosGroup/Vulkan-Docs#427]
Both vkCreateGraphicsPipelines and vkCreateComputePipelines APIs are missing valid usage statements for the following emphasized text of Section 9.5 Pipeline Derivatives:

> A derivative pipeline is created by setting the VK_PIPELINE_CREATE_DERIVATIVE_BIT flag in the Vk*PipelineCreateInfo structure. If this is set, then exactly one of basePipelineHandle or basePipelineIndex members of the structure must have a valid handle/index, and indicates the parent pipeline.
>...
>**The base pipeline must have been created with the VK_PIPELINE_CREATE_ALLOW_DERIVATIVES_BIT flag set.**

Suggested wording of the new valid usage statement could be as follows:

If the flags member of any given element of pCreateInfos contains the VK_PIPELINE_CREATE_DERIVATIVE_BIT flag, the base pipeline of that element must have been created with the VK_PIPELINE_CREATE_ALLOW_DERIVATIVES_BIT flag set

**Comment by oddhack** [comment]
This should be fixed in the 1.0.39 spec update.
