### ISSUE TITLE
Why do push_constant blocks require an instance name?

### ISSUE THREAD

**Issue by casseveritt** [KhronosGroup/Vulkan-Docs#428]
This issue is copied from https://github.com/KhronosGroup/glslang/issues/665

--
GL_KHR_vulkan_glsl states

"A block declared with layout(push_constant) must have an /instance-name/ supplied, or a compile-time error results."

However, there is no reason given as to why an instance name is required. Regular uniform buffers do not require an instance name.

Because push constant blocks do require an instance name, it is more work to convert an OpenGL shader to a Vulkan shader. You can't just place your OpenGL uniforms in a Vulkan push contant block. You now also have to go through your shader code and pre-append the push constant instance name to each usage of the original OpenGL uniform.

If there is a solid reason for requiring an instance name, then it should be documented in GL_KHR_vulkan_glsl. If there is no good reason, then it's just an annoyance.

**Comment by johnkslang** [comment]
Khronos has decided to allow the relaxation of having a push-constant instance name being optional.  Will appear in a near-future release of the specification.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.43 spec update.
