### ISSUE TITLE
Pipeline Layout Compatibility

### ISSUE THREAD

**Issue by Silverdaru** [KhronosGroup/Vulkan-Docs#431]
The specification says:
> Two pipeline layouts are defined to be “compatible for set N” if they were created with matching (the same, or identically defined) descriptor set layouts for sets zero through N, and if they were created with identical push constant ranges.

My scenario: I have two objects representing the camera and another object in the scene. The camera defines a pipeline layout containing one uniform buffer and a push constant range of 64 bytes with offset 0, assuming that objects may set their model matrices as push constants. The uniform buffer gets filled with view and projection matrices. 
The idea is, that the camera only defines the pipeline layout and a descriptor set and binds them. Afterwards scene objects are called to render themselves. They have their own pipeline, pipeline layout and descriptor sets. 
According to the quoted paragraph above I would assume that my scene object will have to define a pipeline layout with 2 sets (1 containing the uniform buffer, another one for its own ressources) and an identical push constant range (64 bytes, offset 0), so that the sets defined by the camera object may be used by the scene object without having to rebind them.

However, testing this out in my project showed that apparently the push constant ranges do not need to be identical, as my scene object defined the range to be 16 bytes with offset 0 (validation layers do not report anything). Is this a quirk of my implementation or is the specification a bit too restrictive when stating that ranges have to be identical (or is my understanding of "identical" flawed)?

I performed additional tests, which all imply that push constant ranges are not factored into set compatibility at all:
1. The scene object defines its push constant range as 16 bytes with offset 64 (assuming that a push constant range may be considered to be compatible as long as it fits into the previously bound). Result: works just fine.
2. The camera object does not define a push constant range in its pipeline layout at all. Result: works just fine.

**Comment by Novum** [comment]
The validation layer will complain about it and the implementation is free to do anything with invalid usage of the API including crashing the system and drawing pink elephants on the screen.

**Comment by Silverdaru** [comment]
What actually prompted me to open the issue is the fact that the LUNARG_core_validation layer does not report anything about this. The whole project compiles and runs without any validation messages (except for the info messages when binding descriptor sets). I am using the LunarG SDK 1.0.39.

That made me think that maybe the quoted paragraph from the spec may be wrong, i.e. that PushConstantRanges are not part of the pipeline layout compatibility regarding DescriptorSets. Maybe I should have considered an error inside the validation layers first.

**Comment by Novum** [comment]
You should probably file a bug against the validation layer then :)

**Comment by oddhack** [comment]
Closing - please refile against the LunarG validation layer repo.

**Comment by Silverdaru** [comment]
So here is the related LunarG issue:
[https://vulkan.lunarg.com/issue/view/588c4e776631512b4c4b1f50](url)
Originally I wantet to post this link after the issue is closed there but as it seems to take a bit longer, here you go.
