### ISSUE TITLE
VkFrameBufferCreateInfo is missing lower bounds requirement

### ISSUE THREAD

**Issue by gfxguymatt** [KhronosGroup/Vulkan-Docs#432]
This issue is related to the validation issue that was opened in  [#1230](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1230). 

In the valid usage section for VkFramebufferCreateInfo the only restrictions for width, height and layers are:

>  * pname:width must: be less than or equal to
    sname:VkPhysicalDeviceLimits::pname:maxFramebufferWidth
>  * pname:height must: be less than or equal to
    sname:VkPhysicalDeviceLimits::pname:maxFramebufferHeight
>  * pname:layers must: be less than or equal to
    sname:VkPhysicalDeviceLimits::pname:maxFramebufferLayers

However if a value of 0 is set for any of these parameters it will cause VK_ERROR_DEVICE_LOST to be returned after submitting the command buffer for some drivers (in my case I am using a GeForce GTX 980). Reviewing both VkImageCreateInfo and VkImageViewCreateInfo the corresponding values for these parameters have the added restriction that these values are greater than or equal to 1.

Is there any reason why this restriction should not be applied to VkFramebufferCreateInfo?

**Comment by oddhack** [comment]
I'll take a look at this for a future update.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.41 spec update.
