### ISSUE TITLE
Question for users of the Vulkan-Docs repo: is an XML-specific subtree repo useful?

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Docs#434]
There have been a couple of requests from users of vk.xml to the effect that downloading all the rest of the spec is excessive when all they need is the XML and (maybe) accompanying scripts.

We're not enthusiastic about splitting the XML into a separately managed repository because it is really tightly intertwined with the spec and contains a good deal of spec language. However, apparently we could use a contrib addon called 'git subtree' to extract the relevant portion of the Vulkan-Docs repo into a separate repo, and it would probably be straightforward to build that into the release process so such a 'Vulkan-XML' repo remains in sync.

Soliciting feedback on whether this would be useful, and if so, what in addition to vk.xml you would want to see in such a repo. My inclination if we do this would be to extract the entire src/spec directory.

**Comment by ratchetfreak** [comment]
I see 3 ways of using the data in the repo

1. just get the most current headers

2. get the xml for processing with tools

3. get everything 

So you may also include the headers in the xml subrepo

**Comment by oddhack** [comment]
@ratchetfreak Which of those ways would be useful to you? If we do this the intent is to address problems people are confronting.

**Comment by NicolBolas** [comment]
This would be helpful for my needs; the only reason I pull from this repo is to get the .xml and .rnc files. That being said, I imagine that some people care just as much about the build files for the .xml as they do for the XML file itself. So if you're going to split something out, it should be the `src` directory as a whole, not just `src/spec`.

That being said, I just took stock of the `src` directory; it is ~1MB (and about half of that is `vk.xml` by itself). The other two directories combined are ~8MB. However "excessive" some people might find it, it certainly isn't taking up all that much space in an objective sense.

**Comment by oddhack** [comment]
@NicolBolas personally agreed the additional files are insignificant, but the complaints/requests were out there previously, so trying to measure interest before closing the issue.

**Comment by oddhack** [comment]
Closing for lack of compelling demand. I'm told someone posted something on twitter complaining about submodules which might be related to this, but if so they should comment here.
