### ISSUE TITLE
vkCreateDescriptorPool fails if VkDebugReportCallbackExt with information flag bit set is attached

### ISSUE THREAD

**Issue by discosultan** [KhronosGroup/Vulkan-Docs#437]
I'm having an issue where the command `vkCreateDescriptorPool` fails with **error code -1000011001** (`VK_ERROR_VALIDATION_FAILED_EXT`) **only if** I've created a `VkDebugReportCallbackExt` on the `VkInstance` with `VK_DEBUG_REPORT_INFORMATION_BIT_EXT` set.

There are no errors/warnings raised by the LunarG standard validation layers. I'm running on 1.0.39 runtime libraries. I'm also accessing the API through custom bindings, meaning that there is chance that a bug is there instead.

**Comment by krOoze** [comment]
`VK_ERROR_VALIDATION_FAILED_EXT` is a fake error, that is returned if you return `VK_TRUE` from your debug callback.

**Comment by discosultan** [comment]
Moved the issue over to the layers repo.

https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1420
