### ISSUE TITLE
Surface–Swapchain association restriction not consistent

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#438]
This restriction:

> The native window referred to by `surface` must not already be associated with a swapchain other than `oldSwapchain`, or with a non-Vulkan graphics API surface.

seems too restrictive to me.

I think it should also be allowed that the surface can also be associated with the oldSwapchain of the oldSwapchain, and also with the oldSwapchain of the oldSwapchain of the oldSwapchain and so on.

(BTW, should perhaps be "nor" for clarity in the sentence)

Also:

> A native window cannot be associated with more than one swapchain at a time. Further, swapchains cannot be created for native windows that have a non-Vulkan graphics API surface associated with them.

That is in contradiction with the above. Apparently **can** be associated with two swapchains too.
Also this statement says "cannot", while the first quote says "must not" about the same thing, so which is it?

**Comment by ratchetfreak** [comment]
maybe add something like "or its ancestors" to oldSwapchain

> The native window referred to by surface must not already be associated with a swapchain other than oldSwapchain or its ancestors, or with a non-Vulkan graphics API surface.

**Comment by krOoze** [comment]
"Ancestor" specifically is dangerous, because #345 , but yeah something like that.

**Comment by ratchetfreak** [comment]
predecessor/successor may be clearer

**Comment by cubanismo** [comment]
I'll pick this up as part of #345.  Seems like this language needs some cleanup in general.  The intention is indeed "... or its predecessors" is included whenever restrictions like this are present, but I agree the language doesn't always clearly reflect that intent.
