### ISSUE TITLE
Question: some pNext members not const void*

### ISSUE THREAD

**Issue by cmaaser** [KhronosGroup/Vulkan-Docs#439]
1.0.39 introduced several new structures some of which have a `pNext` member of type `void*` instead of type `const void*`. Those structures are `VkPhysicalDeviceFeatures2KHR`, `VkPhysicalDeviceProperties2KHR`, `VkFormatProperties2KHR`, `VkImageFormatProperties2KHR`, `VkQueueFamilyProperties2KHR`, `VkPhysicalDeviceMemoryProperties2KHR`, and `VkSparseImageFormatProperties2KHR`.
Is this intentional - and if so, why?

**Comment by chrisforbes** [comment]
This is intentional. The callee is expected to write to the chained structures.

**Comment by cmaaser** [comment]
This makes sense, thanks. I noticed this as it breaks stuff in my custom vk.xml -> c++ generator and it first looked like a bug.
