### ISSUE TITLE
VK_FORMAT_END_RANGE (enums) and extension formats (e.g. PVRTC)

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Docs#440]
Right now the ending range enum for formats (VK_FORMAT_END_RANGE) contains the value of the last core format (VK_FORMAT_ASTC_12x12_SRGB_BLOCK) and does not account for formats added by extensions like the VK_FORMAT_PVRTC2*.

So while you can easily iterate over core formats, that's not possible for formats added via extensions. 

While I don't think it's a good idea to just put the last format added by any extension in VK_FORMAT_END_RANGE, I think it would be nice to have format range begin and end enums for every format block added by an extension.

So e.g. the VK_IMG_format_pvrtc would add three new enums:

	VK_FORMAT_PVRTC_BEGIN_RANGE = VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG
	VK_FORMAT_PVRTC_END_RANGE = VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG```
	VK_FORMAT_PVRTC_RANGE_SIZE = (VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG - VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG + 1)

If every extension that adds new formats could implement such enums, an application could easily iterate over image formats added by extensions.

**Comment by TobiasHector** [comment]
Hmm, that makes sense, and would be relatively trivial to add to the header generator. @oddhack  do you want to take a look at this or should I? I probably won't get to it for a few weeks unfortunately (post-GDC).

**Comment by oddhack** [comment]
If you want to iterate over all possible formats, then you would need an enumeration of all extensions which extend VkFormat. Where does the list of extension_BEGIN/END_RANGE come from?

Might a useful alternative be to provide a C code fragment along with the header which just creates an array containing all the formats, and specifies its length, or an iterator function to return them all? This feels like utility library functionality to me - the original motivation for BEGIN/END_RANGE was just to support driver internals.

**Comment by SaschaWillems** [comment]
Yes, I don't think this is a must for the header. I just noticed this while working on my Vulkan Hardware Caps Viewer adding support for the PVRTC formats. I'm iterating over the BEGIN...END range for the formats and currently the PVRTC formats are left out because of this and so I thought this might be an addition to the headers that others would find useful too. If not I'm perfectly fine adding ranges into my own code instead.

**Comment by oddhack** [comment]
I'm happy to work in background on aforementioned code fragment if you like. I'm not sanguine about the begin/end idea though. I just realized that there's not even a requirement or expectation that an extension make all of the VkFormat enums it adds numerically compact, so it's unclear what begin..end would mean - maybe only two of the values in a larger block would actually be formats.

**Comment by TobiasHector** [comment]
@oddhack Yes and actually, Alon and I spotted yesterday that in fact extensions are definitely doing the "wrong" thing with enum numbering. Not wrong that it would affect anything at the moment, but if we added ranges, it might. A lot of extensions (inlcuding KHR!) have just got increasing "offset" values for all enums they add - regardless of what enum type they are. e.g.:

```
<enum offset="0"         extends="VkStructureType"      name="VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR"/>
<enum offset="1"         extends="VkStructureType"      name="VK_STRUCTURE_TYPE_PRESENT_INFO_KHR"/>
<enum offset="2"         extends="VkImageLayout"        name="VK_IMAGE_LAYOUT_PRESENT_SRC_KHR"/>
<enum offset="3"         extends="VkResult"             name="VK_SUBOPTIMAL_KHR"/>
<enum offset="4" dir="-" extends="VkResult"             name="VK_ERROR_OUT_OF_DATE_KHR"/>
```

We might want to be more vigilant about this in future, but it's mostly harmless. The proposed ranges would work with all existing extensions at least.

**Comment by oddhack** [comment]
I guess we could put something in the style guide about grouping additions by the enumerated type they extend. Not clear it would really make any difference to implementations, they'll presumably just have a big case statement relying on the compiler to be clever since this stuff shouldn't be on a fast path.

**Comment by oddhack** [comment]
Tagging this Future, to autogenerate a piece of sample code enumerating all the formats. In one sense it's almost trivial, but only if returning every possible VkFormat enum in vk.xml. If some filtering is desired, say according to what extensions are supported on a device at runtime, suddenly it starts looking much more complicated. I'd rather not do something half-assed that wouldn't *solve* the issue so this needs to get explored.

**Comment by TobiasHector** [comment]
CC @mtavenrath - just in case this is something you might want to look at?

**Comment by mtavenrath** [comment]
I agree with @oddhack that enumerating enums belongs into a utility library. If we'd generate a static array for each enum with all known values we should add the string representation too for debug layers. Another utility for this library would be a vulkan object factory which can create *CreateInfo objects with user-defined parameters specified in some (XML) file.

@TobiasHector Is something like vulkan-utils something we should reside under the KhronosGroup umbrella?

**Comment by oddhack** [comment]
@mtavenrath I think in general - there are exceptions - Khronos' experience in maintaining utility code layers hasn't been very successful. It is rarely a core priority for the group so they tend to stagnate once the original proponent moves on to other roles. Maybe now that we're on github more direct engagement with outside developers would change that.

**Comment by TobiasHector** [comment]
@mtavenrath I wasn't sure if something like this should belong in the ext loader or vulkan-hpp maybe, but separate project would also be fine. I think having it under the Khronos umbrella does make sense for the same reasons Jon mentions.

**Comment by mtavenrath** [comment]
Something like this for sure doesn't belong to the ext-loader and I'm also not fully concinved to have it in Vulkan-Hpp, especially since this feature should be available for pure C code too.

**Comment by oddhack** [comment]
@SaschaWillems I am inclined to close this. As we discussed above, this sort of utility code just isn't a priority for Khronos; and while the action needed is straightforward (some code to extract enums extending VkFormat from vk.xml, grouped by the extension(s) that contain them), it requires time nobody has stepped up to put in. It's well within the scope of outside developers to do this, and if someone does it we would probably be happy to put either the code, or a pointer to the code into this repo or the Vulkan registry, respectively. What do you think?

**Comment by SaschaWillems** [comment]
Sure, I'm fine with that :)
