### ISSUE TITLE
vkGetQueryPoolResults queryCount not correctly defined?

### ISSUE THREAD

**Issue by ioquatix** [KhronosGroup/Vulkan-Docs#441]
According to the docs:

    firstQuery is the initial query index.
    queryCount is the number of queries. firstQuery and queryCount together define a range of queries.

However, I found that when I set up a query pool of size 2, tracking two pipeline query flags:

```c++
	// Create query pool
	VkQueryPoolCreateInfo queryPoolInfo = {};
	queryPoolInfo.sType = VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO;
	queryPoolInfo.queryType = VK_QUERY_TYPE_PIPELINE_STATISTICS;
	queryPoolInfo.pipelineStatistics = 
		VK_QUERY_PIPELINE_STATISTIC_VERTEX_SHADER_INVOCATIONS_BIT | 
		VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_EVALUATION_SHADER_INVOCATIONS_BIT;
	queryPoolInfo.queryCount = 2;
```

Calling vkGetQueryPoolResults with queryCount = 2 is not correct, even though according to the documentation it should be necessary to get both results. 

```c++
	uint64_t pipelineStats[2] = { 0 };


	vkGetQueryPoolResults(
		device,
		queryPool,
		0,
		2,
		sizeof(pipelineStats),
		pipelineStats,
		sizeof(uint64_t),
		VK_QUERY_RESULT_64_BIT);
```

What I found DOES work, is setting queryCount = 1. I don't know why this works and it's not explained anywhere in the documentation why this might work.

**Comment by ioquatix** [comment]
Okay, so I'm an idiot - queryCount doesn't relate to the number of individual query flags, it relates to the number of times you want to be able to discretely call BeginQuery... perhaps this needs to be clarified somehow. An example might be a good start. Perhaps a diagram showing how the information is stored and retrieved and an explicit axis for both flags, and queryCount.

**Comment by NicolBolas** [comment]
> queryCount doesn't relate to the number of individual query flags, it relates to the number of times you want to be able to discretely call BeginQuery

That's not quite it. Each query index in the pool contains _all_ of the pipeline statistics listed in the flags. And thus, the get operations, for an index, will write one value for each flag.

This is spelled out in Query Operation:

>  Occlusion queries write one integer value - the number of samples passed. Pipeline statistics queries write one integer value for each bit that is enabled in the `pipelineStatistics` when the pool is created, and the statistics values are written in bit order starting from the least significant bit. Timestamps write one integer value.

Admittedly, it's an easy section to miss.

**Comment by ioquatix** [comment]
I don't see how what you've quoted explains that "Each query index in the pool contains all of the pipeline statistics listed in the flags"

**Comment by NicolBolas** [comment]
> ***Pipeline statistics queries write one integer value for each bit that is enabled in the `pipelineStatistics` when the pool is created***

I don't know how that could possibly be clearer.

**Comment by ioquatix** [comment]
> *Pipeline statistics queries* write *one integer value* for each bit that is enabled in the pipelineStatistics when the pool is created"

It's not clear that you don't need queryCount = number of bits enabled.

Add "Each query index in the pool contains all of the pipeline statistics listed in the flags."

**Comment by ioquatix** [comment]
Also, just FYI, it wasn't just me who found this documentation unclear, another experienced C++ developer who originally wrote this code for a client within my business, couldn't get it working for lack of better documentation/examples. I finally figured it out after reviewing the SashaWilliams examples, the documentation, after reading it several times, didn't end up helping. It's definitely unclear and could do with some psudo-code example.

**Comment by oddhack** [comment]
We'll take a look at adding @ioquatix 's suggested sentence to the spec. People can reasonably disagree on how clear the language has to be and if this is accurate and helpful for some developers, we're OK with putting it in - just need to review in more detail.

**Comment by ioquatix** [comment]
Awesome. If it helps, I could try submitting a PR?

**Comment by oddhack** [comment]
We are, unfortunately, *still* not at the point of having a CLA which allows us to actually accept external PRs against the document. Hopefully sometime soon. But I can go off the discussion in this thread.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.44 spec update.

**Comment by ioquatix** [comment]
I'm on holiday on my phone do you mind pointing me to the updated documentation? Thanks :)

**Comment by oddhack** [comment]
The current spec is in khronos.org/registry/vulkan/ as always.

**Comment by ioquatix** [comment]
Abbott yep I mean the exact commit that fixed this issue :) when you make the commit you can annotate it like fixes #number and GitHub will link it automatically

**Comment by ratchetfreak** [comment]
All fixes in an update get squashed into a single public commit, it's always the latest public commit after an update: https://github.com/KhronosGroup/Vulkan-Docs/commit/43f1fd5550cac5547cf3421ad0783f46a6e64aa2

The sha1 of the public commit is at the top of the spec.

**Comment by ioquatix** [comment]
Oh cool, yeah it was a bit hard to find, but now I'm on my laptop, the change looks good.
