### ISSUE TITLE
VK_EXT_display_surface_counter asciidoc ifdef broken

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#443]
In the spec+extensions `VK_EXT_display_surface_counter` `#ifdef` and `#endif` is broken (is visible in the generated text).

It therefore also breaks spec+WSI, where the text in between should not appear at all.

**Comment by oddhack** [comment]
This should be fixed in the upcoming spec update - I'll close this once it goes out.
