### ISSUE TITLE
Question: When does VkPipelineTessellationStateCreateInfo Valid Usage apply?

### ISSUE THREAD

**Issue by mikes-lunarg** [KhronosGroup/Vulkan-Docs#445]
VkPipelineTessellationStateCreateInfo contains the following valid usage:

> * patchControlPoints must be greater than zero and less than or equal to VkPhysicalDeviceLimits::maxTessellationPatchSize

Recent updates to the validation layers have raised questions about whether or not this statement should apply to VkGraphicsPipelineCreateInfo.pTessellationState when using VkGraphicsPipelineCreateInfo.pInputAssumblyState.topology values other than VK_PRIMITIVE_TOPOLOGY_PATCH_LIST
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1411
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1425

One interpretation is that the pTessellationState parameter will be ignored in this case and the contents can be anything (ie default values of 0).  If this is the case, I would expect some text that states when the above valid usage statement is applicable.

Another interpretation is that pTessellationState should always be NULL when not using tessellation shaders.  The spec provides some text to indicate this, but no valid usage:
> * pTessellationState is a pointer to an instance of the VkPipelineTessellationStateCreateInfo structure, or NULL if the pipeline does not include a tessellation control shader stage and tessellation evaluation shader stage.

Any thoughts on which interpretation is correct, and how the spec can make this more obvious?

**Comment by NicolBolas** [comment]
I don't see any validation rules which prevent you from having a `pTessellationState` without tessellation shaders. I see this in the Valid Usage section for `VkGraphicsPipelineCreateInfo`:

> * If `pStages` includes a tessellation control shader stage and a tessellation evaluation shader stage,
`pTessellationState` must not be `NULL`.

It seems to me that there should also be the reverse:

> * If `pTessellationState` is not `NULL`, `pStages` must include a tessellation control shader stage and a tessellation evaluation shader stage.

This would fit with the two rules above it, requiring a TCS if there is a TES and vice-versa.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.47 spec update.
