### ISSUE TITLE
What is the lifetime of strings passed to debug report callback?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#446]
What is the lifetime of `pLayerPrefix` and `pMessage` strings passed to `PFN_vkDebugReportCallbackEXT` user callback function?

Are they:
- static?
- destroyed with `VkDebugReportCallbackEXT`?
- do I become the owner responsible for destruction?

(After quick searching in the spec: same Q about `VkDisplayPropertiesKHR::displayName`)

**Comment by ratchetfreak** [comment]
The strings passed into the `vkDebugReportCallbackEXT` are [alive for the _duration of the call_.](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/vk_layer_logging.h#L342).

As for `VkDisplayPropertiesKHR::displayName` I expect it to be the _lifetime of vkInstance_.

It could do with documenting though.

**Comment by courtney-g** [comment]
Will add "TBD is only valid for the duration of the callback." to pLayerPrefix and pMessage.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.41 spec update.
