### ISSUE TITLE
[Extension][Editing] VK_EXT_debug_report lists wrong "New Object Types"

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#447]
"New Object Types" in the `VK_EXT_debug_report` chapter lists `VkDebugReportCallbackCreateInfoEXT`, which is not a Vulkan Object.

It should list `VkDebugReportCallbackEXT` there instead.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.40 spec update.
