### ISSUE TITLE
Terminology chapter errors

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#448]
1) There is missing "," between "shall" and "should" [fixed in 1.0.42]
2) "Shall" is missing in the extended descriptions
3) There is "recommend" instead of "recommended"

**Comment by oddhack** [comment]
We don't use 'shall' any more. Will fix soon.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.44 spec update.
