### ISSUE TITLE
Extension Loader Redefinitions with Different Type Modifiers

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/Vulkan-Docs#449]
I'm trying to integrate the simple extension loader [vulkan_ext.c](src/docs/vulkan_ext.c) into one of my projects but my compiler (VS2015) is complaining about function redefinitions with different type modifiers:

`...\vulkan_ext.c(54): error C2373: 'vkDebugReportMessageEXT': redefinition; different type modifiers
3>  C:\VulkanSDK\1.0.39.1\Include\vulkan/vulkan.h(4009): note: see declaration of 'vkDebugReportMessageEXT'`

This is because the Vulkan headers include VKAPI_ATTR and VKAPI_CALL in their definitions:

`VKAPI_ATTR void VKAPI_CALL vkDebugReportMessageEXT( ...`

and the extension loader does not:

`void vkDebugReportMessageEXT( ...`

Adding VKAPI_ATTR and VKAPI_CALL (manually) fixed the problem for me so I'm not blocked for now, but I wanted to open this issue while I figure out how to correctly auto-generate the extension loader with them.

(Is this just a simple matter of including `apicall` and `apientry` in the genOpts for vulkan_ext.c?)

**Comment by oddhack** [comment]
> (Is this just a simple matter of including apicall and apientry in the genOpts for vulkan_ext.c?)

Probably - give it a try!

**Comment by oddhack** [comment]
@mtavenrath could you review and sign off this change, since the extension loader is your creation?

**Comment by timofonic** [comment]
@bashbaug @oddhack @mtavenrath @krOoze Any news?

**Comment by oddhack** [comment]
We no longer support ext_loader.
