### ISSUE TITLE
Implicit location assignment in blocks

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#45]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#interfaces-iointerfaces-locations says:

> If it is a Block with a Location decoration, then its first member is assigned to the location specified for the Block, any member with its own Location decoration is assigned that location, and otherwise each subsequent member is assigned consecutive locations in declaration order.

This seems ambiguous.

If the first member has its own Location decoration (which might differ from the block's Location), which rule applies?

Also, what specifically does "consecutive" mean? E.g. if I have something in pseudo-GLSL like:

    layout(location = 0) in blk {
      vec4 a;
      layout(location = 4) vec4 b;
      vec4 c;
    };

and pretend that it gets compiled to:

             Decorate 8(blk) Block
             Decorate 8(blk) Location 0
             MemberDecorate 8(blk) 1 Location 4
	8(blk):  TypeStruct 7(fvec4) 7(fvec4) 7(fvec4)

then would the third member be given location 1 (the next in the sequence of implicitly-assigned locations after the first member was given 0), or location 5 (the next after the previous member's location), or location 42 (it just needs to be consecutive with all other members that aren't first and don't have an explicit Location, and since it's the only such member that means it can be any arbitrary location)?

**Comment by dgkoch** [comment]
c should be assigned location 5. I'll propose a spec change to clarify this.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.6 spec update.
