### ISSUE TITLE
Massive jump in the size of `vkspec.pdf`

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#453]
The PDF for the Vulkan specification jumped in the 1.0.40 version from ~3.5MB to ~34MB, a 10-fold increase.

The page count does not seem to be radically different, but the text size seems to have changed, and possibly the font itself. If the standard PDF fonts were used before, but now you're using one or more embedded fonts, that could explain the file size difference.

**Comment by oddhack** [comment]
Asciidoctor uses a complete different PDF generation toolchain. Perhaps @TobiasHector knows more about how much control we get over the form of the output.

**Comment by TobiasHector** [comment]
There's an "optimize-pdf" script (http://asciidoctor.org/docs/convert-asciidoc-to-pdf/#optional-scripts) which should be installed with asciidoctor-pdf which reduces the size back down to sane levels. For some reason it doesn't seem to have installed in my system though, which is confusing. On an "all extensions" build it gets the size down to ~7MB, which is still bigger but not astronomically so. I'll investigate.

**Comment by TobiasHector** [comment]
Ah see https://github.com/asciidoctor/asciidoctor-pdf/issues/670 and https://github.com/asciidoctor/asciidoctor-pdf/issues/535.

So we'll just have to pull the optimize-pdf script manually, which isn't a big deal - unless one of us feels like fixing https://github.com/asciidoctor/asciidoctor-pdf/issues/535.

**Comment by oddhack** [comment]
Can you just check it into the Vulkan tree under config/ (for lack of a better place)? If it's just a Bash script we're good. I don't have much sympathy for the weird ideology that everything must be rewritten to target Ruby / Javascript / JVM bytecodes / Elisp / FORTRAN IV / other lockin environment-of-the-day. Computers are general-purpose.

**Comment by TobiasHector** [comment]
Am already on it. The reason for porting to Ruby within the asciidoctor project is reasonable but not relevant to us right now, so this is the simplest solution.

**Comment by oddhack** [comment]
@TobiasHector setup the optimize-pdf script (which is really just a Ghostscript wrapper as it turns out) and it will go into future spec updates.
