### ISSUE TITLE
Most links broken in public Vulkan webpage

### ISSUE THREAD

**Issue by Jasper-Bekkers** [KhronosGroup/Vulkan-Docs#454]
Example:

https://www.khronos.org/registry/vulkan/specs/1.0/man/html/vkCmdCopyBuffer.html

This page has a few links, for example one to VkBufferCopy that all point to the wrong place. They point to an anchor on the same page instead of a link to the actual page. The link in question points to https://www.khronos.org/registry/vulkan/specs/1.0/man/html/vkCmdCopyBuffer.html#VkBufferCopy instead of https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkBufferCopy.html

(Most/All) other pages have the same problem (in their See Also section for example). This makes navigating the web-manual next to impossible.

- Jasper

**Comment by TobiasHector** [comment]
We discovered this internally - a fix has already been pushed for review and should be available in the next weekly release. Apologies!

**Comment by TobiasHector** [comment]
NB: As a workaround for now, suggest you use the single-page man pages: https://www.khronos.org/registry/vulkan/specs/1.0/apispec.html

**Comment by Jasper-Bekkers** [comment]
Thanks for the quick reply! Some links in the single-page man page also don't seem to work. For example there is a link to https://www.khronos.org/registry/vulkan/specs/1.0/apispec.html#synchronization that doesn't lead anywhere.

**Comment by krOoze** [comment]
Also pretty much all Vulkan Object (like `VkSurfaceKHR`) links lead nowhere.

**Comment by TobiasHector** [comment]
> Some links in the single-page man page also don't seem to work. For example there is a link to https://www.khronos.org/registry/vulkan/specs/1.0/apispec.html#synchronization that doesn't lead anywhere.

@Jasper-Bekkers That needs to link back to the main spec, and the links are just generic anchors, so I will have to do something more sophisticated to fix that... I do have some ideas though. I'll see if I can figure out a simple fix; in the meantime could you raise a separate issue for this one?

> Also pretty much all Vulkan Object (like VkSurfaceKHR) links lead nowhere.

@krOoze Hm, I assumed we were generating html pages for those, but apparently not. This is going to require more effort to fix - do you think you could raise a separate issue for this too?

**Comment by krOoze** [comment]
@TobiasHector You do, but the links refer to an in-page anchor.
(BTW the same links do not work in the spec itself)

**Comment by TobiasHector** [comment]
> @TobiasHector You do, but the links refer to an in-page anchor instead.
(BTW the same links do not work in the spec itself)

Oh you're right - I was looking at an unextended build. Derp. They should work in the manpages with the fix I've already put in then.

**Comment by Jasper-Bekkers** [comment]
> @Jasper-Bekkers That needs to link back to the main spec, and the links are just generic anchors, so I will have to do something more sophisticated to fix that... I do have some ideas though. I'll see if I can figure out a simple fix; in the meantime could you raise a separate issue for this one?

Filed as #455

**Comment by krOoze** [comment]
@TobiasHector Right sorry, that makes it the same issue as the OP.
So I am only filing separate issue for the spec document (#456).

**Comment by oddhack** [comment]
@TobiasHector I had noticed this a while back and figured I could just edit the regular links on the fly during the genRef.py extraction process if anyone else noticed, but nobody noticed until now :-)

**Comment by oddhack** [comment]
Regarding the VkSurfaceKHR thing, yeah, the links go nowhere because there's actually nothing in the spec describing the handle type. Initially I thought this might be more widespread, but we put in spec boilerplate for (at least most of) the handle types when the ref pages started getting generated, so it may just be a one-off. Probably best to fix by adding a definition of the type somewhere in the WSI text; unfortunately it's not immediately obvious where that is because there's no 'vkCreateSurfaceKHR' to attach it to, just a bunch of WS-specific create commands.

**Comment by oddhack** [comment]
The general cross-page link problem is fixed in the 1.0.41 spec update.
