### ISSUE TITLE
Cygwin build missing dependency

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#457]
For Cygwin target it also seems to want `libiconv-devel` for me (which is not listed in the README) during one of the gem installs.

<s>(And BTW the top-most README seem to be out of date now)</s>

**Comment by jjulianoatnv** [comment]
Thanks for the report. I'll add it to the dependency list.

**Comment by jjulianoatnv** [comment]
The merge request that I submitted to add this package to the list of cygwin dependencies was met with the following feedback:

> You don't need this library if you use the alternative command for installing mathematical as documented in the Cygwin section, rather than using the one documented in the ruby section.

I have not at this time tried to verify the claim. However someone else has reorganized the readme to make it more clear what steps should be performed when installing cygwin packages.

I'm going to leave this issue open until I or someone else has confirmed that the libiconv-devel package really is not necessary, and that the modified readme is sufficiently clear.

**Comment by jjulianoatnv** [comment]
BTW, I found instructions for automating the list of packages when installing cygwin:

https://cygwin.com/ml/cygwin/2011-09/msg00097.html

**Comment by krOoze** [comment]
> I'm going to leave this issue open until I or someone else has confirmed that the libiconv-devel package really is not necessary, and that the modified readme is sufficiently clear.

On it!

**Comment by krOoze** [comment]
@jjulianoatnv Still doesn't work for me.

Repro:
1) Install Cygwin64 with default options + listed dependencies from the readme
2) Run `MATHEMATICAL_USE_SYSTEM_LASEM=1 gem install asciidoctor-mathematical`

Symptoms:
```
gcc -shared -o mathematical.so cairo_callbacks.o lasem_overrides.o mathematical.o
-L/home/Petr/.gem/ruby/gems/mathematical-1.6.7/ext/mathematical/lib 
-L.  -L/usr/lib -L. -fstack-protector
-lgdk_pixbuf-2.0 -lm -lgmodule-2.0 -lpng16 -lm -lz -lcairo -lz -lGL -lpixman-1
-lfontconfig -lexpat -lfreetype -lexpat -lfreetype -lbz2 -lz -lEGL -lm -lpthread
-lGL -lm -lpthread -lXdamage -lXfixes -lX11-xcb -lxcb-glx -lpng16 -lm -lz
-lxcb-shm -lxcb-render -lXrender -lXext -lX11 -lxcb -lXau -lXdmcp -lpango-1.0
-lm -lgobject-2.0 -lffi -lglib-2.0 -lintl -lpcre -lintl -liconv -lpcre
-Wl,--export-all-symbols -Wl,--enable-auto-image-base,--enable-auto-import    
-lruby220 -lpangocairo-1.0 -lxml2  -lpthread -lgmp -ldl -lcrypt   -lmtex2MML -llasem
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -liconv
collect2: error: ld returned 1 exit status
make: *** [Makefile:256: mathematical.so] Error 1

make failed, exit code 2
```

**Comment by oddhack** [comment]
@jjulianoatnv I don't see any harm in listing libiconv as required. It's nothing special in terms of installation AFAIK, just another word to paste in. I've found it challenging to identify sufficiently-pristine installations (of whatever OS/environment) to be *sure* I haven't already got something installed someone else might need.

**Comment by jjulianoatnv** [comment]
@krOoze, thanks for testing. Next step is for me to resolve a merge conflict in my MR and get merged.

**Comment by TobiasHector** [comment]
> `/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -liconv`

@krOoze Just to check, isn't that just saying you're missing libiconv, rather than libiconv-devel? Have you checked that libiconv is installed? I've currently -1'd the internal MR for this because it worked for me with the non devel version. Only just realised there was a public MR for this. If you could verify one way or another it'll sway me.

**Comment by krOoze** [comment]
@TobiasHector 
Yes, I have `libiconv` installed. Manually checking there's no such (or similar) lib to link against. Then installing `-devel` makes the error go away.

Unix-likes and I are not best of friends, but I assumed it is the whole point of all the `-devel` packages. If you include and link, you need `-devel` and if you only need runtime you can use non`-devel`.

**Comment by jjulianoatnv** [comment]
I RTM the cygwin documentation and learned something new. Here you go:

> $ cygcheck --list-package libiconv | grep "libiconv\.a"
> [Exit 1 ]
> 
> $ cygcheck --list-package libiconv-devel | grep "libiconv\.a"
> /usr/lib/libiconv.a

Bottom line: the -devel package is needed.

**Comment by krOoze** [comment]
Fixed in the 1.0.42 spec update.

**Comment by jjulianoatnv** [comment]
@krOoze , thanks for verifying and closing the issue.

**Comment by krOoze** [comment]
@jjulianoatnv Actually I still have problem with `make pdf`... I will make a new Issue after bit of re-testing.
