### ISSUE TITLE
`supported` in XML is sometimes incorrectly disabled.

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#461]
In `vk.xml`, the `extension` element has a `supported` attribute. This can be either a specific profile that is supported (like "vulkan") or "disabled".

But some of them have a spelling error:

>     <extension name="VK_KHR_extension_72" number="72" author="KHR" contact="James Jones @cubanismo" supported="disable">

Note that `supported` is "disable", not "disable<B>d</B>". This happens in several places, likely due to a simple copy&paste error.

**Comment by oddhack** [comment]
This is corrected in the upcoming spec release. But it's not actually a problem. Any text other than "vulkan" will not match while processing the scripts.
