### ISSUE TITLE
Separate the docs and API changelog

### ISSUE THREAD

**Issue by LiamDawe** [KhronosGroup/Vulkan-Docs#463]
The changelog is getting really long and it seems the actual API changes in the changelog are getting pushed further and further down this big file.

Can we please get them separated for much easier reading?

**Comment by oddhack** [comment]
We could add new entries at the top instead of the bottom, if that would be helpful. Though I'm not eager to manually reverse the order of the previous 40-odd entries.

**Comment by oddhack** [comment]
I've reversed the ChangeLog order in the 1.0.44 spec update.
