### ISSUE TITLE
PDF: Lots of broken validation box formatting.

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#465]
The valid usage box for `vkCmdDrawIndirect` is only shaded for the first page. The next page has the bulleted list unshaded, but they should still be part of the valid usage. This is also true for `vkCmdDrawIndexedIndirect`'s Valid Usage box.

The specifications for `vkCmdDrawIndirectCountAMD` and `vkCmdDrawIndexedIndirectCountAMD` are shaded like they are in Valid Usage boxes, but they're not. And no other extension function specifications use that shading.

These are all in the PDF that contains the full set of Vulkan extensions.

**Comment by TobiasHector** [comment]
This is part of an ongoing issue with (read: missing feature of) asciidoctor-pdf. I *thought* I had a fix (there's a monkeypatch in the spec repo), but apparently it doesn't work as well as it should, for no obvious reason. Debugging is going slowly, and stalled whilst I was at GDC. It'll probably be a couple of weeks before I have a robust fix, though I do have some ideas.

Thanks for spotting this, it's at least something I can look at to help with the debugging :)

**Comment by oddhack** [comment]
This should be fixed in the 1.0.46 spec update. It requires updating to the latest asciidoctor-pdf --pre gem.
