### ISSUE TITLE
"Invalid" clashes with the new CmdBuff states

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#467]
In `vkDestroyCommandPool()` descriptions there is:

> When a pool is destroyed, all command buffers allocated from the pool are implicitly freed and **become invalid**.

That dangerously imitates how the new "invalid" state is worded, e.g.:

> Any primary command buffer allocated from another VkCommandPool that is in the recording or executable state and has a secondary command buffer allocated from commandPool recorded into it, **becomes invalid**.

It should instead explicitly say the cmdbuffer **handle** becomes invalid. (Or in this case it seems the "and become invalid" is completely unnecessary, and "are freed" should suffice.)

**Comment by TobiasHector** [comment]
Going with your second option ("...are freed.") Thanks :)

**Comment by TobiasHector** [comment]
I'm also linking to the vkFreeCommandBuffers command and deleting the completely unnecessary second sentence in that paragraph, whilst I'm there...

**Comment by oddhack** [comment]
Should be fixed in the 1.0.44 spec update.
