### ISSUE TITLE
Contradictory info of commandBuffer in vkResetCommandBuffer

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#468]
In the descriptions of `commandBuffer` for `vkResetCommandBuffer` it is said:

> The command buffer **can** be in any state, and is put in the initial state.

Yet in Valid Usage there is a contradictory restriction:

> `commandBuffer` **must not** be in the pending state

**Comment by TobiasHector** [comment]
Good catch, thanks.

**Comment by krOoze** [comment]
BTW using "can" there may be tricky. Based on the terminology definitions it looks like it should be "may".
I.e. the API will indeed accept command buffer in any state (=="can"), but it might result in undefined behavior.

**Comment by TobiasHector** [comment]
> BTW using "can" there may be tricky. Based on the terminology definitions it looks like it should be "may".
I.e. the API will indeed accept command buffer in any state (=="can"), but it might result in undefined behavior.

Can is *meant* to mean "this is a thing you can **do**". Whereas may is "this is a thing that may **happen**". I.e. one is cause, the other is effect. Not sure on how clear the definitions are around this, but that's how we're using it. If you think that's not clear from the current definitions, please raise an issue.

In this particular case, the application is responsible for the state of the command buffer, and **can** move it to other states. The state of the command buffer before calling the command is not the result of the command itself.

**Comment by krOoze** [comment]
@TobiasHector 
> If you think that's not clear from the current definitions, please raise an issue.

Indeed I treated it differently. I derive it from the 1.3. Terminology definition of "cannot", which basically reads "you are not physically able to cram it to the API" or the note puts it nicely: "literally unable to express or accomplish". And treating the "can" as the opposite (which probably isn't based on the definition).

**Comment by oddhack** [comment]
Should be fixed in the 1.0.44 spec update.
