### ISSUE TITLE
Contradictory info of recording state for vkBeginCommandBuffer

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#470]
In `vkBeginCommandBuffer` descriptions there is:

> If a command buffer is in the _invalid_, _recording_ or _executable_ state [... rest not really important here]

But in VU there is:

> `commandBuffer` **must not** be in the _recording_ or _pending_ state.

Contrary to that the first statement gives the idea that _recording_ state is also allowed.

**Comment by TobiasHector** [comment]
Ah right - this is because allowing it to be in the recording state fell out naturally from the edits, and then someone pointed out this was a functionality change. Apparently I forgot to fix up the language, I only caught the VU.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.44 spec update.
