### ISSUE TITLE
Missing invalid state on VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#471]
`VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT` description:

> `VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT `controls whether command buffers allocated from the pool **can** be individually reset. If this flag is set, individual command buffers allocated from the pool **can** be reset either explicitly, by calling `vkResetCommandBuffer`, or implicitly, by calling `vkBeginCommandBuffer` on an _executable_ command buffer. If this flag is not set, then `vkResetCommandBuffer` and `vkBeginCommandBuffer` (on an _executable_ command buffer) **must not** be called on the command buffers allocated from the pool, and they **can** only be reset in bulk by calling `vkResetCommandPool`.

It singles out only _executable_ state. But I think it should also apply to all cmdbuffer states usable based on the VU in `vkBeginCommandBuffer` and `vkResetCommandBuffer`.

I.e. initial, recording, executable and invalid can be used for `vkResetCommandBuffer` (i.e. the command must not be used without the flag at all).   
Executable and invalid for the `vkBeginCommandBuffer`.

(Should probably avoid complex descriptions here and leave the details to the VUs. E.g. could be:
> `VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT` allows any command buffer allocated from this pool to be individually reset back to the initial state via using the `vkResetCommandBuffer` command, or via using the implicit reset of the`vkBeginCommandBuffer` command. If this flag is not set `vkResetCommandBuffer` command or the implicit reset must not be used on any command buffer allocated from this pool.

[i.e. removed references to the states and replaced with the set of allowed operations instead -> replaced `vkBeginCommandBuffer` with "implicit reset of"]
)

**Comment by TobiasHector** [comment]
I'm currently going with roughly with your suggestion, and have written this:

>   * ename:VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT allows any
     command buffer allocated from a pool to be individually reset to the
     \<\<commandbuffers-lifecycle, initial state\>\> by calling
     flink:vkResetCommandBuffer.
     Command buffers allocated from such a pool are also implicitly reset
     when calling flink:vkBeginCommandBuffer.
     If this flag is not set on a pool, then fname:vkResetCommandBuffer
     must: not be called for any command buffer allocated from that pool.

**Comment by krOoze** [comment]
@TobiasHector I don't like it. It mentions `vkResetCommandBuffer` explicitly:

>  "by calling flink:vkResetCommandBuffer"

 and

> then fname:vkResetCommandBuffer must: not be called

, but mentions the implicit reset only.... implicitly as a subtle hint to the reader.

Besides "are also implicitly reset" is inaccurate (cmdbuffer in initial state **is not** reset).

**Comment by TobiasHector** [comment]
The thing I was trying to capture is that it doesn't *allow* the reset to happen when you call begin, it toggles whether it even does anything, or not. If you don't have this bit, it doesn't do the reset.

However actually looking now at the language hole I've dug myself - whether it always resets or is just not allowed to reset is actually moot - both result in invalid things happening if you try to begin a command buffer without the reset bit in anything other than initial state. Soo.. yea ok I'll go change that if you think it's clearer the other way.

**Comment by TobiasHector** [comment]
So now it's:

>   * ename:VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT allows any
     command buffer allocated from a pool to be individually reset to the
     \<\<commandbuffers-lifecycle, initial state\>\>; either by calling
     flink:vkResetCommandBuffer, or via the implicit reset when calling
     flink:vkBeginCommandBuffer.
     If this flag is not set on a pool, then fname:vkResetCommandBuffer
     must: not be called for any command buffer allocated from that pool.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.44 spec update.
