### ISSUE TITLE
Contradictory and redundant VU of VkSubmitInfo

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#472]
`VkSubmitInfo` VU;

> Any given element of `pCommandBuffers` **must** be in the _executable_ state

is contradictory and redundant to the `vkQueueSubmit` VU:

> - Any given element of the `pCommandBuffers` member of any element of `pSubmits` **must** be in the _pending_ or _executable_ state.
> 
> - If any given element of the `pCommandBuffers` member of any element of `pSubmits` was not recorded with the `VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT`, it **must not** be in the _pending_ state.

**Comment by TobiasHector** [comment]
Ack apparently I missed one when I moved it. Simple enough to fix... the vkQueueSubmit VU is the correct one.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.44 spec update.
