### ISSUE TITLE
VkImageCreateInfo not clickable in vkCreateImage man page

### ISSUE THREAD

**Issue by Plagman** [KhronosGroup/Vulkan-Docs#474]
https://www.khronos.org/registry/vulkan/specs/1.0/man/html/vkCreateImage.html

Mention of VkImageCreateInfo should be a hyperlink to this page:

https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkImageCreateInfo.html

**Comment by oddhack** [comment]
It's linked from the See Also section below. There are hundreds of places in the spec where structure and function names are not generated as crosslinks, and we might change that eventually in a global sense, but not in specific cases now.
