### ISSUE TITLE
Confusion of terminologies residencyNonResidentStrict and sparseResidencyNonResidentStrict in sparsemem.txt

### ISSUE THREAD

**Issue by lanphon** [KhronosGroup/Vulkan-Docs#475]
In the sparsemem.txt part of doc/specs/vulkan/chapters, I found following reference to the terminology of *sparseResidencyNonResidentStrict* at line 541/550

> Not faulting on access to unbound pages is not enough to support
pname:sparseResidencyNonResidentStrict.
An implementation must: also guarantee that reads after writes to unbound
regions of the resource always return data for the read as if the memory
contains zeros.
Depending on the cache implementation of the hardware this may: not always
be possible.
> 
> Hardware that does not fault, but does not guarantee correct read values
will not require dummy pages, but also must: not support
pname:sparseResidencyNonResidentStrict.

But in fact, this terminology only appears here. Besides, there is another similar name *residencyNonResidentStrict*, I wonder if they are the same thing. Please help to check and confirm that.

Thanks a lot

**Comment by oddhack** [comment]
Yes, they are the same thing - thanks for catching this! This should be fixed in the 1.0.45 spec update.
