### ISSUE TITLE
Legal to have fragment shader without color-output in subpass with a color attachment?

### ISSUE THREAD

**Issue by schwa423** [KhronosGroup/Vulkan-Docs#477]
In https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1597, I describe what I thought was an error in the validation layer, but now believe is probably a valid error report: I think that my program relies on driver behavior that is undefined by the spec, as of 1.0.43.

The question is whether this is an oversight by the spec, which needs to be corrected.

My original use-case in that bug report involved a depth-only prepass.  However, I think that a more fruitful scenario for discussing this issue is a 2D renderer that wishes to implement clipping by interleaving "update clip region" operations (which test and write to the stencil attachment) with "draw shape" operations (which test the stencil attachment, and write to the color attachment).  

For performance reasons, we wish to do so within a single subpass, and don't want the "update clip region" operation to touch the color attachment (e.g. no blending of fully-transparent fragments into the framebuffer).  

A natural way to do the latter is to use a ```void main() {}``` fragment shader for the "update clip region" operation.  But, is this legal, defined behavior?

(and if not, is there some other way to express this intention in Vulkan?)

**Comment by critsec** [comment]
You should mask off the color writes using VkPipelineColorBlendAttachmentState::colorWriteMask. Fragment shaders always emit values for all color attachments; if you don't explicitly write something, then the shader output values are undefined.

**Comment by critsec** [comment]
Actually, you can just omit the fragment shader from the pipeline altogether; you still need the color write mask though. From section 9.2.1:

> If a fragment shader is omitted, the results of fragment processing are undefined. Specifically, any fragment color outputs are considered to have undefined values, and the fragment depth is considered to be unmodified. This can be useful for depth-only rendering.

**Comment by schwa423** [comment]
OK, thanks.  It seems like the necessary use cases are supported.

It also seems that there is room to improve the clarity of the spec.  I found what you wrote above to be very illuminating:

> Fragment shaders always emit values for all color attachments; if you don't explicitly write something, then the shader output values are undefined.

... perhaps this could be added to section 8.9 ?

**Comment by critsec** [comment]
I've created an internal issue to figure out how to make it easier to find the relevant shader interface info (in chapter 14) from the shader stage descriptions (chapter 8). Maybe links, or maybe a larger rearrangement. For what it's worth, there's a better description of this in section 14.3 "Fragment Output Interface".
