### ISSUE TITLE
[Extension][Question] How *exactly* debug flags work?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#478]
1) What is the exact purpose of `VK_DEBUG_REPORT_DEBUG_BIT_EXT`?
In the spec there is only written:

> `VK_DEBUG_REPORT_DEBUG_BIT_EXT` indicates diagnostic information from the loader and layers.

which pretty much describes most of the messages.

I consider this flag part of a hierarchy (of seriousness): error > warning > perf. warning > info > debug. 
Is this correct interpretation?

2) The callback and `vkDebugReportMessageEXT` seems to accept any combination of the flags, but they seem quite mutually exclusive. Is allowing this intentional?

If so how is it supposed to be used? What purpose e.g. `ERROR | WARNING` message serve?

Also how does the filter work in that case? E.g. if I specify `ERROR` in `VkDebugReportCallbackCreateInfoEXT::flags` will the callback be called for `ERROR | WARNING` message, or not?

3) There is no guarantee the flags will be non-zero for the callback.
Is this also intentional to allow by the spec?

**Comment by courtney-g** [comment]
The DEBUG_BIT is not intended for valid usage checks. It's intended as a way to share "interesting" information with the application. I don't see it used in the validation layers at this time, but the desktop loader does generate DEBUG_BIT reports with information about what it's doing, e.g. search path it's using to look for manifest files, ICDs, etc. This can be useful when checking loader behavior.

Similarly, VK_DEBUG_REPORT_INFORMATION_BIT_EXT is used by the validation layers and loader to remark on specific actions such as memory tracking info or what ICD(s) are being loaded.

The flags are independent. It's expected that most folks are only interested in ERROR and WARNING and, maybe, PERF_WARNING. Callbacks will only be generated if the bitwise AND of the mask and the callback flag is non-zero. E.g.  if you only indicate VK_DEBUG_REPORT_WARNING_BIT_EXT you will only see notifications that have that bit set.

**Comment by krOoze** [comment]
> The DEBUG_BIT is not intended for valid usage checks. It's intended as a way to share "interesting" information with the application.

So my assumption is correct that it is like `INFORMATION_BIT` (except perhaps less important or something)? Or is it meant to be only (non-error) info about internal workings of the loader and layers?

I still feel the spec description could be clearer. Currently if taken literaly it describes any kind of notification including `ERROR` ones (they are diagnostic, and they do come from the layers, don't they).

> Callbacks will only be generated if the bitwise AND of the mask and the callback flag is non-zero.

So, it would call in my example(mask=`ERROR`, msg=`ERROR | WARNING`), because at least one of the notification bits is in the mask provided during callback creation.

The spec says:

> A callback will be made for issues that match any bit set in its flags. 

Somehow I am unable to parse this sentence and verify if it is the same as what you just told me. Could it use wording update?

<hr/>

Still this question remains: What is the semantics of e.g. `ERROR | WARNING` (or other combination of several bits) received by the callback? Should it be allowed by the spec?

**Comment by krOoze** [comment]
> What would help you?

Dunno, what you said here (with bitwise and) seems beter.
I was not joking -- I literally have problem reading it despite it being deceptively short -- it just looks like word salad to me. I e.g. cannot tell what the "its" there references. And what is supposed to match what. Should also probably use (previously used) "events", instead of "issues".

> Setting flags to ERROR | WARNING will generate notifications for any notification that has ERROR or WARNING set. Notification could even set both, though validation layers do not do that.

No, I meant if I actually receive it in my debug function;  I am **not** currently speaking about the mask.
I.e. if I actually receive a notification that has `ERROR | WARNING` set. What would that message even mean? The descriptions of `ERROR` and `WARNING` seem mutually exclusive, so it feels that receiving their combination should not be allowed by the spec.

> Yeah, doing an equality check for a specific value isn't robust. Should use bitwise AND to test. Validation layers only set one bit so things work.

True, actually because of the dont-care values in the unused bits.
Still the cube demo uses bitwise-and in a `else if`, which is technically also wrong then, because the spec allows seting more than one of the bits and the demo would report only one of them in the log.

> Creating a callback with no bits set in the flag isn't very useful, but I don't think it needs to be invalid. I can imagine that an application could create a callback based on flags provided at runtime. Would prefer not having to protect the call when no flags are set. Just let the call go through.

No, creating callback with 0 flags is actually invalid by VU. So is injecting messages by the app (by `vkDebugReportMessageEXT`).
What I mean is that the app can still receive 0 flag (i.e. the callback function gets called with flags set to 0).
Then again if what you say about the mask is true, then it would be filtered out, because 0 flags bitwise-and would never be non-zero. So, I guess that aspect is actually covered sneakily.

**Comment by courtney-g** [comment]
FYI - updated commits to, hopefully, address comments.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.50 spec update.
