### ISSUE TITLE
Vulkan ext loader: vkCreateAndroidSurfaceKHR = nullptr?

### ISSUE THREAD

**Issue by TheMasterMaind** [KhronosGroup/Vulkan-Docs#479]
Hello,

I am trying to use the ext_loader from this repo.

I statically link with libvulkan.so and without the ext_loader everything works fine!

But when I use the loader, my app crashes. Logcat says its because vkCreateAndroidSurfaceKHR is 0x0.

I tried to use both vkExtInit* methods as well as seperated.

It also seems this issue occurs on desktop systems too!

Tested with an Nvidia 940m on Ubuntu 16.04 my app also crashes, but this time on vkGetPhysicalDeviceSurfaceSupportKHR being 0x0.

Is there anything wrong with the ext_loader or may I be wrong using it?

**Comment by MarkY-LunarG** [comment]
One of the issues I see is that you're attempting to use `vkCreateAndroidSurfaceKHR` on Linux.  Each platform's Windows System Integration (WSI) extensions are only made available on that platform.  For example, Windows has `vkCreateWin32SurfaceKHR` available, but not any of the Linux or Android commands.  If you desire to use the Android entrypoints, you would need to use the Android SDK which exposes the Android loader.

I've added Markus who can comment on expected behavior of the extension loader library itself, but the Desktop Vulkan loader directgly exposes platform WSI functions like `vkGetPhysicalDeviceSurfaceSupportKHR`.  However, it will not be valid unless you enable the appropriate extensions during `vkCreateInstance`.  You can look at LunarG's cube example (in the SDK) or many other examples in the Khronos repository that show you how to enable the VK_KHR_surface and appropriate platform extensions before use.

**Comment by TheMasterMaind** [comment]
I guess I did not express my Issue correctly. So I am sorry for the inconvinience.

I tried the ext_loader on actually 3 Platforms. Android, Linux, Windows.

With a statically linked vulkan lib everything work as expected on all three platforms. However when using the ext_loader I got some problems:

The steps to reproduce (single device and instance)
Create an instance
call vkExtInitInstance
create logical device 
call vlExtInitDevice

On Android vkCreateAndroidSurfaceKHR and vkGetPhysicalDeviceSurfaceCapabilitiesKHR are both nullptr (I guess there are more function invalid but i didnt tested this)

On Linux: vkCreateXcbSurfaceKHR and vkGetPhysicalDeviceSurfaceSupportKHR are both nullptr

On Windows: Only vkGetPhysicalDeviceSurfaceSupportKHR is nullptr.

On Android I can get it to work if I omit the vkExtInitDevice call and fix the code of the ext_loader (see below). On desktop Platforms however nothing works.

So I investigated the source of the ext_loader and found something interesting:

#ifdef VK_KHR_android_surface
#ifndef VK_KHR_android_surface
    pfn_vkCreateAndroidSurfaceKHR = (PFN_vkCreateAndroidSurfaceKHR)vkGetInstanceProcAddr(instance, "vkCreateAndroidSurfaceKHR");
#endif /* VK_USE_PLATFORM_ANDROID_KHR */
#endif /* VK_KHR_android_surface */

which looks weird to me. So i changed it to this

#ifdef VK_KHR_android_surface
#ifdef VK_USE_PLATFORM_ANDROID_KHR
    pfn_vkCreateAndroidSurfaceKHR = (PFN_vkCreateAndroidSurfaceKHR)vkGetInstanceProcAddr(instance, "vkCreateAndroidSurfaceKHR");
#endif /* VK_USE_PLATFORM_ANDROID_KHR */
#endif /* VK_KHR_android_surface */

And I was able to get it to work on Android. I changed all occurences of this mighty error (and for all other functions too)
But it is still errouneus on desktop platforms.


I know how the WSI works as my code works on all 3 Platforms without the ext_loader.
All I did was to drop in the ext_loader into my code. And start wondering :)

I also may to be too dumb to use it ^^

**Comment by TheMasterMaind** [comment]
Of course I dont use vkCreateAndroidSurfaceKHR on other platforms than Android and vice versa. I also enable all extensions correctly (for debug report, surface, swapchain etc.).

**Comment by yvt** [comment]
`vkExtInitDevice`  [attempts to use `vkGetDeviceProcAddr`](https://github.com/KhronosGroup/Vulkan-Docs/blob/712755f6883af760b325bc795c23050cac3255b6/src/ext_loader/vulkan_ext.c#L1929) to retrieve function pointers of instance extension commands (e.g., `vkGetPhysicalDeviceSurfaceSupportKHR`) even though [a paragraph from the specification implies](https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/doc/specs/vulkan/chapters/initialization.txt#L106) that `vkGetDeviceProcAddr` cannot be used for this purpose. 

> *Table 2. vkGetDeviceProcAddr behavior*
> ...
>    The returned function pointer **must** only be called with a dispatchable object (the first parameter) that is `device` or a child of `device`. e.g. `VkDevice`, `VkQueue`, or `VkCommandBuffer`.

`VkInstance` is not a child of `VkDevice`.

Maybe that's the cause of this problem?

**Comment by oddhack** [comment]
We no longer support ext_loader.
