### ISSUE TITLE
Advanced categorisation of API functions

### ISSUE THREAD

**Issue by elfring** [KhronosGroup/Vulkan-Docs#48]
The application programming interface provides [some functions which can be categorised](https://en.wikipedia.org/wiki/Ontology_%28information_science%29 "Usage of ontologies") like the following.

1. [Initialisation](https://en.wikipedia.org/wiki/Initialization_%28programming%29#C_family_of_languages "Initialisation functions")
2. [Finalisation](https://en.wikipedia.org/wiki/Finalization#Use "Finalisation functions")
3. [Querying properties](https://en.wikipedia.org/wiki/Property_%28programming%29 "Accessor functions")
4. [Setting attributes](https://en.wikipedia.org/wiki/Mutator_method#C_example "Setter methods")
5. [Utilities](https://en.wikipedia.org/wiki/Utility_software "Description for utility software")

Which functions should usually be combined for the [proper construction and destruction of the involved data structures](https://en.wikipedia.org/wiki/Destructor_%28computer_programming%29#In_C_with_GCC_extensions "Object construction and destruction")?

**Comment by NicolBolas** [comment]
The Vulkan specification is quite clear on this. Any function of the form `vkCreate*` constructs an object. Any function of the form `vlAllocate*` allocates memory from an object. And so forth. The API is quite regular in this regard, and you can easily make a tool to parse `vk.xml` and mate up constructors/allocators of objects with their destructors/deallocators.

Also, we are all programmers here. We do not need to be linked to Wikipedia to know what the word "initialize" means.

**Comment by oddhack** [comment]
The specification is, hopefully, clear about how an app can create, use, and destroy objects. If it's not clear in some specific case, please point out the specific language that needs increased clarity. But our goals with Vulkan do not include creating an idealized computer science class architecture.

**Comment by elfring** [comment]
@NicolBolas: I am trying to express my ideas with help of this issue tracker in a way so that other contributors (besides programmers) can better understand the involved details.
Do you suggest to filter "commands" of this application programming interface by English key words?

@oddhack: I guess that my computer science understanding will result in further useful software improvements.
* Does [the XML schema](https://github.com/KhronosGroup/Vulkan-Docs/blob/d204ac2f6991f75fab2ebc22136fd179d692f84f/src/spec/registry.rnc#L246 "Specification for command properties") contain the possibility to identify a function as an initialiser or finaliser explicitly by a corresponding property?
* Would you like to express in a structured way which functions should usually be combined for construction and destruction of the involved data structures?

**Comment by ratchetfreak** [comment]
Frankly all structs are treated as Plain Old Data either as input or output issue #10 will help clarify that. 

The handles are created by the vkCreate* or vkAllocate* functions and destroyed by the vkDestroy* and vkFree* functions.

Those rules are enough to know what things need to be cleaned up when.

**Comment by elfring** [comment]
I find the dependency on special function name patterns insufficient for the safe combination of API functions which should belong to a well-known category.

**Comment by NicolBolas** [comment]
@elfring 
> I am trying to express my ideas with help of this issue tracker in a way so that other contributors (besides programmers) can better understand the involved details.

I'm not sure what contributions non-programmers can make to a tool intended for programmers. Even the hardware vendors who work on the specification have programming experience.

> Would you like to express in a structured way which functions should usually be combined for construction and destruction of the involved data structures?

To what end? However "insufficient" you find "name patters", they do in fact _work_. The Vulkan devs should spend time on features that are genuinely broken, not things that work but might be made a bit more convenient.

**Comment by elfring** [comment]
How do you think about to reduce the error probability around this application programming interface by extending the information which is provided by the [Relax NG schema](https://github.com/KhronosGroup/Vulkan-Docs/blob/d204ac2f6991f75fab2ebc22136fd179d692f84f/src/spec/registry.rnc#L246 "Further clarfication for API properties")?
Which specification file will contain an explicit listing for the combination of constructors and destructors in a data format so that it can be used for automatic software generation?
