### ISSUE TITLE
Inconsistent pNext allowed structures

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#481]
VU(I) for `VkPresentInfoKHR` says:

> Each `pNext` member of any structure (including this one) in the `pNext` chain **must** be either `NULL` or a pointer to a valid instance of `VkDisplayPresentInfoKHR`, `VkPresentRegionsKHR`, `VkDeviceGroupPresentInfoKHX`, or `VkPresentTimesInfoGOOGLE`

but VU(I) for `VkPresentRegionsKHR`:

> Each `pNext` member of any structure (including this one) in the `pNext` chain **must** be either `NULL` or a pointer to a valid instance of `VkPresentRegionsKHR`, `VkDeviceGroupPresentInfoKHX`, or `VkPresentTimesInfoGOOGLE`

Considering they are both of the same potential pNext-chain, why is `VkDisplayPresentInfoKHR` missing in the second one?

**Comment by ianelliottus** [comment]
Thanks for reporting this.  A fix is on its way.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.47 spec update. Note that pNext VU are handled differently now, and only generated for the base structure in this pNext chain, not for each such structure.
