### ISSUE TITLE
[Specification] Ambiguities in vkCreateInstance description

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#483]
I find this paragraph about `vkCreateInstance` ambiguous:

> `vkCreateInstance` creates the instance, then enables and initializes global layers and extensions requested by the application. If an extension is provided by a layer, both the layer and extension **must** be specified at `vkCreateInstance` time. If a specified layer cannot be found, no `VkInstance` will be created and the function will return `VK_ERROR_LAYER_NOT_PRESENT`. Likewise, if a specified extension cannot be found the call will return `VK_ERROR_EXTENSION_NOT_PRESENT`.

1) Does the sentence about layer provided extension means:
a) If I want the extension I also have to enable the layer (unless the extension is also provided by the Implementation).
or
b) If I want the layer I also have to enable the extension.
or
c) (Read literaly but probably non-sense:) Any layer that provides any extension has to be enabled.

2) The first sentence should probably use the established "instance" instead of "global".

3) It feels there should not be "must" about the layer provided extensions, but such case should also return either `VK_ERROR_LAYER_NOT_PRESENT` or `VK_ERROR_EXTENSION_NOT_PRESENT`. Because layers (and their provided extensions) may change at runtime, so the Application would be unable to guarantee that requirement (and so avoid the undefined behavior).

4) It feels like the creation order should be opposite; i.e. "first initializes layers and extensions and then creates instance". Because I would want the `pNext` extension of `VkInstanceCreateInfo` to also potentially affect the instance creation itself (as it does in reality with e.g. `debug_report` extension or layers validating the input from the command start).

**Comment by courtney-g** [comment]
#3 is interesting. The app needs to specify the extension and the associated layer for things to work so I think the must: is justified. This seems in conflict to other places where valid use allows for the implementation to return an error. In this case, for things to work the application does need to specify both the instance layer and the extension. If either is not found, the application will get a well defined error.
But if an extension is solely implemented by a layer and the app leaves off one, they will not get what they want.

**Comment by krOoze** [comment]
> This seems in conflict to other places where valid use allows for the implementation to return an error.

Since some spec version there should be no more cases where VU disallows something that is also handled be an error `VkResult`.

It is not a VU statement (though almost certainly it should be if it requires anything of the Application).

But the underlying problem is the same. RFC "**must**" is "an absolute requirement". Consequences of breaking such requirement should be largely unspecified(\undefined).

**Comment by courtney-g** [comment]
You are correct, the condition is not invalid, so maybe okay to leave out the must:
Just want to emphasize / clarify that application must specify both the layer and the extension. Maybe that's obvious to folks. Or rare enough it doesn't need extra emphasis.

**Comment by krOoze** [comment]
> Just want to emphasize / clarify that application must specify both the layer and the extension. Maybe that's obvious to folks. Or rare enough it doesn't need extra emphasis.

It can't hurt anything of course.
It could be a Note, if it is redundant information.
The problem is with this chosen wording, and not with the nice intention to emphasize some specific case.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.50 spec update.
