### ISSUE TITLE
[Registry][Extension] VkInstanceCreateInfo missing validextensionstructs

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#486]
`VkInstanceCreateInfo` is missing `validextensionstructs` in `vk.xml`.
There should be at least `VkDebugReportCallbackCreateInfoEXT` in there that I know of.

`VkDebugReportCallbackCreateInfoEXT` itself may possibly need some special treatment, because it can be both top-level, or chained structure.

**Comment by TobiasHector** [comment]
This might be an awkward case that needs manual validity, but I'll take a look at it.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.50 spec update.
