### ISSUE TITLE
[Validity] VU vs VK_ERROR_LAYER_NOT_PRESENT

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#487]
`vkEnumerateInstanceExtensionProperties` and `vkEnumerateDeviceExtensionProperties` have `VK_ERROR_LAYER_NOT_PRESENT` specified as a possible Return Code.

But they both have VU saying:
> If `pLayerName` is not `NULL`, it `must` be the name of a layer returned by `vkEnumerateInstanceLayerProperties`

I think this VU should be removed and `VK_ERROR_LAYER_NOT_PRESENT` should handle those cases. (It is the way e.g. the `vkCreateInstance` command went.)

**Comment by oddhack** [comment]
This should be fixed in the 1.0.49 spec update.
