### ISSUE TITLE
[validity] VU vs VK_ERROR_INCOMPATIBLE_DRIVER

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#488]
VU for `VkApplicationInfo::apiVersion` says:

> `apiVersion` **must** be zero, or otherwise it **must** be a version that the implementation supports, or supports an effective substitute for

I think it should be removed because it is in contradiction with `VK_ERROR_INCOMPATIBLE_DRIVER`:

>  [...]if the implementation does not support the requested `apiVersion` it **must** return `VK_ERROR_INCOMPATIBLE_DRIVER`.

Besides the application has no way to know which versions the end-users Vulkan implementation supports. There is no global `vkEnumerateVulkanVersions` (maybe there should be one though).

**Comment by oddhack** [comment]
This should be fixed in the 1.0.49 spec update.
