### ISSUE TITLE
[Extension] Ambiguous "should" about PFN_vkDebugReportCallbackEXT return

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#489]
Spec says about debug callback return :

> The callback returns a `VkBool32` that indicates to the calling layer if the Vulkan call **should** be aborted or not.

Which would imply (per RFC "should") that the return might be ignored, and implementation might choose whether to abort or not.
But it feels the "should" in this sentence is colloquial (and in intention means "is supposed to").

In next paragraph it says:

> If the application returns `VK_TRUE` from its callback and the Vulkan call being aborted returns a `VkResult`, the layer will return `VK_ERROR_VALIDATION_FAILED_EXT`.

Which seem to make a different assumption about it than the above.
It is especially obvious from it not saying what happens if it returns `VK_FALSE` and call is being aborted (which is a possibility based on the first quote).

**Comment by oddhack** [comment]
This should be fixed in the 1.0.50 spec update.
