### ISSUE TITLE
Omit "optional" parameters from some API functions

### ISSUE THREAD

**Issue by elfring** [KhronosGroup/Vulkan-Docs#49]
Some functions are documented for this application programming interface in the way that a pointer can be passed. Some of these pointers can also be also be [null](https://en.wikipedia.org/wiki/Null_pointer#C "Usage of null pointers") as a regular value.

I imagine that null pointers will be passed often enough for [a parameter like "VkAllocationCallbacks"](https://www.khronos.org/registry/vulkan/specs/1.0/apispec.html#vkCreateInstance "Optional allocation callbacks") so that it would make sense to provide functions which omit such an input value in their signature.
Will a reduced API variant be useful for less data transfer traffic in some use cases?

**Comment by NicolBolas** [comment]
Perhaps you could clarify the circumstances where NULL parameters would constitute such a significant amount of "traffic" that their absence would be of benefit?

**Comment by oddhack** [comment]
Regarding possible API ease-of-user, this sounds like an good use case for a Layer - you can put whatever convenience wrappers you want in at that level. Regarding possible driver performance improvements, It seems unlikely that removing one call parameter will significantly affect performance, but if you can demonstrate otherwise that would be interesting data to have and would affect the group's willingness to include such commands in future extensions or API versions.

**Comment by elfring** [comment]
* Can it generally be a bit more efficient to pass data only for function parameters which are really needed and used actually?
* How often will [a custom memory allocator](https://en.wikipedia.org/wiki/Memory_management "Description for memory management approaches") be better than the default service which will be provided by a specific software library implementation?
* Is it possible to add a special test that will measure potential benefits for the suggested API "convenience" layer with less function parameters in your software benchmark infrastructure?
* How can [the API specification](https://github.com/KhronosGroup/Vulkan-Docs/blob/d204ac2f6991f75fab2ebc22136fd179d692f84f/src/spec/vk.xml#L1 "Description for the application programming interface") be automatically queried which functions will tolerate the passing of null pointers for one of their parameters?

**Comment by oddhack** [comment]
vk.xml contains this information already, in the optional= parameter for pointer arguments.

**Comment by elfring** [comment]
How do you think about to generate an API extension automatically in a corresponding software build step by extracting functions where the currently provided standard ones [accept optional parameters](https://github.com/KhronosGroup/Vulkan-Docs/blob/d204ac2f6991f75fab2ebc22136fd179d692f84f/src/spec/registry.rnc#L246 "Omitting optional function parameters?")?

**Comment by NicolBolas** [comment]
As oddhack just said, `vk.xml` contains all of the information needed to deduce if a parameter is optional or not. As such, you can develop such an "API extension" generator already.

As for making it standard, no. The standard generators should generate the functions as specified by the Vulkan standard. That's what makes it *standard*.

**Comment by elfring** [comment]
How often will software developers appreciate to work without optional settings for this application programming interface by default (or as standard)?

**Comment by NicolBolas** [comment]
Then those software developers can make a simple wrapper function. The API specification even gives them enough information to write such wrappers *automatically*.

This is not something that needs to be part of Vulkan itself.

And to be perfectly honest, I imagine that most serious software developers who are writing high-performance applications very much have a need to track/control the implementation's memory allocations. So for the most important users of Vulkan, such parameters are not optional. I suspect the only people for whom these parameters will always be NULL are those who are writing hobby/tutorial applications.

Remember who the primary users of Vulkan are.
