### ISSUE TITLE
[Registry] Missing "_CALLBACK" for debug report object type

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#490]
`VK_DEBUG_REPORT_OBJECT_TYPE_DEBUG_REPORT_EXT`
should be
`VK_DEBUG_REPORT_OBJECT_TYPE_DEBUG_REPORT_CALLBACK_EXT`
to match the object name `VkDebugReportCallbackEXT`

umm, actually
`VK_DEBUG_REPORT_OBJECT_TYPE_DEBUG_REPORT_CALLBACK_EXT_EXT`
right?

**Comment by courtney-g** [comment]
Let's say that since VK_DEBUG_REPORT_OBJECT_TYPE_DEBUG_REPORT_EXT was defined by VK_EXT_debug_report we can leave off the extra EXT. :-)

Yeah, probably should have CALLBACK in there as well.

**Comment by courtney-g** [comment]
@krOoze I'd like your feedback on MR #493

**Comment by oddhack** [comment]
This should be fixed in the 1.0.50 spec update.

**Comment by ParticlePeter** [comment]
`_CALLBACK` was added but `_EXT_EXT` remains in `VK_DEBUG_REPORT_OBJECT_TYPE_DEBUG_REPORT_CALLBACK_EXT_EXT` of v1.0.51. Is this supposed to stay?

**Comment by krOoze** [comment]
@ParticlePeter Heh, heh. Sorry for suggesting that variant.
But it makes sense if you think about it:
The recipe is VK_DEBUG_REPORT_OBJECT_TYPE_{Vulkan type capitalized and underscored incl. extension suffix}_EXT. Ergo twice EXT.

**Comment by ParticlePeter** [comment]
@krOoze, just looks so wired. So fine, it'll probably stay.
