### ISSUE TITLE
[Validity] Bad array size VUs?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#491]
For example lets consider this VU(I) for array in `VkPresentInfoKHR`:

> If `waitSemaphoreCount` is not `0`, and `pWaitSemaphores` is not `NULL`, `pWaitSemaphores` **must** be a pointer to an array of `waitSemaphoreCount` valid `VkSemaphore` handles

It does makes sense for commands that return the array (e.g. `enumeratePhysicalDevices`), which write the `count` in case of `array` is `NULL`, so `count` is write only parameter in that case.

But for purely input array it makes no sense &mdash; it forces the Implementation to do an unnecessary `if( array != NULL )` check instead of relying only on the `count`.
And I am assuming good behavior here (i.e. assuming that `count > 0 && array == NULL` means "empty array" &mdash; which is not written in the spec I think)

Should pehaps disallow case `count > 0 && array == NULL` for input arrays?

For clarity as a table:

| `count`      | `array`            |     | Output array    | Input array                  | Input array <br/> proposed VU |
| -----------|---------------|---| ---------------   | -----------                       | ----------------- |
| 0              | `NULL`                || overwrites `count`    | in empty                           |  same                 |
| 0              | non-`NULL`        ||  out empty array<br/>(ignores `array`)    | in empty<br/>(ignores `array`)  |  same                 |
| N(>0)       | `NULL`                ||  overwrites `count`   | assumably:<br/>in empty<br/>ignores `count` |  Invalid usage     |
| N(>0)       | valid non-`NULL` || outs N elems    | ins N elems                       |  same                 |

**Comment by krOoze** [comment]
I noticed the VU is OK in some cases (e.g. `VkDescriptorSetLayoutCreateInfo` bindings array).
The difference is simply if the array has `optional=true` or not in `vk.xml`. Probably should be removed in cases such as the `VkPresentInfoKHR` above.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.55 spec update.
