### ISSUE TITLE
Format compatibility of vkCmdResolveImage

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-Docs#492]
The spec is a little unclear on what formats are compatible for source and destination images in `vkCmdResolveImage`. `vkCmdCopyImage` has details about how it considers formats compatible, and `vkCmdBlitImage` also details how it converts between formats, but `vkCmdResolveImage` doesn't give any details either way.

Currently the validation layers are requiring that the formats precisely match (ie. even `RGBA8_UNORM` to `RGBA8_SRGB` would be invalid), which I think is stricter than the spec intends. I suspect that the rules are maybe similar to those for `vkCmdCopyImage`, minus the specifics about copying to/from block compressed images. Possibly there are additional restrictions about resolves between floating point and integer images.

**Comment by krOoze** [comment]
> Currently the validation layers are requiring that the formats precisely match

That will probably be correct, because that is what renderpass resolve attachments require too.

**Comment by janharaldfredriksen-arm** [comment]
Yes. The formats have to match. We'll clarify this.

**Comment by oddhack** [comment]
This should be addressed in the 1.0.51 spec update.
