### ISSUE TITLE
String implicit VU not described

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#494]
String VU is not described in the 2.6.2. Implicit Valid Usage chapter.

Nearest thing would be "Valid Usage for Pointers", but I don't think it applies well to the string case.

**Comment by TobiasHector** [comment]
Hi @krOoze what are you looking for here? Are you asking for specific constraints for what a string is? At the moment the only generic valid usage we have for these things is "must: be null-terminated", are you looking for things like "must be UTF-8" etc.?

**Comment by krOoze** [comment]
Just saying, while this is in VU(Implicit) under respective commands, it is missing in 2.6.2. Implicit Valid Usage (which otherwisely seems to list those exhaustively).

Yeah, adding "string means UTF-8" would be nice. It is meaningless most of the times, but makes some sense to note for e.g. `pApplicationName`. The chapter (despite its name) also tends to describe what is a valid output from Vulkan, where it would be also nice knowing it is UTF-8.

**Comment by oddhack** [comment]
Well, it doesn't necc. mean that for the whole spec. There are some extensions under development which pass around UTF-16 strings because of platform-specific requirements, for example.

**Comment by krOoze** [comment]
@oddhack Except exceptions of course. Maybe then disable autovalidity for these (I have to assume win32) extensions? They would need extended VU anyway (I think technically UTF-16 should be also divisible by 2 bytes).

**Comment by critsec** [comment]
The UTF-16 cases are Windows-specific and use type `LPCWSTR`, rather than the `const char*` or `const char[]` we use for other strings. So it shouldn't be too hard to distinguish these.

**Comment by TobiasHector** [comment]
> The UTF-16 cases are Windows-specific and use type LPCWSTR, rather than the const char* or const char[] we use for other strings. So it shouldn't be too hard to distinguish these.

Yea the autovalidity language in question is already based on type, so this shouldn't be a problem.

**Comment by TobiasHector** [comment]
FWIW, we have dropped the general UTF-8 requirement, it's unnecessary in most places - though some specific parameters do require valid UTF-8, which is called out in the spec at the appropriate location. But this should hopefully make it into the next spec update.

**Comment by oddhack** [comment]
This should be addressed in the 1.0.51 spec update.
