### ISSUE TITLE
VU vs VK_ERROR_FEATURE_NOT_PRESENT

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#496]
`VkPhysicalDeviceFeatures` structure VU says:

> - If any member of this structure is `VK_FALSE`, as returned by `vkGetPhysicalDeviceFeatures`, then it **must** be `VK_FALSE` when passed as part of the `VkDeviceCreateInfo` struct when creating a device

But I think that should be removed, because `VK_ERROR_FEATURE_NOT_PRESENT` already seems like it should handle all such cases.

**Comment by TobiasHector** [comment]
Yea agree this should go - I'll take this.

**Comment by oddhack** [comment]
This should be addressed in the 1.0.51 spec update.
