### ISSUE TITLE
[Validity] vkGetPhysicalDeviceSurfaceSupportKHR should have generated same-source VU?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#497]
I think `vkGetPhysicalDeviceSurfaceSupportKHR` is missing generated/Implicit VU saying something like:

> `surface` and `physicalDevice` **must** have been created from the same `VkInstance`

**Comment by oddhack** [comment]
This should be fixed in the 1.0.59 spec update.
