### ISSUE TITLE
PDF: Slightly deeper nesting in the bookmark list

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#498]
Right now, the bookmarks in the PDF have 2 levels: chapter and top-level sections. Because some sections of the specification go pretty deep into nested sections, I think having this go 3 levels deep would be a good idea.

A good example of where this would be helpful is in the *Drawing Commands* chapter. That chapter has two top-level sections: one for all primitive topologies, and one for programmable shading. But all of the specific topologies live in subsections of the first section. Jumping to one of those subsections is kind of useful.

Now, there is a concern that adding this third level will also cause the bookmarks to get less navigatable. An example for that is all of the extensions, which will have bunches of new sections added to them.

**Comment by oddhack** [comment]
Asciidoctor only supports static TOC depth OOTB, which means whatever we do, someone will be unhappy that there's either too much or too little depth. I will try to take a look at https://stackoverflow.com/questions/34481638/how-to-use-tocify-with-asciidoctor-for-a-dynamic-toc when time allows though.

**Comment by oddhack** [comment]
I just tried the stackoverflow solution but while the script is getting included in the generated HTML, it's not doing anything. Perhaps if you have time to experiment with this you could sort out why it isn't working - also see https://github.com/asciidoctor/asciidoctor/issues/699

**Comment by TobiasHector** [comment]
If we wanted collapsible toc for html there are html built-in things we can do that I've previously experimented with which would allow this. I could dig that up again and integrate it if you think that's helpful? Javascript solutions like tocify will probably result in more awkward layout issues when loading the spec which I'd rather avoid, and there's a good html alternative with the \<details\> tag. For instance:

<details>
<summary>
A collapsed section
</summary>
Hello! 
</details>
<br>

Maybe raise a separate issue for that?

For the PDF, I don't think adding another level would be the worst thing in the world, though there are some chapters that would kind of explode. The use of levels is fairly inconsistent through the spec which is sort of a whole other problem. We can probably look how bad it is to do that and make a judgement call.

**Comment by oddhack** [comment]
I got the tocify thing working after feedback on asciidoctor/asciidoctor#699 and expanding toclevels to 3, and it seems functional. It only expands the section you've currently selected and all the others remain unexpanded, unlike some other accordion solutions I've used where you toggle it manually on a section by section basis. Not sure it's really an improvement - I usually just search anyway - but we could run it by the group and compare/contrast to the HTML built-ins if you want to get that working. I am pretty passive about this sort of stuff. It's like being a sysadmin, no matter what you do, you will make people unhappy.

My guess is that the asciidoctor project will not address feature requests of this nature unless they're given a complete, functioning PR - more power to you if you can give them one.

**Comment by oddhack** [comment]
I think the direction we're headed here is that @TobiasHector will work up a \<details>-based solution for the index when he has time. The script solution works, but is pretty complex.

**Comment by timofonic** [comment]
@Tobski @oddhack @NicolBolas Any news?
