### ISSUE TITLE
Add required extension to extension function VU

### ISSUE THREAD

**Issue by ratchetfreak** [KhronosGroup/Vulkan-Docs#499]
Currently when seeing you can use an extension function in the spec there is only the suffix to show that it is an extension function and the surrounding text.

I propose adding the extension that adds the function/structure to their implicit valid usage.

**Comment by oddhack** [comment]
Do you mean something like "vkFooKHX cannot: be called unless the VK_KHX_foo extension is supported"?

**Comment by ratchetfreak** [comment]
yeah or something like

VU for for vkGetPhysicalDeviceFeatures2KHR

>  Valid Usage (Implicit)
> * physicalDevice must be a valid VkPhysicalDevice handle
> * pFeatures must be a pointer to a VkPhysicalDeviceFeatures2KHR structure
> * The extension VK_KHR_get_physical_device_properties2 must be enabled in the instance.

**Comment by krOoze** [comment]
These things can be looked up in the spec appendices (yeah, not ideal).

I would note: a function is not the only way to use an extension:

 - structures may be passed as `pNext`
 - extended enum values may be used (adding this to function VU might get lenghty, so I proposed #444 as a compromise)

**Comment by ratchetfreak** [comment]
@krOoze I did mention structures and there is the implicit condition that a structure can only be valid if the extension it's part of is active so it doesn't need to be mentioned in the pnext chain of the core struct.

**Comment by krOoze** [comment]
@ratchetfreak Oh, I thought this is about convenience. If this is about actual validity, this spec sentence covers all (including functions).

> Enabling an extension does not change behavior of functionality exposed by the core Vulkan API or any other extension, other than **making valid** the use of the **commands**, enums and structures defined by that extension.

**Comment by oddhack** [comment]
We have some ideas about this but they'll be in the longer term.

**Comment by oddhack** [comment]
We just published an update that puts a comment at the beginning of each structure and function definition showing what extension, version, or combination thereof requires that interface. This isn't exactly what you were asking for, but it is some progress.

**Comment by oddhack** [comment]
Closing this. We aren't planning any additional changes in this area beyond the comments in the structure / function definitions showing which extension(s)/core version they depend on.
