### ISSUE TITLE
[Validity] missing pQueueFamilyIndices VUs

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#501]
There seems to be missing VU for `pQueueFamilyIndices` saying the elements have to be valid queue family indices for the `VkDevice`.

Also:
Can the indices repeat in the array? If not, that uniqueness VU is missing too.

Affected VUs:
`VkBufferCreateInfo`
`VkImageCreateInfo`
`VkSwapchainCreateInfoKHR`

**Comment by oddhack** [comment]
This should be addressed in the 1.0.51 spec update.
