### ISSUE TITLE
[Validity] Valid value for maxAnisotropy unclear when samplerAnisotropy enabled but anisotropyEnable false

### ISSUE THREAD

**Issue by msc-** [KhronosGroup/Vulkan-Docs#503]
Spec 48 says that if samplerAnisotropy not enabled on the device then VkSamplerCreateInfo::maxAnisotropy must be 1.0. It also says that this value must be between 1.0 and VkPhysicalDeviceLimits::maxSamplerAnisotropy if VkSamplerCreateInfo::anisotropyEnable is true.

It does not say what the valid values are if samplerAnisotropy is enabled but VkSamplerCreateInfo::anisotropyEnable is false. It seems reasonable to expect it should be 1.0 but vulkan.hpp sets it to 0.

**Comment by critsec** [comment]
When `VkSamplerCreateInfo::anisotropyEnable` is `VK_FALSE`, the value of `maxAnisotropy` is irrelevant and is ignored, so any value is valid. We do this in some other places in the API, but the spec probably doesn't call that out explicitly. But making the `maxAnisotropy` value validity conditional on `anisotropyEnable==VK_TRUE` is intentional.

**Comment by msc-** [comment]
> When VkSamplerCreateInfo::anisotropyEnable is VK_FALSE, the value of maxAnisotropy is irrelevant and is ignored

This would normally be the expected choice but elsewhere (section 32.1) the spec. states that if VkPhysicalDeviceFeatures::samplerAnisotropy is not enabled, i.e. VK_FALSE, then maxAnisotropy must be 1.0 which leads one to conclude that the maxAnisotropy value may also not be ignored when VkSamplerCreateInfo::anisotropyEnable is VK_FALSE.

**Comment by msc-** [comment]
> When VkSamplerCreateInfo::anisotropyEnable is VK_FALSE, the value of maxAnisotropy is irrelevant and is ignored

This would normally be the expected choice but elsewhere (section 32.1) the spec. states that if VkPhysicalDeviceFeatures::samplerAnisotropy is not enabled, i.e. VK_FALSE, then maxAnisotropy must be 1.0 which leads one to conclude that the maxAnisotropy value may also not be ignored when VkSamplerCreateInfo::anisotropyEnable is VK_FALSE.

**Comment by critsec** [comment]
Good point, thanks for pointing that out. I've filed an internal bug to make sure everyone is on the same page about this, and to fix the inconsistency.

**Comment by zeux** [comment]
In addition, the validation layers explicitly check for the 32.1 condition of spec:

https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/b7fe35057ef99c503c3ad96860c2eb437345beb8/layers/parameter_validation.cpp#L2459-L2465

Whereas it seems like the spec should say that maxAnisotropy is ignored when VkSamplerCreateInfo::anisotropyEnable is false *and* the layers should restrict the check to this condition.

**Comment by oddhack** [comment]
This should be closed in the 1.0.65 spec update.
