### ISSUE TITLE
[Specification] VK_KHR_get_surface_capabilities introduced typo

### ISSUE THREAD

**Issue by hesiod** [KhronosGroup/Vulkan-Docs#504]
Right above the [VkPhysicalDeviceSurfaceInfo2KHR](https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPhysicalDeviceSurfaceInfo2KHR), it says "strucutre".

**Comment by oddhack** [comment]
This will be fixed in the next public spec update in a week or so. Closing now as I'll certainly forget about it otherwise.
