### ISSUE TITLE
[Specification] Unmet extension dependency behavior unspecified

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#507]
(Continuing from #260)
In the appendix the extensions state dependency on other extensions.

1) Does that mean those dependency extensions also have to be enabled at the same time?

2) If I do not/forget to list the dependency extension in requested extensions of `vkCreateInstance` or `vkCreateDevice`, what is the Vulkan's behavior?
    a) `VK_ERROR_EXTENSION_NOT_PRESENT` is returned
    b) `VK_ERROR_INITIALIZATION_FAILED` is returned
    c) Undefined behavior applies
    d) The dependency extension is also implicitly enabled

The generic descriptions of a) nor b) does not really match the case. The requested extension is in fact supported (unlike `VK_ERROR_EXTENSION_NOT_PRESENT` says), and resp. this does not feel like a "implementation-specific reason" (unlike `VK_ERROR_INITIALIZATION_FAILED` definition says), but more like a logical-error of the Application.

**Comment by warp-10** [comment]
I've been wondering this myself.
I'd prefer (d), as that would allow extension dependencies to change with driver updates.
However, I'm not sure if there is any way for an application to then query which additional extensions were enabled...

**Comment by krOoze** [comment]
> I'd prefer (d), as that would allow extension dependencies to change with driver updates.

Extension-extension dependencies flow directly from the way extension's API is specified (e.g. it could need a Format introduced by another extension and the user will need to use the API of the dependency extension directly too).  So, I don't see the need for a driver to change these kinds of dependencies at all. They are at lower abstraction level, and can to whatever they want under the hood.

**Comment by oddhack** [comment]
This should be addressed in the 1.0.51 spec update.

**Comment by krOoze** [comment]
Alright, I see it resolved to c) (while reserving the option to change it to a) or b) in the future).
