### ISSUE TITLE
[Registry] VkSwapchainCounterCreateInfoEXT missing in validextensionstructs

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#510]
`VkSwapchainCounterCreateInfoEXT` is missing in `validextensionstructs` of `VkSwapchainCreateInfoKHR`.

**Comment by cubanismo** [comment]
Good catch.  I'll get this fixed.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.55 spec update.
