### ISSUE TITLE
When are VkRenderPasses safe to delete?

### ISSUE THREAD

**Issue by cdwfs** [KhronosGroup/Vulkan-Docs#516]
I have a test application which creates VkFramebuffers and VkPipelines prior to creating VkRenderPasses.  For framebuffer/pipeline creation purposes I'm using a placeholder VkRenderPass that is compatible (according to the requirements in section 7.2 of the spec) with the final render pass used at draw time. Originally, I destroyed the placeholder VkRenderPass immediately after VkFramebuffer/VkPipeline creation, since my application no longer needed it. This worked correctly in some cases, but caused a driver crash on certain IHVs. The crash went away after I deferred destroying the throwaway render pass until application cleanup time. I speculate that the vendor in question is keeping a handle to the original render pass around to verify compatibility at draw time, and not testing it for validity before the check.

I'm fine with this workaround if necessary, but I'm curious whether the spec has anything to say about when it's safe to destroy a VkRenderPass that's only used to create VkPipelines and VkFramebuffers? The VU notes for vkDestroyRenderPass() do say that "All submitted commands that refer to renderPass must have completed execution", but this isn't really an explicit reference by a GPU command; if anything it's an implicit reference by some internal validation code. Is this a driver bug, or should the spec require applications not to destroy VkRenderPasses until any dependent VkFramebuffers and VkPipelines have been destroyed?

**Comment by courtney-g** [comment]
Yeah, section 2.3.1 Object Lifetime doesn't really cover the lifetime of "compatible" objects.

**Comment by critsec** [comment]
The intent was definitely to allow you to use a temporary VkRenderPass to create these object, and have them outlive the render pass. Any internal state was supposed to be copied into the secondary objects, or reference-counted internally (or something equivalent). I guess we failed to make that completely clear in the spec. Cort, can you raise an internal issue? Sounds like we need spec fixes and a CTS test.

**Comment by cdwfs** [comment]
Done!

**Comment by oddhack** [comment]
This should be fixed in the 1.0.55 spec update.
