### ISSUE TITLE
Spec does not tell value of VkPhysicalDeviceProperties2KHR::sType

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/Vulkan-Docs#518]
Hi,

current spec (51) does not tell a valid value for VkPhysicalDeviceProperties2KHR::sType (and also not for VkPhysicalDeviceIDPropertiesKHX following it up)

**Comment by TobiasHector** [comment]
This is actually a general problem for "returned" structures in the API, but this has been fixed already and will be resolved in the next spec release.

**Comment by TiemoJung** [comment]
Hase been fixed with rev 53.
