### ISSUE TITLE
Integer color value 1

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#52]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#textures-texel-replacement says:

> VK_BORDER_COLOR_INT_OPAQUE_WHITE  B=(1,1,1,1)

Shouldn't the "1" actually be "2^{number of bits in the integer component type}-1", or "the maximum representable positive integer value" or something? Otherwise, how does it ever get converted into the same numeric range as any non-normalized integer memory reads that went through the "Format Conversion" steps?

(It feels like there's probably something obvious that I'm missing here...)

Same with the "one=1 for integer formats and stencil aspects" in "Conversion to RGBA".

Same with the "one=1 for integer components" in "Component Swizzle".

Same with the "VK_COMPONENT_SWIZZLE_ONE: the component is set to either 1 or 1.0" in "Image Views".

**Comment by jeffbolznv** [comment]
It is intentionally "1" in all cases.

Integer formats don't do any format conversion, except possibly sign-extension (I don't recall, but we should clarify in the spec).

**Comment by philiptaylor** [comment]
Hmm, so VK_BORDER_COLOR_INT_OPAQUE_WHITE is always going to come out as extremely dark grey? Odd, but if that's how the hardware works then I guess I can't complain except about the quite misleading symbol name (which probably wouldn't be worth changing now).

**Comment by jeffbolznv** [comment]
It'll be dark if you normalize it. Maybe the names are misleading, but it's just trying to describe a few combinations of zeros and ones.

**Comment by krOoze** [comment]
Gonna bump this issue. Also what about SNORM? Shouldn't VK_BORDER_COLOR_INT_OPAQUE_BLACK be -1 in that case?

Most likely somewhere should be written more clearly those are only expressed as unsigned normalized fixed-point in the spec text... (or am I wrong and the values are literaly meant regardles of format?)

There seems to be an (in my opinion poor) attempt at that in the spec:

> Border texels are replaced with a value [!]based on the image format[!] and the borderColor of the sampler.

**Comment by jeffbolznv** [comment]
> or am I wrong and the values are literaly meant regardles of format?

Texel replacement occurs after format conversion, so all texels are either floating point, signed integer, or unsigned integer, and the border color values are in one of those types.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.16 spec update.
