### ISSUE TITLE
Spec does not tell something

### ISSUE THREAD

**Issue by eranzhao** [KhronosGroup/Vulkan-Docs#520]
Hi, I has some question but the spec does not tell:

1. Can one memory object bind to multiple vulkan image/buffer objects?
2. How does the memory layout look like when create a vulkan image with mipmap level and array size specified? （How to calculate the offset of the memory when map the texture and memcpy data directly to the subimages?）
3. Is the all map operation defined as a persistent map?  How can I create a persistent mapping buffer/image? （Just specified the VK_MEMORY_PROPERTY_HOST_COHERENT_BIT and VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT, and then map the memory of the buffer/image?）

Thanks!

**Comment by TobiasHector** [comment]
Hey @eranzhao:

> 1. Can one memory object bind to multiple vulkan image/buffer objects?

Yes, https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#resources-memory-aliasing has details on what you can and can't do when you alias memory like this.

> 2. How does the memory layout look like when create a vulkan image with mipmap level and array size specified? （How to calculate the offset of the memory when map the texture and memcpy data directly to the subimages?)

Firstly, you can only do that with images with a `tiling` parameter of `TILING_LINEAR` - `TILING_OPTIMAL` images cannot be addressed from the CPU in any sane fashion. The memory for these images must also be in either the VK_IMAGE_LAYOUT_PREINITIALIZED or VK_IMAGE_LAYOUT_GENERAL layouts.
[vkGetImageSubresourceLayout](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#vkGetImageSubresourceLayout) describes how this works.

> 3. Is the all map operation defined as a persistent map? How can I create a persistent mapping buffer/image? （Just specified the VK_MEMORY_PROPERTY_HOST_COHERENT_BIT and VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT, and then map the memory of the buffer/image?）

Assuming you mean persistent as described in https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_buffer_storage.txt, all Vulkan mappings are considered persistent - there's no non-persistent mappings.

Hope that helps!

**Comment by eranzhao** [comment]
Thanks @TobiasHector ! That's all I need! 👍 I will read your spec more carefully!
