### ISSUE TITLE
Link from 14.3. Fragment Output Interface to 2.8.2. Conversion from Floating-Point to Normalized Fixed-Point

### ISSUE THREAD

**Issue by tksuoran** [KhronosGroup/Vulkan-Docs#521]
Current spec 1.0.51, section 14.3 Fragment Output Interface says: "If the color attachment has a signed or unsigned normalized fixed-point format, color values are assumed to be floating-point and are converted to fixed-point as described in Conversion from Normalized Fixed-Point to Floating-Point". This is wrong conversion (2.8.1). The correct conversion should be 2.8.2. Conversion from Floating-Point to Normalized Fixed-Point.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.55 spec update.
