### ISSUE TITLE
What happens when two variables have the same DescriptorSet and Binding values?

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#522]
At present, the Vulkan specification doesn't really say that this must not happen. The closest it gets is this:

> If multiple entry points in the same pipeline refer to the same set and binding, all variable definitions with that `DescriptorSet` and `Binding` must have the same basic type.

This applies only to "multiple entry points". Which means that if you have single entry point that references multiple different variable definitions with the same `DescriptorSet` and `Binding`, apparently that's fine.

I assume the idea is that all declarations with a particular set&binding, anywhere in the pipeline, have to be declared identically.

Also, it's not clear what it means for the two variable definitions to "have the same basic type".

**Comment by critsec** [comment]
This arose from: https://stackoverflow.com/questions/44827700/do-bindings-within-a-set-have-to-be-unique-for-a-uniform

**Comment by oddhack** [comment]
Should be addressed in the 1.0.58 spec update.
