### ISSUE TITLE
Is it legal for fragment shaders to not write to a color attachment if writes are masked in blend state?

### ISSUE THREAD

**Issue by aejsmith** [KhronosGroup/Vulkan-Docs#523]
As the title says, if we have an attachment specified in a render pass, but a fragment shader used with that render pass does not write to that attachment (and doesn't even define an output corresponding to it), would that be valid behaviour if the blend state in the pipeline has writes masked for that attachment?

The spec says the following:
> The input to blending or color attachment writes is undefined for components which do not correspond to a fragment shader output.

But my assumption would be that the input to the write being undefined would not matter if the write is masked anyway. Is that a correct assumption? I found [an older issue](https://github.com/KhronosGroup/Vulkan-Docs/issues/477) which suggests in the comments that it is.

If so, I think the validation layers need to be updated to handle this case. Currently if you have an output which is not written, you still get a warning even when the write mask is set to 0:
> Attachment 1 not written by fragment shader

**Comment by critsec** [comment]
Correct, undefined input to the write don't matter if the write is disabled. Please file a bug against the [validation layers](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers), if you don't mind.

**Comment by NicolBolas** [comment]
As you've stated, the specification is very clear. And there is [already an issue filed there](KhronosGroup/Vulkan-LoaderAndValidationLayers#1931). So there's no need for this one.

**Comment by aejsmith** [comment]
Oops, I missed that one. In that case, sorry for the noise here!
