### ISSUE TITLE
VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER aliasing vs. spec descriptor language

### ISSUE THREAD

**Issue by Novum** [KhronosGroup/Vulkan-Docs#524]
I'm confused about a possible contradiction in the spec

"DescriptorSet and Binding Assignment"
> If multiple entry points in the same pipeline refer to the same set and binding, all variable definitions with that DescriptorSet and Binding *must have the same basic type*.

"Combined Image Sampler"
> VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER descriptor set entries can also be accessed via separate sampler and sampled image shader variables.

As far as I know the later requires to alias e.g. a sampler2D with either sampler or texture2D in GLSL:
`layout( set = 0, binding = 0 ) uniform sampler2D combined;`
`layout( set = 0, binding = 0 ) uniform texture2D textureOnly;`
`layout( set = 0, binding = 0 ) uniform sampler samplerOnly;`

Is this legal? It seems to work in my tests. If it is not, what is the correct way of using only the texture or sampler part of a combined sampler? Casts from sampler2D to texture2D seem to illegal.

**Comment by oddhack** [comment]
Should be addressed in the 1.0.58 spec update.
