### ISSUE TITLE
Documentation of VkPipelineCreateFlagBits wrong

### ISSUE THREAD

**Issue by abergmeier** [KhronosGroup/Vulkan-Docs#525]
From https://stackoverflow.com/questions/45065402/compute-pipeline-as-parent/45066109#45066109:

Can a compute pipeline be derived from another compute pipeline? `VkPipelineCreateFlagBits` doc says no.

**Comment by janharaldfredriksen-arm** [comment]
It can. We'll fix the VkPipelineCreateFlagBits documentation.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.57 spec update.
