### ISSUE TITLE
KHX not  listed in vendor/author tags for extensions and layers

### ISSUE THREAD

**Issue by ville-h** [KhronosGroup/Vulkan-Docs#526]
KHX not  listed in vendor/author tags for extensions and layers:
https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/src/spec/vk.xml#L38

**Comment by oddhack** [comment]
Thanks. I'll take care of it.

**Comment by krOoze** [comment]
I wonder if names ending in X should be reserved and implicit (without need to be listed) for every listed vendor.

**Comment by ville-h** [comment]
Having the tags listed explicitly makes it easier to process the xml for purposes of generating namespaces/modules and placing corresponding identifiers in them.

There doesn't even seem to be a simple scheme for the x-name. KHR's x-name is KHX, AMD's x-name is AMDX, NV's x-name is NVX. So if they are not explicitly listed, any tool processing would hardcode them, or at least some exceptions, as it's not certain what scheme to use to generate the x-name from a base-name is.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.56 spec update.
