### ISSUE TITLE
registry.rnc comment nodes in features, but not in extensions.

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#527]
The recent updates to registry.rnc added a lot of `comment` nodes. Among the places they were added was between the `InterfaceElement` nodes in `required` and `removed` elements. But this was only done for `feature` elements, not for the `required` and `removed` elements in `extension`s.

This seems to be an odd inconsistency.

**Comment by oddhack** [comment]
I added them in the places they were required to support the existing XML comments. If more are needed  in the future that can be done by the person adding a comment in a new place.
