### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by TTimo** [KhronosGroup/Vulkan-Docs#528]
Will the documentation and specifications be available in other languages? (Japanese)

**Comment by oddhack** [comment]
We would like to do that, but don't have the resources and language skills in-house. When Khronos has provided translations of our specifications in the past, it was by partnering with another organization in those countries, which had government or academic funding support for what is a moderately large project. So, no plans at present, but we are interested in supporting other people who could take on such a project.
