### ISSUE TITLE
aspectMask restrictions should be converted to VU (+ have VUID)

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#529]
`aspectMask` (`VkImageAspectFlags`) parameter restrictions should be converted to VU (+ have VUID).

For example:
`vkCmdClearColorImage` have in the descriptions:
> The `aspectMask` of all image subresource ranges **must** only include `VK_IMAGE_ASPECT_COLOR_BIT`.

It is obvious it fits better in the VU section. Also it needs VUID so it can be properly reported by the layers.

**Comment by timofonic** [comment]
@krOoze @oddhack Any news?

**Comment by krOoze** [comment]
There might be some VUs missing in `vkCmdClearAttachments` for the exoctic aspect masks (e.g. multi-plane)?

**Comment by krOoze** [comment]
`vkGetImageSubresourceLayout` `aspectMask` restrictions are still in free-form text instead of VUs.

**Comment by oddhack** [comment]
There's been a lot of improvements in the VUs and I don't think these specific concerns with duplicating VUs in body text are still relevant. If you see more cases where VU text is replicated in the body please bring that up.
