### ISSUE TITLE
relative order of struct declarations in vk.xml

### ISSUE THREAD

**Issue by ville-h** [KhronosGroup/Vulkan-Docs#530]
Is the relative order of declarations of structs in vk.xml meant to be "c declaration order"? 
If not then nevermind. If yes then these seem to be "out of order":
VkPhysicalDeviceLimits should appear before VkPhysicalDeviceProperties
VkPhysicalDeviceSparseProperties should appear before VkPhysicalDeviceProperties
VkPhysicalDeviceFeatures should appear before VkDeviceCreateInfo
VkMemoryType should appear before VkPhysicalDeviceMemoryProperties
VkMemoryHeap should appear before VkPhysicalDeviceMemoryProperties
VkPresentTimeGOOGLE should appear before VkPresentTimesInfoGOOGLE
VkPresentRegionKHR should appear before VkPresentRegionsKHR
VkRectLayerKHR should appear before VkPresentRegionKHR

**Comment by oddhack** [comment]
It is not meant to be in dependency order. The header generation scripts perform a dependency analysis and emit declarations in the required order. In fact we're probably going to start sorting them alphabetically in the near future.
