### ISSUE TITLE
Debug report callback return value real-world behavior contradicts spec

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#534]
I am not sure if to raise this here or on Validation Layer repo...

The spec says:

> The callback returns a `VkBool32` that indicates to the calling layer the application’s desire to abort the call. A value of `VK_TRUE` indicates that the application wants to abort this call. If the application returns `VK_FALSE`, the command **must** not be aborted.

Firstly, it is not plainly obvious what "the call" and "this call" refers to.

Secondly, I dabble a bit in the layer development, and this does not seem to match what actually happens.
Which is (to my understanding) that within the Vulkan call a layer makes a bitwise ORs of all the return values of debug callbacks within that layer and then if that sum is true it prevents the next layer (or driver) in the chain to be called.

Let's say a debug callback returns `VK_TRUE` and then second callback within the same command retruns `VK_FALSE`. Considering the "If the application returns `VK_FALSE`, the command **must** not be aborted.", it is not obvious what should happen. (Equally non-obvious is If the first is `VK_FALSE` and second `VK_TRUE`.)

Then there are things that are at least worth a note.
One might assume `VK_TRUE` aborts immediatelly and there won't be another debug callback issued.
Also one might assume it does not interrupt between the layers, especially if they are presented as one layer (`VK_LAYER_LUNARG_standard_validation`)

UPDATE:
I also learned it does not abort on INFO and DEBUG messages while `VK_TRUE`, which makes a sort of sense, but still is a bit surprising given the spec description above.

**Comment by oddhack** [comment]
Assign to @courtney-g to triage.

**Comment by courtney-g** [comment]
+tobine as validation layer lead. From comments here, it sounds like validation behavior does not follow the debug_report spec expectation. Need to decide if that is something that needs to be fixed in the validation layers or relax the spec language a bit.

**Comment by courtney-g** [comment]
FWIW, the inclusion of a return value from the callback was made to help with validation testing.
In our validation tests (tests to check proper execution of the validation layers) there were times where the test wants the validation layer to abort the call as soon as possible to avoid a segfault or other issue that could bring down the test process.
Makes me think that one possibility is to remove the definition of the return value from the spec. Apps should always return false and instead make it part of the loaderAndValidationLayers development documentation for validation layer deverlopers.

**Comment by krOoze** [comment]
@courtney-g The intention is clearly not to send the test-case invalid parameters down the chain to the non-validation layers and the drivers. One way would be to make this a layer setting instead and deprecate the return value completely.

**Comment by mark-lunarg** [comment]
The line "If the application returns VK_FALSE, the command must not be aborted" can be excised or edited -- as it currently stands it is nonsense.

**Comment by courtney-g** [comment]
@krOoze considering the use for validation layer testing, what language would you like to see in the extension?

**Comment by krOoze** [comment]
@courtney-g 
Well, perhaps simplest would be:

> The callback returns a `VkBool32` which is interpreted in a layer-defined manner. The application **should** return `VK_FALSE`. The `VK_TRUE` value is reserved only for the use in layer development.

Alternatively fix it to be accurate:

> The callback returns a `VkBool32` value. A value of `VK_TRUE` indicates that the application wants the current layer (identified by `pLayerPrefix`) to prevent propagating the currently intercepted command down the layer chain. Returning multiple different values to the same layer in the duration of a command counts as a single `VK_TRUE` value. Applications **should** always return `VK_FALSE` so that they see the same behavior with and without validation layers enabled.

**Comment by courtney-g** [comment]
I like your first option. Second gets into too much detail on how validation works, today, that is probably not necessary to cover here.

**Comment by courtney-g** [comment]
CL I've posted for review now says:
The callback returns a basetype:VkBool32 which is interpreted in a
layer-specified manner. The application should: always return ename:VK_FALSE.
The ename:VK_TRUE value is reserved for use in layer development.

I'll set this to merge tomorrow if I don't hear any feedback.

**Comment by krOoze** [comment]
@courtney-g I think "which" requires a comma. There should possibly be "the" somewhere before development noun.

**Comment by courtney-g** [comment]
> I think "which" requires a comma. There should possibly be "the" somewhere before development noun.

Not according to Grammarly.

> PS: It might require some wholistic changes elsewhere. 

Good point. I've removed the sentence relating return of VK_TRUE with VK_RESULT_VALIDATION_ERROR. I think that's okay because VK_RESULT_VALIDATION_ERROR is described elsewhere in the extension.

**Comment by krOoze** [comment]
> Not according to Grammarly.

[Or does it not?](https://www.grammarly.com/blog/comma-before-which/)

**Comment by courtney-g** [comment]
I see, apparently Grammarly parser can't tell if that is a restrictive or non-restrictive phrase.
Based on Grammarly article, that phrase is non-restrictive and should have comma.

**Comment by krOoze** [comment]
@courtney-g It is tricky. 

> Restrictive phrases are usually introduced by that instead of which, especially in American English.

Is probably why their script generally avoids flagging it. The day a computer can handle English grammar is the day I welcome our artificial overlords. :p

**Comment by oddhack** [comment]
This should be resolved in the 1.0.64 spec update.
