### ISSUE TITLE
what is the purpose of <extension> tag's author attribute?

### ISSUE THREAD

**Issue by ville-h** [KhronosGroup/Vulkan-Docs#536]
What is the purpose of &lt;extension&gt; tag's author attribute? I noticed that a handful of &lt;extension&gt; tags have a seeming mismatch between the author attribute and the actual author/vendor identifier used by the extension. As an example:

&lt;extension name="VK_EXT_depth_range_unrestricted" type="device" number="14" author="NV" contact="Piers Daniell @pdaniell" supported="vulkan"&gt;

Author attribute says "NV" but the actual used author/vendor identifier is "EXT" in the identifiers. Are the two supposed to match?

**Comment by krOoze** [comment]
https://www.khronos.org/registry/vulkan/specs/1.0/registry.html#tag-extensions

> **author** - optional. The author name, such as a full company name. If not present, this can be taken from the corresponding tag attribute. However, EXT and other multi-vendor extensions may not have a well-defined author or contact in the tag.

**Comment by TobiasHector** [comment]
Hm, that seems somewhat redundant to be honest. I think usually I've put EXT when doing an EXT, not even sure what it's really giving you for information. Kind of wonder if we should ditch it, or at least make it always consistent with the tag.

@oddhack?

**Comment by ville-h** [comment]
Good to know it's not meant to be anything consistent. And yes, if it's not ment to match an existing "vulkan vendor/author tags for extensions and layers" tag name attribute, it seems quite pointless information as far as processing the xml goes.

Also thanks for the link. Somehow I've been oblivious to its existence all this time.

**Comment by oddhack** [comment]
We should state something more assertive about that. The author tag is intended to be the vendor ID, if it exists, but there were a few cases where that wasn't happening, and if we were capturing information about layers (we aren't, at present), they don't necc. have a vendor ID. The use is to map the extension onto a full vendor name, and (potentially, though we don't do that) to valid the extension suffixes.

**Comment by oddhack** [comment]
This should be resolved in the 1.0.64 spec update.
