### ISSUE TITLE
VK_STRUCTURE_TYPE_SURFACE_CAPABILITIES2_EXT has no word-boundary '_' before '2'

### ISSUE THREAD

**Issue by ville-h** [KhronosGroup/Vulkan-Docs#539]
VK_STRUCTURE_TYPE_SURFACE_CAPABILITIES2_EXT has no word-boundary '_' before '2' like other versioned entries such as: VK_STRUCTURE_TYPE_SURFACE_CAPABILITIES_2_KHR, VK_STRUCTURE_TYPE_SURFACE_FORMAT_2_KHR and so on.

**Comment by NicolBolas** [comment]
Well, I don't think it's something that can be fixed now. There's been I think one example of an enumerator that was misspelled but not caught before it shipped. They created a correctly named enum, but left the other.

In this case, the type has been superseded by VK_KHR_get_surface_capabilities2. Indeed, `VkSurfaceCapabilities2EXT` can't even be taken by `vkGetPhysicalDeviceSurfaceCapabilities2KHR`. So there's not much point in issuing such a change.

**Comment by TobiasHector** [comment]
It can be fixed somewhat with an alias. We've done that before, make it so the "proper" version is the one in the enum and then there's an alias with the incorrect name in the header. There's a couple examples of this already in the header for similar reasons.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.59 spec update.
