### ISSUE TITLE
Misleading naming of section 5.2 (Command Buffer Lifetime)

### ISSUE THREAD

**Issue by AlexeyKryshen** [KhronosGroup/Vulkan-Docs#54]
Using a word "Lifetime" in naming of section 5.2 (Command Buffer Lifetime) is a bit misleading. The word "Lifetime" is better suitable for the cases when there are some kind of implicit rules for the period during which something is functional (e.g. objects and object names lifetime in OpenGL). In a case of section 5.2 of Vulkan specification there are no such implicit rules and section actually just describe the creation/destruction functions for Command Buffers.

**Comment by oddhack** [comment]
Thanks. Will fix in one of the upcoming weekly-ish spec updates.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.6 spec update.
