### ISSUE TITLE
Dynamic viewport and scissor not restricted to VkPipelineViewportStateCreateInfo.viewportCount

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#540]
Viewport and scissor count is still inherited even if dynamic:

> `VK_DYNAMIC_STATE_VIEWPORT` specifies that the `pViewports` state in `VkPipelineViewportStateCreateInfo` will be ignored and **must** be set dynamically with `vkCmdSetViewport` before any draw commands. The number of viewports used by a pipeline is still specified by the `viewportCount` member of `VkPipelineViewportStateCreateInfo`.

> `VK_DYNAMIC_STATE_SCISSOR` specifies that the `pScissors` state in `VkPipelineViewportStateCreateInfo` will be ignored and **must** be set dynamically with `vkCmdSetScissor` before any draw commands. The number of scissor rectangles used by a pipeline is still specified by the `scissorCount` member of `VkPipelineViewportStateCreateInfo`.

But in `vkCmdSetViewport` (and similarly in `vkCmdSetScissor`) there is no VU restricting `firstViewport` and `viewportCount` pair to the `[0, VkPipelineViewportStateCreateInfo.viewportCount)` range.

**Comment by oddhack** [comment]
Can you submit a PR to this effect? We'll start considering github PRs in our internal process starting next week, now that the CLA issue is finally resolved - I see you have a couple of old ones we'll look at as well.

**Comment by krOoze** [comment]
@oddhack Alright then.

**Comment by krOoze** [comment]
@oddhack Hmm, after further reading I think the original intention was to make the dynamic state bound to the whole command bufer (and **not** the currently bound pipeline). But such usage is prevented by the VU statement of the `vkCmdSetViewport`:

> - The currently bound graphics pipeline **must** have been created with the `VK_DYNAMIC_STATE_VIEWPORT` dynamic state enabled

Can I have some resolution on that?

**Comment by krOoze** [comment]
@oddhack After further reading I am no longer exactly certain on how dynamic state is supposed to be carried over. The spec on numerous occasions want it to be a command buffer state (not bound pipeline state). It seems sensible to me to set more viewports and that state would carry over to the pipeline that is bound next (with potentially more viewports). Then again it was touched on a bit before in #235 , which resulted in a restriction that does not allow dynamic state to be set without a bound dynamic-state pipeline (which makes it more of a pipeline state).

I.e. it is not obvious to me what is supposed to happen to the arrayed dynamic state. If the pre-existing dynamic state has different array size:
a) It is preserved including size (and next bound pipeline can use the elements past size)
b) It splices the array, keeping only the part that fits in the new size stated in pipeline creation
c) It considers the whole dynamic state invalid because of the wrong size and requires it to be set again.

Aside, it is also not obvious to me what non-dynamic state pipeline does to the dynamic state. The spec says it "overrides" it. Does it also over**write** it (, or resumes its previous state, or makes it undefined)?

**Comment by jeffbolznv** [comment]
I'm inclined to say that if the currently set dynamic state is not an exact match for what's in the newly bound pipeline, that entire dynamic state becomes invalid.

> Aside, it is also not obvious to me what non-dynamic state pipeline does to the dynamic state. The spec says it "overrides" it. Does it also overwrite it (, or resumes its previous state, or makes it undefined)?

I think this was meant to say the old dynamic values are lost and must be resent the next time a pipeline with dynamic state is bound.

**Comment by krOoze** [comment]
@jeffbolznv OK, that possibly needs some clarifications in the spec then.
(Also this stuff is "hidden" in the introductory Pipeline chapter. It could possibly use some esthetic changes too; its own chapter, some backlinks to it, maybe "pipeline dynamic state" term in the Glossary.)

Anyway, I got little side-tracked with previous post.
My point was I am no longer confident the proposed VUs in the OP fits the original intention of the spec. It seems sensible to set a dynamic state larger than the current `count`. And it even seems what current drivers and apps do despite the VU introduced by #235 ( e.g. [setting vieport before any pipeline](https://github.com/SaschaWillems/Vulkan/blob/be70aff2ae578971a575585f2e131d25fe53dd41/triangle/triangle.cpp#L294) despite the `VUID-vkCmdSetViewport-None-01221` ).

I should probably close this and make an Issue about potentially underspecified/conflicting pipeline dynamic state specification first.
