### ISSUE TITLE
VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT is not mentioned where needed

### ISSUE THREAD

**Issue by fredrikzetterman** [KhronosGroup/Vulkan-Docs#541]
In the documentation for vkCmdDrawIndexedIndirect and vkCmdDrawIndirect, there is no mention of any requirement for VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT to be set for the input buffer. The documentation for VkBufferUsageFlagBits however says it should be set: "VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT specifies that the buffer is suitable for passing as the buffer parameter to vkCmdDrawIndirect, vkCmdDrawIndexedIndirect, or vkCmdDispatchIndirect."

I presume that this flag needs to be set in buffers used for indirect draws?

**Comment by oddhack** [comment]
Both of these commands now have valid usage statements saying that buffer must have been created with the VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT set, though I don't recall when we added those. So closing this issue (unless there's something I'm missing here).
