### ISSUE TITLE
Nonexistent pDepthStencil in VkGraphicsPipelineCreateInfo VU

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#542]
There's this VU in `VkGraphicsPipelineCreateInfo`:

> If the depth bias clamping feature is not enabled, no element of the `pDynamicStates` member of `pDynamicState` is `VK_DYNAMIC_STATE_DEPTH_BIAS`, and the `depthBiasEnable` member of `pDepthStencil` is `VK_TRUE`, the `depthBiasClamp` member of `pDepthStencil` **must** be `0.0`

But `pDepthStencil` is not a thing. Probably means `pRasterizationState`.

**Comment by oddhack** [comment]
This should be resolved in the 1.0.64 spec update.
