### ISSUE TITLE
VkPipelineLayoutCreateInfo is missing valid usage for the maxDescriptorSet* limits

### ISSUE THREAD

**Issue by tomaka** [KhronosGroup/Vulkan-Docs#546]
The documentation of `VkPipelineLayoutCreateInfo` says, for example:

> The total number of descriptors of the type VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, and VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER accessible to any given shader stage across all elements of pSetLayouts must be less than or equal to VkPhysicalDeviceLimits::maxPerStageDescriptorStorageImages

Similarly it mentions all the `maxPerStageDescriptor*` limits.

However the documentation doesn't mention anything about the `maxDescriptorSet*` limits (`maxDescriptorSetSamplers`, `maxDescriptorSetUniformBuffers`, and so on). If I'm not mistaken they should also be there.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.63 spec update.
