### ISSUE TITLE
[Specification] OpImageFetch LOD operation needs clarification

### ISSUE THREAD

**Issue by Retrofractal** [KhronosGroup/Vulkan-Docs#548]
In the SPIR-V (1.2) specification (3.14 Image Operands), an optional _integer_ Lod operand is available for the OpImageFetch and OpImageSparseFetch operations. The Vulkan (1.0.59) specification (15.6.2) states that if the optional SPIR-V operand Lod is provided, the _floating point_ scalar coordinate is used according to the "Level-of-Detail Operation" (15.6.7 Scale Factor Operation, Level-Of-Detail Operation and Image Level(s) Selection). This section includes various sampler parameters, which are used to determine which image levels are selected. However, OpImageFetch and OpImageSparseFetch do not use a sampler (or a floating point Lod operand) and so it is unclear whether the aforementioned passages are directly applicable. In particular, the level of detail is only mentioned for instructions with either "ImplicitLod" or "ExplicitLod" in the name (15.1 Image Operations Overview).

In the OpenGL spec the level of detail calculation for texel fetches is described explicitly (11.1.3.2 Texel Fetches) and it forms parts of the input validation, in the sense that any attempt to read a mipmap level outside of the valid range will either be undefined, or if robust buffer access is enabled, will produce a defined out of bounds result (OpenGL ES specifies only undefined results). Vulkan lists its own set of validation conditions (15.3.1 Texel Input Validation Operations) but I am unable to find any explicit reference to the integer Lod operand and it doesn't appear to fall under the category of "integer texel coordinate".

Is the intention to maintain undefined behaviour for out of bounds texel fetch Lod or to apply implicit clamping based on the available mipmap levels?

**Comment by NicolBolas** [comment]
If I am not mistaken, the specification says:

> SPIR-V OpImageFetch, OpImageSparseFetch, OpImageRead, OpImageSparseRead, and OpImageWrite
instructions use integer texel coordinates. [...] Normalized coordinates are logically converted to unnormalized as part of image operations, and [link to 15.6] are only performed on normalized coordinates.

So nothing from 15.6 should apply to `OpImageFetch`. This includes computing the LOD from a floating-point value.

I haven't been able to find anything about the nature of the LOD value of `OpImageFetch` if it falls outside of the image view's min/max LOD range.

**Comment by Retrofractal** [comment]
So as it stands, the LOD calculation for `OpImageFetch` is essentially undocumented!

Curiously, the Lod operand description also refers to query instructions:
>  For queries and fetch operations, it must be an integer type scalar. 

There are no query operations, however, that use optional image operands.

The operation `OpImageQuerySizeLod` requires an integer LOD, but only states:
> Level of Detail is used to compute which mipmap level to query, as described in the API
specification.

Again, this operation doesn't use a sampler and there's no way to know for certain which _integer_ level of detail is actually required.

**Comment by gnl21** [comment]
> There are no query operations, however, that use optional image operands.

This is true. The "queries and" will be removed in a future revision of the spec.

> Again, this operation doesn't use a sampler and there's no way to know for certain which integer level of detail is actually required.

Thanks for reporting this. We'll add spec language for this to a future revision of the API spec. The intention is to have undefined behavior for out-of-range LODs. (For robust buffer access guarantees see #567). The LOD should be provided as an integer to the ImageOperands and it will be added to the image base level to select an LOD to sample from.

**Comment by Retrofractal** [comment]
Great, thanks for the clarification!

**Comment by oddhack** [comment]
This should be closed in the 1.0.65 spec update.
