### ISSUE TITLE
Support for customised internal reallocations?

### ISSUE THREAD

**Issue by elfring** [KhronosGroup/Vulkan-Docs#55]
The field "pfnReallocation" is described for [the data structure "VkAllocationCallbacks"](https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkAllocationCallbacks.html "Description for memory allocation callback functions") while I do not see a similar interface "PFN_vkInternalReallocationNotification" there.
Will there any need evolve to handle also "short-lived" internal reallocations anyhow?

**Comment by ratchetfreak** [comment]
Internal allocation is for when the driver needs to allocate memory that can be _executed_. This is more complex than normal data memory because of Data Execution Prevention. So the workgroup decided that the driver can simply call VirtualAlloc (and the equivalent on *nix) itself with the correct flags.

The Internal allocation callbacks just notify the application when those allocation happened.

**Comment by elfring** [comment]
>The Internal allocation callbacks just notify the application when those allocation happened.

Should the distinction between an allocation and a corresponding notification be better expressed in the affected description for this application programming interface?

**Comment by ratchetfreak** [comment]
[It's there](https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#PFN_vkInternalAllocationNotification)

> The type of pfnInternalAllocation is:
>[...]
> This is a purely informational callback.

**Comment by elfring** [comment]
Are there any more update candidates around information like the following?

```
…
pfnInternalAllocation
    A pointer to a function that is called to make short-lived internal allocations. 
pfnInternalFree
    A pointer to a function that is called to free internal allocations.
…
```

Would a description like the following be more appropriate?

```
…
pfnInternalAllocationNotification
    A pointer to a function that is called after a short-lived internal allocation was performed.
pfnInternalFreeNotification
    A pointer to a function that is called after an internal allocation was released.
…
```


Would anybody like to be notified only if anything was internally reallocated?

**Comment by NicolBolas** [comment]
This seems like a de-synchronization between the Vulkan spec and the man pages. If you [look at the specification](https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#memory-host), it is much more clear about the meaning of these functions.

The man pages should be updated accordingly.

**Comment by elfring** [comment]
The section "10.1. Host Memory" contains descriptions like the following.

```
…
* pfnInternalAllocation is a pointer to an application-defined function
  that is called by the implementation when the implementation makes
  internal allocations, …
* pfnInternalFree is a pointer to an application-defined function that is called
  by the implementation when the implementation frees internal allocations,
…
```

I do not see that a notification is mentioned there (besides the referenced data type). Should such a wording be usually interpreted in the way that an allocation and a corresponding release is performed by such callback functions?

**Comment by NicolBolas** [comment]
First, I think the language is quite clear. The function is called "when the implementation _makes_ internal allocations". This is very different from the prior functions, which are "memory allocation/ reallocation/free function". The documentation seems to make a distinction between functions that actually do the work and functions that are just used to inform the user that work has been done.

Second, the function pointer definitions in question do not in fact have a way to allocate or free memory. `PFN_vkInternalAllocationNotification` functions do not return pointers, and `PFN_vkInternalFreeNotification` functiosn are not given a pointer to free. Also notice the text "This is a purely informational callback." (which should also be applied to `FreeNotification`.

Overall, the specification seems quite clear on the meaning of these functions. The man page documentation simply needs to be updated accordingly.

**Comment by oddhack** [comment]
The ref pages are current with the spec as of the 1.0.20 spec update.
