### ISSUE TITLE
vulkan_ext.c's two function have overlapping undefined responsibilites

### ISSUE THREAD

**Issue by UPS7kYkHEPbZIucaqjje** [KhronosGroup/Vulkan-Docs#551]
// void vkExtInitInstance(VkInstance instance);
pfn_vkCreateDebugReportCallbackEXT = (PFN_vkCreateDebugReportCallbackEXT)vkGetInstanceProcAddr(instance, "vkCreateDebugReportCallbackEXT");

// void vkExtInitDevice(VkDevice device);
pfn_vkCreateDebugReportCallbackEXT = (PFN_vkCreateDebugReportCallbackEXT)vkGetDeviceProcAddr(device, "vkCreateDebugReportCallbackEXT");

According to this link, the code in the respective functions doesn't follow the standard at all
https://vulkan.lunarg.com/doc/view/1.0.57.0/windows/LoaderAndLayerInterface.html#user-content-instance-versus-device

vkExtInitDevice shouldn't be getting vkCreateDebugReportCallback

And this is just one of many examples.

**Comment by oddhack** [comment]
Assigned to @mtavenrath who owns the extension stub generators.

**Comment by timofonic** [comment]
@UPS7kYkHEPbZIucaqjje @oddhack @mtavenrath Any news?

**Comment by krOoze** [comment]
@oddhack Might be closed as no longer supported ([Vulkan-Docs/ext_loader/README.md](https://github.com/KhronosGroup/Vulkan-Docs/blob/master/src/ext_loader/README.md))?
