### ISSUE TITLE
Command buffer out of order execution

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-Docs#552]
The Vulkan specs (1.0.41) say:

> Command buffer submissions to a single queue respect submission order and other implicit
ordering guarantees, but otherwise may overlap or execute out of order.

"submission order" is a link to implicit ordering guarantees that essentially say commands are:

- Ordered by vkQueueSubmit, then
- Ordered by pSubmits of each of those calls, then
- Ordered by pCommandBuffers inside each of those submits, then
- Ordered in order of host recording.

What can actually be executed out of order then?

**Comment by krOoze** [comment]
Almost everything done by "action commands".

You are potentially confusing "submission order" and "execution order".

**Comment by TobiasHector** [comment]
Submission order doesn't actually make many guarantees in and of itself - the paragraph right after that listing of what determines the order describes what guarantees it makes:

> Action and synchronization commands recorded to a command buffer execute the
VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT pipeline stage in submission order - forming an implicit
execution dependency between this stage in each command.

Which is the only real ordering guarantee made by it directly.

There are other things based on it though:
- Synchronization commands divide execution based on submission order (stuff submitted before vs. after)
- Rasterization order makes guarantees for the purposes of depth testing, blending, etc.
- Image layout transitions performed as part of a VkImageMemoryBarrier structure are done in submission order

Anything else is up for re-ordering.

**Comment by krOoze** [comment]
@ShabbyX PS: Why are you reading/quoting old version of the spec.

@TobiasHector While I have you here, the thing you quote is a bit weird. Synchronization commands do not execute `VK_PIPELINE_STAGE_TOP_OF_PIPE`, I would think. Only for action commands the pipeline makes sense.

> - Image layout transitions performed as part of a VkImageMemoryBarrier structure are done in submission order

I don't think that's true. It should overlap with other stuff and it is specified with the "happens-after/before" in its own chapter in 6.1.1. Image Layout Transitions.

**Comment by TobiasHector** [comment]
> @TobiasHector While I have you here, the thing you quote is a bit weird. Synchronization commands do not execute VK_PIPELINE_STAGE_TOP_OF_PIPE, I would think. The pipeline makes sense only for action commands. Right?

This is definitely correct. I am afraid I can't remember the details of *why* very well, think it sort of mostly fell out as a consequence of how we'd written other parts of the spec. There may also be something to do with how the set/reset/wait event commands work but I'm afraid I can't remember.

The only real consequence of this is that you can do two synchronization commands one after the other and it guarantees that their submission has happened in order, which is to say... there's very little (basically nothing) guaranteed by it.

Synchronization commands basically execute TOP_OF_PIPE, <something not enumerated>, BOTTOM_OF_PIPE - and that's it.

**Comment by TobiasHector** [comment]
> I don't think that's true. It should overlap with other stuff and it is specified with the "happens-after/before" in its own chapter in 6.1.1. Image Layout Transitions.

See the description of VkImageMemoryBarrier:

> Layout transitions that are performed via image memory barriers execute in their entirety in
submission order, relative to other image layout transitions submitted to the same queue, including
those performed by render passes. In effect there is an implicit execution dependency from each
such layout transition to all layout transitions previously submitted to the same queue.

I have no real idea *why* this is there, it's been there since release day. I think I asked about it when rewriting the chapter, and I *think* it's something to do with memory aliasing but I am afraid that again, I can't remember. We couldn't remove it because it had the potential to subtly break people's apps.

**Comment by krOoze** [comment]
> Synchronization commands basically execute TOP_OF_PIPE, , BOTTOM_OF_PIPE - and that's it.

That's probably not a healthy way of describing it. I summed it up in #554, as not to derail this thread any more.

> [...]and I think it's something to do with memory aliasing but I am afraid that again [...]

That makes sense. Sounds like something that may aid aliasing. It would probably be better if these can overlap too; then again they probably can under the typical "as if" rule.

**Comment by TobiasHector** [comment]
> That's probably not a healthy way of describing it. I summed it up in #554, as not to derail this thread any more.

I disagree, but I'll argue with you about it in #554 :)

> That makes sense. Sounds like something that may aid aliasing. It would probably be better if drivers could overlap these too; then again they probably can under the typical "as if" rule.

Yea I wonder if anyone's taking the time to figure out if two image memory barriers refer to image subresources bound to the same memory or not :S I kind of hope not... if they are, we should probably add an explicit aliasing bit like renderpasses have. But I digress.

**Comment by TobiasHector** [comment]
@ShabbyX Apologies for the tangent (though I'm inclined to blame @krOoze ;)) - but did we answer your question?

**Comment by ShabbyX** [comment]
@krOoze I had an old version lying around. Hadn't realized it was that hold.

@TobiasHector yes you did (and the offshoot thread was informative as well). I indeed misread "submission order" as "execution order".
