### ISSUE TITLE
VK_AMD_mixed_attachment_samples extension is missing "type" attribute in vk.xml

### ISSUE THREAD

**Issue by yzsolt** [KhronosGroup/Vulkan-Docs#553]
According to the documentation, it is a device extension.
Additionally, I think the "type" attribute should be required for Vulkan extensions (based on the "supported" attribute), instead of the current optional ([described here](https://www.khronos.org/registry/vulkan/specs/1.0/registry.html#tag-extensions)).

**Comment by yzsolt** [comment]
I mean _attribute_ instead of property/tag, sorry.

**Comment by NicolBolas** [comment]
I would really suggest adopting my schema suggestion from issue #354. That way, you could have an automated way to validate whether these requirements are in the `vk.xml` before releasing it.

**Comment by oddhack** [comment]
This should be addressed in the 1.0.60 spec update
