### ISSUE TITLE
vkCmdWriteTimestamp spec confusion 

### ISSUE THREAD

**Issue by Jasper-Bekkers** [KhronosGroup/Vulkan-Docs#558]
The page for vkCmdWriteTimestamp and for vkCmdCopyQueryPoolResults say that:

> The VkCommandPool that commandBuffer was allocated from must support graphics, or compute operations.

However, section "16.5 Timestamp Queries" seems to slightly contradict this, stating:

>Timestamps are supported on any queue which reports a non-zero value for timestampValidBits via vkGetPhysicalDeviceQueueFamilyProperties.

However, both the NV and AMD drivers report timestampValidBits to be 64 on the transfer queue. Presumably because of this contradiction.

Ideally I'd like to see that timestampValidBits is used throughout the spec to indicate which queues support timestamps and which don't so that it's queryable at runtime. Allowing vendors that /do/ support timestamps on transfer queues to provide them (so I can display them in our internal benchmarking tools).

**Comment by drakos-amd** [comment]
There indeed seems to be an unnecessary valid usage condition on vkCmdWriteTimestamp being limited to queues that support graphics or compute operations, considering that there's already a valid usage condition requiring a non-zero timestampValidBits for the queue families supporting vkCmdWriteTimestamp. We'll look into resolving this.

However, vkCmdCopyQueryPoolResults support on queues does not depend on timestampValidBits and it's intentionally unsupported on transfer-only queues.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.63 spec update.
