### ISSUE TITLE
Additional data types for memory allocation callback functions

### ISSUE THREAD

**Issue by elfring** [KhronosGroup/Vulkan-Docs#56]
Internal functions are mentioned for [the data structure "VkAllocationCallbacks"](https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkAllocationCallbacks.html "Description for memory allocation callback functions").

How do you think about to make the shown distinction more explicit by a combination of corresponding data types?
Would you like to reuse types like the following?
* regular_allocation_callback
* internal_allocation_callback

**Comment by oddhack** [comment]
There's no interest inside Khronos in doing this at present.
