### ISSUE TITLE
fragment_mask.png broken in pdf spec

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#561]
`fragment_mask.png` is missing in the pdf spec having only placeholder text.
Found out compiling it myself. I get this error:

> asciidoctor: WARNING: could not embed image: /Vulkan-Docs/doc/specs/vulkan/images/fragment_mask.png; PNG uses unsupported interlace method

PS: It should be reauthored in svg as the rest.

**Comment by oddhack** [comment]
That's been fixed internally, and will show up in the next public update in a few days.
