### ISSUE TITLE
SPIR-V should be able to return pointers from functions

### ISSUE THREAD

**Issue by MaikKlein** [KhronosGroup/Vulkan-Docs#563]
I orginally asked this question on [stackoverflow](https://stackoverflow.com/questions/46276007/why-can-i-not-return-pointers-in-the-logical-adressing-model) but I thought that I should also post it here.

I can assign pointers

         %32 = OpVariable %_ptr_Function_v4float Function
         %33 = OpVariable %_ptr_Function__ptr_Function_v4float Function
               OpStore %33 %32

I can store pointers in structs and assign them with `OpAccessChain / OpStore`.

But I can not return pointers in functions. Why is that? 

As far as I know there is only `OpReturn`and `OpReturnValue`. If I try to return a pointer with `OpReturnValue` I get 

> error: 87: OpReturnValue value's type <id> '4' is a pointer, which is invalid in the Logical addressing model.

The workaround that I am currently doing is that I can return a struct that contains a pointer.

    // Rust syntax
    pub struct Ref<'a>{
        f: &'a f32
    }
    
    fn reference(f: &f32) -> Ref{
        Ref{
            f
        }
    }

      %_struct_8 = OpTypeStruct %_ptr_Function_float
      %9 = OpTypeFunction %_struct_8 %_ptr_Function_float
      %2 = OpFunction %_struct_8 None %9
     %10 = OpFunctionParameter %_ptr_Function_float
     %11 = OpLabel
     %13 = OpVariable %_ptr_Function__struct_8 Function
           OpBranch %5
      %5 = OpLabel
     %17 = OpInBoundsAccessChain %_ptr_Function__ptr_Function_float %13 %uint_0
           OpStore %17 %10
     %18 = OpLoad %_struct_8 %13
           OpReturnValue %18
           OpFunctionEnd

So why can't I return pointers in functions? Is that an oversight? Or should the SPIR-V above be illegal? `spirv-val` doesn't complain and the code actually runs in a Vulkan vertex shader.

**Comment by NicolBolas** [comment]
If there is an oversight, I would say that it's the ability to store pointers in aggregates in logical addressing modes at all. Indeed, part of the SPIR-V standard says:

> The Logical addressing model means pointers are abstract, having no physical size or numeric value. In this mode, pointers can only be created from existing objects, and they cannot be stored into an object.

That seems to fly in the face of being able to pass them to `OpStore`.

**Comment by krOoze** [comment]
Do not rely on potentially incomplete or buggy layers to test what is and isn't allowed.
[Universal Validation Rules](https://www.khronos.org/registry/spir-v/specs/1.2/SPIRV.html#_universal_validation_rules) chapter seems to define what is allowed. And to my reading it seems to prohibit creation of your `%33` variable.
