### ISSUE TITLE
vkUpdateDescriptorSetWithTemplateKHR descriptorUpdateTemplate parameter description

### ISSUE THREAD

**Issue by ville-h** [KhronosGroup/Vulkan-Docs#564]
In https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/html/vkspec.html#vkUpdateDescriptorSetWithTemplateKHR the description for `descriptorUpdateTemplate` uses the term "the application pointer" to refer to another parameter, rather than stating the parameter name explicitly. It should probably say `pData` explicitly instead.

**Comment by oddhack** [comment]
Seems straightforward. I will run it by the group. Thanks!

**Comment by oddhack** [comment]
This should be fixed in the 1.0.66 spec update.
