### ISSUE TITLE
Clarify warning on vkCmdWaitEvents

### ISSUE THREAD

**Issue by haasn** [KhronosGroup/Vulkan-Docs#570]
The [documentation](https://www.khronos.org/registry/vulkan/specs/1.0/man/html/vkCmdWaitEvents.html) notes:

> Applications should be careful to avoid race conditions when using events. There is no direct ordering guarantee between a vkCmdResetEvent command and a vkCmdWaitEvents command submitted after it, so some other execution dependency must be included between these commands (e.g. a semaphore).

This wording specifically mentions `vkCmdResetEvent`, unlike the previous note in that paragraph. It's not entirely clear to me whether or not this also applies to `vkCmdSetEvent`.

To clarify: is it legal to submit two command buffers at the same time to separate VkQueues, when those two command buffers access the shared common resource, using `vkCmdSetEvent` and `vkCmdWaitEvents` to order the access to this resource, with no extra semaphore between the two, assuming I have an external guarantee (e.g. via VkFence witness) that an event is reset prior to execution of both commands.

Or do I also need to include a semaphore to ensure that the command buffer containing `vkCmdSetEvent` will have finished by the relevant stage in which the other command buffer executes `vkCmdWaitEvents` to ensure it sees the event?

**Comment by krOoze** [comment]
>  It's not entirely clear to me whether or not this also applies to `vkCmdSetEvent`.

On that subject the specification says in the documentation of `vkCmdWaitEvents`:

> Event signal operations performed by `vkCmdSetEvent` that were previously submitted to the same queue are included in the first synchronization scope, if the logically latest pipeline stage in their `stageMask` parameter is logically earlier than or equal to the logically latest pipeline stage in `srcStageMask`.

**Comment by haasn** [comment]
> Event signal operations performed by vkCmdSetEvent that were previously submitted to the same queue are included in the first synchronization scope

What if they were submitted to a different queue?

**Comment by krOoze** [comment]
@haasn Two different queues act completely independently, no? How is that relevant here?

**Comment by haasn** [comment]
I'm just double checking, because the way this is worded implies to me that there's nothing stopping an event from being signalled across queues - the paragraph only refers to the special case of it being signaled from the same queue; and the other one following it only refers to the special case of it being signalled from the host. But there's no wording I can find that would prevent a VkEvent from getting signalled from a different queue; and no comment about needing an explicit semaphore to define a dependency between the command buffers in question, either. My question is simply: Is this indeed legal, or am I misunderstanding something entirely?

**Comment by krOoze** [comment]
@haasn 
The above quotes really do not say either way. They simply describe what the command does in its scope, which is a command queue context. As for any other `vkCmd*` the chapter does not repeat again what happens at the coarser context between queues, despite it also potentially influencing things. Inter-queue synchronization is described elsewhere.

If there were no other restrictions written in the spec, you should be able to signal in one queue and wait in another as long as you also provide an execution dependency ensuring the signalling operation happens-before the waiting operation. BUT there seems to be some extra restrictions:

 this VU of `vkQueueSubmit` says:

> Any calls to `vkCmdSetEvent`, `vkCmdResetEvent` or `vkCmdWaitEvents` that have been recorded into any of the command buffer elements of the `pCommandBuffers` member of any element of `pSubmits`, **must** not reference any `VkEvent` that is referenced by any of those commands in a command buffer that has been submitted to another queue and is still in the pending state.

So, if you want to signal an event in one queue and wait on it on another, you would have to `vkCmdSetEvent` on the one queue. Wait for the command buffer containing that to exit pending state (as it is written you pretty much need `VkFence` or `vkWait*`. And only then submit a command buffer that waits on the event. So unless it is a spec bug I would pretty much summed it as: no you cannot effectivelly use events across queues.

**Comment by haasn** [comment]
I see, thanks for the clarification. That's rather unfortunate, since it seems like a perfect fit for guarding access to common resources on a sub-command-buffer granularity.

The only work-around as far as I can tell is splitting up the command buffer into lots of tiny command buffers (~10-20 per frame) and having each of those sub-command-buffers signal individual semaphores for each shared resource. And that approach is slow, comes with overhead, and apparently deadlocks randomly on every driver I've tested.

**Comment by NicolBolas** [comment]
> That's rather unfortunate, since it seems like a perfect fit for guarding access to common resources on a sub-command-buffer granularity.

The reason semaphores exist as a distinct concept is to guard access to common resources across queues. If such things could be done by events, we wouldn't need semaphores at all. You could just stick events at the end of the command buffer you're going to submit, if you want to know when it's finished.

Or to put it another way, access to resources across queues is not expected to be able to work within a command buffer. That's not a concept Vulkan supports.

**Comment by haasn** [comment]
> If such things could be done by events, we wouldn't need semaphores at all.

That's a good point. I assume that means it was considered to make VkEvents cross-queue as well and deemed impossible, which is why VkSemaphores exist? In that case, this issue is irrelevant; and I will have to come up with some sort of my own abstraction to group semaphores and events into a common “signal” abstraction and try using events wherever semaphores would be overkill (same-queue scenario).

**Comment by TobiasHector** [comment]
NB: There's a clarification pending on the spec to make it more obvious that events can't be used across queues. And yes we did consider having them work across queues, but events and semaphores map differently on different HW/Platforms, so we ended up with different constructs for them.
