### ISSUE TITLE
VkBufferImageCopy valid usage editorial issue

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#575]
> If ***the the*** calling command’s VkImage parameter’s format is not a depth/stencil format, then bufferOffset must be a multiple of the format’s element size

Obviously, two "the"s are not necessary.

**Comment by krOoze** [comment]
@NicolBolas Actually there's "the the" like 4 times in the spec. I am gonna merge this one with #331 and sooner or later make a PR... If you come across more grammar or formatting problems add it to the list.

**Comment by oddhack** [comment]
We welcome the PR :-)
