### ISSUE TITLE
Performing ordinary work in an easy way

### ISSUE THREAD

**Issue by elfring** [KhronosGroup/Vulkan-Docs#58]
I imagine that the usual work submission can be achieved in an easier way by a specific software design if no extra allocation callback configuration will be needed.
I suggest to consider the introduction of the following function pattern where another callback function will be passed for the desired work execution.

```C
…
typedef
VkResult
(VKAPI_PTR* vkOrdinaryWorkOnItem)(VkItem* Item);
typedef
VkResult
(VKAPI_PTR* vkOrdinaryWorkOnItemWithUserData)
(VkItem* Item,
 void* UserData);

VkResult
vkPerformOrdinaryWorkItem(vkOrdinaryWorkOnItem WorkCallback);
VkResult
vkPerformOrdinaryWorkItemWithUserData(vkOrdinaryWorkOnItemWithUserData WorkCallback,
                                      void* UserData);
…
```

Can such an interface take care of calling the appropriate initialisation and finalisation function of the affected API item?

**Comment by ratchetfreak** [comment]
Why would vk*WorkItem even exist in the first place? All it would do is invoke the callback immediately. If it's supposed to wait on on a command buffer then you should be using a fence for that and waiting on/testing it yourself.

vulkan is not supposed to be a graphics framework but a rendering api around which you can create your framework.

**Comment by elfring** [comment]
How many extra software developments efforts can [the suggested function wrappers](https://en.wikipedia.org/wiki/Wrapper_function "Wrapping function calls") reduce eventually?

**Comment by ratchetfreak** [comment]
None. And it's not vulkan's job to reduce effort. 

If you still believe that this should be added then show me a use-case. Give me an example of how and where this should be used.

**Comment by elfring** [comment]
How many use case explanation do still need just for using a small collection of simple function wrappers for this API?

**Comment by ratchetfreak** [comment]
At least one and _you haven't given me one yet._

Any time you would call `vkPerformOrdinaryWorkItem(myWorkItem);` in your current format you could just as well do `myWorkItem();` directly.

Callbacks are useful in only a few places; 

1. The user code needs to be notified of an event which runs asynchronously. (This is what fences are for)

2. The user code needs to be executed on a particular thread under the control of the API. (Vulkan doesn't start its own threads)

3. The user code needs to provide information/resources to the api in a unpredictable manner. (Only allocations fall under this)

**Comment by elfring** [comment]
I am trying to point the usefulness out for a small function wrapper library. Callbacks have got more uses.

Example:
```C
…
VkResult
my_stuff(VkInstance* an_instance)
{
 /* Which further work should be performed here? */

 return VK_SUCCESS;
}
…
VkResult result = vkPerformOrdinaryWorkInstance(&my_stuff);
…
```

**Comment by ratchetfreak** [comment]
Then that should be in the wrapper library. It's not vulkan's job to create that wrapper library.

**Comment by elfring** [comment]
Can such an approach to [work with more callback functions](https://en.wikipedia.org/wiki/Callback_%28computer_programming%29 "Working with callback functions") (besides the memory allocation callbacks) become so useful that you wonder that it was not provided from the official beginning of this application programming interface?

**Comment by ratchetfreak** [comment]
Callback are not that useful. 

Also that example you used would not work because it assumes global state of which instance is to be used. Vulkan **explicitly** does not have any global state.

So the way it would work would be:

```C
VkResult
my_stuff(VkInstance* an_instance)
{
 /* Which further work should be performed here? */

 return VK_SUCCESS;
}
…
VkResult result = vkPerformOrdinaryWorkInstance(instance, &my_stuff);
```

and at that point you may as well do:

```C
VkResult result = my_stuff(instance);
```

**Comment by elfring** [comment]
The callback functions I propose can handle various context information.


>VkResult result = vkPerformOrdinaryWorkInstance(instance, &my_stuff);

The parameter "instance" is unnecessary at this place in my proposal because the function "my_stuff" has got access to other data that it might need.

**Comment by ratchetfreak** [comment]
But how would `vkPerformOrdinaryWorkInstance` know which `VkInstance` to pass to my_stuff?

**Comment by elfring** [comment]
The function "vkPerformOrdinaryWorkInstance" will call the function "vkCreateInstance" for you and will also perform the usual error handling as a service so that you do need to care any more about such details.

**Comment by ratchetfreak** [comment]
Again that sounds like something a **_entirely separate library_** should do. Not vulkan nor the bare metal binding.

**Comment by elfring** [comment]
- Can an application programming interface provide also a higher level service by default (or another evolving standard configuration)?
- Would you like to concentrate on the implementation of your own callback functions (instead of struggling with memory management functions from a new API)?

**Comment by oddhack** [comment]
Wrapper libraries are indeed going to be useful. We expect there will be a lot of them - implemented not by Khronos as part of the Vulkan API, where they explicitly do not belong, but by ISVs, IHVs, and independent developers, such as the validation layers that were implemented (primarily) by LunarG. If you have good ideas for wrappers, layers, etc. then you would be doing the developer community a service by coding them up and launching your own github project for that purpose. Or perhaps you can find an existing project to develop such layers and contribute to that. But we're not going to put convenience functions and utilities running in user space into the core API, because that is explicitly not part of its purpose.
