### ISSUE TITLE
[Enhancement][Extension] More explicit description of VK_ERROR_OUT_OF_POOL_MEMORY_KHR

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#582]
It would be nice to have more explicit description of `VK_ERROR_OUT_OF_POOL_MEMORY_KHR` of the `VK_KHR_maintenance1`.

Currently it says:

> If the allocation fails due to no more space in the descriptor pool, and not because of system or device memory exhaustion, then `VK_ERROR_OUT_OF_POOL_MEMORY_KHR` **must** be returned.

I think it would be nicer if it was explained explicitly in terms of `VkDescriptorPoolCreateInfo::maxSets` and contents of `VkDescriptorPoolCreateInfo::pPoolSizes`, and others if they could play a role here.

Current drivers seem to [act weirdly](https://forums.khronos.org/showthread.php/13576-Descriptor-pool-able-to-allocate-even-though-pool-should-be-empty), which may also be caused by misunderstanding of the spec.

**Comment by TobiasHector** [comment]
This error is properly documented in the Return Codes section of the spec - the function description simply dictates roughly when it is returned. Note that behaviour has changed here somewhat with KHR_maintenance2 compared to what it was in KHR_maintenance1.

You'll note there that there is a lot of "should" wording.

**Comment by krOoze** [comment]
> This error is properly documented in the Return Codes section of the spec.

Not that much better. For reference here it is:

> `VK_ERROR_OUT_OF_POOL_MEMORY_KHR` A pool memory allocation has failed. This **must** only be returned if no attempt to allocate host or device memory was made to accomodate the new allocation. If the failure was definitely due to fragmentation of the pool, `VK_ERROR_FRAGMENTED_POOL` **should** be returned instead.

Still no mention of `VkDescriptorPoolCreateInfo::maxSets` and/or `VkDescriptorPoolCreateInfo::pPoolSizes` (not that I would expect it in this particular place).

> Note that behaviour has changed here somewhat with KHR_maintenance2 compared to what it was in KHR_maintenance1.

Shouldn't matter. I probably read the `KHR_maintenance2` version, since I usually read the `1.0-extensions` version of the spec.

> You'll note there that there is a lot of "should" wording.

What? Where? There's a "must".

Anyway, point is the spec should probably say explicitly whether it allows Implementations to overalloc wrt `VkDescriptorPoolCreateInfo::maxSets` and `VkDescriptorPoolCreateInfo::pPoolSizes`, or not.

**Comment by TobiasHector** [comment]
Ah ok I was kind of looking for more clarification from you - wasn't 100% sure what the issue was, but it's obvious now.

It looks like we need to add some language to tie the "maxSets" and "pPoolSizes" values together with the error. Relatively easy to do I guess.

**Comment by TobiasHector** [comment]
> What? Where? There's a "must".

I specifically meant between FRAGMENTED_POOL and OUT_OF_POOL_MEMORY. For instance, you might return OOPM if the pool is fragmented and can no longer allocate a contiguous range for a given descriptor.

**Comment by TobiasHector** [comment]
Text being proposed is:

> If a call to fname:vkAllocateDescriptorSets would cause the number of total
descriptors in the pool to exceed the value of
slink:VkDescriptorPoolCreateInfo::pname:maxSets used to create
pname:pAllocateInfo->pname:descriptorPool, then the allocation may: fail
due to lack of space in the descriptor pool.
Similarly, the allocation may: fail due to lack of space if the call to
fname:vkAllocateDescriptorSets would cause the number of any given
descriptor type to exceed the sum of all the pname:descriptorCount members
of each element of slink:VkDescriptorPoolCreateInfo::pname:pPoolSizes with a
pname:member equal to that type.
If the allocation fails due to no more space in the descriptor pool, and not
because of system or device memory exhaustion, then
ename:VK_ERROR_OUT_OF_POOL_MEMORY_KHR must: be returned.

**Comment by krOoze** [comment]
Interesting. "may"s everywhere.

1) Considering it is largely non-specifying but informative ("may"), some of it could potentially be a Note.
2) It may potentially make more sense to describe it the other way around. E.g. "`vkAllocateDescriptorSets` may: succeed allocating more than `VkDescriptorPoolCreateInfo::maxSets` descriptor sets".
3) You seem to have it formatted already. In that case C `->` needs to be escaped in asciidoc (like so: `\->`)
4) Something about "sum of all the X members of each element of Y" feels weird to me. I read it like Y struct has multiple X values that I am supposed to sum.
5) Ad 2) I feel there should be something like:

> fname:vkAllocateDescriptorSets **must** [?**should**?] not fail with `VK_ERROR_OUT_OF_POOL_MEMORY_KHR ` if `VkDescriptorPoolCreateInfo::maxSets` is not exhausted, and if `VkDescriptorPoolCreateInfo::pPoolSizes` count for any type(s) is not exhausted.

**Comment by oddhack** [comment]
This should be closed in the 1.0.65 spec update. If not all of @krOoze's last issues were dealt with, please open a new issue.
