### ISSUE TITLE
Nonsense desc. below VkObjectTablePushConstantEntryNVX

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#583]
Parameter descriptions below `VkObjectTablePushConstantEntryNVX` refer to some parameters that are not in the struct (`layout` and `descriptorSet`), while the real parameter descriptions are missing.

**Comment by oddhack** [comment]
Assigned to @jeffbolznv as proxy for NVIDIA, but probably Christoph Kubisch should propose an internal MR to fix this, since he's tagged as the extension author.

**Comment by oddhack** [comment]
Christoph will take this issue. Unfortunately I don't think I can assign him to it as while he's an NV employee and part of Khronos, he's not a member of KhronosGroup on github.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.67 spec update.
