### ISSUE TITLE
VK_AMD_negative_viewport_height placeholder VU

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#584]
In `VkViewport` VU section it says:

- If the `VK_AMD_negative_viewport_height` extension is enabled, `height` **can** also be negative.

That's not really an orthogonal statement to the other VUs. "can" statements does not belong in this section.

**Comment by oddhack** [comment]
Yes, there should be two different VUs controlled by conditionalized language on the extension name allowing this, or not. Want to propose the PR?
