### ISSUE TITLE
Editorial issue (section 5.2)

### ISSUE THREAD

**Issue by AlexeyKryshen** [KhronosGroup/Vulkan-Docs#59]
In the section 5.2 (**Command Buffer Lifetime**), in description of `vkAllocateCommandBuffers`

> - `pAllocateInfo` is an instance of the `VkCommandBufferAllocateInfo` structure which defines additional information about creating the pool.

"... the pool." seems to be typo and actually should be "... the command buffers."

**Comment by oddhack** [comment]
Thanks. Will fix in one of the upcoming weekly-ish spec updates.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.6 spec update.
