### ISSUE TITLE
[Specification] Semaphore signal operations should include all batches, not only previously

### ISSUE THREAD

**Issue by axinging** [KhronosGroup/Vulkan-Docs#594]
In 6.4.1. Semaphore Signaling
https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#synchronization-semaphores:
"Semaphore signal operations that are defined by vkQueueSubmit additionally include all batches previously submitted to the same queue via vkQueueSubmit, "

Think about two threads, they both call vkQueueSubmit with the same Semaphore.  The memory dependency is cmds of thread 2 depends on the cmds of thread 1. It has two possibilities ( cmds of thread i shorted as cmds i ):
1),  cmds 1 arrives first:
     cmds 1 executes; cmds 2 executes; 
In this case, cmds 1 is previously submitted.  This is consistent with the spec's "previously submitted".

 2),  cmds 2 arrives first:
     cmds 2 wait ; cmds 1 executes;  cmds 2 executes;
In this case, cmds 1 is the later submitted one,  cmds 2 is the previously submitted.  This seems not align with the spec, because Semaphore signal operations wake up the latter submitted cmds.

Am I missing something?

**Comment by TobiasHector** [comment]
You're running into all sorts of data races here (i.e. undefined behaviour), but I'll focus on the one which is really the crux of your issue:

You can't submit to the same queue from multiple threads at the same time (the queue parameter is tagged as `externally synchronized`), so you'd need to put down a mutex or other CPU-side scheduling mechanism to guarantee the one submit call has completed before the other one starts.
Once you've got that scheduling mechanism, you then have a defined order - whichever vkQueueSubmit call completed first has the batches that were submitted first.

**Comment by axinging** [comment]
Thanks. Closed.
