### ISSUE TITLE
Please clarify GL_KHR_vulkan_glsl's interaction with storage image format qualifiers

### ISSUE THREAD

**Issue by haasn** [KhronosGroup/Vulkan-Docs#596]
Storage images in GLSL can have associated [storage qualifiers](https://www.khronos.org/opengl/wiki/Layout_Image_Format#Image_formats). The [ARB_shader_image_load_store specification](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_shader_image_load_store.txt) gives a full list of these + their mapping to OpenGL image formats.

I see no mention of any change to this table in the [GL_KHR_vulkan_glsl](https://www.khronos.org/registry/vulkan/specs/misc/GL_KHR_vulkan_glsl.txt) specification, so one can only assume they apply 1:1.

Despite this, there appears to me the (hypothetical?) possibility for implementations to advertise VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT for VkFormats which have no corresponding entry on this list, and would therefore be impossible to assign a storage format qualifier in legal GLSL, even under GL_KHR_vulkan_glsl semantics. (For example, `rgb10_a2i` would be an example of a VkFormat which exists, and would have an obvious analog following the same scheme, but does not appear on this list. For another example, formats like `r5_g6_b5` could be plausibly supported by actual hardware in the same way that `r11_g11_b10` formats are)

Is this intended, and if not, is it a bug?

**Comment by haasn** [comment]
I had a look at the [SPIR-V specification](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#OpTypeImage) and it seems like SPIR-V inherits these same exact storage qualifiers for `OpTypeImage`. That's at least consistent with GL_KHR_vulkan_glsl, although it raises the equivalent question of what `OpTypeImage` format to use for storage images with VkFormats not on this list.

**Comment by NicolBolas** [comment]
> That's at least consistent with GL_KHR_vulkan_glsl, although it raises the equivalent question of what OpTypeImage format to use for storage images with VkFormats not on this list.

But that's a question the standard answers: only formats on that list can be used with image load/store. OpenGL has a similar list, and only internal formats on that list can be used in image load/store operations.

If your implementation supports `VK_FORMAT_A2R10G10B10_SINT_PACK32`, and you want to use that in an image load/store operation, you have to create a `VK_FORMAT_A2R10G10B10_UINT_PACK32` view of that image in order to use it in load/store.

**Comment by haasn** [comment]
Ah, that makes sense - I forgot you could create a VkImageView of a different type and use that as a storage image.

**Comment by haasn** [comment]
Incidentally, it seems like this is not a hypothetical case: RADV on Polaris GPUs advertises VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT for some formats such as VK_FORMAT_R4G4B4A4_UNORM_PACK16 which have no obvious corresponding SPIR-V/GLSL image format type. In other words, I can't specify "rgba4" as the image format because it's not listed on the table, so I have to use a VkImageView.

I can't answer the question of whether or not it would make sense to extend this list to include "rgba4" directly, though.

**Comment by NicolBolas** [comment]
If you're [referring to this implementation](http://vulkan.gpuinfo.org/displayreport.php?id=2089#features), it also supports the `shaderStorageImageWrite/ReadWithoutFormat` features. These allow you to not specify the format in the shader, and therefore, the shader-based format restrictions are not a restriction.

Except for atomic operations where they're still needed. But my point is that you can use storage images of those formats just fine.
