### ISSUE TITLE
Unclear language for transitioning away from VK_IMAGE_LAYOUT_PRESENT_SRC_KHR 

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/Vulkan-Docs#607]
After vkAcquireNextImageKHR, the application is supposed to transition from VK_IMAGE_LAYOUT_PRESENT_SRC_KHR to a layout like VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL for rendering.

My understanding is that the idiomatic way to do that is to transition as part of the render pass, but "29.6. WSI Swapchain" states:

> The vkCmdWaitEvents or vkCmdPipelineBarrier used to transition the image away from VK_IMAGE_LAYOUT_PRESENT_SRC_KHR layout must have dstStageMask and dstAccessMask parameters set based on the next use of the image. The application must use implicit ordering guarantees and execution dependencies to prevent the image transition from occurring before the semaphore passed to vkAcquireNextImageKHR has signaled.

It would be nice to clarify the spec to make it more obvious that you are not required to use any of these commands to transition from VK_IMAGE_LAYOUT_PRESENT_SRC_KHR if a render pass is doing that - my initial understanding upon reading that part was that I would *have* to use vkCmdPipelineBarrier to do the transition outside of a pass.

**Comment by TobiasHector** [comment]
I've proposed language to swap that paragraph (and the following note) to be:

> The application must: ensure that the image layout transition happens-after
pname:semaphore is signalled by fname:vkAcquireNextImageKHR.
>
> Note:
> When the presentable image will be accessed by some stage [eq]#S#, the
recommended idiom for ensuring the semaphore signals before the transition
occurs is:
>
>  * The slink:VkSubmitInfo used to submit the image layout transition for
    execution includes pname:semaphore in its pname:pWaitSemaphores member,
    with the corresponding element of pname:pWaitDstStageMask including
    [eq]#S#.
>  * The <<synchronization, synchronization command>> that performs the
    image layout transition includes [eq]#S# in both the pname:srcStageMask
    and pname:dstStageMask.
>
> This will ensure that the image layout transition happens-after [eq]#S#.

(no good way to translate notes to Markdown but hopefully that's clear enough?)

Will go through a few rounds of feedback still but hopefully that is better???

**Comment by ratchetfreak** [comment]
So when doing the transition as part of the renderpass, a subpass dependency from External to which ever pass you write to the image is still required.

**Comment by krOoze** [comment]
TBH I don't like the paragraph (old, or the proposed one):

1) It assumes there **must** (RFC!) be layout transition. That is not true. The app may wish to quit, or perhaps re-present the same image (i.e. leaving the layout be).

2) It does not account for `VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR`.

3) Feels like a wrong place to teach about synchronization.

4) The `vkAcquireNextImage` description is already too long, and this paragraph seems to only repeat what is said above many times, e.g. the:

> The presentation engine **may** not have finished reading from the image at the time it is acquired, so the application **must** use `semaphore` and/or `fence` to ensure that the image layout and contents are not modified until the presentation engine reads have completed.

I propose removing the paragraph completely.

**Comment by TobiasHector** [comment]
> So when doing the transition as part of the renderpass, a subpass dependency from External to which ever pass you write to the image is still required.

Yea you need to do the transition *somewhere* (subject to the conditions pointed out by @krOoze), which is clarified more in a different part of the text, but it does need to be done. This change basically just points you to the place where how it might be done is defined, rather than trying to define it on its own.

@krOoze 
> TBH I don't like the paragraph (old, or the proposed one):

Honestly I could live without the paragraph AND the note - I mean it's really a hangover from when the synchronization model was poorly defined and it needed spelling out everywhere. It just would read a bit weirdly compared to the rest of the chapter if I did that, which is why I didn't outright remove it. I'll float the idea on the MR though, because really you're right.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.66 spec update.
