### ISSUE TITLE
[Extension] Definition of structures missing

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#612]
Definition of the
`VkBindImageMemoryDeviceGroupInfoKHX`,
`VkBindImagePlaneMemoryInfoKHR`,
`VkBindImageMemorySwapchainInfoKHX`,
`VkImageSparseMemoryRequirementsInfo2KHR`,
`VkSparseImageMemoryRequirements2KHR` and
`VkShaderInfoTypeAMD` (#597)
structure is missing in the specification.

`vkGetImageSparseMemoryRequirements2KHR` command definition is also missing.

`VkShaderResourceUsageAMD` is missing as added in the extension appendix.

**Comment by Qining** [comment]
+1, same issue here

**Comment by Qining** [comment]
Also missing the document for `vkGetImageSparseMemoryRequirements2KHR`

**Comment by oddhack** [comment]
I see there's a misspelled ifdef::VK_KHR_device_group in a couple of places that's the cause of most of this. AMD appears not to have added spec language to go with their extension, as well.

**Comment by oddhack** [comment]
The BindImage* interfaces should be present in the 1.0.66 spec update. The others require action by the extension authors to actually include spec language about them, which is underway internally.

**Comment by timofonic** [comment]
@krOoze @Qining @oddhack Any news?

**Comment by krOoze** [comment]
@timofonic All fixed, except `VkShaderInfoTypeAMD` (#597), and `VkShaderResourceUsageAMD` missing in extension appendix.

BTW: might make more sense in the future to autogenerate the extension appendix list of added interfaces...

**Comment by krOoze** [comment]
@jaakkoamd `VkShaderInfoTypeAMD` still missing

**Comment by krOoze** [comment]
Last remaining item apparently fixed in 1.1.93.
