### ISSUE TITLE
Wrong revision date for VK_AMD_gpu_shader_half_float extension

### ISSUE THREAD

**Issue by polarina** [KhronosGroup/Vulkan-Docs#617]
The revision history for the `VK_AMD_gpu_shader_half_float` extension contains a date that has not yet passed.

```
    Revision 1, 2019-09-21 (Dominik Witczak)
        Initial draft
```

**Comment by oddhack** [comment]
Assigned to @DominikWitczakAMD

**Comment by krOoze** [comment]
@timofonic Yes, we discovered AMD was cheating, and we send time-cops after them.

**Comment by oddhack** [comment]
This will be fixed in the next public spec update.
