### ISSUE TITLE
Wrong issues referenced in 1.0.41 changelog wrt render pass compatibility

### ISSUE THREAD

**Issue by polarina** [KhronosGroup/Vulkan-Docs#618]
The [ChangeLog for Vulkan version 1.0.41](https://github.com/KhronosGroup/Vulkan-Docs/blob/c0f5633c7f34e98e80e041bfab8282bd906473bb/ChangeLog.txt#L1162) says:

>   * Clarify render pass compatibility in different usage scenarios (public
> issues 303 and 304).

These should be issues #403 and #404.

**Comment by oddhack** [comment]
Thanks. I've fixed this internally and it will show up on github/registry next time we do a public spec update.
