### ISSUE TITLE
vk.xml v1.0.66: Wrong sType for struct VkPhysicalDeviceExternalMemoryHostPropertiesEXT

### ISSUE THREAD

**Issue by ParticlePeter** [KhronosGroup/Vulkan-Docs#625]
vk.xml line 2661 specifies the VkStructureType sType of the mentioned struct as: VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_HOST_PROPERTIES_EXT

but the enum specified for this struct at line 7481 is:
VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_MEMORY_HOST_PROPERTIES_EXT

Those two must be identical, I assume the latter is the right one in respect to VkStructureType naming convention.

**Comment by oddhack** [comment]
Yes, good catch. We'll fix this in the next public update.

**Comment by oddhack** [comment]
Hm, actually we already fixed it and I just didn't track it in the change log. Go ahead and re-open if you're still seeing this problem.

**Comment by ParticlePeter** [comment]
Wanted to close it just right now myself. It was fixed after v1.0.66 on Dec-01 with this commit 2f5bc66d7adcf5bda62bb2e3666e36992b93792d
