### ISSUE TITLE
vkAcquireNextImageKHR synchronization description issues

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#626]
This is basically followup of discussion in #607.
Also raised in https://github.com/KhronosGroup/Vulkan-Docs/commit/64fa8ef4df3bff37214e717abe490f7ea7ea44b0#r25899350 .

The sentence that appeared in 1.0.66 replacing older language is:

> The application **must** ensure that the image layout transition happens-after `semaphore` is signalled by `vkAcquireNextImageKHR`.

1) Styleguide prescribes "signaled" (US spelling).

2) `vkAcquireNextImageKHR` may use `fence`, and `semaphore` can be `VK_NULL_HANDLE`. This sentence does not take this into account.

3) It refers to some unknown "the image layout transition". Also assumes there always must be a layout transition.

4) It seems to describe what is already said about 3-4x below the `vkAcquireNextImageKHR`. This section of text is already too long. This information should be unified a bit in a single paragraph.

5) There is a Note below. It may be nice for new developers, but is it necessary to have it in a specification? It seems like a symptom that `vkAcquireNextImageKHR` synchronization is not well described in the spec and subject to misinterpretation.

**Comment by polarina** [comment]
> 3. It refers to some unknown "the image layout transition". Also assumes there always must be a layout transition.

There must always be a layout transition.

The specification says that all images acquired through `vkAcquireNextImageKHR` **must** be transitioned away from the `PRESENT_SRC` layout, even if the application later decides not to use the image.

The "Image Layouts" chapter says:
> `VK_IMAGE_LAYOUT_PRESENT_SRC_KHR` must only be used for presenting a presentable image for display. A swapchain’s image **must** be transitioned to this layout before calling `vkQueuePresentKHR`, and **must** be transitioned away from this layout after calling `vkAcquireNextImageKHR`.

**Comment by krOoze** [comment]
@polarina I know what the spec says. Point is it seems unreasonable restriction. And it assumes more than you quote.

Consider this:
1) I acquire images.
2) App decides to quit.
3) I would have to transition all the acquired images.
4) App quits.

Sounds like nonsense.

The intention seems to be that it must be `VK_IMAGE_LAYOUT_PRESENT_SRC_KHR` for `vkQueuePresent` and anything else for non-`vkQueuePresent` use.

Thanks for that quote. If it is found to be a nonsense, it is also a place where it needs to be adjusted.

**Comment by TobiasHector** [comment]
> There must always be a layout transition.

This is definitely not intended when you're destroying objects. Sorry that I messed this up so much - it sort of sat unreviewed for a little while and then "just" went in. I can to a patch fix again to sort out most of these issues, though as you point out @krOoze, this text is waaaayyy too long. There's a lot of extraneous "how do you practically use this" detail which just ends up repeating things from elsewhere.

> There is a Note below. It may be nice for new developers, but is it necessary to have it in a specification? It seems like a symptom that vkAcquireNextImageKHR synchronization is not well described in the spec and subject to misinterpretation.

It is a symptom sure, though even experienced developers are falling over on this one at the moment, so I have no intention of removing it right now. If the section gets a full cleanup then we can consider removing it or moving it elsewhere.

**Comment by TobiasHector** [comment]
There's an internal change in review to fix this up, which did end up including a substantial rework of vkAcquireNextImageKHR's description, so there's potentially that to look forward to.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.69 spec update.
