### ISSUE TITLE
Broken VU in vkCmdCopyImage

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#627]
1.0.66 introduced some bug here in `vkCmdCopyImage`:
https://github.com/KhronosGroup/Vulkan-Docs/commit/64fa8ef4df3bff37214e717abe490f7ea7ea44b0#diff-54b1cfd13f7f681a8c6b20c308c9a564L360

The bullet point seem to have been accidentally deleted, and so the VUID was not regenerated either.

**Comment by oddhack** [comment]
I'm unclear which VU you're referring to, or if the problem persists in the 1.1 spec. If the problem still exists, could you provide the text of the affected VU, so I can track it down? Thanks.

**Comment by krOoze** [comment]
You just need to follow the link which highlights exactly the affected line.

It seems to still be a problem in 1.1: https://github.com/KhronosGroup/Vulkan-Docs/blob/master/doc/specs/vulkan/chapters/copies.txt#L371
Note the missing bullet point and so no VUID label either on that VU.

**Comment by krOoze** [comment]
Nevermind, the author clearly meant to only delete the VUID label and not the bullet.
I can just PR it.

**Comment by oddhack** [comment]
I've already fixed this internally and it will show up in the next update, probably at the end of this week.
