### ISSUE TITLE
Vanilla spec has *_KHR in VkGraphicsPipelineCreateInfo

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#628]
In `VkGraphicsPipelineCreateInfo` VU section has `VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL_KHR`
even if `VK_KHR_maintenance2` is not enabled in build.

It was introduced in 1.0.66 here, where it is clearly in `ifndef` block:
https://github.com/KhronosGroup/Vulkan-Docs/commit/64fa8ef4df3bff37214e717abe490f7ea7ea44b0#diff-2ac583426d5e410b6ffdcc7cc9c77ae4R588

**Comment by oddhack** [comment]
We'll fix this in the next spec update. We had to duplicate / simplify for different paths some of the VUs that had imbedded conditionals, which the VU extractor doesn't support, and this wasn't done correctly.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.67 spec update.
