### ISSUE TITLE
Description for VK_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE references extension by wrong name

### ISSUE THREAD

**Issue by polarina** [KhronosGroup/Vulkan-Docs#629]
The description for `VK_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE` (part of `VkSamplerAddressMode`) says:

> `VK_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE` specifies that the mirror clamp to edge wrap mode will be used. This is only valid if the `VK_KHR_mirror_clamp_to_edge` extension is enabled.

The extension's name is `VK_KHR_sampler_mirror_clamp_to_edge`.

**Comment by krOoze** [comment]
#600 fixes that. Apparently I forgot to cherry-pick it for #603...
