### ISSUE TITLE
Are extensions compatible?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#638]
Are extensions compatible with core and other extension? E.g. can program written in core run as intended no matter what extensions are enabled?

It seemed to me that it should be so, but the chapters discussing extensions does not seem to say exactly.

**Comment by NicolBolas** [comment]
Actually, this is already defined in Vulkan's [Procedures and Conventions document](https://www.khronos.org/registry/vulkan/specs/1.0/styleguide.html). From the section "General Rules/Guidelines":

> Extensions must be strictly additive and backwards-compatible. That is, extensions must not remove existing functionality, or change existing default behaviors. A Vulkan implementation may support any combination of extensions, but applications written using only the core API, or a subset of the supported extensions, must continue to work in such an implementation without changes in behavior.

This is not a normative part of the standard; it is instead a guideline as to how to design extensions. I don't think we need it to be an actual part of the standard.

**Comment by krOoze** [comment]
> This is not a normative part of the standard; it is instead a guideline as to how to design extensions. I don't think we need it to be an actual part of the standard.

I think it is relevant to all Vulkan audiences, and so be in the specification.
I would even argue it should be in the first sentence\paragraph explaining what extensions are.

**Comment by TomOlson** [comment]
Agreed that having the style guide make normative statements about things like this is a little weird - if it does, it should probably do it by quoting the spec.  To make life interesting, this rule is already broken by VK_AMD_negative_viewport_height and VK_KHR_maintenance1 - the VU says you can't enable both simultaneously.  So we want compatibility to be the norm, but also need to allow for exceptions. We'll look at this.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.68 spec update.
