### ISSUE TITLE
LOD bias clamping

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#64]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#_scale_factor_operation_level_of_detail_operation_and_image_level_s_selection says:

>     \lambda'(x,y) & = \lambda_{base} + \operatorname{clamp}(sampler.bias + shaderOp.bias) \\

What min/max values is it clamping to?

(OpenGL defines the clamping in prose on the same page, but I can't find it anywhere in Vulkan.)

**Comment by oddhack** [comment]
I am pretty sure it's VkPhysicalDeviceLimits.maxSamplerLodBias as defined elsewhere, but this does need to add a reference. Thanks!

**Comment by oddhack** [comment]
Done in the 1.0.5 spec update.
