### ISSUE TITLE
[Validity] VK_FORMAT_FEATURE_STORAGE_IMAGE_ATOMIC_BIT VU missing

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#640]
`VK_FORMAT_FEATURE_STORAGE_IMAGE_ATOMIC_BIT` is not in any VU section in the specification. That is probably wrong.

**Comment by NicolBolas** [comment]
If there is to be a VU about it, there is at least some information on it. The specification says:

> Storage image declarations **must** specify the image format in the shader if the variable is used for
atomic operations.

Given that, a VU rule can key off of the specified image format for such a variable.

**Comment by krOoze** [comment]
@NicolBolas The format of the bound image view would not suffice?

**Comment by TobiasHector** [comment]
I think the ATOMIC bits are somewhat special since the validation is based on the use of a particular op code in the SPIR-V, rather than anything in the API. We've got similar language for this elsewhere though, e.g. for unnormalised coordinates on all the draw/dispatch commands:

> * If any VkSampler object that is accessed from a shader by the VkPipeline currently bound to VK_PIPELINE_BIND_POINT_GRAPHICS uses unnormalized coordinates, it must not be used with any of the SPIR-V OpImageSample* or OpImageSparseSample* instructions that includes a LOD bias or any offset values, in any shader stage

We could have similar VU for the atomic features?

**Comment by oddhack** [comment]
We had originally intended to ask @krOoze to propose the VU, but weren't clear that's what we were suggesting. @krOoze if this is still of interest, please feel free to suggest a PR in line with @ghost's comments.

**Comment by Tobski** [comment]
@krOoze please hold off - I realised this change would conflict with a fairly large internal change I have that's nearly ready to land. I've (partially) incorporated this internally for now, and will take on the rest soon.

**Comment by Tobski** [comment]
ISTM this got fixed at some point whilst I was tinkering but I forgot to close the external bug. All the draw/dispatch commands now have VU about the atomic feature, and the feature is now described properly. Closing, but feel free to reopen or raise a new issue if you feel there's something left to do here...
