### ISSUE TITLE
Conservative Rasterization for graphics pipelines? 

### ISSUE THREAD

**Issue by elviras9t** [KhronosGroup/Vulkan-Docs#646]
What about conservative rasterization support for Vulkan API?
As I know, this feature supported by main vendors Intel, AMD (Vega), NVidia. I don't know about support by mobile vendors.

**Comment by pdaniell-nv** [comment]
Thanks for your interest in new Vulkan features! There is an EXT extension for conservative raster that can be supported by several vendors that should be released fairly soon.

**Comment by pdaniell-nv** [comment]
The latest Vulkan 1.0.67 specification has a new VK_EXT_conservative_rasterization extension:
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_EXT_conservative_rasterization

If you would like to play with it, you can use the new NVIDIA Vulkan beta driver from here:
https://developer.nvidia.com/vulkan-driver
