### ISSUE TITLE
vkCmdUpdateBuffer dataSize limit

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#65]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#clears-updating-buffers says:

> dataSize must be less than or equal to 65536 bytes.

and:

> * The value of dataSize must be less than 65536

They should be stating consistent limits.

**Comment by oddhack** [comment]
We'll sort out which it is. Good catch!

**Comment by oddhack** [comment]
Fixed in 1.0.4 updates.
