### ISSUE TITLE
Sentence refering to VkCommandBufferAllocateInfo::flags which does not exist

### ISSUE THREAD

**Issue by Gaspard--** [KhronosGroup/Vulkan-Docs#651]
Seems like a minor typo, unless I'm missing anything: https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VkCommandBufferAllocateInfo

_Possible values of VkCommandBufferAllocateInfo::**flags**, specifying the command buffer level, are:_

should probably read:

_Possible values of VkCommandBufferAllocateInfo::**level**, specifying the command buffer level, are:_

since `VkCommandBufferAllocateInfo::flags` is not specified in the above structure.

I browsed the issues I didn't find any mention of this. Hope I'm not wasting your time.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.68 spec update.
