### ISSUE TITLE
Vanilla spec still has some *_KHR

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#652]
- in `VkImageSubresourceRange` VU
- In Note of the "30. Features, Limits, and Formats" chapter
- In the table of "Window System-Specific Header Control" section

**Comment by oddhack** [comment]
The first is a typo which I'll fix. While it's unfortunate that the extension references in the other two cases are dead internal links, they're still useful information about the respective extensions involved. I'll see if people feel like going to the trouble of special-casing them for a 1.0-only spec.

**Comment by oddhack** [comment]
This should be addressed in the 1.0.68 spec update. As I noted above, a couple of the names have been left intact because they are relevant information to people using extensions, even though they're dead links in the core-only spec. Special-casing them is messy so a warning note was added.
