### ISSUE TITLE
Can "packed" rowLength/bufferImageHeight be used on transfer queues with minTransferGranularity != (1, 1, 1)?

### ISSUE THREAD

**Issue by Themaister** [KhronosGroup/Vulkan-Docs#654]
Spec says that bufferImageHeight and rowLength for CopyBufferImage must align to minTransferGranularity.

However, the spec says that "0" are special cases, where it will treat the buffer data as "tightly packed".
Based on the snippet in the spec rowLength/bufferImageHeight then inherit width/height of the copy extent.

Does it mean the inherited value must align, or does the provided value "0" have to align? (I sure hope it's the latter, or we will have to pad out buffers in memory before making a copy ...). There is a special case in the spec if you upload where (x + extent.width == image width) and similar for height ... 

What about the case with minImageGranularity == (0, 0, 0)? How can rowLength/bufferImageHeight align to 0?

**Comment by krOoze** [comment]
Yeah, the spec could be more explicit.

I would add it is not exactly obvious how `bufferOffset` is compared against the `minImageTransferGranularity`.

I think even layers have this wrong. What they do is only compare all three `bufferOffset`, `bufferRowLength` and `bufferImageHeight` against the `minImageTransferGranularity.width`.

> Does it mean the inherited value must align, or does the provided value "0" have to align? (I sure hope it's the latter, or we will have to pad out buffers in memory before making a copy ...).

I would say (obviously) the former. `0` is only a placeholder for `imageExtent.width` or `imageExtent.height`.

> What about the case with minImageGranularity == (0, 0, 0)? How can rowLength/bufferImageHeight align to 0?

I would guess `bufferOffset` must be `0`, and `bufferRowLength` and `bufferImageHeight` must be either `0` or equal to `imageExtent`.

**Comment by jeffbolznv** [comment]
> Spec says that bufferImageHeight and rowLength for CopyBufferImage must align to minTransferGranularity.

Where does it say that? minImageTransferGranularity is intended to restrict the subregion of the image that can be read/written, because the image may be swizzled in a way that a DMA engine cannot interpret. It shouldn't restrict the shape of the data in buffer memory. Is there a validation layer bug here? I think there's also a spec bug since there are no VUs for minImageTransferGranularity.

**Comment by krOoze** [comment]
@jeffbolznv It says so in the `VkBufferImageCopy` VU section ([VUID-VkBufferImageCopy-bufferOffset-00210](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkBufferImageCopy-bufferOffset-00210)):

> `bufferOffset`, `bufferRowLength`, `bufferImageHeight` and all members of `imageOffset` and `imageExtent` **must** respect the image transfer granularity requirements of the queue family that it will be submitted against, as described in _Physical Device Enumeration_

**Comment by jeffbolznv** [comment]
The rules in Physical Device Enumeration say nothing about bufferOffset/bufferRowLength or bufferImageHeight, they are only about subranges of an image. IMO that VU is wrong and would be correct if we just remove "bufferOffset, bufferRowLength, bufferImageHeight and ". I've filed an internal issue to work this out.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.69 spec update.
