### ISSUE TITLE
Enum values and extensions interaction

### ISSUE THREAD

**Issue by msiglreith** [KhronosGroup/Vulkan-Docs#656]
(I couldn't find anything about this in the specification.)

Are the return values supposed to only return enum variants of extensions, when the actual extension is enabled?
For example, if a device support `VK_KHR_sampler_ycbcr_conversion` and the extension is not enabled on instance creation, could a `vkGetPhysicalDeviceSurfaceFormatsKHR` call return VkFormat values from the aforementioned extension?

**Comment by krOoze** [comment]
It is allowed for the implementation to return extended enums even if that extension is not enabled. Of course, you are still not allowed to used those enums (as an application).

**Comment by msiglreith** [comment]
Ok, thanks for the quick response!
