### ISSUE TITLE
Data type deduction for VkFormat in vk.xml

### ISSUE THREAD

**Issue by Sairony** [KhronosGroup/Vulkan-Docs#658]
Would be nice if vk.xml contained data for deducing the underlying arity & type of VkFormat, where possible. For example something along the lines of: &lt;enum value="107"   name="VK_FORMAT_R32G32B32A32_UINT" type="uint32_t" arity="4" /&gt;.

**Comment by NicolBolas** [comment]
That information is redundant, and therefore can easily get out of sync. Outside of certain types involving depth/stencil and the BLOCK formats, you can write a parser to generate this information pretty easily.

**Comment by oddhack** [comment]
I agree with @NicolBolas . The XML is restricted in its purpose: to describe the API in a way that lets different language bindings and other representations of the API be generated; the dependencies between different parts of the API; and some tagging to help in mechanically constructing valid usage statements for the API. What you're asking for here sounds like it might be most useful in a utility library, though I don't know your use case.

**Comment by Sairony** [comment]
How is it redundant? I persume I could parse the enum name as a string & pray that the different parts will always map correctly even if new ones gets introduced.

I want it because given a vertex stream inputs type & arity I need to deduce the appropiate VkFormat for its VkVertexInputAttributeDescription.

**Comment by oddhack** [comment]
It's redundant because it's already discussed in the spec in the "Format Definition" section. We've found that any time we duplicate information in two places in a spec, it's very likely that eventually they will become inconsistent, so there's a very strong incentive not to do that.

**Comment by NicolBolas** [comment]
> I persume I could parse the enum name as a string & pray that the different parts will always map correctly even if new ones gets introduced.

Considering how regular the format names are, I don't think prayer is necessary.

> I want it because given a vertex stream inputs type & arity I need to deduce the appropiate VkFormat for its VkVertexInputAttributeDescription.

But there's not a 1:1 mapping between those parameters. If you see a type of `uint8_t` and an arity of 4, that doesn't mean they want `VK_FORMAT_R8G8B8A8_UINT`. They could want `VK_FORMAT_R8G8B8A8_UNORM`. Or `VK_FORMAT_R8G8B8A8_USCALED`. Or `VK_FORMAT_B8G8R8A8_UINT`.

What you're trying to do is simply not workable. I understand the desire to go to a more OpenGL way of describing vertex formats, but using only those two parameters is simply insufficient information to deduce a proper Vulkan format name.
