### ISSUE TITLE
VkImageCopy/VkBufferImageCopy Valid Usage missing indentation

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#66]
In https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#copies-images the Valid Usage section for VkImageCopy tries to do some conditional sequences of statements like:

> * If the calling command’s srcImage is a compressed format image:
> * all members of srcOffset must be a multiple of the block size in the relevant dimensions 
> * extent.width must be a multiple of the block width or (extent.width + srcOffset.x) must equal the source image subresource width
> * [...]

but there's no visible indentation or nesting of the bullet points so you can't tell what the "If" condition applies to. (It's not terribly hard to guess, but I'd prefer not to have to.)

Same problem with VkBufferImageCopy.

**Comment by oddhack** [comment]
Assign to @TobiasHector . This looks like some additional markup in the <usage> tags will be needed to indicate nesting levels - right now there are a couple of blank spaces but perhaps it would make more sense to have <usage>* A sub-point.</usage>

**Comment by TobiasHector** [comment]
I think this happened because someone tried to add nested bullets, but then it didn't come out in all the asciidoc builds correctly, so the sub-points got removed... I suspect this isn't too hard of a thing to fix - I'll take a look.

**Comment by philiptaylor** [comment]
1.0.6 added some invisible indentation to VkBufferViewCreateInfo too.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.12 update.
