### ISSUE TITLE
[Specification] Fixed point LOD and "mipmapPrecisionBits"

### ISSUE THREAD

**Issue by Retrofractal** [KhronosGroup/Vulkan-Docs#660]
In Section 30.2. Limits, under "mipmapPrecisionBits", there is a note:

> For example, if this value is 2 bits then when linearly filtering between two levels, each level could contribute: 0%, 33%, 66% or 100% (this is just an example and the amount of contribution **should** be covered by different equations in the spec).

I'm not sure whether this is a mistake, but I don't think it is wise/ideal to use `unorm` for mipmap interpolation, given that DirectX mandates an explicit S8.8 fixed point representation for the LOD, when applied to mipmap selection/interpolation.

Unfortunately, Vulkan makes no reference to this quantization in the relevant portion of the spec (15.6.7 or 15.9.3). Since accuracy requirements appear to be a little thin on the ground, I suppose the spec can be ignored, but it would be nice if explicit provision for fixed point conversion could be made.

**Comment by NicolBolas** [comment]
I think you're misunderstanding what `mipmapPrecisionBits` means. It doesn't say anything about the total "representation for the LOD". The value merely specifies the number of bits of precision you get *between* mipmap levels.

That is, if an implementation uses S8.8 fixed point to represent the LOD, then `mipmapPrecisionBits` would be 8, derived from the ".8" part of that. Precision doesn't involve a sign.

**Comment by Retrofractal** [comment]
Sorry, I should have stated the issue more clearly.

For the example given above to be consistent with a fixed point representation of the LOD (without additional conversion), the stated contributions ought to be:
0%, 25%, 50%, 75%

**Comment by oddhack** [comment]
We are looking into this, starting with polling what existing implementations are doing.

**Comment by oddhack** [comment]
Should be fixed in the 1.1.89 spec update.
