### ISSUE TITLE
Memory size requirements for resources created with identical create info?

### ISSUE THREAD

**Issue by Barakat** [KhronosGroup/Vulkan-Docs#661]
Given that two or more buffers/images created with identical create info, is it guaranteed that they will require the same _size_?

I think it should be stated explicitly in the documentation since it is quite counter-intuitive that they may require different sizes.

**Comment by drakos-amd** [comment]
This is not currently guaranteed by the spec. Only the memory types returned in the memory requirements have invariance rules.

We will consider adding that requirement to the spec though as it is indeed seems like a sensible requirement from an application's perspective.

**Comment by oddhack** [comment]
This should be addressed in the 1.1.74 spec update.
