### ISSUE TITLE
VK_TRUE / VK_FALSE are signed, while VkBool32 is unsigned

### ISSUE THREAD

**Issue by Sairony** [KhronosGroup/Vulkan-Docs#662]
As the title says, is this an oversight? Currently when using wrappers for the API functions one needs to explicitly cast to VkBool32 because of this.

**Comment by NicolBolas** [comment]
It's not an oversight because it's not true. The specification says this:

> VK_TRUE represents a boolean True (integer 1) value, and VK_FALSE a boolean False (integer 0) value.

It says nothing about whether this is signed or unsigned. `vk.xml` declares their values as a "value". `vulkan.h` makes them macros, so they are merely integer literals. There's no need to explicitly the literal `1` to an unsigned type.

Perhaps your problem is with some generated version of the header? That's an issue to be sorted out by the creators of that header.

**Comment by krOoze** [comment]
> There's no need to explicitly cast the literal 1 to an unsigned type.

There might be in C++. Can't hurt to have a literal of appropriate type...

BTW `#define VK_REMAINING_MIP_LEVELS (~0U)` and others are not exactly correct either for `uint32_t`, if I am being anal about it...

**Comment by Sairony** [comment]
I generate a header from the xml schema & use wrappers for the API functions & structs for various reasons. In my case these wrappers use variadic templates to forward the arguments, hence they would need an explicit cast. With some more effort I could skip the variadic approach, but in any case it would still be nice if `VK_TRUE` & `VK_FALSE` actually matched `VkBool32`, for the same reasons `#define NULL 0` is bad practice in C++. `vulkan.h` could continue to go the `#define` route.

**Comment by NicolBolas** [comment]
> In my case these wrappers use variadic templates to forward the arguments

To forward the arguments to what? To forward arguments to _all_ functions? I don't understand the point of that. Especially since you have the XML right there and can easily provide the actual prototype for the function.

**Comment by Sairony** [comment]
For example:
```template<>
struct make_vkstruct< VkPipelineCacheCreateInfo >
{
	template< typename... TParams >
	VkPipelineCacheCreateInfo operator()( TParams... a_Args ) const
	{
		return VkPipelineCacheCreateInfo{ VK_STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO, std::forward<TParams>(a_Args)... };
	}
};
```

Same deal with the API functions:
```
...
template< typename... TParams >
inline auto operator()( TParams&&... a_Args ) const -> decltype(m_Func( std::forward< TParams >( a_Args )... ))
{
	ALTUS_ASSERT( m_Func, "Trying to call an function that hasn't been linked yet" )(m_Key);
	return m_Func( std::forward< TParams >( a_Args )... );
}
...
```

**Comment by krOoze** [comment]
Well, for fun let's have a PR to that effect (#664).

**Comment by oddhack** [comment]
There is stronger typing on constants now, and they're unsigned or float explicitly. Closing.
