### ISSUE TITLE
Request for clarification on shader interfaces

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/Vulkan-Docs#666]
I'd like to raise an issue on an ambiguity in the spec wrt shader interface matching. I'm honestly not sure what the spec means to say in this area, and this seems crucial for tool, driver and shader development.

In a sentence (TL;DR):
Is it valid for vertex shader to have user-defined outputs with locations 0, 1 and 2, but for fragment shader to only have user-defined input with location 1 (assuming output/input for location 1 matches in size/component)?

On one hand, the spec says
> At an interface between two shader stages, the user-defined variable interface must match exactly, as described above.

Which can be interpreted as "no" and I can imagine that this simplifies driver code if a driver wants to compile shaders separately. However I'm not sure how to interpet this sentence precisely.

On another hand, no other API has the same strict requirement (HLSL, GLSL and MSL all have rules that allow omitting some outputs from subsequent shader stages, although the rules tend to vary a bit), existing Vulkan drivers seem to handle missing outputs fine, and validation layers don't issue an error for this (they do issue a *performance* warning).

I would like to get a clarification on this issue in the form of either an explicit statement that allows this, or an explicit statement that prohibits this, as part of the spec. Additionally, a few other points I'm not clear on (what follows is quotes from `14. Shader Interfaces`):

> 14.1.1. Built-in Interface Block
> ... be declared in a block whose top-level members are the built-ins.

What does "block" mean in this context? Basic block from SPIRV?

> Built-ins only participate in interface matching if they are declared in such a block. They must not have any Location or Component decorations.

Is it even valid to have builtins in a different block? I'm assuming "no" because then you'd have two blocks with builtins?
Is it valid to have a BuiltIn that is listed in the block with other builtins but isn't referred to by the OpEntryPoint?
It it valid to have a BuiltIn outside a block with Location/Component decoration?

> 14.1.3. Interface Matching
> At an interface between two non-fragment shader stages, the built-in interface block must match exactly, as described above.

Does this mean for any output you must have an input? How does this work for, say, vertex shader `Layer` output if you also have a geometry shader present? Similarly to TL;DR, this should clarify what "exactly matching" means even if it seems redundant.

> At an interface involving the fragment shader inputs, the presence or absence of any built-in output does not affect the interface matching.

Does this mean the built-in input to the fragment shader stage (and built-in output to the stage that precedes it)?

> At an interface between two shader stages, the user-defined variable interface must match exactly, as described above.

As stated in the TL;DR, this should clarify what "exactly matching" means, even if it seems redundant. 

> 14.2. Vertex Input Interface
> All vertex shader inputs declared as above must have a corresponding attribute and binding in the pipeline.

This seems less ambiguous, and I'm assuming this does mean that pipeline can have attribute/binding entries that aren't listed in the vertex shader inputs; it would be nice to spell this out explicitly.

**Comment by zeux** [comment]
After reading the shader validation source code (which seems like a bad source to get your spec knowledge from), my renewed understanding of builtin rules is as follows:

- You can declare builtin inputs/outputs either as standalone variables, or as a `Block` - that is, a variable of type `Struct` with a `Block` decoration
- You can have at most one input and one output `Block` with built-ins per entrypoint; in addition to that, you can have an arbitrary number of free-standing builtin variables of scalar/vector type.
- Input and output `Block` must match exactly between shader stages - that is, they have to contain the same fields with the same builtin decorations - with the exception of fragment shader inputs where you can omit... something... (still not sure what).

Please let me know if this is accurate, and the original question about user-defined variables still stands. Also it would be great if the spec said `Block` instead of block everywhere where it means SPIRV `Struct` with `Block` decoration...

**Comment by NicolBolas** [comment]
> How does this work for, say, vertex shader Layer output if you also have a geometry shader present?

It doesn't; the BuiltIn `Layer` is not legal to be used in a VS:

> Layer output by a Geometry Execution Model, input to a Fragment Execution Model, for multi-layer framebuffer. See Vulkan or OpenGL API specifications for more detail.

Vulkan doesn't have ARB_shader_viewport_layer_array.

----

> with the exception of fragment shader inputs where you can omit... something... (still not sure what).

"Something"? The spec gives a blank-check to the built-in interface between the FS and the prior stage. That's what "the presence or absence of any built-in output does not affect the interface matching," means. An FS is not required to take the `Position` built-in input, nor is the previous stage required to write the `FrontFacing` built-in output if the FS reads that input.

The FS has its own built-in variable interface, whose values are not (necessarily) supplied by the prior stage.

**Comment by zeux** [comment]
> the BuiltIn Layer is not legal to be used in a VS:

This is incorrect, see VK_EXT_shader_viewport_index_layer

**Comment by zeux** [comment]
> The spec gives a blank-check to the built-in interface between the FS and the prior stage

Right, the "output" part initially confused me slightly but I now realize that it's stated the way it is because depending on pipeline configuration, different stages can immediately precede FS. This specific part now makes more sense, thanks.

**Comment by oddhack** [comment]
@zeux it seems like some of your initially posted questions are getting resolved in the course of the discussion. Could you perhaps post a stripped-down version of the OP with what remaining issues/questions are open?

**Comment by zeux** [comment]
@oddhack the main questions/requests are still open. Here's a new version (lmk if you'd prefer me updating the top post):

I'd like to raise an issue on an ambiguity in the spec wrt shader interface matching. I'm honestly not sure what the spec means to say in this area, and this seems crucial for tool, driver and shader development.

In a sentence (TL;DR):
Is it valid for vertex shader to have user-defined outputs with locations 0, 1 and 2, but for fragment shader to only have user-defined input with location 1 (assuming output/input for location 1 matches in size/component)?

On one hand, the spec says

> At an interface between two shader stages, the user-defined variable interface must match exactly, as described above.

Which can be interpreted as "no" and I can imagine that this simplifies driver code if a driver wants to compile shaders separately. However I'm not sure how to interpet this sentence precisely.

On another hand, no other API has the same strict requirement (HLSL, GLSL and MSL all have rules that allow omitting some outputs from subsequent shader stages, although the rules tend to vary a bit), existing Vulkan drivers seem to handle missing outputs fine, and validation layers don't issue an error for this (they do issue a performance warning).

I would like to get a clarification on this issue in the form of either an explicit statement that allows this, or an explicit statement that prohibits this, as part of the spec. Additionally, a few other points I'm not clear on (what follows is quotes from 14. Shader Interfaces):

> At an interface between two shader stages, the user-defined variable interface must match exactly, as described above.

As stated in the TL;DR, this should clarify what "exactly matching" means, even if it seems redundant.

> 14.2. Vertex Input Interface
> All vertex shader inputs declared as above must have a corresponding attribute and binding in the pipeline.

This seems less ambiguous, and I'm assuming this does mean that pipeline can have attribute/binding entries that aren't listed in the vertex shader inputs; it would be nice to spell this out explicitly.

**Comment by oddhack** [comment]
Thanks. We've taken your last update above for internal discussion and hopefully will be doing corresponding spec updates soon.

**Comment by timofonic** [comment]
@zeux @NicolBolas @oddhack Any news? Will the spec be updated soon? Thanks!

PS: There's tons of old issues yet not addressed in the issue tracker, many of them from 2016...

**Comment by oddhack** [comment]
This should be fixed in the 1.2.183 spec update.

**Comment by Tobski** [comment]
As of this morning's update, the interface matching section has *finally* been rewritten to be as unambiguous as possible (and much smaller):

https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap15.html#interfaces-iointerfaces-matching

So to answer your question directly...

> Is it valid for vertex shader to have user-defined outputs with locations 0, 1 and 2, but for fragment shader to only have user-defined input with location 1 (assuming output/input for location 1 matches in size/component)?

Yes, this should now be unambiguously allowed, and we have CTS tests on the way which enforce this.

**Comment by Tobski** [comment]
@oddhack You beat me to it!

**Comment by oddhack** [comment]
> @oddhack You beat me to it!

Well, I *do* have the first-mover advantage of commenting immediately after I post the updated spec :-)

**Comment by alecazam** [comment]
This change to "Allow ADCE" to remove dad inputs broke our shader codegen to HLSL.  The interfaces are no longer non-gapped to the vs, and from vs to fs.   This ADCE is also part of the default optimizations, and so all shader gen is affected.  The code always passes false for ADCE's preserve_interface flag.   And there's no CLI option to override or run ADCE with this set to true.  This has worked okay in our MSL and SPV generation so far, but first noticed it when trying to transpile HLSL from the glslc spirv sources.  

https://github.com/google/shaderc/issues/1244

**Comment by alecazam** [comment]
This change to ADCE is still unresolved for our build break.  We're about to update to the latest tools again.  Our tools have languished for 3.5 years due to this change with no CLI override of this ADCE behavior.  And we don't build from sources, and just take the tools from the Vulkan SDK.   Will either have to fix our reflection and GLSL -> HLSL codegen, or add our own override and build this tool from source.

**Comment by Tobski** [comment]
> This change to ADCE is still unresolved for our build break. We're about to update to the latest tools again. Our tools have languished for 3.5 years due to this change with no CLI override of this ADCE behavior. And we don't build from sources, and just take the tools from the Vulkan SDK. Will either have to fix our reflection and GLSL -> HLSL codegen, or add our own override and build this tool from source.

Hi @alecazam, not sure if I saw your previous comment since this PR was closed a while back, but it sounds like you have an issue with the spir-v tools pass that's running over your code, correct? I don't think there's any changes requested for the spec here?

If that's the case, can you raise an issue there detailing your problem? The people who maintain that repository don't typically look here. I can point people at your comment here to start with but you'll get more eyes on an issue there, and they'd need something there to provide updates and facilitate discussion as well.

**Comment by alecazam** [comment]
I mean this is this issue.   We're seeing our HLSL -> PSSL transpile messed up on several shaders.  I think it's because the vs inputs are mismatched to what we send down.   And I don't think PSSL likes gaps in the inputs.   I'm surprised this didn't break Roblox.

https://github.com/google/shaderc/issues/1244

I'll log it as a separate issue there, but need a way to set preserve_interfaces to true on the ADCE step instead of hardcoding it to false.

**Comment by alecazam** [comment]
Looks like someone realize just how bad this was for HLSL codegen and added a flag for preserve_interface that is supposed to be true for HLSL codegen, but I don't see anything in the submit actually setting it to true.

https://github.com/KhronosGroup/SPIRV-Tools/pull/5268

**Comment by Tobski** [comment]
Thanks, I'll bring this up with the SPIR-V folk to see if there's someone who can look at this.
