### ISSUE TITLE
Q: Allow `currentExtent` of (N, 0)?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#668]
In #590 we added:

> The `currentExtent` of a Win32 surface **must** have both `width` and `height` greater than 0, or both of them 0.

But AMD driver violates it on Windows 10. When a window is resized to 0 height it still shows non-0 width.

Before I report it as driver bug, I was wondering if we perhaps were too restrictive there.

**Comment by ianelliottus** [comment]
Seems like a driver bug to me.

@drakos-amd do you have any comment on this?

**Comment by drakos-amd** [comment]
Are you sure you're using the most up-to-date version of the AMD drivers?

This issue should be already fixed.

**Comment by krOoze** [comment]
@drakos-amd Yes, I have 18.3.4. Still the same.
On W10, when I resize the window to 0 height I get `currentExtent` e.g. `(800, 0)`.

**Comment by drakos-amd** [comment]
We (AMD) will investigate the issue.
FWIW, the spec is intentional and is the convention that we expect drivers to follow.

**Comment by krOoze** [comment]
> FWIW, the spec is intentional and is the convention that we expect drivers to follow.

Well, it is written by people; in this case by me no less.  The change was a bit of a grey area considering backwards compatibility too. So forgive my doubts.

If you say this newish restriction is desirable, then close the Issue at your leasure.
