### ISSUE TITLE
[Extension] Is VkExternalImageFormatPropertiesNV zero filled on VK_ERROR_FORMAT_NOT_SUPPORTED?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#669]
I think `vkGetPhysicalDeviceExternalImageFormatPropertiesNV`'s `VkExternalImageFormatPropertiesNV` should be zero filled on `VK_ERROR_FORMAT_NOT_SUPPORTED`, to match how `vkGetPhysicalDeviceImageFormatProperties` works.

**Comment by critsec** [comment]
I haven't been involved in this extension, but in general Vulkan doesn't zero-fill output structs on error. This was clarified in the spec a couple months ago, with VkImageFormatProperties called out as an exception retained for backwards compatibility.

The general rule is:

> If a command returns a run time error, unless otherwise specified any output parameters will have undefined contents, except that if the output parameter is a structure with `sType` and `pNext` fields, those fields will be unmodified. Any structures chained from `pNext` will also have undefined contents, except that `sType` and `pNext` will be unmodified.

See also the note in [VkImageFormatProperties2](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VkImageFormatProperties2) and the second note in [VkImageFormatProperties](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VkImageFormatProperties).
