### ISSUE TITLE
Possible typo: "optimal linear resources"

### ISSUE THREAD

**Issue by nsf** [KhronosGroup/Vulkan-Docs#67]
I'm not sure if this wording is correct, but seems like a typo here:

https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/doc/specs/vulkan/chapters/resources.txt#L1018-L1019

> optimal linear resources are those created with ename:VK_IMAGE_TILING_OPTIMAL

Perhaps, should be

> optimal image resources are those created with ename:VK_IMAGE_TILING_OPTIMAL

**Comment by nsf** [comment]
When there is just one result :grinning: :

![justone](https://cloud.githubusercontent.com/assets/12567/13237493/6726a05e-d9ee-11e5-9054-9df85e9ddb81.png)

**Comment by drakos-amd** [comment]
Yes, that is indeed a typo.

**Comment by oddhack** [comment]
Done in the 1.0.5 spec update.
