### ISSUE TITLE
Vulkan 1.1 and VK_AMD_negative_viewport_height

### ISSUE THREAD

**Issue by polarina** [KhronosGroup/Vulkan-Docs#674]
The `VK_AMD_negative_viewport_height` extension has [added text](https://github.com/KhronosGroup/Vulkan-Docs/commit/ce60b9c88745ecded74296dfbe69dae7c1fb2e62#diff-c900a33edbc8a97b719606c019619550R24) that disallows using it when the device reports Vulkan 1.1 support.

> Functionality in this extension is included in `VK_KHR_maintenance1` and Vulkan 1.1. Due to some slight behavioral differences, this extension must: not be enabled alongside `VK_KHR_maintenance1`, or when the device reports Vulkan 1.1 support.

The wording is a bit unfortunate. Valid and well behaving Vulkan 1.0 applications using `VK_AMD-negative_viewport_height`, that were written before Vulkan 1.1 was published and thus had no prior knowledge that this restriction would be added, now produce undefined behavior.

**Comment by NicolBolas** [comment]
Has Khronos ever promised backwards compatibility with vendor extensions? That is, that an extension which is valid against version X.Y shall be valid against all X.Z versions where Z > Y?

I think the bigger problem is that 1.1 took out the `apiVersion` check from `VkApplicationInfo`. Before, you could protect yourself from such changes by setting the `apiVersion` to 1.0. Now, you can't; without `VK_ERROR_INCOMPATIBLE_DRIVER`, there's no way to say "My code is specific to 1.0, so give me that or don't work". Or at least, there's no way to say that which is compatible with both 1.0 and 1.1.

**Comment by RC-1290** [comment]
@NicolBolas How about using (the existence of) vkEnumerateInstanceVersion (with extra help from vkGetInstanceProcAddr, as suggested in the 1.1.7 specification) to determine the difference?

**Comment by NicolBolas** [comment]
@RC-1290 The problem the OP is talking about happens for people who have _shipping code_ on Vulkan 1.0 implementations. That is, they wrote a 1.0 application that has no idea that `vkEnumerateInstanceVersion` is a thing that even *could* exist. Vulkan is technically supposed to be backwards compatible, so an app written against 1.0 ought to be able to run against 1.1. But that isn't the case here, since the app is written against 1.0+an extension, and 1.1 doesn't work with that extension.

Yes, it's not particularly difficult to write code that can work with either 1.0+extension and 1.1 by itself. But that's not the scenario in question.

**Comment by oddhack** [comment]
What does the AMD driver actually *do* when an app tries to enable the extension with 1.1 - fail vkCreateDevice with VK_ERROR_EXTENSION_NOT_PRESENT?

**Comment by krOoze** [comment]
@oddhack It is marked "deprecated", so yes it will simply simply not be supported by 1.1(, I would assume).

Common sense would assume that passing "1.0" for `apiVersion` should make the impl. behave as 1.0 though. The spec does not make clear whether it just relaxes the parameter, or deprecates it completely.

`vkEnumerateInstanceVersion` seems broken to me. It is not backwards compatible, nor future-proof.
I think it should be backported to 1.0 (as an extension?).
And also remade to return array of all supported versions. I.e. how do I know if implementation returning 2.0 also supports 1.0??
Also why does it give `VkResult`, where only return code is `VK_SUCCESS`??

**Comment by drakos-amd** [comment]
Vulkan 1.1 is backwards compatible.

Applications written against Vulkan 1.0 (+ possibly VK_AMD_negative_viewport_height) will have their apiVersion set to 1.0 (or not set at all). That means the created instance will be a Vulkan 1.0 instance.

That means such existing applications will continue to work even on a driver implementation supporting Vulkan 1.1.
Only if the application explicitly opts in to using Vulkan 1.1 (by specifying an apiVersion of 1.1) will they not be able to use VK_AMD_negative_viewport_height.

**Comment by NicolBolas** [comment]
> Vulkan 1.1 is backwards compatible.
> ...
> That means such existing applications will continue to work even on a driver implementation supporting Vulkan 1.1.

That is not how the specification defines "backwards compatibility". You're saying that compatibility is achieved by requiring implementations to provide _both_ 1.0 and 1.1 implementations, which will be selected based on `apiVersion`. The specification says:

> A given version of the API is backwards compatible with an earlier version if an application,
relying only on valid behavior and functionality defined by the earlier specification, is **able to
correctly run against each version without any modification**. This assumes no active attempt by
that application to not run when it detects a different version.

Emphasis added.

**Comment by drakos-amd** [comment]
Can you explain why you think that the statement you quoted doesn't hold? An application will correctly run against a 1.1 implementation without any modification.

The implementation doesn't have to provide both a 1.0 and a 1.1 implementation (separately), it's simply that a 1.1 implementation will operate according to 1.0 rules unless the application actually opts in for using 1.1.

**Comment by NicolBolas** [comment]
If a Vulkan implementation follows 1.0's rules and returns MAKE_VERSION(1, 0, 0) for `VkPhysicalDeviceProperties::apiVersion`, then it is a 1.0 implementation. And therefore, code running on such an implementation is not running on a 1.1 implementation. Therefore, code running on that implementation is not running "against" version 1.1.

They may be using the same code behind the scenes, but my overall point remains. Backwards compatibility defined by the standard says that a correct 1.0 program should be able to run on a 1.X *implementation*, not merely the same codebase that returns a lower version than it could support. That is, a 1.0 application ought to be able to request an apiVersion of 1.0, yet still run fine if they get a `VkPhysicalDeviceProperties::apiVersion` of 1.1. That's what the standard says.

**Comment by drakos-amd** [comment]
I see what you mean now. Yes, `VkPhysicalDeviceProperties::apiVersion` being 1.1 should not have an effect.

It seems like the deprecation note in the extension's appendix is incorrectly worded when it says "or when the **device reports** Vulkan 1.1 support". It should refer to the version the application opted in for at instance creation.

**Comment by oddhack** [comment]
This should be fixed in the 1.1.71 spec update per @drakos-amd
