### ISSUE TITLE
Wrong parameter descriptions for vkCreateIndirectCommandsLayoutNVX

### ISSUE THREAD

**Issue by andens** [KhronosGroup/Vulkan-Docs#677]
In section 28.3.2, the parameter descriptions for `vkCreateIndirectCommandsLayoutNVX` are wrong. They have been duplicated from `vkCreateObjectTableNVX`.

**Comment by oddhack** [comment]
@dgkoch could you take this, or assign it to Christoph, who is the listed contact (he doesn't seem to be a member of KhronosGroup so I can't assign it to @pixeljetstream myself, assuming that's his Github ID).

**Comment by oddhack** [comment]
This should be fixed in the 1.1.71 spec update.
