### ISSUE TITLE
registry.rnc and the API documentation don't describe the `platform` attribute.

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#678]
`extension` tags now allow the `platform` attribute, which presumably names one of the members of the `platforms` list. But there is no documentation for the meaning of this attribute at present, either in the .rnc file or in the [registry documentation](https://www.khronos.org/registry/vulkan/specs/1.1/registry.html).

**Comment by oddhack** [comment]
We're not using this yet, but will be able to eventually to help construct the per-platform headers. I'll document the current state of it soon.

**Comment by RC-1290** [comment]
The platform specific extensions no longer use their own protect attributes (used for the platform specific ifdefs in the standard vulkan.h header). Those defines are now listed in the platform tags (inside the platforms tag, inside the registry tag), so I'm fairly sure those **are** used.

**Comment by oddhack** [comment]
They're only used in vulkan.h, which is a handcoded header.

**Comment by oddhack** [comment]
@NicolBolas the \<extension> documentation (section 20.1 of registry.html) does describe the platform= attribute. See https://www.khronos.org/registry/vulkan/specs/1.1/registry.html#_attributes_of_code_extension_code_tags . So all I see to do here is to add the platform= attribute to the comments in registry.rnc, and add the \<platforms> tag to the index in section 4.1 as requested by #673. Is there something else you think is missing in this regard?

**Comment by RC-1290** [comment]
Interesting. That explains some things.

Yeah, I think it's clear. In my header generator, I implemented the platform attribute in the same way as the protect attribute (after looking up the platform's protect value), which worked fine. I'm only wondering whether these attributes and tags are still subject to change in the short term. I'll make a mental note of it possibly changing with future versions.

**Comment by oddhack** [comment]
It is unlikely the values would change. The protect symbols have been defined for all the platforms people have wanted to support so far, and there's no apparent reason for them to be changed in the future. The XML schema might very well change in the future to accommodate future needs (or some of the existing issues people have run into when generating non-C language bindings), but we're conservative about breaking changes, as there's a substantial ecosystem dependent on the schema, including particularly the loader and validation layers.

**Comment by oddhack** [comment]
The docs have been updated in the 1.1.72 release.
