### ISSUE TITLE
Releasing vkPhysicalDevices?

### ISSUE THREAD

**Issue by li3** [KhronosGroup/Vulkan-Docs#68]
Maybe I'm miss-understanding something but I don't see a symmetrical `vkDestroyPhysicalDevice` to go along with `vkEnumeratePhysicalDevices`. Should we be cleaning up these pointers or is this handled by `vkDestroyInstance`?

**Comment by baldurk** [comment]
`vkPhysicalDevices` are considered to be implicitly created by the `vkInstance`, so they get destroyed when you destroy the `vkInstance` - no need to do anything special.

The same applies for `vkQueues` and `vkDevices`. From the spec 2.2.1 Object Lifetime:

> * VkQueue objects cannot be explicitly destroyed. Instead, they are implicitly destroyed when the VkDevice object they are retrieved from is destroyed.
> 
> * VkPhysicalDevice objects cannot be explicitly destroyed. Instead, they are implicitly destroyed when the VkInstance object they are retrieved from is destroyed.

**Comment by li3** [comment]
Perfect thank you. One thing to note in the [`vkDestroyInstance`](https://www.khronos.org/registry/vulkan/specs/1.0/man/html/vkDestroyInstance.html) there's a segment that states:
>However, objects allocated directly or indirectly through the instance are not destroyed automatically and so may be leaked. 

I had missed that particular bullet under Object Lifetime, and with the statement above I was concerned I needed to release the physical device -- hence the question.

**Comment by baldurk** [comment]
I think that line is referring to direct/child and indirect/grandchild objects. i.e. devices and debug report objects created directly from the instance, and memory objects or images created indirectly via a child device. It could probably use some clarification though, but the spec is the 'letter of the law' so to speak :smile:.

**Comment by oddhack** [comment]
@li3 are you OK with closing this? If not, perhaps @baldurk could suggest a clarification that would help?

**Comment by li3** [comment]
Oops, sorry closing this is perfectly fine with me.
