### ISSUE TITLE
Ambiguity about when descriptor sets can be modified

### ISSUE THREAD

**Issue by tomaka** [KhronosGroup/Vulkan-Docs#69]
It is not clear when you are allowed to call `vkUpdateDescriptorSets` on a descriptor set. Is it:

- When the descriptor set is not used in any command buffer that is going to be executed any time in the future?
- When the descriptor set is not used in any command buffer that is currently being executed by a queue?

Here is what I found in the specs:

> When a descriptor set is allocated, the initial state is largely uninitialized and all descriptors are undefined. However, the descriptor set can be bound in a command buffer without causing errors or exceptions. Entries must be populated before they are accessed by a pipeline, but leaving uninitialized entries that are not accessed by a pipeline will produce well-defined results.

This paragraph suggests that you can update a descriptor set after you have recorded a command buffer that uses it and before it is accessed by the pipeline (ie. the GPU).

> The descriptor set contents bound by a call to vkCmdBindDescriptorSets may be consumed during host execution of the command, or during shader execution of the resulting draws, or any time in between. Thus, the contents must not be altered (overwritten by an update command, or freed) between when the command is recorded and when the command completes executing on the queue.

But this paragraph suggests that you can't update a descriptor set once you start recording the command buffer.

**Comment by jeffbolznv** [comment]
The intent was that the descriptor set must be updated before it is bound to a command buffer. Or more precisely, that you can't bind a descriptor set to a command buffer and then update the descriptor set without invalidating that command buffer. We should clarify this.

**Comment by oddhack** [comment]
(@jeffbolznv, I don't think you're in the Vulkan team yet? I can't seem to assign this to you externally but did internally.)

**Comment by oddhack** [comment]
Done in the 1.0.5 spec update.
