### ISSUE TITLE
Device Limits When Using VkDeviceGroupDeviceCreateInfo

### ISSUE THREAD

**Issue by bryanmcconkey** [KhronosGroup/Vulkan-Docs#695]
The specification does not outline how queue families, extensions, and other things that are physical device specific impact creation of a logical device when using VkDeviceGroupDeviceCreateInfo with a device group.

I would *think* that it must be one of two things.
A) A device group will only ever exist when these limits match exactly (ie same physical card x 2 etc)
B) The limits of the physical device referenced directly by the vkCreateDevice structure are the ones that matter, the drivers would take care any physical device differences among the device group.

I feel like A is the most likely, but I do not actually know, and feel the specification should be explicit about what device limits one can expect when using device groups.

Thanks!

**Comment by MarcelPiNacy** [comment]
Any update on this?

**Comment by jeffbolznv** [comment]
We discussed this in today's meeting and agreed on option A. I'll try to get this into the spec soon.

**Comment by bryanmcconkey** [comment]
Thanks for the update!

**Comment by oddhack** [comment]
This should be fixed in the 1.1.109 spec update.

**Comment by bryanmcconkey** [comment]
I can confirm I see a description resolving my issue in the 1.1.109 spec. Thanks!
