### ISSUE TITLE
VK_NV_shader_subgroup_partitioned doc issues

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#696]
1) The `VK_NV_shader_subgroup_partitioned` is missing in the appendices.

2) The GLSL link in it is to GH, not registry as usual

3) The SPV registry link is 404

4) The `VK_SUBGROUP_FEATURE_PARTITIONED_BIT_NV` is an `elink`, but that unfortunately does not work for individual enumerants.

5) First it says it requires Vulkan 1.0 and then it says 1.1 in the free text.

**Comment by oddhack** [comment]
This should be fixed in the 1.1.74 spec update.
