### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [KhronosGroup/Vulkan-Docs#7]
I would like to point out that identifiers like "[`__vulkan_h_`](https://github.com/KhronosGroup/Vulkan-Docs/blob/d204ac2f6991f75fab2ebc22136fd179d692f84f/src/vulkan/vulkan.h#L1)" and "[`__VK_PLATFORM_H__`](https://github.com/KhronosGroup/Vulkan-Docs/blob/d204ac2f6991f75fab2ebc22136fd179d692f84f/src/vulkan/vk_platform.h#L28)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to [adjust your selection for unique names](https://github.com/KhronosGroup/Vulkan-Docs/blob/d204ac2f6991f75fab2ebc22136fd179d692f84f/src/spec/generator.py#L592 "Update candidate: COutputGenerator")?

**Comment by oddhack** [comment]
Thanks. Taken under advisement inside Khronos - we'll poll the members and see who might have a problem with such a change. It's the same __ prefix scheme used for the GL/ES/EGL headers for something like 15 years, so in practice it doesn't seem to be causing many problems, but I think it's likely we could change this pretty soon.

**Comment by elfring** [comment]
Does this issue need to be copied to any more places in [other bug tracking systems](https://www.khronos.org/bugzilla/ "Using Bugzilla?")?

How do you think about to avoid that the mentioned software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by oddhack** [comment]
No, it doesn't. We are only using Github issues for public issue tracking. When there's something to report, an update will be posted here.

**Comment by RichardRanft** [comment]
The standard was different 15+ years ago - let's get modern please....

**Comment by salamanderrake** [comment]
First the libraries and such are not C++, they are C, and if you want a C++ language standard then check out NVidias vkcpp wrapper https://github.com/nvpro-pipeline/vkcpp. but yeah I thought the whole point of vulkan was to get away from the archaic opengl stuff.

**Comment by NicolBolas** [comment]
@salamanderrake 

Vulkan's C headers are intended to be able to be consumed by C++ too. Since that's how a lot of C++ users will be using it.

**Comment by oddhack** [comment]
Fixed.

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/KhronosGroup/Vulkan-Docs/commit/5a4c5e5925c65c6e6677c1fb21571684b4b0a77b#diff-436ea93d14085146d8d9dd81b01fb58bL28 "Deletion of a few underscores").
