### ISSUE TITLE
SVG diagram broken in Firefox for triangle strips with adjacency

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#70]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#_triangle_strips_with_adjacency

The "Triangle strips with adjacency" diagram is not visible for me in Firefox (various versions on both Windows and Linux), there's just a big white gap.

It looks correct in Chrome.

In IE11 that diagram is also invisible, plus the "triangles with adjacency" diagram is greatly zoomed in so you can't see much of it.

**Comment by oddhack** [comment]
Apparently something about SVG generated from Inkscape is making FF unhappy, though it reports no errors that I can see on the console. I can save as "plain SVG" and that renders in FF at the SVG file level, at least. Will play with that and see if switching formats is a suitable fix. Just getting images to more-or-less work in both PDF and HTML (Chromium) outputs was a pain :-(

**Comment by oddhack** [comment]
Ping @TobiasHector since IIRC you were mostly responsible for the existing image handling in the spec?

**Comment by philiptaylor** [comment]
[Apparently](http://logs.glob.uno/?c=freenode%23whatwg&s=24%20Feb%202016&e=24%20Feb%202016#c986022) the problem is the

>     viewBox="-108.050 3.950 -13.183 76.817"

which is specifying a negative width, which is illegal. Firefox chooses to not render anything, Chrome chooses to ignore the viewBox.

**Comment by oddhack** [comment]
Thanks for following up. No clue why Inkscape is doing that. BTW what is the chat forum you were using about?

**Comment by philiptaylor** [comment]
It's the IRC channel for the [WHATWG](https://whatwg.org/), who are responsible for the HTML5 spec and various other web stuff, so there's a bunch of web standards people and browser developers there.

**Comment by oddhack** [comment]
Using Inkscape to turn the diagram into Plain SVG does solve the problem. Will be coming up in an upcoming spec update (we are trying to do these weekly, I'm guessing this will roll out 3/10 but it's just a guess).

**Comment by oddhack** [comment]
Done in the 1.0.5 spec update.
