### ISSUE TITLE
Wrong date for v1.1.72 in Changelog.txt

### ISSUE THREAD

**Issue by cneumann** [KhronosGroup/Vulkan-Docs#701]
At the risk of collective groan and/or laughter from the maintainers, I'd like to report that the date for v1.1.72 in Changelog.txt is wrong ;)

Change log for March 5, 2018 Vulkan 1.1.72 spec update:
should be:
Change log for April 5, 2018 Vulkan 1.1.72 spec update:

**Comment by oddhack** [comment]
That will be fixed in the next public update in a few days. Thanks.
