### ISSUE TITLE
vulkan_ext.c broken for SDK 1.1.70.1?

### ISSUE THREAD

**Issue by nsubtil** [KhronosGroup/Vulkan-Docs#707]
After updating to the latest Vulkan SDK, I now get compilation errors in the latest version of vulkan_ext.c:

vulkan_ext.c(26): error C2373: 'vkDestroySurfaceKHR': redefinition; different type modifiers
c:\vulkansdk\1.1.70.1\include\vulkan\vulkan_core.h(4608): note: see declaration of 'vkDestroySurfaceKHR'
...

Is this a known issue? Has something changed in the expected usage of vulkan_ext?

**Comment by krOoze** [comment]
Dup of #449

**Comment by nsubtil** [comment]
#449 has been fixed for over a year now. I've had success building vulkan_ext.c in the meantime.

It does sound related however. But if this is indeed a recurring issue, then something isn't right.

**Comment by krOoze** [comment]
@nsubtil Seems like the fix was reverted, or not picked in migration to master branch...
Indeed the `vulkan_ext.c` is missing `VK_API_*` decorations.

**Comment by oddhack** [comment]
We will be removing vulkan_ext.[ch] in the next spec update. As @krOoze notes, it has conflicts with the loader, and other significant limitations. Since people may still want to use it, we'll be keeping the generator code that creates these files from vk.xml, but not supporting it going forward.
