### ISSUE TITLE
vkCmdDraw linear filtering feature requirement

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#71]
vkCmdDraw, vkCmdDrawIndexed, vkCmdDrawIndirect, vkCmdDrawIndexedIndirect all say:

> Any VkImage being sampled with VK_FILTER_LINEAR as a result of this command must be of a format which supports linear filtering, as specified by the VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT flag in VkFormatProperties::linearTilingFeatures returned by vkGetPhysicalDeviceFormatProperties

I suspect linearTilingFeatures should only apply to VK_IMAGE_TILING_LINEAR images, and VK_IMAGE_TILING_OPTIMAL images should instead be checking optimalTilingFeatures here.

**Comment by drakos-amd** [comment]
Correct. This is described in the "Format Properties" section of the "Features, Limits, and Formats" chapter.

**Comment by TobiasHector** [comment]
Yes this is a mistake in the validation which apparently cropped up whilst trying to simplify the language IIRC... I'll look into a fix for this - should be easy enough to do something sane here.

**Comment by philiptaylor** [comment]
For completeness: This also applies to vkCmdDispatch, vkCmdDispatchIndirect.

**Comment by krOoze** [comment]
@TobiasHector This seems fixed in 1.0.12. Close?

**Comment by TobiasHector** [comment]
Apparently I've been missing some housekeeping - yes this is fixed. All relevant functions have been updated.
