### ISSUE TITLE
XML Type Issues

### ISSUE THREAD

**Issue by Keith-Cancel** [KhronosGroup/Vulkan-Docs#717]
Why are these marked as a define? 
```
        <type category="define">struct <name>ANativeWindow</name>;</type>
        <type category="define">struct <name>AHardwareBuffer</name>;</type>
```
Although, reading over the schema doc I don't see how you would describe a forward declared struct? Does the struct/union type have any thing to mark them as a forward declaration? Otherwise a separate category. 

Additionally, why are these constants specified as enums if they are not an enum type? Moreover, some of these values are compile time dependent is that intended? For instance (~0U) may have a different bit width on 32 bit system vs a 64 bit system.
```
<enums name="API Constants" comment="Vulkan hardcoded constants - not an enumerated type, part of the header boilerplate">
        <enum value="256"   name="VK_MAX_PHYSICAL_DEVICE_NAME_SIZE"/>
        <enum value="16"    name="VK_UUID_SIZE"/>
        <enum value="8"     name="VK_LUID_SIZE"/>
        <enum               name="VK_LUID_SIZE_KHR" alias="VK_LUID_SIZE"/>
        <enum value="256"   name="VK_MAX_EXTENSION_NAME_SIZE"/>
        <enum value="256"   name="VK_MAX_DESCRIPTION_SIZE"/>
        <enum value="32"    name="VK_MAX_MEMORY_TYPES"/>
        <enum value="16"    name="VK_MAX_MEMORY_HEAPS" comment="The maximum number of unique memory heaps, each of which supporting 1 or more memory types"/>
        <enum value="1000.0f" name="VK_LOD_CLAMP_NONE"/>
        <enum value="(~0U)" name="VK_REMAINING_MIP_LEVELS"/>
        <enum value="(~0U)" name="VK_REMAINING_ARRAY_LAYERS"/>
        <enum value="(~0ULL)" name="VK_WHOLE_SIZE"/>
        <enum value="(~0U)" name="VK_ATTACHMENT_UNUSED"/>
        <enum value="1"     name="VK_TRUE"/>
        <enum value="0"     name="VK_FALSE"/>
        <enum value="(~0U)" name="VK_QUEUE_FAMILY_IGNORED"/>
        <enum value="(~0U-1)" name="VK_QUEUE_FAMILY_EXTERNAL"/>
        <enum               name="VK_QUEUE_FAMILY_EXTERNAL_KHR" alias="VK_QUEUE_FAMILY_EXTERNAL"/>
        <enum value="(~0U-2)" name="VK_QUEUE_FAMILY_FOREIGN_EXT"/>
        <enum value="(~0U)" name="VK_SUBPASS_EXTERNAL"/>
        <enum value="32"    name="VK_MAX_DEVICE_GROUP_SIZE"/>
        <enum               name="VK_MAX_DEVICE_GROUP_SIZE_KHR" alias="VK_MAX_DEVICE_GROUP_SIZE"/>
    </enums>

```

**Comment by Keith-Cancel** [comment]
Woops my first question seem to be a duplicate of: https://github.com/KhronosGroup/Vulkan-Docs/issues/679

**Comment by krOoze** [comment]
#662 and #664 relevant to your second question.

**Comment by Keith-Cancel** [comment]
Okay, those are relevant to the later half of the question. It just does not seem great to rely on values that are generated at compile time. Yea definitely makes it harder for other languages since they have to generate sane values for what the compiler/system would. 

However, still why are these constants marked with enum tags? While an enum can be similar to a constant it's also more similar to class. It's just odd that this different from all the enums, and there is no tag marking it as such. I have read through this. https://www.khronos.org/registry/vulkan/specs/1.1/registry.html#tag-enums 

I don't see anything allowing such construction. Moreover the comment for this enum section even says "not an enumerated type". It's just seems like the schema could be better organized so when parsing the XML one does not have to know the enums section named "API Constants" is not really a enum.  

I just found the use of the type marked as a define, and this enums block inconsistent from what the schema documentation explained.

**Comment by oddhack** [comment]
N.b. the way the dependency-driven approach to generating interfaces works, the only time an "enums" block is required is when the corresponding enumerated type is being defined, and at that point it spits out all the contents of that block as the corresponding type. For a block like this one, the individual "enum" tags are required, and in that case a #define is generated. The description in registry.html could also stand to be improved as you note.

**Comment by oddhack** [comment]
Closing as non-actionable. The constant values are now all explicitly typed as uint32_t, uint64_t, or float which should help with FFI. Schema changes of larger scope, beyond additions such as this explicit tagging, are unlikely to happen due to disruption to us and everyone downstream from us consuming the XML.
