### ISSUE TITLE
Task list for VK_KHR_draw_indirect_count release

### ISSUE THREAD

**Issue by pdaniell-nv** [KhronosGroup/Vulkan-Docs#719]
The Khronos board of promoters have recently ratified a new Vulkan extension called `VK_KHR_draw_indirect_count`. This extends `vkCmdDrawIndirect` and `vkCmdDrawIndexedIndirect` with two new draw calls that allow the "drawCount" parameter to be sourced from a buffer rather than the function argument.

The task list for the `VK_KHR_draw_indirect_count` extension release is:
- [x] Headers, specs, etc. in https://github.com/KhronosGroup/Vulkan-Docs
- [x] Vulkan specification in the [Vulkan Registry](https://www.khronos.org/registry/vulkan/)
- [x] Vulkan Conformance Test Suite in https://github.com/KhronosGroup/VK-GL-CTS
- [x] Validation in https://github.com/KhronosGroup/Vulkan-ValidationLayers
- [x] Vulkan SDK at https://vulkan.lunarg.com/

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

Historically the Vulkan working group has tried to coordinate all components of a new KHR extension to be released to the public at the same time. The components typically include:
- Headers, specs, etc. in https://github.com/KhronosGroup/Vulkan-Docs
- Vulkan specification in the [Vulkan Registry](https://www.khronos.org/registry/vulkan/)
- Vulkan Conformance Test Suite in https://github.com/KhronosGroup/VK-GL-CTS
- Validation in https://github.com/KhronosGroup/Vulkan-ValidationLayers
- glslang in https://github.com/KhronosGroup/glslang
- SPIR-V headers in https://github.com/KhronosGroup/SPIRV-Headers
- SPIR-V extension in https://github.com/KhronosGroup/SPIRV-Registry
- SPIR-V tools in https://github.com/KhronosGroup/SPIRV-Tools
- Vulkan Loader in https://github.com/KhronosGroup/Vulkan-Loader
- Vulkan SDK at https://vulkan.lunarg.com/

Since many of those components have dependencies on other components it's actually quite hard to do a simultaneous release and takes a lot of preparation and efforts from many folks to pull together. We would like to reduce this workload and make releases easier and more timely.

As an experiment the Vulkan working group is trying a "rolling release" for `VK_KHR_draw_indirect_count`. This allows the components to be released in any order as the dependencies are satisfied. There will be some period of time between the release of the first component and the last, but our goal is to keep this as short as possible. This GitHub issue has been created to track when each component is released. When all the tasks have been completed the issue will be closed. We have a similar experiment for [VK_KHR_get_display_properties2](https://github.com/KhronosGroup/Vulkan-Docs/issues/720).

If you have any feedback on this experiment, please comment below.

**Comment by oddhack** [comment]
The extension spec is included in the 1.1.76 spec update.

**Comment by alegal-arm** [comment]
The tests are published in https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.1.1.1

**Comment by oddhack** [comment]
Fixed unfortunate typo in the extension name :-)

**Comment by jekstrand** [comment]
Loader support is missing from the checklist.  This is an instance extension and the loader does not yet support it.

**Comment by krOoze** [comment]
@jekstrand The spec says "Device extension".

**Comment by jekstrand** [comment]
@krOoze Yeah, I accidentally commented on the wrong extension checklist.  Too many tabs open.  Feel free to ignore. :)

**Comment by pdaniell-nv** [comment]
Validation has been merged: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/188

**Comment by pdaniell-nv** [comment]
Validation for VK_KHR_draw_count_indirect is in the newly released VulkanSDK-1.1.82. This feature is now fully released. Closing.
