### ISSUE TITLE
maxVertexInputBindings comparisons

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#72]
VkVertexInputBindingDescription says:

> binding must be less than or equal to VkPhysicalDeviceLimits::maxVertexInputBindings

VkVertexInputAttributeDescription says:

> binding must be less than VkPhysicalDeviceLimits::maxVertexInputBindings

They ought to be more consistent about the "or equal" bit (since I assume there's no value in having bindings that you can't attach to any attributes).

**Comment by jeffbolznv** [comment]
The first one is wrong and should be "less than".

**Comment by oddhack** [comment]
Done in the 1.0.5 spec update.
