### ISSUE TITLE
What's the current (and last) patch version number for 1.0? 69 or 76?

### ISSUE THREAD

**Issue by rohith10** [KhronosGroup/Vulkan-Docs#722]
https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html and its pdf say 76, but both https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/html/vkspec.html and https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html seem to have been frozen at 69.

If it's 76, where could I find the changelogs from 70 through 76? Would they be same as the ones for 1.1?

**Comment by oddhack** [comment]
The currently tagged revision in github is 1.1.76, because 1.1 is the current spec version, but any other specs generated from that tag will also be revision 76, thus 1.0.76. We chose not to continue publishing three different variants of the 1.0 spec when 1.1 came out - just the core API variant - but they can be generated from github if someone really needs them. Probably the most correct action here would be to replace the 1.0+WSI and 1.0+All specs with redirection to a landing page explaining this.

**Comment by oddhack** [comment]
We discussed this on the internal working group call today, and agreed to redirect to a landing page as I suggest above. I'll take care of that in an upcoming spec update.

**Comment by rohith10** [comment]
If I understand correctly - when you say "can be generated from github", do you mean cloning the repo, downloading/installing the necessary tools and then generating the documentation files (.html/.pdf) using them?

If so, that would be a massive backward step, in my opinion. As an application developer, it is incredibly helpful for me to refer to documentation that's readily available, and not have to build it myself. I understand that the core spec will always be available, but things like WSI are an integral part of a Vulkan app, but not of the core spec.

**Comment by krOoze** [comment]
I think building the HTML targets and hosting them is not a big deal.
I wonder if the `1.0-extensions` being subtly broken is the reason for reluctance to officially publish it.
E.g. it uses the 1.1 promoted command names.

**Comment by oddhack** [comment]
@rohith10 yes, building it yourself. I will pass on your feedback to the WG.

**Comment by oddhack** [comment]
We discussed this and agreed to restore current 1.0 specs for KHR and all extensions, given the upvotes on @rohith10's comment. I'll do that starting with the next public spec update.

**Comment by volcanoauthors** [comment]
I don't remember the issue number where some contributions were being made to asciidoctor. But I wanted to mention it in case others are wondering too.

**Comment by oddhack** [comment]
The 1.1.78 spec update has resumed updating all three 1.0 specs, not just the core 1.0 spec.

@volcanoauthors I'm not sure how your comment bears on this issue, but the original issue has been solved, so closing this. If you have an actionable problem, please open a new issue.
