### ISSUE TITLE
VK_SUBPASS_EXTERNAL is not specified

### ISSUE THREAD

**Issue by tumnus** [KhronosGroup/Vulkan-Docs#723]
The specification does not discuss the value of VK_SUBPASS_EXTERNAL.

Although I can look in my android ndk to discover that...

#define VK_SUBPASS_EXTERNAL (~0U)

...I'm looking to the spec to tell me if I can rely on this value in the future and for other platforms in the present.

**Comment by oddhack** [comment]
It's actually a general issue of the compile-time constants, not just this one. These values are hardwired into vk.xml and are not going to change in the future, but currently we don't expose the values in the API spec.

**Comment by tumnus** [comment]
Thanks that's really helpful
