### ISSUE TITLE
VK_QUEUE_SPARSE_BINDING_BIT and sparseBinding

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#727]
`VK_QUEUE_SPARSE_BINDING_BIT` is described as:

> `VK_QUEUE_SPARSE_BINDING_BIT` specifies that queues in this queue family support sparse memory management operations (see [Sparse Resources]()). If any of the sparse resource features are enabled, then at least one queue family **must** support this bit.

1) It does not make sense to speak of features being "enabled". This is obtained by `vkGetPhysicalDeviceQueueFamilyProperties`, i.e. well before features are enabled by `vkCreateDevice`. It probably means "supported".

2) Complementary restriction is missing. I.e. "If none of the sparse resource features are supported, then no queue family **must** support this bit". AMD would be in violation of this.

3) Would it make sense to similarly restrict `vkCreateDevice`? I.e. `pQueueCreateInfos` vs `pEnabledFeatures->sparseBinding`; something like: 

> - If `pQueueCreateInfos` does not contain any queue families with `VK_QUEUE_SPARSE_BINDING_BIT`, and `pEnabledFeatures->sparseBinding` is `VK_TRUE`, then `vkCreateDevice` returns `VK_ERROR_FEATURE_NOT_PRESENT`.
> - If `pQueueCreateInfos` does contain a queue family that supports only `VK_QUEUE_SPARSE_BINDING_BIT`, then `pEnabledFeatures->sparseBinding` **must** be `VK_TRUE`.

Or would that be too annoying to the user?

**Comment by Tobski** [comment]
> It does not make sense to speak of features being "enabled". This is obtained by vkGetPhysicalDeviceQueueFamilyProperties, i.e. well before features are enabled by vkCreateDevice. It probably means "supported".

Agreed. This should say "supported".

> Complementary restriction is missing. I.e. "If none of the sparse resource features are supported, then no queue family must support this bit". AMD would be in violation of this.

I'm generally against forcing anyone (especially the company I work for now 😛) to change their behaviour if it wasn't already in the spec, but if you feel strongly, raise it in a PR and we'll consider the implications.

> Or would that be too annoying to the user?

The latter is just overly specific. If someone wants to create a queue with no features enabled, it's fairly harmless (they'll find out as soon as they use it for anything that they've done it wrong).

If anyone tried the former condition, it might break a driver if someone isn't careful (e.g. a queue lookup where there is no queue) - so arguably it either needs a VU, a CTS test, or an error condition (and also a CTS test). I'd argue to just throw it in a VU, as that doesn't require any changes to existing drivers, and plugs a useless and untested part of the API.


If you are able to raise a PR for any of this, tag me and I'll try to review it ASAP.

**Comment by krOoze** [comment]
> I'm generally against forcing anyone (especially the company I work for now 😛) to change their behaviour if it wasn't already in the spec, but if you feel strongly, raise it in a PR and we'll consider the implications.

Taking the red pill, eh?

It is so nice the desktop can adapt and update within 1/2 year (or sooner if not Windows Update). I wish Android would be the same.
Though technically it is still incompatible spec change. Though it seems the restriction was originally intended by the author (because the reciprocal restriction exists) -- that's a common mistake to make.

It would be nice if AMD stopped reporting this queue bit all the same. It is a bit annoying, like those queue families with zero queues on some other implementations.

> The latter is just overly specific. If someone wants to create a queue with no features enabled, it's fairly harmless (they'll find out as soon as they use it for anything that they've done it wrong).

I suppose so, as the spec should already be handling sparse queues combined with some other bit(s).

>  I'd argue to just throw it in a VU, as that doesn't require any changes to existing drivers, and plugs a useless and untested part of the API.

Though again, it would unfortunatelly be incompatible spec change.
But it allows creation of sparse Resources and such, which is probably unintended, as you say.

**Comment by krOoze** [comment]
PS: ad 3b:

 I wonder if there would be some benefit to having new API, where the user would specify only the bits he will use. I.e. `VkDeviceQueueCreateInfo2`, or `vkGetDeviceQueue2` with `VkQueueFlags usedFlags`. The driver could unload some unneeded parts?

That's the place where this proposed restriction would fit best...

**Comment by Tobski** [comment]
> Though again, it would unfortunatelly be incompatible spec change.

Eh. I think in this case it's fine - nobody necessarily intended that to work in the first place, and if it does, there's nothing a developer can be doing with it. So I doubt anyone is doing it in practice - this is very much at the level of bug fix territory.

**Comment by oddhack** [comment]
Closing. If you want to propose a PR as @tobski suggests please do, but this seems dead.
