### ISSUE TITLE
Redundant requirement for vkGetDeviceGroupPeerMemoryFeatures

### ISSUE THREAD

**Issue by tumnus** [KhronosGroup/Vulkan-Docs#729]
From 1.1.77 Don't need that final bullet...

Valid Usage (Implicit)
• device must be a valid VkDevice handle
• pPeerMemoryFeatures must be a valid pointer to a VkPeerMemoryFeatureFlags value
• pPeerMemoryFeatures must not be 0

**Comment by cdwfs** [comment]
Good catch, thanks!

**Comment by Tobski** [comment]
@jeffbolznv Will take a look at this.

**Comment by oddhack** [comment]
This should be fixed in the 1.1.79 spec update.
