### ISSUE TITLE
Missing object lifetime rule for vkDestroy(Pipeline|DescriptorSet)Layout "Valid Usage"

### ISSUE THREAD

**Issue by Kangz** [KhronosGroup/Vulkan-Docs#730]
The "Object lifetime" section of the spec (2.3.1) defines the constraint for Vulkan objects to be destroyed. In some cases the constraints are also written in the "Valid Usage" of the respective `vkDestroyFoo` command. For example `vkDestroySampler` says:

> All submitted commands that refer to sampler must have completed execution

However the `vkDestroyPipelineLayout` and `vkDestroyDescriptorSetLayout` (and maybe others?) don't mention any constraints. This is a problem because the "Object Lifetime" section isn't very discoverable since it doesn't appear on the ToC in the sidebar, and at least 3 Vulkan developers I know thought these objects could be destroyed at any time.

Please consider adding the lifetime constraints in the "Valid Usage" of these commands, thank you!

**Comment by cdwfs** [comment]
Thanks for the suggestion Corentin; I'll raise it internally for discussion. If you come across any other objects that could also potentially use a lifetime-related Valid Usage items, please add them to the thread here as well. Thanks!

**Comment by oddhack** [comment]
This should be fixed in the 1.1.82 spec update.

**Comment by krOoze** [comment]
Just to make sure:
`VkPipelineLayout` **can** be destroyed when command buffer is in _executable_, or _pending_, or invalid state?

BTW why is it outright invalid usage? Should destroying it not move the command buffer into the _invalid_ state as it works for other objects?

I mean it is weird that just `vkDestroyPipelineLayout(...);` on _recording state_ cmdbuffer is invalid, while this is valid:
```
// cmdbuffer in recording state
vkDestroyImageView(...); // moves cmdbuffer to invalid state
vkDestroyPipelineLayout(...); // so this is valid now, yay
```

**Comment by jeffbolznv** [comment]
I agree that the behavior is unique and kind of unexpected, but the motivation is that some implementations may hold onto the bound pipeline layout and reference it during a draw command, so if further commands are recorded to the command buffer it could cause a crash. But this VU was meant to reflect the pre-existing behavior documented in the Object Lifetime section:

```
A sname:VkPipelineLayout object must: not be destroyed while any command
buffer that uses it is in the recording state.
```
