### ISSUE TITLE
VK_PIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXT vs TOP and BOTTOM

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#739]
The spec says:

> For conditional rendering operations, the pipeline stage where predicate read happens has no particular order relative to other stages.

Shouldn't it at least be after `VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT` and before `VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT`?

**Comment by jeffbolznv** [comment]
We discussed in the WG and agree (though, it potentially can be equal to top_of_pipe? I'm not sure if that's distinguishable from being immediately after top_of_pipe). Are you going to make the change?

**Comment by krOoze** [comment]
> (though, it potentially can be equal to top_of_pipe? I'm not sure if that's distinguishable from being immediately after top_of_pipe)

It is distinguishable. `STAGE_TOP_OF_PIPE` is logically before every other stage.
If you want to preserve `STAGE_CONDITIONAL_RENDERING` being in no particualr order with other stages, then it cannot be aliased with `TOP` (or `BOTTOM`).

> Are you going to make the change?

why not: #743.

**Comment by oddhack** [comment]
Closing this, since the underlying PR #743 was closed.
