### ISSUE TITLE
VkBufferImageCopy: bufferRowLength and padding unclear

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/Vulkan-Docs#752]
The spec. (1.1.81) for `VkBufferImageCopy's` `bufferRowLength` states only

> specify the data in buffer memory ... and control the addressing calculations ... in buffer memory.

Valid Usage states simply

> bufferRowLength must be 0, or greater than or equal to the width member of imageExtent

A reader then has to search for more instances of bufferRowLength, or scroll down in the document past the lengthy valid usage statements, to find, in the pseudo-code in section 18.4.1, a mere hint that bufferRowLength is expressed in texels. The spec for `VkBufferImageCopy` needs to state this explicitly, as it does for imageExtent and imageOffset, at the first quote above.

Incidentally vk.xml has a comment that bufferRowLength is in texels. It has similar comments for imageExtent & imageOffset except that it uses "pixels" where the spec. uses "texels."

Since bufferRowLength is in texels the question then arises what does one do for a texture/format whose row is not a multiple of 4 bytes, e.g, a 3 texel wide VK_FORMAT_R8G8B8_UNORM image, given that valid usage states bufferOffset must be a multiple of 4? I can find no indication. Do you set bufferRowLength=3 (texels) and pray the driver will round to the next 4-byte multiple for each row it copies, to match the texture one packed for GL's default UNPACK_ALIGNMENT of 4? I failed to find any indication of such behavior in the spec. If the spec already states this somewhere, there needs to be a link to it from VkBufferImageCopy.

**Comment by MarkCallow** [comment]
To further explain the requested clarifications and the info I am looking for, I will describe what led to me opening this issue.

I have textures packed for OpenGL, that is using the default GL_UNPACK_ALIGNMENT of 4. I need to understand how to copy from a staging buffer an image where, due to the format and texel width, padding was necessary to meet the unpack alignment. I first thought that I could just specify the byte row length instead of 0 for `bufferRowLength`. An explicit statement that the unit is texels in the sentences describing `bufferRowLength` (& `bufferRowHeight`) would have helped me avoid wasted time.

The phrase "tightly packed" is not defined. The natural interpretation is that there is no padding between rows. However the Valid Usage statement that `bufferOffset` must be a multiple of 4 makes me wonder.

If truly there is no padding between rows, it looks as if I'll need to add a copy region for each row of a texture packed for OpenGL, whose format and width lead to a "tightly packed" byte row length that is not a multiple of 4. I am hoping for a simpler and lower overhead alternative especially as there must be many such texture images out there due to the OpenGL default.

**Comment by MarkCallow** [comment]
I've now implemented loading of textures that have row padding. That has shown me they must be tightly packed in the staging buffer with no rounding of rows. So I have to copy the data to the staging buffer a row at a time. I must say it is a bit of a pain. 

So this issue becomes simply a request to document clearly that `bufferRowLength` and `bufferRowHeight` are in texels.

One oddity I noticed is that valid usage requires staging buffer offsets to be a multiple of both 4 and the element size of the image. In the case when the latter is 3, that means you need to round to a multiple of 12. Given that this is a _staging_ buffer, it is not clear why Vulkan is so fussy about the buffer offsets.

**Comment by TomOlson** [comment]
> So this issue becomes simply a request to document clearly that bufferRowLength and bufferRowHeight are in texels.

@MarkCallow,  we agree that that should be done. As an old hand at spec-writing, maybe you could raise a PR? Or let us know that you're not going ot. 

We are more puzzled about the padding question - something sounds wrong. You can definitely have padding in the staging buffer, and you should definitely be able to blast the data to the buffer in one go. The whole point of the imageExtent is to make it possible to copy a subregion of the buffer, as in section 18.4.1. 

I think; maybe a Real Programmer will correct me?

**Comment by MarkCallow** [comment]
I am talking about the padding required to be compliant with the default GL_UNPACK_ALIGNMENT of 4. Basically each row is padded to a multiple of 4. The example I created to test this case is a 270 x 270 texel VK_FORMAT_R8G8B8_UNORM format image. So there are 810 bytes (270 x 3) of image data + 2 bytes of padding in each row.

The only way I can see to handle this case is to copy each row into the staging buffer stripping the padding in the process. The method I had hoped to use was copy the whole padded image into the staging buffer and use the region's `bufferRowLength` to make `VkCmdCopyBufferToImage` copy only 810 pixels. However `bufferRowLength` "control(s) the addressing calculations of data in buffer memory" and is in texels. If I leave it 0 or set it to 270 texels, then it pulls the next row starting with the padding of the previous row so the image ends up with a diagonal offset.

I'll take a look at making a PR. Hopefully the CI provides sufficient testing so I don't need to install all the tools to build the spec. myself.

**Comment by MarkCallow** [comment]
I'm going to spin off the GL_UNPACK_ALIGNMENT question to a new issue.

**Comment by MarkCallow** [comment]
PR #781 sent.

**Comment by oddhack** [comment]
This should be closed in the 1.1.85 spec update.

**Comment by HumanZero** [comment]
"bufferRowLength" should specify source row length with padding in bytes, which allows to easily handle already mentioned issues with different paddings per texel and row, as well as makes it explicit. This is also how D3D12 (D3D12_SUBRESOURCE_FOOTPRINT and D3D12_PLACED_SUBRESOURCE_FOOTPRINT) and Metal (copyFromBuffer:sourceOffset:sourceBytesPerRow:sourceBytesPerImage: . . .) consume data from staging buffers, which makes engine common abstraction layer simple to write (and it is how NVidia drivers interpreted this filed in the past). After specifying it to be in texels, it is unclear what happens if row stores texel blocks of compressed texture (I suppose it then specifies texel blocks count). It is now also breaking earlier mentioned abstraction and requires providing additional cumbersome parameters in such RHI to re-calculate row length in texels from row length in bytes.

**Comment by HumanZero** [comment]
This is also breaking change for any Vulkan application as it will result in textures being uploaded in invalid way from the moment anybody will update drivers to ones that implement this new behavior.

**Comment by krOoze** [comment]
This was practically a typo fix. The pseudocode explaining the addressing in depth always implied it is in texels.

**Comment by zakarumych** [comment]
This section suggests that those values are in bytes

```
For each (x,y,z,layer) coordinate, bytes in the buffer are accessed at offsets in the range [texelOffset, texelOffset + blockSize), where:

    texelOffset = bufferOffset + (x × blockSize) + (y × rowExtent) + (z × sliceExtent) + (layer × layerExtent)

    blockSize is the size of the block in bytes for the format

    rowExtent = max(bufferRowLength, ⌈imageExtent.width / blockWidth⌉ × blockSize)

    sliceExtent = max(bufferImageHeight, imageExtent.height × rowExtent)

    layerExtent = imageExtent.depth × sliceExtent
```

It is [here in the spec](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#copies-buffers-images)
