### ISSUE TITLE
VK_ACCESS_INDIRECT_COMMAND_READ_BIT documentation is misleading

### ISSUE THREAD

**Issue by MagicPoncho** [KhronosGroup/Vulkan-Docs#757]
The documentation for VK_ACCESS_INDIRECT_COMMAND_READ_BIT in VkAccessFlagBits (6.1.3. Access Types) states: "VK_ACCESS_INDIRECT_COMMAND_READ_BIT specifies read access to an indirect command structure read as part of an indirect drawing or dispatch command."

However the "or dispatch command" does not seem to track with the rest of the documentation.

The table lower in the same section shows "Supported pipeline stages" for access flags (only VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT is listed as a valid for VK_ACCESS_INDIRECT_COMMAND_READ_BIT).

Similarly, the validation layer returns "dstAccessMask (0x1) is not supported by dstStageMask (0x800)". 

The "or dispatch" should probably be removed.

**Comment by chrisforbes** [comment]
`VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT` exists in the compute pipeline as well, and is the stage where this access occurs for indirect dispatches.

**Comment by MagicPoncho** [comment]
In that case, I petition that VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT be renamed VK_PIPELINE_STAGE_INDIRECT_BIT.  :)
