### ISSUE TITLE
Does Vulkan's current API support multiple physical devices to create a logical device?

### ISSUE THREAD

**Issue by gchihiha** [KhronosGroup/Vulkan-Docs#758]
Does Vulkan's current API support multiple physical devices to create a logical device?
version 1.1.82
vkEnumeratePhysicalDeviceGroups
only:
vkCreateDevice

**Comment by pdaniell-nv** [comment]
You can use the `VkDeviceGroupDeviceCreateInfo` extension structure and extend the `VkDeviceCreateInfo` structure to specify which physical devices from a physical device group should be used to create the logical device. With this logical device you can use the device mask and other multi-device features, based on the implementation's capabilities, to do multi-device work.

Let us know if there is something in the spec that you feel needs clarification.

**Comment by gchihiha** [comment]
I still have some questions:

There are 4 physical devices in the physical device group: pd0 pd1 pd2 pd3
There is also a physical device group with 2 physical devices: pd4 pd5

`VkDeviceGroupDeviceCreateInfo dc_group_info;
Dc_group_info.physicalDeviceCount = 4;
Std::vector<VkPhysicalDevice> four_physical_device{pd0,pd1,pd2,pd3};
dc_group_info.pPhysicalDevices = &four_physical_device[0];
...

VkDeviceCreateInfo device_create_info;
...
dc_info.pNext = dc_group_info;

...
VkDevice device_handle;
Auto ret = vkCreateDevice(physicalDevice_handle, &device_create_info, nullptr, &device_handle);`

1.physicalDevice_handle Which physical device handle should I choose here? Any one? Or any of four_physical_device? Is there a difference between choosing different physical devices?

2.VkDeviceCreateInfo.pQueueCreateInfos can only store the queue of four_physical_device?



Thank you very much!

**Comment by gchihiha** [comment]
I still have some questions:

There are 4 physical devices in the physical device group: pd0 pd1 pd2 pd3
There is also a physical device group with 2 physical devices: pd4 pd5

```
VkDeviceGroupDeviceCreateInfo dc_group_info;
Dc_group_info.physicalDeviceCount = 4;
Std::vector<VkPhysicalDevice> four_physical_device{pd0,pd1,pd2,pd3};
dc_group_info.pPhysicalDevices = &four_physical_device[0];
...

VkDeviceCreateInfo device_create_info;
...
dc_info.pNext = dc_group_info;

...
VkDevice device_handle;
Auto ret = vkCreateDevice(physicalDevice_handle, &device_create_info, nullptr, &device_handle);
```

1.physicalDevice_handle Which physical device handle should I choose here? Any one? Or any of four_physical_device? Is there a difference between choosing different physical devices?

2.VkDeviceCreateInfo.pQueueCreateInfos can only store the queue of four_physical_device?



Thank you very much!

**Comment by pdaniell-nv** [comment]
1. Yes, it can be any one of them.

2. This is the queue of the "logical" device so is associated with all physical devices used to create the logical device. In your case, everything in four_physical_device.

**Comment by gchihiha** [comment]
thank you very much!!

**Comment by gchihiha** [comment]
thank you very much!!

**Comment by oddhack** [comment]
@gchihiha have your questions been answered fully? If so, please close this issue. Thanks!
