### ISSUE TITLE
"image element" not defined for uncompressed formats

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/Vulkan-Docs#763]
The glossary tells you:

    Element Size

    The size (in bytes) used to store one element of an uncompressed format or the size
    (in bytes) used to store one block of a block-compressed format.

However element is not defined anywhere. Is it 1 component or 1 texel? An example in the man page for vkCmdCopyImage suggests that it is a texel.

The best I can come up searching the spec. is

    Each format has an element size, the number of bytes used to stored one element
    or one compressed block, with the value of the element size listed in VkFormat.

The `VkFormat` link takes you to the list of image formats but what is the element size in, e.g, 
`VK_FORMAT_R8G8B8_UNORM`? It's not 8, the only number visible.

Please add a definition to the glossary and add explanation to the above quote about what element size being listed in `Vkformat` means.

**Comment by oddhack** [comment]
WG notes that it means a texel, and asks if you could make a PR to that effect?

**Comment by MarkCallow** [comment]
Okay but I still don't know what "the value of the element size listed in VkFormat" refers to.  Is it, e.g., the `R8G8B8` in the format name? That only gives the value of the element size by mental interpolation.

**Comment by janharaldfredriksen-arm** [comment]
In the spec, the

> with the value of the element size listed in VkFormat.

quote hyperlinks to the "30.3.1. Format Definition" section, which describes each of the formats with wording such as:

> VK_FORMAT_R8G8B8_UNORM specifies a three-component, 24-bit unsigned normalized format that has an 8-bit R component in byte 0, an 8-bit G component in byte 1, and an 8-bit B component in byte 2.

The element/texel size in this example is 24-bit.

The WG acknowledges that this isn't entirely clear and that it would be a good idea to define the term "element size" (or some alternative to it) in the Format Definition section and use that in the format descriptions.

**Comment by krOoze** [comment]
It would be nice if some more disctinct name could be used instead of generic "element". At least consistently "data element" ("datel", lol).

**Comment by MarkCallow** [comment]
@krOoze, the WG is discussing formalizing its use of the term "element". I'll leave such a change as you propose up to them.

**Comment by oddhack** [comment]
This has been addressed in the 1.1.94 spec update (the fix started out straightforward, then got progressively less straightforward and touched more and more spec language - there will be some followon changes to make sure terminology used for compressed / uncompressed / multiplanar formats is really all consistent, but these changes are a good start).
