### ISSUE TITLE
What is default value for `optional` XML attribute

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#769]
E.g. `VkDeviceQueueCreateInfo::queueCount` does not have `optional` XML attribute despite being subject to it.

1) Is `optional` attribute optional (for pointers, handles, bitmasks, and array sizes) in the first place
2) If so, what is the implicit\default value for `optional` attribute

The schema document does not seem to say.

**Comment by oddhack** [comment]
Should be fixed in the 1.1.87 spec update.
