### ISSUE TITLE
[registry] registry.rnc doesn't match current schema

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-Docs#77]
I tripped over some failures when trying to do a `make validate` (I am trying to figure out how to produce the `doc/specs/vulkan/protos/*.txt` files for newly added extension commands, and wondered if there were errors in my vk.xml).

It looks to me like registry.rnc doesn't match the actual contents of vk.xml and I assume that it's just out of date and should be corrected to match vk.xml. The `namespace` addition to `Enums` might be the odd one out where vk.xml is wrong - it only shows up in the debug report extension and it seems unnecessary and inconsistent with the KHR WSI extensions. The debug report parts of vk.xml might just be a bit old since e.g. it doesn't use `len="null-terminated"` for its strings either.

Here is the diff of what I changed to get `make validate` to run cleanly:

```diff
diff --git a/src/spec/registry.rnc b/src/spec/registry.rnc
index 0eb4502..06ca28b 100644
--- a/src/spec/registry.rnc
+++ b/src/spec/registry.rnc
@@ -51,9 +51,9 @@ Vendorids = element vendorids {
 #   name - author ID of the vendor
 #   id - Khronos vendor ID
 #   comment - unused
-Tag = element tag {
+Vendorid = element vendorid {
     attribute name { text } ,
-    attribute author { text } ,
+    attribute id { Integer } ,
     Comment ?
 }

@@ -170,6 +170,7 @@ Type = element type {
 #   type - "enum" or "bitmask", if present
 #   comment - unused
 Enums = element enums {
+    attribute namespace { text } ? ,
     attribute name { text } ? ,
     attribute type { text } ? ,
     attribute start { Integer } ? ,
@@ -267,6 +268,8 @@ Commands = element commands {
 #       objects that are not parameters of the command, but
 #       are related to them and also require external synchronization.
 Command = element command {
+    attribute successcodes { text } ? ,
+    attribute errorcodes { text } ? ,
     attribute queues { text } ? ,
     attribute renderpass { text } ? ,
     attribute cmdbufferlevel { text } ? ,
```

**Comment by oddhack** [comment]
Thanks! I made similar updates in the 1.0.4 update that was just pushed. 'make validate' works now.
