### ISSUE TITLE
`VkBufferImageCopy` has no equivalent to GL_UNPACK_ALIGNMENT

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/Vulkan-Docs#776]
`GL_UNPACK_ALIGNMENT` allows the number of _bytes_ in rows of incoming image data to be padded to a multiple of some value. The default value in OpenGL is 4 which means there are a lot of texture images out there with rows padded to 4 bytes. `VkBufferImageCopy` does not have any equivalent functionality which makes loading formats whose texel size is < 4 bytes and whose width is such that the number of bytes in a row is not a multiple of 4, awkward.

Is this a deliberate or accidental omission? VkBufferImageCopy` has equivalents for most of the other unpack parameters. If accidental, please look into adding this functionality.

**Comment by ratchetfreak** [comment]
That's what the bufferRowLength field is about. That lets you have row strides that are not equal to width*texelSize

**Comment by MarkCallow** [comment]
@ratchetfreak, no it is not. `bufferRowLength` is equivalent to `GL_UNPACK_ROW_LENGTH`.  It is, as you say, is the number of _texels_ between rows. `GL_UNPACK_ALIGNMENT` affects the number of _bytes_ between rows. Checkout section 8.4.4.1 and equations 8.1 & 8.2 in the OpenGL 4.5 spec.

**Comment by MarkCallow** [comment]
A related inconvenience is that valid usage can require, e.g, in the case of an R8G8B8 format, padding to the next multiple of 12 bytes. This is because bufferOffset has to be both a multiple of 4 and a multiple of the format's element (i.e. texel) size.

**Comment by oddhack** [comment]
It is a deliberate omission, for performance reasons. We don't plan to address this in the Vulkan implementation.
