### ISSUE TITLE
Self-dependency stages potentially over-restricted?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#777]
>If `srcSubpass` is equal to `dstSubpass` and not all of the stages in `srcStageMask` and `dstStageMask` are _framebuffer-space_ stages, the _logically latest_ pipeline stage in `srcStageMask` **must** be _logically earlier_ than or equal to the _logically earliest_ pipeline stage in `dstStageMask`

>Self-dependencies **must** not have any earlier pipeline stages depend on any later pipeline stages (according to the order of _graphics pipeline stages_), unless all of the stages are _framebuffer-space stages_.

is potentially over-restricted?

Example:
`srcStageMask = VK_PIPELINE_STAGE_VERTEX_SHADER_BIT | VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT`
and
`dstStageMask = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT`
(`FRAGMENT` is earlier than `COLOR`, but both are framebuffer-space. `VERTEX` is still earlier than `dstStageMask`)

It may be cleaner to express it as two subpass dependencies, but still; seems like an artificial restriction.

**Comment by oddhack** [comment]
This should be fixed in the 1.1.107 spec update.
