### ISSUE TITLE
about VkDeviceQueueCreateInfo::pQueuePriorities

### ISSUE THREAD

**Issue by gchihiha** [KhronosGroup/Vulkan-Docs#786]
```
VkDeviceCreateInfo dc_info{.....};
VkDeviceQueueCreateInfo qc_info{......};

dc_info.queueCreateInfoCount = 1;
dc_info.pQueueCreateInfos = &qc_info;
....

```
After creating the logical device,
I am modifying qc_info.pQueuePriorities[0] = 0.1
Will it affect the queue priority?

**Comment by krOoze** [comment]
No.
Unless otherwisely said, Vulkan does *not* hold on to pointers you pass to it.

**Comment by gchihiha** [comment]
thank you!
