### ISSUE TITLE
Ambiguous PFN_vkDebugUtilsMessengerCallbackEXT type parameter

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#788]
In `PFN_vkDebugUtilsMessengerCallbackEXT` type parameter is declared as:
`VkDebugUtilsMessageTypeFlagsEXT messageType`,
but in the parameter descriptions it says:
> `messageTypes` [sic] specifies the `VkDebugUtilsMessageTypeFlagBitsEXT` that triggered this callback.

So, is it a bitmask, or a single bit?

PS: `vkSubmitDebugUtilsMessageEXT` clearly has bitmask, so that is probably the correct case.

**Comment by MarkY-LunarG** [comment]
Yes, the thought was that while a severity might be singular, a message could conform to multiple types of messages.  We don't have any that conform to that style now, but we wanted to support it in the future.  I think your PR #791 resolves this.

**Comment by krOoze** [comment]
I am getting sidetracked with #791. Instead, I am making surgical PR #800 for this...
