### ISSUE TITLE
`VkDebugUtilsObjectNameInfoEXT` overrestricted?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#789]
`VkDebugUtilsObjectNameInfoEXT` requires real `objectHandle`.
`VkDebugUtilsMessengerCallbackDataEXT` requires `objectCount > 0` (BTW `pObjects` array VU is missing &mdash; weird)

So when I do `vkSubmitDebugUtilsMessageEXT` I am required to provide valid object handle.
Considering the layers themselves do return `UNKNOWN` and `0` sometimes (and it even makes sense e.g. in creation functions, where there's no valid handle), isn't this overrestricted?

**Comment by oddhack** [comment]
Will ask Mark to take a look at this, if he has time.

**Comment by MarkY-LunarG** [comment]
`objectCount` and `pObjects` in `VkDebugUtilsMessengerCallbackDataEXT` should be optional (and able to be `0` and `NULL`).  I'll modify the XML.

As far as the objects themselves go, there were two cases to the `VkDebugUtilsObjectNameInfoEXT`.

1. For use in `vkSetDebugUtilsObjectNameEXT` we thought that passing in `UNKNOWN` and `NULL` information was invalid.
2. When returning the information to a callback from inside the layers, our original thought was that the layers would know what they were dealing with.  But, it still might not for certain extension and so `UNKNOWN` should still have been allowed for this case.

Because of this, I'll move the "can't be `UNKNOWN`" VU from the `VkDebugUtilsObjectNameInfoEXT` up to the `vkSetDebugUtilsObjectNameEXT` section, which is where it belongs.

**Comment by krOoze** [comment]
Would it make sense to allow 0 Object count and keep object type VU?

**Comment by MarkY-LunarG** [comment]
Here are the new sections:

![screenshot from 2018-09-10 12-25-09](https://user-images.githubusercontent.com/16328578/45316683-fb8ad600-b4f4-11e8-84fc-53cbe348ee33.png)

![screenshot from 2018-09-10 12-25-41](https://user-images.githubusercontent.com/16328578/45316692-ff1e5d00-b4f4-11e8-808e-584d3da3ec9f.png)

**Comment by MarkY-LunarG** [comment]
I also added a VU to `vkSubmitDebugUtilsMessageEXT` for the same kind of restriction I put on `vkSetDebugUtilsObjectNameEXT`.

So, `vkSubmitDebugUtilsMessageEXT` now has the manual VU info:

```
+.Valid Usage
+****
+* If pname:pCallbackData\->objectCount is greater than 0, then for each
+  pname:pCallbackData\->objects, the value of pname:objectHandle value
+  must: not be ename:VK_NULL_HANDLE.
+* If pname:pCallbackData\->objectCount is greater than 0, then for each
+  pname:pCallbackData\->objects, the value of pname:objectHandle value
+  must: be a Vulkan object of the type associated with pname:objectType.
+****
+
```

**Comment by MarkY-LunarG** [comment]
Just noticed that wording stinks.  I'll fix it.

**Comment by MarkY-LunarG** [comment]
```
+.Valid Usage
+****
+* If pname:pCallbackData\->objectCount is greater than 0, then for
+  each object in pname:pCallbackData\->objects, the value of
+  pname:objectHandle must: not be ename:VK_NULL_HANDLE.
+* If pname:pCallbackData\->objectCount is greater than 0, then for
+  each object in pname:pCallbackData\->objects, the value of
+  pname:objectHandle must: be a Vulkan object of the type associated
+  with pname:objectType.
+****
```

**Comment by krOoze** [comment]
Somewhat redundant to state "if count not zero". Maybe:

> objectHandle member of each VkStruct element in objects array must not be null

Would it make sense to allow valid type with null object? It used to be used for validation msges from `vkCreate*` cmds.

**Comment by krOoze** [comment]
PS also similarly, would unknown types with valid object handles make sense in the general case?

**Comment by MarkY-LunarG** [comment]
> Would it make sense to allow valid type with null object? It used to be used for validation msges from vkCreate* cmds.

Oops, sorry, I remember you mentioned this before.  So you call `vkSubmitDebugUtilsMessageEXT` with a NULL handle?  I didn't think anyone would do that, but if you use it, I can relax that wording.

**Comment by MarkY-LunarG** [comment]
> PS also similarly, would unknown types with valid object handles make sense in the general case?

Originally, our thinking was this: why would you pass yourself an object if you didn't know what it was OR you didn't have a handle for it.  You would just send a message without the object's info in the list of objects.

Plus, the loader/layers don't know how to find the content for the object if it's unknown, so when the call enters the loader, it won't be able to find any data associated with it (i.e. the object name or tag information)?  Therefore, we decided that we didn't want to allow Unknown.

**Comment by krOoze** [comment]
> I didn't think anyone would do that, but if you use it, I can relax that wording.

I don't, but I remember it from the Validation Layers with the old debug extension. So would make sense to allow the Application to do the same (if that is still so in the layers)...

> Originally, our thinking was this: why would you pass yourself an object if you didn't know what it was OR you didn't have a handle for it. You would just send a message without the object's info in the list of objects.

Right, ok. It's not a big deal. It would only make sense for dispatchable (unique) handles, and in some contrieved way only when someone intentionally forgets the type for some weird reason.

**Comment by MarkY-LunarG** [comment]
Ok, I've relaxed the NULL value for the submit.

**Comment by oddhack** [comment]
@krOoze same question as for #797 / #790 - did PR #794 fix this issue?

**Comment by krOoze** [comment]
Yeah we reached some consensus there.
