### ISSUE TITLE
`VkDebugUtilsMessengerCallbackDataEXT` array members

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#790]
1) Why do `VkDebugUtilsMessengerCallbackDataEXT` array members have missing VUs (except `objectCount`)

2) Why are not the array/pointers `const`?

**Comment by oddhack** [comment]
Will ask Mark to take a look at this, if he has time.

**Comment by MarkY-LunarG** [comment]
Not sure why, but these had "noatuovalidity" in their tags so they didn't expand.  `const` isn't needed because the only places `VkDebugUtilsMessengerCallbackDataEXT` is used, it itself is a pointer and `const`.  If anything, the `const` in front of `pMessageIdName` is overkill.  I could remove that if necessary, but I'm not sure it's worth changing the interface, do you?

**Comment by MarkY-LunarG** [comment]
I'm going to fix the "noautovalidity" issue in a PR shortly.

**Comment by krOoze** [comment]
That array VU looks like the wrong type (intended for arrays that return `count`).

Per the `const` issue, I spam it everywhere, so I run into this issue when trying to assingn const variable into the non-const pointer, ergo compiler says nope.

**Comment by MarkY-LunarG** [comment]
> That array VUs look like the wrong type (intended for arrays that return `count`).

That's actually the VUs automatically generated by just remove the "noautovalidity" flag on the XML.  I can manually add the VU statement.  It seems like we want this type of statement, though, any time the application passes in this struct, but not when we return it.

> Per the `const` issue, I spam it everywhere, so I run into this issue when trying to assingn const variable into the non-const pointer, ergo compiler says nope. PS: it would not be so api breaking change to add as const can be assigned non-const var.

My concern was mostly related to the loader and layers that implement this extension.  I'll have to look into those separately.  I also know AMD implements this, so they'd have to potentially change as well.

**Comment by krOoze** [comment]
> That's actually the VUs automatically generated by just remove the "noautovalidity" flag on the XML. 

It's finicky, IIRC one has to get the `optional` attributes of both the array and the count correctly. The VU(I) then looks e.g. like this:

> If `dependencyCount` is not `0`, `pDependencies` **must** be a valid pointer to an array of `dependencyCount` valid `VkSubpassDependency` structures

The XML for above is:

```
<member optional="true"><type>uint32_t</type>       <name>dependencyCount</name></member>
<member len="dependencyCount">const <type>VkSubpassDependency</type>* <name>pDependencies</name></member>
```

So apparently `optional` on the count, but not the array pointer.

**Comment by MarkY-LunarG** [comment]
Ok, I updated that in the PR.

**Comment by oddhack** [comment]
@krooze same question as for #797 - did PR #794 fix this issue?

**Comment by krOoze** [comment]
Seems fixed to me.
