### ISSUE TITLE
Task list for VK_KHR_driver_properties release

### ISSUE THREAD

**Issue by drakos-amd** [KhronosGroup/Vulkan-Docs#795]
The Khronos board of promoters have recently ratified a new Vulkan extension called `VK_KHR_driver_properties`. This extension provides a new physical device query which allows retrieving information about the driver implementation, allowing applications to determine which physical device corresponds to which particular vendor's driver, and which conformance test suite version the driver implementation is compliant with.

The task list for the `VK_KHR_driver_properties` extension release is:
- [x] Headers, specs, etc. in https://github.com/KhronosGroup/Vulkan-Docs
- [x] Vulkan specification in the [Vulkan Registry](https://www.khronos.org/registry/vulkan/)
- [x] Vulkan Conformance Test Suite in https://github.com/KhronosGroup/VK-GL-CTS
- [x] Validation in https://github.com/KhronosGroup/Vulkan-ValidationLayers
- [x] Vulkan SDK at https://vulkan.lunarg.com/

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

If you have any questions or feedback, please leave comments below.

**Comment by alegal-arm** [comment]
CTS coverage released in https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.1.2.1
