### ISSUE TITLE
Synchronization model for VkDebugUtilsMessengerEXT poorly defined?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#797]
`VkDebugUtilsMessengerEXT` potentially interacts with everything, so it seems to me the synchronization model of it is insufficiently specified.

1. The `vkCreateDebugUtilsMessengerEXT` obviously has to modify some internal Vulkan state. The spec should perhaps state whether it is internally synchronized, or no other Vulkan calls should be happening.

2. The `vkDestroyDebugUtilsMessengerEXT` has it as externally synchronized, but it is not explicitly stated what things also access it. One would assume practically every Vulkan call **may** read this object in its duration. <s>The driver potentially even outside the duration...</s> (EDIT: I think async call not possible due to: "A callback will always be executed in the same thread as the originating Vulkan call.")

**Comment by oddhack** [comment]
Assigned to LunarG folks for triage.

**Comment by MarkY-LunarG** [comment]
Changes made in PR #794.

**Comment by oddhack** [comment]
@krOoze did #794 address both of these issues? If not, please recap what the remaining ones are.

**Comment by krOoze** [comment]
Yes, the PR addressed it quite directly banning execution of all other Vulkan commands in parallel.
