### ISSUE TITLE
image subresource {width, height, depth} not defined

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/Vulkan-Docs#798]
What are they? Are these just the {width,height,depth} of a single image at the `mipLevel` or something else? Consider a subresource where `layerCount > 0`.

**Comment by oddhack** [comment]
> What are they? Are these just the {width,height,depth} of a single image at the `mipLevel` or something else? Consider a subresource where `layerCount > 0`.

Is this still an issue now? If so, could you specify which width, height, depth you're referring to? I realized I was supposedly on the hook to address this but have totally forgotten the context from when this originally came up.

**Comment by MarkCallow** [comment]
> but have totally forgotten the context

Me too. I think it was in relation to `VkImageCopy`, `VkImageCopy2KHR` and `VkBufferImageCopy` but on reading them now I can't see what was causing me confusion. The `VkImageSubresourceLayers` struct only allows you to specify multiple layers and  all layers have the same width and height. I must have been confusing layers and levels when I wrote the 3rd sentence of the issue.`VkImageSubresourceLayers` only lets you specify a single level so presumably the `width`, `height` and  and `depth` of the `extent` parameter to these functions are those of the selected mip level. The only minor tweak I can see is to change

```
extent is the size in texels of the image to copy in width, height and depth
```

to

```
extent is the size in texels of the area of the image to copy in width, height and depth
```

**Comment by lewa-j** [comment]
area -> volume? Since it is three-dimensional

**Comment by oddhack** [comment]
We tweaked this a while back to just "extent is the size in texels of the image to copy...". Closing.
