### ISSUE TITLE
Typo Correction

### ISSUE THREAD

**Issue by codepilot** [KhronosGroup/Vulkan-Docs#8]
Under

Chapter 24. Rasterization

The members of the VkPipelineMultisampleStateCreateInfo structure are as follows:

~~alphaToOne~~ alphaToOneEnable controls whether the value of the alpha component of the fragment’s first color output is replaced with one as described in Multisample Coverage.

**Comment by oddhack** [comment]
Thanks! We have to pass most changes to the spec back through the internal discussion before signing off, but this looks like an obvious typo. Will get back to you.

**Comment by oddhack** [comment]
We will fix this at the next update from the internal repository, probably next Thursday.
