### ISSUE TITLE
Depth test behaviour when disabled

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#80]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#fragops-depth says:

> When disabled, the depth comparison and subsequent possible updates to the depth/stencil attachment value are bypassed and the fragment is passed to the next operation. The stencil value, however, can be modified as indicated above if the depth test passed.

I don't think that makes sense - how can it tell if the depth test passed, when the depth comparison was bypassed?

Maybe this meant "can be modified as indicated above **as** if the depth test passed" (i.e. it will run passOp).

**Comment by jeffbolznv** [comment]
yes, it should be "as if the depth test passed".

**Comment by janharaldfredriksen-arm** [comment]
We should fix this along with #81 since it touches the same paragraph.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.6 spec update.
