### ISSUE TITLE
Docs for VK_EXTERNAL_MEMORY_FEATURE_DEDICATED_ONLY_BIT refer to an outdated extension

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/Vulkan-Docs#801]
https://github.com/KhronosGroup/Vulkan-Docs/blob/2d900062e2c704c6eebb61e30f8d963936c27f1c/chapters/features.txt#L7017

This link should be to VK_KHR_dedicated_allocation, not to VK_NV_dedicated_allocation

**Comment by oddhack** [comment]
Agreed. We'll fix this soon.

**Comment by krOoze** [comment]
> `VK_KHR_dedicated_allocation`

Which in turn is part of 1.1.
Should just point to the specific chapter instead....

**Comment by oddhack** [comment]
This should be fixed in the 1.1.95 spec update (note: until I fix an odd Ruby/Debian dependency nightmare, the PDF targets in the registry are out of date).
