### ISSUE TITLE
Barycentric extension between vendors?

### ISSUE THREAD

**Issue by elviras9t** [KhronosGroup/Vulkan-Docs#803]
NVidia published fragment shader barycentric (for Turing GPU), AMD already has similar extension. Similar situation awaiting with half floats. What solutions are considered? 
- https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_NV_fragment_shader_barycentric
- https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_AMD_shader_explicit_vertex_parameter

**Comment by Tobski** [comment]
Hi @elviras9t - thanks for your feedback (and also thanks @krOoze for pointing out #706!).
 
There is interest within the Vulkan Working Group to produce a more widely supported extension for this functionality; we’re currently gathering feedback in order to help prioritise this against other features we’re working on. If you (or anyone else!) has any specific requirements or use cases for this item, please do let us know!

**Comment by helixd-2k18** [comment]
Float16 or 'half' support has already been added, but I am still puzzled by the vendor-to-vendor barycentric extension support...

**Comment by georgeouzou** [comment]
I have used both extensions and i have found 2 issues worth noting:

- With  VK_AMD_shader_explicit_vertex_parameter you need to apply a correction to [stable barycentric coordinates](https://gpuopen.com/learn/stable-barycentric-coordinates/) which is a bit extra work
- NV_fragment_shader_barycentric produces stable coordinates but as the in-spec issue (1) says:
"It should produce results approximately equal to those that would be obtained via conventional attribute interpolation". So the result with manual "software" interpolation will not be exactly the same as hardware interpolation.

**Comment by georgeouzou** [comment]
We now have a KHR extension for barycentrics! 
https://github.com/KhronosGroup/Vulkan-Docs/issues/1863

**Comment by Tobski** [comment]
Ah! We probably should've closed this when we released it - thanks for spotting this @georgeouzou. The relese is being tracked in #1863 as noted - if there's any questions they should be directed there. Please feel free to reopen this issue or start a new one if there are any requests not met by this extension.
