### ISSUE TITLE
Shared graphics memory under Windows

### ISSUE THREAD

**Issue by FMC64** [KhronosGroup/Vulkan-Docs#804]
Hello,

I noticed something interesting, developing my Vulkan application under both Linux and Windows. Under Linux, the function vkGetPhysicalDeviceMemoryProperties returns 12GB for a host heap and a device local heap of 6GB for my graphics card (this one has the VK_MEMORY_HEAP_DEVICE_LOCAL_BIT on the flags, the other has a no flag set so that's what I thought). The thing is that I got 16GB of RAM on my system. So I assumed Vulkan returns the maximum amount of RAM usable as graphics memory.

But on Windows 10 on the same PC, the function still returns the same amount for my GPU (6GB, which is normal) but it gives me 16GB for the "host" heap. I made some research about that, and it turns out that Microsoft authorizes up to the half of the RAM for graphics memory : 
https://docs.microsoft.com/en-us/windows-hardware/drivers/display/calculating-graphics-memory

And indeed, if I allocate more than 8GB of graphics memory on the host heap, I quickly got a crash with VK_ERROR_DEVICE_LOST error code (around transfer operations).

So I was wondering : why is Vulkan not returning 8GB for shared graphics memory under Windows ?
Temporarily I just cut in half the maximum of RAM amount my application could eat of the host heap under Windows and it does work, but it looks like a bad idea if Microsoft would change this limit in the future. The application seems also less portable this way.

Thanks by advance.

**Comment by krOoze** [comment]
> So I was wondering : why is Vulkan not returning 8GB for shared graphics memory under Windows?

It is, just apparently not with your driver.

E.g. I got 8 GB, and get 4-ish GB heap with AMD.
[this person](https://stackoverflow.com/questions/51624650/vulkan-memoryheaps-and-their-memorytypes/51631606) gets 75 % on NV.

**Comment by FMC64** [comment]
Oh, yeah I got a GTX 1060 6GB. Makes sense thanks.
So I guess I should first query Windows to get the precise amount of bytes on the RAM, and then clamp what my allocator can take on the heap. As I can see, my implementation would take up to ~2GB on your system, which is clearly not enough compared to its potential.

**Comment by krOoze** [comment]
If there is no way the GPU can allocate more than the reported value, then that is as good as a bug. 
You should report it to the vendor.

Then again `VK_ERROR_DEVICE_LOST` is suspicious in other ways. That looks even more bug like.

**Comment by krOoze** [comment]
BTW, you should not be allocating chunks larger than 4 GB as a single allocation.

If you are making a transfer of a large amount of memory, it may be the transfer itself takes too long, and so the OS restarts the driver?? What happens if you spread it to smaller chunks to transfer?

**Comment by oddhack** [comment]
@FMC64 if you believe this is a driver bug, could you close this issue? If it turns out to be something else, you can reopen, of course.

**Comment by FMC64** [comment]
@oddhack Yes, thanks for the support.

**Comment by pdaniell-nv** [comment]
I've created an NVIDIA internal bug to get this fixed. I think we're over-reporting the available memory on Windows.
