### ISSUE TITLE
Why vkDeviceWaitIdle is externsync, and vkQueueWaitIdle is not?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#809]
`vkDeviceWaitIdle` is externsync:

> Host access to all `VkQueue` objects created from `device` **must** be externally synchronized

But `vkQueueWaitIdle` does not have `externsync` on its `queue` parameter.

That sounds inconsistent. Potential spec bug?

**Comment by jeffbolznv** [comment]
We discussed it in the WG call and agreed that vkQueueWaitIdle should have externsync on the queue. Can you make a PR for it?

**Comment by krOoze** [comment]
@jeffbolznv Ok: #815
