### ISSUE TITLE
Depth test behaviour when passing

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#81]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#fragops-depth says:

> If the depth test fails, [...]. Otherwise, the fragment continues to the next operation and **the value of the depth framebuffer attachment at the sample’s location is conditionally written to the sample’s zf value**. In this case the stencil value is updated according to the function currently in effect for depth test success.
>
> Upon passing the depth test, a sample’s (possibly clamped) zf value is conditionally written to the depth framebuffer attachment based on the value of the depthWriteEnable member of VkPipelineDepthStencilStateCreateInfo. If depthWriteEnable is VK_TRUE the value is written, and if it is VK_FALSE the value is not written.

I don't understand the emphasised phrase - why would it write *to* the zf value, and what is it conditional on?

It looks like maybe the phrase is just an editing mistake and should be removed entirely, since the next paragraph gives a more understandable explanation of conditionally writing zf to the framebuffer.

**Comment by janharaldfredriksen-arm** [comment]
I agree this looks like an editing mistake. Looks like we could remove the bold sentence and move the following one to the next paragraph. We'll fix it.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.6 spec update.
