### ISSUE TITLE
VkPhysicalDeviceDriverPropertiesKHR::driverID should be VkDriverIdKHR, not uint32_t?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#811]
`VkPhysicalDeviceDriverPropertiesKHR::driverID` is defined as `uint32_t`, but later there is `VkDriverIdKHR`. So, shouldn't the `driverID` actually be of type `VkDriverIdKHR` ?

**Comment by oddhack** [comment]
This should be done in the 1.1.88 spec update.
