### ISSUE TITLE
Remove the VK_KHR_mir_surface

### ISSUE THREAD

**Issue by jekstrand** [KhronosGroup/Vulkan-Docs#814]
The Khronos Vulkan working group would like entirely remove the VK_KHR_mir_surface extension from the spec and headers.  The extension has only ever shipped in one non-LTS Ubuntu release and only in an old Ubuntu-specific patched version of the Intel Linux driver.  As far as anyone can tell, isn't explicitly used in any shipping applications.  There are, however, a few language bindings projects and WSI wrappers which have (probably untested) support for the extension.  Before removing it from the headers, we should make sure those projects have removed their support so that we don't break anything.

Known projects with some level of MIR Vulkan support:
- [ ] [SDL](https://libsdl.org/index.php)
- [x] [vulkano](https://docs.rs/vulkano/0.1.0/vulkano/swapchain/struct.Surface.html#method.from_mir)
- [ ] [Vulkan Haskell bindings](http://hackage.haskell.org/package/vulkan-2.1.0.0/docs/Graphics-Vulkan-Extensions-VK_KHR_mir_surface.html)
- [x] [GLFW](https://github.com/glfw/glfw/blob/8d3595fb4d4d919e27e1a755095ae1ffae5f50be/src/vulkan.c#L140)
- [x] [MoonVulkan](https://stetre.github.io/moonvulkan/doc/index.html)
- [x] [Ash](https://github.com/MaikKlein/ash)
- [ ] [SharpVK](https://github.com/FacticiusVir/SharpVk)
- [ ] https://github.com/mellinoe/vk
- [ ] [VulkanCore](https://github.com/discosultan/VulkanCore)
- [ ] [Tanagra](https://github.com/Mervill/Tanagra)
- [ ] [SharpVulkan](https://github.com/jwollen/SharpVulkan)
- [x] [VulkanSharp](https://github.com/mono/VulkanSharp)
- [ ] [dvulkan](https://github.com/ColonelThirtyTwo/dvulkan)
- [x] [ErupteD](https://github.com/ParticlePeter/ErupteD)
- [x] [LWJGL](https://github.com/LWJGL/lwjgl3)
- [x] https://github.com/realitix/vulkan
- [x] https://github.com/vulkan-go/vulkan
- [x] https://github.com/BeRo1985/pasvulkan
- [x] [Vulkan-Hpp](https://github.com/KhronosGroup/Vulkan-Hpp)
- [ ] The Vulkan loader
- [x] The Vulkan spec XML and headers

**Comment by jekstrand** [comment]
SDL bug: https://bugzilla.libsdl.org/show_bug.cgi?id=4288

**Comment by jekstrand** [comment]
From the SDL bug:

> We don't actually use this extension, it's simply part of the Khronos header
we've pulled.
>
> Please let us know when it's been removed from Khronos headers and we'll grab
new ones.
>
> Thanks!

**Comment by jekstrand** [comment]
> From the SDL bug:
> 
> > We don't actually use this extension, it's simply part of the Khronos header
> > we've pulled.
> > Please let us know when it's been removed from Khronos headers and we'll grab
> > new ones.
> > Thanks!

Turns out, that assertion was incorrect.  We're still waiting on SDL.

**Comment by programmerjake** [comment]
actually that's incorrect, see https://github.com/spurious/SDL-mirror/blob/d2fcd08e539f879ba1cfe864a5fd310cf8deb72b/src/video/mir/SDL_mirvulkan.c

**Comment by FacticiusVir** [comment]
Are you looking for a (relatively) comprehensive list of bindings, or is this change specifically known to be breaking for the listed projects?

**Comment by jekstrand** [comment]
> Are you looking for a (relatively) comprehensive list of bindings, or is this change specifically known to be breaking for the listed projects?

I googled for "VK_KHR_mir_surface" and the list above was the list of projects I found.  Clearly, that search wasn't quite comprehensive because someone just pointed out Ash, another Rust wrapper for Vulkan.

**Comment by FacticiusVir** [comment]
I can link you to about half a dozen notable C# bindings that reference or expose the Mir extension ([SharpVK](https://github.com/FacticiusVir/SharpVk/blob/ab07e7231fb5a45659ffce6daac3ceda099efcaf/src/SharpVk/Khronos/KhrExtensions.gen.cs#L70), [vk](https://github.com/mellinoe/vk/blob/bcf5e4eb0d28419773374f7d70ad1296f4456424/src/vk/Generated/Structures.gen.cs#L1636), [VulkanCore](https://github.com/discosultan/VulkanCore/blob/a2eeed262a3439ced85b623a29e5474a1e33edf8/Src/Constant.cs#L65), [Tanagra](https://github.com/Mervill/Tanagra/blob/7d196df273c23053bf7ea8f6cb1ce0012569fd0a/Vulkan/Generated/VulkanConstant.cs#L36), [SharpVulkan](https://github.com/jwollen/SharpVulkan/blob/5fdeff95793e40fe996ebafed8d0f4343be36469/Source/SharpVulkan/Generated/Enumerations.cs#L183), [VulkanSharp](https://github.com/mono/VulkanSharp/blob/7959250309c1c3231baec7174a1a36ed2b9a4da7/src/Vulkan/Enums.cs#L914)), as they're all derived from the XML spec - though most use automated code generators and I think only VulkanCore will specifically need updating by hand once the spec is updated.

You may also want to look up curated binding lists like [AwesomeVulkan](https://github.com/vinjn/awesome-vulkan#bindings).

**Comment by krOoze** [comment]
The point of semantic versioning is you don't have to be solving such problems.
Just mark the extension `deprecated`. Problem solved?

**Comment by BeRo1985** [comment]
At PasVulkan, the WSI support is controlled by compile-time-defines, so as a first step I have now removed the MIR-define from the default-defines for the Linux target, and as soon as it is completely removed from the specification, I will remove it completely.

At least thank you very much for the hint.

**Comment by oddhack** [comment]
As a first step, the registry XML has been updated to mark the extension as 'obsoletedby=""'. This doesn't affect the spec contents other than to move the extension appendix into a different subsection. As feedback from downstream is received, we'll move towards actually removing the extension entirely from the XML and Specification.

**Comment by oddhack** [comment]
We agreed to go ahead and remove this extension in the just-published 1.1.91 spec update, as it seemed that the remaining un-checked downstream consumers of the XML either weren't active enough to respond, or would just pick up then change and didn't care whether the extension was removed or not.
