### ISSUE TITLE
Clarify "Availability and Visibility Semantics" subsection in the memory model appendix

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [KhronosGroup/Vulkan-Docs#823]
The subsection
https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#memory-model-availability-visibility-semantics
states

> The implicit availability operation is program-ordered between the barrier or atomic and all other operations program-ordered before the write.

and likewise (in reverse) for the visibility op.

I find this rather misleading and hard to understand upon first read, as a barrier operation doesn't *really imply a write* .

I do now understand that it means the availability/visibility is program-ordered before/after the write of the atomic operation or the barrier, but that was not immediately clear until finishing reading the section after.

My point is saying that something "is program-ordered between the barrier and all other operations program-ordered [insert precedence relation] the write", in the context of a barrier is a very confounding.

**Comment by jeffbolznv** [comment]
Agreed, this looks like it was copy/paste mistakes when copying the language from the following section. I will fix it.

**Comment by oddhack** [comment]
Should be fixed in the 1.1.89 spec update.
