### ISSUE TITLE
Probably missing VK_PIPELINE_STAGE_SHADING_RATE_IMAGE_BIT_NV from the "graphics mesh shading pipeline" stage order spec

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [KhronosGroup/Vulkan-Docs#824]
In section 6.1.2 of the vulkan 1.1.87 spec I noticed that `VK_PIPELINE_STAGE_SHADING_RATE_IMAGE_BIT_NV` is present in the "primitive shading graphics pipeline" stage order just before early fragment tests.

In the "mesh shading graphics pipeline" stage order  there is no mention of `VK_PIPELINE_STAGE_SHADING_RATE_IMAGE_BIT_NV`

Is it impossible to mix NV_shading _rate_image with NV_mesh_shader, or was this a typo?

**Comment by jeffbolznv** [comment]
This surely happened because the two extensions were written simultaneously in separate branches. I will fix it.

**Comment by oddhack** [comment]
Should be fixed in the 1.1.89 spec update.
