### ISSUE TITLE
Create SwapChain Exception | Win32

### ISSUE THREAD

**Issue by Karutoh** [KhronosGroup/Vulkan-Docs#825]
`vkGetSwapchainImagesKHR` throws the exception "Division by zero." I'm not sure why, I know it has to do with my code, but I can't pinpoint my error. I already tried LunarXchange's debug layer, but nothing. The `VkSurface` handle is valid.

```cpp
VkSurfaceCapabilitiesKHR cap = {};
vkGetPhysicalDeviceSurfaceCapabilitiesKHR(*inst.Owner(), *win, &cap);

VkExtent2D ext = {};
if (cap.currentExtent.width == 0xFFFFFFFF)
{
	Vec2_i client = win->GetClientSize();

	ext.width = client[0];
	ext.height = client[1];

	if (ext.width < cap.minImageExtent.width)
		ext.width = cap.minImageExtent.width;
	else if (ext.width > cap.maxImageExtent.width)
		ext.width = cap.maxImageExtent.width;

	if (ext.height < cap.minImageExtent.height)
		ext.height = cap.minImageExtent.height;
	else if (ext.height > cap.maxImageExtent.height)
		ext.height = cap.maxImageExtent.height;
}
else
{
	ext = cap.currentExtent;
}

if (frames < cap.minImageCount)
	frames = cap.minImageCount;
else if (frames > cap.maxImageCount)
	frames = cap.maxImageCount;

VkSwapchainCreateInfoKHR info = {};
info.sType = VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR;
info.surface = *win;
info.imageFormat = VK_FORMAT_R8G8B8_UNORM;
info.minImageCount = frames;
info.imageExtent = ext;
info.preTransform = VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR;
info.presentMode = VK_PRESENT_MODE_FIFO_KHR;
info.compositeAlpha = VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR;
info.clipped = true;
info.imageColorSpace = VK_COLORSPACE_SRGB_NONLINEAR_KHR;
info.imageUsage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;
info.imageSharingMode = VK_SHARING_MODE_EXCLUSIVE;
info.queueFamilyIndexCount = 0;
info.pQueueFamilyIndices = nullptr;
info.oldSwapchain = swap;
info.imageArrayLayers = 1;

VkResult r = vkCreateSwapchainKHR(inst.Handle(), &info, nullptr, &swap);
if (r != VK_SUCCESS)
{
	Unitialize();

	Engine::AddLog(U"Failed to create swapchain.", true, true);

	return;
}
```

**Comment by ianelliottus** [comment]
First, I don't see a specification bug here, and so this probably isn't the best forum.

Second, I don't see enough of your code (including the call to vkGetSwapchainImagesKHR) to be able to determine what you might be doing wrong.  I see that some of your code follows what the LunarG cube demo does (which is the official example source for the WSI extensions), but not all of it.  It doesn't show how to use every part of WSI, but it does show the basics, which I think you may be missing.  For example, somebody pointed out to me that you are setting:

```
info.imageFormat = VK_FORMAT_R8G8B8_UNORM;
```

Is that a supported image format for the device you are running your code on?  I don't see a call to vkGetPhysicalDeviceSurfaceFormatsKHR, nor any code that's checking to make sure you're using what the device supports.  There may be other checks that you should be doing and are not.  I suggest that you look at the spec and ensure that anything that can be queried/checked is queried/checked.

Third, are you using the validation layers?  If so, which?  Do they give you any warnings/errors in this area?  You might try running the cube demo on the same system.  If it runs, look at what it's doing (e.g. in the debugger) and compare it to what your code is doing.  I'm sure you'll find the problem.  If you want to report back what you find, please do.

If there's something that is missing in the spec, please create an issue for this repository.  If there's a missing check in the validation layers, please report it to that code's repository.

Then, please close this issue.  Best wishes!

**Comment by krOoze** [comment]
Per https://www.reddit.com/r/vulkan/comments/9nludd/create_swapchain_exception_win32/ you seemed to solve the problem. Apparently violation of Valid Usage?

**Comment by Karutoh** [comment]
> Per https://www.reddit.com/r/vulkan/comments/9nludd/create_swapchain_exception_win32/ you seemed to have solved the problem. Apparently bug in the old SDK layers?

Ah, yes. I wasn't getting a response from the debug layer in the SDK version 1.1.82.1 and I didn't realize that there was another SDK version available. All I needed to do was `vkGetPhysicalDeviceSurfaceFormatsKHR` before `vkCreateSwapchainKHR`.

**Comment by ianelliottus** [comment]
> All I needed to do was call vkGetPhysicalDeviceSurfaceFormatsKHR before vkCreateSwapchainKHR.

Great!

Sounds like we can close this then.
