### ISSUE TITLE
Chapter 27 doesn't specify overflow behaviour of integer fragment shader outputs

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [KhronosGroup/Vulkan-Docs#830]
Unless I've missed something there is no explicit paragraph on what happens if for example the shader outputs an integer (signed or unsigned) outside the range of the associated attachment's unnormalized integer format.

EXT_texture_integer and the core 3.0+ spec (somewhat, inferred through buffer clearing and texture upload format conversions) in OpenGL explicitly specify that wrap-around does not happen and a clamp is performed instead.

**Comment by gnl21** [comment]
This is specified at the end of section 14.3 "Fragment Shader Outputs". The final paragraph there says:
> If the color attachment has an integer format, color values are assumed to be integers and converted to the bit-depth of the target. Any value that cannot be represented in the attachment’s format is undefined.

That is, you can't rely on either wrapping or clamping behaviour. If the shader needs a defined result then it needs to do the conversion itself.

**Comment by devshgraphicsprogramming** [comment]
That's right, I see.

I just thought that "converted to the bit-depth" and "any value that
cannot be represented" are contradictory clauses, as I thought
"conversion to the bit-depth" encompasses some saturation or wraparound.
