### ISSUE TITLE
Relax single subpass render pass compatibility (for pResolveAttachments)

### ISSUE THREAD

**Issue by Kangz** [KhronosGroup/Vulkan-Docs#835]
The render pass subpass compatibility rules imply that the `VkSubpassDescription::pResolveAttachments` must match. It makes sense that this would influence HW tile-cache allocation when resolving in the middle of a render pass, but if resolving at the last subpass of the render pass I don't see why it would change tile-cache allocation.

If my understanding is correct, can text be added to render pass compatibility to allow for the last subpass of the render pass to differ in `pResolveAttachments`. Or if the wording would be too complicated, could the restriction be lifted for single-subpass render passes?

Feel free to CC me internally with @corentinwallez.

Context: I'm asking this because we're looking at how to do multisampling in WebGPU which has "Metal-like" render passes, meaning single-subpass render passes when translated to Vulkan. That pResolveAttachments must match means that when creating graphics pipelines, developers will have to say for each attachment state the format, sample count (that's ok) and whether the attachment will be resolved (that's less ok).

Our other option would be to use `vkCmdResolveImage` but that would be much slower on tilers.

Relevent WebGPU issue is https://github.com/gpuweb/gpuweb/pull/102

**Comment by janharaldfredriksen-arm** [comment]
@Kangz,

Your understanding of the current rules is correct.

We'd need to ask all the implementors whether the proposed relaxation is possible.

But first - could you clarify why you think it's a problem to specify the resolve action as part of the pipeline? E.g. are you saying you want to make the decision on whether to resolve or not dynamically, or is the issue that you want to avoid tying the (shader) compilation step to that decision?

> Our other option would be to use vkCmdResolveImage but that would be much slower on tilers.

Yes, don't do that :)

**Comment by Kangz** [comment]
> But first - could you clarify why you think it's a problem to specify the resolve action as part of the pipeline? E.g. are you saying you want to make the decision on whether to resolve or not dynamically, or is the issue that you want to avoid tying the (shader) compilation step to that decision?

Definitely the latter, we are not interested in deciding dynamically inside the render pass for example.

**Comment by oddhack** [comment]
This should be fixed in the 1.1.97 spec update.

**Comment by Kangz** [comment]
Thanks! I still have writing dEQP tests for this on my TODO list.
