### ISSUE TITLE
Sparse Resource Creation note

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#84]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#sparsememory-resource-creation says:
 
> **Note**
> Specifying VK_BUFFER_CREATE_SPARSE_RESIDENCY_BIT or VK_IMAGE_CREATE_SPARSE_RESIDENCY_BIT implies specifying VK_BUFFER_CREATE_SPARSE_BINDING_BIT or VK_IMAGE_CREATE_SPARSE_BINDING_BIT, respectively, as well. This means that resources created with either (or both) flag(s) can be used with the sparse binding command (vkQueueBindSparse).

Why does it imply that?

As far as I can tell, it's perfectly valid to create a buffer/image with SPARSE_RESIDENCY and not SPARSE_BINDING. Other parts of the document (the vkQueueBindSparse definition and lots of other places) talk about e.g. "VkImage objects created with the VK_IMAGE_CREATE_SPARSE_BINDING_BIT or VK_IMAGE_CREATE_SPARSE_RESIDENCY_BIT flags", which sounds like both are treated equally and explicitly - neither requires or implies the other. So I don't understand what the note is trying to say.

**Comment by oddhack** [comment]
Should have been fixed in the 1.0.10 spec update.
