### ISSUE TITLE
VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT should support VK_PIPELINE_STAGE_TRANSFORM_FEEDBACK_BIT_EXT

### ISSUE THREAD

**Issue by llyzs** [KhronosGroup/Vulkan-Docs#842]
In vkCmdBeginTransformFeedbackEXT, the spec specifies that: 

"VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT specifies read access to a transform feedback counter buffer which is read when vkCmdBeginTransformFeedbackEXT executes."

However in the "Supported access types" table, VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT only supports draw indirect stage. It should also support transform feedback stage for above reason. The NVidia beta driver actually requires it to work properly.

My test scenario for the counter buffer barrier is as following:
1. update counter to 0, barrier: VK_ACCESS_TRANSFER_WRITE_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT
2. begin transform feedback, barrier: VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT, VK_PIPELINE_STAGE_TRANSFORM_FEEDBACK_BIT_EXT
3. end transform feedback, barrier: VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_PIPELINE_STAGE_TRANSFORM_FEEDBACK_BIT_EXT

**Comment by pdaniell-nv** [comment]
The VK_PIPELINE_STAGE_TRANSFORM_FEEDBACK_BIT_EXT stage in the graphics pipeline is where the GPU captures the vertex data emitted by the last vertex processing stage into the XFB buffers. Think of it between the geometry shader and early fragment tests. When the counter buffer is read by vkCmdBeginTransformFeedbackEXT, that's way before this point in the pipeline. The best fit is VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT, which is at the point in the pipeline where commands can get read state data from buffers right at the start of the graphics pipeline before vertex data is transferred.

**Comment by llyzs** [comment]
Thanks for the clarification. Closing this.
