### ISSUE TITLE
Usage of vkCmdWaitEvents inside render pass scope

### ISSUE THREAD

**Issue by yNeo** [KhronosGroup/Vulkan-Docs#847]
I was wondering what is the proper usage of ```vkCmdWaitEvents``` inside a render pass scope. I came across this example from Khronos - https://www.khronos.org/assets/uploads/developers/library/2016-vulkan-devday-uk/7-Keeping-your-GPU-fed.pdf, which states that you can declare an external subpass dependency and then wait for external events in that subpass.

My current understanding is that external subpass dependencies act as an explicit pipeline barrier between previous commands and the destination subpass, not as a declaration for future barriers or event waits.

I have looked through the events chapter and the render passes chapter and found no information about the correct usage of ```vkCmdWaitEvents``` inside a render pass scope. The spec does say that it can be used inside a render pass scope but doesn't specify exactly how that works.

**Comment by Tobski** [comment]
Hey, yea it looks like this is really rather underspecified. I'll take a look at it and see what needs fixing here.

**Comment by Tobski** [comment]
Ok, so after a brief discussion in the WG, we came to the conclusion that whilst a number of us remembered having this kind of discussion about needing external dependencies, it never actually ended up in the spec. I wrote that slide before doing the massive overhaul of the sync chapter, and I guess I never revisited it 🤷‍♂️ 

So in other words, my presentation was wrong (sorry!) and the spec is right - you can just plop any old vkWaitEvents call into a subpass and it should just work.

**Comment by Tobski** [comment]
(I'll make sure to update that presentation should I ever give it again 😅)
