### ISSUE TITLE
vkGetImageSparseMemoryRequirements non-SPARSE_RESIDENCY behaviour

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#85]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#sparsememory-memory-requirements says:

>     vkGetImageSparseMemoryRequirements
>
> [...]
>
> * image must have been created with the VK_IMAGE_CREATE_SPARSE_RESIDENCY_BIT flag 
>
> [...]
>
> If the image was not created with VK_IMAGE_CREATE_SPARSE_RESIDENCY_BIT then pSparseMemoryRequirementCount will be set to zero and pSparseMemoryRequirements will not be written to.

This is about the only place in the spec that says both "applications must do X" and "if the application does not-X then implementations must/will do Y". Normally applications violating a requirement get undefined behaviour, so it's meaningless to describe specific implementation behaviour in that case.

Is that intentional here?

If applications can omit VK_IMAGE_CREATE_SPARSE_RESIDENCY_BIT without suffering undefined behaviour, I think either the "image must ..." should be removed or it should be clarified like "image must have been ... (but the behaviour is well-defined if it wasn't, as described below)". Or if it *is* undefined behaviour, don't subsequently try to define the behaviour.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.7 spec update.
