### ISSUE TITLE
Task list for VK_KHR_swapchain_mutable_format release

### ISSUE THREAD

**Issue by drakos-amd** [KhronosGroup/Vulkan-Docs#853]
The Khronos board of promoters have recently ratified a new Vulkan extension called `VK_KHR_swapchain_mutable_format`. This extension enables processing of swapchain images as different formats to that used by the window system, which is particularly useful for switching between sRGB and linear RGB formats.

The task list for the `VK_KHR_swapchain_mutable_format` extension release is:
- [x] Headers, specs, etc. in https://github.com/KhronosGroup/Vulkan-Docs
- [x] Vulkan specification in the [Vulkan Registry](https://www.khronos.org/registry/vulkan/)
- [x] Vulkan Conformance Test Suite in https://github.com/KhronosGroup/VK-GL-CTS
- [x] Validation in https://github.com/KhronosGroup/Vulkan-ValidationLayers
- [x] Vulkan SDK at https://vulkan.lunarg.com/

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

If you have any questions or feedback, please leave comments below.

**Comment by alegal-arm** [comment]
CTS: https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.1.2.2

**Comment by mikes-lunarg** [comment]
Validation: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/514

**Comment by TomOlson** [comment]
In full release, so closing this tracker
