### ISSUE TITLE
Sparsely-resident compressed image sizes

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#86]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#sparsememory-standard-sizes says:

> For compressed pixel formats (e.g. VK_FORMAT_BC5_UNORM_BLOCK), the pixel size is the size of the compression block (128-bit for BC5).

for defining the standard image block sizes.

https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#sparsememory-format-props says:

> imageGranularity is the width, height, and depth of the block in pixels / compressed blocks.

These seem to be the only places that compression is mentioned in the Sparse Resources section. Everything else only talks about pixels, e.g.:

> formatProperties.imageGranularity describes the size of a single bindable block in pixel units.

Also there is e.g.:

> extent.width must either be a multiple of the block width of the image, or else extent.width + offset.x must equal the width of the image subresource

For a 1024x1024-pixel BC5 image, the standard sparse image block shape is 64x64x1 (in 128-bit compression units), so "the block width of the image" is probably 64 (I think?) (which corresponds to 256 pixels since each compression unit is 4x4 pixels) but then "the width of the image subresource" is always counted as 1024 pixels (I think), so it's mixing different units together here.

The specification of sparse compressed images seems incomplete and/or pretty confusing to me.

**Comment by drakos-amd** [comment]
As you said, the compression unit (block) is 4x4 texels in BC5, thus the compression block width is 4, and the block height is 4 for BC5 images (block depth is 1 as it's a 2D compression scheme).
This means if you have a sparse image block shape of 64x64x1 then the corresponding image block shape in terms of compression blocks is 64x64x1 / 4x4x1 = 16x16x1.

Indeed the term "block" is a bit overloaded across the spec, as it can refer to a sparse image block, or a compression block. We'll look into it.

**Comment by philiptaylor** [comment]
> This means if you have a sparse image block shape of 64x64x1 then the corresponding image block shape in terms of compression blocks is 64x64x1 / 4x4x1 = 16x16x1.

Hmm, are you sure? The spec says:

> All currently defined standard block shapes are 64 KB in size.

and I calculate:

* 16x16x1 * 128 bits = 4 KB
* 64x64x1 * 128 bits = 64 KB

where each BC5 compression block is 128 bits, so I think the standard sparse image block shape has to contain 64x64x1 compression blocks, which is 256x256x1 pixels, to make up the right size in bytes.

Also, dividing 64x64x1 by the compression block size would get tricky when you're using ASTC_5x5, so I don't think it makes sense to do that.

(Then, since the sparse binding is meant to happen at 64KB granularity, it'd only make sense for the VkSparseImageMemoryBind offset/extent to be multiples of 256x256 pixels, not multiples of 64x64.)

**Comment by drakos-amd** [comment]
Sorry, I described it backwards.

So 64x64x1 is the block shape for 128-bit pixel size, which for compressed formats is a single compression block.

Thus for a 64x64x1 block shape for 128-bit compression blocks of size 4x4x1 means 256x256x1 block shape in terms of texels.

**Comment by oddhack** [comment]
This should be done in the 1.0.65 spec update.
