### ISSUE TITLE
pNext version of debug should cover vkCreateDebug* too?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#861]
Spec says for the `debug_report` and `debug_utils`:

> This callback is only valid for the duration of the `vkCreateInstance` and the `vkDestroyInstance` call.

It think it should be allowed to be valid for `vkCreateDebugUtilsMessengerEXT` and `vkCreateDebugReportCallbackEXT` in order for those two to be validatable when no preexisting callback exist.

**Comment by mikes-lunarg** [comment]
After some discussion, we decided not to allow more special cases for temporary debug callbacks.  The proposed change would add complexity to implementations of the debug extensions without adding any new debug capabilities.
