### ISSUE TITLE
Please clarify how extensions added to the core vulkan API interact with extension dependencies

### ISSUE THREAD

**Issue by haasn** [KhronosGroup/Vulkan-Docs#865]
In section 33.3 of the vulkan 1.1 spec, you state:

> Some extensions are dependent on other extensions to function. To enable extensions with dependencies, such required extensions must also be enabled through the same API mechanisms when creating an instance with vkCreateInstance or a device with vkCreateDevice. Each extension which has such dependencies documents them in the appendix summarizing that extension.

Now, some device-level extensions have dependencies on instance-level extensions such as `VK_KHR_get_physical_device_properties2`, for example `VK_KHR_push_descriptor`. However, in vulkan 1.1, the functionality of `VK_KHR_get_physical_device_properties2` has been promoted to the vulkan core API. The way this is worded, specifically the “must be enabled through the same API mechanisms”, seems to imply that I still need to specify `VK_KHR_get_physical_device_properties2` when creating the `VkInstance`!

Now this conclusion seems obviously wrong, so maybe this section needs to be clarified to either make it clear that implicitly enabled extensions in future versions of the vulkan core satisfy extension-level dependencies, or the extensions themselves need to be reworded to make it clear that the dependency is only valid for vulkan 1.0?

**Comment by oddhack** [comment]
This should be addressed in the 1.2.166 spec update (together with some prior changes that also addressed this area).
