### ISSUE TITLE
Allow relaxing VkImageCopy.bufferOffset alignment requirement?

### ISSUE THREAD

**Issue by haasn** [KhronosGroup/Vulkan-Docs#869]
In `VkImageCopy`, it's required that `bufferOffset` be a multiple of 4. I was wondering whether it could make sense to somehow relax this to only requiring a multiple of some new field `minBufferCopyOffsetAlignment` (which, for backwards compatibility, is guaranteed to be a divisor of 4).

Empirically, it seems that at least some hardware/drivers (e.g. AMD) do not have any such internal "multiple of 4" requirement - and if this is indeed the case it seems rather silly to force users to work around this restriction (e.g. by using a slow indirection via intermediate `VkBuffer`) even in cases where this performance loss would otherwise be completely avoidable. Such drivers could expose `minBufferCopyOffsetAlignment = 0x1`, and code that's aware of this field would be able to skip the indirection whenever the buffer offset is already aligned to this value. Existing applications that assume the alignment requirement is always equal to 4 would continue to work as if nothing had changed.

That said, I'm not 100% sure if the premise is true. It might be the case that the "multiple of 4" requirement still matters for some internal fallback paths. I haven't exhaustively tested all scenarios, nor fully read the code.

**Comment by krOoze** [comment]
dup of #574?

**Comment by haasn** [comment]
I think so.
