### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by JamesChenChina** [KhronosGroup/Vulkan-Docs#874]
Quick question
Does NVIDIA Tesla GPU suport vulkan?
Many thanks

**Comment by pdaniell-nv** [comment]
Which model number in particular are you asking about?

**Comment by pdaniell-nv** [comment]
@JamesChenChina question for you in the previous comment.

**Comment by JamesChenChina** [comment]
@pdaniell-nv NVIDIA Tesla K10   and Tesla V100.  Thanks

**Comment by pdaniell-nv** [comment]
Yes, Vulkan should work on both of those products. If it doesn't work, let me know what driver version you tried.

**Comment by JamesChenChina** [comment]
@pdaniell-nv Thank you!

My OS: ubuntu 16.04

nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 415.18.04    Driver Version: 415.18.04    CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K10.G2.8GB    Off  | 00000000:84:00.0 Off |                  N/A |
| N/A   41C    P0    42W / 117W |      0MiB /  3527MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K10.G2.8GB    Off  | 00000000:85:00.0 Off |                  N/A |
| N/A   38C    P0    37W / 117W |      0MiB /  3527MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+


vulkaninfo
ERROR: ld.so: object 'libachk.so' from /etc/ld.so.preload cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
===========
VULKAN INFO
===========

Vulkan Instance Version: 1.1.73

ERROR: [Loader Message] Code 0 : libGLX_nvidia.so.0: cannot open shared object file: No such file or directory
Cannot create Vulkan instance.
/build/vulkan-CbT3KM/vulkan-1.1.73+dfsg/demos/vulkaninfo.c:812: failed with VK_ERROR_INCOMPATIBLE_DRIVER

I also tried 396.54 and 396.54.09. And I got same error.

**Comment by pdaniell-nv** [comment]
Since this is NVIDIA specific support, would you mind moving this conversation to https://devtalk.nvidia.com/default/board/63/gpu-unix-graphics/. The next thing we would ask you to try is to run nvidia-bug-report.sh and attached your output there. Thank you.

**Comment by JamesChenChina** [comment]
@pdaniell-nv  Please review https://devtalk.nvidia.com/default/topic/1045406/linux/vulkaninfo-doesn-t-work-on-ubuntu16-04-with-nvidia-396-54-09-driver-gpu-tesla-k10-/
I have attached log.
Thanks a lot!

**Comment by JamesChenChina** [comment]
@pdaniell-nv As far as I know, Tesla doesn't have video output. So I have another question, What's your opinion to use WINE+DXVK(A Vulkan-based translation layer for Direct3D 10/11 which allows running 3D applications on Linux using Wine) to play windows games like GTA-V  on Linux(Ubuntu)? Is it possible to compute/render in Tesla and make video output in another graphic video card?
I have tried NVIDIA Quadro. It's no problem to play GTA-V on ubuntu with one Quadro Card.
So I want to know the probability to do the same thing with Tesla card.
Thank you so much

**Comment by pdaniell-nv** [comment]
I think it's technically possible to do that, but I assume there would need to be some code added to WINE+DXVK to make that work. I doubt it would work automatically. It's sounds like a fairly niche requirement to play games on a Tesla. You might be the only person who wants to do that. ;-)

**Comment by oddhack** [comment]
I thought Elon had just shipped an update to support old Atari games. But pretty sure Tesla cars don't have an onboard Tesla GPU, do they? :-)

**Comment by oddhack** [comment]
@JamesChenChina could this be closed? It sounds like you would need to work through NVIDIA's devrel website to convince them to support this use case.

**Comment by krOoze** [comment]
@pdaniell-nv @oddhack This still seems abandoned and closeable.
