### ISSUE TITLE
Diagrams for texture coordinates are flipped vertically

### ISSUE THREAD

**Issue by francoisbertelatschrodinger** [KhronosGroup/Vulkan-Docs#876]
According to "15.1.1. Texel Coordinate Systems" (spec 1.1.95),
* Normalized texel coordinates:
The t coordinate goes from 0.0 to 1.0, top to bottom.
* Unnormalized texel coordinates:
The v coordinate goes from -1.0 to 5.0, top to bottom. 
* Integer texel coordinates:
The j coordinate goes from -1 to 5, top to bottom.

However figure 3 "Texel Coordinate Systems" ( images/vulkantexture0.svg ), figure 4 "Texel Coordinate Systems" ( images/vulkantexture1.svg) and figure 11 "Implicit Derivatives" (in 15.5 Derivatives Operations, images/vulkantexture2.svg) show a vertical axis going from bottom to top.

**Comment by oddhack** [comment]
Appears to be related to #898?

**Comment by francoisbertelatschrodinger** [comment]
It is! However the commit 31b0c98a504eb3f9dc5a6f7bcf9a130fb09cb376 in #898 is only touching images/vulkantexture0.svg and images/vulkantexture1.svg.
It is missing images/vulkantexture2.svg for figure 11 "Implicit Derivatives".

**Comment by oddhack** [comment]
We just pushed an update that included a bunch of changes to diagrams in this chapter. @francoisbertelatschrodinger could you take a look and see if this issue has been addressed now?

**Comment by francoisbertelatschrodinger** [comment]
Should I look at a specific branch? In the master branch  images/vulkantexture0.svg, images/vulkantexture1.svg and images/vulkantexture2.svg are still from "10 month ago" when browsing through github. And the current pdf (Version 1.1.99, 2019-02-04 09:27:01Z) at https://www.khronos.org/registry/vulkan/specs/1.1-extensions/pdf/vkspec.pdf still have the vertical axes going from bottom to top instead of top to bottom.

**Comment by oddhack** [comment]
I misspoke about the nature of the changes. It's the body text that should be different now, for example it describes "The t coordinate goes from 0.0 to 1.0" without talking about top/bottom. Hopefully that's improved consistency between text and diagrams to the point the arrows are not a problem?

**Comment by francoisbertelatschrodinger** [comment]
I see. Yes it looks consistent now. The spec is orientation agnostic then, right?

**Comment by oddhack** [comment]
We are headed that way, but I think not all the way there yet. The WG member who did the changes we're talking about here has commented on a number of other uses of terms like "top left" and "bottom right" in other parts of the spec, that they also hope to make improvements with.

P.S. Bill, you are more than welcome to take over this discussion, but I know you're not very active on Github :-)

**Comment by francoisbertelatschrodinger** [comment]
As the Vulkan tutorial has the following sentence in the "Loading Models" chapter:
"The problem is that the origin of texture coordinates in Vulkan is the top-left corner, whereas the OBJ format assumes the bottom-left corner.",  I asked the authors of the tutorial if they could step in ( https://github.com/Overv/VulkanTutorial/issues/127 )

**Comment by oddhack** [comment]
@francoisbertelatschrodinger it looks like the tutorial issue has been closed - is there more to do here, or could we close this as well? As noted previously, Bill does have some additional cleanup planned in other parts of the spec, but in terms of the specific diagrams this issue mentions, there may be nothing more to do.

**Comment by francoisbertelatschrodinger** [comment]
Yes, this is issue can be closed. Thank you.
