### ISSUE TITLE
Links in PDF specs not working

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Docs#877]
In https://github.com/KhronosGroup/Vulkan-Web-Registry/commit/ddf69d4a2215e16be78c9bf7ac4bd10bf58eadcd#commitcomment-31641862, @michaelforney noticed that links from the PDF documents weren't resolving, which I've verified.

I updated to Ruby 2.5.3 and slightly newer versions of some of the Ruby packages out of necessity due to a deep DSO versioning conflict after updating my Debian system (one that actually made it impossible to even do a 'gem update' because it was unhappy about the installed version of the ssl/crypto libraries), and can't easily back off to the older Ruby version / components I was using. That  will make diagnosing this difficult, but I'll try to figure it out - assistance welcome. The asciidoctor-pdf toolchain is a giant black box from my POV so there's a limited amount of diagnosis available.

**Comment by krOoze** [comment]
Seems to work for me if I remove the `ghostscript` optimization step.

Also had problem with SSL at update at some point, and installing `libssl-dev` package fixed it.
