### ISSUE TITLE
multiDrawIndirect drawCount values

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#88]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#features-features says:

> multiDrawIndirect indicates whether multi-draw indirect is supported. If this feature is not enabled, the drawCount parameter to the vkCmdDrawIndirect and vkCmdDrawIndexedIndirect commands must be 1.

https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#_programmable_primitive_shading says:
 
> If the multi-draw indirect feature is not enabled, the value of drawCount must be 0 or 1

These are inconsistent about whether 0 is permitted.

**Comment by oddhack** [comment]
Agreed. Pursuing a clarification inside Khronos

**Comment by oddhack** [comment]
Should be fixed in the 1.0.6 spec update.
