### ISSUE TITLE
vkCmdDispatchIndirect function size requirement

### ISSUE THREAD

**Issue by Nielsbishere** [KhronosGroup/Vulkan-Docs#880]
The Vulkan spec states that vkCmdDispatchIndirect takes a command buffer, buffer resource and offset into the resource; however, it doesn't state the number of dispatches (unlike vkCmdDrawIndirect and vkCmdDrawIndexedIndirect). This is an issue, since this requires the dispatch buffer to be the exact size of the dispatched arguments. Meaning that unlike MDI, you can't specify a region it takes the dispatch commands from. 
Is there a way to get around this? Or should the spec be updated to allow this?

**Comment by polarina** [comment]
The number of dispatches done by `vkCmdDispatchIndirect` is always one.

**Comment by krOoze** [comment]
I am not sure what you mean. What's a "function size"?
It is identical to `vkCmdDispatch`, except the `x`, `y`, and `z` are read from the buffer instead.

**Comment by Nielsbishere** [comment]
That makes more sense, I thought it was similar to vkCmdDraw(Indexed)Indirect, where you can dispatch multiple dispatches with one command. I guess I could make this myself by just calling vkCmdDispatchIndirect foreach dispatch and increasing the offset; or is there some sort of multi dispatch indirect?

**Comment by polarina** [comment]
> [...]; or is there some sort of multi dispatch indirect?

There is no multi-dispatch functionality present in Vulkan.

**Comment by Nielsbishere** [comment]
Unfortunate, I guess multiple dispatches will do. Thanks!
