### ISSUE TITLE
Cmdbuffer state diagram shows path from Initial to Invalid

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#881]
The command buffer state diagram shows a path from Initial to Invalid state. I can't find a mechanism in the spec by which this could be possible.

BTW I am also unclear what the two styles of arrows signify. What is the difference between dashed and solid arrows in the diagram?

BTW 2, it is a null-op, but technically it seems valid to reset in Initial state, which is missing in the diagram.

**Comment by polarina** [comment]
The spec has the following to say, implying that command buffers **cannot** transition directly to the invalid state from the initial:
> Command buffers in the initial state **can** only be moved to the recording state, or freed.

**Comment by Tobski** [comment]
> The command buffer state diagram shows a path from Initial to Invalid state. I can't find a mechanism in the spec by which this could be possible.

Yes, this is incorrect - I'll fix it.

> BTW I am also unclear what the two styles of arrows signify. What is the difference between dashed and solid arrows in the diagram?

It's kind of meant to be "solid lines == this is an actual command" vs. "dashed lines == thing that happens as a side effect of other commands". It's not clear, but felt somewhat overboard to create a key for it.

> BTW 2, it is a null-op, but technically it seems valid to reset in Initial state, which is missing in the diagram.

True, but I'm not sure that it would be helpful to anyone to diagram that...

**Comment by oddhack** [comment]
This should be fixed in the 1.1.104 spec update.
