### ISSUE TITLE
about flags is reserved for future use.

### ISSUE THREAD

**Issue by gchihiha** [KhronosGroup/Vulkan-Docs#884]
in vkspec.html,Some flags like this:
flags is reserved for future use.
Where is this reflected in vk.xml?

**Comment by oddhack** [comment]
It is not explicitly tagged. If a Vk*FlagBits type has no bits defined for it, either in the enum group definition or via extends= enum tags in extension blocks, then the corresponding Vk*Flags type must be zero. Look at the logic near the beginning of createValidationLineForParameter in xml/validitygenerator.py starting around line 516.

**Comment by gchihiha** [comment]
thx~
