### ISSUE TITLE
asciidoctor: invalid option: --failure-level

### ISSUE THREAD

**Issue by gchihiha** [KhronosGroup/Vulkan-Docs#885]
> gc@DESKTOP-A03N851:/mnt/d/project/Vulkan-Docs$ make
> fatal: your current branch 'master' does not have any commits yet
> asciidoctor: invalid option: --failure-level
> Usage: asciidoctor [OPTION]... FILE...
> Translate the AsciiDoc source FILE or FILE(s) into the backend output format (e.g., HTML 5, DocBook 4.5, etc.)
> By default, the output is written to a file with the basename of the source file and the appropriate extension.
> Example: asciidoctor -b html5 source.asciidoc
> 
>     -b, --backend BACKEND            set output format backend: [html5, xhtml5, docbook5, docbook45, manpage] (default: html5)
>                                      additional backends are supported via extensions (e.g., pdf, latex)
>     -d, --doctype DOCTYPE            document type to use when converting document: [article, book, manpage, inline] (default: article)
>     -o, --out-file FILE              output file (default: based on path of input file); use - to output to STDOUT
>         --safe                       set safe mode level to safe (default: unsafe)
>                                      enables include macros, but restricts access to ancestor paths of source file
>                                      provided for compatibility with the asciidoc command
>     -S, --safe-mode SAFE_MODE        set safe mode level explicitly: [safe, unsafe, server, secure] (default: unsafe)
>                                      disables potentially dangerous macros in source files, such as include::[]
>     -s, --no-header-footer           suppress output of header and footer (default: false)
>     -n, --section-numbers            auto-number section titles in the HTML backend; disabled by default
>     -e, --eruby ERUBY                specify eRuby implementation to use when rendering custom ERB templates: [erb, erubis] (default: erb)
>     -C, --compact                    compact the output by removing blank lines. (No longer in use)
>     -a, --attribute key[=value]      a document attribute to set in the form of key, key! or key=value pair
>                                      unless @ is appended to the value, this attributes takes precedence over attributes
>                                      defined in the source document
>     -T, --template-dir DIR           a directory containing custom converter templates that override the built-in converter (requires tilt gem)
>                                      may be specified multiple times
>     -E, --template-engine NAME       template engine to use for the custom converter templates (loads gem on demand)
>     -B, --base-dir DIR               base directory containing the document and resources (default: directory of source file)
>     -D, --destination-dir DIR        destination output directory (default: directory of source file)
>     -I, --load-path DIRECTORY        add a directory to the $LOAD_PATH
>                                      may be specified more than once
>     -r, --require LIBRARY            require the specified library before executing the processor (using require)
>                                      may be specified more than once
>     -q, --quiet                      suppress warnings (default: false)
>         --trace                      include backtrace information on errors (default: false)
>     -v, --verbose                    enable verbose mode (default: false)
>     -t, --timings                    enable timings mode (default: false)
>     -h, --help                       show this message
>     -V, --version                    display the version and runtime environment (or -v if no other flags or arguments)
> Makefile:212: recipe for target '/mnt/d/project/Vulkan-Docs/out/html/vkspec.html' failed
> make: *** [/mnt/d/project/Vulkan-Docs/out/html/vkspec.html] Error 1
> gc@DESKTOP-A03N851:/mnt/d/project/Vulkan-Docs$ asciidoctor --version
> Asciidoctor 1.5.5 [http://asciidoctor.org]
> Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
> gc@DESKTOP-A03N851:/mnt/d/project/Vulkan-Docs$ uname -a
> Linux DESKTOP-A03N851 4.4.0-17134-Microsoft #471-Microsoft Fri Dec 07 20:04:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
> gc@DESKTOP-A03N851:/mnt/d/project/Vulkan-Docs$ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 18.04.1 LTS
> Release:        18.04
> Codename:       bionic

i can't make 
help~~~~

**Comment by karl-lunarg** [comment]
You need asciidoctor version 1.5.8, as explained in the BUILD.adoc file in this repo.

You are using 1.5.5 which does not have the `--failure-level` option.

**Comment by gchihiha** [comment]
ha 
thx a lot!
