### ISSUE TITLE
How to disable the generation of pdf ???

### ISSUE THREAD

**Issue by gchihiha** [KhronosGroup/Vulkan-Docs#887]
How to disable the generation of pdf

I'm going crazy
Make this project, the PDF generation process will always have problems, can you give me an option to turn it off?
please...

**Comment by oddhack** [comment]
Apparently you figured it out? Anyway, 'make html' generates just the HTML spec target, or './makeAllExts html' to build the spec with all extensions included.

**Comment by gchihiha** [comment]
Because of this, I closed it later.
