### ISSUE TITLE
Request for `VK_IMAGE_LAYOUT_SHADER_READ_WRITE_OPTIMAL`

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-Docs#888]
Currently, compute writes to images require them to be in `VK_IMAGE_LAYOUT_GENERAL`. In helper routines in many applications and libraries, where the access mask is computed from the layout without taking context into account, this imposes an inefficiency.

Taken out of context, a transition out of GENERAL would require `VK_ACCESS_MEMORY_WRITE_BIT` on src and into GENERAL would require `VK_ACCESS_MEMORY_READ_BIT | VK_ACCESS_MEMORY_WRITE_BIT` on dst.

However, if a new image layout is added, namely `VK_IMAGE_LAYOUT_SHADER_READ_WRITE_OPTIMAL` (or perhaps `VK_IMAGE_LAYOUT_SHADER_WRITE_OPTIMAL`), these access masks can be optimized to use `VK_ACCESS_SHADER_READ_BIT` and `VK_ACCESS_SHADER_WRITE_BIT`.

---

The context of this request is ANGLE, where a frame's structure is not apriori known, and the layout transitions are handled by tracking the old layout automatically, with the callers simply requesting a new layout.

The issue can be mitigated by not only tracking the old layout, but also the necessary access mask, but that's almost entirely unnecessary (as the layout gives away the access mask in almost all cases).  Compute writes to images is the only (common) case where the layout doesn't imply tight access masks, hence the request.

**Comment by Tobski** [comment]
Hi @ShabbyX, thanks for the suggestion! From the description, it seems like you're using the image layout as a sort of proxy for the access masks, which is not what the layout enums are designed for at all - the property of *nearly* matching the access masks for your use case is really just a happy coincidence. In general, the Vulkan API is designed to expose the hardware, and as best we can tell there is no hardware that would benefit from such a layout state, this is just a request for a software convenience?

However, the layout/access/stage combination is understandably complex (more than it needs to be IMO...), so using a single enum to drive everything is definitely a sensible goal. In fact many developers I've talked to have adopted their own mappings to handle this, combining the set of things they *actually* use into a single list of enums that make sense for their domain.

I would suggest that doing similar would probably be the best approach here - if it's helpful, I've created an example that covers most of the possible space, which might be useful to look at: https://github.com/Tobski/simple_vulkan_synchronization/blob/master/thsvs_simpler_vulkan_synchronization.h. In your case though, it might just make sense to make your own enum list that mirrors the VkLayout enum and just adds the extra one you need?

**Comment by ShabbyX** [comment]
Hi @Tobski, that's an interesting approach, I'd think about it.

In the meantime, I always thought layouts are really there for validation and debugging. I don't know all hardware, but know GCN pretty in depth, and I think access/stage is enough to implement any needed barrier. For which driver (and how) does SHADER_READ_ONLY_OPTIMAL actually make a difference for example compared to GENERAL, as long as the necessary barriers have the right access masks?

**Comment by ShabbyX** [comment]
Actually never mind, I can think of a use for the layout!

**Comment by Tobski** [comment]
Ahh I was just about to reply as well, but looks like you figured it out. GCN basically uses it (in combination with other sync/image information) for various compression routines for images; you can dive into our public driver source if you're interested!
Vulkan's synchronization model is awkward as all heck, and there's not a 1:1 mapping between layouts and access masks (there's many more than just this) and AMD's driver (and others) use the full combination of access/stage/layout to figure out what to actually do. The practical set of combinations is several orders of magnitude less than what the API exposes unfortunately.

**Comment by ShabbyX** [comment]
That's interesting about compression, I presume you are talking about CMASK and HTILE?

What I had thought of was choosing the caching strategy based on layout (for example SHADER_READ_ONLY would mean L1 is used, while GENERAL would bypass L1).

And yes, the Vulkan model is pretty extensive, but at least it's better than the other way around, right? ;) I just hope that the complexity would eventually be worth it (with hardware ending up more complex), otherwise it would be over engineered for nothing...
