### ISSUE TITLE
Broken links in the VK_EXT_buffer_device_address html page

### ISSUE THREAD

**Issue by vilya** [KhronosGroup/Vulkan-Docs#893]
The links to GLSL_EXT_buffer_reference and SPV_EXT_physical_storage_buffer on this page https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/chap41.html#VK_EXT_buffer_device_address are broken.

**Comment by oddhack** [comment]
Thanks. We don't always release all the parts of an extension at once, so there's a tracker (#890) which will get filled in as the other components come out. That should happen fairly soon and at that point the links will be valid. In that light I suggest closing this.

**Comment by vilya** [comment]
Thanks for the info, I'm looking forward to reading the other parts. I'll close this and keep an eye on #890 instead.
