### ISSUE TITLE
bufferImageGranularity clarity

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#90]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#features-limits says:

> bufferImageGranularity is the granularity, in bytes, at which buffer or linear image resources, and optimal image resources can be bound to adjacent memory for simultaneous usage. See Buffer-Image Granularity for more details.

https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#resources-bufferimagegranularity says:

> There is an implementation-dependent limit, bufferImageGranularity, which specifies a page-like granularity at which buffer, linear image and optimal image resources must be placed in adjacent memory locations for simultaneous usage. Two resources which do not satisfy this granularity requirement are said to alias.

and:

> Given resourceA at the lower memory offset and resourceB at the higher memory offset, where one of the resources is a buffer and the other is an image, [...]

https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#resources-memory-aliasing says:

> Applications can alias memory, but use of multiple aliases is subject to several constraints. [...]

The descriptions seem quite confusing to me. I guess the intention is:

* If a linear image and a buffer are bound to the same VkDeviceMemory, and they overlap based on the bufferImageGranularity calculation, then they are aliased, which is okay if (and only if) you use appropriate memory dependencies.
* If an optimal image and a buffer are bound to the same VkDeviceMemory, ... (same as above).
* If a linear image and an optimal image are bound to the same VkDeviceMemory, then we don't care about bufferImageGranularity at all (though the normal aliasing applies if they have a bytewise overlap).
* If two buffers are bound to the same VkDeviceMemory, then we don't care about bufferImageGranularity at all (though the normal aliasing applies etc).

The phrases "buffer or linear image resources, and optimal image resources" and "buffer, linear image and optimal image resources" don't make the combinations clear. I think it'd be better to say e.g.:

"bufferImageGranularity is the granularity, in bytes, at which a buffer resource and an image resource (either linear or optimal) can be bound to adjacent memory for simultaneous usage."

and

"bufferImageGranularity, which specifies a page-like granularity at which a buffer resource and an image resource (either linear or optimal) must be placed in adjacent memory locations for simultaneous usage."

to make it clear that it's about one buffer vs one image.

And the thing about "at which ... resources must be placed in adjacent memory locations for simultaneous usage" sounds like it's forbidding simultaneous usage when they're aliased, whereas the aliasing section indicates it's permitted (though it'll need the right memory dependencies).

And https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#resources-bufferimagegranularity should probably say that it only applies to resources from the same VkDeviceMemory.

**Comment by jeffbolznv** [comment]
I think @drakos-amd has a change in progress that clarifies things a bit. But the two sets that need to avoid overlap according to the granularity are {buffers and linear images} vs {optimal}

**Comment by oddhack** [comment]
Should be fixed in the 1.0.7 spec update (I'm not sure if it's entirely fixed - if not, please reopen with a comment narrowing to the remaining issues).
