### ISSUE TITLE
Chunked version does not include copyright+license text.

### ISSUE THREAD

**Issue by ratchetfreak** [KhronosGroup/Vulkan-Docs#903]
The first text of the chunked version starts immediately from the "1. Introduction" header and skips the copyright and license intro you can find in the single html file version before that header.

There is no way that I can find to show that copyright+license information in the chunked version.

**Comment by krOoze** [comment]
http://vulkan.hys.cz/orig/chunked/index.html starts at the Copyright. It is not accessible through the TOC though. And the registry links point at `chap1.html` instead of the `index.html`...

**Comment by oddhack** [comment]
I updated the index to link to the index.html / copyright page. I'm unsure if it's possible to alter the TOC generation to include material before the first chapter, so hopefully this will suffice to close this issue. @ratchetfreak please close if this change is OK for you.

**Comment by ratchetfreak** [comment]
It's enough for me, but I'm not sure it's enough for other parties, (the reason I brought it to your attention).

Another option is to add a link in the header/footer to index.html
