### ISSUE TITLE
What's the deal with vkEnumerateInstanceVersion

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#904]
Rant from #674:

1) `vkEnumerateInstanceVersion` returns only one code: `VK_SUCCESS`. That's weird; why? Is it planned to be extended with something here in 1.2? Should I now be checking its return value, or treat it like a `void` returning command?

2) Why does it not allow coexistence of `1.N` and potential `2.0`. It can only return one Vulkan version. Should it be restricted to only return a `1.N` value, and later a vkEnumerateInstanceVersion2 will be added for `2.N` versions etc? Or how will that work?

**Comment by ianelliottus** [comment]
> vkEnumerateInstanceVersion returns only one code: VK_SUCCESS. That's weird; why?

In case we add a possible error in the future.  Right now (Vulkan 1.1), it's very simple (at least in the Android loader): always return 1.1 and VK_SUCCESS.


> Is it planned to be extended with something here in 1.2?

No plans, but you never know:-).


> Should I now be checking its return value, or treat it like a void returning command?

You should be checking its return value.


> Why does it not allow coexistence of 1.N and potential 2.0.

Vulkan 2.0 may or may not be backward compatible.  Who knows when it will be defined, or what it will look like.

I'm closing this, since I answered the questions (as best as we can at this point).  Reopen if my answers weren't clear.

**Comment by critsec** [comment]
> If I was being strict, what should I do if I code today and I am a 1.0 app and vkEnumerateInstanceVersion returns a 2.X value somewhere in this future? Terminate or continue (if continue, which N in 1.N version does the driver support)?

This is one of the reasons it might not make sense to use vkEnumerateInstanceVersion in a hypothetical Vulkan 2.0. Some apps would want it to return the 1.X version supported, and other apps would want it to return the 2.X version supported, assuming both can be supported by the same implementation.

So I would say that if it returns 2.X, anything written today doesn't know whether there's anything further it can safely do, so bailing out would be appropriate.

**Comment by krOoze** [comment]
> So I would say that if it returns 2.X, anything written today doesn't know whether there's anything further it can safely do, so bailing out would be appropriate.

Ok, that makes sense, though I would like to be able to run a retro app from good ol' 2019 without it just terminating because of this.

From that perspective it only ever makes sense for the command to return `1.N` version.
Should spec guarantee this to safeguard that today's apps will work in future without recompilation?

**Comment by Tobski** [comment]
@krOoze so I think we can say with certainty that vkEnumerateInstanceVersion as linked against via something that looks like Vulkan 1.0 would never return "2" in the major version.

As it so happens, we have language currently in review that basically states that a major version break means backwards incompatibility - both that there can be incompatibility and that we won't do a major version without incompatibility. Once present, that language is us (the Vulkan WG) promising to developers that we won't let the scenario you're worried about happen , which I think is as good as we can do as for defining the behaviour of a possible future API.

**Comment by krOoze** [comment]
1: probably fixed in 1.2.137, but #1231 
@Tobski 2: Still, that probably means Vulkan 1.* should then state that 2.*+ is never returned from the command.
