### ISSUE TITLE
Specification copyright prevents changing Type information?

### ISSUE THREAD

**Issue by maierfelix** [KhronosGroup/Vulkan-Docs#905]
I'm trying to auto-generate a documentation for a language binding project, but the language types differ a lot. The [license](https://www.khronos.org/registry/speccopyright.html) explicitly tells, that the specification data must stay unmodified. Is there a chance to add something like: Type informations might be modified, but textual information must be retained

or would `Such distributed specification may be reformatted AS LONG AS the contents of the specification are not changed in any way` allow such changes?

Thanks!

Edit: [here](https://prnt.sc/md94du) is an example what the documentation looks like, I will add a link to the original specification for each page. I have to replace all types like `NULL`=>null or pointer=>reference to fit the language.

**Comment by oddhack** [comment]
We intend to allow reuse and adaptation of the Vulkan spec. The COPYING.md file at the top level of the spec repository attempts to make this clear, and includes an FAQ which addresses your use case.

**Comment by maierfelix** [comment]
Thanks!
