### ISSUE TITLE
minTexelBufferOffsetAlignment described as maximum

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#91]
> minTexelBufferOffsetAlignment is the minimum required alignment, [...]. This limit is a maximum, not a minimum.

How is it a maximum?

Maybe this means the value in the Required Limits table is a maximum value for the minimum alignment, but that table already says that (with a "max" in the appropriate column), and that information doesn't belong in the section above.

Same for minUniformBufferOffsetAlignment, minStorageBufferOffsetAlignment.

**Comment by oddhack** [comment]
Agreed. I proposed an internal MR to drop the "This limit" sentence in each case.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.6 spec update.
