### ISSUE TITLE
Why Vulkan has fences?

### ISSUE THREAD

**Issue by procedural** [KhronosGroup/Vulkan-Docs#918]
When you can submit an event and spin on it on the host?

**Comment by critsec** [comment]
Because spinning is inefficient.

**Comment by procedural** [comment]
@critsec is this the only reason? :)

**Comment by krOoze** [comment]
`vkGetEventStatus` nor `vkCmdSetEvent` define a memory dependency (only `vkCmdWaitEvents` does), nor a memory domain op. So unless that is wrongly specified (#755), you cannot do anything interesting with it anyway.

**Comment by procedural** [comment]
@krOoze fences don't define memory dependencies too, as far as I know?

**Comment by krOoze** [comment]
@procedural They do include device memory access. COHERENT memory (or explicit invalidate) provide the second half.

**Comment by procedural** [comment]
@krOoze I thought coherent memory and explicit invalidates are always visible to the device regardless of fences? Update a coherently mapped buffer and the changes become visible in the middle of command buffer execution, no?

**Comment by krOoze** [comment]
Anyway, I only wanted to link the other issue here which contains the similar idea of using events for device->host sync. I think the Events (though they technically allow it) were not really designed to do that (well).

flushes give implicit (convenience?) guarantee if the `vkSubmit` is called afterwards. AFAIK other way around (i.e. invalidate) still needs a fence beforehand. Which makes sense, as `vkSubmit` execution may continue past that command returning and you have no way to know (without a fence) when it finishes.

**Comment by procedural** [comment]
> I think the Events (though they technically allow it) were not really designed to do that (well).

That's why I opened this issue: why exactly? :)

**Comment by procedural** [comment]
Look what I found :)

![khronos-vulkan-gdc_mar15](https://user-images.githubusercontent.com/28234322/53323467-49eb3000-38ef-11e9-93a6-7e624d27a020.png)

**Comment by krOoze** [comment]
@procedural  An old presentation slide listing the Event's methods?

**Comment by procedural** [comment]
@krOoze "Command buffers can signal _events_ as they complete execution"

Looks like fences were introduced to replace event signaling. Still have no idea why.

**Comment by krOoze** [comment]
@procedural Yes, that's what `vkCmdSetEvent` means. How is that new information?

> Looks like fences were introduced to replace event signaling. Still have no idea why.

non-sequitur

**Comment by procedural** [comment]
> Yes, that's what vkCmdSetEvent means.

Calling vkCmdSetEvent at the end of command buffer doesn't guarantee that command buffer completed execution afaik.

**Comment by krOoze** [comment]
Interpreting presentation slides is always dangerous. Always see slides with speaker.
https://youtu.be/qKbtrVEhaw8?t=1510
"And also, if the command buffers complete execution, they can signal **Fences**."

**Comment by procedural** [comment]
@krOoze nice find :) What a mess tho, he shows slides on events, he talks about events, and only at the end he says "fences" when the slide says "events".

**Comment by krOoze** [comment]
Yes, he does not even talk about Barriers, Semaphores, and Fences, while having a full slide about Events (which are, at least currently, somewhat optional to use). Though what can one want from a prerelease presentation; everyone was glad to get any breadcrumbs info about Vulkan...

**Comment by procedural** [comment]
> PS: IMO it is bit pointless to dig in history now like that.

Ok then.
