### ISSUE TITLE
256-bit standard sparse image block sizes

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#93]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#sparsememory-standard-sizes

Standard sparse image block shapes are only defined up to 128-bit pixel size. What happens if an implementation supports 256-bit formats like VK_FORMAT_R64G64B64A64_UINT for sparse images? (Maybe no implementation does today, but I don't see anything stopping them in the future.)

Should there be a standard 256-bit block shape? If not, does that mean implementations supporting 256-bit sparse images aren't allowed to advertise residencyStandard2DBlockShape even if they follow the standard for all the defined sizes?

(I'd be happy if the spec explicitly said that pixel sizes not in the table do not have a standard block shape and can only be supported as custom shapes.)

**Comment by oddhack** [comment]
This should be fixed in the 1.1.71 spec update.
