### ISSUE TITLE
Synchronization with presentation is confusing.

### ISSUE THREAD

**Issue by zakarumych** [KhronosGroup/Vulkan-Docs#932]
I was reading synchronization examples [here](https://github.com/KhronosGroup/Vulkan-Docs/wiki/Synchronization-Examples#swapchain-image-acquire-and-present) and value of `.srcStageMask` confuses me.
Even though there is the comment

  `// .srcStageMask needs to be a part of pWaitDstStageMask in the WSI semaphore.`

it confuses even more, as it doesn't align with other semaphore + barrier synchronization examples.
Is it special case for WSI? If yes then why it works like that and where in spec I can read about that?

**Comment by omni-viral** [comment]
And what the purpose of `.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT` if `.loadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE`?

**Comment by krOoze** [comment]
Not sure what exactly is confusing you. From `vkAcquireNextImageKHR` you will get signal-pending semaphore. You need to wait on the semaphore if you want to use the image. You want to wait on the semaphore in as logically-latest stage as possible (`pWaitDstStageMask`). That stage must be followed up by a barrier if you want to change image layout; therefore `.srcStageMask` will probably be same value as `pWaitDstStageMask`.

`VK_ATTACHMENT_LOAD_OP_DONT_CARE` means it may load or clear or anything in between. It still happens in the `VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT`  with `VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT` (per [spec](http://vulkan.hys.cz/1.1-extensions/vkspec.html#renderpass-load-store-ops)).

I explain it [here a bit](https://github.com/krOoze/Hello_Triangle/blob/master/doc/synchronizationTutorial.md) by other words if it helps...

**Comment by omni-viral** [comment]
On the same page, right above block I linked there is a snippet for general case of barrier after semaphore wait

```
vkCmdDispatch(...);

... // Semaphore signal/wait happens here

VkImageMemoryBarrier imageMemoryBarrier = {
  ...
  .srcAccessMask = 0};

vkCmdPipelineBarrier(
    ...
    VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, // srcStageMask
    ...);


vkCmdDispatch(...);
```

As you can see it uses `VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT` as `srcStageMask`.

**Comment by krOoze** [comment]
That example seems incorrect or at least unclear to me.

Assuming the first `vkCmdDispatch` writes an image we need in our second `vkCmdDispatch`, then `srcStageMask` and `pWaitDstStageMask` should be `VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT`. `VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT` is equivalent and acceptable in this case, but more brittle. Assuming unrelated `vkCmdDraw` was added before the `vkCmdDispatch`, the `TOP_OF_PIPE` in `pWaitDstStageMask` would then unnecesserily block all that unrelated work.

I don't understand what the author meant in the introductory paragraph linking `pWaitDstStageMask` and `dstStageMask`. There's probably an error. It would be true only if `srcStageMask` also equal `dstStageMask` (as suggested above). Otherwisely if  `srcStageMask=VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT` and `pWaitDstStageMask=dstStageMask=VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT` then TMK the Application is missynchronized as there would be hazard between the layout transition and the first `vkCmdDispatch` image access.

**Comment by omni-viral** [comment]
I was under impression that for pipeline barrier following waiting for semaphore this:
```
srcStageMask=VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT
pWaitDstStageMask=dstStageMask=<StagesThatUseResource>
```
is exactly what spec requires for proper synchronization.

**Comment by krOoze** [comment]
Nah, that would be weird. The tricky part is:

> [...] when the required execution dependency is satisfied by other means [...]

Which in this case is not.
That would be the case if e.g. you had the samaphore wait in one batch, and the layout transition was in subsequent batch. Or e.g. if Fences are at play or whatevs...

If in doubt use the normative parts of the spec as a guide. It may be bit harder to read initially, but you will have less of a gulash in your head about Vulkan sync understanding it on a conceptual level.

**Comment by omni-viral** [comment]
> samaphore wait in one batch, and the layout transition was in subsequent batch

Isn't it irrelevant?

**Comment by krOoze** [comment]
It is not. Semaphore wait includes in its destination scope all the subsequent batches. That would be one way how "execution dependency is satisfied by other means" might happen.

**Comment by omni-viral** [comment]
Semaphore wait includes current batch too.

**Comment by krOoze** [comment]
Yes but only from `pWaitDstStageMask` onwards. Subsequent batches are covered in whole.

**Comment by omni-viral** [comment]
The second synchronization scope includes every command submitted in the same batch. In the case of vkQueueSubmit, the second synchronization scope is limited to operations on the pipeline stages determined by the destination stage mask specified by the corresponding element of pWaitDstStageMask. Also, in the case of vkQueueSubmit, the second synchronization scope additionally includes all commands that occur later in submission order.

Commands from subsequent batches, but `limited to operations on the pipeline stages determined by the destination stage mask specified by the corresponding element of pWaitDstStageMask`

**Comment by krOoze** [comment]
We are getting off-topic. Let's pretend I said `vkDeviceWaitIdle` for simplicity.
Anyway your quote above says exactly why in our example execution dependency is not covered "by other means"...

**Comment by omni-viral** [comment]
So, am I understand it correctly now?
We want layout transition to wait for the <particular stage> too, hence we specify it in `srcStageMask`
And having `pWaitDstStageMask = srcStageMask = dstStageMask = <particular stage>` creates execution dependency `semaphore signal -> layout transition -> operations at <particular stage>`

**Comment by krOoze** [comment]
Yeah, that is my understanding of the spec. @Tobski and @tobine authored the wiki so let's see...

**Comment by Tobski** [comment]
I'm a bit swamped for time just now with GDC coming up, but I'll look at this soon!

**Comment by Tobski** [comment]
Wow I forgot about this - sorry all. I have now updated the Sync examples page, and it was indeed the compute dependency pre-amble about dstStageMask that was wrong. I've now removed that paragraph and written an explanatory paragraph that should make more sense for that section... please see if this improves things: https://github.com/KhronosGroup/Vulkan-Docs/wiki/Synchronization-Examples#dependency-between-images-where-a-layout-transition-is-required-expressed-after-the-semaphore-signal

**Comment by oddhack** [comment]
Closing this based on @tobski's wiki update. @zakarumych please reopen with comment if there is more to be done.

**Comment by ShabbyX** [comment]
Closing based on the last comment. Looks like it's accidentally left open.
