### ISSUE TITLE
Why VkBufferDeviceAddressCreateInfoEXT::deviceAddress is of type VkDeviceSize and not of type VkDeviceAddress?

### ISSUE THREAD

**Issue by procedural** [KhronosGroup/Vulkan-Docs#934]
Shouldn't [`VkBufferDeviceAddressCreateInfoEXT::deviceAddress`](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkBufferDeviceAddressCreateInfoEXT.html) be of type `VkDeviceAddress`?

**Comment by oddhack** [comment]
This should be fixed in the 1.1.104 spec update.
