### ISSUE TITLE
How to set object name at object creation time via VK_EXT_debug_utils?

### ISSUE THREAD

**Issue by guwangfeng** [KhronosGroup/Vulkan-Docs#936]
Hi,

The code snippet is:

VkRenderPassCreateInfo createInfo = {…};
VkRenderPass renderPass = VK_NULL_HANDLE;
vkCreateRenderPass(device, &createInfo, NULL, &renderPass);
vkSetDebugUtilsObjectNameEXT(renderPass, "renderPassForDrawTree");

I received the following message via the callback:

Validation -[VUID-VkRenderPassCreateInfo-pDependencies-00837](0): Dependency 1 specifies a source stage mask that contains stages not in the GRAPHICS pipeline as used by the source subpass 0. The Vulkan spec states: For any element of pDependencies, if the srcSubpass is not VK_SUBPASS_EXTERNAL, all stage flags included in the srcStageMask member of that dependency must be a pipeline stage supported by the pipeline identified by the pipelineBindPoint member of the source subpass. (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkRenderPassCreateInfo-pDependencies-00837)
                                     Objects - 1
                                     Object[0] - Type VK_OBJECT_TYPE_UNKNOWN, Value 0000000000000000, Name "(null)"

As you can see, the error message doesn't show the name since the name must be set until a object handle is created. 

Do we have a way to set the object name at object creation time so that the message output likes:

 Objects - 1
                                     Object[0] - Type VK_OBJECT_TYPE_RENDERPASS, Value 0000000000000000, Name "renderPassForDrawTree"

?

**Comment by krOoze** [comment]
You cannot.
Object that does not exist (fails creation) obviously cannot have a name.

If you want to track stuff in some more complex way than this allows, you can use `pUserData`

**Comment by mikes-lunarg** [comment]
As @krOoze says, there isn't a way to do this with the current extension.  If you have ideas to improve validation messages for failed object creation, you can open a feature request on https://github.com/KhronosGroup/Vulkan-ValidationLayers
