### ISSUE TITLE
KHR_vulkan_glsl unused type declaration simplification

### ISSUE THREAD

**Issue by archimedus** [KhronosGroup/Vulkan-Docs#937]
Many SPIR-V examples in [GL_KHR_vulkan_glsl.txt](https://github.com/KhronosGroup/GLSL/blob/master/extensions/khr/GL_KHR_vulkan_glsl.txt) contain fragment that is not used in any of the examples inside the file:

        %2 = OpTypeVoid
        %3 = OpTypeFunction %2

I can't find reason it was added for. May be it can be removed for clarity?

**Comment by oddhack** [comment]
Please ask this question on the GLSL repository, where the extension is kept. Thanks.

https://github.com/KhronosGroup/GLSL/issues/new

**Comment by archimedus** [comment]
ok.
Thanks for quick answer.
