### ISSUE TITLE
Does spec has anything to say on identical memory types?

### ISSUE THREAD

**Issue by procedural** [KhronosGroup/Vulkan-Docs#938]
Nvidia GT 1030, for example, reports two memory types with identical heap index and flags values, see `Memory type 7` and `Memory type 8` here: https://vulkan.gpuinfo.org/displayreport.php?id=5336#memory

For my code that chooses memory types programmably it creates ambiguity as to which memory type to choose. They have the same heap index and flags, does it mean they are the same and I can pick any or does it mean one of them is secretly faster than the other one and I should pay IHV to tell me which one is faster or does it mean whoever wrote the driver code for that card was drunk and Khronos has nothing to do with this and I should simply ignore this oddity?

**Comment by krOoze** [comment]
Yes.
Image Memory Requirements say which memory type given Image is allowed to be allocated from.
That implies "identical" memory types differ by which Image Creation parameters they are compatible with.

For the specific case of NV, I answered it here:  https://stackoverflow.com/questions/48242445/why-does-vkgetphysicaldevicememoryproperties-return-multiple-identical-memory-ty

**Comment by procedural** [comment]
> Image Memory Requirements say which memory type given Image is allowed to be allocated from.
Does it have any implications on memory aliasing? Memory aliasing chapter doesn't mention multiple resources allocated from different memory types at the same byte offset? If it has no implications, why wouldn't driver report one memory type then, since the only thing you can do with memory and resources is to bind them?

**Comment by krOoze** [comment]
Nah that would be weird. I think it is safe to assume that freshly allocated memory will always be unaliased. I vaguely remember it being specifically pointed out somewhere in spec, but it seems so riddiculously obvious that I won't even bother looking it up.

Assumably, and that is Q for NV, they simply want to control where\when do you allocate your depth images. Remember that at `vkAllocate` time it has no way to know what kind of image the memory will be used for. If they want to restrict memory specifically for e.g. depth images, they have to make a separate Memory Type.

PS: For completeness to your original Q. Yeah, everything else being equal the memory with lower index is supposed to be (non secretly) faster.

And yeah, at the moment I think this is specific to NV and most others expose what you would expect.

**Comment by procedural** [comment]
> Remember that at vkAllocate time it has no way to know what kind of image the memory will be used for.

You're binding image handles to memory types, not raw vkAllocate memory. To create an image handler, you specify everything about that image, including whether it's color or depth.

**Comment by procedural** [comment]
> And yeah, at the moment I think this is specific to NV and most others expose what you would expect.

Thanks, good to know, cc @jeffbolznv then?

**Comment by krOoze** [comment]
Yes, handles **to raw memory**.

If the memory it `vkAllocate`d did not fit, the driver would have to allocate a different one at the `vkBind` time. That would compromize core ideals of Vulkan: thin drivers and performance transparency.

**Comment by procedural** [comment]
> If the memory it vkAllocated did not fit

You query exactly how much memory a color or depth image needs with `vkGetImageMemoryRequirements` before binding it to a memory type.

**Comment by krOoze** [comment]
I mean if the memory was not compatible to be bound to given Image, e.g. because of `VkImageCreateInfo::usage`.

**Comment by procedural** [comment]
> if the memory was not compatible to be bound to given Image

Compatible with what?

**Comment by krOoze** [comment]
As said above. Because of `usage`, `format` or `flags` or something like that.

Separate question is why NV would want to do that (perf benefit maybe??). The relevant article is in the SO I linked, but here goes: https://developer.nvidia.com/what%E2%80%99s-your-vulkan-memory-type
For the rest you pinged a proper person that might give us the juicy deets...

**Comment by procedural** [comment]
Does spec allow memory requirements retrieved with `vkGetImageMemoryRequirements` change with system time for the same image?

In our case, can `VkMemoryRequirements::memoryTypeBits` change for the same image at different points of system time?

For example, at this point in time `vkGetImageMemoryRequirements` returns `VkMemoryRequirements::memoryTypeBits` with a bit == 1 for `Memory type 7` and a bit == 0 for `Memory type 8`, but if something happened on a system, say, you no longer have available device memory, can `vkGetImageMemoryRequirements` **for the same image** return `VkMemoryRequirements::memoryTypeBits` now with a bit == 0 for `Memory type 7` and a bit == 1 for `Memory type 8`?

**Comment by procedural** [comment]
https://github.com/KhronosGroup/Vulkan-Docs/issues/939

**Comment by procedural** [comment]
So far not a single possible combination of `VkImageCreateInfo` parameters result in an image that needs to be placed in `Memory type 8`, thus I suspect a dependence on time.

**Comment by krOoze** [comment]
> So far not a single possible combination of VkImageCreateInfo parameters result in an image that needs to be placed in Memory type 8, thus I suspect a dependence on time.

Nah, time dependence is relatively strictly defined in the spec below the `vkGetImageMemoryRequirements`.

Maybe it is memory type specifically for `VkBuffer`s then? Try `vkGetBufferMemoryRequirements`.

**Comment by procedural** [comment]
> Maybe it is memory type specifically for VkBuffers then? Try vkGetBufferMemoryRequirements.

Thanks, will try...

**Comment by procedural** [comment]
Nope, buffers ignore `Memory type 8` too.

**Comment by procedural** [comment]
Well, if all image and buffer types I care about ignore `Memory type 8`, and Vulkan standard guarantees they won't suddenly start to require `Memory type 8` at some point in application's lifetime (#939), then I can ignore it for now as a quirk of this specific implementation.

I'll reopen this issue if I notice something strange related to these memory type twins.

**Comment by procedural** [comment]
So apparently all Nvidia graphics card expose 11 memory types, 7 of which no-one-knows-what-they-are (All point to CPU heap with no flags at all. What?), 2 your typical visible | coherent, visible | coherent | cached, and 2 identical device local heaps, second of which I couldn't hit with any image and buffer parameter combinations.

Since all their cards are like this, I wish Nvidia would just explain wtf those are.

**Comment by krOoze** [comment]
@procedural Read the linked StackOverflow answer. The 7 are 1 for buffers, 1 for images, 1 per supported depth format. The linked article explain this, but still not sure why NV felt the need to do this; spilling depth buffers to host-side still sounds bit desperate to me...

Still not sure what those two device side do. If you figure it out, share. If you are impatient, there's not that many options (assuming conformant driver); for images it would be for sparse, transient, linearly tiled, or for specific depth format. For buffers any combination of `usage` and `flags` can change memory type, but I think testing only each bit in isolation should suffice. Alternatively it could be just fake memory type for the external memory.

Anyway you inspired me to write https://github.com/KhronosGroup/Vulkan-Tools/pull/158 which should print that info in `vulkaninfo`...

**Comment by krOoze** [comment]
@procedural Read the linked StackOverflow answer. The 7 are 1 for buffers, 1 for (color) images, 1 per supported depth format. The linked article explain this, but still not sure why NV felt the need to do this; spilling depth buffers to host-side still sounds bit desperate to me...

Still not sure what those two device side do. If you figure it out, share. If you are impatient, there's not that many options (assuming conformant driver); for images it would be for sparse, transient, linearly tiled, or for specific depth format. For buffers any combination of `usage` and `flags` can change memory type, but I think testing only each bit in isolation should suffice. Alternatively it could be just fake memory type for the external memory.

Anyway you inspired me to write https://github.com/KhronosGroup/Vulkan-Tools/pull/158 which should print that info in `vulkaninfo`...

**Comment by procedural** [comment]
> @procedural Read the linked StackOverflow answer. The 7 are 1 for buffers, 1 for (color) images, 1 per supported depth format.

Oh, right, thank you, I added that link to my bookmarks and forgot to read it... Yea, that article explains those first 7 types, I guess Nvidia didn't add flags to them so that user side programmable memory type picking would skip them, since these not really generic memory types. Kinda obscure to interpret an API object by a blog post from 2016 on some website, to be honest, but what can we do? :)

> The linked article explain this, but still not sure why NV felt the need to do this; spilling depth buffers to host-side still sounds bit desperate to me...

You're right, my guess if you can spill even depth buffers, maybe those memory types represent managed memory that implicitly moves/copies resources from host to device and vice versa, and they point at host heap only because Vulkan has only one heap index... Not sure!

> Still not sure what those two device side do. If you figure it out, share.

Yeah, `Memory type 8` specifically, I will share if I ever hit it with some combination of flags, although I restrict my code to just slightly extended Vulkan 1.0, so probability of hitting it may be very low. :)

> Anyway you inspired me to write KhronosGroup/Vulkan-Tools#158 which should print that info in vulkaninfo...

Awesome! I see your loops are 4 level nested, I tried 7 yesterday to hit `Memory type 8`, probably an overkill, but still couldn't hit it! :)

```c
for (unsigned INDEX_FLAG = 0; INDEX_FLAG < _countof(allFlags); INDEX_FLAG += 1) {
  for (unsigned INDEX_TYPE = 0; INDEX_TYPE < _countof(allTypes); INDEX_TYPE += 1) {
    for (unsigned INDEX_FORMAT = 1; INDEX_FORMAT < (VK_FORMAT_ASTC_12x12_SRGB_BLOCK + 1); INDEX_FORMAT += 1) {
      for (unsigned INDEX_SAMPLES = 0; INDEX_SAMPLES < _countof(allSampleCounts); INDEX_SAMPLES += 1) {
        for (unsigned INDEX_TILING = 0; INDEX_TILING < _countof(allTiling); INDEX_TILING += 1) {
          for (unsigned INDEX_USAGE = 0; INDEX_USAGE < _countof(allUsages); INDEX_USAGE += 1) {
            for (unsigned INDEX_QUEUE = 0; INDEX_QUEUE < queueFamilyIndexCount; INDEX_QUEUE += 1) {
```

**Comment by krOoze** [comment]
> Kinda obscure to interpret an API object by a blog post from 2016 on some website, to be honest, but what can we do? :)

Is official blog, not "some website".

The thing here with the memory types at least should be a non-problem assuming your memory type selection loop is healthy and free-of-assumptions as the spec recommends...
The queue selection is bit of a larger problem IMO (#569), as far as the fundamental Vulkan fundamental execution+memory model goes.

> I tried 7 yesterday to hit Memory type 8

Looks pretty robust. That leaves extensions (should be `VK_IMAGE_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT` only), buffer (any combination of `usage`x`flag`), not used for anything (red herring), or non-conformant driver. I guess, with patience @jeffbolznv will provide the spoilers. Meanwhile I welcome your input at KhronosGroup/Vulkan-Tools#158 if you have any ideas how best to report this to users.

**Comment by jeffbolznv** [comment]
I think memory type 8 is only used on old hardware (Maxwell1 and earlier?). I also think the several depth-format-specific non-local memory types are unused on Turing.
