### ISSUE TITLE
vkGetImageMemoryRequirements time independence guarantee

### ISSUE THREAD

**Issue by procedural** [KhronosGroup/Vulkan-Docs#939]
For the same image, does Vulkan spec guarantees that `vkGetImageMemoryRequirements` always returns `VkMemoryRequirements` with the same values for the duration of the application's lifetime or there is no such guarantee?

At any point of application's time, can driver return different `VkMemoryRequirements` values for the same image?

**Comment by krOoze** [comment]
Yes there is such guarantee:

> 2.5.1. Lifetime of Retrieved Results
>Information is retrieved from the implementation with commands of the form `vkGet*` and `vkEnumerate*`.
>
> Unless otherwise specified for an individual command, the results are _invariant_; that is, they will remain unchanged when retrieved again by calling the same command with the same parameters, so long as those parameters themselves all remain valid.

Furthermore there are some special guarantees below `VkMemoryRequirements`, e.g.:

> For images created with a color format, the `memoryTypeBits` member is identical for all `VkImage` objects created with the same combination of values for the `tiling` member, the `VK_IMAGE_CREATE_SPARSE_BINDING_BIT` bit of the flags member, the `VK_IMAGE_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT` bit of the flags member, `handleTypes` member of `VkExternalMemoryImageCreateInfo`, and the `VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT` of the usage member in the `VkImageCreateInfo` structure passed to `vkCreateImage`.

That somewhat at minimum implies same image creation arguments yield same `memoryTypeBits`.

**Comment by krOoze** [comment]
PS: I would prefer to answer such questions at StackOverflow or Reddit or Vulkan Forums or such. I would prefer Issues in this repo to be reserved for situations where it is strongly suspected there is specific bug in the Spec. If you just need fetch a spec quote and need no people with internal knowledge, it can be done on those external sites without impacting searchability and issue backlog of this repo.

**Comment by procedural** [comment]
@krOoze Thank you for answer! Will close for now, if this is true.

> I would prefer to answer such questions at StackOverflow or Reddit or Vulkan Forums or such.

I'm not on those websites often, or at all. I open issues here because they can be reopened if needed. I opened this one, for example, because I think Nvidia did something odd with a concept of memory type, and it may go against the spec or rely on its underspecification. Not in this instance, I hope.
