### ISSUE TITLE
sRGB alpha in ASTC formats

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#94]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#features-formats-definition says:

> VK_FORMAT_R8G8B8A8_SRGB: A four-component, 32-bit unsigned normalized format that has an 8-bit R component stored with sRGB nonlinear encoding in byte 0, an 8-bit G component stored with sRGB nonlinear encoding in byte 1, an 8-bit B component stored with sRGB nonlinear encoding in byte 2, and an 8-bit A component in byte 3.
> ...
> VK_FORMAT_ASTC_4x4_SRGB_BLOCK: A four-component, ASTC compressed format where each 4x4 block consists of 128-bits of encoded image data which is decoded as unsigned normalized RGBA image data with sRGB nonlinear encoding. 

For all of the non-ASTC SRGB formats, the format descriptions are explicit that the sRGB encoding only applies to the RGB channels, not A, so they're consistent with the definition of "SRGB" in https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#features-formats-numericformat :

> SRGB: The R, G, and B components are unsigned normalized values that represent values using sRGB nonlinear encoding, while the A component (if one exists) is a regular unsigned normalized value

But the ASTC format descriptions don't follow that patterns, so it sounds like maybe sRGB applies to all channels.

I think the ASTC spec (https://www.khronos.org/registry/dataformat/specs/1.1/dataformat.1.1.html#_weight_application per Vulkan's normative references) says that each of the 4 color components gets passed to the sRGB conversion block independently, but https://www.khronos.org/registry/dataformat/specs/1.1/dataformat.1.1.html#srgbgamma defines sRGB conversion in terms of a (R,G,B) tuple, so it's rather unclear what should actually happen to the A component.

ARM's software ASTC encoder applies sRGB conversion to just the RGB channels (https://github.com/ARM-software/astc-encoder/blob/master/Source/astc_image_load_store.cpp#L784). I don't know what hardware does.

The behaviour ought to be made clearer in the Vulkan spec and/or in the Khronos Data Format Specification.

**Comment by janharaldfredriksen-arm** [comment]
>The behaviour ought to be made clearer in the Vulkan spec and/or in the Khronos Data Format Specification

We should clarify both. The sRGB conversion should only apply to the RGB components, but we should verify that that's what all the implementations do.

The description in the Data Format spec is inherited from the [GLES extension](https://www.khronos.org/registry/gles/extensions/KHR/texture_compression_astc_hdr.txt) so we should clarify that too.

I'll create a couple of internal issues to sort this out.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.6 spec update.
