### ISSUE TITLE
Probably `ifdef` typo in 1.1.103

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#942]
It seems at
https://github.com/KhronosGroup/Vulkan-Docs/commit/4ad4fd17161efd9bfd1125c0c9d17db6fb276216#diff-7f1bf77addf3f1ebaef660565594c697R57

the `ifdef` should been `ifndef`.

**Comment by oddhack** [comment]
We have an internal MR queued up to address this - thanks!

**Comment by oddhack** [comment]
This should be fixed in the 1.1.106 spec update.
