### ISSUE TITLE
Ambiguous valid usage condition in vkMapMemory

### ISSUE THREAD

**Issue by edrickhong** [KhronosGroup/Vulkan-Docs#946]
https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#vkMapMemory

Under valid usage, a clause states:
memory must not have been allocated with multiple instances

The multiple instances here is ambiguous. Does it refer to a vulkan instance or multiple allocations or what?

**Comment by jeffbolznv** [comment]
It means this definition from the glossary:

```
Instance (Memory)::
    In a logical device representing more than one physical device, some
    device memory allocations have the requested amount of memory allocated
    multiple times, once for each physical device in a device mask.
    Each such replicated allocation is an instance of the device memory.
```

**Comment by jeffbolznv** [comment]
Closing.
