### ISSUE TITLE
Bilinear filtering of depth comparisons

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#95]
In OpenGL, when doing depth comparisons on non-NEAREST filtered images, the result "may be computed by comparing more than one depth texture value to the texture reference value. The details of this are implementation-dependent, [...]", and the depth comparison processing seems to replace all the usual texture filtering stages.

I think Vulkan's only mention of linear filtering of depth images is:

> VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT ... If the format being queried is a depth/stencil format, this only indicates that the depth aspect is linearly filterable.

As far as I can see, it's not defined any differently to the standard filtering of any other image, except that the depth comparison happens in one of the stages before the filtering. That means it's going to be bilinearly filtering 4 comparison results, potentially with mipmaps and anisotropy too (and component swizzling).

(I think optimal depth texture formats are required to have VkImageFormatProperties::maxMipLevels > 1, given that "maxMipLevels must either be equal to 1 (valid only if tiling is VK_IMAGE_TILING_LINEAR) or [larger]" and they're not TILING_LINEAR, so I don't see anything stopping an application asking for mipmapping on depth comparisons.)

Is that an intentional change from OpenGL? (Maybe it is but I thought it's best to check.)

**Comment by jeffbolznv** [comment]
OpenGL supports the full texturing pipeline on depth-compared texture (including swizzling, etc.). So does Vulkan, though we didn't have the weasel-words to make it so implementations aren't required to do full linear filtering. There's a change in progress for this already.

**Comment by oddhack** [comment]
Assign to @jeffbolznv to close this when the internal change is complete (Jeff, I'm not sure what the internal tracking issue is - if you haven't already, you might add a link back to the public issue from that to help track it).

**Comment by TobiasHector** [comment]
This got fixed ages ago. There's now this wording:

> If the format being queried is a depth/stencil format, this bit only indicates that the depth aspect
(not the stencil aspect) of an image of this format supports linear filtering, and that linear
filtering of the depth aspect is supported whether depth compare is enabled in the sampler or
not. If this bit is not present, linear filtering with depth compare disabled is unsupported and
linear filtering with depth compare enabled is supported, but may compute the filtered value in
an implementation-dependent manner which differs from the normal rules of linear filtering.
The resulting value must be in the range [0,1] and should be proportional to, or a weighted
average of, the number of comparison passes or failures
