### ISSUE TITLE
Shouldn't shaderSampledImageArrayDynamicIndexing and shaderStorageImageArrayDynamicIndexing features include uniform texel buffers and storage texel buffers?

### ISSUE THREAD

**Issue by procedural** [KhronosGroup/Vulkan-Docs#952]
From Vulkan spec:

`shaderSampledImageArrayDynamicIndexing`:
> shaderSampledImageArrayDynamicIndexing specifies whether arrays of samplers or sampled images can be indexed by dynamically uniform integer expressions in shader code. If this feature is not enabled, resources with a descriptor type of **VK_DESCRIPTOR_TYPE_SAMPLER**, **VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER**, or **VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE** must be indexed only by constant integral expressions when aggregated into arrays in shader code. This also specifies whether shader modules can declare the SampledImageArrayDynamicIndexing capability.

`shaderStorageImageArrayDynamicIndexing`:
> shaderStorageImageArrayDynamicIndexing specifies whether arrays of storage images can be indexed by dynamically uniform integer expressions in shader code. If this feature is not enabled, resources with a descriptor type of **VK_DESCRIPTOR_TYPE_STORAGE_IMAGE** must be indexed only by constant integral expressions when aggregated into arrays in shader code. This also specifies whether shader modules can declare the StorageImageArrayDynamicIndexing capability.

Shouldn't `shaderSampledImageArrayDynamicIndexing` include `VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER` and `shaderStorageImageArrayDynamicIndexing` include `VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER`?

Or I miss something and arrays of `VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER` and `VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER` can always be dynamically indexed?

**Comment by jeffbolznv** [comment]
I noticed these were missing when working on VK_EXT_descriptor_indexing, and the way we resolved it is to add new features and SPIR-V capabilities for them in that extension:

```
| code:InputAttachmentArrayDynamicIndexingEXT | <<features-shaderInputAttachmentArrayDynamicIndexing,shaderInputAttachmentArrayDynamicIndexing>>
| code:UniformTexelBufferArrayDynamicIndexingEXT | <<features-shaderUniformTexelBufferArrayDynamicIndexing,shaderUniformTexelBufferArrayDynamicIndexing>>
| code:StorageTexelBufferArrayDynamicIndexingEXT | <<features-shaderStorageTexelBufferArrayDynamicIndexing,shaderStorageTexelBufferArrayDynamicIndexing>>
```

So core Vulkan 1.0/1.1 don't allow dynamically indexing these, it requires the descriptor_indexing extension. In retrospect, 1.0 should have had a way to enable this, but it was an oversight.

Closing.

**Comment by procedural** [comment]
@jeffbolznv thank you for clarification!
