### ISSUE TITLE
typo in fragmentdensitymapops.txt

### ISSUE THREAD

**Issue by programmerjake** [KhronosGroup/Vulkan-Docs#954]
https://github.com/KhronosGroup/Vulkan-Docs/blob/56e0289318a4cd23aa5f5dcfb290ee873be53b82/chapters/fragmentdensitymapops.txt#L47-L48

shouldn't that be `maxFragmentDensityTexelSize_{width}`?

**Comment by oddhack** [comment]
Thanks! This will be fixed in the next (1.1.109) spec update in a week or two.

**Comment by oddhack** [comment]
This should be fixed in the 1.1.109 spec update.

**Comment by programmerjake** [comment]
fixed
