### ISSUE TITLE
Specification of subdivision type in tessellation shaders

### ISSUE THREAD

**Issue by sheaf** [KhronosGroup/Vulkan-Docs#957]
It seems to me that the subdivision type (**Triangles**/**Quads**/**Isolines**) needs to be specified in the tessellation evaluation shader. Specifically, I have a program which performs as expected when:

* _VertexOrderCw_, _SpacingEqual_ and _OutputVertices 3_ are all specified in the tessellation control shader.
* _Triangles_ is specified in the tessellation evaluation shader.

If I remove the _Triangles_ execution mode from the tessellation evaluation shader (thus specifying no execution modes at all for this stage), and instead specify it within the tessellation control shader, then the program behaviour changes and gives unexpected output.

This is in contrast with the specification (21.1 _Tessellator_):

> The type of subdivision performed by the tessellator is specified by an _OpExecutionMode_ instruction in the tessellation evaluation or tessellation control shader using one of execution modes Triangles, Quads, and IsoLines.
> [...]
> Tessellation execution modes include:
> * Triangles, Quads, and IsoLines. These control the type of subdivision and topology of the output primitives. One mode **must** be set in at least one of the tessellation shader stages.
> [...]

I can include the source SPIR-V files were they to be of any use.    

If this is a problem in the implementation rather than the documentation, it might still be best to make note of this fact within the documentation? I lost quite a bit of time figuring it out.

**Comment by jeffbolznv** [comment]
This sounds like a bug in the implementation.

> it might still be best to make note of this fact within the documentation?

Make note of what, exactly?

**Comment by sheaf** [comment]
Fair enough if this kind of information doesn't belong in the specification, I understand. I just wanted to avoid other people losing time to this issue, and I thought mentioning that it is preferred to set the subdivision type in the tessellation evaluation shader might help in that regard.

**Comment by jeffbolznv** [comment]
It's not preferred one way or the other. However, GLSL for OpenGL originally required these to be set in specific stages, and it's possible that some implementations have bugs left over from those old assumptions.

**Comment by sheaf** [comment]
OK, thank you for the clarification. Should I file a bug somewhere else concerning the implementation?

**Comment by jeffbolznv** [comment]
Yeah, you should report it to the appropriate IHV. I don't actually know where that is for most of them, sorry.
