### ISSUE TITLE
vkBeginCommandBuffer on command buffers pending execution

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#96]
vkResetCommandBuffer's Valid Usage says:

> commandBuffer must not currently be pending execution 

But vkBeginCommandBuffer's Valid Usage doesn't say that, even though it might have exactly the same effect as resetting (with VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT). I can't see anywhere else with equivalent language for vkBeginCommandBuffer.

vkBeginCommandBuffer should probably have a similar requirement.

**Comment by ratchetfreak** [comment]
For vkBeginCommandBuffer:

> If commandBuffer was allocated from a VkCommandPool which did not have the VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT flag set, `commandBuffer` must be in the initial state. 

then a bit down:

> If a command buffer is in the executable state and the command buffer was allocated from a command pool with the VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT flag set, then vkBeginCommandBuffer implicitly resets the command buffer, behaving as if vkResetCommandBuffer had been called with VK_COMMAND_BUFFER_RESET_RELEASE_RESOURCES_BIT not set. It then puts the command buffer in the recording state.

This should probably be explicit in the valid usage though. Something like: 

> If commandBuffer was allocated from a VkCommandPool which has the VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT flag set, `commandBuffer` can: be in any state but mustnot: be pending execution. 

Though there is a clause that forbids the recording state which if the flag is set then it can be (because it implicitly resets first which does allow it to be in the recording state).

So a more conservative "`commandBuffer` mustnot: be pending execution" instead of the "not in recording state" clause and keeping the 2 clauses with the flag condition.

**Comment by philiptaylor** [comment]
I interpret "implicitly ... behaving as if vkResetCommandBuffer had been called" as just meaning that it has the same implementation behaviour as was defined for vkResetCommandBuffer, and not that you must also satisfy the Valid Usage requirements that were defined for explicit calls to vkResetCommandBuffer. (I agree that's not the only plausible interpretation, but I like to pick the more awkward interpretation when it's ambiguous.)

> Though there is a clause that forbids the recording state

Oh, I hadn't noticed that vkResetCommandBuffer can be called even in the recording state. I don't have an opinion on whether vkBeginCommandBuffer with RESET_COMMAND_BUFFER_BIT should be permitted while recording too (as long as it's unambiguous!)

**Comment by slippah** [comment]
Still working on this one - GDC prep is eating up a lot of time. We should have a resolution not too long after that.

**Comment by oddhack** [comment]
This should be dealt with in the 1.0.8 spec update.
