### ISSUE TITLE
Why Vulkan returns VkSubresourceLayout::size?

### ISSUE THREAD

**Issue by procedural** [KhronosGroup/Vulkan-Docs#969]
Why Vulkan returns VkSubresourceLayout::size if it's effectively just a `rowPitch * subresourceMipLevelHeight`? Is this a convenience thing or I (and Vulkan docs) miss an important information about it? Here is everything the documentation has to say about it:
> size is the size in bytes of the image subresource. size includes any extra memory that is required based on rowPitch.

**Comment by jeffbolznv** [comment]
This field primarily exists for images with optimal tiling where there can be padding in each row and at the bottom of the image, and we just defined it to do the most natural thing for linear tiling. It could potentially be larger than rowPitch*height even for linear tiling, for something like a sparse linear array image where each array slice would need its own page. I don't know if that actually happens in practice.

**Comment by procedural** [comment]
@jeffbolznv Thank you very much for your answer! This explains it. Should we add some of this to documentation or the existence of this issue will be enough?

**Comment by jeffbolznv** [comment]
I'm fine with just closing the issue.

**Comment by procedural** [comment]
Alright!
