### ISSUE TITLE
Sparse resource binding example code

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#97]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#sparsememory-examples

In both sparse resource examples, the code is missing the pAllocatorInfo argument in vkCreateImage.

In the advanced example:

The "free(pSparseReqs);" is in the wrong place - it should be outside the loop, not inside.

It says:

> ```
> VkDeviceSize lod0MemSize = totalBlocks * memoryRequirements.alignment;
> ```

I don't understand why it's multiplying by alignment - I think it wants the sparse block size in bytes, and I don't see any reason why that'd be the same value. (I'm not sure how you do get the block size, other than imageGranularity.width \* imageGranularity.height \* imageGranularity.depth \* GetBytesPerPixelOrPerCompressedBlockFromFormatUsingAGiantSwitchStatement(sparseImageInfo.format).)

The code doesn't correctly handle the case where imageMipTailFirstLod == 0 (e.g. if the first mip level is smaller than the sparse block size, or ALIGNED_MIP_SIZE and the first mip level is not an exact multiple of the sparse block size, which both sound like plausible cases). It would need to allocate the whole mip tail instead.

**Comment by oddhack** [comment]
Thanks. Code sample compilation errors are just embarassing. I'm hoping we can eventually break them out as separate source files in the asciidoc build that can actually be compiled as part of regression tests.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.40 spec update.

We eventually reviewed all the code samples, spread over many months, and closed out the last one. Hopefully no new bugs were introduced in the meantime.
