### ISSUE TITLE
PFN_vkReallocationFunction can never free memory

### ISSUE THREAD

**Issue by polarina** [KhronosGroup/Vulkan-Docs#973]
Section 10.1, _Host Memory_, of the Vulkan 1.0.109 specification, when describing `PFN_vkReallocationFunction`, states:

> If size is zero, then `pfnReallocation` must behave equivalently to a call to `PFN_vkFreeFunction` with the same `pUserData` parameter value, and `pMemory` equal to `pOriginal`.

This requirement is redundant as-is. Various other texts in the specification imply that `pfnReallocation` must never be used to free memory.

The specification list rules on when implementations may call which allocation callbacks.

> `pfnFree` may be called in the following situations:
>
> [... rules on when an implementation may free memory ...]

The `pfnReallocation` function is only mentioned earlier along with `pfnAllocation` on when it may be used to _allocate_ memory.

In addition, the `pOriginal` parameter of `PFN_vkReallocationFunction` is documented as:

> pOriginal must be either NULL or a pointer previously returned by pfnReallocation or
pfnAllocation of the **same allocator**.

This implies that implementations **must not** free memory using `pfnReallocation` during `vkDestroy*/vkFree*` commands since the provided allocator may not be the same as was given to `vkCreate*/vkAllocate*`. It does not matter if the two allocators are compatible, `pOriginal` must be from the _same allocator_.

I believe this to be an error. Implementations should be allowed to completely ignore `pfnAlloction` and `pfnFree` and use `pfnReallocation` for all their allocations and frees.

**Comment by critsec** [comment]
So to be specific, the two issues preventing a `pfnReallocation`-only implementation are:

1. The list of situations where `pfnFree` can be called should also allow `pfnReallocation(..., size=0, ...)`.

2. The `pOriginal` parameter should be allowed to come from a compatible allocator, not just the same allocator.

Correct? I believe that's all consistent with the intent and we should be able to make those fixes.

**Comment by polarina** [comment]
@critsec correct, fixing those two issues would resolve any issues I have wrt to the allocator functions. Thanks!

**Comment by critsec** [comment]
Thanks. I've created a change to do that internally and will get it reviewed.

**Comment by oddhack** [comment]
This should be fixed in the 1.1.112 spec update.
