### ISSUE TITLE
vkQueuePresentKHR with invalid VkQueue doesn't trigger any validation layers warnings

### ISSUE THREAD

**Issue by Kadowns** [KhronosGroup/Vulkan-Docs#976]
My application was crashing (without any exceptions or validation layers warnings) when calling vkQueuePresentKHR with an invalid VkQueue. Fixed it by properly calling vkGetDeviceQueue();

It would be nice if validation layers warned me about my mistake, just like when other calls are made with invalid handles.

SDK version is 1.1.106.0.

**Comment by oddhack** [comment]
Suggest refiling this on the https://github.com/KhronosGroup/Vulkan-ValidationLayers repo - this is the specification repo which doesn't appear related to what you're asking for.

**Comment by Kadowns** [comment]
Oh, i didn't saw that, thanks, i'll re-open the issue there.
