### ISSUE TITLE
Typo in VK_EXT_global_priority

### ISSUE THREAD

**Issue by WoodRain** [KhronosGroup/Vulkan-Docs#979]
Hi @lostgoat Paragraph 3 of VK_EXT_global_priority is :
"The global priority level of a queue shall take predence over the per-process queue priority. "
Seems the *predence* is a typo? precedence may be used.

**Comment by oddhack** [comment]
Thanks. We'll take care of this for the next spec update.

**Comment by oddhack** [comment]
Actually, in next week's update - internal MR is in the queue now.

**Comment by oddhack** [comment]
Should be fixed in the 1.1.113 spec update.
