### ISSUE TITLE
Last Modified Date syntax in extension specifications

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#98]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#_vk_khr_sampler_mirror_clamp_to_edge says:

> Last Modified Date: 16/02/2016 
> [...]
> Revision 1, 2016-02-16 (Tobias Hector)

Would be nice to use a consistent date format here, and in all other extensions, and preferably the yyyy-mm-dd format so that Americans won't cause so much confusion by trying to use the silly mm/dd/yyyy instead of the much better dd/mm/yyyy. There aren't many extensions defined yet so hopefully it's not too late to set a good precedent.

(To be fair it's not just Americans, apparently it's also Micronesians and Zimbabweans.)

**Comment by oddhack** [comment]
To be fair, this American has been lobbying inside Khronos to adopt the ISO date format for about the last decade, with indifferent success, and the named author on the extension is from the UK :-)

**Comment by TobiasHector** [comment]
Whoops. This is what I get for copy + pasting!

I wonder if this isn't the only extension with this problem... I'll try to get a fix in for the next release.

**Comment by oddhack** [comment]
Yeah, it's kinda a pain to have all the extensions in different branches for such things. I've gone through and made global cleanups to the GL extension registry a few times, which had less overhead because it was just editing a bunch of files in the same directory.

**Comment by TobiasHector** [comment]
Luckily we're still at the start, so we can set some guidelines and make sure people use them. I don't mind cleaning up the WSI - but the other extensions we'll have to wrestle with the authors :).

**Comment by oddhack** [comment]
This was mostly fixed in the 1.0.27 update and the few remaining cases should be dealt with in the next weekly update.
