### ISSUE TITLE
Render to any side cubemap texture by choice, it's possible?

### ISSUE THREAD

**Issue by Mikez2015** [KhronosGroup/Vulkan-Docs#981]
Is there a way in the latest version to render a any side of a cubic texture? I really don't want to use slow geometric shaders and gl_layer...

**Comment by critsec** [comment]
Each face of a cubemap is one layer in a `VkImage`. So create a `VkImageView` of just the layer/face you want to render to, and attach that to your framebuffer to render into it.

**Comment by oddhack** [comment]
@Mikez2015 if @critsec has answered your question, could you close this issue? Thanks.

**Comment by Mikez2015** [comment]
Yep, thx.
