### ISSUE TITLE
What aspectMask must include depends on VkImageSubresourceRange's procedure

### ISSUE THREAD

**Issue by procedural** [KhronosGroup/Vulkan-Docs#982]
It was all fine and dandy when around spec version 1.0.26 this quote:

> If using a depth/stencil format with both depth and stencil components, aspectMask must include at least one of VK_IMAGE_ASPECT_DEPTH_BIT and VK_IMAGE_ASPECT_STENCIL_BIT, and can include both.

was included in the context of Image Views chapter: https://vulkan.lunarg.com/doc/view/1.0.26.0/linux/vkspec.chunked/ch11s05.html

then I guess this quote was ripped from the Image Views chapter and now in the latest spec it exists in its own vacuum: https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkImageSubresourceRange.html

The issue is, `VkImageSubresourceRange` struct is used not only for `VkImageViewCreateInfo`, but for [`VkImageMemoryBarrier`](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkImageMemoryBarrier.html) as well that happily invalidates it:

> If image has a depth/stencil format with both depth and stencil components, then the aspectMask member of subresourceRange must include both VK_IMAGE_ASPECT_DEPTH_BIT and VK_IMAGE_ASPECT_STENCIL_BIT

**Comment by krOoze** [comment]
It does not invalidate it. You **must** follow both (that's how a specification works).

"both A and B" implies "A or B (or both)". There's no contradiction\double bind.

**Comment by krOoze** [comment]
I don't see any invalidation here.

**Comment by procedural** [comment]
> Both requirements are satisfiable together.

Now that I think about it, I guess you're right.

Closing.
