### ISSUE TITLE
All queues can execute transfer commands? :D

### ISSUE THREAD

**Issue by procedural** [KhronosGroup/Vulkan-Docs#983]
`vkCmdUpdateBuffer`'s documentation page states that

> The VK_BUFFER_USAGE_TRANSFER_DST_BIT must be specified in usage of VkBufferCreateInfo in order for the buffer to be compatible with vkCmdUpdateBuffer.

but it leaves ambiguous whether a queue that will call `vkCmdUpdateBuffer` should support `VK_QUEUE_TRANSFER_BIT` flag or not.

For example, Nvidia GPUs have 8 compute-only queues which don't have `VK_QUEUE_TRANSFER_BIT` flag set, can they call `vkCmdUpdateBuffer`?

**Comment by jozefkucia** [comment]
All compute and graphics queues support transfer commands:

> All  commands  that  are  allowed  on  a  queue  that  supports  transfer  operations  are
> also  allowed  on  a  queue  that  supports  either  graphics  or  compute  operations.
> Thus,   if   the   capabilities   of   a   queue   family   include   VK_QUEUE_GRAPHICS_BIT
>    or VK_QUEUE_COMPUTE_BIT,    then    reporting    the  VK_QUEUE_TRANSFER_BIT
>     capability separately for that queue family is optional.

**Comment by procedural** [comment]
> then **reporting** the VK_QUEUE_TRANSFER_BIT
capability separately for that queue family **is optional**

Oh, **reporting** is optional, got it, thanks, @jozefkucia!

**Comment by procedural** [comment]
I got used to AMD cards which set `VK_QUEUE_TRANSFER_BIT` flag anyway. :)

**Comment by jeffbolznv** [comment]
Also, the XML (and auto-generated VUs) are explicit about which queues are supported by each command:

```
        <command queues="transfer,graphics,compute" renderpass="outside" cmdbufferlevel="primary,secondary" pipeline="transfer">
            <proto><type>void</type> <name>vkCmdUpdateBuffer</name></proto>
...
```

**Comment by procedural** [comment]
@jeffbolznv yea, I know that, it's the absence of `VK_QUEUE_TRANSFER_BIT` set for compute queues put me off. :)

**Comment by procedural** [comment]
Guys, hold on, does it mean ALL queues are transfer-capable? :D

**Comment by procedural** [comment]
I know that queues with only `VK_QUEUE_TRANSFER_BIT` are actually DMA queues, but

for any kind of transfer

it means all queues can execute transfer commands?

**Comment by krOoze** [comment]
> it means all queues can execute transfer commands?

Sparse does not imply transfer I think (though it would be natural if it did).

Also any future\extension queue type might not support transfer.

**Comment by procedural** [comment]
> Sparse does not imply transfer I Think (though it would be natural if it did).

I think you're right, @jozefkucia's quote doesn't include `VK_QUEUE_SPARSE_BINDING_BIT`, which right now means queues must report both `VK_QUEUE_SPARSE_BINDING_BIT` and `VK_QUEUE_TRANSFER_BIT` if they support transfer on sparse queues.

**Comment by procedural** [comment]
Will close for now...

**Comment by krOoze** [comment]
PS: also do nothing queues, but I think that might be a spec bug.

**Comment by procedural** [comment]
@krOoze I called them ["no-one-knows-what-they-are"](https://github.com/KhronosGroup/Vulkan-Docs/issues/938#issuecomment-471473327) :)

**Comment by krOoze** [comment]
@procedural Well, `0` memory types can do stuff.
`0` queue family type can literaly do exactly nothing.

**Comment by procedural** [comment]
@krOoze yep!

**Comment by haasn** [comment]
Can I ask, why was this wording added? Why not force ICDs to report exactly the capabilities they support for a given queue, and instead reword that section to "all queues that support either COMPUTE_BIT or GRAPHICS_BIT must also advertise TRANSFER_BIT"?

It seems a bit weird to have implicit capabilities-implying-other-capabilities in an API all about explicitness.

**Comment by krOoze** [comment]
@haasn There's a subtle difference. Graphics pipeline and compute pipeline have load\store, therefore can act as if they can transfer. But that's cheating isn't it? If you copy from the Host, you **don't** want to use such queue. Instead you want to use real DMA queue, not the PIO queue.
