### ISSUE TITLE
The right way of setting immutable samplers

### ISSUE THREAD

**Issue by procedural** [KhronosGroup/Vulkan-Docs#985]
3 possible ways of setting immutable samplers which are not covered by the spec simply and clearly (someone will probably point me to some "obvious" spec language I missed because ha ha stupid me) nor they are currently caught by validation layers (tested with LunarG SDK 1.1.106):

 1. Setting `VkDescriptorSetLayoutBinding::pImmutableSamplers` with some immutable samplers and NOT passing a `VkWriteDescriptorSet` struct to `vkUpdateDescriptorSets` for these immutable samplers at all.
 2. Setting `VkDescriptorSetLayoutBinding::pImmutableSamplers` with some immutable samplers and passing a `VkWriteDescriptorSet` struct to `vkUpdateDescriptorSets` with `VkWriteDescriptorSet::descriptorCount` set to match `VkDescriptorSetLayoutBinding::descriptorCount` and `VkWriteDescriptorSet::pImageInfo[i].sampler` all set to NULL.
 3. Setting `VkDescriptorSetLayoutBinding::pImmutableSamplers` with some immutable samplers and passing a `VkWriteDescriptorSet` struct to `vkUpdateDescriptorSets` with `VkWriteDescriptorSet::descriptorCount` set to match `VkDescriptorSetLayoutBinding::descriptorCount` and `VkWriteDescriptorSet::pImageInfo[i].sampler` all set to the same immutable samplers to match `VkDescriptorSetLayoutBinding::pImmutableSamplers`.

**Comment by procedural** [comment]
I know, I just know some [Joe-an-Android-graphics-driver-programmer](https://twitter.com/zeuxcg/status/1023005009959481344) will

 1. leave some memory for the set uninitialized if 1 is the right way.
 2. overwrite the immutable samplers with NULLs if 2 is the right way.
 3. won't treat the samplers as immutable if 3 is the right way.

So it's better if two of these were officially considered as incorrect and validation layers could catch them.

**Comment by procedural** [comment]
If you invert the meaning of

> If descriptorType is VK_DESCRIPTOR_TYPE_SAMPLER or VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, and dstSet was not allocated with a layout that included immutable samplers for dstBinding with descriptorType, the sampler member of each element of pImageInfo must be a valid VkSampler object

it kinda invalidates the case number 3 (only if inverting the meaning of that text is a correct assumption), but 1 and 2 are still ambiguous.

**Comment by procedural** [comment]
> Immutable samplers are permanently bound into the set layout; later binding a sampler into an immutable sampler slot in a descriptor set is not allowed.

"later binding a sampler into an immutable sampler slot in a descriptor set is not allowed" is ambiguous, it can mean both that just passing a `VkWriteDescriptorSet` struct to `vkUpdateDescriptorSets` is considered as "binding" or that only setting `VkWriteDescriptorSet::pImageInfo[i].sampler` is considered as "binding".

**Comment by procedural** [comment]
When in doubt, I usually start looking how Khronos members code these things.

The Khronos Group / LunarG:

No examples of using `pImmutableSamplers`:

https://github.com/KhronosGroup/Vulkan-Tools/search?q=pImmutableSamplers

No CTS coverage of `pImmutableSamplers`, it looks like:

https://github.com/KhronosGroup/VK-GL-CTS/search?q=pImmutableSamplers

AMD:

https://github.com/GPUOpen-LibrariesAndSDKs/HelloVulkan/blob/2575360/hellovulkan/src/VulkanTexturedQuad.cpp#L656

passed to `descriptorSetLayoutBinding[1]`, but `vkUpdateDescriptorSets` writes only the first set:

https://github.com/GPUOpen-LibrariesAndSDKs/HelloVulkan/blob/2575360/hellovulkan/src/VulkanTexturedQuad.cpp#L699

so AMD people assume the case number 1 is the correct one.

Nvidia:

Couldn't find any use of `pImmutableSamplers` in https://github.com/nvpro-samples

@SaschaWillems' Vulkan examples:

No examples of using `pImmutableSamplers`:

https://github.com/SaschaWillems/Vulkan/search?q=pImmutableSamplers

**Comment by jeffbolznv** [comment]
This bit of spec language answers it, but it should be converted into a VU:

```
    Immutable samplers are permanently bound into the set layout; later
    binding a sampler into an immutable sampler slot in a descriptor set is
    not allowed.
```

**Comment by procedural** [comment]
> binding a sampler into an immutable sampler slot in a descriptor set

But... descriptor sets don't have immutable sampler slots? Only regular `VkWriteDescriptorSet::pImageInfo[i].sampler` slots...

**Comment by procedural** [comment]
I guess you meant immutable sampler`'s` slot.

Anyway, it still doesn't answer what "binding" is exactly.

Based on AMD's code, for samplers, I assume it's any `VkWriteDescriptorSet` struct with any value in `VkWriteDescriptorSet::pImageInfo[i].sampler`, even NULL one, which is a 64-bit value of 0 on x64, which doesn't make sense to write in the first place, but validation layers should catch this. They don't currently tho.

**Comment by oddhack** [comment]
VU statements have been added in the 1.1.115 spec update which, hopefully, address this. If so, please close it.

**Comment by procedural** [comment]
> VU statements have been added in the 1.1.115 spec update which, hopefully, address this.

Which ones?

**Comment by procedural** [comment]
https://github.com/KhronosGroup/Vulkan-Docs/commit/57b7cd572d2d9dafdcc18218175d984019c2c092
