### ISSUE TITLE
Expose NEGATIVE_ONE_TO_ONE depth space as an extension

### ISSUE THREAD

**Issue by ReinUsesLisp** [KhronosGroup/Vulkan-Docs#986]
There are some cases where due to backwards compatibility or hardware emulation applications may need to use OpenGL's `[-1, 1]` NDC. I know from [this](https://community.khronos.org/t/1-1-clip-depth-mode-on-vulkan-glclipcontrol/104208) downstream thread that using `[-1, 1]` is not good, sadly I can't change matrices or change the z position in a VTG shader (or fragment depth in that regard) since in some nit-picky cases the change in range makes some depth tests fail.

As background, I'm emulating Maxwell GPUs (Nintendo Switch) and Nvidia GPUs natively support both D3D and Vulkan's `[0, 1]` and OpenGL's `[-1, 1]` depth space, due to this flexibility different games use different modes.

What I'm requesting is to backport OpenGL 4.5 `glClipControl` to Vulkan as an extension (being vendor exclusive or `EXT`). I'd like to highlight again that I *can't* change the depth from matrices (since I don't have control over them) or from shaders (since it changes the precision and value ranges, e.g. when reading from `FragCoord`).

**Comment by jekstrand** [comment]
My first response would be to suggest that you add a bit of shader code in the final geometry stage to apply the required affine transformation to put the depth into the [0, 1] range.  However, going back through your community.khronos.org post, I see that you already tried that and ran into some difficulty.  Could you elaborate a bit more on exactly what's going wrong?

I would expect that uniformly doing `fma(z, 0.5, 0.5)` would result in comparisons coming out the same except that some things would now compare equal which didn't before and vice versa due to truncation caused by adding 0.5.  In particular, values near zero would lose precision.  However, as long as this transform is applied consistently, it shouldn't matter in the vast majority of cases.  In the cases where it does matter, I would expect that simply running on another GPU or driver stack is likely to cause similar problems in which case you're going to have major portability problems.

**Comment by ReinUsesLisp** [comment]
I investigated the particular issue I was having a bit further, the biggest discrepancy starts in a draw call with a large `gl_Position.w` value. This is OpenGL on [-1,1]:
![imagen](https://user-images.githubusercontent.com/26564870/60050377-e0b1d880-96a6-11e9-8830-1d1cb18bf6e8.png)

And Vulkan on [0,1] with `gl_Position.z = fma(gl_Position.z, 0.5f, 0.5f)`:
![imagen](https://user-images.githubusercontent.com/26564870/60050435-fd4e1080-96a6-11e9-9d28-95fb587dd4ed.png)

(As a side note, this is seems to be used to render the background, hence the large coordinates)

Doing `gl_Position.z = (gl_Position.z + 1) / 2` when `gl_Position.z`'s absolute value is greater than 1 won't convert the depth from `[-1,1]` to `[0,1]` since `gl_Position.w` will then divide it, resulting in a large discrepancy (OpenGL gets ~0.99654 and Vulkan ~0.49687).

The solution for now seems to be:
```glsl
gl_Position.z = (gl_Position.z + gl_Position.w) / 0.5f;
```

There are also the cases where a game could read `gl_FragCoord.z` expecting a `[-1,1]` range or write `gl_FragDepth` with a `[-1,1]` but these are kind of easy to workaround.

About precision changes, luckily the particular game where those RenderDoc captures came from uses `less or equal` as depth function and relies on draw order to show what it wants (the depth values are the same).

---

>  In the cases where it does matter, I would expect that simply running on another GPU or driver stack is likely to cause similar problems in which case you're going to have major portability problems.

This would be now theoretical and is not an immediate issue, I might run into issues like this for not using the native depth space since some of the games we have emulate are designed to run on a single hardware vendor. We already ran into similar issues where we had to apply `NoConstraint` (or `precise` in GLSL) on add and multiply operations to tell the compilers to stop using FMA, doing this z-fighting issues.

With the immediate issue out of the way, I still think it's worth considering support for OpenGL's NDC as an extension, for the same but inverted reasons explained in [ARB_clip_control](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_clip_control.txt):

> This extension's goal is to 1) allow OpenGL to effectively match Direct3D's coordinate system
> conventions, and 2) potentially improve the numerical precision of the Z coordinate mapping.

Sometimes lack of precision is what we need, like in the example I described where add and multiply operations being converted to FMA operations generated graphical issues.

**Comment by jekstrand** [comment]
>     gl_Position.z = (gl_Position.z + gl_Position.w) / 0.5f;

Right.  I had also forgotten about `gl_Position.w`.  In light of that, the above does appear to be the correct math.

> This would be now theoretical and is not an immediate issue, I might run into issues like this for not using the native depth space since some of the games we have emulate are designed to run on a single hardware vendor.

Does this mean that this is no longer an immediate issue?  I think that's what you meant but I wanted to confirm for sure.  It doesn't mean that this request will be outright rejected or fall of our (the Vulkan working group) radar but it does lessen the priority.

**Comment by ReinUsesLisp** [comment]
This is no longer an immediate issue.

**Comment by jekstrand** [comment]
Had a bit of discussion internally and we (the Vulkan working group) have no plans to add an extension for this at the moment unless more use-cases or issues come up.

**Comment by sfricke-samsung** [comment]
@ReinUsesLisp - Happy to update [https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_depth_clip_control.html](VK_EXT_depth_clip_control) has been added so now you can use `NEGATIVE_ONE_TO_ONE`

**Comment by pdaniell-nv** [comment]
> @ReinUsesLisp - Happy to update [VK_EXT_depth_clip_control](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_depth_clip_control.html) has been added so now you can use `NEGATIVE_ONE_TO_ONE`

There is a driver implementation [here](https://developer.nvidia.com/vulkan-driver) if you want to try it out.
