### ISSUE TITLE
vkEnumerateInstanceLayerProperties/vkEnumerateDeviceLayerProperties inconsistency over pPropertyCount=0

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#99]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#extended-functionality-layers

vkEnumerateInstanceLayerProperties says:

> * If the value referenced by pPropertyCount is not 0, and pProperties is not NULL, pProperties must be a pointer to an array of pPropertyCount VkLayerProperties structures 

vkEnumerateDeviceLayerProperties says:

> * If pProperties is not NULL, pProperties must be a pointer to an array of pPropertyCount VkLayerProperties structures
> * If pProperties is not NULL, the value referenced by pPropertyCount must be greater than 0 

I don't see any reason for those functions to be different, so it's surprising that they have subtly incompatible requirements. I think they should be changed to have consistent requirements (specifically for pPropertyCount==0 && pProperties!=NULL).

**Comment by courtney-g** [comment]
Agree, they should use the same language. I'll change EnumerateInstanceLayerProperties to matchEnumerateDeviceLayerProperties.

**Comment by philiptaylor** [comment]
Maybe it's worth noting that that'll make code like https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/demos/vulkaninfo.c#L624 invalid (because it calls vkEnumerateInstanceLayerProperties to get count, then unconditionally calls vkEnumerateInstanceLayerProperties again with that count, which is perfectly fine until it gets count==0).

https://github.com/nvpro-samples/gl_vk_chopper/blob/master/VulkanDeviceContext.cpp#L269 does the same pattern with vkEnumerateDeviceLayerProperties so it's already invalid.

I don't know whether it's better to make the spec more tolerant of that case, or just say it's invalid and fix that code and hope nobody else ever does the same. (I know Vulkan intentionally doesn't go out of its way to make the programmer's life easier, but does it really need to be so good at tripping them up in places where performance is irrelevant?)

**Comment by courtney-g** [comment]
You're right. So the first definition is better as it allows pPropertyCount to be zero and existing code works fine.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.6 spec update.
