### ISSUE TITLE
VkStencilFaceFlagBits VK_STENCIL_FRONT_AND_BACK prefix

### ISSUE THREAD

**Issue by ville-h** [KhronosGroup/Vulkan-Docs#991]
The VkStencilFaceFlagBits enumeration's VK_STENCIL_FRONT_AND_BACK enumerator has an inconsistent prefix "VK_STENCIL_". It should be "VK_STENCIL_FACE_" to match with the other enumerators in that specific enumeration, and the general convention used across the specification.

**Comment by oddhack** [comment]
This has been fixed in the 1.1.117 spec update.
